TOP: refactor listado de solicitudes
andes/app pull request #1824
Opened 2020-07-31 16:05 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/TOP-64

### Funcionalidad desarrollada 
1. Refactor de pantalla de listado de solicitudes en base al mockup
2. Cambio en la ruta de nueva solicitud para recibir el paciente
3. Se elimina de la pantalla de nueva solicitud la selección del paciente

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [X] Si --> pendiente
- [ ] No

2020-08-19 16:31 UTC, liquid36 commented
BUILD NUMBER: 1494
TEST START: 2020-08-19T16:31:29.370Z
TOTAL: 298
SUCCESS: 292
FAIL: 4
SKIPPED: 2

2020-09-09 13:21 UTC, plammel requested changes
Habría que rebasear con master para que vuelva a funcionar el filtro por prestaciónes que ahora busca por conceptId.
El header no quedó bien alineado con la tabla
![image](https://user-images.githubusercontent.com/25707055/92603641-ec76c400-f285-11ea-9640-6db0a5830eed.png)

2020-09-09 16:45 UTC, JSantarelli requested changes
El listado con size 'sm' (sin sidebar desplegado) genera algunas superposiciones. En monitores chicos la situación es más evidente (ver item-size-2.png). Propongo mantenerlo en 'md' hasta que ajustemos estos detalles.
![desborde-1](https://user-images.githubusercontent.com/5895886/92627772-38376680-f2a2-11ea-807a-71ac6b6ea5a0.PNG)

![item-size-2](https://user-images.githubusercontent.com/5895886/92628038-9a906700-f2a2-11ea-81e1-0eb6ad02d623.PNG)

Otro punto a mejorar es la altura que se le setea al plex-list (actualmente en 300px). Mi sugerencia es que se utilice una medida relativa al viewport (vh) para no desaprovechar potencial espacio del listado.

2020-09-14 18:20 UTC, plammel commented
> Habría que rebasear con master para que vuelva a funcionar el filtro por prestaciones que ahora busca por conceptId.
> El header no quedó bien alineado con la tabla:
> ![image](https://user-images.githubusercontent.com/25707055/92603641-ec76c400-f285-11ea-9640-6db0a5830eed.png)
.
.
El ancho de los headers no se está ajustando al de las columnas:
![image](https://user-images.githubusercontent.com/25707055/93122835-92b73500-f69d-11ea-9d24-60b952efdc3b.png)

2020-09-16 16:34 UTC, kroce commented
Se va a dividir en PRs mas pequeños.

2020-10-06 17:41 UTC, andrrrl commented on src/app/components/top/solicitudes/detalleSolicitud.html
> +                *ngIf="!prestacionSeleccionada.solicitud.turno && prestacionSeleccionada.estadoActual.tipo !== 'rechazada'">
[Sugerencia] este tipo de if se pueden hacer más legibles con: 
```suggestion
                *ngIf="noRechazada">
                // .ts
                get noRechazada() {
    return !this.prestacionSeleccionada.solicitud.turno && this.prestacionSeleccionada.estadoActual.tipo !== 'rechazada';
}
```

2020-10-06 17:54 UTC, kroce commented
Este PR se está reemplazando por otros. Cuando se termine con el resto se va a cerrar

2020-10-07 12:14 UTC, andrrrl commented
> Este PR se está reemplazando por otros. Cuando se termine con el resto se va a cerrar

Perfecto, la sugerencia (es sólo eso) sirve para los otros PRs :smiley_cat:

2020-10-15 14:17 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [2200](http://condorpiedra.andes.gob.ar:85/2200/mochawesome.html)
CYPRESS RUN: [1382](https://dashboard.cypress.io/projects/xr7gft/runs/1382/specs)
TEST START: 2020-10-15T14:17:07.803Z
TOTAL: 322
SUCCESS: 322
FAIL: 0
SKIPPED: 0

2020-10-15 14:57 UTC, kroce approved these changes

2020-10-15 15:11 UTC, palita1991 approved these changes

2020-10-15 15:20 UTC, JSantarelli approved these changes

2020-10-15 15:25 UTC, merged