RUP: Enviar archivos ajuntos por mail
andes/app pull request #1848
Opened 2020-08-07 18:40 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/RUP-152

### Funcionalidad desarrollada 
1. Se permite seleccionar los adjuntos que serán enviados por mail con el pdf
2. Si se manda un registro aislado, solo se adjuntan si hay relación con el componente adjuntarDocumentoComponent

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1074
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

![image](https://user-images.githubusercontent.com/7090371/89677728-576a5f00-d8c4-11ea-8b25-2c49729acfec.png)

2020-09-30 12:02 UTC, liquid36 commented
BUILD NUMBER: [1995](http://condorpiedra.andes.gob.ar:85/1995/mochawesome.html)
TEST START: 2020-09-30T12:02:15.763Z
TOTAL: 301
SUCCESS: 301
FAIL: -1
SKIPPED: 1

2020-10-04 22:49 UTC, silviroa requested changes

2020-10-04 22:49 UTC, silviroa commented on src/app/modules/rup/components/ejecucion/acciones-envio-informe/acciones-envio-informe.component.ts
> +            registros = registro.relacionadoCon;
Con este control si se elige enviar por email un concepto que contiene un adjunto...  o una molécula que contiene un adjunto no es posible

2020-12-29 12:29 UTC, liquid36 approved these changes

2020-12-29 14:59 UTC, merged