MPI - Refactor visual auditoria
andes/app pull request #1872
Opened 2020-08-25 15:23 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MPI-206
https://proyectos.andes.gob.ar/browse/MPI-207

### Funcionalidad desarrollada 

1. Se unifican pestañas de busqueda principal, vinculaciones y paciestes inactivos. Toda la funcionalidad queda unificada en dos tabs.
2. Se elimina el footer, los botones de acción se re-ubican en la lista de resultados y sidebar.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si  https://github.com/andes/api/pull/1084
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [X] Si   https://github.com/andes/andes-test-integracion/pull/218
- [ ] No

2020-08-31 18:16 UTC, liquid36 commented
BUILD NUMBER: 1624
TEST START: 2020-08-31T18:14:31.921Z
TOTAL: 294
SUCCESS: 169
FAIL: 123
SKIPPED: 2

2020-09-10 14:56 UTC, condorpiedra requested changes

2020-09-10 14:56 UTC, condorpiedra commented on src/app/core/mpi/services/paciente.service.ts
> +    getAuditoriaVinculados(params: any): Observable<IPaciente[]> {
Este servicio no se utiliza

2020-09-10 14:56 UTC, condorpiedra commented on src/app/core/mpi/services/paciente.service.ts
> +    getInactivos(): Observable<IPaciente[]> {
Este servicio no se utiliza

2020-09-10 14:56 UTC, condorpiedra commented on src/app/core/mpi/services/paciente.service.ts
> +        return this.setActivo(paciente, false);
Revisar (no se usa)

2020-09-10 14:56 UTC, condorpiedra commented on src/app/core/mpi/services/paciente.service.ts
> +        return this.setActivo(paciente, true);
Revisar no se usa

2020-09-17 16:10 UTC, MCele commented on src/app/core/mpi/services/paciente.service.ts
> +    getInactivos(): Observable<IPaciente[]> {
borrado!

2020-09-17 16:10 UTC, MCele commented on src/app/core/mpi/services/paciente.service.ts
> +        return this.setActivo(paciente, true);
listo! borrado

2020-09-17 16:10 UTC, MCele commented on src/app/core/mpi/services/paciente.service.ts
> +        return this.setActivo(paciente, false);
ok! Borrado

2020-09-17 16:11 UTC, MCele approved these changes

2020-09-17 16:39 UTC, liquid36 commented
BUILD NUMBER: [1830](http://condorpiedra.andes.gob.ar:85/1830/mochawesome.html)
TEST START: 2020-09-17T16:39:36.164Z
TOTAL: 301
SUCCESS: 299
FAIL: 1
SKIPPED: 1

2020-09-17 17:38 UTC, liquid36 commented
BUILD NUMBER: [1833](http://condorpiedra.andes.gob.ar:85/1833/mochawesome.html)
TEST START: 2020-09-17T17:37:51.364Z
TOTAL: 6
SUCCESS: 6
FAIL: 0
SKIPPED: 0

2020-09-17 18:59 UTC, liquid36 commented
BUILD NUMBER: [1837](http://condorpiedra.andes.gob.ar:85/1837/mochawesome.html)
TEST START: 2020-09-17T18:59:24.885Z
TOTAL: 301
SUCCESS: 301
FAIL: -1
SKIPPED: 1

2020-09-18 11:28 UTC, condorpiedra approved these changes

2020-09-22 12:47 UTC, liquid36 commented
BUILD NUMBER: [1904](http://condorpiedra.andes.gob.ar:85/1904/mochawesome.html)
TEST START: 2020-09-22T12:46:59.558Z
TOTAL: 301
SUCCESS: 301
FAIL: -1
SKIPPED: 1

2020-09-25 11:04 UTC, merged