INTERNACION - Controla la fecha de egreso con el historial de la cama
andes/app pull request #1880
Opened 2020-08-27 17:40 UTC by GaboCancellieri

### Requerimiento
 
No se debería poder egresar un paciente en una fecha en la que la cama este ocupada por otro paciente.

### Funcionalidad desarrollada 

1. Agrega control para determinar la fecha máxima de egreso según el historial de la cama.
2. 
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2020-08-31 15:53 UTC, plammel commented on src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
> +    private subscription4: Subscription;
Qué es `subscription4` ?

2020-09-30 12:08 UTC, silviroa commented
Cuando se egresa un paciente en una fecha posterior a que haya ingresado un nuevo paciente en la cama, pone como de egreso la fecha en la que ingreso el siguiente paciente.
Ejemplo:
23/08 -> ingresa paciente A en la cama 1
20/08 -> ingresa paciente B en la cama 1
29/09 -> se egrese al paciente B de la cama 1 y queda como fecha de egreso 23/08, fecha en la que ingreso el paciente A

2020-09-30 12:17 UTC, silviroa commented
Otro caso para revisar:
23/08 -> ingresa paciente A en la cama 1
24/08 -> muevo al paciente A a la cama 2
vuelvo al mapa de camas al día 23/08 y viendo al paciente A en la cama 1 lo egreso con fecha 26/08 ---- Que un registro de egreso pero el paciente A lo sigo viendo en la cama 2 y no lo puedo mover.
- Aquí habría que verificar que no haya un estado disponible en la cama que lo estoy intentando egresar antes de la fecha de egreso, esto quiere decir que el paciente no esta en esa cama en la fecha seleccionada.

2020-09-30 16:40 UTC, GaboCancellieri commented on src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
> +    private subscription4: Subscription;
Es la subscripción que se hace al buscar el historial de la cama, está en el método checkHistorial

2020-10-05 00:40 UTC, silviroa requested changes

2020-10-05 00:40 UTC, silviroa commented on src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/desocupar-cama.component.ts
> +import { c } from 'bowser';
quitar, sin uso

2020-10-15 15:12 UTC, silviroa approved these changes

2020-10-16 11:19 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [2221](http://condorpiedra.andes.gob.ar:85/2221/mochawesome.html)
CYPRESS RUN: [1403](https://dashboard.cypress.io/projects/xr7gft/runs/1403/specs)
TEST START: 2020-10-16T11:18:53.876Z
TOTAL: 322
SUCCESS: 322
FAIL: 0
SKIPPED: 0

2020-10-19 13:56 UTC, liquid36 requested changes
Me lanzo el alert de fecha maxima pero aún así pude egresar al paciente.

2020-10-19 14:05 UTC, GaboCancellieri commented
> Me lanzo el alert de fecha maxima pero aún así pude egresar al paciente.
Claro, la idea es avisar al usuario que la fecha elegida excede la fecha máxima y que el egreso se va a ajustar a esta última.

2020-10-19 14:14 UTC, liquid36 commented
Ok, no quedo muy claro que la fecha cambio, pero no se rompio todo. :+1:

2020-10-19 14:14 UTC, liquid36 approved these changes

2020-10-21 13:30 UTC, merged