MPI - Nuevo campo 'hora de nacimiento'
andes/app pull request #1891
Opened 2020-09-02 17:07 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MPI-212

### Funcionalidad desarrollada 

1. Corrige visualización de fecha/hora de nacimiento que se encontraban 'desincronizadas' en distintas vistas
2. Nuevo campo en formulario de alta de bebé para ingresar hora de nacimiento

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2020-09-10 18:31 UTC, condorpiedra requested changes

2020-09-10 18:31 UTC, condorpiedra commented on src/app/modules/mpi/components/paciente-panel.component.ts
> +    set paciente(value: IPaciente) {
Para que sirve este control?

2020-09-15 18:30 UTC, condorpiedra approved these changes

2020-09-16 12:40 UTC, liquid36 commented
BUILD NUMBER: [1812](http://condorpiedra.andes.gob.ar:85/1812/mochawesome.html)
TEST START: 2020-09-16T12:40:18.153Z
TOTAL: 297
SUCCESS: 295
FAIL: 1
SKIPPED: 1

2020-09-16 13:02 UTC, MCele approved these changes

2020-09-16 13:15 UTC, liquid36 commented
BUILD NUMBER: [1813](http://condorpiedra.andes.gob.ar:85/1813/mochawesome.html)
TEST START: 2020-09-16T13:06:30.243Z
TOTAL: 210
SUCCESS: 189
FAIL: 21
SKIPPED: 0

2020-09-16 13:55 UTC, liquid36 commented
BUILD NUMBER: [1815](http://condorpiedra.andes.gob.ar:85/1815/mochawesome.html)
TEST START: 2020-09-16T13:55:31.663Z
TOTAL: 279
SUCCESS: 278
FAIL: 1
SKIPPED: 0

2020-09-16 14:05 UTC, liquid36 commented
BUILD NUMBER: [1816](http://condorpiedra.andes.gob.ar:85/1816/mochawesome.html)
TEST START: 2020-09-16T14:03:58.194Z
TOTAL: 19
SUCCESS: 19
FAIL: -1
SKIPPED: 1

2020-09-16 17:13 UTC, liquid36 commented
BUILD NUMBER: [1819](http://condorpiedra.andes.gob.ar:85/1819/mochawesome.html)
TEST START: 2020-09-16T17:13:08.746Z
TOTAL: 297
SUCCESS: 297
FAIL: -1
SKIPPED: 1

2020-09-16 17:38 UTC, merged