RUP: posibilidad de registrar conceptos repetidos en una prestación
andes/app pull request #1895
Opened 2020-09-03 14:03 UTC by juuliotero

### Requerimiento 
https://proyectos.andes.gob.ar/browse/RUP-179

### Funcionalidad desarrollada 
1. En la ejecución de una prestación, si el concepto a registrar está repetido se chequea si el elementoRUP asociado permite repetidos.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2020-09-06 23:14 UTC, silviroa requested changes

2020-09-06 23:14 UTC, silviroa commented on src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
> +                if (!elemento.permiteRepetidos) {
Los elementosRUP están cargados en memoria... es posible usar el método "elementosRUPService.buscarElemento(concepto, esSolicitud)" y no ir a la api a buscarlo.

2020-09-06 23:14 UTC, silviroa commented on src/app/modules/rup/interfaces/elementoRUP.interface.ts
> +    permiteRepetidos: Boolean;
el campo o es opcional (?) o hay que hacer un script para actualizar los elementos existentes con el campo en false (valor por defecto)

2020-09-08 15:56 UTC, juuliotero commented on src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
> +                if (!elemento.permiteRepetidos) {
Modificado

2020-09-08 15:56 UTC, juuliotero commented on src/app/modules/rup/interfaces/elementoRUP.interface.ts
> +    permiteRepetidos: Boolean;
Se opta por dejarlo opcional

2020-09-29 17:41 UTC, liquid36 commented
BUILD NUMBER: [1987](http://condorpiedra.andes.gob.ar:85/1987/mochawesome.html)
TEST START: 2020-09-29T17:41:42.214Z
TOTAL: 301
SUCCESS: 299
FAIL: 1
SKIPPED: 1

2020-10-01 15:27 UTC, liquid36 commented
BUILD NUMBER: [2017](http://condorpiedra.andes.gob.ar:85/2017/mochawesome.html)
TEST START: 2020-10-01T15:27:43.621Z
TOTAL: 301
SUCCESS: 300
FAIL: 0
SKIPPED: 1

2020-10-01 16:30 UTC, palita1991 approved these changes

2020-10-02 15:15 UTC, liquid36 commented
BUILD NUMBER: [2034](http://condorpiedra.andes.gob.ar:85/2034/mochawesome.html)
TEST START: 2020-10-02T15:15:01.771Z
TOTAL: 311
SUCCESS: 311
FAIL: 0
SKIPPED: 0

2020-10-02 16:28 UTC, liquid36 commented
BUILD NUMBER: [2036](http://condorpiedra.andes.gob.ar:85/2036/mochawesome.html)
TEST START: 2020-10-02T16:28:12.589Z
TOTAL: 312
SUCCESS: 312
FAIL: 0
SKIPPED: 0

2020-10-05 11:00 UTC, merged