feat(RUP):buscador, mostrar fsn cuando no coicide con el term.(RUP-182)
andes/app pull request #1896
Opened 2020-09-04 12:12 UTC by waltergarrido

### Requerimiento
 
mostrar fsn cuando no coicide con el term
### Funcionalidad desarrollada 

1. Comparar el fsn sin semantic tags con el term. Si no coiciden mostrar en un segundo renglón el FSN. 
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2020-09-04 12:37 UTC, liquid36 requested changes
Fiajte que se mezclan algunas definiciones. Si buscas fiebre y empezas a scrollear.

Eso es porque vos pusiste el calculo en el ngOnit y hay un truco de angular que reutiliza compónentes (para mejorar performance). Deberías poner el calculo en el ` ngOnChanges`.

Ademas a tener en cuenta, esta todo atrapado en el link. Que el link afecte al primer termino.  y Si vas a la pestaña frecuentes el numerito queda abajo de todo. Por ahí te combie armar una nueva componente para resolver esto. 

![image](https://user-images.githubusercontent.com/3813270/92239986-40526900-ee92-11ea-872d-191afb0c34e1.png)

2020-09-10 18:26 UTC, liquid36 approved these changes

2020-09-10 18:34 UTC, liquid36 approved these changes

2020-09-21 14:05 UTC, palita1991 approved these changes

2020-09-21 14:25 UTC, liquid36 commented
BUILD NUMBER: [1874](http://condorpiedra.andes.gob.ar:85/1874/mochawesome.html)
TEST START: 2020-09-21T14:25:34.158Z
TOTAL: 297
SUCCESS: 297
FAIL: -1
SKIPPED: 1

2020-09-22 15:51 UTC, merged