Dashboard HUDS: mejora en filtro de prestaciones
andes/app pull request #1898
Opened 2020-09-07 12:38 UTC by martinebucarey

### Requerimiento
https://proyectos.andes.gob.ar/browse/BI-37

### Funcionalidad desarrollada 

1. Se modifica el llamado a _snomedService_ por el de _conceptosTurneablesService_ para que traiga todos los conceptos turneables que están en la base de datos.
2. Se corrige linteo.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2020-09-07 15:28 UTC, plammel approved these changes

2020-09-07 16:11 UTC, palita1991 requested changes
Cuando se selecciona ecografía y le haces click a "Filtrar" sale lo siguiente por consola
![image](https://user-images.githubusercontent.com/30004190/92405240-91b95d00-f10b-11ea-9f27-f75be80d36d6.png)

2020-09-17 13:51 UTC, liquid36 commented
BUILD NUMBER: [1825](http://condorpiedra.andes.gob.ar:85/1825/mochawesome.html)
TEST START: 2020-09-17T13:50:48.731Z
TOTAL: 297
SUCCESS: 297
FAIL: -1
SKIPPED: 1

2020-09-17 14:12 UTC, palita1991 approved these changes

2020-09-18 17:47 UTC, merged