Punto inicio ANDES
andes/app pull request #1901
Opened 2020-09-08 17:24 UTC by andrrrl

### Requerimiento
Refactor visual

### Funcionalidad desarrollada 
1. 
2. 
3. 

### UserStory llegó a completarse
- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos
- [X] Si
- [ ] No

### Requiere actualizaciones en la API
- [X] Si ==> en espera PR
- [ ] No

### Requiere actualizaciones en andes-test-integracion
- [X] Si
- [ ] No

2020-09-08 17:42 UTC, liquid36 commented
BUILD NUMBER: 1716
TEST START: 2020-09-08T17:42:12.715Z
TOTAL: 297
SUCCESS: 284
FAIL: 9
SKIPPED: 4

2020-09-11 11:11 UTC, liquid36 requested changes
cuando llegue la api sigo revisando.

2020-09-11 11:11 UTC, liquid36 commented on src/app/components/inicio/inicio.scss
> +    .neuquen {
Esta clase es dinamica o no? Porque la asignaste un un archivo que puede cambiar. Pero no veo como San Juan sin tocar el código puede customizar esta parte de la visualización. ¿Que trataste de hacer acá?

2020-09-11 11:11 UTC, liquid36 commented on src/app/components/inicio/inicio.scss
> +header {
header o .logo-container? Se dificulta mucho leer todo. Agrupa todo el estilo del componente.

2020-09-11 11:11 UTC, liquid36 commented on src/app/components/inicio/inicio.scss
> +        .bienvenida {
En algunos lugares usan w-100 y en otros lugares crean clases especiales. ¿Cual es el parámetro ?

2020-09-11 11:11 UTC, liquid36 commented on src/app/components/inicio/inicio.scss
> +        color: $andes-azul-claro;
acá estimo que quisiste usar la custom propierties --nav-bar-color, que es la propieda que configura san juan desde un archivo de configuración.

2020-09-11 11:11 UTC, liquid36 commented on src/app/components/inicio/inicio.scss
> +        color: $andes-azul-claro;
Sino se esta perdiendo esa feature.

2020-09-11 11:11 UTC, liquid36 commented on src/app/components/inicio/inicio.scss
> +        fill: $andes-azul-oscuro;
Atento acá, antes se usaba una custom properties

2020-09-11 11:11 UTC, liquid36 commented on src/app/components/inicio/inicio.scss
> +.bienvenida {
Esto esta dos veces. Poner todo en un solo lugar.

2020-09-11 19:14 UTC, andrrrl commented on src/app/components/inicio/inicio.html
> +                                <div class="submodulo {{submodulo.class}} hover" [style.background]="submodulo.color"
Color! jaja

2020-09-18 15:29 UTC, liquid36 commented
BUILD NUMBER: [1851](http://condorpiedra.andes.gob.ar:85/1851/mochawesome.html)
TEST START: 2020-09-18T15:28:45.881Z
TOTAL: 297
SUCCESS: 294
FAIL: 2
SKIPPED: 1

2020-09-22 18:07 UTC, liquid36 commented
BUILD NUMBER: [1915](http://condorpiedra.andes.gob.ar:85/1915/mochawesome.html)
TEST START: 2020-09-22T18:07:08.165Z
TOTAL: 298
SUCCESS: 298
FAIL: -1
SKIPPED: 1

2020-09-25 16:53 UTC, andrrrl commented on src/app/components/inicio/inicio.scss
> +.bienvenida {
una está anidada en .size-sm y .size-md

2020-09-29 12:00 UTC, andrrrl commented
> cuando llegue la api sigo revisando.

Che también mirá la versión responsive, gracias!

2020-10-08 13:12 UTC, juuliotero commented
Mi usuario no tiene permisos para Campañas de Salud pero puedo ver el ícono en el inicio. Al hacer click me vuelve al inicio.

![image](https://user-images.githubusercontent.com/7090371/95462863-716d0000-094e-11eb-8213-9586a89fdfe8.png)

![image](https://user-images.githubusercontent.com/7090371/95463075-b85af580-094e-11eb-8569-0d47363ad666.png)

2020-10-08 13:16 UTC, andrrrl commented
> Mi usuario no tiene permisos para Campañas de Salud pero puedo ver el ícono en el inicio. Al hacer click me vuelve al inicio.
Revisando, gracias!

2020-10-08 17:19 UTC, andrrrl commented
> > Mi usuario no tiene permisos para Campañas de Salud pero puedo ver el ícono en el inicio. Al hacer click me vuelve al inicio.
> 
> Revisando, gracias!

Revisado!

2020-10-14 12:15 UTC, liquid36 commented
USUARIO: avelazquez  
BUILD NUMBER: [2182](http://condorpiedra.andes.gob.ar:85/2182/mochawesome.html)
CYPRESS RUN: [1368](https://dashboard.cypress.io/projects/xr7gft/runs/1368/specs)
TEST START: 2020-10-14T12:15:04.156Z
TOTAL: 322
SUCCESS: 319
FAIL: 3
SKIPPED: 0

2020-10-14 12:46 UTC, liquid36 commented
USUARIO: avelazquez  
BUILD NUMBER: [2183](http://condorpiedra.andes.gob.ar:85/2183/mochawesome.html)
CYPRESS RUN: [1369](https://dashboard.cypress.io/projects/xr7gft/runs/1369/specs)
TEST START: 2020-10-14T12:46:41.486Z
TOTAL: 323
SUCCESS: 323
FAIL: 0
SKIPPED: 0

2020-10-15 16:56 UTC, liquid36 commented
USUARIO: avelazquez  
BUILD NUMBER: [2205](http://condorpiedra.andes.gob.ar:85/2205/mochawesome.html)
CYPRESS RUN: [1387](https://dashboard.cypress.io/projects/xr7gft/runs/1387/specs)
TEST START: 2020-10-15T16:56:15.142Z
TOTAL: 323
SUCCESS: 323
FAIL: 0
SKIPPED: 0

2020-10-16 12:14 UTC, liquid36 reviewed
Las novedades no se pueden enviar a las submodulos que es lo que realmente importa. Ejemplo MPI y Auditoria.

2020-10-16 17:04 UTC, liquid36 commented
USUARIO: avelazquez  
BUILD NUMBER: [2232](http://condorpiedra.andes.gob.ar:85/2232/mochawesome.html)
CYPRESS RUN: [1412](https://dashboard.cypress.io/projects/xr7gft/runs/1412/specs)
TEST START: 2020-10-16T17:04:14.196Z
TOTAL: 323
SUCCESS: 323
FAIL: 0
SKIPPED: 0

2020-10-21 12:53 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [2294](http://condorpiedra.andes.gob.ar:85/2294/mochawesome.html)
CYPRESS RUN: [1464](https://dashboard.cypress.io/projects/xr7gft/runs/1464/specs)
TEST START: 2020-10-21T12:53:06.562Z
TOTAL: 324
SUCCESS: 324
FAIL: 0
SKIPPED: 0

2020-10-21 15:32 UTC, kroce approved these changes

2020-10-21 15:32 UTC, palita1991 approved these changes

2020-10-21 15:41 UTC, merged