feat(rup): componente receta médica
andes/app pull request #1905
Opened 2020-09-11 12:31 UTC by juuliotero

### Requerimiento 
https://proyectos.andes.gob.ar/browse/RUP-180

### Funcionalidad desarrollada 
1. Se crea un nuevo componente RUP RecetaMedicaComponent

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [X] Si https://gist.github.com/juuliotero/e02eeeb7129c5540f0e0dc2e5971448d
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

![image](https://user-images.githubusercontent.com/7090371/92925731-4fe12d00-f411-11ea-991e-905a7ac5d4bf.png)

2020-09-15 02:45 UTC, liquid36 requested changes
Van comentarios de mejoras. La query que están usando no hace lo que piensan. Mañana charlamos al respecto.

2020-09-15 02:45 UTC, liquid36 commented on src/app/modules/rup/components/elementos/recetaMedica.component.ts
> +            this.snomedService.get(queryPresentacion).subscribe(resultado => {
Estas dos se pueden "paralelizar" con forkJoin.

2020-09-15 02:45 UTC, liquid36 commented on src/app/modules/rup/components/elementos/recetaMedica.component.ts
> +        if (this.medicamento.generico && this.medicamento.presentacion && this.medicamento.unidades && this.medicamento.cantidad > 0) {
Para todo esto se podría haber usado un <form> que te valide los campos pero es un detalle.

2020-09-16 10:51 UTC, liquid36 commented
Acordarse de hacer la parte de impresión en la API.

2020-09-25 18:31 UTC, juuliotero commented on src/app/modules/rup/components/elementos/recetaMedica.component.ts
> +            this.snomedService.get(queryPresentacion).subscribe(resultado => {
listo

2020-09-25 18:38 UTC, juuliotero commented on src/app/modules/rup/components/elementos/recetaMedica.component.ts
> +        if (this.medicamento.generico && this.medicamento.presentacion && this.medicamento.unidades && this.medicamento.cantidad > 0) {
un form? estuve probando pero por algún motivo siempre pasa como válido.

2020-09-30 15:12 UTC, liquid36 commented
BUILD NUMBER: [2003](http://condorpiedra.andes.gob.ar:85/2003/mochawesome.html)
TEST START: 2020-09-30T15:11:50.886Z
TOTAL: 301
SUCCESS: 301
FAIL: -1
SKIPPED: 1

2020-11-11 13:05 UTC, juuliotero commented
> Acordarse de hacer la parte de impresión en la API.

listo

2020-11-12 12:53 UTC, kroce requested changes

2020-11-12 12:53 UTC, kroce commented on src/app/modules/rup/components/elementos/recetaMedica.component.ts
> +            ).subscribe(([resultado, presentaciones]) => {
```suggestion
            forkJoin([this.snomedService.get(queryPresentacion), this.snomedService.get(queryUnidades)]).
            subscribe(([resultado, presentaciones]) => {
```

2020-11-12 12:54 UTC, kroce commented on src/app/modules/rup/components/elementos/recetaMedica.component.ts
> +            ).subscribe(([resultado, presentaciones]) => {
El forkjoin como lo estabas usando aparece como deprecado

2020-11-12 14:33 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [2585](http://condorpiedra.andes.gob.ar:85/2585/mochawesome.html)
CYPRESS RUN: [1744](https://dashboard.cypress.io/projects/xr7gft/runs/1744/specs)
TEST START: 2020-11-12T14:33:31.488Z
TOTAL: 336
SUCCESS: 336
FAIL: 0
SKIPPED: 0

2020-11-12 14:35 UTC, kroce approved these changes

2020-11-12 14:35 UTC, kroce commented on src/app/modules/rup/components/elementos/recetaMedica.component.ts
> +    }
eliminado

2020-11-12 15:36 UTC, palita1991 approved these changes

2020-11-13 11:12 UTC, merged