HUDS: rutas separadas de rup para huds
andes/app pull request #1908
Opened 2020-09-15 18:28 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/HUDS-24
https://proyectos.andes.gob.ar/browse/HUDS-27

### Funcionalidad desarrollada 

1. Desacoplar la página principal de la HUDS de RUP
2. Se crea un nuevo módulo para HUDS dentro de rup
3. Se acomodan las rutas que dirigen a huds en la app
4. Se arregla la redirección desde vistaHUDS en el volver

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [X] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2020-09-16 12:15 UTC, liquid36 commented
BUILD NUMBER: [1811](http://condorpiedra.andes.gob.ar:85/1811/mochawesome.html)
TEST START: 2020-09-16T12:14:54.558Z
TOTAL: 297
SUCCESS: 297
FAIL: -1
SKIPPED: 1

2020-09-16 14:38 UTC, palita1991 approved these changes

2020-09-17 11:54 UTC, liquid36 requested changes

2020-09-17 11:54 UTC, liquid36 commented on src/app/modules/rup/rup.routing.ts
>      { path: 'huds', component: HudsBusquedaPacienteComponent },
Esta ruta también hay que borrar, y al hacerlo te vas a dar cuenta que hay que cambiar el ruteo de los módulos y el botón "VER HUDS" del punto de inicio.

2020-09-17 11:55 UTC, liquid36 commented on src/app/modules/rup/rup.routing.ts
>      { path: 'huds', component: HudsBusquedaPacienteComponent },
En la colección módulos HUDS esta apuntando a 'rup/huds'

2020-09-17 12:08 UTC, liquid36 requested changes

2020-09-17 12:08 UTC, liquid36 commented on src/app/modules/rup/huds.module.ts
> +    declarations: [
Lo que esta vacío hace limpieza de código.

2020-09-17 13:34 UTC, juuliotero commented on src/app/modules/rup/rup.routing.ts
>      { path: 'huds', component: HudsBusquedaPacienteComponent },
Hay un script asociado que actualiza módulos

2020-09-21 11:35 UTC, juuliotero commented on src/app/modules/rup/huds.module.ts
> +    declarations: [
listo

2020-09-21 11:36 UTC, juuliotero commented on src/app/modules/rup/rup.routing.ts
>      { path: 'huds', component: HudsBusquedaPacienteComponent },
queda corregido lo de la ruta

2020-09-21 12:09 UTC, liquid36 approved these changes

2020-09-22 11:38 UTC, liquid36 commented
BUILD NUMBER: [1903](http://condorpiedra.andes.gob.ar:85/1903/mochawesome.html)
TEST START: 2020-09-22T11:38:19.746Z
TOTAL: 297
SUCCESS: 297
FAIL: -1
SKIPPED: 1

2020-09-22 15:44 UTC, merged