GDU): actualiza control de permisos de GDU
andes/app pull request #1912
Opened 2020-09-16 15:51 UTC by plammel

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/MPI-229
### Funcionalidad desarrollada 

1. actualiza control de permisos de GDU a `usuarios:perfiles`
2. 
3. 

### UserStory llegó a completarse

- [ ] Si https://proyectos.andes.gob.ar/browse/MPI-229
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2020-09-16 17:24 UTC, liquid36 commented
BUILD NUMBER: [1820](http://condorpiedra.andes.gob.ar:85/1820/mochawesome.html)
TEST START: 2020-09-16T17:24:18.583Z
TOTAL: 297
SUCCESS: 297
FAIL: -1
SKIPPED: 1

2020-09-16 17:28 UTC, palita1991 approved these changes

2020-09-17 11:22 UTC, kroce requested changes
El requerimiento mencionado no corresponde

2020-09-17 11:43 UTC, plammel commented
> El requerimiento mencionado no corresponde

Actualizado!

2020-09-22 14:03 UTC, kroce requested changes
Al cargar un nuevo perfil salta un error en consola
![image](https://user-images.githubusercontent.com/18030170/93892757-41bdc700-fcc3-11ea-8d96-7f4569135700.png)

2020-09-22 14:12 UTC, plammel commented
> Al cargar un nuevo perfil salta un error en consola
> ![image](https://user-images.githubusercontent.com/18030170/93892757-41bdc700-fcc3-11ea-8d96-7f4569135700.png)

El error es preexistente a estos cambios:
![image](https://user-images.githubusercontent.com/25707055/93893770-69615f00-fcc4-11ea-87ad-624bc4d3ca4d.png)
Se generó un nuevo ticket para hacer seguimiendo al mismo: https://proyectos.andes.gob.ar/browse/GDU-26

2020-09-23 12:39 UTC, kroce approved these changes

2020-09-23 12:59 UTC, palita1991 approved these changes

2020-09-23 13:01 UTC, merged