feat(TOP): refactor visual en busqueda de paciente
andes/app pull request #1913
Opened 2020-09-16 17:55 UTC by kroce

### Requerimiento
Resuelve parte de los requerimientos de https://proyectos.andes.gob.ar/browse/TOP-64

### Funcionalidad desarrollada 

1. Se agrega la búsqueda de pacientes dentro de solicitudes
2. Se cambia el sidebar por invert
3. Se agregan rutas propias de TOP

### UserStory llegó a completarse

- [ ] Si
- [x] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2020-09-16 18:07 UTC, liquid36 commented
BUILD NUMBER: [1821](http://condorpiedra.andes.gob.ar:85/1821/mochawesome.html)
TEST START: 2020-09-16T18:07:18.977Z
TOTAL: 297
SUCCESS: 297
FAIL: -1
SKIPPED: 1

2020-09-17 12:08 UTC, plammel approved these changes

2020-09-17 12:20 UTC, liquid36 requested changes

2020-09-17 12:20 UTC, liquid36 commented on src/app/components/top/top.module.ts
>  @NgModule({
Este es el módulo compartido para otros módulos. 
Todo lo interno de TOP agregalo en el TOPRouting y hacele lazy load como tiene rup, internación y otros.

2020-09-17 12:20 UTC, liquid36 commented on src/app/components/top/top.routing.ts
> +    { path: 'solicitudes/:tipo/:paciente', component: NuevaSolicitudComponent },
Tené en cuenta que la ruta vieja sigue existiendo .

2020-09-17 12:20 UTC, liquid36 commented on src/app/components/top/solicitudes/nuevaSolicitud.component.ts
> +                    let promise = this.plex.wizard({
Me parece un buen momento para volar este wizard. Agregar un help o hitn o esos chiches que le gusta a la gente de UI/UX. jajaja

2020-09-17 12:20 UTC, liquid36 commented on src/app/components/top/solicitudes/nuevaSolicitud.component.ts
> +                this.plex.info('warning', 'Intente nuevamente', 'Error en la búsqueda de paciente');
```suggestion
                this.plex.info('danger', 'Intente nuevamente', 'Error en la búsqueda de paciente');
```

Acá hay que volver a la pantalla anterior, alguien hizo trampa y cambio la URL. O se rompio MPI xd

2020-09-17 12:20 UTC, liquid36 commented on src/app/components/top/solicitudes/nuevaSolicitud.component.ts
>          this.route.params.subscribe(params => {
unsubscribe le falta a esto

2020-09-17 12:20 UTC, liquid36 commented on src/app/components/top/solicitudes/nuevaSolicitud.component.ts
>      @HostBinding('class.plex-layout') layout = true;
Si usa plex-layout esto no va más.

2020-09-17 16:31 UTC, kroce commented on src/app/components/top/solicitudes/busquedaPaciente.component.ts
> +    selector: 'busqueda-paciente',
listo

2020-09-17 16:31 UTC, kroce commented on src/app/components/top/top.module.ts
>  @NgModule({
listo

2020-09-17 16:31 UTC, kroce commented on src/app/components/top/solicitudes/nuevaSolicitud.component.ts
> +                    let promise = this.plex.wizard({
volado el wizard. Agregado hint

2020-09-17 16:31 UTC, kroce commented on src/app/components/top/solicitudes/nuevaSolicitud.component.ts
> +                this.plex.info('warning', 'Intente nuevamente', 'Error en la búsqueda de paciente');
done

2020-09-17 16:31 UTC, kroce commented on src/app/components/top/solicitudes/nuevaSolicitud.component.ts
>          this.route.params.subscribe(params => {
done

2020-09-17 16:31 UTC, kroce commented on src/app/components/top/solicitudes/nuevaSolicitud.component.ts
>      @HostBinding('class.plex-layout') layout = true;
done

2020-09-17 16:56 UTC, liquid36 commented
BUILD NUMBER: [1831](http://condorpiedra.andes.gob.ar:85/1831/mochawesome.html)
TEST START: 2020-09-17T16:52:17.117Z
TOTAL: 291
SUCCESS: 282
FAIL: 8
SKIPPED: 1

2020-09-17 18:07 UTC, liquid36 commented
BUILD NUMBER: [1834](http://condorpiedra.andes.gob.ar:85/1834/mochawesome.html)
TEST START: 2020-09-17T18:07:33.880Z
TOTAL: 297
SUCCESS: 286
FAIL: 10
SKIPPED: 1

2020-09-17 18:33 UTC, liquid36 commented
BUILD NUMBER: [1835](http://condorpiedra.andes.gob.ar:85/1835/mochawesome.html)
TEST START: 2020-09-17T18:33:32.148Z
TOTAL: 297
SUCCESS: 297
FAIL: -1
SKIPPED: 1

2020-09-17 19:32 UTC, liquid36 commented
BUILD NUMBER: [1840](http://condorpiedra.andes.gob.ar:85/1840/mochawesome.html)
TEST START: 2020-09-17T19:31:49.211Z
TOTAL: 297
SUCCESS: 296
FAIL: 0
SKIPPED: 1

2020-09-17 19:55 UTC, liquid36 commented
BUILD NUMBER: [1841](http://condorpiedra.andes.gob.ar:85/1841/mochawesome.html)
TEST START: 2020-09-17T19:54:54.563Z
TOTAL: 297
SUCCESS: 297
FAIL: -1
SKIPPED: 1

2020-09-18 10:45 UTC, liquid36 approved these changes

2020-09-18 13:02 UTC, palita1991 approved these changes

2020-09-18 13:03 UTC, merged