GDU: permisos unidades organizativas de internacion
andes/app pull request #1914
Opened 2020-09-16 18:47 UTC by plammel

### Requerimiento
 
https://github.com/andes/api/pull/1109
### Funcionalidad desarrollada 

1. Incluye tipo de `unidad-organizativa` en `arbol-permisos-item`
2. 
3. 

### UserStory llegó a completarse

- [ ] Si https://github.com/andes/api/pull/1109
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2020-09-17 16:27 UTC, liquid36 commented
BUILD NUMBER: [1829](http://condorpiedra.andes.gob.ar:85/1829/mochawesome.html)
TEST START: 2020-09-17T16:27:40.368Z
TOTAL: 297
SUCCESS: 289
FAIL: 7
SKIPPED: 1

2020-09-18 19:16 UTC, liquid36 commented
BUILD NUMBER: [1862](http://condorpiedra.andes.gob.ar:85/1862/mochawesome.html)
TEST START: 2020-09-18T19:16:11.002Z
TOTAL: 297
SUCCESS: 291
FAIL: 5
SKIPPED: 1

2020-09-21 14:56 UTC, liquid36 commented
BUILD NUMBER: [1875](http://condorpiedra.andes.gob.ar:85/1875/mochawesome.html)
TEST START: 2020-09-21T14:56:33.052Z
TOTAL: 297
SUCCESS: 297
FAIL: -1
SKIPPED: 1

2020-09-24 18:32 UTC, palita1991 requested changes
En un efector donde ya tenía permisos para internación, le quise agregar permisos para una unidad organizativa y al guardar sale este cartel. También para aquellos efectores donde no tenia permisos para internación, le quise agregar y me salió el mismo cartel. El caso pasó también al no agregar ninguna unidad organizativa y poner guardar.
![image](https://user-images.githubusercontent.com/30004190/94184590-85a6fc80-fe7a-11ea-995e-b1aa466325c2.png)

![image](https://user-images.githubusercontent.com/30004190/94184824-dcacd180-fe7a-11ea-86f5-ffd71ad6e7ad.png)

2020-09-25 18:32 UTC, palita1991 commented
> @plammel
> En un efector donde ya tenía permisos para internación, le quise agregar permisos para una unidad organizativa y al guardar sale este cartel. También para aquellos efectores donde no tenia permisos para internación, le quise agregar y me salió el mismo cartel. El caso pasó también al no agregar ninguna unidad organizativa y poner guardar.
> ![image](https://user-images.githubusercontent.com/30004190/94184590-85a6fc80-fe7a-11ea-995e-b1aa466325c2.png)
> 
> ![image](https://user-images.githubusercontent.com/30004190/94184824-dcacd180-fe7a-11ea-86f5-ffd71ad6e7ad.png)

Error en mi  BD local, se vuelve a revisar

2020-10-01 13:57 UTC, liquid36 requested changes

2020-10-01 13:57 UTC, liquid36 commented on src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos.component.ts
> +            this.organizacionService.unidadesOrganizativas(this.organizacionId).subscribe((data) => {
Hay que mantener consistencia en todos los select. El GET de unidades organizativas debe ocurrir dentro de `arbol-permisos-item` tal cual ocurre con el GET de prestaciones y organización.
No escala crear un argumento por tipo de datos que necesitemos.

2020-10-01 14:23 UTC, liquid36 commented
Ver como se resolvio en este PR : https://github.com/andes/app/pull/1920

2020-10-06 11:54 UTC, juuliotero requested changes

2020-10-06 11:54 UTC, juuliotero commented on src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.ts
> +                            case 'unidad-organizativa':
Cómo dijo marian, habría que traerse las unidades organizativas acá, y no leerlas del input para que sea consistente con los otros

2020-10-06 11:54 UTC, juuliotero commented
@plammel tiene conflictos

2020-10-07 16:25 UTC, liquid36 approved these changes

2020-10-08 16:34 UTC, palita1991 requested changes
Estando en la organización A le agrego unidades organizativas al usuario, el cambiarme a la Organización B, y agregarle unidades organizativas de ese efector cuando vuelvo a la organización A no se visualizan las que había cargado en un principio.
https://www.loom.com/share/1475063c5925461796ab5fa435036c52

2020-10-08 18:41 UTC, liquid36 commented
Reparado @palita1991

2020-10-09 12:21 UTC, juuliotero commented on src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.ts
> +    @Input() unidadesOrganizativas = [];
Quedó esté input pero nunca se recibe

2020-10-09 13:04 UTC, juuliotero approved these changes

2020-10-09 13:43 UTC, merged