COM: nuevo módulo centro operativo médico
andes/app pull request #1926
Opened 2020-09-25 13:58 UTC by juuliotero

### Requerimiento 
https://proyectos.andes.gob.ar/browse/COM-3

### Funcionalidad desarrollada 
1. Nuevo módulo _Centro Operativo Médico_

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [X] Si
- [ ] No

Crear nueva colección _reglasDerivación_ y correr:
https://gist.github.com/juuliotero/6d7a90f08269f4d650f6e79f72557875
https://gist.github.com/juuliotero/8b477da2bf01783d658ba8f06d7ca8ec

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1122
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2020-09-28 20:46 UTC, sychus reviewed
Algunos detalles que faltarían:
1) Poder adjuntar documentos por cada movimiento (optativo) pero q esté la posibilidad.
2) Poder cancelar la solicitud de derivación en origen (antes que intervenga el COM), luego ya no debería ser posible.

2020-09-29 14:29 UTC, palita1991 requested changes
@juuliotero  en DERIVACIONES SOLICITADAS el filtro de **Organización destino** no filtra
https://www.loom.com/share/ecaa79f2ae21477ca19b37cbb88bcc05

2020-09-30 14:04 UTC, juuliotero commented on projects/shared/src/lib/components/popover-audit/popover-audit.component.ts
>  import * as moment from 'moment';
Ya se pueden adjuntar archivos en movimientos y cancelar derivaciones pendientes (solo el efector que las generó)

2020-09-30 14:04 UTC, juuliotero commented
> @juuliotero en DERIVACIONES SOLICITADAS el filtro de **Organización destino** no filtra
> 
> https://www.loom.com/share/ecaa79f2ae21477ca19b37cbb88bcc05

Quedó arreglado

2020-09-30 19:32 UTC, sychus approved these changes
joya.. nos quedaría pegarle una buena testeada!

2020-10-01 14:23 UTC, kroce requested changes
Al cancelar una derivación , esta desaparece pero quedan los datos en el sidebar

2020-10-01 17:59 UTC, juuliotero commented
> Al cancelar una derivación , esta desaparece pero quedan los datos en el sidebar

Listo!

2020-10-02 11:55 UTC, kroce approved these changes

2020-10-02 12:26 UTC, JSantarelli submitted a review, later dismissed
Sugiero que el botón "guardar" permanezca en 'disable' hasta que que los campos requeridos del formulario estén completos. 
![guardar-disable](https://user-images.githubusercontent.com/5895886/94922846-48052d80-0491-11eb-879b-47cdba8fe1fd.PNG)

2020-10-02 12:53 UTC, palita1991 approved these changes

2020-10-02 13:14 UTC, liquid36 commented
BUILD NUMBER: [2029](http://condorpiedra.andes.gob.ar:85/2029/mochawesome.html)
TEST START: 2020-10-02T13:14:13.672Z
TOTAL: 306
SUCCESS: 306
FAIL: -1
SKIPPED: 1

2020-10-02 13:34 UTC, merged