CITAS - Habilita turnos de gestion en agendas del dia
andes/app pull request #1932
Opened 2020-09-30 19:22 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/CIT-69

### Funcionalidad desarrollada 

1. Verifica si un turno solicitado desde TOP pertenece a una agenda (Del dia) configurada **solo con turnos de gestion** para permitirle dar turnos.
2. Permite visualizar desde el gestor de agendas este tipo de turnos (Solo en agendas exclusivas de gestion)

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si  https://github.com/andes/api/pull/1131
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si  (PENDIENTE)
- [ ] No

2020-10-01 19:01 UTC, liquid36 commented
BUILD NUMBER: [2026](http://condorpiedra.andes.gob.ar:85/2026/mochawesome.html)
TEST START: 2020-10-01T19:01:05.451Z
TOTAL: 301
SUCCESS: 299
FAIL: 1
SKIPPED: 1

2020-10-05 14:24 UTC, kroce requested changes
Creé dos agendas del día únicamente con turnos de gestión. Cuando voy a darle un turno desde una solicitud no veo la agenda. Adjunto captura, si las está trayendo en network pero no me las muestra en el calendario.
![image](https://user-images.githubusercontent.com/18030170/95091808-48096580-06fd-11eb-9293-af1fac7f8605.png)

2020-10-06 17:22 UTC, liquid36 commented
BUILD NUMBER: [2079](http://condorpiedra.andes.gob.ar:85/2079/mochawesome.html)
TEST START: 2020-10-06T17:22:08.088Z
TOTAL: 313
SUCCESS: 313
FAIL: 0
SKIPPED: 0

2020-10-09 14:17 UTC, kroce requested changes
@negro89 Ahora veo la agenda pero no puedo clickearla. 
![agenda](https://user-images.githubusercontent.com/18030170/95594185-ffb1b680-0a20-11eb-9200-513b8d700a48.png)
![calendar](https://user-images.githubusercontent.com/18030170/95594215-07715b00-0a21-11eb-88c9-fee8f83ccbb9.png)

2020-10-14 14:03 UTC, kroce requested changes
A partir de las fallas en los tests realizamos pruebas con agendas con turnos del día y no está funcionando como se espera.
Agenda planificada
![planif](https://user-images.githubusercontent.com/18030170/95999920-bee4e380-0e0c-11eb-9324-6d815d7a1edd.png)
Como se puede ver en el gestor de agendas, los turnos del día se muestran en cero
![cupo](https://user-images.githubusercontent.com/18030170/95999993-d1f7b380-0e0c-11eb-8f01-a6a38129edb0.png)

2020-10-14 14:52 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [2186](http://condorpiedra.andes.gob.ar:85/2186/mochawesome.html)
CYPRESS RUN: [1372](https://dashboard.cypress.io/projects/xr7gft/runs/1372/specs)
TEST START: 2020-10-14T14:52:40.840Z
TOTAL: 322
SUCCESS: 322
FAIL: 0
SKIPPED: 0

2020-10-16 13:06 UTC, kroce requested changes
Un detalle nada mas y estaría. Paso las pruebas

2020-10-16 13:06 UTC, kroce commented on src/app/components/turnos/dar-turnos/dar-turnos.component.ts
> +        return resp;
```suggestion
        return agenda.bloques.some(bloque => bloque.reservadoGestion > 0 && bloque.accesoDirectoDelDia === 0 && bloque.accesoDirectoProgramado === 0 && bloque.reservadoProfesional === 0);
```

2020-10-16 13:24 UTC, kroce approved these changes

2020-10-16 13:30 UTC, palita1991 approved these changes

2020-10-16 14:23 UTC, merged