feat(gestor-agendas): mejora interactividad al editar agendas
andes/app pull request #1935
Opened 2020-10-02 14:04 UTC by andrrrl

- feat(panel-agenda): actualiza layout (plex-title)
- feat(editar-agenda): se mejora layout (camba de 8 a 4 cols)
- chore(gestor-agendas): lint y formateo

### Requerimiento
 

### Funcionalidad desarrollada 

1. 
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2020-10-02 15:21 UTC, liquid36 commented
BUILD NUMBER: [2035](http://condorpiedra.andes.gob.ar:85/2035/mochawesome.html)
TEST START: 2020-10-02T15:20:40.141Z
TOTAL: 9
SUCCESS: 9
FAIL: 0
SKIPPED: 0

2020-10-05 13:40 UTC, liquid36 commented
BUILD NUMBER: [2052](http://condorpiedra.andes.gob.ar:85/2052/mochawesome.html)
TEST START: 2020-10-05T13:40:15.625Z
TOTAL: 312
SUCCESS: 312
FAIL: 0
SKIPPED: 0

2020-10-05 13:43 UTC, palita1991 approved these changes

2020-10-05 14:11 UTC, liquid36 requested changes

2020-10-05 14:11 UTC, liquid36 commented on src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
> +                if (this.showEditarAgendaPanel && agenda.estado !== 'publicada' && agenda.estado !== 'disponible' && agenda.estado !== 'planificacion') {
Esto estaba después del GET por una razón especifica. Si en simultaneo modifican el estado de la agenda y ya no se puede editar se mostraba un cartel al usuario.

2020-10-06 11:26 UTC, andrrrl commented on src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
> +                if (this.showEditarAgendaPanel && agenda.estado !== 'publicada' && agenda.estado !== 'disponible' && agenda.estado !== 'planificacion') {
Buenas! está perfecto, no estaba al tanto de eso. Igualmente la funcionalidad de plex.info() estaba siendo mal usada. Hice una versión con ambas cosas, decime si te parece bien! gracias!

2020-10-06 12:03 UTC, liquid36 commented on src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
> +                if (this.showEditarAgendaPanel && agenda.estado !== 'publicada' && agenda.estado !== 'disponible' && agenda.estado !== 'planificacion') {
No se enterá el usuario que ya la edito otra persona? Toca editar y no le pasa nada ?

2020-10-06 15:15 UTC, andrrrl commented on src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
> +                if (this.showEditarAgendaPanel && agenda.estado !== 'publicada' && agenda.estado !== 'disponible' && agenda.estado !== 'planificacion') {
> No se enterá el usuario que ya la edito otra persona? Toca editar y no le pasa nada ?

Para esos casos está esto: 
![image](https://user-images.githubusercontent.com/11394455/95221181-8d956380-07cd-11eb-8d6f-e47580262840.png)

2020-10-07 11:56 UTC, JSantarelli requested changes
Quizás relocalizaría los botones de 'guardar' / 'cancelar' en el sidebar para que queden vinculados al formulario que edita el usuario (según el lineamiento de acciones contextuales). Como un plus, pondría el plex-bool (espacios físicos de la organización) al mismo nivel de la selección del espacio físico o agrupado de algún modo (en un plex-title quizás).
Otro detalle sería mostrar algún recurso para que el usuario sepa que puede agregar más profesionales a la agenda.

2020-10-07 14:57 UTC, JSantarelli approved these changes
Perfecto.

2020-10-07 15:12 UTC, liquid36 approved these changes

2020-10-07 18:41 UTC, merged