TOP: refactor visual en listado de solicitudes
andes/app pull request #1943
Opened 2020-10-06 16:33 UTC by kroce

### Requerimiento
 Recrea parte de los mockups de https://proyectos.andes.gob.ar/browse/TOP-64

### Funcionalidad desarrollada 

1. Refactor del listado con todos componentes plex
2. Agrega plex-dropdown en los casos en los que hay muchos botones (p.e: solicitudes asignadas)

### UserStory llegó a completarse

- [ ] Si
- [x] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2020-10-06 16:55 UTC, liquid36 commented
BUILD NUMBER: [2076](http://condorpiedra.andes.gob.ar:85/2076/mochawesome.html)
TEST START: 2020-10-06T16:54:56.466Z
TOTAL: 313
SUCCESS: 312
FAIL: 1
SKIPPED: 0

2020-10-06 17:26 UTC, liquid36 commented
BUILD NUMBER: [2080](http://condorpiedra.andes.gob.ar:85/2080/mochawesome.html)
TEST START: 2020-10-06T17:24:38.195Z
TOTAL: 3
SUCCESS: 2
FAIL: 1
SKIPPED: 0

2020-10-06 17:55 UTC, liquid36 commented
BUILD NUMBER: [2084](http://condorpiedra.andes.gob.ar:85/2084/mochawesome.html)
TEST START: 2020-10-06T17:52:21.094Z
TOTAL: 3
SUCCESS: 2
FAIL: 1
SKIPPED: 0

2020-10-07 11:44 UTC, liquid36 commented
BUILD NUMBER: [2093](http://condorpiedra.andes.gob.ar:85/2093/mochawesome.html)
TEST START: 2020-10-07T11:44:04.511Z
TOTAL: 313
SUCCESS: 308
FAIL: 5
SKIPPED: 0

2020-10-07 12:14 UTC, liquid36 commented
BUILD NUMBER: [2095](http://condorpiedra.andes.gob.ar:85/2095/mochawesome.html)
TEST START: undefined
TOTAL: 0
SUCCESS: 0
FAIL: 0
SKIPPED: 0

2020-10-07 12:35 UTC, liquid36 commented
BUILD NUMBER: [2097](http://condorpiedra.andes.gob.ar:85/2097/mochawesome.html)
TEST START: 2020-10-07T12:31:39.795Z
TOTAL: 3
SUCCESS: 2
FAIL: 1
SKIPPED: 0

2020-10-07 15:06 UTC, palita1991 requested changes
En estos casos los dropdown están vacíos
![image](https://user-images.githubusercontent.com/30004190/95341166-5cc83380-088c-11eb-94a1-fae7d79b46d8.png)
![image](https://user-images.githubusercontent.com/30004190/95341204-6782c880-088c-11eb-93e8-d946b621ec8a.png)
![image](https://user-images.githubusercontent.com/30004190/95349301-538f9480-0895-11eb-8cb8-e900bd4c0835.png)

2020-10-07 16:29 UTC, liquid36 commented
BUILD NUMBER: [2112](http://condorpiedra.andes.gob.ar:85/2112/mochawesome.html)
TEST START: 2020-10-07T16:28:40.245Z
TOTAL: 296
SUCCESS: 295
FAIL: 0
SKIPPED: 1

2020-10-07 17:11 UTC, liquid36 commented
BUILD NUMBER: [2117](http://condorpiedra.andes.gob.ar:85/2117/mochawesome.html)
TEST START: 2020-10-07T17:11:15.350Z
TOTAL: 310
SUCCESS: 310
FAIL: 0
SKIPPED: 0

2020-10-07 18:51 UTC, kroce commented
> En estos casos los dropdown están vacíos
> ![image](https://user-images.githubusercontent.com/30004190/95341166-5cc83380-088c-11eb-94a1-fae7d79b46d8.png)
> ![image](https://user-images.githubusercontent.com/30004190/95341204-6782c880-088c-11eb-93e8-d946b621ec8a.png)
> ![image](https://user-images.githubusercontent.com/30004190/95349301-538f9480-0895-11eb-8cb8-e900bd4c0835.png)

Ahi hice unos cambios @palita1991

2020-10-07 19:01 UTC, liquid36 commented
BUILD NUMBER: [2120](http://condorpiedra.andes.gob.ar:85/2120/mochawesome.html)
TEST START: 2020-10-07T19:00:52.436Z
TOTAL: 302
SUCCESS: 301
FAIL: 1
SKIPPED: 0

2020-10-08 12:32 UTC, JSantarelli approved these changes
El listado se visualiza y comporta según lo esperado.

2020-10-08 12:46 UTC, palita1991 approved these changes

2020-10-08 12:54 UTC, JSantarelli requested changes
Agregaría la clase selected al plex-item seleccionado: `[selected]="prestacion.seleccionada === true"`

![item-selected](https://user-images.githubusercontent.com/5895886/95460975-091d1f00-094c-11eb-8c20-ea06eff4eb1d.gif)

2020-10-08 13:11 UTC, liquid36 commented
BUILD NUMBER: [2123](http://condorpiedra.andes.gob.ar:85/2123/mochawesome.html)
TEST START: 2020-10-08T13:11:09.578Z
TOTAL: 302
SUCCESS: 301
FAIL: 1
SKIPPED: 0

2020-10-08 15:32 UTC, kroce commented
> Agregaría la clase selected al plex-item seleccionado: `[selected]="prestacion.seleccionada === true"`
> 
> ![item-selected](https://user-images.githubusercontent.com/5895886/95460975-091d1f00-094c-11eb-8c20-ea06eff4eb1d.gif)

listo

2020-10-08 15:35 UTC, liquid36 commented
BUILD NUMBER: [2131](http://condorpiedra.andes.gob.ar:85/2131/mochawesome.html)
TEST START: 2020-10-08T15:35:14.095Z
TOTAL: 302
SUCCESS: 302
FAIL: 0
SKIPPED: 0

2020-10-08 16:01 UTC, juuliotero commented
Al abrir el sidebar, si hay más de un badge se pisa con las otras columnas. Por ahí se podrían ocultar columnas al seleccionar una solicitud.

![image](https://user-images.githubusercontent.com/7090371/95483967-4098c500-0966-11eb-83d2-49af837bd158.png)

2020-10-08 16:15 UTC, kroce commented
> Al abrir el sidebar, si hay más de un badge se pisa con las otras columnas. Por ahí se podrían ocultar columnas al seleccionar una solicitud.
> 
> ![image](https://user-images.githubusercontent.com/7090371/95483967-4098c500-0966-11eb-83d2-49af837bd158.png)

Ahí realicé el cambio. Cuando se abre el sidebar se oculta el paciente del listado

2020-10-08 17:13 UTC, juuliotero approved these changes

2020-10-08 17:14 UTC, merged