INTERNACION - Agregar o sacar columnas adicionales de la tabla
andes/app pull request #1949
Opened 2020-10-09 17:40 UTC by GaboCancellieri

### Requerimiento
 
A demás de las columnas que se muestran ahora(fijas), poder elegir otras columnas para visualizar. Columnas extras: fecha ultimo movimiento, usuario movimiento, sector completo (arrancar de arriba a abajo así se puede sortear), Documento, Sexo

### Funcionalidad desarrollada 

1. Agrega columnas adicionales a la tabla
2. Permite ordenar la tabla por estas columnas también
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2020-10-09 19:14 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [2163](http://condorpiedra.andes.gob.ar:85/2163/mochawesome.html)
TEST START: 2020-10-09T19:14:19.709Z
TOTAL: 5
SUCCESS: 5
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2020-10-14 12:39 UTC, liquid36 approved these changes

2020-10-14 12:39 UTC, liquid36 commented on src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
> +                                [class.invert]="(!cama.esSala || cama.estado !== 'ocupada') ? selectedCama.idCama === cama.idCama : selectedCama.idInternacion && cama.idInternacion === selectedCama.i
Esto provoco que se marquen todas las camas como seleccionadas.

2020-10-14 12:39 UTC, liquid36 commented on src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.html
> +                {{cama.createdBy?.nombreCompleto}}
```suggestion
                {{cama.createdBy | nombre }}
```

Las salas no viene el nombre completo

2020-10-14 12:39 UTC, liquid36 commented on src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.html
> +                {{cama.fecha | fecha}}
fecha y hora

2020-10-14 12:39 UTC, liquid36 commented on src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
> +                                [class.invert]="(!cama.esSala || cama.estado !== 'ocupada') ? selectedCama.idCama === cama.idCama : selectedCama.idInternacion && cama.idInternacion === selectedCama.i
![image](https://user-images.githubusercontent.com/3813270/95989847-2bf27c00-0e01-11eb-9070-344836f292b0.png)

2020-10-14 19:22 UTC, JSantarelli requested changes
La funcionalidad en sí es un gran aporte. Sólo un cambio (en la medida que se pueda implementar), una observación y una mejora:

a. Cuando el usuario navega hacia otra sección (existe un ruteo) los filtros seleccionados se resetean. Imagino que no es un comportamiento deseado (adjunto gif).

![mapa-camas](https://user-images.githubusercontent.com/5895886/96035044-d33ed580-0e38-11eb-9508-1395a59ca84d.gif)


b. En casos críticos (todas las columnas al asador) y una pantalla de 1280 x 768 px se da superposición de elementos (adjunto captura).

![caso-extremo-2](https://user-images.githubusercontent.com/5895886/96035089-e5b90f00-0e38-11eb-98da-ddeaa5697377.PNG)

c. No estaría de más que el heading del listado sea [sticky](https://codepen.io/chriscoyier/pen/PrJdxb) para que al scrollear no se pierda referencia de los datos.

2020-10-15 11:23 UTC, liquid36 commented
a. A futuro despues de detectar el uso que se lede.
b. Por algo la funcionalidad de elegir columna, muchas veces el usuario no necesita ver todo y se le termina rompiendo el layout por exceso de información. que se maneje y seleccione lo que necesite. Esta en camino de plex-list pero no quedan algunos detalles funcionales. 
c. Surgio un tema con el cdk-virtual-scroll, y se solucionará con la implementación de plex-list.

2020-10-16 11:07 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [2220](http://condorpiedra.andes.gob.ar:85/2220/mochawesome.html)
CYPRESS RUN: [1402](https://dashboard.cypress.io/projects/xr7gft/runs/1402/specs)
TEST START: 2020-10-16T11:07:30.045Z
TOTAL: 322
SUCCESS: 322
FAIL: 0
SKIPPED: 0

2020-10-19 16:44 UTC, merged