TOP: permite anular solicitudes auditables
andes/app pull request #1956
Opened 2020-10-14 17:20 UTC by plammel

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/TOP-86
### Funcionalidad desarrollada 

1. permite anular solicitudes auditables, botón anular en fila de solicitud
2. 
3. 

### UserStory llegó a completarse

- [ ] Si https://proyectos.andes.gob.ar/browse/TOP-86
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2020-10-14 17:31 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [2189](http://condorpiedra.andes.gob.ar:85/2189/mochawesome.html)
CYPRESS RUN: [1375](https://dashboard.cypress.io/projects/xr7gft/runs/1375/specs)
TEST START: 2020-10-14T17:31:30.736Z
TOTAL: 322
SUCCESS: 322
FAIL: 0
SKIPPED: 0

2020-10-15 17:45 UTC, palita1991 requested changes
@plammel Encontré un detalle en el sidebar cuando anulas una solicitud auditable, ahi como se puede observar en el "Motivo de anulación" dice anulada por [object][object] . El branch lo rebase localmente con master ya que hace unos minutos subio un cambio donde se cambiaba la visualización del historial
![image](https://user-images.githubusercontent.com/30004190/96166934-0a72bc80-0ef5-11eb-9e84-e227438f13d2.png)

2020-10-16 13:44 UTC, palita1991 approved these changes

2020-10-21 14:49 UTC, kroce requested changes
@plammel se están perdiendo controles que se estaban haciendo en el botón anular (como el efector del usuario logueado por ejemplo). Respecto al pipe sugiero modificar el que ya existe en lugar de crear uno nuevo

2020-10-22 12:27 UTC, plammel commented
> @plammel se están perdiendo controles que se estaban haciendo en el botón anular (como el efector del usuario logueado por ejemplo). Respecto al pipe sugiero modificar el que ya existe en lugar de crear uno nuevo

Los controles no se pierden, si no que están implícitos en el contexto, por eso son obviados. Se modificó el pipe de estado de solicitud para incluir 'auditables anulables'

2020-11-02 13:05 UTC, kroce commented
Ya mergeado el pipe de los botones, se resuelve este requerimiento en https://github.com/andes/app/pull/2014

2020-11-02 13:05 UTC, closed without merging