TOP: tab para historial en detalle
andes/app pull request #1958
Opened 2020-10-15 13:58 UTC by juuliotero

### Requerimiento 
https://proyectos.andes.gob.ar/browse/TOP-90

### Funcionalidad desarrollada 
1. Se muestra en un tab el historial en el detalle de solicitud

### UserStory llegó a completarse
- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2020-10-15 14:47 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [2203](http://condorpiedra.andes.gob.ar:85/2203/mochawesome.html)
CYPRESS RUN: [1385](https://dashboard.cypress.io/projects/xr7gft/runs/1385/specs)
TEST START: 2020-10-15T14:47:42.075Z
TOTAL: 322
SUCCESS: 322
FAIL: 0
SKIPPED: 0

2020-10-15 17:03 UTC, JSantarelli submitted a review, later dismissed
Juli! Sugiero que el historial ya se trabaje con [plex-item](https://www.andes.gob.ar/plex/doc/components/PlexItemComponent.html) en lugar de una  table así vamos unificando el uso de listados.
Adjunto captura y [html ](https://codepen.io/juliosantarelli/pen/QWEyYoG?editors=1000)si te sirve de guía.

![top-historial-refactor](https://user-images.githubusercontent.com/5895886/96161037-283c2380-0eed-11eb-8e98-e72f975c1515.PNG)

**Plus:** Ya que el primer tab se descomprime al moverse el historial a otra pestaña (plex-option) y ya no se requiere realizar tanto scroll, propongo que el encolumnado sea con el sidebar a 4 columnas:

`<plex-layout main="{{showSidebar? 8 : 12}}"`>

2020-10-15 17:12 UTC, liquid36 commented
y yo propongo que lo usen así:
```
<plex-layout [main]="showSidebar? 8 : 12">
```

xd

2020-10-15 18:51 UTC, juuliotero commented
> [main]="showSidebar? 8 : 12"

Aplicadas sugerencias. Se ve un poco raro el historial con el ancho en 8/12 @JSantarelli , pero lo dejé así para que veas que te parece

2020-10-15 19:10 UTC, JSantarelli commented
okas! Lo miro. Gracias @juuliotero

2020-10-16 03:47 UTC, JSantarelli commented
Lo veo bien así (adjunto captura). Le haría un par de ajustes:

- El icono que sea `<plex-icon name="entrada" type="info"></plex-icon>` tanto en historial como en listado del panel principal.
- Sacar el `[tituloBold]="false"` así se enfatiza la fecha.

![item-selected](https://user-images.githubusercontent.com/5895886/96210816-2011d180-0f49-11eb-8874-ef0c0c7c2808.JPG)

2020-10-16 14:03 UTC, juuliotero commented
> Lo veo bien así (adjunto captura). Le haría un par de ajustes:
> 
> * El icono que sea `<plex-icon name="entrada" type="info"></plex-icon>` tanto en historial como en listado del panel principal.
> * Sacar el `[tituloBold]="false"` así se enfatiza la fecha.
> 
> ![item-selected](https://user-images.githubusercontent.com/5895886/96210816-2011d180-0f49-11eb-8874-ef0c0c7c2808.JPG)

listooo

2020-10-16 15:59 UTC, palita1991 reviewed
Todo muy lindo @juuliotero , solo un detalle que al auditar una solicitud el botón de RESPONDER no se ve centrado como los demas
![image](https://user-images.githubusercontent.com/30004190/96280993-18851380-0faf-11eb-8c21-55f2662b6e80.png)

2020-10-20 19:57 UTC, juuliotero commented
> Todo muy lindo @juuliotero , solo un detalle que al auditar una solicitud el botón de RESPONDER no se ve centrado como los demas
> ![image](https://user-images.githubusercontent.com/30004190/96280993-18851380-0faf-11eb-8c21-55f2662b6e80.png)

corregido pala

2020-10-20 20:07 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [2283](http://condorpiedra.andes.gob.ar:85/2283/mochawesome.html)
CYPRESS RUN: [1456](https://dashboard.cypress.io/projects/xr7gft/runs/1456/specs)
TEST START: 2020-10-20T20:07:43.790Z
TOTAL: 323
SUCCESS: 323
FAIL: 0
SKIPPED: 0

2020-10-21 17:51 UTC, liquid36 requested changes

2020-10-21 17:51 UTC, liquid36 commented on src/app/components/top/solicitudes/detalleSolicitud.html
> +<plex-options [items]="items" (activated)="cambiarOpcion($event)"></plex-options>
un plex-options no es un TAB, a veces se usa como tab secundario pero creo que no es el caso acá.

2020-10-23 17:20 UTC, juuliotero commented on src/app/components/top/solicitudes/detalleSolicitud.html
> +<plex-options [items]="items" (activated)="cambiarOpcion($event)"></plex-options>
En el mockup del historial por separado en COM era un plex-options, y como se buscaba replicarlo en TOP se hizo de la misma manera

2020-11-02 14:46 UTC, palita1991 approved these changes

2020-11-02 16:51 UTC, kroce commented on src/app/components/top/solicitudes/detalleSolicitud.html
> +<plex-options [items]="items" (activated)="cambiarOpcion($event)"></plex-options>
@liquid36 aceptás el argumento de @juuliotero ?? lo estoy probando y parece que #andatodo

2020-11-02 16:59 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [2487](http://condorpiedra.andes.gob.ar:85/2487/mochawesome.html)
CYPRESS RUN: [1650](https://dashboard.cypress.io/projects/xr7gft/runs/1650/specs)
TEST START: 2020-11-02T16:55:25.282Z
TOTAL: 333
SUCCESS: 329
FAIL: 4
SKIPPED: 0

2020-11-02 17:07 UTC, liquid36 commented on src/app/components/top/solicitudes/detalleSolicitud.html
> +<plex-options [items]="items" (activated)="cambiarOpcion($event)"></plex-options>
@JSantarelli @andrrrl

2020-11-03 13:59 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [2496](http://condorpiedra.andes.gob.ar:85/2496/mochawesome.html)
CYPRESS RUN: [1659](https://dashboard.cypress.io/projects/xr7gft/runs/1659/specs)
TEST START: 2020-11-03T13:59:04.493Z
TOTAL: 333
SUCCESS: 333
FAIL: 0
SKIPPED: 0

2020-11-03 14:00 UTC, andrrrl commented on src/app/components/top/solicitudes/detalleSolicitud.html
> +<plex-options [items]="items" (activated)="cambiarOpcion($event)"></plex-options>
En breve habrá noticias sobre esto y todos seremos felices.

2020-11-03 14:15 UTC, JSantarelli commented on src/app/components/top/solicitudes/detalleSolicitud.html
> +<plex-options [items]="items" (activated)="cambiarOpcion($event)"></plex-options>
Buen día. Desde lo visual, los plex-options pueden ser utilizados como pestañas en tanto se encuadren dentro de los [lineamientos](https://ui.andes.gob.ar/components/plex-options/overview); y éste sería un caso válido. Si desde el punto de vista funcional está generando limitaciones podemos implementar [plex-tabs](https://ui.andes.gob.ar/components/component-tabs/overview) y pensar en alguna [solución ](https://proyectos.andes.gob.ar/browse/PLEX-183) intermedia,

2020-11-11 12:19 UTC, kroce approved these changes

2020-11-11 12:24 UTC, merged