CIT: bagde fuera de agenda
andes/app pull request #1966
Opened 2020-10-16 17:18 UTC by plammel

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-76
### Funcionalidad desarrollada 

1. incluye bagde fuera de agenda en histórico de citas
2. 
3. 

### UserStory llegó a completarse

- [ ] Si https://proyectos.andes.gob.ar/browse/CIT-76
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2020-10-16 17:32 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [2234](http://condorpiedra.andes.gob.ar:85/2234/mochawesome.html)
CYPRESS RUN: [1414](https://dashboard.cypress.io/projects/xr7gft/runs/1414/specs)
TEST START: 2020-10-16T17:31:54.038Z
TOTAL: 322
SUCCESS: 322
FAIL: 0
SKIPPED: 0

2020-10-19 15:47 UTC, palita1991 requested changes
@plammel 
1) Si es fuera de agenda propiamente dicho, se visualizan en el historial correctamente. Ahora las solicitudes que el profesional le inicia prestación desde "mis solicitudes" también son fuera de agenda, pero no se están visualizando en el historial como se ve en las imágenes.
![Captura de pantalla de 2020-10-19 12-34-02](https://user-images.githubusercontent.com/30004190/96473101-9b081000-1207-11eb-9a03-7264b20dfaee.png)
![Captura de pantalla de 2020-10-19 12-34-35](https://user-images.githubusercontent.com/30004190/96473108-9c393d00-1207-11eb-8625-2b140a7f949a.png)

2) Una consulta porque no se como sería en el caso de una fuera de agenda de "actividad con la comunidad" porque esas no aparecen en el historial del punto de inicio de citas. Pero la pregunta es , deberían aparecer?

2020-10-20 12:57 UTC, palita1991 approved these changes

2020-11-11 15:21 UTC, kroce requested changes
todavia no están los cambios sugeridos en la api

2020-11-16 13:52 UTC, kroce approved these changes

2020-11-16 14:22 UTC, merged