fix(RUP): relaciones no se guarda como ID
andes/app pull request #1970
Opened 2020-10-19 14:30 UTC by waltergarrido

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/RUP-199
### Funcionalidad desarrollada 

1. Se guarda solo el id del registro con el que esta relacionado y el termino del concepto.
2. 
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2020-10-19 14:43 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [2250](http://condorpiedra.andes.gob.ar:85/2250/mochawesome.html)
CYPRESS RUN: [1428](https://dashboard.cypress.io/projects/xr7gft/runs/1428/specs)
TEST START: 2020-10-19T14:42:58.928Z
TOTAL: 322
SUCCESS: 322
FAIL: 0
SKIPPED: 0

2020-10-20 11:26 UTC, juuliotero commented on src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
>                      let esRegistro = this.prestacion.ejecucion.registros.find(r => {
la variable podría llamarse distinta porque guarda un registro y no un boolean

2020-10-20 18:36 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [2279](http://condorpiedra.andes.gob.ar:85/2279/mochawesome.html)
CYPRESS RUN: [1452](https://dashboard.cypress.io/projects/xr7gft/runs/1452/specs)
TEST START: 2020-10-20T18:36:01.845Z
TOTAL: 323
SUCCESS: 322
FAIL: 1
SKIPPED: 0

2020-10-20 18:55 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [2281](http://condorpiedra.andes.gob.ar:85/2281/mochawesome.html)
CYPRESS RUN: [1454](https://dashboard.cypress.io/projects/xr7gft/runs/1454/specs)
TEST START: 2020-10-20T18:54:55.057Z
TOTAL: 258
SUCCESS: 255
FAIL: 3
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2020-10-21 11:36 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [2286](http://condorpiedra.andes.gob.ar:85/2286/mochawesome.html)
CYPRESS RUN: [1459](https://dashboard.cypress.io/projects/xr7gft/runs/1459/specs)
TEST START: 2020-10-21T11:36:41.356Z
TOTAL: 323
SUCCESS: 322
FAIL: 1
SKIPPED: 0

2020-10-21 11:54 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [2287](http://condorpiedra.andes.gob.ar:85/2287/mochawesome.html)
CYPRESS RUN: [1460](https://dashboard.cypress.io/projects/xr7gft/runs/1460/specs)
TEST START: 2020-10-21T11:51:51.452Z
TOTAL: 1
SUCCESS: 0
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2020-10-21 18:30 UTC, waltergarrido commented on src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
>                      let esRegistro = this.prestacion.ejecucion.registros.find(r => {
@juuliotero corregido

2020-10-21 18:41 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [2313](http://condorpiedra.andes.gob.ar:85/2313/mochawesome.html)
CYPRESS RUN: [1482](https://dashboard.cypress.io/projects/xr7gft/runs/1482/specs)
TEST START: 2020-10-21T18:41:03.060Z
TOTAL: 324
SUCCESS: 322
FAIL: 2
SKIPPED: 0

2020-10-21 19:09 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [2315](http://condorpiedra.andes.gob.ar:85/2315/mochawesome.html)
CYPRESS RUN: [1484](https://dashboard.cypress.io/projects/xr7gft/runs/1484/specs)
TEST START: 2020-10-21T19:09:34.210Z
TOTAL: 324
SUCCESS: 322
FAIL: 2
SKIPPED: 0

2020-10-23 12:56 UTC, liquid36 requested changes

2020-10-23 12:56 UTC, liquid36 commented on src/app/modules/rup/components/huds/vistaPrestacion.ts
> +        this.prestacion.ejecucion.registros.forEach(registro => {
Acá tenes el problema, si miras el código cuando se setea la prestación recien ahí se hace un find de la prestación. 

https://github.com/andes/app/blob/691c42c29ae41312b8e477e272fef50cd517cb4f/src/app/modules/rup/components/huds/vistaPrestacion.ts#L68

No es correcto hacer la trasformación en el ngOnInit. 

Además puede ser que sea un error en los test y no tenga seteado la ejecución. Habría que revisar los test.

2020-10-23 12:56 UTC, liquid36 commented on src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
> +                        registro.relacionadoCon[key] = { id: registroAux.id };
Array de ID, no array de objetos con un campo ID
```suggestion
                        registro.relacionadoCon[key] =  registroAux.id;
```

2020-10-28 15:03 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [2393](http://condorpiedra.andes.gob.ar:85/2393/mochawesome.html)
CYPRESS RUN: [1560](https://dashboard.cypress.io/projects/xr7gft/runs/1560/specs)
TEST START: 2020-10-28T15:03:27.787Z
TOTAL: 329
SUCCESS: 315
FAIL: 14
SKIPPED: 0

2020-10-28 15:39 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [2396](http://condorpiedra.andes.gob.ar:85/2396/mochawesome.html)
CYPRESS RUN: [1563](https://dashboard.cypress.io/projects/xr7gft/runs/1563/specs)
TEST START: 2020-10-28T15:39:34.882Z
TOTAL: 329
SUCCESS: 322
FAIL: 7
SKIPPED: 0

2020-10-29 10:45 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [2416](http://condorpiedra.andes.gob.ar:85/2416/mochawesome.html)
CYPRESS RUN: [1583](https://dashboard.cypress.io/projects/xr7gft/runs/1583/specs)
TEST START: 2020-10-29T10:43:44.343Z
TOTAL: 176
SUCCESS: 127
FAIL: 49
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2020-10-29 11:08 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [2418](http://condorpiedra.andes.gob.ar:85/2418/mochawesome.html)
CYPRESS RUN: [1585](https://dashboard.cypress.io/projects/xr7gft/runs/1585/specs)
TEST START: 2020-10-29T11:08:36.833Z
TOTAL: 329
SUCCESS: 327
FAIL: 2
SKIPPED: 0

2020-10-29 11:47 UTC, liquid36 approved these changes

2020-10-29 16:50 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [2434](http://condorpiedra.andes.gob.ar:85/2434/mochawesome.html)
CYPRESS RUN: [1601](https://dashboard.cypress.io/projects/xr7gft/runs/1601/specs)
TEST START: 2020-10-29T16:50:29.473Z
TOTAL: 329
SUCCESS: 329
FAIL: 0
SKIPPED: 0

2020-11-06 13:41 UTC, merged