INTERNACION - Aplica plex-wrapper en form egreso e ingreso de pacientes
andes/app pull request #1977
Opened 2020-10-21 19:34 UTC by GaboCancellieri

### Requerimiento
 
Refactorizar html a partir de componentes plex. html compuesto por: plex-grid o plex-wrapper (según corresponda)
### Funcionalidad desarrollada 

1. Aplica plex-wrapper en los formularios de egreso e ingreso de pacientes.
2. 
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [X] Si --> PR: https://github.com/andes/andes-test-integracion/pull/270
- [ ] No

2020-10-21 19:41 UTC, liquid36 commented
USUARIO: gcancellieri  
BUILD NUMBER: [2317](http://condorpiedra.andes.gob.ar:85/2317/mochawesome.html)
CYPRESS RUN: [1486](https://dashboard.cypress.io/projects/xr7gft/runs/1486/specs)
TEST START: 2020-10-21T19:41:05.866Z
TOTAL: 324
SUCCESS: 324
FAIL: 0
SKIPPED: 0

2020-10-22 18:01 UTC, liquid36 requested changes
Desaparecio motivo y especialidad. No te llamo la atencion que los tuviste que borrar en los test?

2020-10-22 18:05 UTC, liquid36 requested changes

2020-10-22 18:05 UTC, liquid36 commented on src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.html
> +        <plex-wrapper>
Este plex-wrapper debería ser todo uno con el de arriba. 

![image](https://user-images.githubusercontent.com/3813270/96911984-022bfb80-1478-11eb-99e2-a122f13e64f5.png)

Genera muchas rayas sino

2020-10-22 18:06 UTC, liquid36 commented on src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.html
> +        <plex-wrapper>
En egreso pasa algo parecido

2020-10-23 13:48 UTC, JSantarelli commented on src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.html
> +        <plex-wrapper>
Subscribo al tema wrapper, la única consideración es trabajar bien con la [directiva grow ](https://www.andes.gob.ar/plex/doc/directives/GrowDirective.html)para que los inputs mantengan un determinado tamaño en función de la info que alojan (por ej: origen será un [grow]="1" y profesional [grow]="3" ) en caso de crecer el sidebar.

2020-10-30 11:26 UTC, liquid36 approved these changes

2020-10-30 14:14 UTC, merged