Turnos y prestaciones: columnas dinámicas
andes/app pull request #1978
Opened 2020-10-22 12:42 UTC by martinebucarey

### Requerimiento
https://proyectos.andes.gob.ar/browse/BI-59

### Funcionalidad desarrollada 

1. Agrego _plex-dropdown_ en la vista del buscador de turnos y prestaciones para que el usuario pueda seleccionar que columnas desea ver y cuales no. Por defecto se mostraran fecha, paciente, tipoPrestacion y estado.
2. Se agrega el ámbito a las columnas dinámicas.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [x] Si https://github.com/andes/api/pull/1162
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2020-10-22 12:55 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [2324](http://condorpiedra.andes.gob.ar:85/2324/mochawesome.html)
CYPRESS RUN: [1492](https://dashboard.cypress.io/projects/xr7gft/runs/1492/specs)
TEST START: 2020-10-22T12:54:36.410Z
TOTAL: 280
SUCCESS: 270
FAIL: 10
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2020-10-22 13:28 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [2326](http://condorpiedra.andes.gob.ar:85/2326/mochawesome.html)
CYPRESS RUN: [1493](https://dashboard.cypress.io/projects/xr7gft/runs/1493/specs)
TEST START: 2020-10-22T13:28:28.263Z
TOTAL: 329
SUCCESS: 329
FAIL: 0
SKIPPED: 0

2020-10-22 15:57 UTC, plammel requested changes

2020-10-22 15:57 UTC, plammel commented on src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
> +                    <div *ngIf="columnas.equipoSalud" class="nombres-profesionales">
Un detalle: la columna "equipo de salud", no tiene los mismos margenes (superior e izquierdo) que las demás columnas y se ve ligeramente desalineado. Presumiblemente por usar `div` en lugar de `td`.
![image](https://user-images.githubusercontent.com/25707055/96897729-4cf04800-1465-11eb-8be8-c02cc2f97ccf.png)

2020-10-22 16:19 UTC, plammel commented
Así como se incluye "ámbito" a la tabla de resultados, ¿Debería de la misma manera incluirse el filtro por "ámbito" en el buscador?

2020-10-22 16:20 UTC, plammel commented
Tilde para "Prestación" y para "Ámbito" (si es que corresponde tilde en mayúsculas).
![image](https://user-images.githubusercontent.com/25707055/96901080-30560f00-1469-11eb-9ac1-5ec864b5a949.png)

2020-10-27 17:56 UTC, martinebucarey commented on src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
> +                    <div *ngIf="columnas.equipoSalud" class="nombres-profesionales">
Modificado, era por usar el div.

2020-10-27 17:56 UTC, martinebucarey commented
> Tilde para "Prestación" y para "Ámbito" (si es que corresponde tilde en mayúsculas).
> ![image](https://user-images.githubusercontent.com/25707055/96901080-30560f00-1469-11eb-9ac1-5ec864b5a949.png)

Modificado

2020-10-27 17:57 UTC, martinebucarey commented
> Así como se incluye "ámbito" a la tabla de resultados, ¿Debería de la misma manera incluirse el filtro por "ámbito" en el buscador?

mmm no se si vale la pena agregar un filtro mas de todos los que hay, mas teniendo en cuenta que en otro PR se va a poder ordenar por ámbito en este caso. No se que pensas @silviroa

2020-11-03 14:53 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [2500](http://condorpiedra.andes.gob.ar:85/2500/mochawesome.html)
CYPRESS RUN: [1662](https://dashboard.cypress.io/projects/xr7gft/runs/1662/specs)
TEST START: 2020-11-03T14:52:58.130Z
TOTAL: 333
SUCCESS: 333
FAIL: 0
SKIPPED: 0

2020-11-04 14:05 UTC, palita1991 approved these changes

2020-11-04 14:49 UTC, plammel approved these changes

2020-11-05 18:12 UTC, merged