MPI - re-ordenamiento campos telefono/usuario ANDES
andes/app pull request #1997
Opened 2020-10-27 18:35 UTC by negro89

### Requerimiento
 https://proyectos.andes.gob.ar/browse/MPI-266

### Funcionalidad desarrollada 

1. Re-estructura template de datosContactoComponent para mostrar dos columnas si el usuario tiene usuario ANDES (app-mobile)

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2020-10-27 18:51 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [2375](http://condorpiedra.andes.gob.ar:85/2375/mochawesome.html)
CYPRESS RUN: [1542](https://dashboard.cypress.io/projects/xr7gft/runs/1542/specs)
TEST START: 2020-10-27T18:48:28.287Z
TOTAL: 329
SUCCESS: 322
FAIL: 7
SKIPPED: 0

2020-10-27 21:09 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [2382](http://condorpiedra.andes.gob.ar:85/2382/mochawesome.html)
CYPRESS RUN: [1549](https://dashboard.cypress.io/projects/xr7gft/runs/1549/specs)
TEST START: 2020-10-27T21:09:06.301Z
TOTAL: 329
SUCCESS: 326
FAIL: 3
SKIPPED: 0

2020-10-28 13:16 UTC, JSantarelli requested changes
Al eliminar el mail del usuario desaparece el usuario ANDES del DOM. Adjunto comportamiento.
![ccomportamiento](https://user-images.githubusercontent.com/5895886/97440693-8d890f00-1906-11eb-902d-79cfdc8c2ccb.gif)

2020-10-28 15:35 UTC, negro89 commented
> Al eliminar el mail del usuario desaparece el usuario ANDES del DOM. Adjunto comportamiento.
> ![ccomportamiento](https://user-images.githubusercontent.com/5895886/97440693-8d890f00-1906-11eb-902d-79cfdc8c2ccb.gif)

gracias, resuelto!

2020-10-28 15:58 UTC, JSantarelli approved these changes
Funciona!

2020-10-28 16:11 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [2399](http://condorpiedra.andes.gob.ar:85/2399/mochawesome.html)
CYPRESS RUN: [1566](https://dashboard.cypress.io/projects/xr7gft/runs/1566/specs)
TEST START: 2020-10-28T16:10:54.053Z
TOTAL: 329
SUCCESS: 329
FAIL: 0
SKIPPED: 0

2020-11-03 13:20 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [2494](http://condorpiedra.andes.gob.ar:85/2494/mochawesome.html)
CYPRESS RUN: [1657](https://dashboard.cypress.io/projects/xr7gft/runs/1657/specs)
TEST START: 2020-11-03T13:20:05.334Z
TOTAL: 333
SUCCESS: 333
FAIL: 0
SKIPPED: 0

2020-11-03 16:17 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [2502](http://condorpiedra.andes.gob.ar:85/2502/mochawesome.html)
CYPRESS RUN: [1664](https://dashboard.cypress.io/projects/xr7gft/runs/1664/specs)
TEST START: 2020-11-03T16:16:58.745Z
TOTAL: 333
SUCCESS: 333
FAIL: 0
SKIPPED: 0

2020-11-04 15:41 UTC, MCele approved these changes

2020-11-04 18:25 UTC, merged