COM: permitir eliminar notas generadas por el usuario logueado
andes/app pull request #2008
Opened 2020-10-29 16:53 UTC by juuliotero

### Requerimiento 
https://proyectos.andes.gob.ar/browse/COM-24

### Funcionalidad desarrollada 

1. Permitir eliminar notas generadas por el usuario logueado

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si 
- [X] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1172
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2020-10-29 17:31 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [2437](http://condorpiedra.andes.gob.ar:85/2437/mochawesome.html)
CYPRESS RUN: [1604](https://dashboard.cypress.io/projects/xr7gft/runs/1604/specs)
TEST START: 2020-10-29T17:31:43.934Z
TOTAL: 329
SUCCESS: 322
FAIL: 7
SKIPPED: 0

2020-10-29 17:43 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [2438](http://condorpiedra.andes.gob.ar:85/2438/mochawesome.html)
CYPRESS RUN: [1605](https://dashboard.cypress.io/projects/xr7gft/runs/1605/specs)
TEST START: 2020-10-29T17:43:44.349Z
TOTAL: 329
SUCCESS: 329
FAIL: 0
SKIPPED: 0

2020-10-30 11:32 UTC, JSantarelli reviewed
El botón se visualiza. A futuro restaría utilizar componentes plex en el historial, plex-items (y los adjuntos visibles con plex-visualizador) o un listado de plex-accordions, ya que el item debe alojar una imagen. Queda [cargada la tarea en en Jira](https://proyectos.andes.gob.ar/browse/COM-32)

2020-10-30 12:24 UTC, JSantarelli requested changes

2020-10-30 12:24 UTC, JSantarelli commented on src/app/modules/com/components/historial-derivacion.html
> +                                 type="danger btn-sm" icon="trash-can" (click)="eliminarNota(item)">
plex-button tiene atributo [size], de paso evitamos clases extras. También eliminar el 'label' si está vacío. Quedaría algo así:
`<plex-button *ngIf="!item.estado && item.createdBy.username === auth.usuario.username" type="danger" size="sm" icon="trash-can" (click)="eliminarNota(item)"></plex-button>`

2020-11-04 12:25 UTC, palita1991 approved these changes

2020-11-04 12:36 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [2511](http://condorpiedra.andes.gob.ar:85/2511/mochawesome.html)
CYPRESS RUN: [1672](https://dashboard.cypress.io/projects/xr7gft/runs/1672/specs)
TEST START: 2020-11-04T12:36:44.703Z
TOTAL: 333
SUCCESS: 333
FAIL: 0
SKIPPED: 0

2020-11-04 12:37 UTC, kroce approved these changes

2020-11-04 12:37 UTC, merged