Punto Inicio Andes revisión 1
andes/app pull request #2018
Opened 2020-11-03 19:07 UTC by andrrrl

### Requerimiento
 
[![Documento de percepciones de usuarios !](https://img.shields.io/badge/Documento-UI%2FUX-sucess)](https://docs.google.com/document/d/1bjPlJzfI28g-rii56U5B5AtVGoQB3VBKfpx3miZIppE/edit)

### Funcionalidad desarrollada 

1. Se incrementó cuerpo tipográfico de algunos títulos y descripciones
2. Se agrandaron las cajas contenedoras de submódulos
3. Se agregó nombre del efecto junto al nombre del usuario
4. Mejoras en la versión mobile

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

**Desktop**
![image](https://user-images.githubusercontent.com/11394455/98024870-b407e800-1de7-11eb-86bb-ab044adb17e7.png)

**Mobile**
![image](https://user-images.githubusercontent.com/11394455/98024950-d13cb680-1de7-11eb-9e68-9480027261db.png)

2020-11-04 16:40 UTC, liquid36 requested changes

2020-11-04 16:40 UTC, liquid36 commented on src/app/components/inicio/inicio.html
> +                <div class="efector" *ngIf="auth.orgs.length > 1">{{ auth.organizacion.nombre }}</div>
Ojo que `auth.orgs` es un error de la matrix, no debería existir. 
Cambia por aurg.organizaciones() que es un observable. 

De todas forma, porque solo mostrarlo cuando tiene mas de una org y no siempre?

2020-11-11 12:44 UTC, andrrrl commented on src/app/components/inicio/inicio.html
> +                <div class="efector" *ngIf="auth.orgs.length > 1">{{ auth.organizacion.nombre }}</div>
Ah mirá, no sabía, se puede cambiar... la idea era mostrarlo porque algunos usuarios con más de 1 efector a veces se confunden en cual efector se loguearon y en el header está muy chiquito.

2020-11-11 12:52 UTC, liquid36 commented on src/app/components/inicio/inicio.html
> +                <div class="efector" *ngIf="auth.orgs.length > 1">{{ auth.organizacion.nombre }}</div>
Si, se entiende la idea. No se porque solo mostrarlo cuando hay mas de uno. Yo lo mostraría siempre.

2020-11-11 13:03 UTC, andrrrl commented on src/app/components/inicio/inicio.html
> +                <div class="efector" *ngIf="auth.orgs.length > 1">{{ auth.organizacion.nombre }}</div>
Y no se puede sacar de la session? (es observable y tiene la org)

2020-11-12 12:42 UTC, liquid36 approved these changes

2020-11-12 13:11 UTC, liquid36 commented
![image](https://user-images.githubusercontent.com/3813270/98944105-49ce0200-24cf-11eb-9872-1f98362d1908.png)

Se hizo un ajuste por el error que aparecia en la consola. Lo ideal a futuro seria usar routerLink.

2020-11-12 13:39 UTC, palita1991 approved these changes

2020-11-12 13:47 UTC, merged