COM: sumar gravedad al habilitar una derivación desde el COM
andes/app pull request #2025
Opened 2020-11-05 17:36 UTC by juuliotero

### Requerimiento 
https://proyectos.andes.gob.ar/browse/COM-25

### Funcionalidad desarrollada 
1. Permite indicar la gravedad del paciente al modificar el estado de una derivación si la regla lo permite
2. Filtro por gravedad del paciente
3. Hint para mostrar el tiene definida la gravedad

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1182
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2020-11-09 17:28 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [2559](http://condorpiedra.andes.gob.ar:85/2559/mochawesome.html)
CYPRESS RUN: [1718](https://dashboard.cypress.io/projects/xr7gft/runs/1718/specs)
TEST START: 2020-11-09T17:28:00.345Z
TOTAL: 336
SUCCESS: 336
FAIL: 0
SKIPPED: 0

2020-11-13 13:48 UTC, kroce requested changes
Al hacer click en una derivación se oculta la fecha pero queda la columna arriba. 
![image (4)](https://user-images.githubusercontent.com/18030170/99078797-bb748180-259d-11eb-9da7-2b5dc3d8ca40.png)

2020-11-16 13:50 UTC, juuliotero commented
> Al hacer click en una derivación se oculta la fecha pero queda la columna arriba.
> ![image (4)](https://user-images.githubusercontent.com/18030170/99078797-bb748180-259d-11eb-9da7-2b5dc3d8ca40.png)

corregido

2020-11-16 14:35 UTC, kroce approved these changes

2020-11-16 14:38 UTC, palita1991 approved these changes

2020-11-16 14:39 UTC, merged