refactor(RUP):que el tipo de prestación no pueda ser buscado
andes/app pull request #2028
Opened 2020-11-06 16:40 UTC by waltergarrido

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/RUP-215
### Funcionalidad desarrollada 

1. no se muestra en los resultados el tipo de la prestación sobre la que estoy trabajando .
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2020-11-06 16:48 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [2552](http://condorpiedra.andes.gob.ar:85/2552/mochawesome.html)
CYPRESS RUN: [1711](https://dashboard.cypress.io/projects/xr7gft/runs/1711/specs)
TEST START: 2020-11-06T16:48:34.449Z
TOTAL: 336
SUCCESS: 336
FAIL: 0
SKIPPED: 0

2020-11-06 16:56 UTC, liquid36 requested changes

2020-11-06 16:56 UTC, liquid36 commented on src/app/modules/rup/components/ejecucion/buscador.component.ts
> +                if (i.term === this.prestacion.solicitud.tipoPrestacion.term) {
Lo importante siempre es el identificador "conceptId" no el termino. Sabiendo que tiene sinonimos.
```suggestion
                if (i.conceptId === this.prestacion.solicitud.tipoPrestacion.conceptId) {
```

2020-11-06 16:56 UTC, liquid36 commented on src/app/modules/rup/components/ejecucion/buscador.component.ts
> +            resultadosSnomed.items.map((i, pos) => {
Esto no es más que un filtro, para eso existe la función "**filter**", así no tenes que hacer el splice de adentro que queda medio rebuscado.

2020-11-06 17:20 UTC, waltergarrido commented on src/app/modules/rup/components/ejecucion/buscador.component.ts
> +            resultadosSnomed.items.map((i, pos) => {
@liquid36 corregido

2020-11-06 17:40 UTC, liquid36 approved these changes

2020-11-12 11:23 UTC, liquid36 approved these changes

2020-11-12 12:47 UTC, merged