CIT: refactor arancelamiento
andes/app pull request #2032
Opened 2020-11-10 20:36 UTC by plammel

### Requerimiento
 

### Funcionalidad desarrollada 

1. Remueve código de arancelamiento y utiliza nueva ruta para descargar reporte de arancelamiento.
2. 
3. 

### UserStory llegó a completarse

- [x] Si  https://proyectos.andes.gob.ar/browse/CIT-86
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [x] Si https://github.com/andes/api/pull/1187
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2020-11-10 20:54 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [2569](http://condorpiedra.andes.gob.ar:85/2569/mochawesome.html)
CYPRESS RUN: [1728](https://dashboard.cypress.io/projects/xr7gft/runs/1728/specs)
TEST START: 2020-11-10T20:54:03.737Z
TOTAL: 336
SUCCESS: 336
FAIL: 0
SKIPPED: 0

2020-11-26 17:37 UTC, MCele approved these changes

2020-11-27 18:16 UTC, palita1991 requested changes
Visualizar que el número de carpeta no se está visualizando y en este caso el paciente tiene. 
Visualizar que no se esta mostrando el nombre de la prestación
![Captura de pantalla de 2020-11-27 15-14-27](https://user-images.githubusercontent.com/30004190/100476073-6c613d00-30c3-11eb-9c57-2d2895b10b51.png)

2020-11-30 15:32 UTC, plammel commented
> Visualizar que el número de carpeta no se está visualizando y en este caso el paciente tiene.
> Visualizar que no se esta mostrando el nombre de la prestación
> ![Captura de pantalla de 2020-11-27 15-14-27](https://user-images.githubusercontent.com/30004190/100476073-6c613d00-30c3-11eb-9c57-2d2895b10b51.png)

Fixeado!

2020-11-30 18:47 UTC, palita1991 approved these changes

2020-12-04 15:17 UTC, merged