COM: impresión de comprobante
andes/app pull request #2039
Opened 2020-11-12 16:34 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/COM-31

### Funcionalidad desarrollada 

1. Se agrega la impresión de comprobante para derivaciones finalizadas

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API
- [X] Si https://github.com/andes/api/pull/1192
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2020-11-12 16:52 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [2588](http://condorpiedra.andes.gob.ar:85/2588/mochawesome.html)
CYPRESS RUN: [1747](https://dashboard.cypress.io/projects/xr7gft/runs/1747/specs)
TEST START: 2020-11-12T16:51:54.446Z
TOTAL: 336
SUCCESS: 336
FAIL: 0
SKIPPED: 0

2020-11-17 11:19 UTC, palita1991 requested changes
@juuliotero revisar que se visualice correcto el formato de la hora, por ejemplo en este caso:
**01:09 -> 13:09
02:33 -> 14:33**
![image (5)](https://user-images.githubusercontent.com/30004190/99383790-27f8c480-28ad-11eb-83fd-de0323b780b3.jpg)

2020-11-17 14:35 UTC, palita1991 approved these changes

2020-11-17 17:41 UTC, juuliotero commented
> @juuliotero revisar que se visualice correcto el formato de la hora, por ejemplo en este caso:
> **01:09 -> 13:09 02:33 -> 14:33**
> ![image (5)](https://user-images.githubusercontent.com/30004190/99383790-27f8c480-28ad-11eb-83fd-de0323b780b3.jpg)

modificado

2020-11-18 13:17 UTC, kroce approved these changes

2020-11-18 13:19 UTC, merged