MPI - Visualizacion datos reporte de error
andes/app pull request #2053
Opened 2020-11-18 19:59 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MPI-115

### Funcionalidad desarrollada 

1. Agrega detalles al listado de reportes de error (Y sidebar) desde logs de reportes guardados en logPaciente
2. Nuevo componente para reporte de errores

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2020-11-19 11:56 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [2690](http://condorpiedra.andes.gob.ar:85/2690/mochawesome.html)
CYPRESS RUN: [1842](https://dashboard.cypress.io/projects/xr7gft/runs/1842/specs)
TEST START: 2020-11-19T11:56:16.502Z
TOTAL: 344
SUCCESS: 343
FAIL: 1
SKIPPED: 0

2020-11-19 12:47 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [2691](http://condorpiedra.andes.gob.ar:85/2691/mochawesome.html)
CYPRESS RUN: [1843](https://dashboard.cypress.io/projects/xr7gft/runs/1843/specs)
TEST START: 2020-11-19T12:42:38.306Z
TOTAL: 87
SUCCESS: 0
FAIL: 87
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2020-11-27 15:01 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [2776](http://condorpiedra.andes.gob.ar:85/2776/mochawesome.html)
CYPRESS RUN: [1918](https://dashboard.cypress.io/projects/xr7gft/runs/1918/specs)
TEST START: 2020-11-27T15:00:53.741Z
TOTAL: 350
SUCCESS: 350
FAIL: 0
SKIPPED: 0

2020-11-30 10:51 UTC, JSantarelli submitted a review, later dismissed

2020-11-30 10:51 UTC, JSantarelli commented on src/app/modules/auditoria/component/auditoria.html
> +            <plex-button *ngIf="permisoEdicion && pacienteSelected.reportarError" type="warning" position="right"
En general se respeta muy bien el prototipo. Sólo algunos detalles:
**Siempre en el sidebar:**
- Alinear botón "corregir" a la derecha (justify="end") y utilizar label del componente (label="corregir")
- Generar espacio entre la descripción del error reportado y el historial de errores (mediante un hr o alguna [helper](https://getbootstrap.com/docs/4.4/utilities/spacing/))
- Agregar fecha del error reportado (según [prototipo](https://xd.adobe.com/view/5bd93c2f-13ee-4ab4-5472-09110d408d1d-2de8/?fullscreen))

`<plex-button label="corregir" justify="end">`

![solucion](https://user-images.githubusercontent.com/5895886/100600830-93e12100-32e0-11eb-9ec7-44209cb66142.JPG)

2020-11-30 17:17 UTC, negro89 commented on src/app/modules/auditoria/component/auditoria.html
> +            <plex-button *ngIf="permisoEdicion && pacienteSelected.reportarError" type="warning" position="right"
hecho!

2020-11-30 20:19 UTC, MCele requested changes
Se observa una foto incorrecta al visualizar el modal para corregir los datos del paciente.
Parece ser que no se actualiza la foto del paciente cuando hay un paciente sin campo descripción. Es decir, que si alguno de los pacientes que se encuentra en el listado no tienen el campo descripción cargado, entonces el modal queda seteado siempre con la foto de dicho paciente.

![download](https://user-images.githubusercontent.com/19591224/101497317-98917f00-3949-11eb-85ba-ba6d5f96e749.png)

2020-12-08 14:40 UTC, MCele approved these changes

2020-12-10 14:06 UTC, condorpiedra approved these changes

2020-12-10 16:15 UTC, merged