COM: Ordenar listado por columnas
andes/app pull request #2056
Opened 2020-11-20 17:49 UTC by juuliotero

### Requerimiento 
https://proyectos.andes.gob.ar/browse/COM-37

### Funcionalidad desarrollada 
1. En el listado de derivaciones, permitir ordenar por cualquier columna. 

### UserStory llegó a completarse

- [ ] Si
- [X] No --> queda pendiente el orden por prioridad
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2020-11-25 12:46 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [2745](http://condorpiedra.andes.gob.ar:85/2745/mochawesome.html)
CYPRESS RUN: [1889](https://dashboard.cypress.io/projects/xr7gft/runs/1889/specs)
TEST START: 2020-11-25T12:46:06.828Z
TOTAL: 349
SUCCESS: 349
FAIL: 0
SKIPPED: 0

2020-11-26 18:41 UTC, palita1991 approved these changes

2020-12-02 15:39 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [2801](http://condorpiedra.andes.gob.ar:85/2801/mochawesome.html)
CYPRESS RUN: [1941](https://dashboard.cypress.io/projects/xr7gft/runs/1941/specs)
TEST START: 2020-12-02T15:39:38.156Z
TOTAL: 354
SUCCESS: 354
FAIL: 0
SKIPPED: 0

2020-12-02 19:27 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [2804](http://condorpiedra.andes.gob.ar:85/2804/mochawesome.html)
CYPRESS RUN: [1944](https://dashboard.cypress.io/projects/xr7gft/runs/1944/specs)
TEST START: 2020-12-02T19:27:03.275Z
TOTAL: 354
SUCCESS: 354
FAIL: 0
SKIPPED: 0

2020-12-03 13:21 UTC, palita1991 requested changes
1) Cuando le quiero poner prioridad especial, me salta ese error ( Puede ser que me falte algo en la Base de datos) pero por las dudas te lo comento por aca
![image](https://user-images.githubusercontent.com/30004190/101022928-d01ab880-3550-11eb-86f2-55705d45e301.png)

2) Anda raro al ordenar por fecha, no esta ordenando correctamente. COmo se puede visualizar en el video las derivaciones de diciembre que son las mas nuevas siempre salen por la mitad aunque las ordene en forma descendente
https://www.loom.com/share/d4eb0e19c8d84056af1327f8c6ad0e96

2020-12-04 15:27 UTC, juuliotero commented
> 1. Cuando le quiero poner prioridad especial, me salta ese error ( Puede ser que me falte algo en la Base de datos) pero por las dudas te lo comento por aca
>    ![image](https://user-images.githubusercontent.com/30004190/101022928-d01ab880-3550-11eb-86f2-55705d45e301.png)
> 2. Anda raro al ordenar por fecha, no esta ordenando correctamente. COmo se puede visualizar en el video las derivaciones de diciembre que son las mas nuevas siempre salen por la mitad aunque las ordene en forma descendente
>    https://www.loom.com/share/d4eb0e19c8d84056af1327f8c6ad0e96

Quedó corregido

2020-12-15 17:33 UTC, kroce approved these changes

2020-12-15 17:35 UTC, palita1991 approved these changes

2020-12-15 17:47 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [2883](http://condorpiedra.andes.gob.ar:85/2883/mochawesome.html)
CYPRESS RUN: [2018](https://dashboard.cypress.io/projects/xr7gft/runs/2018/specs)
TEST START: 2020-12-15T17:46:48.401Z
TOTAL: 355
SUCCESS: 348
FAIL: 7
SKIPPED: 0

2020-12-15 17:57 UTC, liquid36 commented
USUARIO: mpalavecino  
BUILD NUMBER: [2884](http://condorpiedra.andes.gob.ar:85/2884/mochawesome.html)
CYPRESS RUN: [2019](https://dashboard.cypress.io/projects/xr7gft/runs/2019/specs)
TEST START: 2020-12-15T17:56:18.913Z
TOTAL: 51
SUCCESS: 51
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2020-12-16 11:49 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [2888](http://condorpiedra.andes.gob.ar:85/2888/mochawesome.html)
CYPRESS RUN: [2023](https://dashboard.cypress.io/projects/xr7gft/runs/2023/specs)
TEST START: 2020-12-16T11:49:31.733Z
TOTAL: 355
SUCCESS: 355
FAIL: 0
SKIPPED: 0

2020-12-16 12:26 UTC, merged