refactor(HUDS):registros, agregar links a otros registros y a prestacion
andes/app pull request #2070
Opened 2020-12-02 14:45 UTC by waltergarrido

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/HUDS-31
### Funcionalidad desarrollada 

1. se agrega funcionalidad para poder abrir los registros de una prestación. 
2. también se agrega link para abrir la prestación desde los registros
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2020-12-02 15:16 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [2799](http://condorpiedra.andes.gob.ar:85/2799/mochawesome.html)
CYPRESS RUN: [1939](https://dashboard.cypress.io/projects/xr7gft/runs/1939/specs)
TEST START: 2020-12-02T15:11:33.895Z
TOTAL: 91
SUCCESS: 0
FAIL: 91
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2020-12-02 15:47 UTC, liquid36 commented
USUARIO: mpalavecino  
BUILD NUMBER: [2802](http://condorpiedra.andes.gob.ar:85/2802/mochawesome.html)
CYPRESS RUN: [1942](https://dashboard.cypress.io/projects/xr7gft/runs/1942/specs)
TEST START: 2020-12-02T15:47:28.524Z
TOTAL: 336
SUCCESS: 335
FAIL: 1
SKIPPED: 0

2020-12-02 16:30 UTC, palita1991 requested changes
Como se puede observar en la imagen al lado de los badge no se ve el botón con el ojito, pero aunque no esté se puede hacer click igual pero te das cuenta porque aparece cursor tipo hand. En cambio donde esta el nombre de la prestación se puede observar correctamente el botón.
![captura_wally](https://user-images.githubusercontent.com/30004190/100900754-eddd1480-34a1-11eb-8cca-394a3e3f10f7.png)

2020-12-02 16:54 UTC, liquid36 requested changes

2020-12-02 16:54 UTC, liquid36 commented on src/app/modules/rup/components/huds/vistaContextoPrestacion.ts
> +        let registroAux = this.todoRegistro.find(r => r.idRegistro === registro.id);
Cuando hago clicl en un trastorno que tiene evolución el codigo falla:

```
VistaContextoPrestacionComponent.html:34 ERROR TypeError: Cannot read property 'concepto' of undefined
    at VistaContextoPrestacionComponent.emitTabs (vistaContextoPrestacion.ts:49)
    at Object.eval [as handleEvent] (VistaContextoPrestacionComponent.html:34)
    at handleEvent (core.js:46182)
    at callWithDebugContext (core.js:47839)
```

Eso es porque los registros tienen esta forma:

![image](https://user-images.githubusercontent.com/3813270/100904263-9b9df280-34a5-11eb-984d-4ec5c955399c.png)

Fijate que hay un array de evoluciones con el ID del registro de cada evolución. Deberías realizar la busqueda en ese array y no en el `idRegistro` superior.

2020-12-02 16:54 UTC, liquid36 commented on src/app/modules/rup/components/huds/vistaContextoPrestacion.ts
> +        let registroAux = this.todoRegistro.find(r => r.idRegistro === registro.id);
sino se entiende, avissame

2020-12-03 14:15 UTC, waltergarrido commented on src/app/modules/rup/components/huds/vistaContextoPrestacion.ts
> +        let registroAux = this.todoRegistro.find(r => r.idRegistro === registro.id);
@liquid36 corregido

2020-12-03 14:58 UTC, liquid36 approved these changes

2020-12-03 15:20 UTC, palita1991 approved these changes

2020-12-03 15:44 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [2808](http://condorpiedra.andes.gob.ar:85/2808/mochawesome.html)
CYPRESS RUN: [1948](https://dashboard.cypress.io/projects/xr7gft/runs/1948/specs)
TEST START: 2020-12-03T15:43:58.861Z
TOTAL: 354
SUCCESS: 350
FAIL: 4
SKIPPED: 0

2020-12-03 15:52 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [2809](http://condorpiedra.andes.gob.ar:85/2809/mochawesome.html)
CYPRESS RUN: [1949](https://dashboard.cypress.io/projects/xr7gft/runs/1949/specs)
TEST START: 2020-12-03T15:52:05.897Z
TOTAL: 354
SUCCESS: 354
FAIL: 0
SKIPPED: 0

2020-12-03 17:51 UTC, merged