feat(HUDS): registros, mostrar adjuntos si esta relacionado
andes/app pull request #2077
Opened 2020-12-10 12:15 UTC by waltergarrido

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/HUDS-32
### Funcionalidad desarrollada 

1. se agrega funcionalidad para ver los archivos adjuntos si esta relacionado.
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

X

2020-12-10 12:27 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [2829](http://condorpiedra.andes.gob.ar:85/2829/mochawesome.html)
CYPRESS RUN: [1967](https://dashboard.cypress.io/projects/xr7gft/runs/1967/specs)
TEST START: 2020-12-10T12:27:01.967Z
TOTAL: 354
SUCCESS: 353
FAIL: 1
SKIPPED: 0

2020-12-10 12:59 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [2831](http://condorpiedra.andes.gob.ar:85/2831/mochawesome.html)
CYPRESS RUN: [1969](https://dashboard.cypress.io/projects/xr7gft/runs/1969/specs)
TEST START: 2020-12-10T12:59:18.242Z
TOTAL: 354
SUCCESS: 345
FAIL: 9
SKIPPED: 0

2020-12-10 13:22 UTC, liquid36 requested changes
Faltan controles si no tiene relaciones,
Falta control de archivo adjuntos, ahora te muestra todo.
Si visualizo un trastorno no se ve la relación con los archivos adjuntos.

2020-12-15 14:52 UTC, liquid36 approved these changes

2020-12-15 15:10 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [2876](http://condorpiedra.andes.gob.ar:85/2876/mochawesome.html)
CYPRESS RUN: [2011](https://dashboard.cypress.io/projects/xr7gft/runs/2011/specs)
TEST START: 2020-12-15T15:10:04.861Z
TOTAL: 305
SUCCESS: 304
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2020-12-15 15:35 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [2878](http://condorpiedra.andes.gob.ar:85/2878/mochawesome.html)
CYPRESS RUN: [2013](https://dashboard.cypress.io/projects/xr7gft/runs/2013/specs)
TEST START: 2020-12-15T15:34:58.583Z
TOTAL: 304
SUCCESS: 304
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2020-12-15 15:48 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [2879](http://condorpiedra.andes.gob.ar:85/2879/mochawesome.html)
CYPRESS RUN: [2014](https://dashboard.cypress.io/projects/xr7gft/runs/2014/specs)
TEST START: 2020-12-15T15:48:37.870Z
TOTAL: 355
SUCCESS: 355
FAIL: 0
SKIPPED: 0

2020-12-15 15:52 UTC, palita1991 approved these changes

2020-12-16 12:52 UTC, merged