CIT: registrar motivo liberación turno
andes/app pull request #2078
Opened 2020-12-10 14:11 UTC by plammel

### Requerimiento

https://proyectos.andes.gob.ar/browse/CIT-67
https://proyectos.andes.gob.ar/browse/CIT-91
### Funcionalidad desarrollada 

1.  Registra motivo liberación turno
2. Incluye nuevas opciones de motivo de liberación de turno

### UserStories llegó a completarse

- [x] Si https://proyectos.andes.gob.ar/browse/CIT-67 https://proyectos.andes.gob.ar/browse/CIT-91
- [ ] No

### Requiere actualizaciones en la API

- [x] Si https://github.com/andes/api/pull/1222
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2020-12-10 14:32 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [2837](http://condorpiedra.andes.gob.ar:85/2837/mochawesome.html)
CYPRESS RUN: [1974](https://dashboard.cypress.io/projects/xr7gft/runs/1974/specs)
TEST START: 2020-12-10T14:32:13.015Z
TOTAL: 350
SUCCESS: 349
FAIL: 1
SKIPPED: 0

2020-12-10 15:07 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [2839](http://condorpiedra.andes.gob.ar:85/2839/mochawesome.html)
CYPRESS RUN: [1975](https://dashboard.cypress.io/projects/xr7gft/runs/1975/specs)
TEST START: 2020-12-10T15:07:33.913Z
TOTAL: 354
SUCCESS: 354
FAIL: 0
SKIPPED: 0

2020-12-11 18:19 UTC, palita1991 requested changes
Se puede observar que en el tooltip de liberar turno hay un agregado "xxx" 
![image](https://user-images.githubusercontent.com/30004190/101939673-1496fb80-3bc4-11eb-9328-9add69a5be02.png)

2020-12-14 12:21 UTC, palita1991 approved these changes

2020-12-14 13:24 UTC, kroce approved these changes

2020-12-14 13:31 UTC, merged