feat(TOP): mostrar cantidad solicitudes
andes/app pull request #2080
Opened 2020-12-10 18:18 UTC by plammel

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/TOP-101
### Funcionalidad desarrollada 

1. Agrega contador de movimientos de auditoria de solicitud
2. 
3. 

### UserStory llegó a completarse

- [ ] Si https://proyectos.andes.gob.ar/browse/TOP-101
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2020-12-10 18:29 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [2849](http://condorpiedra.andes.gob.ar:85/2849/mochawesome.html)
CYPRESS RUN: [1985](https://dashboard.cypress.io/projects/xr7gft/runs/1985/specs)
TEST START: 2020-12-10T18:29:41.371Z
TOTAL: 354
SUCCESS: 351
FAIL: 3
SKIPPED: 0

2020-12-11 16:29 UTC, palita1991 requested changes
Faltarían los siguientes casos en donde vuelve a estar en estado de auditoria la solicitud y no se está contando:
1) Cuando la solicitud  es asignada a profesional y éste la "devuelve", la solicitud pasa a estado de auditoria nuevamente
2) Cuando la solicitud es asignada a un profesional, y desde TOP la deshacen, la solicitud pasa a estado de auditoria nuevamente.

2020-12-11 17:19 UTC, plammel commented
> Faltarían los siguientes casos en donde vuelve a estar en estado de auditoria la solicitud y no se está contando:
> 
> 1. Cuando la solicitud  es asignada a profesional y éste la "devuelve", la solicitud pasa a estado de auditoria nuevamente
> 2. Cuando la solicitud es asignada a un profesional, y desde TOP la deshacen, la solicitud pasa a estado de auditoria nuevamente.

@palita1991 si no entiendo mal el requerimiento, no se trata de contar todas las veces que entró en estado auditoria, sino mostrar cada vez que se realizó una acción/ se tomó un decisión dentro de la auditoria de solicitud.

2020-12-11 17:33 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [2858](http://condorpiedra.andes.gob.ar:85/2858/mochawesome.html)
CYPRESS RUN: [1994](https://dashboard.cypress.io/projects/xr7gft/runs/1994/specs)
TEST START: 2020-12-11T17:33:22.152Z
TOTAL: 354
SUCCESS: 348
FAIL: 6
SKIPPED: 0

2020-12-11 18:33 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [2859](http://condorpiedra.andes.gob.ar:85/2859/mochawesome.html)
CYPRESS RUN: [1995](https://dashboard.cypress.io/projects/xr7gft/runs/1995/specs)
TEST START: 2020-12-11T18:32:59.256Z
TOTAL: 353
SUCCESS: 353
FAIL: 0
SKIPPED: 0

2020-12-14 13:05 UTC, palita1991 approved these changes

2020-12-14 14:45 UTC, kroce requested changes
@plammel el recurso del número en los badges que se menciona en la tarea es este:

![image](https://user-images.githubusercontent.com/18030170/102094834-8b6d0800-3e01-11eb-956a-c9b197c24133.png)


Se utilizó en los casos en que una agenda tiene un turno para reasignar. En este caso, debería mostrarse el número solo en las solicitudes que se encuentran en estado auditoría, mostrando el número al lado (el color rojo no iría). Es para poder diferenciar entre las que están para auditar, cuales ya fueron auditadas y cuántas veces.

2020-12-15 15:30 UTC, plammel commented
> @plammel el recurso del número en los badges que se menciona en la tarea es este:
> 
> ![image](https://user-images.githubusercontent.com/18030170/102094834-8b6d0800-3e01-11eb-956a-c9b197c24133.png)
> 
> Se utilizó en los casos en que una agenda tiene un turno para reasignar. En este caso, debería mostrarse el número solo en las solicitudes que se encuentran en estado auditoría, mostrando el número al lado (el color rojo no iría). Es para poder diferenciar entre las que están para auditar, cuales ya fueron auditadas y cuántas veces.

Hecho

2020-12-18 15:10 UTC, liquid36 approved these changes

2020-12-18 17:33 UTC, merged