feat(CIT): mostrar espacio fisico dacion turno
andes/app pull request #2082
Opened 2020-12-11 15:04 UTC by plammel

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-94
### Funcionalidad desarrollada 

1. Muestra espacio físico de la agenda en dación de turno 
2. 
3. 

### UserStory llegó a completarse

- [x] Si https://proyectos.andes.gob.ar/browse/CIT-94
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2020-12-14 15:10 UTC, palita1991 requested changes
Cuando se elige un espacio físico que no es de la organización, no se visualiza al momento de dar el turno
![image](https://user-images.githubusercontent.com/30004190/102095422-49909180-3e02-11eb-9031-a66f8ed7def1.png)

![image](https://user-images.githubusercontent.com/30004190/102095388-3da4cf80-3e02-11eb-83d2-785c7e6448f7.png)

2020-12-15 12:53 UTC, plammel commented
> Cuando se elige un espacio físico que no es de la organización, no se visualiza al momento de dar el turno
> ![image](https://user-images.githubusercontent.com/30004190/102095422-49909180-3e02-11eb-9031-a66f8ed7def1.png)
> 
> ![image](https://user-images.githubusercontent.com/30004190/102095388-3da4cf80-3e02-11eb-83d2-785c7e6448f7.png)

Arreglado!

2020-12-15 13:24 UTC, liquid36 commented
USUARIO: mpalavecino  
BUILD NUMBER: [2873](http://condorpiedra.andes.gob.ar:85/2873/mochawesome.html)
CYPRESS RUN: [2008](https://dashboard.cypress.io/projects/xr7gft/runs/2008/specs)
TEST START: 2020-12-15T13:23:46.636Z
TOTAL: 355
SUCCESS: 353
FAIL: 2
SKIPPED: 0

2020-12-15 13:27 UTC, liquid36 commented
USUARIO: mpalavecino  
BUILD NUMBER: [2874](http://condorpiedra.andes.gob.ar:85/2874/mochawesome.html)
CYPRESS RUN: [2009](https://dashboard.cypress.io/projects/xr7gft/runs/2009/specs)
TEST START: 2020-12-15T13:27:07.056Z
TOTAL: 3
SUCCESS: 3
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2020-12-15 13:30 UTC, palita1991 approved these changes

2020-12-15 14:08 UTC, kroce approved these changes

2020-12-15 14:08 UTC, merged