COM: borrar archivos del drive al eliminar de la galería
andes/app pull request #2084
Opened 2020-12-11 15:26 UTC by juuliotero

### Requerimiento 
https://proyectos.andes.gob.ar/browse/COM-48

### Funcionalidad desarrollada 
1. Al eliminar un archivo de la galería se llama a la ruta DELETE /drive/:id

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2020-12-14 12:17 UTC, kroce requested changes
![wronDel](https://user-images.githubusercontent.com/18030170/102080346-1099f200-3ded-11eb-96e0-0b27b0a5ad1e.gif)

2020-12-14 19:10 UTC, juuliotero commented
> Nueva derivación: elimina el adjunto incorrecto
> 
> ![wronDel](https://user-images.githubusercontent.com/18030170/102080346-1099f200-3ded-11eb-96e0-0b27b0a5ad1e.gif)

Corregido!

2020-12-15 15:07 UTC, kroce approved these changes
grosa!

2020-12-15 15:14 UTC, palita1991 approved these changes

2020-12-15 15:22 UTC, liquid36 commented
USUARIO: mpalavecino  
BUILD NUMBER: [2877](http://condorpiedra.andes.gob.ar:85/2877/mochawesome.html)
CYPRESS RUN: [2012](https://dashboard.cypress.io/projects/xr7gft/runs/2012/specs)
TEST START: 2020-12-15T15:22:04.691Z
TOTAL: 355
SUCCESS: 355
FAIL: 0
SKIPPED: 0

2020-12-15 15:22 UTC, merged