TURNOS-PRESTACIONES: Agregar virtual scroll y filtro ambito
andes/app pull request #2091
Opened 2020-12-17 17:10 UTC by martinebucarey

### Requerimiento
https://proyectos.andes.gob.ar/browse/MISC-115

### Funcionalidad desarrollada 

1. Se agrega virtual scroll a la pantalla del buscador de turnos y prestaciones.
2. Se agrega el filtro ambito dentro del conjunto de filtros"

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [x] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2020-12-17 17:24 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [2931](http://condorpiedra.andes.gob.ar:85/2931/mochawesome.html)
CYPRESS RUN: [2064](https://dashboard.cypress.io/projects/xr7gft/runs/2064/specs)
TEST START: 2020-12-17T17:24:30.521Z
TOTAL: 355
SUCCESS: 355
FAIL: 0
SKIPPED: 0

2020-12-17 18:06 UTC, liquid36 requested changes

2020-12-17 18:06 UTC, liquid36 commented on src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.scss
> +    height: 100%;
Para evitar el doble scroll:

```suggestion
    height: calc(100% - 180px);;
```

2020-12-17 18:06 UTC, liquid36 commented on src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
> +                <cdk-virtual-scroll-viewport [itemSize]="60">
Es importante setear la altura correcta del item para que ande mejor el virtual scroll. Sino se aprecia que queda un vacío abajo. 

```suggestion
                <cdk-virtual-scroll-viewport [itemSize]="50">
```

2020-12-17 18:10 UTC, martinebucarey commented on src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.scss
> +    height: 100%;
Hecho

2020-12-17 18:11 UTC, martinebucarey commented on src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
> +                <cdk-virtual-scroll-viewport [itemSize]="60">
Hecho, es verdad no me habia dado cuenta

2020-12-17 18:42 UTC, liquid36 approved these changes

2020-12-23 11:26 UTC, liquid36 approved these changes

2020-12-23 15:03 UTC, merged