feat(login): Se agrega la posibilidad resetear la contraseña para los usuarios externos (no OneLogin)
andes/app pull request #2093
Opened 2020-12-21 18:12 UTC by sychus

- Posibilidad de configurar si la funcionalidad de "olvide mi contraseña" la quiero habilitada o no.
- Envío de correo con un link para el reseto de la misma si es un usuario temporal c/ mail (campos obligatorios) para poder utilizar esta funcionalidad. En caso que el usuario no sea externo, se redirecciona al sitio de onelogin para la procecusión del trámite.

### UserStory llegó a completarse
Proceso que permite el login y reset de contraseña para usuarios externos para el proceso de vacunación

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [x] Si
- [ ] No
PR #1233
### Requiere actualizaciones en andes-test-integracion

- [x] Si
- [ ] No

PD: Queda pendiente el test en andes-test-integración

2020-12-22 13:00 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [2947](http://condorpiedra.andes.gob.ar:85/2947/mochawesome.html)
CYPRESS RUN: [2080](https://dashboard.cypress.io/projects/xr7gft/runs/2080/specs)
TEST START: 2020-12-22T13:00:34.541Z
TOTAL: 226
SUCCESS: 187
FAIL: 39
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2020-12-22 16:47 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [2950](http://condorpiedra.andes.gob.ar:85/2950/mochawesome.html)
CYPRESS RUN: [2083](https://dashboard.cypress.io/projects/xr7gft/runs/2083/specs)
TEST START: 2020-12-22T16:47:43.277Z
TOTAL: 303
SUCCESS: 298
FAIL: 5
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2020-12-22 17:10 UTC, liquid36 commented
USUARIO: hfernandez  
BUILD NUMBER: [2951](http://condorpiedra.andes.gob.ar:85/2951/mochawesome.html)
CYPRESS RUN: [2084](https://dashboard.cypress.io/projects/xr7gft/runs/2084/specs)
TEST START: 2020-12-22T17:10:42.899Z
TOTAL: 353
SUCCESS: 353
FAIL: 0
SKIPPED: 0

2021-01-04 18:00 UTC, liquid36 requested changes

2021-01-04 18:00 UTC, liquid36 commented on src/app/apps/auth/components/recovery/recovery.component.ts
> +                this.formulario.show();
Arroja este error la consola, de donde salio ese código?

```
core.js:6241 ERROR TypeError: this.formulario.show is not a function
    at SafeSubscriber._next (recovery.component.ts:42)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183)
    at SafeSubscriber.next (Subscriber.js:122)
    at Subscriber._next (Subscriber.js:72)
    at Subscriber.next (Subscriber.js:49)
    at MapSubscriber._next (map.js:35)
    at MapSubscriber.next (Subscriber.js:49)
    at BehaviorSubject._subscribe (BehaviorSubject.js:14)
    at BehaviorSubject._trySubscribe (Observable.js:42)
    at BehaviorSubject._trySubscribe (Subject.js:81)
```

2021-01-04 18:00 UTC, liquid36 commented on src/app/apps/auth/components/recovery/recovery.component.ts
> +    @Output() closeModal = new EventEmitter<any>();
Las componentes que se usan como rutas no llevan Input y Ouput.

2021-01-06 18:12 UTC, liquid36 approved these changes

2021-01-07 13:43 UTC, kroce approved these changes

2021-01-07 15:19 UTC, merged