feat(mapa-camas): agrega operacion para prestar y devolver camas
andes/app pull request #2107
Opened 2021-01-15 11:18 UTC by liquid36

### Requerimiento
Funcionalidad para prestar/devolver camas sin tener que editar.

### UserStory llegó a completarse 
- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos 
- [ ] Si
- [ ] No

### Requiere actualizaciones en la API 
- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion 
- [ ] Si
- [ ] No

2021-01-15 11:30 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3084](http://condorpiedra.andes.gob.ar:85/3084/mochawesome.html)
CYPRESS RUN: [2211](https://dashboard.cypress.io/projects/xr7gft/runs/2211/specs)
TEST START: 2021-01-15T11:29:36.837Z
TOTAL: 351
SUCCESS: 351
FAIL: 0
SKIPPED: 0

2021-01-15 14:17 UTC, palita1991 approved these changes

2021-01-18 18:17 UTC, sychus commented on src/app/apps/rup/mapa-camas/sidebar/prestar-devolver-recurso/prestar-devolver-recurso.component.ts
> +        this.ambito = this.mapaCamasService.ambito2.getValue();
yo cambiaria fech2 y ambito2 por algo que se entienda más....

2021-01-18 18:17 UTC, sychus requested changes
detalle

2021-01-18 22:31 UTC, silviroa approved these changes

2021-01-20 16:29 UTC, merged