CITAS - Dación de turnos con modificadores
andes/app pull request #2113
Opened 2021-01-20 12:59 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/CIT-98
https://proyectos.andes.gob.ar/browse/CIT-99
https://proyectos.andes.gob.ar/browse/CIT-100
https://proyectos.andes.gob.ar/browse/CIT-101
https://proyectos.andes.gob.ar/browse/CIT-102

### Funcionalidad desarrollada 

1. Se consulta si existen modificadores que permitan a un paciente adquirir un turno de gestión.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [X] Si (Detalle en PR de api)
- [ ] No

### Requiere actualizaciones en la API

- [X] Si   https://github.com/andes/api/pull/1253
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-01-20 14:38 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3097](http://condorpiedra.andes.gob.ar:85/3097/mochawesome.html)
CYPRESS RUN: [2223](https://dashboard.cypress.io/projects/xr7gft/runs/2223/specs)
TEST START: 2021-01-20T14:37:31.589Z
TOTAL: 337
SUCCESS: 334
FAIL: 3
SKIPPED: 0

2021-01-20 16:17 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3098](http://condorpiedra.andes.gob.ar:85/3098/mochawesome.html)
CYPRESS RUN: [2224](https://dashboard.cypress.io/projects/xr7gft/runs/2224/specs)
TEST START: 2021-01-20T16:16:50.776Z
TOTAL: 351
SUCCESS: 351
FAIL: 0
SKIPPED: 0

2021-01-25 14:01 UTC, MCele approved these changes

2021-02-03 14:16 UTC, kroce commented
Consulta @negro89, pq cuando entro al calendario de turnos hace un post a la ruta de modificadores? no debería ser un get?

2021-02-05 13:58 UTC, negro89 commented
> Consulta @negro89, pq cuando entro al calendario de turnos hace un post a la ruta de modificadores? no debería ser un get?

@kroce eso es porque los parámetros son objetos. Si fueran solo los id's de la prestacion y el paciente podría ser un get.

2021-02-09 12:31 UTC, sychus requested changes
revisar porfa

2021-02-09 12:31 UTC, sychus commented on src/app/services/modificadores/modificadores.service.ts
> +        return this.server.post(this.apiUrl, params);
Estoy de acuerdo con @kroce, en realidad no estás creando nada. Probaste usar algo como: return this.server.get(this.apiUrl, params) 
Ya que POST es para create y sino confunde. En la api no usa resourceBase por algún motivo?

2021-02-22 11:37 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [3396](http://condorpiedra.andes.gob.ar:85/3396/mochawesome.html)
CYPRESS RUN: [2499](https://dashboard.cypress.io/projects/xr7gft/runs/2499/specs)
TEST START: 2021-02-22T11:35:51.382Z
TOTAL: 315
SUCCESS: 301
FAIL: 13
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-02-22 12:06 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [3397](http://condorpiedra.andes.gob.ar:85/3397/mochawesome.html)
CYPRESS RUN: [2500](https://dashboard.cypress.io/projects/xr7gft/runs/2500/specs)
TEST START: 2021-02-22T12:05:44.960Z
TOTAL: 358
SUCCESS: 355
FAIL: 2
SKIPPED: 1

2021-02-22 13:24 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [3398](http://condorpiedra.andes.gob.ar:85/3398/mochawesome.html)
CYPRESS RUN: [2501](https://dashboard.cypress.io/projects/xr7gft/runs/2501/specs)
TEST START: 2021-02-22T13:22:52.264Z
TOTAL: 358
SUCCESS: 357
FAIL: 0
SKIPPED: 1

2021-02-23 02:43 UTC, sychus approved these changes

2021-02-23 14:46 UTC, kroce approved these changes

2021-02-23 15:08 UTC, merged