feat(CITAS):se agrega permiso soloLectura
andes/app pull request #2114
Opened 2021-01-20 16:39 UTC by waltergarrido

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-103
### Funcionalidad desarrollada 

1. se agrega permiso soloLectura a punto de inicio y gestor de agenda
2. 
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1256
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-01-20 16:59 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3100](http://condorpiedra.andes.gob.ar:85/3100/mochawesome.html)
CYPRESS RUN: [2226](https://dashboard.cypress.io/projects/xr7gft/runs/2226/specs)
TEST START: 2021-01-20T16:58:13.290Z
TOTAL: 333
SUCCESS: 326
FAIL: 7
SKIPPED: 0

2021-01-20 17:35 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3104](http://condorpiedra.andes.gob.ar:85/3104/mochawesome.html)
CYPRESS RUN: [2230](https://dashboard.cypress.io/projects/xr7gft/runs/2230/specs)
TEST START: 2021-01-20T17:34:51.944Z
TOTAL: 333
SUCCESS: 326
FAIL: 7
SKIPPED: 0

2021-01-21 11:26 UTC, liquid36 requested changes

2021-01-21 11:26 UTC, liquid36 commented on src/app/components/turnos/gestor-agendas/gestor-agendas.html
> +    <footer *ngIf="showGestorAgendas && !soloLectura">
El permiso más que nada es para que te aparezca el acceso al menú. No es que tenerlo te bloquea otras acciones. Ya que cada acción tiene SU permiso.

2021-01-21 11:26 UTC, liquid36 commented on src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
> +                         [create]="!soloLectura">
Esto debería ir atado al permiso de MPI y no a ese permiso.

2021-01-21 13:37 UTC, waltergarrido commented on src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
> +                         [create]="!soloLectura">
@liquid36 corregido

2021-01-21 13:47 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3107](http://condorpiedra.andes.gob.ar:85/3107/mochawesome.html)
CYPRESS RUN: [2233](https://dashboard.cypress.io/projects/xr7gft/runs/2233/specs)
TEST START: 2021-01-21T13:46:00.092Z
TOTAL: 312
SUCCESS: 299
FAIL: 13
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-01-21 14:00 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3108](http://condorpiedra.andes.gob.ar:85/3108/mochawesome.html)
CYPRESS RUN: [2234](https://dashboard.cypress.io/projects/xr7gft/runs/2234/specs)
TEST START: 2021-01-21T13:59:23.837Z
TOTAL: 319
SUCCESS: 308
FAIL: 11
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-01-21 14:40 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3109](http://condorpiedra.andes.gob.ar:85/3109/mochawesome.html)
CYPRESS RUN: [2235](https://dashboard.cypress.io/projects/xr7gft/runs/2235/specs)
TEST START: 2021-01-21T14:39:51.185Z
TOTAL: 351
SUCCESS: 351
FAIL: 0
SKIPPED: 0

2021-01-22 12:37 UTC, liquid36 commented
GESTOR DE AGENDA: Faltaría agregar un permiso para Revisión de agendas:

![image](https://user-images.githubusercontent.com/3813270/105491554-38eef900-5c95-11eb-9467-59af2f53fbbd.png)

Aunque tengo solo los permisos de ver agendas puede Auditarlas.

2021-01-22 12:38 UTC, liquid36 commented
PUNTO DE INICIO
Se puede agregar una nueva capeta sin tener permisos de nada.

![image](https://user-images.githubusercontent.com/3813270/105491710-81a6b200-5c95-11eb-89dc-f16c15094254.png)

Agregar el permiso de _puedeEditarCarpeta_ a ese botón.

2021-01-22 13:07 UTC, palita1991 requested changes
@waltergarrido te deja editar la dirección del paciente en el punto de inicio de citas
![image](https://user-images.githubusercontent.com/30004190/105494450-91c09080-5c99-11eb-857c-30679ee2b0cb.png)

2021-01-26 12:27 UTC, palita1991 requested changes
Se puede realizar revision de agendas y agregar notas en el gestor de agendas
![image](https://user-images.githubusercontent.com/30004190/105844881-af069f00-5fb8-11eb-9f74-f011b87d0f01.png)

2021-01-26 14:31 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3123](http://condorpiedra.andes.gob.ar:85/3123/mochawesome.html)
CYPRESS RUN: [2249](https://dashboard.cypress.io/projects/xr7gft/runs/2249/specs)
TEST START: 2021-01-26T14:30:11.402Z
TOTAL: 351
SUCCESS: 351
FAIL: 0
SKIPPED: 0

2021-01-27 11:09 UTC, liquid36 approved these changes

2021-01-27 11:31 UTC, palita1991 approved these changes

2021-02-18 16:42 UTC, merged