CITAS - Activar/desactivar envío de sms de una agenda
andes/app pull request #2115
Opened 2021-01-21 12:23 UTC by negro89

### Requerimiento
 https://proyectos.andes.gob.ar/browse/CIT-88

### Funcionalidad desarrollada 

1. Nuevo bool para activar/desactivar envío de sms de la agenda
2. Uso de plex-title en pantalla de planificación de agendas

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si   https://github.com/andes/api/pull/1257
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-01-21 12:37 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3106](http://condorpiedra.andes.gob.ar:85/3106/mochawesome.html)
CYPRESS RUN: [2232](https://dashboard.cypress.io/projects/xr7gft/runs/2232/specs)
TEST START: 2021-01-21T12:36:10.139Z
TOTAL: 351
SUCCESS: 351
FAIL: 0
SKIPPED: 0

2021-01-22 12:43 UTC, palita1991 requested changes
Segun la user, el cambio tiene que **Permitir modificar esta opción a través de la edición de agendas**
1) Cuando la agenda esta publicada, y vas a editarla no se visualiza la opción de activar/desactivar el envio de sms
![image](https://user-images.githubusercontent.com/30004190/105491826-bdda1280-5c95-11eb-90a2-0f0085be6499.png)

1) Cuando la agenda esta en planificación, y vas a editarla no se visualiza la opción de activar/desactivar el envio de sms
![image](https://user-images.githubusercontent.com/30004190/105491935-eb26c080-5c95-11eb-98d2-07706a08ee52.png)

2021-01-28 14:03 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3155](http://condorpiedra.andes.gob.ar:85/3155/mochawesome.html)
CYPRESS RUN: [2280](https://dashboard.cypress.io/projects/xr7gft/runs/2280/specs)
TEST START: 2021-01-28T14:02:46.439Z
TOTAL: 354
SUCCESS: 354
FAIL: 0
SKIPPED: 0

2021-01-28 14:06 UTC, negro89 commented
> Segun la user, el cambio tiene que **Permitir modificar esta opción a través de la edición de agendas**
> 
> 1. Cuando la agenda esta publicada, y vas a editarla no se visualiza la opción de activar/desactivar el envio de sms
>    ![image](https://user-images.githubusercontent.com/30004190/105491826-bdda1280-5c95-11eb-90a2-0f0085be6499.png)
> 2. Cuando la agenda esta en planificación, y vas a editarla no se visualiza la opción de activar/desactivar el envio de sms
>    ![image](https://user-images.githubusercontent.com/30004190/105491935-eb26c080-5c95-11eb-98d2-07706a08ee52.png)

listo palita, corregido!

2021-01-29 13:35 UTC, palita1991 requested changes
Esta solucionado lo que se pidió anteriormente. Queda un solo detalle que visualmente puede traer confusión, cuando la agenda esta en planificación e ingresas a la edición de la misma, le activas los sms y guardas, al volver a entrar como se puede ver en el video se ve desactivado el envió de sms a pesar que en la base esta en true.
https://www.loom.com/share/b4e7edd2d5f7456c9eb2f43979a59257

2021-02-04 15:04 UTC, negro89 commented
Nuevamente corregido!

2021-02-04 15:35 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3212](http://condorpiedra.andes.gob.ar:85/3212/mochawesome.html)
CYPRESS RUN: [2334](https://dashboard.cypress.io/projects/xr7gft/runs/2334/specs)
TEST START: 2021-02-04T15:33:56.739Z
TOTAL: 336
SUCCESS: 335
FAIL: 1
SKIPPED: 0

2021-02-04 15:41 UTC, liquid36 commented
USUARIO: mpalavecino  
BUILD NUMBER: [3213](http://condorpiedra.andes.gob.ar:85/3213/mochawesome.html)
CYPRESS RUN: [2335](https://dashboard.cypress.io/projects/xr7gft/runs/2335/specs)
TEST START: 2021-02-04T15:38:14.451Z
TOTAL: 19
SUCCESS: 19
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-02-04 15:42 UTC, palita1991 approved these changes

2021-02-05 14:22 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3230](http://condorpiedra.andes.gob.ar:85/3230/mochawesome.html)
CYPRESS RUN: [2352](https://dashboard.cypress.io/projects/xr7gft/runs/2352/specs)
TEST START: 2021-02-05T14:21:24.351Z
TOTAL: 354
SUCCESS: 354
FAIL: 0
SKIPPED: 0

2021-02-08 13:30 UTC, liquid36 requested changes
Todas las agendas envian SMS actualmente, por esa razón haría que el plex-bool aparezca activado en antemano.

2021-02-08 16:05 UTC, liquid36 commented
Quedo charlado que va a quedar desactivado hasta proximo aviso.

2021-02-08 16:05 UTC, liquid36 approved these changes

2021-02-09 15:43 UTC, merged