feat(MPI): documentos adjuntos paciente
andes/app pull request #2116
Opened 2021-01-26 19:19 UTC by waltergarrido

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/MPI-312
### Funcionalidad desarrollada 

1. se agrega pestaña en MPI para gestionar documentos adjuntos del paciente
2. se agrega lista de documentos en paciente detalle 
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-01-27 16:58 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3144](http://condorpiedra.andes.gob.ar:85/3144/mochawesome.html)
CYPRESS RUN: [2269](https://dashboard.cypress.io/projects/xr7gft/runs/2269/specs)
TEST START: 2021-01-27T16:57:15.084Z
TOTAL: 354
SUCCESS: 330
FAIL: 24
SKIPPED: 0

2021-01-27 17:24 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3146](http://condorpiedra.andes.gob.ar:85/3146/mochawesome.html)
CYPRESS RUN: [2271](https://dashboard.cypress.io/projects/xr7gft/runs/2271/specs)
TEST START: 2021-01-27T17:23:38.466Z
TOTAL: 354
SUCCESS: 328
FAIL: 26
SKIPPED: 0

2021-01-27 19:11 UTC, MCele commented
En ell listado de MPI o desde auditoría cuando se previsualiza el documento del paciente seleccionado se ve que el buscador también sobresale del fondo.
![imagen](https://user-images.githubusercontent.com/19591224/106040811-b82b6500-60b9-11eb-99ae-8abbf1c947cd.png)

2021-01-28 11:51 UTC, MCele commented
> > En ell listado de MPI o desde auditoría cuando se previsualiza el documento del paciente seleccionado se ve que el buscador también sobresale del fondo.
> > ![imagen](https://user-images.githubusercontent.com/19591224/106040811-b82b6500-60b9-11eb-99ae-8abbf1c947cd.png)
> 
> @MCele ayer pregunte y me dijeron que eso es un tema de plex, no tiene que ver propiamente con el PR.

Ok! lo sospechaba, pero lo comenté por las dudas....

2021-01-28 12:00 UTC, MCele approved these changes

2021-01-28 12:02 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3150](http://condorpiedra.andes.gob.ar:85/3150/mochawesome.html)
CYPRESS RUN: [2275](https://dashboard.cypress.io/projects/xr7gft/runs/2275/specs)
TEST START: 2021-01-28T12:01:54.345Z
TOTAL: 354
SUCCESS: 326
FAIL: 28
SKIPPED: 0

2021-01-28 12:31 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3152](http://condorpiedra.andes.gob.ar:85/3152/mochawesome.html)
CYPRESS RUN: [2277](https://dashboard.cypress.io/projects/xr7gft/runs/2277/specs)
TEST START: 2021-01-28T12:30:24.441Z
TOTAL: 354
SUCCESS: 326
FAIL: 28
SKIPPED: 0

2021-01-28 15:38 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3157](http://condorpiedra.andes.gob.ar:85/3157/mochawesome.html)
CYPRESS RUN: [2282](https://dashboard.cypress.io/projects/xr7gft/runs/2282/specs)
TEST START: 2021-01-28T15:37:40.211Z
TOTAL: 327
SUCCESS: 316
FAIL: 11
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-01-28 17:06 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3159](http://condorpiedra.andes.gob.ar:85/3159/mochawesome.html)
CYPRESS RUN: [2284](https://dashboard.cypress.io/projects/xr7gft/runs/2284/specs)
TEST START: 2021-01-28T17:05:43.010Z
TOTAL: 5
SUCCESS: 5
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-01-28 17:29 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3161](http://condorpiedra.andes.gob.ar:85/3161/mochawesome.html)
CYPRESS RUN: [2286](https://dashboard.cypress.io/projects/xr7gft/runs/2286/specs)
TEST START: 2021-01-28T17:28:34.767Z
TOTAL: 354
SUCCESS: 353
FAIL: 1
SKIPPED: 0

2021-01-28 17:37 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3162](http://condorpiedra.andes.gob.ar:85/3162/mochawesome.html)
CYPRESS RUN: [2287](https://dashboard.cypress.io/projects/xr7gft/runs/2287/specs)
TEST START: 2021-01-28T17:35:06.789Z
TOTAL: 17
SUCCESS: 16
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-01-29 12:53 UTC, sychus requested changes
Sugerencias:
1) Al momento de adjuntar el archivo, debería decirte que formato espera que le subas o bien filtrar los formatos permitidos en la ventana de popUp.
2) ¿La 2da confirmación en necesaria? Creo que sería mejor una vez q seleccionas el archivo y valide lo que corresponda que ya lo inserte (de ultima está la posibilidad de borrarlo)
3) Por último, agregaría la hora en la fecha de subida Ej: 01/12/2020 14:30 hrs, a lo mejor si suben 2 documentos el mismo día (dni y pasaporte) quedan 2 como dni y el mismo día. (es un detalle igual)

2021-01-29 14:20 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3178](http://condorpiedra.andes.gob.ar:85/3178/mochawesome.html)
CYPRESS RUN: [2302](https://dashboard.cypress.io/projects/xr7gft/runs/2302/specs)
TEST START: 2021-01-29T14:17:42.922Z
TOTAL: 17
SUCCESS: 16
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-01-29 14:29 UTC, waltergarrido commented
> Sugerencias:
> 
> 1. Al momento de adjuntar el archivo, debería decirte que formato espera que le subas o bien filtrar los formatos permitidos en la ventana de popUp.
> 2. ¿La 2da confirmación en necesaria? Creo que sería mejor una vez q seleccionas el archivo y valide lo que corresponda que ya lo inserte (de ultima está la posibilidad de borrarlo)
> 3. Por último, agregaría la hora en la fecha de subida Ej: 01/12/2020 14:30 hrs, a lo mejor si suben 2 documentos el mismo día (dni y pasaporte) quedan 2 como dni  y el mismo día. (es un detalle igual)

2021-01-29 15:58 UTC, waltergarrido commented
> > Sugerencias:
> > 
> > 1. Al momento de adjuntar el archivo, debería decirte que formato espera que le subas o bien filtrar los formatos permitidos en la ventana de popUp.
> > 2. ¿La 2da confirmación en necesaria? Creo que sería mejor una vez q seleccionas el archivo y valide lo que corresponda que ya lo inserte (de ultima está la posibilidad de borrarlo)
> > 3. Por último, agregaría la hora en la fecha de subida Ej: 01/12/2020 14:30 hrs, a lo mejor si suben 2 documentos el mismo día (dni y pasaporte) quedan 2 como dni  y el mismo día. (es un detalle igual)
> 
> @sychus
> 1- el componente upload-file controla los tipos de archivos permitidos.
> 2- la segunda confirmación es necesaria porque podes agregar mas de un archivo .La segunda confirmación indica que se guarda el item .
> 3 -actualizado

2021-02-19 11:43 UTC, sychus commented
> > Sugerencias:
> > 
> > 1. Al momento de adjuntar el archivo, debería decirte que formato espera que le subas o bien filtrar los formatos permitidos en la ventana de popUp.
> > 2. ¿La 2da confirmación en necesaria? Creo que sería mejor una vez q seleccionas el archivo y valide lo que corresponda que ya lo inserte (de ultima está la posibilidad de borrarlo)
> > 3. Por último, agregaría la hora en la fecha de subida Ej: 01/12/2020 14:30 hrs, a lo mejor si suben 2 documentos el mismo día (dni y pasaporte) quedan 2 como dni  y el mismo día. (es un detalle igual)
> 
> @sychus
> 1- el componente upload-file controla los tipos de archivos permitidos.
> 2- la segunda confirmación es necesaria porque podes agregar mas de un archivo .La segunda confirmación indica que se guarda el item .
> 3 -actualizado

Con respecto a (1) a lo mejor no me explique bien, el problema es que no te filtra los tipos de archivos permitidos a priori. Por lo que te deja seleccionar cualquiera y el control lo hace despues. La sugerencia sería que la misma componente que está usando que invoca al explorador del sistema operativo ya te filtre los tipos de archivos (ejemplo: jpg, pdf). Hoy deja cualquiera, ejemplo:
![image](https://user-images.githubusercontent.com/19353464/108499833-ae96b680-728d-11eb-9500-11ec8ad9fc52.png)
Si no es posible en esta etapa, sugiero agregarlo como mejora en el backlog ya que sería muy útil a futuro.

2021-02-19 11:44 UTC, sychus reviewed
@waltergarrido ojota con el nombre del archivo component, debería ser: documentos-paciente.component  ;-)

2021-02-19 12:53 UTC, waltergarrido commented
> > > Sugerencias:
> > > 
> > > 1. Al momento de adjuntar el archivo, debería decirte que formato espera que le subas o bien filtrar los formatos permitidos en la ventana de popUp.
> > > 2. ¿La 2da confirmación en necesaria? Creo que sería mejor una vez q seleccionas el archivo y valide lo que corresponda que ya lo inserte (de ultima está la posibilidad de borrarlo)
> > > 3. Por último, agregaría la hora en la fecha de subida Ej: 01/12/2020 14:30 hrs, a lo mejor si suben 2 documentos el mismo día (dni y pasaporte) quedan 2 como dni  y el mismo día. (es un detalle igual)
> > 
> > 
> > @sychus
> > 1- el componente upload-file controla los tipos de archivos permitidos.
> > 2- la segunda confirmación es necesaria porque podes agregar mas de un archivo .La segunda confirmación indica que se guarda el item .
> > 3 -actualizado
> 
> Con respecto a (1) a lo mejor no me explique bien, el problema es que no te filtra los tipos de archivos permitidos a priori. Por lo que te deja seleccionar cualquiera y el control lo hace despues. La sugerencia sería que la misma componente que está usando que invoca al explorador del sistema operativo ya te filtre los tipos de archivos (ejemplo: jpg, pdf). Hoy deja cualquiera, ejemplo:
> ![image](https://user-images.githubusercontent.com/19353464/108499833-ae96b680-728d-11eb-9500-11ec8ad9fc52.png)
> Si no es posible en esta etapa, sugiero agregarlo como mejora en el backlog ya que sería muy útil a futuro.



> @waltergarrido ojota con el nombre del archivo component, debería ser: documentos-paciente.component ;-)

@sychus ha cual archivo component te referis?

2021-02-19 13:34 UTC, waltergarrido commented
> > > > Sugerencias:
> > > > 
> > > > 1. Al momento de adjuntar el archivo, debería decirte que formato espera que le subas o bien filtrar los formatos permitidos en la ventana de popUp.
> > > > 2. ¿La 2da confirmación en necesaria? Creo que sería mejor una vez q seleccionas el archivo y valide lo que corresponda que ya lo inserte (de ultima está la posibilidad de borrarlo)
> > > > 3. Por último, agregaría la hora en la fecha de subida Ej: 01/12/2020 14:30 hrs, a lo mejor si suben 2 documentos el mismo día (dni y pasaporte) quedan 2 como dni  y el mismo día. (es un detalle igual)
> > > 
> > > 
> > > @sychus
> > > 1- el componente upload-file controla los tipos de archivos permitidos.
> > > 2- la segunda confirmación es necesaria porque podes agregar mas de un archivo .La segunda confirmación indica que se guarda el item .
> > > 3 -actualizado
> > 
> > 
> > Con respecto a (1) a lo mejor no me explique bien, el problema es que no te filtra los tipos de archivos permitidos a priori. Por lo que te deja seleccionar cualquiera y el control lo hace despues. La sugerencia sería que la misma componente que está usando que invoca al explorador del sistema operativo ya te filtre los tipos de archivos (ejemplo: jpg, pdf). Hoy deja cualquiera, ejemplo:
> > ![image](https://user-images.githubusercontent.com/19353464/108499833-ae96b680-728d-11eb-9500-11ec8ad9fc52.png)
> > Si no es posible en esta etapa, sugiero agregarlo como mejora en el backlog ya que sería muy útil a futuro.
> 
> > @waltergarrido ojota con el nombre del archivo component, debería ser: documentos-paciente.component ;-)
> 
@sychus ha cual archivo component te referis? , y con respecto al filtro hay un filtro en la componente upload-file que recibe por parametro los tipos aceptados , fueron modificados para reducir la cantidad para un mejor control , no si esto responde a lo planteado , cuando quiero agregar un tipo de archivo no permitido un toast informa al usuario .
![Captura de pantalla de 2021-02-19 10-05-55](https://user-images.githubusercontent.com/64211129/108510985-fde4e300-729d-11eb-8322-2f7a3c2b89fc.png)

2021-02-19 14:31 UTC, liquid36 commented
Los documentos adjuntos se ven en todos lados. Habría que agregar un Input a `paciente-detalle` que muestre o no los documentos adjuntos igual a  como está hecho con relaciones.  Por default debería arrancar en false. 

![image](https://user-images.githubusercontent.com/3813270/108516869-7dc27b80-72a5-11eb-95a6-5b63f059ebb9.png)

2021-02-19 19:30 UTC, waltergarrido commented
> Los documentos adjuntos se ven en todos lados. Habría que agregar un Input a `paciente-detalle` que muestre o no los documentos adjuntos igual a como está hecho con relaciones. Por default debería arrancar en false.
> 
 ![image](https://user-images.githubusercontent.com/3813270/108516869-7dc27b80-72a5-11eb-95a6-5b63f059ebb9.png)

@liquid36 se agrega input.

2021-02-19 21:19 UTC, sychus commented
@waltergarrido perdón por la demora!! El archivo al que me refiero es este: 
![image](https://user-images.githubusercontent.com/19353464/108562633-ebd76480-72de-11eb-9730-5904d3935707.png)

El html y el component deberían tener el mismo prefijo, en este caso ambos deberían ser: documentos-paciente

Salutes

2021-02-19 21:21 UTC, sychus commented
@waltergarrido con respecto al tipo no me refiero al del plex-select. Sino a la ventana de popUp al momento de navegar el sistema de archivos. En lugar de permitirte seleccionar "todos", yo decía de restringir a los tipo de datos que soporta a los efectos q el usuario elija un formato inválido. Ojo: Puede ser una mejora para más adelante, pero creo que es muy útil.

2021-02-22 11:59 UTC, waltergarrido commented
@waltergarrido con respecto al tipo no me refiero al del plex-select. Sino a la ventana de popUp al momento de navegar el sistema de archivos. En lugar de permitirte seleccionar "todos", yo decía de restringir a los tipo de datos que soporta a los efectos q el usuario elija un formato inválido. Ojo: Puede ser una mejora para más adelante, pero creo que es muy útil.

@sychus se corrige

2021-02-22 12:02 UTC, waltergarrido commented
> @waltergarrido con respecto al tipo no me refiero al del plex-select. Sino a la ventana de popUp al momento de navegar el sistema de archivos. En lugar de permitirte seleccionar "todos", yo decía de restringir a los tipo de datos que soporta a los efectos q el usuario elija un formato inválido. Ojo: Puede ser una mejora para más adelante, pero creo que es muy útil.
> 
@sychus se tendrá en cuenta para futuras mejoras.

2021-02-22 12:03 UTC, waltergarrido commented
> @waltergarrido perdón por la demora!! El archivo al que me refiero es este:
> ![image](https://user-images.githubusercontent.com/19353464/108562633-ebd76480-72de-11eb-9730-5904d3935707.png)
> 
> El html y el component deberían tener el mismo prefijo, en este caso ambos deberían ser: documentos-paciente, es decir documentos-paciente.html y documentos-paciente.component.ts
> 
> Salutes

@sychus corregido

2021-02-23 13:16 UTC, sychus approved these changes
Ok, recordar el tema de la mejora mencionada (anotarla en jira)

2021-02-23 14:17 UTC, liquid36 approved these changes

2021-02-23 14:47 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3419](http://condorpiedra.andes.gob.ar:85/3419/mochawesome.html)
CYPRESS RUN: [2516](https://dashboard.cypress.io/projects/xr7gft/runs/2516/specs)
TEST START: 2021-02-23T14:46:35.221Z
TOTAL: 358
SUCCESS: 356
FAIL: 1
SKIPPED: 1

2021-02-23 15:51 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3420](http://condorpiedra.andes.gob.ar:85/3420/mochawesome.html)
CYPRESS RUN: [2517](https://dashboard.cypress.io/projects/xr7gft/runs/2517/specs)
TEST START: 2021-02-23T15:41:12.215Z
TOTAL: 251
SUCCESS: 219
FAIL: 31
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-02-23 16:11 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3421](http://condorpiedra.andes.gob.ar:85/3421/mochawesome.html)
CYPRESS RUN: [2518](https://dashboard.cypress.io/projects/xr7gft/runs/2518/specs)
TEST START: 2021-02-23T16:10:42.290Z
TOTAL: 344
SUCCESS: 339
FAIL: 4
SKIPPED: 1

2021-02-23 17:33 UTC, palita1991 approved these changes

2021-02-23 17:43 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3425](http://condorpiedra.andes.gob.ar:85/3425/mochawesome.html)
CYPRESS RUN: [2522](https://dashboard.cypress.io/projects/xr7gft/runs/2522/specs)
TEST START: 2021-02-23T17:42:44.433Z
TOTAL: 358
SUCCESS: 355
FAIL: 2
SKIPPED: 1

2021-02-23 17:57 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3426](http://condorpiedra.andes.gob.ar:85/3426/mochawesome.html)
CYPRESS RUN: [2523](https://dashboard.cypress.io/projects/xr7gft/runs/2523/specs)
TEST START: 2021-02-23T17:56:20.405Z
TOTAL: 358
SUCCESS: 357
FAIL: 0
SKIPPED: 1

2021-03-02 11:21 UTC, MCele approved these changes

2021-03-02 14:32 UTC, merged

2021-03-02 16:35 UTC, JSantarelli commented
> > > En ell listado de MPI o desde auditoría cuando se previsualiza el documento del paciente seleccionado se ve que el buscador también sobresale del fondo.
> > > ![imagen](https://user-images.githubusercontent.com/19591224/106040811-b82b6500-60b9-11eb-99ae-8abbf1c947cd.png)
> > 
> > 
> > @MCele ayer pregunte y me dijeron que eso es un tema de plex, no tiene que ver propiamente con el PR.
> 
> Ok! lo sospechaba, pero lo comenté por las dudas....

Queda cargada y en curso la [task ](https://proyectos.andes.gob.ar/browse/PLEX-234)en Jira