feat(COM): incluye traslados especiales
andes/app pull request #2118
Opened 2021-01-27 17:52 UTC by plammel

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/COM-53
### Funcionalidad desarrollada 

1. Incluye combo de tipo de traslado en nueva derivación.
2. Si la organización realiza traslados especiales, desde el COM visualiza las derivaciones que requieren traslados especiales.
3. Las derivaciones filtradas, pueden ser "actualizadas", registrar observaciones.

### UserStory llegó a completarse

- [x] Si https://proyectos.andes.gob.ar/browse/COM-53 
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [x] Si https://github.com/andes/api/pull/1262
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2021-01-28 19:13 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [3164](http://condorpiedra.andes.gob.ar:85/3164/mochawesome.html)
CYPRESS RUN: [2289](https://dashboard.cypress.io/projects/xr7gft/runs/2289/specs)
TEST START: 2021-01-28T19:12:14.588Z
TOTAL: 349
SUCCESS: 348
FAIL: 1
SKIPPED: 0

2021-01-28 20:23 UTC, sychus requested changes
Algunas cosas que me parecen piolas antes que esto salga:
1) Agregar en organizaciones un plex-bool trasladosEspeciales (en un futuro podríamos tener otras organizaciones q hagan eso: Vital, etc etc).
2) Agregar en organizaciones un plex-bool esCom (ya que no lo hicimos antes y estamos haciendo 1)
3) Ojo!! que cuando interviene la organización de trasladosEspeciales, es posible borrar el registro "historial" cargado desde cualqueir otra organización. Esto no debería suceder, verificar control.

2021-01-28 20:23 UTC, sychus commented on src/app/modules/com/components/punto-inicio.component.ts
> +                query['tipoTraslado'] = 'TRASLADO ESPECIAL';
Evitar el hardcodeo acá, ya que si en la colección lo cargan mal no va a levantar la info. Se propone levantar todos los tipos de la base y q compare con el seleccionado en el registro. YA que el dato lo tenemos. :-)

2021-02-02 18:43 UTC, juuliotero commented on src/app/modules/com/components/punto-inicio.component.ts
> +                query['tipoTraslado'] = 'TRASLADO ESPECIAL';
Por ahí las organizaciones deberían tener asociados tipos de traslados (así como las derivaciones) y en la query mandar directamente los id de tipoTraslados que tenga la organización actual, en lugar de un bool

2021-02-03 11:16 UTC, kroce commented on src/app/modules/com/components/punto-inicio.component.ts
> +                query['tipoTraslado'] = 'TRASLADO ESPECIAL';
Coincido con la observación de @juuliotero

2021-02-05 13:34 UTC, liquid36 commented
USUARIO: hfernandez  
BUILD NUMBER: [3227](http://condorpiedra.andes.gob.ar:85/3227/mochawesome.html)
CYPRESS RUN: [2349](https://dashboard.cypress.io/projects/xr7gft/runs/2349/specs)
TEST START: 2021-02-05T13:33:00.506Z
TOTAL: 315
SUCCESS: 302
FAIL: 13
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-02-05 13:47 UTC, sychus approved these changes

2021-02-05 13:57 UTC, liquid36 commented
USUARIO: hfernandez  
BUILD NUMBER: [3228](http://condorpiedra.andes.gob.ar:85/3228/mochawesome.html)
CYPRESS RUN: [2350](https://dashboard.cypress.io/projects/xr7gft/runs/2350/specs)
TEST START: 2021-02-05T13:56:36.568Z
TOTAL: 354
SUCCESS: 353
FAIL: 1
SKIPPED: 0

2021-02-05 14:09 UTC, sychus commented
@plammel  hay que modificar el test, ya que al sacar el endpoint de historial está fallando.
@updateHistorial para: cy.route('POST', '**/modules/com/derivaciones/**/historial').as('updateHistorial'); Ya que no está en el código.

2021-02-05 15:12 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [3233](http://condorpiedra.andes.gob.ar:85/3233/mochawesome.html)
CYPRESS RUN: [2355](https://dashboard.cypress.io/projects/xr7gft/runs/2355/specs)
TEST START: 2021-02-05T15:10:46.622Z
TOTAL: 267
SUCCESS: 255
FAIL: 12
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-02-05 16:12 UTC, kroce commented
No me convence mucho **Organización Traslado**, pondría  **Traslado a cargo de:** o simplemente **Traslado**
![image](https://user-images.githubusercontent.com/18030170/107058369-489d3000-67b3-11eb-9f74-982155db1f8b.png)

2021-02-05 16:24 UTC, sychus commented
> No me convence mucho **Organización Traslado**, pondría **Traslado a cargo de:** o simplemente **Traslado**
> 
> ![image](https://user-images.githubusercontent.com/18030170/107058369-489d3000-67b3-11eb-9f74-982155db1f8b.png)

De acuerdo!! sisis me parece bien!

2021-02-05 16:45 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [3240](http://condorpiedra.andes.gob.ar:85/3240/mochawesome.html)
CYPRESS RUN: [2362](https://dashboard.cypress.io/projects/xr7gft/runs/2362/specs)
TEST START: 2021-02-05T16:35:12.050Z
TOTAL: 354
SUCCESS: 343
FAIL: 11
SKIPPED: 0

2021-02-05 17:03 UTC, kroce requested changes

2021-02-05 17:03 UTC, kroce commented on src/app/modules/com/components/actualizar-estado.component.ts
> +            this.derivacion.historial.push(this.nuevoEstado);
Esto estaba hecho así por un problema de concurrencia que se dió con el módulo en producción cuando mas de un usuario editaba la derivación. Debería quedar como estaba, utilizando el método updateHistorial

2021-02-05 17:05 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [3241](http://condorpiedra.andes.gob.ar:85/3241/mochawesome.html)
CYPRESS RUN: [2363](https://dashboard.cypress.io/projects/xr7gft/runs/2363/specs)
TEST START: 2021-02-05T17:04:53.477Z
TOTAL: 336
SUCCESS: 334
FAIL: 2
SKIPPED: 0

2021-02-05 17:46 UTC, martinebucarey commented on src/app/modules/com/components/detalle-derivacion.component.ts
> -            this.derivacionService.updateHistorial(this.derivacion._id, this.nuevoEstado).subscribe(() => {
acá también se elimino el uso de updateHistorial, lo marco por el comentario de kroce de arriba.

2021-02-05 20:36 UTC, liquid36 commented
USUARIO: hfernandez  
BUILD NUMBER: [3248](http://condorpiedra.andes.gob.ar:85/3248/mochawesome.html)
CYPRESS RUN: [2364](https://dashboard.cypress.io/projects/xr7gft/runs/2364/specs)
TEST START: 2021-02-05T20:35:45.067Z
TOTAL: 354
SUCCESS: 354
FAIL: 0
SKIPPED: 0

2021-02-05 20:37 UTC, sychus approved these changes

2021-02-09 13:16 UTC, martinebucarey approved these changes

2021-02-09 14:09 UTC, sychus commented on src/app/modules/com/components/actualizar-estado.component.ts
> +            this.derivacion.historial.push(this.nuevoEstado);
Ya quedo resuelto @kroce querés verificar porfa?

2021-02-09 14:51 UTC, merged