COM: crea derivación como prestación
andes/app pull request #2122
Opened 2021-01-28 18:42 UTC by plammel

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/COM-52
### Funcionalidad desarrollada 

1. Reemplaza 'detalle' de derivación por prestación
2. Incluye workflow de registro de prestación en RUP al momento de crear un nueva derivación.
3. 

### UserStory llegó a completarse

- [ ] Si https://proyectos.andes.gob.ar/browse/COM-52
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2021-01-28 19:02 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [3163](http://condorpiedra.andes.gob.ar:85/3163/mochawesome.html)
CYPRESS RUN: [2288](https://dashboard.cypress.io/projects/xr7gft/runs/2288/specs)
TEST START: 2021-01-28T19:01:06.929Z
TOTAL: 354
SUCCESS: 344
FAIL: 10
SKIPPED: 0

2021-01-28 21:01 UTC, sychus approved these changes
Me gustó!!!! creo que es un buen primer paso. Sería bueno evaluarlo con el resto de los chicos. Cositas a definir:
1) El tipo de prestación (como comentaste bien en el código) hay que revisar cual sería la que corresponde.
2) Revisar un pequeño detalle, cuando escribis en rup creo que faltaría parsear los campos html, en este caso me trajo un párrafo
![image](https://user-images.githubusercontent.com/19353464/106198420-c600e900-6192-11eb-8ddc-852a158adcba.png)

2021-01-29 16:01 UTC, liquid36 requested changes

2021-01-29 16:01 UTC, liquid36 commented on src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
> +        let nuevaPrestacion = this.servicioPrestacion.inicializarPrestacion(this.paciente, concepto, 'ejecucion', 'com');
Ambito COM no existe, el paciente estar internado así que seguimos en ambito internación. El inicio de la prestación (es otra variable) si podes setearlo a COM.

2021-01-29 16:01 UTC, liquid36 commented on src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
> +            case 'com':
Ya hay todo un sistema para el botón volver. Utilizar ese sistema

2021-02-02 16:37 UTC, closed without merging