MPI - Salva valor de scan en paciente existente
andes/app pull request #2124
Opened 2021-01-29 12:44 UTC by negro89

### Requerimiento
Dado un paciente existente que no haya sido validado por scanner, realizando una búsqueda por scan el paciente se obtiene y visualiza correctamente pero no se le asigna el código de scan para que persista en DB

### Funcionalidad desarrollada 

1. Modifica servicio de pacienteCaché para que en lugar de almacenar si el paciente fue escaneado o no, almacene codigo de scan o null respectivamente.
2. 
### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-01-29 15:17 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3182](http://condorpiedra.andes.gob.ar:85/3182/mochawesome.html)
CYPRESS RUN: [2306](https://dashboard.cypress.io/projects/xr7gft/runs/2306/specs)
TEST START: 2021-01-29T15:16:40.881Z
TOTAL: 354
SUCCESS: 348
FAIL: 6
SKIPPED: 0

2021-01-29 16:19 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3184](http://condorpiedra.andes.gob.ar:85/3184/mochawesome.html)
CYPRESS RUN: [2308](https://dashboard.cypress.io/projects/xr7gft/runs/2308/specs)
TEST START: 2021-01-29T16:18:18.982Z
TOTAL: 354
SUCCESS: 351
FAIL: 3
SKIPPED: 0

2021-01-29 17:54 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3185](http://condorpiedra.andes.gob.ar:85/3185/mochawesome.html)
CYPRESS RUN: [2309](https://dashboard.cypress.io/projects/xr7gft/runs/2309/specs)
TEST START: 2021-01-29T17:53:06.420Z
TOTAL: 354
SUCCESS: 352
FAIL: 2
SKIPPED: 0

2021-01-29 18:18 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3186](http://condorpiedra.andes.gob.ar:85/3186/mochawesome.html)
CYPRESS RUN: [2310](https://dashboard.cypress.io/projects/xr7gft/runs/2310/specs)
TEST START: 2021-01-29T18:17:49.324Z
TOTAL: 354
SUCCESS: 354
FAIL: 0
SKIPPED: 0

2021-02-09 16:48 UTC, MCele requested changes
La búsqueda por scan no filtra por paciente activo. Me parece que en el caso del buscador básico de mpi si el paciente obtenido está inactivo no se debería mostrar.

2021-02-09 17:24 UTC, condorpiedra requested changes

2021-02-09 17:24 UTC, condorpiedra commented on src/app/core/mpi/services/paciente-buscar.service.ts
> +            sexo: pacienteEscaneado.sexo
agregar al get el campo activo en true

2021-02-09 17:38 UTC, negro89 commented on src/app/core/mpi/services/paciente-buscar.service.ts
> +            sexo: pacienteEscaneado.sexo
hecho!

2021-02-09 18:08 UTC, condorpiedra approved these changes

2021-02-10 15:28 UTC, MCele approved these changes

2021-02-26 13:01 UTC, merged