TOP - Permite modificar profesional al dar turno
andes/app pull request #2125
Opened 2021-02-02 16:01 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/TOP-104

### Funcionalidad desarrollada 

1. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-02-02 17:08 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3198](http://condorpiedra.andes.gob.ar:85/3198/mochawesome.html)
CYPRESS RUN: [2320](https://dashboard.cypress.io/projects/xr7gft/runs/2320/specs)
TEST START: 2021-02-02T16:58:04.007Z
TOTAL: 354
SUCCESS: 346
FAIL: 8
SKIPPED: 0

2021-02-04 16:20 UTC, juuliotero approved these changes

2021-02-04 16:25 UTC, liquid36 commented
USUARIO: mpalavecino  
BUILD NUMBER: [3215](http://condorpiedra.andes.gob.ar:85/3215/mochawesome.html)
CYPRESS RUN: [2337](https://dashboard.cypress.io/projects/xr7gft/runs/2337/specs)
TEST START: 2021-02-04T16:24:18.215Z
TOTAL: 354
SUCCESS: 352
FAIL: 2
SKIPPED: 0

2021-02-04 16:36 UTC, liquid36 commented
USUARIO: mpalavecino  
BUILD NUMBER: [3216](http://condorpiedra.andes.gob.ar:85/3216/mochawesome.html)
CYPRESS RUN: [2338](https://dashboard.cypress.io/projects/xr7gft/runs/2338/specs)
TEST START: 2021-02-04T16:35:22.724Z
TOTAL: 3
SUCCESS: 3
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-02-04 16:39 UTC, palita1991 approved these changes

2021-02-05 14:10 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3229](http://condorpiedra.andes.gob.ar:85/3229/mochawesome.html)
CYPRESS RUN: [2351](https://dashboard.cypress.io/projects/xr7gft/runs/2351/specs)
TEST START: 2021-02-05T14:09:43.193Z
TOTAL: 354
SUCCESS: 352
FAIL: 2
SKIPPED: 0

2021-02-05 15:41 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3236](http://condorpiedra.andes.gob.ar:85/3236/mochawesome.html)
CYPRESS RUN: [2358](https://dashboard.cypress.io/projects/xr7gft/runs/2358/specs)
TEST START: 2021-02-05T15:40:49.362Z
TOTAL: 323
SUCCESS: 316
FAIL: 7
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-02-05 16:21 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3239](http://condorpiedra.andes.gob.ar:85/3239/mochawesome.html)
CYPRESS RUN: [2361](https://dashboard.cypress.io/projects/xr7gft/runs/2361/specs)
TEST START: 2021-02-05T16:20:42.176Z
TOTAL: 354
SUCCESS: 354
FAIL: 0
SKIPPED: 0

2021-02-08 18:20 UTC, liquid36 requested changes
Si quito el filtro, me sigue mostrando las mismas agendas. Debería mostrar todo lo disponible.

2021-02-11 12:32 UTC, negro89 commented
> Si quito el filtro, me sigue mostrando las mismas agendas. Debería mostrar todo lo disponible.

Aplicados los cambios @liquid36

2021-02-11 13:06 UTC, liquid36 approved these changes

2021-02-11 16:01 UTC, merged