COM: crea derivación como prestación
andes/app pull request #2126
Opened 2021-02-02 17:34 UTC by plammel

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/COM-52
### Funcionalidad desarrollada 

1. Reemplaza 'detalle' de derivación por prestación
2. Incluye workflow de registro de prestación en RUP al momento de crear un nueva derivación.
3. 

### UserStory llegó a completarse

- [x] Si https://proyectos.andes.gob.ar/browse/COM-52
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [x] Si https://github.com/andes/api/pull/1264
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2021-02-03 02:22 UTC, sychus approved these changes
Me re gustó como quedo!!! un par de detalles a revisar.
1) No me termina de convencer como se el detalle de la prestación ¿UI/UX podrá ayudar?
2) Hay un errorcito en el build:  **src/app/modules/rup/components/huds/vistaPrestacion.ts:20:14 - error NG6007: The Component 'VistaPrestacionComponent' is declared by more than one NgModule.**

2021-02-03 02:22 UTC, sychus commented on src/app/modules/rup/services/elementosRUP.service.ts
> +            semanticTag: 'procedimiento'
Que les parece si usamos esta concepto? @plammel  @liquid36 @silviroa  @kroce  @condorpiedra 

   traslado del paciente (procedimiento)
SCTID: 107724000

107724000 | traslado del paciente (procedimiento) |
  es   traslado del paciente (procedimiento)
  es   traslado del paciente
  es   Cumplimiento de los pasos necesarios para trasladar a un paciente entre establecimientos asitenciales
  en   Transfer of patient
  en   Transfer of patient procedure
  en   Patient transfer
  en   Performance of the steps necessary to transfer a patient between locations of care delivery
  en   Patient transfer (procedure)
  en   Transfer care

2021-02-03 17:11 UTC, juuliotero requested changes
![image](https://user-images.githubusercontent.com/7090371/106783095-ab62c000-6629-11eb-9f01-989284a9a9c6.png)

Cuando voy a ver el detalle de una derivación vieja, me muestra un error ya que va a buscar la prestación asociada

2021-02-05 14:30 UTC, martinebucarey commented
- Me tira el mismo error que a Juli
![Captura de pantalla -2021-02-05 11-23-41](https://user-images.githubusercontent.com/56874534/107046312-403df880-67a5-11eb-8ad1-d0bc832e8462.png)

- El error en el build si no me equivoco es porque el componente `VistaPrestacionComponent` esta declarado en `COMModule` y `ElementosRUPModule`

2021-02-08 14:08 UTC, palita1991 requested changes
Revisar lint @plammel 

![image](https://user-images.githubusercontent.com/30004190/107230473-e421e100-69fd-11eb-9002-75da17a3dba0.png)

2021-02-09 14:30 UTC, sychus commented
Al momento de aceptar o rechazar una derivación vieja, también da el error que comentan @juuliotero y @martinebucarey. Va ejemplo: 
![image](https://user-images.githubusercontent.com/19353464/107377825-244e9580-6aca-11eb-964d-472042ffd93b.png)

2021-02-09 14:31 UTC, sychus requested changes
Revisar interacción con derivaciones anteriores.

2021-02-09 16:59 UTC, juuliotero requested changes
- Cuando ingresas a ver la prestación, por consola aparece el siguiente error:

Uncaught (in promise): Error: Type VistaPrestacionComponent is part of the declarations of 2 modules: COMModule and ElementosRUPModule! Please consider moving VistaPrestacionComponent to a higher module that imports COMModule and ElementosRUPModule. You can also create a new NgModule that exports and includes VistaPrestacionComponent then import that NgModule in COMModule and ElementosRUPModule.

- Como dijo Hugo, hay que ver los errores que da cuando abris derivaciones previas a este cambio porque sigue dando el error.

- Observación pero no se si es posible. Por ahí cuando no tiene registros la consulta mostrar algún mensaje de 'No hay registros' porque da la impresión de que cargara algo mal.

![image](https://user-images.githubusercontent.com/7090371/107398973-f7f14400-6ade-11eb-8f58-605fb834cb73.png)

2021-02-09 18:51 UTC, plammel commented
> * Cuando ingresas a ver la prestación, por consola aparece el siguiente error:
> 
> Uncaught (in promise): Error: Type VistaPrestacionComponent is part of the declarations of 2 modules: COMModule and ElementosRUPModule! Please consider moving VistaPrestacionComponent to a higher module that imports COMModule and ElementosRUPModule. You can also create a new NgModule that exports and includes VistaPrestacionComponent then import that NgModule in COMModule and ElementosRUPModule.
> 
> * Como dijo Hugo, hay que ver los errores que da cuando abris derivaciones previas a este cambio porque sigue dando el error.
> * Observación pero no se si es posible. Por ahí cuando no tiene registros la consulta mostrar algún mensaje de 'No hay registros' porque da la impresión de que cargara algo mal.
> 
> ![image](https://user-images.githubusercontent.com/7090371/107398973-f7f14400-6ade-11eb-8f58-605fb834cb73.png)

@juuliotero Los errores señalados debieran estar ya fixeados. Porfa actualizar las branches locales.
Respecto a la sugerencia de "Registros de consulta", solo es implementable hacia dentro del componenete VistaPrestacion. Ver:
https://proyectos.andes.gob.ar/browse/MISC-123
https://proyectos.andes.gob.ar/browse/MISC-127

2021-02-10 12:59 UTC, juuliotero approved these changes

2021-02-10 13:00 UTC, juuliotero commented
> > * Cuando ingresas a ver la prestación, por consola aparece el siguiente error:
> > 
> > Uncaught (in promise): Error: Type VistaPrestacionComponent is part of the declarations of 2 modules: COMModule and ElementosRUPModule! Please consider moving VistaPrestacionComponent to a higher module that imports COMModule and ElementosRUPModule. You can also create a new NgModule that exports and includes VistaPrestacionComponent then import that NgModule in COMModule and ElementosRUPModule.
> > 
> > * Como dijo Hugo, hay que ver los errores que da cuando abris derivaciones previas a este cambio porque sigue dando el error.
> > * Observación pero no se si es posible. Por ahí cuando no tiene registros la consulta mostrar algún mensaje de 'No hay registros' porque da la impresión de que cargara algo mal.
> > 
> > ![image](https://user-images.githubusercontent.com/7090371/107398973-f7f14400-6ade-11eb-8f58-605fb834cb73.png)
> 
> @juuliotero Los errores señalados debieran estar ya fixeados. Porfa actualizar las branches locales.
> Respecto a la sugerencia de "Registros de consulta", solo es implementable hacia dentro del componenete VistaPrestacion. Ver:
> https://proyectos.andes.gob.ar/browse/MISC-123
> https://proyectos.andes.gob.ar/browse/MISC-127

Genial. Quedaría solucionar los conflictos con master nada más.

2021-02-10 13:47 UTC, sychus approved these changes

2021-02-11 10:55 UTC, JSantarelli approved these changes
**Next:** Mejorar componente vista-prestación

2021-02-11 11:22 UTC, palita1991 commented
> **Next:** Mejorar componente vista-prestación

Me adhiero al comentario de @JSantarelli

2021-02-11 11:22 UTC, palita1991 approved these changes

2021-03-16 15:59 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [3576](http://condorpiedra.andes.gob.ar:85/3576/mochawesome.html)
CYPRESS RUN: [2659](https://dashboard.cypress.io/projects/xr7gft/runs/2659/specs)
TEST START: 2021-03-16T15:58:01.564Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-04-07 15:16 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [3716](http://condorpiedra.andes.gob.ar:85/3716/mochawesome.html)
CYPRESS RUN: [2786](https://dashboard.cypress.io/projects/xr7gft/runs/2786/specs)
TEST START: 2021-04-07T15:12:41.039Z
TOTAL: 287
SUCCESS: 276
FAIL: 11
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-04-08 12:11 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [3723](http://condorpiedra.andes.gob.ar:85/3723/mochawesome.html)
CYPRESS RUN: [2793](https://dashboard.cypress.io/projects/xr7gft/runs/2793/specs)
TEST START: 2021-04-08T12:08:52.252Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-04-08 14:17 UTC, palita1991 requested changes
@plammel Si vas a internacion y le creas una epicrisis a un paciente, el boton celeste del footer en lugar de decir mapa de camas dice "COM"
![image](https://user-images.githubusercontent.com/30004190/114042430-ce913200-985b-11eb-9b25-12a07265a530.png)

2021-04-09 18:48 UTC, plammel commented
> @plammel Si vas a internacion y le creas una epicrisis a un paciente, el boton celeste del footer en lugar de decir mapa de camas dice "COM"
> ![image](https://user-images.githubusercontent.com/30004190/114042430-ce913200-985b-11eb-9b25-12a07265a530.png)

@palita1991 
Se corrige con https://github.com/andes/app/pull/2207
Merger branches localmente para testear

2021-04-14 12:39 UTC, palita1991 approved these changes

2021-04-15 18:07 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [3774](http://condorpiedra.andes.gob.ar:85/3774/mochawesome.html)
CYPRESS RUN: [2839](https://dashboard.cypress.io/projects/xr7gft/runs/2839/specs)
TEST START: 2021-04-15T18:04:55.331Z
TOTAL: 366
SUCCESS: 365
FAIL: 1
SKIPPED: 0

2021-04-15 19:36 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [3779](http://condorpiedra.andes.gob.ar:85/3779/mochawesome.html)
CYPRESS RUN: [2844](https://dashboard.cypress.io/projects/xr7gft/runs/2844/specs)
TEST START: 2021-04-15T19:33:24.331Z
TOTAL: 316
SUCCESS: 314
FAIL: 2
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-04-16 13:18 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [3783](http://condorpiedra.andes.gob.ar:85/3783/mochawesome.html)
CYPRESS RUN: [2848](https://dashboard.cypress.io/projects/xr7gft/runs/2848/specs)
TEST START: 2021-04-16T13:15:28.237Z
TOTAL: 366
SUCCESS: 359
FAIL: 7
SKIPPED: 0

2021-04-16 13:44 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [3785](http://condorpiedra.andes.gob.ar:85/3785/mochawesome.html)
CYPRESS RUN: [2850](https://dashboard.cypress.io/projects/xr7gft/runs/2850/specs)
TEST START: 2021-04-16T13:41:09.246Z
TOTAL: 366
SUCCESS: 366
FAIL: 0
SKIPPED: 0

2021-04-20 12:16 UTC, merged