refactor(HUDS)se agrega filtro organizaciones
andes/app pull request #2128
Opened 2021-02-03 16:26 UTC by waltergarrido

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/HUDS-33
### Funcionalidad desarrollada 

1. Se agrega el filtro de organizaciones para la busqueda.
2. 
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-02-03 16:37 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3206](http://condorpiedra.andes.gob.ar:85/3206/mochawesome.html)
CYPRESS RUN: [2328](https://dashboard.cypress.io/projects/xr7gft/runs/2328/specs)
TEST START: 2021-02-03T16:36:44.477Z
TOTAL: 354
SUCCESS: 354
FAIL: 0
SKIPPED: 0

2021-02-04 02:31 UTC, sychus requested changes

2021-02-04 02:31 UTC, sychus commented on src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
> +            this.prestaciones = this.prestaciones.filter(p => p.data.ejecucion.organizacion.id === this.organizacionSeleccionada.id);
```suggestion
            this.prestaciones = this.prestaciones.filter(p => p.data.ejecucion?.organizacion.id === this.organizacionSeleccionada.id);
```
Ya que tal vez no tengan info en ejecucion.organizacion (ejemplo con inicio en top) y te va a pinchar sino.

2021-02-04 12:04 UTC, waltergarrido commented on src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
> +            this.prestaciones = this.prestaciones.filter(p => p.data.ejecucion.organizacion.id === this.organizacionSeleccionada.id);
@sychus corregido

2021-02-04 12:52 UTC, sychus approved these changes

2021-02-04 12:53 UTC, palita1991 reviewed
Lo dejo como comentario para ver si alguno mas le pasa, apuntando a local o demo en algunos casos me sale un problemita en el plex-select. @kroce si después podes revisarlo también porfa para corroborar que no sea solo yo al que le pasa.
![image](https://user-images.githubusercontent.com/30004190/106894763-25e51b80-66ce-11eb-8e96-6ea242f693fe.png)

2021-02-04 13:26 UTC, waltergarrido commented
> Lo dejo como comentario para ver si alguno mas le pasa, apuntando a local o demo en algunos casos me sale un problemita en el plex-select. @kroce si después podes revisarlo también porfa para corroborar que no sea solo yo al que le pasa.
> ![image](https://user-images.githubusercontent.com/30004190/106894763-25e51b80-66ce-11eb-8e96-6ea242f693fe.png)

@palita1991 fue corregido , hay algunas prestaciones que no tiene organización asociada , agregue un control y quedo ok .

2021-02-04 15:46 UTC, palita1991 approved these changes

2021-02-08 17:07 UTC, liquid36 approved these changes

2021-02-08 17:53 UTC, merged