CITAS - Fix solapamiento de turnos en agendas dinámicas
andes/app pull request #2129
Opened 2021-02-03 18:54 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/CIT-104

### Funcionalidad desarrollada 

1. Se modificó servicio de turno para que 'saveDinamica' retorne turno en lugar de agenda
2. Uso de funciones rxjs en funcion 'guardarDatosTurno'

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si   https://github.com/andes/api/pull/1269
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-02-03 19:12 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3207](http://condorpiedra.andes.gob.ar:85/3207/mochawesome.html)
CYPRESS RUN: [2329](https://dashboard.cypress.io/projects/xr7gft/runs/2329/specs)
TEST START: 2021-02-03T19:11:12.214Z
TOTAL: 354
SUCCESS: 354
FAIL: 0
SKIPPED: 0

2021-02-05 11:31 UTC, condorpiedra requested changes

2021-02-05 11:31 UTC, condorpiedra commented on src/app/components/turnos/autocitar/dinamica.component.ts
> +                            mergeMap(idturnoDado => {
Se podría utilizar switchMap? porque en este caso no veo que sea necesario encadenar el flujo de los dos observables

2021-02-05 15:41 UTC, condorpiedra approved these changes

2021-02-05 18:28 UTC, kroce approved these changes

2021-02-05 19:01 UTC, MCele approved these changes

2021-02-08 11:13 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [3252](http://condorpiedra.andes.gob.ar:85/3252/mochawesome.html)
CYPRESS RUN: [2368](https://dashboard.cypress.io/projects/xr7gft/runs/2368/specs)
TEST START: 2021-02-08T11:12:35.247Z
TOTAL: 354
SUCCESS: 354
FAIL: 0
SKIPPED: 0

2021-02-08 11:14 UTC, merged