EPIDEMIOLOGIA: Form buillder y punto de inicio de ficha epidemiologica
andes/app pull request #2131
Opened 2021-02-04 15:18 UTC by martinebucarey

### Requerimiento
https://proyectos.andes.gob.ar/browse/EP-3
https://proyectos.andes.gob.ar/browse/EP-17

### Funcionalidad desarrollada 

1. Se crea formBuilder para crear formularios de forma dinámica.
2. Se crea el punto de inicio de la ficha epidemiología, donde una vez seleccionado un paciente se podrá cargar una nueva ficha o visualizad/editar alguna existente.
3. Se crea la ficha Covid-19 con los campos solicitados.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [x] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No
- En proceso

### Observaciones
- En la base de datos de test se encuentra guardado el modelo de ficha "covid19"

2021-02-10 16:58 UTC, negro89 approved these changes

2021-02-10 16:58 UTC, negro89 commented on src/app/components/inicio/inicio.component.ts
> -
TOC detected

2021-02-12 13:22 UTC, plammel commented on src/app/directives/select-search.directive.ts
> +    }
Sugiero realizar en control de subscripciones con el decorator `@Unsubscribe`

2021-02-12 14:12 UTC, plammel requested changes

2021-02-12 14:12 UTC, plammel commented on src/app/modules/forms-builder/components/forms-crud/forms-crud.component.html
> +                        </div> -->
Queda comentado por alguna razón o se puede limpiar?

2021-02-12 14:12 UTC, plammel commented on src/app/modules/forms-builder/components/forms-crud/forms-crud.component.html
> +                        </div> -->
Idem anterior

2021-02-12 14:12 UTC, plammel commented on src/app/modules/forms-builder/services/form.service.ts
> +}
La interface del form debería estar en un archivo `IForm.interface` aparte.

2021-02-18 15:29 UTC, martinebucarey commented on src/app/directives/select-search.directive.ts
> +    }
Se debe hacer en el onDestroy para que el getData del select no quede infinitamente escuchando.

2021-02-18 15:29 UTC, martinebucarey commented on src/app/modules/epidemiologia/components/ficha-covid/ficha-covid.component.ts
> +      label: 'fecha último contacto',
Modificado, igualmente estaba hecho así porque los títulos del plex-table los pasa todo a mayúscula.

2021-02-18 15:29 UTC, martinebucarey commented on src/app/modules/epidemiologia/components/ficha-covid/ficha-covid.component.ts
> +      label: 'tipo de contacto',
Hecho

2021-02-18 15:30 UTC, martinebucarey commented on src/app/modules/epidemiologia/components/ficha-covid/ficha-covid.component.ts
> +  registrarFicha() {
Si quedo muy grande, la pase a dos funciones.

2021-02-18 15:30 UTC, martinebucarey commented on src/app/modules/epidemiologia/components/ficha-covid/ficha-covid.component.ts
> +        }
Hecho

2021-02-19 15:39 UTC, plammel commented on src/app/directives/select-search.directive.ts
> +    }
Genial!

2021-02-19 16:23 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3371](http://condorpiedra.andes.gob.ar:85/3371/mochawesome.html)
CYPRESS RUN: [2474](https://dashboard.cypress.io/projects/xr7gft/runs/2474/specs)
TEST START: 2021-02-19T16:21:56.078Z
TOTAL: 361
SUCCESS: 358
FAIL: 2
SKIPPED: 1

2021-02-19 16:49 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3375](http://condorpiedra.andes.gob.ar:85/3375/mochawesome.html)
CYPRESS RUN: [2478](https://dashboard.cypress.io/projects/xr7gft/runs/2478/specs)
TEST START: 2021-02-19T16:47:10.154Z
TOTAL: 7
SUCCESS: 7
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-02-19 16:59 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3376](http://condorpiedra.andes.gob.ar:85/3376/mochawesome.html)
CYPRESS RUN: [2479](https://dashboard.cypress.io/projects/xr7gft/runs/2479/specs)
TEST START: 2021-02-19T16:58:09.179Z
TOTAL: 361
SUCCESS: 360
FAIL: 0
SKIPPED: 1

2021-02-22 11:40 UTC, andrrrl requested changes
:flushed:

2021-02-22 11:40 UTC, andrrrl commented on src/app/directives/select-search.directive.ts
> +    selector: '[ssSearch]'
Angular en sus guías de estilos [recomiendan usar dahsed-case](https://angular.io/guide/styleguide#style-05-02) para selectores. 
Además es poco claro qué significa "ssSearch". En este caso podría quedar `[select-search]` o `[dynamic-search]`... o algo que se te ocurra.

2021-02-22 13:53 UTC, sychus commented on src/app/modules/forms-builder/services/form.service.ts
> +}
Solved @plammel

2021-02-22 14:15 UTC, martinebucarey commented on src/app/directives/select-search.directive.ts
> +    selector: '[ssSearch]'
Es una directiva por eso esta el camelCase [https://angular.io/guide/attribute-directives](url)

2021-02-24 14:24 UTC, plammel approved these changes

2021-02-24 15:16 UTC, palita1991 approved these changes

2021-03-02 16:45 UTC, andrrrl commented on src/app/directives/select-search.directive.ts
> +    selector: '[ssSearch]'
Si, es cierto, mala mía. igual es poco claro ssSearch, qué hace? busca en la **s**ub**s**ecretaría?

2021-03-02 18:04 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3479](http://condorpiedra.andes.gob.ar:85/3479/mochawesome.html)
CYPRESS RUN: [2573](https://dashboard.cypress.io/projects/xr7gft/runs/2573/specs)
TEST START: 2021-03-02T17:53:35.457Z
TOTAL: 361
SUCCESS: 351
FAIL: 9
SKIPPED: 1

2021-03-02 18:24 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3480](http://condorpiedra.andes.gob.ar:85/3480/mochawesome.html)
CYPRESS RUN: [2574](https://dashboard.cypress.io/projects/xr7gft/runs/2574/specs)
TEST START: 2021-03-02T18:23:21.748Z
TOTAL: 361
SUCCESS: 360
FAIL: 0
SKIPPED: 1

2021-03-04 16:20 UTC, merged