refactor(RUP): se mantiene el formato de texto en las diferentes pest…
andes/app pull request #2135
Opened 2021-02-17 15:05 UTC by waltergarrido

…añas

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/RUP-242
### Funcionalidad desarrollada 

1. se reeamplaza textTarea por plex-text para mantener el formato del texto en las diferentes pestañas
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-02-18 12:40 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3343](http://condorpiedra.andes.gob.ar:85/3343/mochawesome.html)
CYPRESS RUN: [2450](https://dashboard.cypress.io/projects/xr7gft/runs/2450/specs)
TEST START: 2021-02-18T12:39:18.732Z
TOTAL: 358
SUCCESS: 356
FAIL: 1
SKIPPED: 1

2021-02-18 12:44 UTC, liquid36 requested changes
Tener en cuenta que la epicrisis esta en otra Componente RUP, pero tiene el mismo comportamiento.

2021-02-18 12:44 UTC, liquid36 commented
src/app/modules/rup/components/elementos/deprecated/elementoDeRegistro.html

2021-02-18 13:01 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3345](http://condorpiedra.andes.gob.ar:85/3345/mochawesome.html)
CYPRESS RUN: [2452](https://dashboard.cypress.io/projects/xr7gft/runs/2452/specs)
TEST START: 2021-02-18T13:00:18.189Z
TOTAL: 358
SUCCESS: 356
FAIL: 1
SKIPPED: 1

2021-02-18 13:01 UTC, liquid36 commented
También revisar los test de seccionado que estan fallando.

2021-02-24 19:07 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3450](http://condorpiedra.andes.gob.ar:85/3450/mochawesome.html)
CYPRESS RUN: [2545](https://dashboard.cypress.io/projects/xr7gft/runs/2545/specs)
TEST START: 2021-02-24T19:06:45.853Z
TOTAL: 358
SUCCESS: 355
FAIL: 2
SKIPPED: 1

2021-02-25 13:50 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3458](http://condorpiedra.andes.gob.ar:85/3458/mochawesome.html)
CYPRESS RUN: [2552](https://dashboard.cypress.io/projects/xr7gft/runs/2552/specs)
TEST START: 2021-02-25T13:49:52.791Z
TOTAL: 358
SUCCESS: 357
FAIL: 0
SKIPPED: 1

2021-02-26 13:20 UTC, liquid36 requested changes

2021-02-26 13:20 UTC, liquid36 commented on src/app/modules/rup/components/elementos/rupers/seccionado/seccion.component.html
> +        <ng-container *ngIf="!(conceptosSeleccionar?.length > 0) && params.showText">
```suggestion
        <div  [class]="colForText" *ngIf="!(conceptosSeleccionar?.length > 0) && params.showText">
```

Esto tiene que seguir siendo un div con las clases que corresponde, sino se pierde la funcionalidad de orientación de los componentes.

2021-02-26 14:00 UTC, waltergarrido commented on src/app/modules/rup/components/elementos/rupers/seccionado/seccion.component.html
> +        <ng-container *ngIf="!(conceptosSeleccionar?.length > 0) && params.showText">
@liquid36  corregido

2021-02-26 14:04 UTC, liquid36 approved these changes

2021-02-26 14:16 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3469](http://condorpiedra.andes.gob.ar:85/3469/mochawesome.html)
CYPRESS RUN: [2563](https://dashboard.cypress.io/projects/xr7gft/runs/2563/specs)
TEST START: 2021-02-26T14:15:43.739Z
TOTAL: 358
SUCCESS: 357
FAIL: 0
SKIPPED: 1

2021-02-26 16:16 UTC, palita1991 approved these changes

2021-03-01 16:58 UTC, merged