CITAS - Impide liberar turno con prestación ya iniciada
andes/app pull request #2138
Opened 2021-02-19 12:19 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/CIT-74

### Funcionalidad desarrollada 

1. Al intentar liberar un turno se verifica si existe una prestación asociada. Si existe, se muestra un cartel invasivo explicando al usuario que no puede liberar dicho turno.

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-02-19 12:44 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3365](http://condorpiedra.andes.gob.ar:85/3365/mochawesome.html)
CYPRESS RUN: [2468](https://dashboard.cypress.io/projects/xr7gft/runs/2468/specs)
TEST START: 2021-02-19T12:33:37.878Z
TOTAL: 358
SUCCESS: 354
FAIL: 3
SKIPPED: 1

2021-02-19 17:17 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3378](http://condorpiedra.andes.gob.ar:85/3378/mochawesome.html)
CYPRESS RUN: [2481](https://dashboard.cypress.io/projects/xr7gft/runs/2481/specs)
TEST START: 2021-02-19T17:15:57.861Z
TOTAL: 358
SUCCESS: 355
FAIL: 2
SKIPPED: 1

2021-02-19 18:37 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3390](http://condorpiedra.andes.gob.ar:85/3390/mochawesome.html)
CYPRESS RUN: [2493](https://dashboard.cypress.io/projects/xr7gft/runs/2493/specs)
TEST START: 2021-02-19T18:36:40.727Z
TOTAL: 358
SUCCESS: 357
FAIL: 0
SKIPPED: 1

2021-02-22 16:05 UTC, palita1991 reviewed
@negro89  Resuelve lo que se describe en la User. Antes de aprobarlo, quisiera dejar aca un video con el caso inverso, es decir, que se inicie prestacion a un paciente que fue liberado. Si se resuelve aca espero los cambios sino lo apruebo. Dejo video con los pasos a seguir
https://www.loom.com/share/796c4992dc4f49b59611a7329ec13e5d

2021-02-23 11:20 UTC, palita1991 commented
> @negro89 Resuelve lo que se describe en la User. Antes de aprobarlo, quisiera dejar aca un video con el caso inverso, es decir, que se inicie prestacion a un paciente que fue liberado. Si se resuelve aca espero los cambios sino lo apruebo. Dejo video con los pasos a seguir
> 
> https://www.loom.com/share/796c4992dc4f49b59611a7329ec13e5d

Según lo charlado con @negro89 y @condorpiedra queda para una user nueva este bug.

2021-02-23 11:20 UTC, palita1991 approved these changes

2021-02-23 11:58 UTC, condorpiedra approved these changes

2021-02-23 16:44 UTC, kroce commented
No pude reproducir en demo el bug reportado en https://proyectos.andes.gob.ar/browse/CIT-74
Capaz que es haciendo una serie de pasos específicos. Probé desde el gestor de agendas y desde el punto de inicio de CITAS y en ambas pantallas me saltó
![image (35)](https://user-images.githubusercontent.com/18030170/108876471-02cacf00-75dd-11eb-82d7-8d6cf338babf.png)

2021-02-24 14:51 UTC, plammel requested changes

2021-02-24 14:51 UTC, plammel commented on src/app/components/turnos/gestor-agendas/operaciones-turnos/liberar-turno.component.ts
> +                const estadoPrestacion = prestacion[0].estados[prestacion[0].estados.length - 1].tipo;
Evaluar directamente el atributo `estadoActual.tipo`
```suggestion
                const estadoPrestacion = prestacion[0].estadoActual.tipo;
```

2021-03-01 18:00 UTC, liquid36 commented
Buenas, como dice Caro. Este problema ya estaba resuelvo desde la API.

@negro89  A tener en cuenta que un turno se libera desde varios lugares. Así que el control esta correctamente hecho en la API. 

Opino de cerrar este PR, y de ultima mejorar el cartel de error.  Nada más.

2021-03-01 18:30 UTC, closed without merging