MPI - Corrige edición de contactos en ventanilla
andes/app pull request #2141
Opened 2021-02-19 14:24 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MPI-327

### Funcionalidad desarrollada 

1. Actualización de template de edición de contactos
2. Agrega patrón de contenido al valor de contacto
3. Corrige visibilidad de select al borrar el tipo de contacto (bug)

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-02-19 16:43 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3373](http://condorpiedra.andes.gob.ar:85/3373/mochawesome.html)
CYPRESS RUN: [2476](https://dashboard.cypress.io/projects/xr7gft/runs/2476/specs)
TEST START: 2021-02-19T16:41:55.642Z
TOTAL: 269
SUCCESS: 259
FAIL: 9
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-02-19 17:33 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3380](http://condorpiedra.andes.gob.ar:85/3380/mochawesome.html)
CYPRESS RUN: [2483](https://dashboard.cypress.io/projects/xr7gft/runs/2483/specs)
TEST START: 2021-02-19T17:32:22.891Z
TOTAL: 358
SUCCESS: 356
FAIL: 1
SKIPPED: 1

2021-02-19 18:26 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3389](http://condorpiedra.andes.gob.ar:85/3389/mochawesome.html)
CYPRESS RUN: [2492](https://dashboard.cypress.io/projects/xr7gft/runs/2492/specs)
TEST START: 2021-02-19T18:20:33.136Z
TOTAL: 273
SUCCESS: 260
FAIL: 4
SKIPPED: 9
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-02-19 19:46 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3392](http://condorpiedra.andes.gob.ar:85/3392/mochawesome.html)
CYPRESS RUN: [2495](https://dashboard.cypress.io/projects/xr7gft/runs/2495/specs)
TEST START: 2021-02-19T19:45:30.090Z
TOTAL: 344
SUCCESS: 341
FAIL: -6
SKIPPED: 9

2021-02-23 11:26 UTC, palita1991 approved these changes

2021-02-23 11:51 UTC, liquid36 requested changes
![image](https://user-images.githubusercontent.com/3813270/108839654-1dd51900-75b4-11eb-99e7-9bc0b35e6b42.png)

al querer guardar con el contacto en blanco sigue tirando el error.

1. No debería ocultarse el plex-phone.
2. Deberían tener required y que el formulario los valide. 
3. Para guardar en blanco, debes borrarlo con la cruz sino el formulario no te deja.

2021-02-23 13:03 UTC, palita1991 requested changes
Adjunto video https://www.loom.com/share/c542acbc35d443d7bdc5d3fb23e14e13 sobre lo que comentaba @liquid36

2021-02-23 19:59 UTC, negro89 commented
> Adjunto video
> 
> https://www.loom.com/share/c542acbc35d443d7bdc5d3fb23e14e13 sobre lo que comentaba @liquid36

Corregido!

2021-02-24 14:29 UTC, liquid36 approved these changes

2021-02-24 18:23 UTC, palita1991 approved these changes

2021-02-25 17:05 UTC, MCele approved these changes

2021-02-26 15:56 UTC, merged