CIT: new date fecha prestacion dinamica
andes/app pull request #2142
Opened 2021-02-19 14:33 UTC by plammel

### Requerimiento
 
https://github.com/andes/api/pull/1279#issuecomment-782017873
### Funcionalidad desarrollada 

1. Cuando se inicia una prestación de un turno de agenda dinámica, se verifica si la fecha de turno es anterior a la fecha actual.
2. Caso afirmativo, se guarda fechaHora de ejecución la fechaHora del turno, caso negativo, new date.
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2021-02-23 11:55 UTC, condorpiedra requested changes

2021-02-23 11:55 UTC, condorpiedra commented on src/app/modules/rup/services/prestaciones.service.ts
> +        const esAnterior = (moment(fechaTurno).format('YYYY-MM-DD') < moment().startOf('day').format('YYYY-MM-DD'));
¿Es necesario formatear la fecha para realizar la comparación?

2021-03-01 16:08 UTC, liquid36 approved these changes

2021-03-01 16:20 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3474](http://condorpiedra.andes.gob.ar:85/3474/mochawesome.html)
CYPRESS RUN: [2568](https://dashboard.cypress.io/projects/xr7gft/runs/2568/specs)
TEST START: 2021-03-01T16:19:41.457Z
TOTAL: 358
SUCCESS: 357
FAIL: 0
SKIPPED: 1

2021-03-02 16:15 UTC, merged