Prestamo de carpetas - Fix en filtro de prestaciones y actualización (uso) de componentes plex
andes/app pull request #2144
Opened 2021-02-22 18:31 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MISC-90

### Funcionalidad desarrollada 

1. Fix del error reportado modificando control del valor ingresado en filtro de prestaciones
2. Reemplazo de código para uso de algunos componentes plex
3. Se agrega botón para cierre de sidebar en búsqueda de paciente

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-02-22 18:42 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3410](http://condorpiedra.andes.gob.ar:85/3410/mochawesome.html)
CYPRESS RUN: [2512](https://dashboard.cypress.io/projects/xr7gft/runs/2512/specs)
TEST START: 2021-02-22T18:41:32.740Z
TOTAL: 358
SUCCESS: 357
FAIL: 0
SKIPPED: 1

2021-02-22 18:46 UTC, condorpiedra requested changes

2021-02-22 18:46 UTC, condorpiedra commented on src/app/components/prestamosHC/prestamos/listar-prestamos.component.html
> +                         labe lField="nombre + '(' + servicio.nombre + ')'" ngModelOptions="{standalone: true}">
quedó con un espacio

2021-02-23 11:00 UTC, liquid36 commented on src/app/components/prestamosHC/prestamos/listar-prestamos.component.html
> +    <plex-grid cols="4" type="full">
Para los filtros se usa `plex-wrapper`.

2021-02-23 11:02 UTC, liquid36 commented on src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.html
> +        <div class="pb-2">
No es necesario el `div` dentro del plex-title

2021-02-23 11:03 UTC, liquid36 commented on src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.html
> +    <plex-grid cols="4">
Acá lo mismo, para filtros se usa `plex-wrapper`

2021-02-23 18:56 UTC, plammel commented
Revisé el PR pero no encontré correcciones más allá de las señaladas por los compañeros.
Mi único comentario/sugerencia, basado en mi experiencia personal, es que las tareas de boyscouting (que siempre son bienvenidas), cuando no involucran directamente al código afectado por el requerimiento original, es preferible pasarlas en un PR aparte en un commit de chore, para agilizar el merge y evitar una posible introducción de errores (me ha pasado 🙃)

2021-02-23 19:21 UTC, negro89 commented on src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.html
> +        <div class="pb-2">
Gracias marian. Si bien no es necesario, como el plex-title tiene un tamaño 'sm' los botones sobresalen y quedan desalineados. Otra opción es achicar los botones pero no quería que pierdan relevancia.
@JSantarelli o @andrrrl si tienen alguna observación al respecto bienvenida sea

2021-02-23 23:09 UTC, JSantarelli requested changes

2021-02-23 23:09 UTC, JSantarelli commented on src/app/components/prestamosHC/prestamos/listar-prestamos.component.html
> +            <plex-button class="pt-2 float-right" type="primary"
El [`<plex-wrapper>`](https://www.andes.gob.ar/plex/doc/components/PlexWrapperComponent.html) resuelve esta interacción internamente al alojar los inputs ocultos en un `<div>` con el selector 'collapse'. No es necesario agregar html extra.

2021-02-23 23:09 UTC, JSantarelli commented on src/app/components/prestamosHC/prestamos-hc.component.html
> +                <plex-button icon="close" type="danger" size="sm" (click)="hideSidebar()"></plex-button>
Ya que se toca el sidebar, se podría agregar 'type="invert"' así vamos unificando visualmente los paneles de toda la aplicación.

2021-02-23 23:09 UTC, JSantarelli commented on src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.html
> +            <plex-button class="pr-1" type="primary" icon="plus" title="Agregar solicitud manual"
Acción aditiva. El <plex-button> debería ser type="success".

2021-02-25 18:12 UTC, negro89 commented
@liquid36 @JSantarelli @condorpiedra ya están los cambios. Mil disculpas por subir todo junto, de haber sabido que se iba a extender tanto hacia dos PRs como comentó @plammel. Besis @palita1991

2021-02-25 18:26 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3463](http://condorpiedra.andes.gob.ar:85/3463/mochawesome.html)
CYPRESS RUN: [2557](https://dashboard.cypress.io/projects/xr7gft/runs/2557/specs)
TEST START: 2021-02-25T18:25:03.254Z
TOTAL: 358
SUCCESS: 357
FAIL: 0
SKIPPED: 1

2021-02-26 11:48 UTC, JSantarelli requested changes

2021-02-26 11:48 UTC, JSantarelli commented on src/app/components/prestamosHC/historial/historial-hc.component.html
> +        <plex-label *ngIf="paciente" titulo="No hay movimientos de prestamos de la
@negro89 el tratamiento que le venimos dando a este tipo de mensajes tiene que contemplar:
- que el icono queda por encima de la leyenda (agregar `direction="column"` al `<plex-label>`)
- que el mensaje **consta de dos partes:** un titulo notificando qué ocurre ('
_No hay solicitudes para los filtros consultados_' o 'No hay movimientos de prestamos de la carpeta consultada') y un subtitulo que le propone al usuario una acción ('_Comience realizando una búsqueda mediante los filtros en la parte superior de la pantalla_' o '_Corrobore el número de carpeta ingresado_').

- Cuando el usuario accede **por primera vez**, al no haber realizado ninguna búsqueda, el mensaje debería ser de ayuda, por ejemplo: '_Comience realizando una búsqueda_' y el subtitulo '_Utilice los filtros de la parte superior de la pantalla para filtrar por fecha, prestación o profesional_'. El icono también debería cambiar en éste segundo caso ('information-variant').

2021-02-26 12:37 UTC, liquid36 approved these changes
Todo ok, solo faltan los ultimos detalles de Julio.

2021-02-26 13:51 UTC, palita1991 approved these changes

2021-03-02 14:25 UTC, merged