In 252
andes/app pull request #2145
Opened 2021-02-23 20:57 UTC by waltergarrido

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/IN-252
### Funcionalidad desarrollada 

1. se crea el listado de recursos , se agrupa las camas por sectores.
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-02-23 21:05 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3433](http://condorpiedra.andes.gob.ar:85/3433/mochawesome.html)
CYPRESS RUN: [2528](https://dashboard.cypress.io/projects/xr7gft/runs/2528/specs)
TEST START: 2021-02-23T21:04:37.064Z
TOTAL: 358
SUCCESS: 357
FAIL: 0
SKIPPED: 1

2021-02-24 14:18 UTC, plammel requested changes
Cambiar el título del PR por uno más descriptivo.

2021-02-24 14:18 UTC, plammel commented on src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
> +    }
```suggestion
    verListadoRecursos() {
        this.listadoRecursos = !this.listadoRecursos;
    }
    
```
Sugerencia: un nombre más apropiado para esta función podría ser `toggleListadoRecursos`

2021-02-24 14:18 UTC, plammel commented on src/app/apps/rup/mapa-camas/views/mapa-camas-capa/recursos-listado/recursos-listado.component.ts
> +
```suggestion

```

2021-02-24 14:18 UTC, plammel commented on src/app/apps/rup/mapa-camas/views/mapa-camas-capa/recursos-listado/recursos-listado.component.ts
> +
```suggestion

```

2021-02-24 20:02 UTC, negro89 commented on src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
> +    }
O quizás se pueda cambiar el valor en el template, ya que no se realiza otra acción además de esta.

2021-02-24 21:13 UTC, negro89 approved these changes

2021-02-26 12:08 UTC, JSantarelli reviewed
El [botón que switchea](https://github.com/andes/app/blob/fbb87c6fe1cab61ecee17e95b720d0bd16beea00/src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html#L27) entre 'Listado de camas' y 'Listado de recursos' impacta directamente (y exclusivamente) sobre el listado. Quizás la ubicación de este botón sería más adecuada al nivel del `<plex-title>` del listado.

2021-02-26 12:30 UTC, waltergarrido commented
El [botón que switchea](https://github.com/andes/app/blob/fbb87c6fe1cab61ecee17e95b720d0bd16beea00/src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html#L27) entre 'Listado de camas' y 'Listado de recursos' impacta directamente (y exclusivamente) sobre el listado. Quizás la ubicación de este botón sería más adecuada al nivel del `<plex-title>` del listado.

@JSantarelli corregido

2021-02-26 12:31 UTC, waltergarrido commented on src/app/apps/rup/mapa-camas/views/mapa-camas-capa/recursos-listado/recursos-listado.component.ts
> +
@plammel corregido

2021-03-02 17:14 UTC, liquid36 requested changes
Falta que la cama quede como seleccionada.

Primera review

2021-03-02 17:14 UTC, liquid36 commented on src/app/apps/rup/mapa-camas/views/mapa-camas-capa/recursos-listado/recursos-listado.component.html
> +            <section class="w-50">
Quitar este <section>. Solo hace que el texto se caiga a una segunda linea.

2021-03-02 17:14 UTC, liquid36 commented on src/app/apps/rup/mapa-camas/views/mapa-camas-capa/recursos-listado/recursos-listado.component.ts
> +                        nombre: sector.sectorName.split(',').reverse().join(','),
```suggestion
                        nombre: sector.sectorName.split(',').reverse().join(', '),
```

2021-03-02 17:14 UTC, liquid36 commented on src/app/apps/rup/mapa-camas/views/mapa-camas-capa/recursos-listado/recursos-listado.component.ts
> +                    if (!(arreglo.length > 0)) {
Esta condición no tiene sentido, con el find es mas que suficiente.

2021-03-02 17:19 UTC, liquid36 commented on src/app/apps/rup/mapa-camas/views/mapa-camas-capa/recursos-listado/recursos-listado.component.html
> +        <plex-grid size="md" type="full">
```suggestion
        <plex-grid size="md" cols="3">
```

2021-03-02 17:32 UTC, liquid36 commented
Los botones de la cama no funcionan.

![image](https://user-images.githubusercontent.com/3813270/109689553-2acdab80-7b64-11eb-9ef0-e58916bc05f1.png)

2021-03-03 11:18 UTC, JSantarelli commented
Viendo el prototipo noté que falta la información secundaria en los cabezales de los accordions. La idea es que el usuario pueda previsualizar los recursos alojados en el sector antes de desplegar. Lo ven posible/útil?
![dato-secundario](https://user-images.githubusercontent.com/5895886/109797929-de807b00-7bf8-11eb-9100-fa3f03192ded.PNG)

2021-03-03 11:24 UTC, liquid36 commented
Esta @JSantarelli pero todo en una misma linea.

![image](https://user-images.githubusercontent.com/3813270/109798780-eee52580-7bf9-11eb-8181-332003a602dc.png)

2021-03-03 11:46 UTC, JSantarelli commented
Ah perfecto @liquid36, entonces el pedido sería desacoplar de allí esa info.

2021-03-05 10:46 UTC, JSantarelli requested changes

2021-03-05 10:46 UTC, JSantarelli commented on src/app/apps/rup/mapa-camas/views/mapa-camas-capa/recursos-listado/recursos-listado.component.html
> +                <plex-label size="lg" case="capitalize" titulo="{{ sector.nombre }}" icon="hospital">
Falta agregar subtitulo con los recursos que aloja el sector (actualmente todo en una misma línea en el título).
![dato-secundario](https://user-images.githubusercontent.com/5895886/110105185-d7877300-7d86-11eb-810d-dd8f9445ca55.PNG)

2021-03-11 11:38 UTC, waltergarrido commented on src/app/apps/rup/mapa-camas/views/mapa-camas-capa/recursos-listado/recursos-listado.component.html
> +                <plex-label size="lg" case="capitalize" titulo="{{ sector.nombre }}" icon="hospital">
@JSantarelli corregido

2021-03-11 11:38 UTC, waltergarrido commented on src/app/apps/rup/mapa-camas/views/mapa-camas-capa/recursos-listado/recursos-listado.component.ts
> +                    if (!(arreglo.length > 0)) {
@liquid36 corregido

2021-03-11 16:01 UTC, liquid36 reviewed
![image](https://user-images.githubusercontent.com/3813270/110815841-8e915c00-8269-11eb-8f01-a991b3682f86.png)

- Haría el icono de la cama más grande
- Sacaría el icono del paciente (ya hay uno)
- quitaría el nombre del sector de cada cama.
- En el headear del acordion veo muy desproporcionado el tamañan del icono contra el titulo principal.

@JSantarelli Qué opinas?

2021-03-12 14:18 UTC, liquid36 commented
No se puede deseleccionar una cama, para poder cambiar la hora del mapa.

2021-03-12 16:24 UTC, waltergarrido commented
No se puede deseleccionar una cama, para poder cambiar la hora del mapa.

@liquid36 corregido

2021-03-29 13:11 UTC, JSantarelli reviewed
Luego de internar un paciente, se cierran automáticamente todos los accordions. El usuario pierde foco y quizás hay probabilidades de que quiera seguir realizando operaciones sobre el paciente recientemente internado. La sugerencia es que el foco quede en el paciente internado (accordion correspondiente abierto y sidebar con detalle del paciente en cuestión).

https://user-images.githubusercontent.com/5895886/112841604-11daec00-9077-11eb-8225-d0c1954d3f12.mp4

2021-04-13 12:35 UTC, liquid36 approved these changes

2021-04-13 12:57 UTC, merged