Inscripcion vacunas
andes/app pull request #2149
Opened 2021-02-26 18:46 UTC by kroce

### Requerimiento

- Implementa formulario de inscripción a vacunación para los grupos vigentes: Mayores de 60 y personal de salud
- Envía a la api los datos con el formato correspondiente

### Funcionalidad desarrollada 

1. Nuevo módulo de carga de inscripciones que no requiere autenticación del usuario

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [x] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [x] Si (actualizar cuando suba PR @condorpiedra )
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2021-03-01 18:09 UTC, juuliotero commented on src/app/apps/vacunacion/services/inscripcion.service.ts
> +    // get(params: any): Observable<any[]> {
Eliminar código comentado

2021-03-01 18:09 UTC, juuliotero commented on src/app/apps/vacunacion/vacunacion.module.ts
> +// import { VaccinationConsultComponent } from './components/consult/consult.component';
Eliminar imports

2021-03-01 18:24 UTC, sychus requested changes
Separar en steps

2021-03-01 18:24 UTC, sychus commented on src/app/apps/vacunacion/components/inscripcion.component.html
> +                    <plex-label titulo="Condiciones de Salud" size="lg"></plex-label>
Lo de las condiciones de salud... lo haría en un siguiente paso (step by step.... uhh baby)

2021-03-01 18:26 UTC, juuliotero commented on src/app/apps/vacunacion/components/inscripcion.component.html
> +                    <plex-label titulo="Condiciones de Salud" size="lg"></plex-label>
Si se hace esto se podrían dejar los botones en el title, si no deberían ir al final del scroll así el usuario no tiene que volver arriba para guardar el formulario.

2021-03-01 18:44 UTC, palita1991 requested changes
Al momento de seleccionar el grupo de "Mayores de 60", al desactivar switch de "Mi DNI tiene numero de trámite", completar todos los campos y luego guardar te indica que el número de trámite es invalido.
![image](https://user-images.githubusercontent.com/30004190/109542742-3ce81500-7aa4-11eb-9af5-cf0285fedcf2.png)

2021-03-01 19:04 UTC, juuliotero requested changes

2021-03-01 19:04 UTC, juuliotero commented on src/app/apps/vacunacion/components/inscripcion.component.html
> +                        <plex-phone label="Teléfono" [(ngModel)]="ciudadano.telefono" name="telefono" [required]="true"
![image](https://user-images.githubusercontent.com/7090371/109545327-7ff7b780-7aa7-11eb-9e54-9f0521388447.png)

No verifica que el formato del teléfono sea válido

2021-03-01 19:04 UTC, juuliotero commented on src/app/apps/vacunacion/components/inscripcion.component.ts
> +    save(valid) {
Al guardar me da el siguiente error:

![image](https://user-images.githubusercontent.com/7090371/109545549-c0573580-7aa7-11eb-8198-50e14a6c6c79.png)

2021-03-01 19:11 UTC, palita1991 commented on src/app/apps/vacunacion/components/inscripcion.component.ts
> +    save(valid) {
Me paso lo mismo que @juuliotero

2021-03-02 09:56 UTC, condorpiedra commented on src/app/apps/vacunacion/services/inscripcion.service.ts
> +    // get(params: any): Observable<any[]> {
Se elimina código

2021-03-02 09:56 UTC, condorpiedra commented on src/app/apps/vacunacion/vacunacion.module.ts
> +// import { VaccinationConsultComponent } from './components/consult/consult.component';
se eliminan imports

2021-03-02 09:57 UTC, condorpiedra commented on src/app/apps/vacunacion/components/inscripcion.component.html
> +                        <plex-phone label="Teléfono" [(ngModel)]="ciudadano.telefono" name="telefono" [required]="true"
agrega validación de teléfono y documento

2021-03-02 09:57 UTC, condorpiedra commented on src/app/apps/vacunacion/components/inscripcion.component.ts
> +    save(valid) {
Verificar con los nuevos cambios

2021-03-02 09:58 UTC, condorpiedra commented
> Al momento de seleccionar el grupo de "Mayores de 60", al desactivar switch de "Mi DNI tiene numero de trámite", completar todos los campos y luego guardar te indica que el número de trámite es invalido.
> ![image](https://user-images.githubusercontent.com/30004190/109542742-3ce81500-7aa4-11eb-9af5-cf0285fedcf2.png)

Verificar con los nuevos cambios

2021-03-02 12:17 UTC, juuliotero requested changes
![image](https://user-images.githubusercontent.com/7090371/109647323-e9bfa200-7b37-11eb-93b7-02ddadc60357.png)

Cuando selecciono mayores de 60, no me deja poner en falso 'Mi DNI Tiene Número De Trámite' y por consola me aparece el error de la imagen.

2021-03-02 12:32 UTC, sychus commented
Al momento de querer guardar la info de personal de salud, me da el siguiente error:

![image](https://user-images.githubusercontent.com/19353464/109649131-3b692c00-7b3a-11eb-86d8-2fd9e86fe90f.png)

2021-03-02 12:36 UTC, sychus requested changes
Sugerencia general del workflow:
1) Validar primero al paciente con la menor cantidad de info posible, en caso qeu no se pueda por algún motivo q permita cargar el resto. Me parece bien q la clasificación de q tipo es esté aca: Ej. personal de salud, mayor 60, etc.
2) El 2do paso del workflow debería ser carga la info de enfermedades y ahí debería considerar al menos el sexo para no dejar checkbox de "estoy amamantando" si la persona validada es un masculino y esas cosas. Esto nos permitirá a futuro realizar validaciones automáticas antes de llegar a esta pantalla sin tener que modificar el workflow.

2021-03-02 12:44 UTC, palita1991 requested changes
1) No verifica que el numero de tramite del dni sea correcto con los cambios nuevos
2) Si selecciono Mayores de 60 deshabilito el switch del numero del tramita en personal de salud ya no me sale mas esa opción.

2021-03-02 12:44 UTC, juuliotero commented
> ![image](https://user-images.githubusercontent.com/7090371/109647323-e9bfa200-7b37-11eb-93b7-02ddadc60357.png)
> 
> Cuando selecciono mayores de 60, no me deja poner en falso 'Mi DNI Tiene Número De Trámite' y por consola me aparece el error de la imagen.

Este error quedó solucionado. Pero ahora noté que pasa algo parecido si vos completas el formulario, y después limpias el select del grupo. También habría que mostrar el mensaje de success con algo distinto del toast, porque por ahí no se dan cuenta. y que limpie los datos si se cargo ok.

![image](https://user-images.githubusercontent.com/7090371/109650254-b7b03f00-7b3b-11eb-95f3-678f64759572.png)

2021-03-02 13:02 UTC, liquid36 commented on src/app/apps/vacunacion/components/inscripcion.component.html
> +                        <re-captcha (resolved)="resolved($event)" siteKey="6Lc5nUsaAAAAALJ15OtJMKpdW9XSEOl13A_3Hx6i">
¿De donde sale este ID? La API no se protege también? De esta forma te la pueden bombardear igual

2021-03-02 14:00 UTC, andrrrl requested changes
Va revisión sabiendo que hay urgencia, quizá algunas cosas se puedan resolver fácil.

2021-03-02 14:48 UTC, kroce commented on src/app/apps/vacunacion/vacunacion.routing.ts
> +    { path: 'inscripcion', component: InscripcionComponent },
done

2021-03-02 16:38 UTC, juuliotero commented
![image](https://user-images.githubusercontent.com/7090371/109681670-7a0fde00-7b5c-11eb-8f3d-70d251747ce3.png)

Después del registro exitoso, limpia el formulario pero marca todos los campos como no válidos.

2021-03-02 16:42 UTC, kroce commented on src/app/apps/vacunacion/components/inscripcion.component.html
> +                    <plex-label titulo="Condiciones de Salud" size="lg"></plex-label>
Se bajaron los botones

2021-03-02 17:39 UTC, andrrrl requested changes

2021-03-02 17:39 UTC, andrrrl commented on src/app/apps/vacunacion/components/inscripcion.component.ts
> +        this.plex.updateTitle('VACUNACIÓN');
Al ser un sitio público, un título más descriptivo va a ayudar a quien googlee
```suggestion
        this.plex.updateTitle('Inscripción a vacunación COVID-19 - Provincia del Neuquén');
```

2021-03-02 17:39 UTC, andrrrl commented on src/app/apps/vacunacion/components/inscripcion.component.html
> +                        <plex-select name="localidades" [data]="localidades$ | async" label="Localidad" [(ngModel)]="ciudadano.localidad" [required]="true">
Podría ser "Localidad de residencia"

2021-03-02 17:47 UTC, liquid36 commented on src/app/apps/vacunacion/components/inscripcion.component.ts
> +        this.plex.updateTitle('VACUNACIÓN');
No va a figurar en Google, los robotos no lo pueden encontrar porque no tiene javascript.

2021-03-02 18:39 UTC, kroce commented on src/app/apps/vacunacion/components/inscripcion.component.html
> +                        <plex-select name="localidades" [data]="localidades$ | async" label="Localidad" [(ngModel)]="ciudadano.localidad" [required]="true">
done

2021-03-02 18:39 UTC, kroce commented on src/app/apps/vacunacion/components/inscripcion.component.ts
> +        this.plex.updateTitle('VACUNACIÓN');
no había visto el coment de marian, igual lo cambié

2021-03-02 18:40 UTC, kroce commented
> ![image](https://user-images.githubusercontent.com/7090371/109681670-7a0fde00-7b5c-11eb-8f3d-70d251747ce3.png)
> 
> Después del registro exitoso, limpia el formulario pero marca todos los campos como no válidos.

done

2021-03-02 18:50 UTC, andrrrl commented on src/app/apps/vacunacion/components/inscripcion.component.ts
> +        this.plex.updateTitle('VACUNACIÓN');
Creo que index cosas básicas así como el title, incluso seteado con JavaScript. De todos modos, mejor que el título sea más descriptivo para el usuario.

2021-03-02 23:19 UTC, condorpiedra commented on src/app/apps/vacunacion/components/inscripcion.component.html
> +                        <re-captcha (resolved)="resolved($event)" siteKey="6Lc5nUsaAAAAALJ15OtJMKpdW9XSEOl13A_3Hx6i">
Se agrega SITE_KEY en el environment y se realiza la verificación correspondiente en la api

2021-03-03 00:00 UTC, sychus approved these changes
vi algunos detalles... pero va. Me queda probar el circuito

2021-03-03 03:45 UTC, sychus approved these changes

2021-03-03 11:09 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [3482](http://condorpiedra.andes.gob.ar:85/3482/mochawesome.html)
CYPRESS RUN: [2576](https://dashboard.cypress.io/projects/xr7gft/runs/2576/specs)
TEST START: 2021-03-03T11:08:39.917Z
TOTAL: 358
SUCCESS: 357
FAIL: 0
SKIPPED: 1

2021-03-03 13:53 UTC, andrrrl commented
> Separar en steps

Me parece que en este tipo de formulario no corresponde steps. 
En un formulario de registro único, como este, es mejor permitir que el usuario revise todos sus datos juntos en la misma pantalla.

2021-03-04 14:10 UTC, juuliotero approved these changes

2021-03-04 14:13 UTC, palita1991 approved these changes

2021-03-04 14:15 UTC, merged