TURNOS-PRESTACIONES: Agregar máximo permitido al exportarHuds
andes/app pull request #2150
Opened 2021-03-03 14:31 UTC by martinebucarey

1. Se agregó un máximo permitido de 500 prestaciones al momento de exportar las mismas desde el buscador de turnos y prestaciones
2. Si ocurre que un usuario selecciono mas de 500 prestaciones, el botón exportar quedara deshabilitado mostrando un hint que indica el numero máximo permitido de prestaciones.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

![imagen](https://user-images.githubusercontent.com/56874534/109820607-ed285b80-7c13-11eb-880a-201698a033bc.png)

2021-03-03 14:53 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3485](http://condorpiedra.andes.gob.ar:85/3485/mochawesome.html)
CYPRESS RUN: [2579](https://dashboard.cypress.io/projects/xr7gft/runs/2579/specs)
TEST START: 2021-03-03T14:52:32.785Z
TOTAL: 359
SUCCESS: 358
FAIL: 0
SKIPPED: 1

2021-03-03 15:05 UTC, liquid36 commented on src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
> +        Object.values(this.selectPrestaciones$.getValue()).map(element => {
```suggestion
        const prestacionesSelected = Object.values(this.selectPrestaciones$.getValue()).filter(e => e);
```

2021-03-03 15:11 UTC, liquid36 approved these changes

2021-03-03 15:18 UTC, martinebucarey commented on src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
> +        Object.values(this.selectPrestaciones$.getValue()).map(element => {
Totalmente. Modificado

2021-03-04 11:09 UTC, JSantarelli requested changes

2021-03-04 11:09 UTC, JSantarelli commented on src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
> +                             [disabled]="true" hint="El máximo permitido de prestaciones es de {{prestacionesMax}}"
**Detalle:** Existe una clase global 'disabled', puede ser un buen momento para usarla. 
![disabled](https://user-images.githubusercontent.com/5895886/109955049-c96f1f00-7cc0-11eb-81ab-5a97f40b6935.PNG)

2021-03-04 11:59 UTC, martinebucarey commented on src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
> +                             [disabled]="true" hint="El máximo permitido de prestaciones es de {{prestacionesMax}}"
Modificado.

2021-03-04 12:49 UTC, JSantarelli approved these changes

2021-03-09 16:18 UTC, merged