feat(rup): ajuste visual botones en ejecucion
andes/app pull request #2151
Opened 2021-03-04 18:24 UTC by liquid36

### Requerimiento
https://proyectos.andes.gob.ar/browse/RUP-160

### Funcionalidad desarrollada 
1. Mueve los botones al nivel del `plex-tabs` ganando más espacio.

### UserStory llegó a completarse
- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos
- [ ] Si
- [ ] No

### Requiere actualizaciones en la API
- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion
- [ ] Si
- [ ] No

2021-03-04 18:38 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3488](http://condorpiedra.andes.gob.ar:85/3488/mochawesome.html)
CYPRESS RUN: [2582](https://dashboard.cypress.io/projects/xr7gft/runs/2582/specs)
TEST START: 2021-03-04T18:37:29.373Z
TOTAL: 363
SUCCESS: 358
FAIL: 5
SKIPPED: 0

2021-03-04 19:01 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3490](http://condorpiedra.andes.gob.ar:85/3490/mochawesome.html)
CYPRESS RUN: [2584](https://dashboard.cypress.io/projects/xr7gft/runs/2584/specs)
TEST START: 2021-03-04T19:00:16.862Z
TOTAL: 363
SUCCESS: 358
FAIL: 5
SKIPPED: 0

2021-03-05 11:18 UTC, andrrrl requested changes

2021-03-05 11:59 UTC, liquid36 commented on src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
> +                                 title="{{ collapse ? 'Expandir los registros' : 'Colapsar los registros'}}"
Recién estuve viendo ese comporatamiento, creo que antes deberíamos definir si aparecen colapsados o no. **Depende** de los valores de los registros y si son requeridos o no. 

Deberiamos unificar los criterios.

2021-03-05 14:57 UTC, andrrrl commented on src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
> +                                 title="{{ collapse ? 'Expandir los registros' : 'Colapsar los registros'}}"
Bien, para mí deberían estar siempre expandidos. Qué decís @JSantarelli?

2021-03-05 15:11 UTC, JSantarelli commented on src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
> +                                 title="{{ collapse ? 'Expandir los registros' : 'Colapsar los registros'}}"
Siempre expandidos y veremos que hace el usuario con Hotjar.

2021-03-05 18:04 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3507](http://condorpiedra.andes.gob.ar:85/3507/mochawesome.html)
CYPRESS RUN: [2600](https://dashboard.cypress.io/projects/xr7gft/runs/2600/specs)
TEST START: 2021-03-05T18:03:42.721Z
TOTAL: 313
SUCCESS: 310
FAIL: 3
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-03-05 18:35 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3510](http://condorpiedra.andes.gob.ar:85/3510/mochawesome.html)
CYPRESS RUN: [2602](https://dashboard.cypress.io/projects/xr7gft/runs/2602/specs)
TEST START: 2021-03-05T18:33:41.099Z
TOTAL: 280
SUCCESS: 266
FAIL: 14
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-03-08 11:47 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3519](http://condorpiedra.andes.gob.ar:85/3519/mochawesome.html)
CYPRESS RUN: [2609](https://dashboard.cypress.io/projects/xr7gft/runs/2609/specs)
TEST START: 2021-03-08T11:46:21.897Z
TOTAL: 314
SUCCESS: 300
FAIL: 14
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-03-08 12:01 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3520](http://condorpiedra.andes.gob.ar:85/3520/mochawesome.html)
CYPRESS RUN: [2610](https://dashboard.cypress.io/projects/xr7gft/runs/2610/specs)
TEST START: 2021-03-08T12:00:08.794Z
TOTAL: 363
SUCCESS: 354
FAIL: 9
SKIPPED: 0

2021-03-08 12:33 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3522](http://condorpiedra.andes.gob.ar:85/3522/mochawesome.html)
CYPRESS RUN: [2612](https://dashboard.cypress.io/projects/xr7gft/runs/2612/specs)
TEST START: 2021-03-08T12:32:18.644Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-03-08 14:08 UTC, juuliotero reviewed
ver lo del estado inicial que dicen @andrrrl y @JSantarelli, después funciona está todo ok

2021-03-08 14:58 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3524](http://condorpiedra.andes.gob.ar:85/3524/mochawesome.html)
CYPRESS RUN: [2614](https://dashboard.cypress.io/projects/xr7gft/runs/2614/specs)
TEST START: 2021-03-08T14:57:25.871Z
TOTAL: 363
SUCCESS: 359
FAIL: 4
SKIPPED: 0

2021-03-08 15:29 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3526](http://condorpiedra.andes.gob.ar:85/3526/mochawesome.html)
CYPRESS RUN: [2616](https://dashboard.cypress.io/projects/xr7gft/runs/2616/specs)
TEST START: 2021-03-08T15:18:42.036Z
TOTAL: 339
SUCCESS: 325
FAIL: 14
SKIPPED: 0

2021-03-08 15:39 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3527](http://condorpiedra.andes.gob.ar:85/3527/mochawesome.html)
CYPRESS RUN: [2617](https://dashboard.cypress.io/projects/xr7gft/runs/2617/specs)
TEST START: 2021-03-08T15:38:28.557Z
TOTAL: 359
SUCCESS: 357
FAIL: 2
SKIPPED: 0

2021-03-08 15:48 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3528](http://condorpiedra.andes.gob.ar:85/3528/mochawesome.html)
CYPRESS RUN: [2618](https://dashboard.cypress.io/projects/xr7gft/runs/2618/specs)
TEST START: 2021-03-08T15:47:32.520Z
TOTAL: 363
SUCCESS: 362
FAIL: 1
SKIPPED: 0

2021-03-08 16:20 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3529](http://condorpiedra.andes.gob.ar:85/3529/mochawesome.html)
CYPRESS RUN: [2619](https://dashboard.cypress.io/projects/xr7gft/runs/2619/specs)
TEST START: 2021-03-08T16:10:12.402Z
TOTAL: 355
SUCCESS: 348
FAIL: 7
SKIPPED: 0

2021-03-08 16:30 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3530](http://condorpiedra.andes.gob.ar:85/3530/mochawesome.html)
CYPRESS RUN: [2620](https://dashboard.cypress.io/projects/xr7gft/runs/2620/specs)
TEST START: 2021-03-08T16:28:26.573Z
TOTAL: 304
SUCCESS: 292
FAIL: 12
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-03-08 16:44 UTC, palita1991 approved these changes
Revisar que se subio el archivo **src/environments/environment.dev.ts** apuntando la api a demo, lo demás todo ok :+1:

2021-03-08 16:51 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3531](http://condorpiedra.andes.gob.ar:85/3531/mochawesome.html)
CYPRESS RUN: [2621](https://dashboard.cypress.io/projects/xr7gft/runs/2621/specs)
TEST START: 2021-03-08T16:50:16.574Z
TOTAL: 363
SUCCESS: 362
FAIL: 1
SKIPPED: 0

2021-03-08 17:04 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3532](http://condorpiedra.andes.gob.ar:85/3532/mochawesome.html)
CYPRESS RUN: [2622](https://dashboard.cypress.io/projects/xr7gft/runs/2622/specs)
TEST START: 2021-03-08T17:03:19.793Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-03-09 16:39 UTC, merged