VAC - Listado de inscriptos
andes/app pull request #2156
Opened 2021-03-08 14:06 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-1

### Funcionalidad desarrollada 

1. Se muestra el listado de inscriptos para vacunación y un conjunto de filtros de búsqueda

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-03-09 18:53 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3546](http://condorpiedra.andes.gob.ar:85/3546/mochawesome.html)
CYPRESS RUN: [2636](https://dashboard.cypress.io/projects/xr7gft/runs/2636/specs)
TEST START: 2021-03-09T18:51:56.044Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-03-10 13:33 UTC, martinebucarey reviewed
En la user dice de usar plex-table, por algo en particular se uso una table comun??

2021-03-10 13:33 UTC, martinebucarey commented on src/app/apps/vacunacion/components/listado-inscriptos.component.ts
> +import { find, map, tap, filter } from 'rxjs/operators';
estos import no están usandose

2021-03-10 13:33 UTC, martinebucarey commented on src/app/apps/vacunacion/components/listado-inscriptos.html
> +                <!-- <plex-title titulo="Datos personales" size="sm"></plex-title> -->
plex-title comentado

2021-03-10 13:33 UTC, martinebucarey commented on src/app/apps/vacunacion/components/filtros-vacunacion.component.ts
> +                const index = listado.findIndex(i => i[key] === inside[key]);
```suggestion
                               if(!listado.some(elem=>elem[key]===inside[key]))
```

2021-03-10 15:53 UTC, palita1991 requested changes
Probando con la base de datos de DEMO, esta bien que en grupo diga "Personal de Salud" y luego en la columna "Es personal de salud" diga NO?
![image](https://user-images.githubusercontent.com/30004190/110657223-6a694880-819f-11eb-88a2-cd78d1842f50.png)

2021-03-10 19:07 UTC, negro89 commented
@martinebucarey @juuliotero corregido.
@palita1991 no debería, pero se muestra bien ya que los datos están cargados asi.

2021-03-11 15:10 UTC, palita1991 approved these changes

2021-03-11 16:23 UTC, liquid36 requested changes
Habría que trabajar en la visualizacipon del sidebar, usar plex-detail y plex-label para jerarquizar la información

2021-03-11 16:23 UTC, liquid36 commented on src/app/apps/vacunacion/components/listado-inscriptos.html
> +                <td *plTableCol="'apellido'"> {{ persona.apellido }} </td>
En todo ANDES el nombre y apellido esta en una sola columna.

2021-03-11 16:23 UTC, liquid36 commented on src/app/apps/vacunacion/components/filtros-vacunacion.component.ts
> +        this.localidad$ = this.inscripcionService.inscriptosFiltrados$.pipe(
Este se calcula y no se usa.

2021-03-11 16:23 UTC, liquid36 commented on src/app/apps/vacunacion/services/inscripcion.service.ts
> +        this.inscriptos$ = this.server.get(this.inscripcionUrl);
Atención que en PROD ya hay 1700 inscripciones. Se va a desbordar el listado.

2021-03-17 15:14 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3585](http://condorpiedra.andes.gob.ar:85/3585/mochawesome.html)
CYPRESS RUN: [2668](https://dashboard.cypress.io/projects/xr7gft/runs/2668/specs)
TEST START: 2021-03-17T15:13:05.700Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-03-25 12:10 UTC, juuliotero requested changes

2021-03-25 12:10 UTC, juuliotero commented on src/app/apps/vacunacion/components/listado-inscriptos.html
> +                <!-- <div title>Estado del paciente</div> -->
código comentado

2021-03-25 12:10 UTC, juuliotero commented on src/app/apps/vacunacion/components/listado-inscriptos.html
> +                <plex-label titulo="Número de tramite" subtitulo="{{ personalSelected.nroTramite }}"></plex-label>
No se si el número de trámite es un dato que entre dentro del estado del paciente, pero por ahí está bien

2021-03-25 12:10 UTC, juuliotero commented on src/app/apps/vacunacion/components/listado-inscriptos.html
> +                <plex-label titulo="Condicion" subtitulo="{{ personalSelected.condicion ? 'Si' : 'No' }}">
Acento en condición

2021-03-25 12:10 UTC, juuliotero commented on src/app/apps/vacunacion/components/listado-inscriptos.html
> +            <plex-detail size="sm" direction="row">
Como no tiene title ni foto, queda una columna al principio vacía con una línea azul si se encierran los plex-label en un plex-detail

![image](https://user-images.githubusercontent.com/7090371/112470833-e8a21f00-8d49-11eb-9a2e-2bc6aeff59e9.png)

2021-03-25 12:23 UTC, liquid36 commented on src/app/apps/vacunacion/components/listado-inscriptos.html
> +            <plex-detail size="sm" direction="row">
El número de tramite es un dato sensible, no deberíamos volver a mostrarlo nunca más. y pesandolo más seriamente no 
 debería estar almacenado en la DB.

2021-03-25 12:24 UTC, liquid36 commented on src/app/apps/vacunacion/components/listado-inscriptos.html
> +            <plex-detail size="sm" direction="row">
En esos casos se usa un **plex-grid** con **plex-label** adentro. **plex-detail** es cuando tiene algún dato para jerarquizar.

2021-03-26 14:40 UTC, negro89 commented on src/app/apps/vacunacion/components/listado-inscriptos.html
> +            <plex-detail size="sm" direction="row">
![image](https://user-images.githubusercontent.com/37875706/112629212-c3c5ae80-8e12-11eb-9e2c-2b7b6925b4f3.png)
Se pasó a plex-detail por una observación anterior, ahora quedó con plex-grid.
Hechas las demás correcciones!

2021-03-26 15:54 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3676](http://condorpiedra.andes.gob.ar:85/3676/mochawesome.html)
CYPRESS RUN: [2747](https://dashboard.cypress.io/projects/xr7gft/runs/2747/specs)
TEST START: 2021-03-26T15:51:58.673Z
TOTAL: 341
SUCCESS: 339
FAIL: 2
SKIPPED: 0

2021-03-26 17:55 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3677](http://condorpiedra.andes.gob.ar:85/3677/mochawesome.html)
CYPRESS RUN: [2748](https://dashboard.cypress.io/projects/xr7gft/runs/2748/specs)
TEST START: 2021-03-26T17:52:36.485Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-03-29 17:12 UTC, juuliotero approved these changes

2021-03-30 17:56 UTC, merged