VACUNACIÓN:  Formulario de inscripción  profesionales certificados
andes/app pull request #2157
Opened 2021-03-08 19:08 UTC by martinebucarey

### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-4

### Funcionalidad desarrollada 

1. Se crea componente de validación para profesionales que deseen emitir certificados a personas con discapacidad  para vacunación de COVID 19.
2. Se actualizan los servicio de profesional y usuario para hacer las modificaciones correspondientes en cada profesional/usuario.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [x] Si https://github.com/andes/api/pull/1291
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No (En proceso)

2021-03-09 01:29 UTC, sychus approved these changes
Joya!! ver el detalle del linting y me quedaría probarlo!! pero era la idea!! 😉

2021-03-09 11:28 UTC, andrrrl commented on src/app/components/profesional/inscripcion-profesionales/inscripcion-profesionales.component.ts
> +    this.profesionalService.validarProfesional({ documento: this.profesional.documento, sexo: this.profesional.sexo.id, nroTramite: this.profesional.nroTramite }).subscribe(datos => {
ultra long line detected

2021-03-09 12:45 UTC, martinebucarey commented on src/app/components/profesional/inscripcion-profesionales/inscripcion-profesionales.component.ts
> +    this.profesionalService.validarProfesional({ documento: this.profesional.documento, sexo: this.profesional.sexo.id, nroTramite: this.profesional.nroTramite }).subscribe(datos => {
fixed

2021-03-10 17:52 UTC, palita1991 approved these changes

2021-03-11 16:59 UTC, liquid36 reviewed
Pregunta, pregunta. Todas las rutas de la API estan protegida. No deberían ser publicas?

2021-03-11 16:59 UTC, liquid36 commented on src/app/app.routing.ts
> +    { path: 'inscripcion/profesionales', component: InscripcionProfesionalesComponent, canActivate: [RoutingNavBar, RoutingGuard] },
Estas rutas no son publicas?

2021-03-12 17:12 UTC, plammel requested changes

2021-03-12 17:12 UTC, plammel commented on src/app/components/profesional/inscripcion-profesionales/inscripcion-profesionales.component.ts
> +  };
Reemplazaría la creación de este objeto en la declaración del atributo por una llamada en el init a la función `resetForm()` que ya hace lo mismo

2021-03-12 17:12 UTC, plammel commented on src/app/components/profesional/inscripcion-profesionales/inscripcion-profesionales.component.ts
> +    const telFijo = this.contactos.filter(contacto => contacto.tipo === 'fijo');
es mejor usar `array.find` (único resultado) en lugar de `array.filter` y obtener la primera posición del array resultante

2021-03-12 17:12 UTC, plammel commented on src/app/utils/permisos/permisos-update.component.ts
> +export const certificadosProfesionalesCovid = ['mpi:paciente:getbyId', 'rup:tipoPrestacion:604793e28566033a409007ea'];
El nombre del archivo es incorrecto: no es un componente.

2021-03-12 17:12 UTC, plammel commented on src/app/components/profesional/inscripcion-profesionales/inscripcion-profesionales.component.html
> +                <plex-text [(ngModel)]="profesional.matricula" name="matricula" label="Matricula" readonly="true">
```suggestion
                <plex-text [(ngModel)]="profesional.matricula" name="matricula" label="Matrícula" readonly="true">
```

2021-03-12 17:12 UTC, plammel commented on src/app/components/profesional/inscripcion-profesionales/inscripcion-profesionales.component.html
> +                        Su matricula se encuentra vigente hasta la fecha: {{profesional.caducidadMatricula | fecha}}
```suggestion
                        Su matrícula se encuentra vigente hasta la fecha: {{profesional.caducidadMatricula | fecha}}
```

2021-03-12 17:12 UTC, plammel commented on src/app/components/profesional/inscripcion-profesionales/inscripcion-profesionales.component.html
> +                        Su matricula no se encuentra vigente</plex-badge>
```suggestion
                        Su matrícula no se encuentra vigente</plex-badge>
```

2021-03-12 17:12 UTC, plammel commented on src/app/components/profesional/inscripcion-profesionales/inscripcion-profesionales.component.html
> +                                subtitulo="Deberá renovar su matricula para continuar con el proceso de habilitación">
```suggestion
                                subtitulo="Deberá renovar su matrícula para continuar con el proceso de habilitación">
```

2021-03-12 17:12 UTC, plammel commented on src/app/components/profesional/inscripcion-profesionales/inscripcion-profesionales.component.html
> +                    <plex-button type="danger" (click)="renovarMatricula()">Renovar matricula
```suggestion
                    <plex-button type="danger" (click)="renovarMatricula()">Renovar matrícula
```

2021-03-12 17:30 UTC, martinebucarey commented on src/app/app.routing.ts
> +    { path: 'inscripcion/profesionales', component: InscripcionProfesionalesComponent, canActivate: [RoutingNavBar, RoutingGuard] },
Así es, para todos y todas. Corregido

2021-03-12 17:46 UTC, plammel approved these changes

2021-03-16 14:44 UTC, plammel commented
@sychus hicimos algunos cambios respecto a la seguridad y asignación de permisos. Por favor revalidar 🙏

2021-03-16 15:31 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3574](http://condorpiedra.andes.gob.ar:85/3574/mochawesome.html)
CYPRESS RUN: [2657](https://dashboard.cypress.io/projects/xr7gft/runs/2657/specs)
TEST START: 2021-03-16T15:30:51.040Z
TOTAL: 366
SUCCESS: 363
FAIL: 3
SKIPPED: 0

2021-03-16 15:46 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3575](http://condorpiedra.andes.gob.ar:85/3575/mochawesome.html)
CYPRESS RUN: [2658](https://dashboard.cypress.io/projects/xr7gft/runs/2658/specs)
TEST START: 2021-03-16T15:45:37.067Z
TOTAL: 366
SUCCESS: 363
FAIL: 3
SKIPPED: 0

2021-03-16 17:45 UTC, martinebucarey commented on src/environments/apiKeyMaps.ts.example
> +
Si, en el último commit ya voló

2021-03-16 18:09 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3578](http://condorpiedra.andes.gob.ar:85/3578/mochawesome.html)
CYPRESS RUN: [2661](https://dashboard.cypress.io/projects/xr7gft/runs/2661/specs)
TEST START: 2021-03-16T18:08:10.155Z
TOTAL: 316
SUCCESS: 302
FAIL: 14
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-03-16 18:35 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3581](http://condorpiedra.andes.gob.ar:85/3581/mochawesome.html)
CYPRESS RUN: [2664](https://dashboard.cypress.io/projects/xr7gft/runs/2664/specs)
TEST START: 2021-03-16T18:34:26.476Z
TOTAL: 366
SUCCESS: 366
FAIL: 0
SKIPPED: 0

2021-03-17 15:28 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3586](http://condorpiedra.andes.gob.ar:85/3586/mochawesome.html)
CYPRESS RUN: [2669](https://dashboard.cypress.io/projects/xr7gft/runs/2669/specs)
TEST START: 2021-03-17T15:27:02.040Z
TOTAL: 366
SUCCESS: 366
FAIL: 0
SKIPPED: 0

2021-03-19 15:09 UTC, kroce requested changes
El campo de email debería ser requerido
![image](https://user-images.githubusercontent.com/18030170/111801942-37643a80-88ac-11eb-9b4c-c54413fd2cdb.png)
![image](https://user-images.githubusercontent.com/18030170/111801387-aa20e600-88ab-11eb-8f38-78c31b599178.png)

2021-03-19 15:24 UTC, martinebucarey commented
> El campo de email debería ser requerido
> ![image](https://user-images.githubusercontent.com/18030170/111801942-37643a80-88ac-11eb-9b4c-c54413fd2cdb.png)
> ![image](https://user-images.githubusercontent.com/18030170/111801387-aa20e600-88ab-11eb-8f38-78c31b599178.png)

Modificado

2021-03-19 15:39 UTC, kroce approved these changes

2021-03-19 16:05 UTC, JSantarelli requested changes

2021-03-19 17:39 UTC, martinebucarey commented on src/app/components/profesional/inscripcion-profesionales/inscripcion-profesionales.component.html
> +            <div class="col-md-6 col-12">
Modificado

2021-03-19 17:46 UTC, merged