VAC: pantalla para consultar el estado de inscripciones
andes/app pull request #2161
Opened 2021-03-09 18:20 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-8

### Funcionalidad desarrollada 
1. Se crea una pantalla para consultar si una persona está registrada para vacunarse y si lo está, muestra el estado. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1294
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-03-10 18:20 UTC, palita1991 approved these changes
@juuliotero Correr los test

2021-03-11 16:08 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [3552](http://condorpiedra.andes.gob.ar:85/3552/mochawesome.html)
CYPRESS RUN: [2640](https://dashboard.cypress.io/projects/xr7gft/runs/2640/specs)
TEST START: 2021-03-11T16:06:38.675Z
TOTAL: 319
SUCCESS: 308
FAIL: 11
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-03-11 16:52 UTC, liquid36 commented on src/app/apps/vacunacion/components/consulta.component.html
> +            <div></div>
(?)

2021-03-11 20:32 UTC, juuliotero commented on src/app/apps/vacunacion/components/consulta.component.html
> +            <div></div>
se fue el div polémico

2021-03-12 16:02 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [3566](http://condorpiedra.andes.gob.ar:85/3566/mochawesome.html)
CYPRESS RUN: [2649](https://dashboard.cypress.io/projects/xr7gft/runs/2649/specs)
TEST START: 2021-03-12T16:01:01.854Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-03-22 15:00 UTC, kroce requested changes

2021-03-22 15:00 UTC, kroce commented on src/app/apps/vacunacion/vacunacion.routing.ts
> +    { path: 'consulta', component: ConsultaComponent },
cambiar por path mas específco: consulta-inscripcion

2021-03-22 18:23 UTC, juuliotero commented on src/app/apps/vacunacion/vacunacion.routing.ts
> +    { path: 'consulta', component: ConsultaComponent },
listo

2021-03-23 14:20 UTC, andrrrl commented
![image](https://user-images.githubusercontent.com/11394455/112158916-625dcf80-8bc7-11eb-87f5-4ed68f5072e7.png)

Creo que podría tener un mensaje un poco más ameno para el usuario: 
"La persona con documento nro. XXXXXX no se encuentra en la lista de inscriptos" y en el mensaje más chico "Revisá los datos ingresados e intentá de nuevo"

2021-03-23 14:34 UTC, andrrrl requested changes
Está bien en general (de hecho yo mismo había dado el OK) pero creo que en una segunda pasada había cosas que quedaron algo desordenadas.

2021-03-23 14:35 UTC, andrrrl requested changes

2021-03-23 14:35 UTC, andrrrl commented on src/app/apps/vacunacion/components/consulta.component.html
> +                </plex-label>
```suggestion
        <plex-grid class="h-75" type="auto" size="lg" cols="3" justify="center">
            <div>
                <plex-label titulo="Campaña de vacunación COVID-19"
                            subtitulo="Completá los datos para conocer el estado de tu inscripción" size="xl"
                            icon="informacion" type="info">
                </plex-label>
                <hr>

2021-03-23 17:20 UTC, andrrrl requested changes

2021-03-23 17:20 UTC, andrrrl commented on src/app/apps/vacunacion/services/inscripcion.service.ts
> +        return this.server.get(`${this.inscripcionUrl}/consultas`, { params });
```suggestion
        return this.server.get(`${this.inscripcionUrl}/consultas`, { params, showErrors: false });
```
Así se puede evitar que muestre el `plex.info()` que es medio invasivo

2021-03-26 15:42 UTC, palita1991 approved these changes

2021-03-26 17:58 UTC, kroce approved these changes

2021-03-26 18:00 UTC, merged