EPIDEMIOLOGÍA: Buscador de fichas epidemiológicas
andes/app pull request #2162
Opened 2021-03-10 14:48 UTC by martinebucarey

### Requerimiento
https://proyectos.andes.gob.ar/browse/EP-15

### Funcionalidad desarrollada 

1. Se agrega componente que permite realizar búsquedas de fichas epidemiologicas registrados, con filtros de fechas, tipo de fichas y paciente.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

### Observacion
- Queda pendiente revision de UI/UX para mejorar los filtros y selección del paciente @andes/ui-ux

2021-03-10 15:03 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3549](http://condorpiedra.andes.gob.ar:85/3549/mochawesome.html)
CYPRESS RUN: [2638](https://dashboard.cypress.io/projects/xr7gft/runs/2638/specs)
TEST START: 2021-03-10T15:02:29.527Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-03-11 14:04 UTC, palita1991 reviewed
Funcionamiento correcto, primer revisión realizada quizás solo un detalle que al eliminar al paciente que había seleccionado, se limpie el listado pero igualmente espero la revision de ui/ux para terminar con el test.

2021-03-11 17:10 UTC, liquid36 requested changes
La parte de seleccionar el paciente esta rara. Pondría el buscador del paciente con el listado. 
y cuando elegis al paciente se convierta en un paciente-detalle con los filtros.
Y el buscador desaparezca hasta que tocas el boton de cambiar paciente. 
Capaz que hay que verlo con UI/UX.

2021-03-11 17:10 UTC, liquid36 commented on src/app/modules/epidemiologia/epidemiologia.routing.ts
> +    path: 'buscador-ficha-epidemiologica',
Iria la palabra 'buscador', ya estamos dentro del modulo 'epidemiologia'

2021-03-12 15:30 UTC, JSantarelli commented
En en el archivo [ficha-epidemiológica.html](https://github.com/andes/app/blob/40d108d757683270d2ab2f7bfb36c12048d2e06d/src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.html#L4) propongo sustituir los encolumnados boostrap por plex-wrapper, agregando grow="full" si la necesidad es que se extienda todo el ancho de pantalla.
![wrapper](https://user-images.githubusercontent.com/5895886/110961446-9535d700-832e-11eb-9c7d-20f390c39cb7.PNG)

2021-03-12 15:34 UTC, JSantarelli commented
> La parte de seleccionar el paciente esta rara. Pondría el buscador del paciente con el listado.
> y cuando elegis al paciente se convierta en un paciente-detalle con los filtros.
> Y el buscador desaparezca hasta que tocas el boton de cambiar paciente.
> Capaz que hay que verlo con UI/UX.

La solución que propones entiendo que va [por éste lado.](https://www.loom.com/share/a4614645c438427ba1b74b3338ea98d4) Lo estamos analizando con @andrrrl

2021-03-23 13:38 UTC, andrrrl commented
> > La parte de seleccionar el paciente esta rara. Pondría el buscador del paciente con el listado.
> > y cuando elegis al paciente se convierta en un paciente-detalle con los filtros.
> > Y el buscador desaparezca hasta que tocas el boton de cambiar paciente.
> > Capaz que hay que verlo con UI/UX.
> 
> @liquid36 La solución que propones entiendo que va [por éste lado.](https://www.loom.com/share/a4614645c438427ba1b74b3338ea98d4) Lo estamos analizando con @andrrrl

Si, la versión del video parece ser la más correcta para la selección de pacientes. Creo que cambié alguito de parecer con algo que hablamos @JSantarelli, lo hablamos aparte con @AgosLizzi también.

2021-03-23 20:51 UTC, JSantarelli requested changes
A la propuesta de selección de paciente y posterior filtrado, se le agrega una pequeña modificación (el paciente seleccionado en la misma línea que los filtros de modo que optimizamos espacio). Envolver para llevar con plex-grid (ver [lineamiento](https://ui.andes.gob.ar/components/template-busqueda-filtrada/overview)). Dejo [video explicativo](https://www.loom.com/share/404ce43615dc4428b53c65e73dea0886) con la propuesta actualizada.

2021-03-25 18:18 UTC, martinebucarey commented on src/app/modules/epidemiologia/epidemiologia.routing.ts
> +    path: 'buscador-ficha-epidemiologica',
Si bien como decís esta dentro del modulo 'epidemiología' puede ser que en un futuro el modulo tengo mas buscadores y no solo uno de fichas por eso tiene esa ruta y esos componentes, te parece igual cambiar el nombre y ponerle a todo solo buscador??

2021-03-25 18:19 UTC, martinebucarey commented
> A la propuesta de selección de paciente y posterior filtrado, se le agrega una pequeña modificación (el paciente seleccionado en la misma línea que los filtros de modo que optimizamos espacio). Envolver para llevar con plex-grid (ver [lineamiento](https://ui.andes.gob.ar/components/template-busqueda-filtrada/api)). Dejo [video explicativo](https://www.loom.com/share/404ce43615dc4428b53c65e73dea0886) con la propuesta actualizada.

Subidos los nuevos cambios según videos y charlas varias :)

2021-03-26 14:41 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3671](http://condorpiedra.andes.gob.ar:85/3671/mochawesome.html)
CYPRESS RUN: [2742](https://dashboard.cypress.io/projects/xr7gft/runs/2742/specs)
TEST START: 2021-03-26T14:39:01.610Z
TOTAL: 366
SUCCESS: 366
FAIL: 0
SKIPPED: 0

2021-04-07 17:10 UTC, palita1991 approved these changes

2021-04-08 11:07 UTC, JSantarelli approved these changes

2021-04-09 14:44 UTC, sychus commented
Lo cerramos por un nuevo PR con las búsquedas actualizadas

2021-04-09 14:44 UTC, closed without merging