VAC - Agrega listado de inscriptos como submodulo de 'visualización'
andes/app pull request #2167
Opened 2021-03-17 18:24 UTC by negro89

### Requerimiento
 

### Funcionalidad desarrollada 

1. Chequea permisos para listado de inscriptos
2. Agrega listado como submodulo de visualización de información

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [X] Si (Agregar permisos para visualizar)
- [ ] No

### Requiere actualizaciones en la API

- [X] Si  https://github.com/andes/api/pull/1302
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-03-17 18:37 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3594](http://condorpiedra.andes.gob.ar:85/3594/mochawesome.html)
CYPRESS RUN: [2676](https://dashboard.cypress.io/projects/xr7gft/runs/2676/specs)
TEST START: 2021-03-17T18:36:52.699Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-03-19 10:35 UTC, JSantarelli requested changes

2021-03-19 10:35 UTC, JSantarelli commented on src/app/apps/vacunacion/components/listado-inscriptos.html
> +            <plex-detail size="sm" direction="row">
Para agrupar y ordenar `<plex-label>` se recomienda utilizar un `<plex-grid>`. En éste caso, con las siguientes propiedades: `size="sm" type="full"` para su correcta distribución.

2021-03-19 10:35 UTC, JSantarelli commented on src/app/apps/vacunacion/components/listado-inscriptos.html
> +            <plex-detail size="sm" direction="row">
Aprovecho para realizar observaciones habladas con @andrrrl  sobre el acceso al submódulo en el inicio de andes:

- El texto que acompaña debería ser más descriptivo: "Vacunación COVID-19" y el hecho que sea listado recaiga sobre el icono, el cual cambiaría a: 'documento-paciente'.

2021-03-26 15:30 UTC, negro89 commented on src/app/apps/vacunacion/components/listado-inscriptos.html
> +            <plex-detail size="sm" direction="row">
Primer cambio corregido en https://github.com/andes/app/pull/2156 que es de donde se desprende este branch.
El resto quedó!

2021-03-31 16:33 UTC, kroce commented
se va a resolver por bd agregando el modulo

2021-03-31 16:33 UTC, closed without merging