TOP: Alertar al cargar solicitud repetida
andes/app pull request #2169
Opened 2021-03-18 15:48 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/TOP-111

### Funcionalidad desarrollada 
1. Al cargar una nueva solicitud en TOP, si el paciente tiene una en curso para la misma prestación muestra un mensaje de error.
2. Al cargar una solicitud desde RUP, si el paciente tiene una en curso para la misma prestación muestra mensaje de error.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-03-18 16:03 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [3600](http://condorpiedra.andes.gob.ar:85/3600/mochawesome.html)
CYPRESS RUN: [2681](https://dashboard.cypress.io/projects/xr7gft/runs/2681/specs)
TEST START: 2021-03-18T16:02:35.155Z
TOTAL: 363
SUCCESS: 358
FAIL: 5
SKIPPED: 0

2021-03-19 15:01 UTC, martinebucarey commented on src/app/components/top/solicitudes/formNuevaSolicitud.component.ts
> +                    let reglaAplicada = this.arrayReglasDestino.find(r => r.destino.prestacion.conceptId === this.modelo.solicitud.tipoPrestacion.conceptId &&
```suggestion
                    const reglaAplicada = this.arrayReglasDestino.find(r => r.destino.prestacion.conceptId === this.modelo.solicitud.tipoPrestacion.conceptId &&
```
- Un nombre más explicativo para 'r'

2021-03-19 15:01 UTC, martinebucarey commented on src/app/components/top/solicitudes/formNuevaSolicitud.component.ts
> +                    let reglaOrigen = reglaAplicada.origen.prestaciones.find(rule => { return rule.prestacion.conceptId === this.modelo.solicitud.tipoPrestacionOrigen.conceptId; });
```suggestion
                    const reglaOrigen = reglaAplicada.origen.prestaciones.find(rule => { return rule.prestacion.conceptId === this.modelo.solicitud.tipoPrestacionOrigen.conceptId; });
```

2021-03-19 17:38 UTC, juuliotero commented on src/app/components/top/solicitudes/formNuevaSolicitud.component.ts
> +                    let reglaOrigen = reglaAplicada.origen.prestaciones.find(rule => { return rule.prestacion.conceptId === this.modelo.solicitud.tipoPrestacionOrigen.conceptId; });
corregido

2021-03-19 17:38 UTC, juuliotero commented on src/app/components/top/solicitudes/formNuevaSolicitud.component.ts
> +                    let reglaAplicada = this.arrayReglasDestino.find(r => r.destino.prestacion.conceptId === this.modelo.solicitud.tipoPrestacion.conceptId &&
corregido

2021-03-19 17:52 UTC, martinebucarey approved these changes

2021-03-19 18:30 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [3610](http://condorpiedra.andes.gob.ar:85/3610/mochawesome.html)
CYPRESS RUN: [2691](https://dashboard.cypress.io/projects/xr7gft/runs/2691/specs)
TEST START: 2021-03-19T18:29:51.037Z
TOTAL: 363
SUCCESS: 361
FAIL: 2
SKIPPED: 0

2021-03-19 18:42 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [3611](http://condorpiedra.andes.gob.ar:85/3611/mochawesome.html)
CYPRESS RUN: [2692](https://dashboard.cypress.io/projects/xr7gft/runs/2692/specs)
TEST START: 2021-03-19T18:41:23.164Z
TOTAL: 363
SUCCESS: 355
FAIL: 8
SKIPPED: 0

2021-03-19 19:00 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [3612](http://condorpiedra.andes.gob.ar:85/3612/mochawesome.html)
CYPRESS RUN: [2693](https://dashboard.cypress.io/projects/xr7gft/runs/2693/specs)
TEST START: 2021-03-19T18:59:25.548Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-03-25 16:36 UTC, palita1991 approved these changes

2021-03-29 10:58 UTC, liquid36 requested changes

2021-03-29 10:58 UTC, liquid36 commented on src/app/modules/rup/components/ejecucion/buscador.component.ts
> +            this.servicioPrestacion.getSolicitudes(params).subscribe(resultado => {
Esta query en producción no va a funcionar. Mínimamente hay que pasar el ID del paciente para que mongo use el Indice.

2021-04-05 14:17 UTC, palita1991 commented on src/app/modules/rup/components/ejecucion/buscador.component.ts
> +            this.servicioPrestacion.getSolicitudes(params).subscribe(resultado => {
@juuliotero

2021-04-13 12:44 UTC, juuliotero commented on src/app/modules/rup/components/ejecucion/buscador.component.ts
> +            this.servicioPrestacion.getSolicitudes(params).subscribe(resultado => {
Corregido. También se cambió el plex info por un plex confirm, para que el usuario decida si carga la solicitud para la misma prestación o la cancela.

2021-04-13 13:21 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [3748](http://condorpiedra.andes.gob.ar:85/3748/mochawesome.html)
CYPRESS RUN: [2814](https://dashboard.cypress.io/projects/xr7gft/runs/2814/specs)
TEST START: 2021-04-13T13:19:05.228Z
TOTAL: 322
SUCCESS: 311
FAIL: 11
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-04-13 13:40 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [3749](http://condorpiedra.andes.gob.ar:85/3749/mochawesome.html)
CYPRESS RUN: [2815](https://dashboard.cypress.io/projects/xr7gft/runs/2815/specs)
TEST START: 2021-04-13T13:37:39.832Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-04-16 18:30 UTC, plammel requested changes

2021-04-16 18:30 UTC, plammel commented on src/app/components/top/solicitudes/formNuevaSolicitud.component.ts
> +        this.servicioPrestacion.getSolicitudes(params).subscribe(resultado => {
Este bloque se repite en dos componentes. Sugiero traspasarlo al Service de prestación para evitar duplicidad de código. Algo del estilo `this.servicioPrestacion.getSolicitudesEnCurso(idPaciente, prestacionDestino).subscribe(resultado => { ... });`

2021-04-16 18:33 UTC, plammel commented on src/app/components/top/solicitudes/formNuevaSolicitud.component.ts
> +        this.servicioPrestacion.getSolicitudes(params).subscribe(resultado => {
Este bloque se repite en dos componentes. Sugiero traspasarlo al Service de prestación para evitar duplicidad de código. Algo del estilo `this.servicioPrestacion.getSolicitudesEnCurso(idPaciente, prestacionDestino).subscribe(resultado => { ... });`

2021-04-29 13:09 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [3892](http://condorpiedra.andes.gob.ar:85/3892/mochawesome.html)
CYPRESS RUN: [2950](https://dashboard.cypress.io/projects/xr7gft/runs/2950/specs)
TEST START: 2021-04-29T13:08:46.331Z
TOTAL: 367
SUCCESS: 367
FAIL: 0
SKIPPED: 0

2021-04-29 13:33 UTC, merged