MPI: se corrige error al mostrar badge "sin dni" en pacietes validados
andes/app pull request #2172
Opened 2021-03-19 15:00 UTC by MCele

### Requerimiento
 
Se corrige bug que mostraba badge "sin dni" en pacietes validados menores a 5 años.
La incosistencia de los datos se visualizaba al mostrar badge "sin dni" en pacientes menores a 5 años con al menos una relación asociada y de edad menor a 5 años

### Funcionalidad desarrollada 

1. 
2. 
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-03-19 16:50 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [3607](http://condorpiedra.andes.gob.ar:85/3607/mochawesome.html)
CYPRESS RUN: [2688](https://dashboard.cypress.io/projects/xr7gft/runs/2688/specs)
TEST START: 2021-03-19T16:49:37.552Z
TOTAL: 363
SUCCESS: 362
FAIL: 1
SKIPPED: 0

2021-03-19 17:08 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [3608](http://condorpiedra.andes.gob.ar:85/3608/mochawesome.html)
CYPRESS RUN: [2689](https://dashboard.cypress.io/projects/xr7gft/runs/2689/specs)
TEST START: 2021-03-19T17:07:21.193Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-03-23 11:19 UTC, juuliotero requested changes

2021-03-23 11:19 UTC, juuliotero commented on src/app/modules/mpi/components/paciente-detalle.component.ts
> +        const p = this.paciente;
estaría bueno llamar a la variable paciente, para facilitar la lectura del código después

2021-03-31 04:44 UTC, sychus requested changes
Verificar

2021-03-31 04:44 UTC, sychus commented on src/app/modules/mpi/components/paciente-detalle.component.ts
> +        const p = this.paciente;
Acuerdo con Juli sobre nombre de la variable. Por otra parte me parece raro el requerimiento ya que es muy dificil que existan menores entre 1 y 5 años sin dni. En general a los bebes se les hace el dni enseguida (antes de los 3 meses de vida). Por las dudas verificar.

2021-04-05 15:06 UTC, MCele commented on src/app/modules/mpi/components/paciente-detalle.component.ts
> +        const p = this.paciente;
Sí, es un valor estimativo que acordamos con @condorpiedra y quedó sujeto a cambios si fueran necesarios. Ya que existían muchos bebés cargados sin DNI y con nombre/apellidos incompletos y luego como no se los encontraba o se prestaban a confusión, estos pacientes no se actualizaban y se los volvía a crear.

2021-04-05 16:01 UTC, MCele commented on src/app/modules/mpi/components/paciente-detalle.component.ts
> +        const p = this.paciente;
> estaría bueno llamar a la variable paciente, para facilitar la lectura del código después

Resuelto! ;)

2021-04-05 16:48 UTC, juuliotero approved these changes

2021-04-06 11:20 UTC, sychus approved these changes

2021-04-07 17:55 UTC, palita1991 approved these changes

2021-04-07 18:09 UTC, liquid36 commented
USUARIO: mpalavecino  
BUILD NUMBER: [3717](http://condorpiedra.andes.gob.ar:85/3717/mochawesome.html)
CYPRESS RUN: [2787](https://dashboard.cypress.io/projects/xr7gft/runs/2787/specs)
TEST START: 2021-04-07T18:06:28.613Z
TOTAL: 363
SUCCESS: 361
FAIL: 2
SKIPPED: 0

2021-04-07 18:13 UTC, liquid36 commented
USUARIO: mpalavecino  
BUILD NUMBER: [3718](http://condorpiedra.andes.gob.ar:85/3718/mochawesome.html)
CYPRESS RUN: [2788](https://dashboard.cypress.io/projects/xr7gft/runs/2788/specs)
TEST START: 2021-04-07T18:09:42.683Z
TOTAL: 7
SUCCESS: 7
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-04-09 11:43 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [3734](http://condorpiedra.andes.gob.ar:85/3734/mochawesome.html)
CYPRESS RUN: [2802](https://dashboard.cypress.io/projects/xr7gft/runs/2802/specs)
TEST START: 2021-04-09T11:40:50.137Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-04-09 11:57 UTC, merged