FICHA-EPIDEMIOLÓGICA: Enviar datos de la ficha epidemiológica a MPI
andes/app pull request #2180
Opened 2021-03-23 16:01 UTC by martinebucarey

### Requerimiento
https://proyectos.andes.gob.ar/browse/EP-21
- Agregar la posibilidad de enviar conceptos snomed a la ficha epidemiológica.

### Funcionalidad desarrollada 

1. Dado un código snomed ingresado en la creación de un nuevo formulario se obtiene el concepto y se muestra en el dropdown de selección de fichas.
2. Dado un campo de tipo snomed donde se ingrese una query snomed se obtiene el resultado de dicha query y se agregan los resultados en un plex-select.
3. Dados los campos teléfono, dirección, localidad y provincia, de la sección MPI de la ficha covid, se realiza la actualización del paciente en mpi con los nuevos datos dados por el mismo.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2021-03-23 16:15 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3640](http://condorpiedra.andes.gob.ar:85/3640/mochawesome.html)
CYPRESS RUN: [2717](https://dashboard.cypress.io/projects/xr7gft/runs/2717/specs)
TEST START: 2021-03-23T16:14:33.659Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-04-05 16:36 UTC, palita1991 requested changes
@martinebucarey  Apenas ingreso al punto de inicio de la ficha, me sale por consola lo siguiente
![image](https://user-images.githubusercontent.com/30004190/113598655-d78fc280-9613-11eb-885c-b0c09b5b0a63.png)

2021-04-05 18:30 UTC, palita1991 approved these changes

2021-04-16 16:16 UTC, sychus requested changes
Para no perder la info en mpi si no hacen ningún cambio propongo agregar un control.
1) Guardar en una estructura aux. cuando carga la ficha
2) Al momento de guardar, verificar si cambio algo. En caso negativo no llamar a mpi.

2021-04-22 18:46 UTC, martinebucarey commented
> Para no perder la info en mpi si no hacen ningún cambio propongo agregar un control.
> 
>     1. Guardar en una estructura aux. cuando carga la ficha
> 
>     2. Al momento de guardar, verificar si cambio algo. En caso negativo no llamar a mpi.

Se agregaron los cambios segun lo acordado en la reunión con epidemio.

2021-04-22 19:11 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3842](http://condorpiedra.andes.gob.ar:85/3842/mochawesome.html)
CYPRESS RUN: [2905](https://dashboard.cypress.io/projects/xr7gft/runs/2905/specs)
TEST START: 2021-04-22T19:08:15.847Z
TOTAL: 360
SUCCESS: 355
FAIL: 5
SKIPPED: 0

2021-04-23 13:12 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3846](http://condorpiedra.andes.gob.ar:85/3846/mochawesome.html)
CYPRESS RUN: [2909](https://dashboard.cypress.io/projects/xr7gft/runs/2909/specs)
TEST START: 2021-04-23T13:12:10.236Z
TOTAL: 366
SUCCESS: 366
FAIL: 0
SKIPPED: 0

2021-04-23 16:11 UTC, sychus approved these changes

2021-04-23 16:26 UTC, merged