PDP - Navegación lateral 'mis familiares'
andes/app pull request #2182
Opened 2021-03-23 19:29 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/PDP-31

### Funcionalidad desarrollada 

1. Visualización de familiares del paciente logueado y detalles de cada familiar seleccionado en el sidebar.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-03-26 15:43 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3675](http://condorpiedra.andes.gob.ar:85/3675/mochawesome.html)
CYPRESS RUN: [2746](https://dashboard.cypress.io/projects/xr7gft/runs/2746/specs)
TEST START: 2021-03-26T15:40:16.505Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-03-30 15:20 UTC, JSantarelli requested changes
Para evitar esta visualización al haber un único item en el `plex-grid` (ver adjunto), recomiendo type 'auto' y size 'xl'. El size de la `plex-card` mantener en el actual (ya que condiciona el tamaño de los elementos de la card)

![portal-grid](https://user-images.githubusercontent.com/5895886/113012051-cb59c000-9150-11eb-9525-2a80e5f57510.PNG)

2021-04-05 16:17 UTC, negro89 commented
> Para evitar esta visualización al haber un único item en el `plex-grid` (ver adjunto), recomiendo type 'auto' y size 'xl'. El size de la `plex-card` mantener en el actual (ya que condiciona el tamaño de los elementos de la card)
> 
Excelente @JSantarelli, cambios hechos.

2021-04-07 12:35 UTC, JSantarelli approved these changes

2021-04-16 17:08 UTC, palita1991 reviewed
@negro89 Resolver conflictos

2021-04-30 18:32 UTC, condorpiedra commented
Funcionalidad incluida en PR https://github.com/andes/app/pull/2206

2021-04-30 18:32 UTC, closed without merging