feat(CITAS):Imprimir agenda
andes/app pull request #2184
Opened 2021-03-25 14:00 UTC by palita1991

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-107

### Funcionalidad desarrollada 

1. Se saca print de pantalla al imprimir agendas
2. Se deja configuración para enviar los datos de la agenda a la api y generar el informe.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [x] Si https://github.com/andes/api/pull/1317
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2021-03-25 14:30 UTC, liquid36 commented
USUARIO: mpalavecino  
BUILD NUMBER: [3652](http://condorpiedra.andes.gob.ar:85/3652/mochawesome.html)
CYPRESS RUN: [2724](https://dashboard.cypress.io/projects/xr7gft/runs/2724/specs)
TEST START: 2021-03-25T14:23:06.019Z
TOTAL: 254
SUCCESS: 230
FAIL: 24
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-03-25 15:14 UTC, liquid36 commented
USUARIO: mpalavecino  
BUILD NUMBER: [3654](http://condorpiedra.andes.gob.ar:85/3654/mochawesome.html)
CYPRESS RUN: [2726](https://dashboard.cypress.io/projects/xr7gft/runs/2726/specs)
TEST START: 2021-03-25T15:12:04.125Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-03-25 16:17 UTC, juuliotero requested changes

2021-03-25 16:17 UTC, juuliotero commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-turnos.component.ts
> +    constructor(public plex: Plex, public servicePaciente: PacienteService, public documentosService: DocumentosService, public auth: Auth) { }
deberían ser private

2021-03-25 16:17 UTC, juuliotero commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-turnos.component.ts
>  import { IAgenda } from './../../../../interfaces/turnos/IAgenda';
los import AgendaService, IAgenda y moment no se usan

2021-03-25 16:17 UTC, juuliotero commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-turnos.component.ts
> +    async printAgenda(agendas) {
¿por qué es async?

2021-03-26 12:52 UTC, palita1991 commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-turnos.component.ts
> +    constructor(public plex: Plex, public servicePaciente: PacienteService, public documentosService: DocumentosService, public auth: Auth) { }
@juuliotero resuelto

2021-03-26 12:52 UTC, palita1991 commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-turnos.component.ts
>  import { IAgenda } from './../../../../interfaces/turnos/IAgenda';
@juuliotero resuelto

2021-03-26 12:53 UTC, palita1991 commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-turnos.component.ts
> +    async printAgenda(agendas) {
@juuliotero fue porque lo saque de otro ejemplo que habia, pero en este caso no era necesario al parecer. Lo saque y funcionaba igual

2021-03-29 16:21 UTC, liquid36 approved these changes
![image](https://user-images.githubusercontent.com/3813270/112867731-a2bec100-9091-11eb-9ee2-e9563f26b33f.png)

Eliminaría esa pantalla, que directamente el botón de imprimir escupa el PDF.  @kroce @condorpiedra ?

2021-03-29 16:46 UTC, palita1991 commented
> ![image](https://user-images.githubusercontent.com/3813270/112867731-a2bec100-9091-11eb-9ee2-e9563f26b33f.png)
> 
> Eliminaría esa pantalla, que directamente el botón de imprimir escupa el PDF. @kroce @condorpiedra ?

Lo deje por las dudas porque no sabia si los usuarios que van a imprimir quieren ver antes una visualización de lo que van a descargar. Espero ordenes de @kroce @condorpiedra

2021-03-29 18:11 UTC, juuliotero approved these changes

2021-03-31 17:27 UTC, kroce commented
> ![image](https://user-images.githubusercontent.com/3813270/112867731-a2bec100-9091-11eb-9ee2-e9563f26b33f.png)
> 
> Eliminaría esa pantalla, que directamente el botón de imprimir escupa el PDF. @kroce @condorpiedra ?

Lo subimos asi para que se corrija el problema y lo vemos con @MCele que es a la que le reportaron el bug a ver si le afecta en algo al usr que saquemos esa pantalla

2021-03-31 17:28 UTC, merged