feat(PDP):visualizar mis vacunas en el Portal de Pacientes.
andes/app pull request #2187
Opened 2021-03-26 15:13 UTC by waltergarrido

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/PDP-28
### Funcionalidad desarrollada 

1. se desarrolla funcionalidad para mostrar las vacunas de un paciente en PDP(portal de paciente)
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

para compilar:  ng serve --project portal

2021-03-30 16:41 UTC, andrrrl commented
![PDP-28](https://user-images.githubusercontent.com/11394455/113024865-a0c23400-915d-11eb-926e-8c766ef7d87f.png)

2021-03-30 16:50 UTC, andrrrl requested changes
![PDP-28](https://user-images.githubusercontent.com/11394455/113025925-dfa4b980-915e-11eb-9090-a705d7fcc7a3.png)

2021-04-06 13:48 UTC, palita1991 requested changes
@waltergarrido Como se puede ver, en huds al visualizar esta vacuna en particular posee el esquema de la misma, cuando se quiere visualizar desde el portal, sale en blanco. Tener en cuenta el detalle que te marco anteriormente @andrrrl sobre el icono de las vacunas que herede el color de RUP.
![image](https://user-images.githubusercontent.com/30004190/113719863-74119d80-96c4-11eb-8dbc-0be328f16acc.png)

![image](https://user-images.githubusercontent.com/30004190/113716700-3f501700-96c1-11eb-85d4-986ef453f5f7.png)

2021-04-08 17:05 UTC, waltergarrido commented
> @waltergarrido Como se puede ver, en huds al visualizar esta vacuna en particular posee el esquema de la misma, cuando se quiere visualizar desde el portal, sale en blanco. Tener en cuenta el detalle que te marco anteriormente @andrrrl sobre el icono de las vacunas que herede el color de RUP.
> ![image](https://user-images.githubusercontent.com/30004190/113719863-74119d80-96c4-11eb-8dbc-0be328f16acc.png)
> 
> ![image](https://user-images.githubusercontent.com/30004190/113716700-3f501700-96c1-11eb-85d4-986ef453f5f7.png)

@palita1991  la coleccion nomivac de la bd no tiene el atributo esquema , quedo para ser corregido , se corrige los colores .

2021-04-08 17:09 UTC, liquid36 commented
Tienen que contrastar contra la app mobile, no contra la HUDS. 
En la app mobile no figura el esquema aún, así que por el momento hay que obviarlo.

2021-04-09 12:32 UTC, liquid36 commented on projects/portal/src/app/services/prestaciones.service.ts
> +export class PrestacionService {
Esto debería ser el VacunaService.

2021-04-09 16:27 UTC, waltergarrido commented on projects/portal/src/app/services/prestaciones.service.ts
> +export class PrestacionService {
@liquid36 corregido

2021-04-13 14:12 UTC, liquid36 approved these changes

2021-04-13 14:29 UTC, merged