feat(PDP):visualizar mis laboratorios en el Portal de Pacientes
andes/app pull request #2188
Opened 2021-03-26 15:27 UTC by waltergarrido

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/PDP-29
### Funcionalidad desarrollada 

1. se desarrolla funcionalidad para mostrar los laboratorios de un paciente en PDP(portal de paciente)
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

para compilar: ng serve --project portal

2021-04-06 16:04 UTC, palita1991 approved these changes

2021-04-08 13:14 UTC, liquid36 requested changes
- No se puede descargar el laboratorio.
- Mirar bien, que en la MobileApp hay una lógica para los laboratorios que son protegidos.

2021-04-08 13:14 UTC, liquid36 commented on projects/portal/src/app/services/prestaciones.service.ts
> +export class PrestacionService {
limpiar este servicio que quedaron cosas viejas.

2021-04-08 13:14 UTC, liquid36 commented on projects/portal/src/app/pages/mis-laboratorios/mis-laboratorios.component.html
> +        <plex-title size="{{ isResponsive() ? 'sm' : 'md' }}" titulo="Detalle laboratorio">
Este plex-title va en la componente de laboratorio-detalle. Sino se van a empezar a pisar cada vez que agregues detalles de otras cosas.

2021-04-09 15:15 UTC, waltergarrido commented on projects/portal/src/app/services/prestaciones.service.ts
> +export class PrestacionService {
@liquid36 corregido

2021-04-09 15:15 UTC, waltergarrido commented on projects/portal/src/app/pages/mis-laboratorios/mis-laboratorios.component.html
> +        <plex-title size="{{ isResponsive() ? 'sm' : 'md' }}" titulo="Detalle laboratorio">
@liquid36 corregido

2021-04-13 13:53 UTC, liquid36 approved these changes

2021-04-13 13:56 UTC, merged