(PDP):visualizar mis turnos actuales
andes/app pull request #2191
Opened 2021-03-30 12:14 UTC by waltergarrido

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/PDP-30
### Funcionalidad desarrollada 

1. mostrar el listado de los turnos que tiene pendientes el paciente.
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-04-05 12:43 UTC, palita1991 reviewed
Arreglar confictos

2021-04-06 12:39 UTC, palita1991 requested changes
El badge "No asistió" en el sidebar no se visualiza
![image](https://user-images.githubusercontent.com/30004190/113711579-7f140000-96bb-11eb-8b42-3afbf40bb02f.png)

No recuerdo como era mockup, pero quizás para tener coherencia con los colores, estaría bueno que en el sidebar el badge de "asistió" sea del mismo color que en el listado.
![image](https://user-images.githubusercontent.com/30004190/113711701-a36fdc80-96bb-11eb-8945-5f425f42a098.png)

2021-04-06 12:59 UTC, andrrrl requested changes

2021-04-06 12:59 UTC, andrrrl commented on projects/portal/src/app/pages/mis-turnos/mis-turnos-detalles.component.html
> +        <plex-badge type="{{turno.asistencia==='asististe' ? 'success' : 'warning' }}">{{ turno.asistencia }}
Creo que es así, dentro de lo mismo que reportó @palita1991 
```suggestion
        <plex-badge type="{{turno.asistencia==='asistio' ? 'success' : 'warning' }}">{{ turno.asistencia }}
```

2021-04-06 14:37 UTC, andrrrl requested changes

2021-04-08 13:27 UTC, liquid36 requested changes

2021-04-08 13:27 UTC, liquid36 commented on projects/portal/src/app/services/prestaciones.service.ts
> +    private agendaUrl = '/modules/turnos/agenda';
Atención Aca! En la mobile APP se consume otra ruta.

2021-04-08 13:27 UTC, liquid36 commented on projects/portal/src/app/services/prestaciones.service.ts
> +    private agendaUrl = '/modules/turnos/agenda';
modules/mobileApp/turnos

2021-04-09 13:26 UTC, waltergarrido commented on projects/portal/src/app/pages/mis-turnos/mis-turnos-detalles.component.html
> +        <plex-badge type="{{turno.asistencia==='asististe' ? 'success' : 'warning' }}">{{ turno.asistencia }}
@andrrrl corregido

2021-04-09 13:27 UTC, waltergarrido commented
> El badge "No asistió" en el sidebar no se visualiza
> ![image](https://user-images.githubusercontent.com/30004190/113711579-7f140000-96bb-11eb-8b42-3afbf40bb02f.png)
> 
> No recuerdo como era mockup, pero quizás para tener coherencia con los colores, estaría bueno que en el sidebar el badge de "asistió" sea del mismo color que en el listado.
> ![image](https://user-images.githubusercontent.com/30004190/113711701-a36fdc80-96bb-11eb-8945-5f425f42a098.png)

@palita1991 corregido

2021-04-09 13:29 UTC, waltergarrido commented on projects/portal/src/app/services/prestaciones.service.ts
> +    private agendaUrl = '/modules/turnos/agenda';
@liquid36 corregido

2021-04-09 13:40 UTC, liquid36 commented on projects/portal/src/app/services/prestaciones.service.ts
> +        const headers = new HttpHeaders({ Authorization: 'JWT ' + token });
Todo esto del Headers y demás ya lo resuelve el Server.

2021-04-09 13:41 UTC, liquid36 commented on projects/portal/src/app/pages/mis-turnos/mis-turnos.component.ts
> +        this.familiar = window.sessionStorage.getItem('familiar');
La feature de familiar se desarrolla en otra user storie, no la agregaría ahora.

2021-04-09 15:43 UTC, waltergarrido commented on projects/portal/src/app/services/prestaciones.service.ts
> +        const headers = new HttpHeaders({ Authorization: 'JWT ' + token });
@liquid36 corregido

2021-04-09 15:43 UTC, waltergarrido commented on projects/portal/src/app/pages/mis-turnos/mis-turnos.component.ts
> +        this.familiar = window.sessionStorage.getItem('familiar');
@liquid36 corregido

2021-04-12 15:44 UTC, liquid36 approved these changes

2021-04-12 15:44 UTC, liquid36 commented
Quedan algunos detalles que se cargaron como Task para mejorar.

2021-04-12 15:46 UTC, merged