VAC: mostrar los datos del inscripto al consultar por la inscripción
andes/app pull request #2192
Opened 2021-03-30 15:11 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-22

### Funcionalidad desarrollada 
1. Mostrar datos del inscripto al consultar por la inscripción

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1322
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-03-30 16:24 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [3688](http://condorpiedra.andes.gob.ar:85/3688/mochawesome.html)
CYPRESS RUN: [2759](https://dashboard.cypress.io/projects/xr7gft/runs/2759/specs)
TEST START: 2021-03-30T16:21:17.035Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-03-30 18:44 UTC, palita1991 approved these changes

2021-03-31 04:38 UTC, sychus approved these changes
Me queda esa duda nomás

2021-03-31 04:38 UTC, sychus commented on src/app/apps/vacunacion/components/consulta.component.html
> +                        Localidad: {{ resultado.inscripto.localidad.nombre }}<br></p>
¿estamos seguros que siempre vamos a tener la localidad?

2021-03-31 12:15 UTC, juuliotero commented on src/app/apps/vacunacion/components/consulta.component.html
> +                        Localidad: {{ resultado.inscripto.localidad.nombre }}<br></p>
Listo. Si no llega la localidad, muestra 'Sin datos'

2021-04-05 14:26 UTC, kroce requested changes

2021-04-05 14:26 UTC, kroce commented on src/app/apps/vacunacion/components/consulta.component.html
> +                        Nombre y apellido: {{ resultado.inscripto.apellido }},
Un detalle...está invertido, dice nombre y apellido pero muestra apellido y nombre

2021-04-05 16:05 UTC, juuliotero commented on src/app/apps/vacunacion/components/consulta.component.html
> +                        Nombre y apellido: {{ resultado.inscripto.apellido }},
Corregido, se pone 'Inscripto:'

2021-04-05 17:29 UTC, kroce approved these changes

2021-04-05 17:43 UTC, merged