VAC - Asociar paciente a inscripción
andes/app pull request #2196
Opened 2021-03-31 15:33 UTC by negro89

tambien agrega filtro por fecha de registro al listado de inscriptos y filtra por defecto pacientes no vacunados

### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-23

### Funcionalidad desarrollada 

1. Opción en el sidebar de asociar un paciente ya registrado
2. Agrega filtros por fecha de registro y paciente vacunado/no vacunado (Por defecto)

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si  https://github.com/andes/api/pull/1325
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-03-31 15:48 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3694](http://condorpiedra.andes.gob.ar:85/3694/mochawesome.html)
CYPRESS RUN: [2765](https://dashboard.cypress.io/projects/xr7gft/runs/2765/specs)
TEST START: 2021-03-31T15:45:19.116Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-03-31 16:49 UTC, palita1991 requested changes
Como se puede observar en el video, en algún momento después de aplicar filtros de fechas pasa algo extraño. En este caso las fechas de registros son de 12/03 y aunque ponga 14/03 en desde y hasta, me las sigue trayendo igual.
https://www.loom.com/share/308f11322520424e90b3646205d0e973

Esto sale en api
![image](https://user-images.githubusercontent.com/30004190/113181602-5b1e6d80-9228-11eb-8999-ee9856048c90.png)

2021-04-05 16:02 UTC, negro89 commented
> Como se puede observar en el video, en algún momento después de aplicar filtros de fechas pasa algo extraño. En este caso las fechas de registros son de 12/03 y aunque ponga 14/03 en desde y hasta, me las sigue trayendo igual.
> https://www.loom.com/share/308f11322520424e90b3646205d0e973


Corregido!

2021-04-05 17:43 UTC, liquid36 requested changes

2021-04-05 17:43 UTC, liquid36 commented on src/app/apps/vacunacion/services/inscripcion.service.ts
> +                const desdeF = moment(fechaDesde).startOf('day').toDate();
Del lado de la API **inscripcion-vacunas** es un **ResourceBase**, así que del lado de la APP este servicio debería ser tambien **ResourceBaseHttp**.

De esta forma podes reutilizar esta lógica de las fechas duplicar código.

También aplica al tema del _.save()_.

2021-04-07 19:48 UTC, negro89 commented on src/app/apps/vacunacion/services/inscripcion.service.ts
> +                const desdeF = moment(fechaDesde).startOf('day').toDate();
buen dato, no lo sabia. Corregido.

2021-04-14 11:53 UTC, condorpiedra approved these changes

2021-04-14 11:55 UTC, merged