VAC: permitir editar inscripciones
andes/app pull request #2198
Opened 2021-04-05 15:56 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-21

### Funcionalidad desarrollada 
1. Permitir sanear errores en el tipeo en alguno de los datos de las inscripciones para vacunación

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1327
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-04-05 16:26 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [3701](http://condorpiedra.andes.gob.ar:85/3701/mochawesome.html)
CYPRESS RUN: [2771](https://dashboard.cypress.io/projects/xr7gft/runs/2771/specs)
TEST START: 2021-04-05T16:23:58.587Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-04-05 17:55 UTC, palita1991 requested changes
@juuliotero  
Cuando edito el estado de la inscripción,  a penas lo cambio me aparece [object Object] en el listado antes de que seleccione guardar. En este caso esta inscripción estaba como pendiente y la quise pasar habilitada. 
![image](https://user-images.githubusercontent.com/30004190/113606418-5853bc00-961e-11eb-902e-0b80e3acfc10.png)

Observación pequeña que puede confundir en caso de que utilicen el dato, como se puede ver en la imagen anterior el email esta con minúscula y fuera de la edición esta con la P en mayúscula
![image](https://user-images.githubusercontent.com/30004190/113606709-bed8da00-961e-11eb-8b60-0e01a56bdc08.png)

2021-04-07 15:45 UTC, JSantarelli commented
En línea con el comentario de @palita1991 respecto a la mayúsculas y minúsculas en los datos, recomiendo utilizar la [directiva [case]](https://www.andes.gob.ar/plex/doc/directives/CaseDirective.html) con valor 'lowercase'.

2021-04-07 16:04 UTC, JSantarelli requested changes

2021-04-07 16:25 UTC, juuliotero commented on src/app/apps/vacunacion/components/listado-inscriptos.html
> +            <plex-grid *ngIf="!editando" cols="3">
listo!

2021-04-07 16:25 UTC, juuliotero commented on src/app/apps/vacunacion/components/listado-inscriptos.html
>              <plex-button type="danger" icon="close" size="sm" (click)="closeSidebar()"></plex-button>
listo!

2021-04-07 16:25 UTC, juuliotero commented
> @juuliotero
> Cuando edito el estado de la inscripción, a penas lo cambio me aparece [object Object] en el listado antes de que seleccione guardar. En este caso esta inscripción estaba como pendiente y la quise pasar habilitada.
> ![image](https://user-images.githubusercontent.com/30004190/113606418-5853bc00-961e-11eb-902e-0b80e3acfc10.png)
> 
> Observación pequeña que puede confundir en caso de que utilicen el dato, como se puede ver en la imagen anterior el email esta con minúscula y fuera de la edición esta con la P en mayúscula
> ![image](https://user-images.githubusercontent.com/30004190/113606709-bed8da00-961e-11eb-8b60-0e01a56bdc08.png)

corregido

2021-04-07 17:34 UTC, palita1991 requested changes
@juuliotero 
Teniendo en cuenta esto:
**Cuando** hago click en una inscripción
si la inscripción se encuentra en estado pendiente y su grupo es factores-riesgo/discapacidad
**Entonces** poder modificar el grupo dentro de  factores-riesgo/discapacidad

Cuando cambio el grupo, el estado queda vacio
![image](https://user-images.githubusercontent.com/30004190/113909615-40ab3d80-97ae-11eb-9496-d0d2e6d8e704.png)
![image](https://user-images.githubusercontent.com/30004190/113909655-4d2f9600-97ae-11eb-850b-ec00a60f94b6.png)

2021-04-08 13:52 UTC, juuliotero commented
> @juuliotero
> Teniendo en cuenta esto:
> **Cuando** hago click en una inscripción
> si la inscripción se encuentra en estado pendiente y su grupo es factores-riesgo/discapacidad
> **Entonces** poder modificar el grupo dentro de factores-riesgo/discapacidad
> 
> Cuando cambio el grupo, el estado queda vacio
> ![image](https://user-images.githubusercontent.com/30004190/113909615-40ab3d80-97ae-11eb-9496-d0d2e6d8e704.png)
> ![image](https://user-images.githubusercontent.com/30004190/113909655-4d2f9600-97ae-11eb-850b-ec00a60f94b6.png)

no puedo reproducir el caso

2021-04-08 18:48 UTC, palita1991 commented
> > @juuliotero
> > Teniendo en cuenta esto:
> > **Cuando** hago click en una inscripción
> > si la inscripción se encuentra en estado pendiente y su grupo es factores-riesgo/discapacidad
> > **Entonces** poder modificar el grupo dentro de factores-riesgo/discapacidad
> > Cuando cambio el grupo, el estado queda vacio
> > ![image](https://user-images.githubusercontent.com/30004190/113909615-40ab3d80-97ae-11eb-9496-d0d2e6d8e704.png)
> > ![image](https://user-images.githubusercontent.com/30004190/113909655-4d2f9600-97ae-11eb-850b-ec00a60f94b6.png)
> 
> no puedo reproducir el caso

@juuliotero es raro porque me pasa que no se visualiza el estado, pero en la base no se borro solo con actualizar la pagina me aparece de nuevo y con el grupo correctamente cambiado. Porque será que me pasa eso?
https://www.loom.com/share/547d0dc3199844e69de51930b33c8e83

2021-04-09 11:16 UTC, JSantarelli approved these changes

2021-04-09 14:08 UTC, juuliotero commented
> > > @juuliotero
> > > Teniendo en cuenta esto:
> > > **Cuando** hago click en una inscripción
> > > si la inscripción se encuentra en estado pendiente y su grupo es factores-riesgo/discapacidad
> > > **Entonces** poder modificar el grupo dentro de factores-riesgo/discapacidad
> > > Cuando cambio el grupo, el estado queda vacio
> > > ![image](https://user-images.githubusercontent.com/30004190/113909615-40ab3d80-97ae-11eb-9496-d0d2e6d8e704.png)
> > > ![image](https://user-images.githubusercontent.com/30004190/113909655-4d2f9600-97ae-11eb-850b-ec00a60f94b6.png)
> > 
> > 
> > no puedo reproducir el caso
> 
> @juuliotero es raro porque me pasa que no se visualiza el estado, pero en la base no se borro solo con actualizar la pagina me aparece de nuevo y con el grupo correctamente cambiado. Porque será que me pasa eso?
> 
> https://www.loom.com/share/547d0dc3199844e69de51930b33c8e83

quedó corregido!

2021-04-09 15:22 UTC, palita1991 approved these changes

2021-04-14 15:12 UTC, merged