feat(ficha-epidemiologica): Se agrega el identificador de ficha
andes/app pull request #2199
Opened 2021-04-06 15:57 UTC by sychus

Se crea el campo de identificación de ficha que estará asociada al hisopo.
### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [x] Si
- [ ] No
https://github.com/andes/api/pull/1330

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2021-04-06 16:17 UTC, liquid36 commented
USUARIO: hfernandez  
BUILD NUMBER: [3709](http://condorpiedra.andes.gob.ar:85/3709/mochawesome.html)
CYPRESS RUN: [2779](https://dashboard.cypress.io/projects/xr7gft/runs/2779/specs)
TEST START: 2021-04-06T16:14:11.736Z
TOTAL: 363
SUCCESS: 360
FAIL: 3
SKIPPED: 0

2021-04-06 16:42 UTC, palita1991 requested changes
Cuando busco al paciente, lo selecciono, hago click en nueva ficha y selecciono la ficha me sale ese error por la consola
![image](https://user-images.githubusercontent.com/30004190/113747409-bd221b80-96dd-11eb-89e4-236e2ec770e5.png)

2021-04-06 17:01 UTC, sychus commented
> Cuando busco al paciente, lo selecciono, hago click en nueva ficha y selecciono la ficha me sale ese error por la consola
> ![image](https://user-images.githubusercontent.com/30004190/113747409-bd221b80-96dd-11eb-89e4-236e2ec770e5.png)

Listo @palita1991

2021-04-06 17:21 UTC, palita1991 reviewed
@sychus consulta, mira ahi en la imagen se ve como pude crear dos con el mismo identificador, esta bien que me deje o me deberia tirar un cartel? Pregunto porque en formulario dice identificador único de ficha
![image](https://user-images.githubusercontent.com/30004190/113752274-25bfc700-96e3-11eb-8274-097253016ad2.png)

2021-04-07 04:18 UTC, sychus commented
> @sychus consulta, mira ahi en la imagen se ve como pude crear dos con el mismo identificador, esta bien que me deje o me deberia tirar un cartel? Pregunto porque en formulario dice identificador único de ficha
> ![image](https://user-images.githubusercontent.com/30004190/113752274-25bfc700-96e3-11eb-8274-097253016ad2.png)

Claro, no debería pasar eso. En la api le agregué el index y el unique pero tengo que ver porque no da bola.

2021-04-07 15:46 UTC, palita1991 commented
> > @sychus consulta, mira ahi en la imagen se ve como pude crear dos con el mismo identificador, esta bien que me deje o me deberia tirar un cartel? Pregunto porque en formulario dice identificador único de ficha
> > ![image](https://user-images.githubusercontent.com/30004190/113752274-25bfc700-96e3-11eb-8274-097253016ad2.png)
> 
> Claro, no debería pasar eso. En la api le agregué el index y el unique pero tengo que ver porque no da bola.

@sychus probe localmente, pero nuevamente me dejo crear una ficha con un identificador que pertenece a otra ficha anteriormente creada.

2021-04-08 01:04 UTC, sychus commented
> > > @sychus consulta, mira ahi en la imagen se ve como pude crear dos con el mismo identificador, esta bien que me deje o me deberia tirar un cartel? Pregunto porque en formulario dice identificador único de ficha
> > > ![image](https://user-images.githubusercontent.com/30004190/113752274-25bfc700-96e3-11eb-8274-097253016ad2.png)
> > 
> > 
> > Claro, no debería pasar eso. En la api le agregué el index y el unique pero tengo que ver porque no da bola.
> 
> @sychus probe localmente, pero nuevamente me dejo crear una ficha con un identificador que pertenece a otra ficha anteriormente creada.

Si si .... raro estoy buscando un psicóloco ya...   X-(

2021-04-08 11:41 UTC, liquid36 commented
USUARIO: hfernandez  
BUILD NUMBER: [3722](http://condorpiedra.andes.gob.ar:85/3722/mochawesome.html)
CYPRESS RUN: [2792](https://dashboard.cypress.io/projects/xr7gft/runs/2792/specs)
TEST START: 2021-04-08T11:38:31.104Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-04-08 17:09 UTC, sychus commented
Se cierra por cambio en los requerimientos

2021-04-08 17:09 UTC, closed without merging