VAC - Filtra grupos según permisos, habilita edición
andes/app pull request #2200
Opened 2021-04-07 19:43 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-20

### Funcionalidad desarrollada 

1. Filtra grupos poblacionales segun permiso
2. Nueva seccion para editar datos del inscripto en el sidebar de detalles
3. Agrega columna 'telefono' al listado de inscriptos
4. Extiende servicio de inscipcion a resource base

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1331
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-04-07 19:55 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3719](http://condorpiedra.andes.gob.ar:85/3719/mochawesome.html)
CYPRESS RUN: [2789](https://dashboard.cypress.io/projects/xr7gft/runs/2789/specs)
TEST START: 2021-04-07T19:52:07.863Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-04-08 14:07 UTC, JSantarelli requested changes

2021-04-08 14:07 UTC, JSantarelli commented on src/app/apps/vacunacion/components/listado-inscriptos.html
> +                <div>
Utilizar [directiva justify](https://www.andes.gob.ar/plex/doc/directives/JustifyDirective.html) en el `<div>` que envuelve en lugar de las clases 'float' de bootstrap.

2021-04-08 14:07 UTC, JSantarelli commented on src/app/apps/vacunacion/components/listado-inscriptos.html
> +            <ng-container *ngIf="editarDatos">
Envolver todo el formulario en un `plex-wrapper` y a éste en un `ng-container` incluyendo los botones de confirmación. Utilizar la directiva 'grow' con valor full a los primeros dos `plex-select` para mantener la disposición actual.

2021-04-08 16:24 UTC, negro89 commented on src/app/apps/vacunacion/components/listado-inscriptos.html
> +            <ng-container *ngIf="editarDatos">
corregido!

2021-04-09 10:52 UTC, JSantarelli approved these changes

2021-04-15 13:15 UTC, kroce commented
Se resolvió en https://github.com/andes/app/pull/2198

2021-04-15 13:15 UTC, closed without merging