VAC: Nueva inscripción
andes/app pull request #2201
Opened 2021-04-08 11:37 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-28

### Funcionalidad desarrollada 

1. Permitir cargar una nueva inscripción a partir de un paciente

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1332
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-04-16 13:13 UTC, palita1991 requested changes

2021-04-16 13:13 UTC, palita1991 commented on src/app/apps/vacunacion/components/nueva-inscripcion/nueva-inscripcion.component.ts
> +        { id: 'lista-espera', label: 'Pacientes en lista de espera para trasplante y trasplantados (excepto córnea)' }
@juuliotero las morbilidades no se sacan de la base de datos? como esta en inscripcion.component ?

2021-04-16 17:14 UTC, juuliotero commented on src/app/apps/vacunacion/components/nueva-inscripcion/nueva-inscripcion.component.ts
> +        { id: 'lista-espera', label: 'Pacientes en lista de espera para trasplante y trasplantados (excepto córnea)' }
Si, quedó viejo. Ya está corregido.

2021-04-20 18:38 UTC, kroce requested changes
Al elegir el grupo de factores de riesgo me tirá un error
![image](https://user-images.githubusercontent.com/18030170/115447086-76a8e280-a1ee-11eb-9c38-9bd352288f13.png)

2021-04-21 12:29 UTC, juuliotero commented
> Al elegir el grupo de factores de riesgo me tirá un error
> ![image](https://user-images.githubusercontent.com/18030170/115447086-76a8e280-a1ee-11eb-9c38-9bd352288f13.png)

corregido

2021-04-21 15:45 UTC, condorpiedra commented
Debería controlar si el paciente esta previamente inscripto realizando la búsqueda por documento y sexo. Verificar también el estado.

2021-04-22 14:49 UTC, kroce approved these changes

2021-04-22 16:00 UTC, palita1991 approved these changes

2021-04-22 16:06 UTC, merged