feat(VAC):agrega morbilidades a base de datos
andes/app pull request #2202
Opened 2021-04-08 16:52 UTC by palita1991

### Requerimiento
 
https://proyectos.andes.gob.ar/projects/VAC/issues/VAC-32?filter=allissues

### Funcionalidad desarrollada 

1. Se agrega Factor de riesgo asociado a vacunación contra COVID-19 a la colección de grupo-poblacional

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [x] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2021-04-08 17:11 UTC, liquid36 commented
USUARIO: mpalavecino  
BUILD NUMBER: [3727](http://condorpiedra.andes.gob.ar:85/3727/mochawesome.html)
CYPRESS RUN: [2795](https://dashboard.cypress.io/projects/xr7gft/runs/2795/specs)
TEST START: 2021-04-08T17:08:30.385Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-04-09 11:28 UTC, kroce approved these changes

2021-04-09 13:02 UTC, juuliotero requested changes

2021-04-09 13:02 UTC, juuliotero commented on src/app/apps/vacunacion/components/inscripcion.component.ts
> +                            this.grupofr = grupos.find(g => g.nombre === 'factores-riesgo');
Esto podría hacerse directamente en el onInit. La variable grupofr no debería ser de clase ya que solo se usa dentro del método, usar un const.

2021-04-09 13:17 UTC, juuliotero approved these changes

2021-04-09 13:59 UTC, merged