BI: biquery ficha epidemio
andes/app pull request #2204
Opened 2021-04-08 19:13 UTC by plammel

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/BI-75
### Funcionalidad desarrollada 

1. Biquery para ficha epidemiológica
2. Cambio de type de ficha por `{ id, name }`
3. 

### UserStory llegó a completarse

- [ ] Si https://proyectos.andes.gob.ar/browse/BI-75
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si https://github.com/andes/api/pull/1334
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2021-04-08 19:29 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [3731](http://condorpiedra.andes.gob.ar:85/3731/mochawesome.html)
CYPRESS RUN: [2799](https://dashboard.cypress.io/projects/xr7gft/runs/2799/specs)
TEST START: 2021-04-08T19:26:23.675Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-04-13 15:11 UTC, sychus commented
@plammel me da este error:
formsEpidemiologia validation failed: type: Cast to string failed for value "{ id: '600ceaf8220da69a4bbe7223', name: 'covid19' }" at path "type"

2021-04-13 15:11 UTC, sychus requested changes
Verificar error al guardar la ficha en la validación del form

2021-04-13 15:54 UTC, plammel commented
> Verificar error al guardar la ficha en la validación del form

@sychus  eso es porqué cambio el `{ type: String }` a `{ type: { id: ObjectId, name: String } }`. Asegurate de probarlo con la branch BI-75  borrar los registros pre-existentes de fichasEpidemiologicas o editarlos para que se ajusten al nuevo schema.

2021-04-14 16:29 UTC, sychus approved these changes

2021-04-14 16:32 UTC, martinebucarey approved these changes

2021-04-14 16:33 UTC, merged