PDP - Uso de pacienteCache
andes/app pull request #2206
Opened 2021-04-09 18:05 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/PDP-37

### Funcionalidad desarrollada 

1. Utiliza el servicio de paciente caché para evitar recurrentes peticiones sobre el paciente principal correspondiente al usuario logeado

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-04-10 03:19 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3740](http://condorpiedra.andes.gob.ar:85/3740/mochawesome.html)
CYPRESS RUN: [2806](https://dashboard.cypress.io/projects/xr7gft/runs/2806/specs)
TEST START: 2021-04-10T03:16:16.619Z
TOTAL: 363
SUCCESS: 362
FAIL: 1
SKIPPED: 0

2021-04-12 15:51 UTC, liquid36 requested changes
esto se puede resolver desde RxJs usando algunos de los operadores de Cache que ya tenemos desarrollados.

2021-04-21 12:02 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3809](http://condorpiedra.andes.gob.ar:85/3809/mochawesome.html)
CYPRESS RUN: [2872](https://dashboard.cypress.io/projects/xr7gft/runs/2872/specs)
TEST START: 2021-04-21T11:59:06.748Z
TOTAL: 366
SUCCESS: 365
FAIL: 1
SKIPPED: 0

2021-04-22 13:09 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3832](http://condorpiedra.andes.gob.ar:85/3832/mochawesome.html)
CYPRESS RUN: [2895](https://dashboard.cypress.io/projects/xr7gft/runs/2895/specs)
TEST START: 2021-04-22T13:04:45.507Z
TOTAL: 366
SUCCESS: 366
FAIL: 0
SKIPPED: 0

2021-05-20 13:17 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [4116](http://condorpiedra.andes.gob.ar:85/4116/mochawesome.html)
CYPRESS RUN: [3152](https://dashboard.cypress.io/projects/xr7gft/runs/3152/specs)
TEST START: 2021-05-20T13:16:51.302Z
TOTAL: 393
SUCCESS: 393
FAIL: 0
SKIPPED: 0

2021-05-20 13:21 UTC, condorpiedra approved these changes

2021-05-20 13:21 UTC, merged