feat(RUP):rup-card, links a informacion
andes/app pull request #2217
Opened 2021-04-15 15:16 UTC by waltergarrido

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/RUP-231
### Funcionalidad desarrollada 

1. se pueden agregar links a archivos en plantillas-rup , para luego desde rup poder desplegar el dropdown y seleccionar un item-link y poder visualizar el archivo en una nueva pestaña .
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-04-15 15:32 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3766](http://condorpiedra.andes.gob.ar:85/3766/mochawesome.html)
CYPRESS RUN: [2831](https://dashboard.cypress.io/projects/xr7gft/runs/2831/specs)
TEST START: 2021-04-15T15:20:11.567Z
TOTAL: 353
SUCCESS: 346
FAIL: 7
SKIPPED: 0

2021-04-15 15:51 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3767](http://condorpiedra.andes.gob.ar:85/3767/mochawesome.html)
CYPRESS RUN: [2832](https://dashboard.cypress.io/projects/xr7gft/runs/2832/specs)
TEST START: 2021-04-15T15:48:36.010Z
TOTAL: 366
SUCCESS: 365
FAIL: 1
SKIPPED: 0

2021-04-16 11:38 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3782](http://condorpiedra.andes.gob.ar:85/3782/mochawesome.html)
CYPRESS RUN: [2847](https://dashboard.cypress.io/projects/xr7gft/runs/2847/specs)
TEST START: 2021-04-16T11:34:59.521Z
TOTAL: 315
SUCCESS: 304
FAIL: 11
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-04-16 12:16 UTC, liquid36 requested changes

2021-04-16 12:16 UTC, liquid36 commented on src/app/modules/rup/services/plantillas.service.ts
> +            return () => { this.cos.notify({ conceptId: ctid } as any, { link: plantilla.link } as any); };
```suggestion
            return () => { 
                 // ACA ABRIR EL LINK.
            };
```

2021-04-16 12:39 UTC, waltergarrido commented on src/app/modules/rup/services/plantillas.service.ts
> +            return () => { this.cos.notify({ conceptId: ctid } as any, { link: plantilla.link } as any); };
@liquid36 corregido.

2021-04-16 16:53 UTC, liquid36 approved these changes

2021-04-16 17:06 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3791](http://condorpiedra.andes.gob.ar:85/3791/mochawesome.html)
CYPRESS RUN: [2856](https://dashboard.cypress.io/projects/xr7gft/runs/2856/specs)
TEST START: 2021-04-16T17:03:18.614Z
TOTAL: 366
SUCCESS: 366
FAIL: 0
SKIPPED: 0

2021-04-21 18:05 UTC, negro89 approved these changes

2021-04-30 16:22 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3900](http://condorpiedra.andes.gob.ar:85/3900/mochawesome.html)
CYPRESS RUN: [2956](https://dashboard.cypress.io/projects/xr7gft/runs/2956/specs)
TEST START: 2021-04-30T16:22:29.288Z
TOTAL: 367
SUCCESS: 367
FAIL: 0
SKIPPED: 0

2021-05-04 12:45 UTC, andrrrl commented
Cuando se selecciona un concepto, por defecto agrega una plantilla. Por tanto, si quiero poner un link, tengo que borrar esa plantilla y elegir Agregar => enlace externo. Se cargó [una user para solucionar ese problema](https://proyectos.andes.gob.ar/browse/RUP-231).

2021-05-04 13:10 UTC, merged