VAC - Plex-table en listado inscriptos
andes/app pull request #2221
Opened 2021-04-16 15:23 UTC by negro89

### Requerimiento
Reemplazar table común por plex-table

### Funcionalidad desarrollada 

1. Se reemplaza la table por plex-table eliminando la funcion 'sort' hasta resolver conflicto con scroll infinito

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-04-16 15:53 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3786](http://condorpiedra.andes.gob.ar:85/3786/mochawesome.html)
CYPRESS RUN: [2851](https://dashboard.cypress.io/projects/xr7gft/runs/2851/specs)
TEST START: 2021-04-16T15:50:50.837Z
TOTAL: 366
SUCCESS: 366
FAIL: 0
SKIPPED: 0

2021-04-16 18:47 UTC, palita1991 approved these changes

2021-04-19 13:53 UTC, JSantarelli requested changes
En los [filtros](https://github.com/andes/app/blob/ef2ac0692f7c2900c3c89b9960c6af678b70ce42/src/app/apps/vacunacion/components/filtros-vacunacion.html) recomiendo implementar directiva grow para asignar el espacio correcto a cada input. En éste caso, el campo de grupo y el resto con grow="4". Los datetimes sin directiva asi mantienen su tamaño por defecto.

2021-04-19 13:53 UTC, JSantarelli commented on src/app/apps/vacunacion/components/listado-inscriptos.html
>          <plex-title titulo="Listado de inscriptos para vacunación" size="lg"> </plex-title>
Acá lo ideal sería que tanto título como filtros queden fijos y sólo scrollee el listado. El selector 'main' en el `plex-title` lo resolvería pero como los filtros están en un componente a parte, no funciona. Por lo tanto, lo que sugiero es envolver tanto `plex-title` como `plex-wrapper` dentro de un tag `header`.  **Nota:** Se visualizará doble línea al final del wrapper.

2021-04-19 13:53 UTC, JSantarelli commented on src/app/apps/vacunacion/components/listado-inscriptos.html
> +        <plex-table [columns]="columns" #table="plTable" [height]="400" (scroll)="onScroll()">
Sacar [height] y setear [offset] en 0 para evitar espacio al final del listado.

2021-04-19 14:23 UTC, kroce commented
Subió en https://github.com/andes/app/pull/2223
Se tendrán en cuenta las sugerencias para una tarea aparte.

2021-04-19 14:23 UTC, closed without merging

2021-04-19 14:51 UTC, JSantarelli commented
Perfecto. Acá les dejé la [tarea escrita](https://proyectos.andes.gob.ar/browse/VAC-44) por si la quieren revisar o modificar.