VAC - Agregar nota a una inscripción
andes/app pull request #2222
Opened 2021-04-16 15:29 UTC by negro89

### Requerimiento
Poder agregar una nota a las inscripciones

### Funcionalidad desarrollada 

1. Se agrega opcion en el sidebar para agregar una nota en texto libre
2. Se observa un icon 'comment' en la columna 'grupo' si la inscripción posee una nota

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1346
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-04-16 16:06 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3787](http://condorpiedra.andes.gob.ar:85/3787/mochawesome.html)
CYPRESS RUN: [2852](https://dashboard.cypress.io/projects/xr7gft/runs/2852/specs)
TEST START: 2021-04-16T16:03:25.429Z
TOTAL: 366
SUCCESS: 366
FAIL: 0
SKIPPED: 0

2021-04-19 11:28 UTC, condorpiedra commented
- Seria bueno que la nota se vea sobre el estado de la inscripción
- cuando se guarda estado y luego la nota, ésta no aparece inmediatamente, hay que refrescar para verla

2021-04-19 15:56 UTC, plammel requested changes
Algunos comentarios y consultas:
1. El sort de columnas no funciona.
2. Sugiero mostrar un sort por defecto (si es que hay algún criterio de ordenamiento por defecto). Al no estar visible a priori ninguna flecha de sort, pareciera que la posibilidad de ordenar por columnas no está disponible.
3. ¿La transparencia del header de la tabla es el efecto deseado? 
![image](https://user-images.githubusercontent.com/25707055/115265054-3d4c7600-a10d-11eb-95e6-0ca61f6266a8.png)
4. La nota ingresada no se muestra en los datos de inscripción.
5. El botón reza "Agregar nota", pero en los hechos sobreescribe la nota preexistente (si la hay). ¿Las notas deberían ser acumulables (es decir, poder ingresar mas de una), o la idea es que sólo exista una nota por inscripción? ¿o ingresar varias anotaciones pero siempre en el mismo campo?.
6. ¿Es válido incluir datos de auditoría de la nota, o para éste caso no aplica?

2021-04-19 15:56 UTC, plammel commented on src/app/apps/vacunacion/components/listado-inscriptos.component.ts
> +    // public selectedColumn = null;
```suggestion
```

2021-04-19 18:13 UTC, kroce approved these changes

2021-04-19 18:26 UTC, plammel approved these changes

2021-04-19 18:27 UTC, plammel commented
> @plammel gracias por las observaciones
> 
> 1. El sort de columnas esta deshabilitado hasta que se fixee un bug.
> 2. El ordenamiento no estaría disponible por el momento pero en el código los criterios permanecen. Lo que se quitó fue la acción de ordenar el response.
> 3. La transparencia viene dada por el componente plex.
> 4. Por el momento las notas no son acumulables. Esto quedará para una mejora futura.
> 5. Por ahora es texto libre y no se audita.

De diego!!

2021-04-19 18:38 UTC, merged