EPIDEMIOLOGÍA: Scroll infinito buscador
andes/app pull request #2229
Opened 2021-04-20 18:17 UTC by martinebucarey

### Requerimiento
https://proyectos.andes.gob.ar/browse/EP-33

### Funcionalidad desarrollada 

1. Se agrega scroll infinito y las funciones sort para cada columna.

### UserStory llegó a completarse

- [ ] Si
- [x] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

### Observacion
Queda pendiente una mejora en la UI al seleccionar un paciente.

2021-04-20 18:28 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3806](http://condorpiedra.andes.gob.ar:85/3806/mochawesome.html)
CYPRESS RUN: [2869](https://dashboard.cypress.io/projects/xr7gft/runs/2869/specs)
TEST START: 2021-04-20T18:25:25.910Z
TOTAL: 366
SUCCESS: 366
FAIL: 0
SKIPPED: 0

2021-04-20 19:32 UTC, JSantarelli requested changes

2021-04-20 19:32 UTC, JSantarelli commented on src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
>          <plex-grid type="full" size="lg">
Para mejorar visualización recomiendo 3 columnas fijas y el wrapper ocupando 2  con la directiva [span]. Como el wrapper se reutiliza en la pantalla de búsqueda, implementar con la condición correspondiente (ver video adjunto). 

https://user-images.githubusercontent.com/5895886/115452252-90e5bf00-a1f4-11eb-9690-92292a78c7ca.mp4

2021-04-20 19:32 UTC, JSantarelli commented on src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
> +            <plex-detail justify="center" *ngIf="pacienteSelected">
La directiva [justify] en valor 'start', para marginar el elemento a la izquierda y que no quede un blanco indeseado. Y otro detalle es que en el sidebar, una vez realizada la búsqueda, persiste el mensaje de 'buscar por dni... '

https://user-images.githubusercontent.com/5895886/115453364-ed95a980-a1f5-11eb-99fc-d40085999ea3.mp4

2021-04-20 19:32 UTC, JSantarelli commented on src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
> +        <plex-table *ngIf="listado?.length && !inProgress" [columns]="columns" #table="plTable" (scroll)="onScroll()"
Al intentar sortear el tipo de ficha deja de tener efecto la funcionalidad. Dejo video adjunto con error.

https://user-images.githubusercontent.com/5895886/115453245-c4751900-a1f5-11eb-9e13-9db85398b32c.mp4

2021-04-21 12:48 UTC, martinebucarey commented
@JSantarelli Subidas las observaciones. Gracias!!

2021-04-21 13:00 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3811](http://condorpiedra.andes.gob.ar:85/3811/mochawesome.html)
CYPRESS RUN: [2874](https://dashboard.cypress.io/projects/xr7gft/runs/2874/specs)
TEST START: 2021-04-21T12:57:21.348Z
TOTAL: 366
SUCCESS: 364
FAIL: 2
SKIPPED: 0

2021-04-21 13:13 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3812](http://condorpiedra.andes.gob.ar:85/3812/mochawesome.html)
CYPRESS RUN: [2875](https://dashboard.cypress.io/projects/xr7gft/runs/2875/specs)
TEST START: 2021-04-21T13:10:27.336Z
TOTAL: 366
SUCCESS: 365
FAIL: 1
SKIPPED: 0

2021-04-22 15:22 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3836](http://condorpiedra.andes.gob.ar:85/3836/mochawesome.html)
CYPRESS RUN: [2899](https://dashboard.cypress.io/projects/xr7gft/runs/2899/specs)
TEST START: 2021-04-22T15:18:58.067Z
TOTAL: 366
SUCCESS: 363
FAIL: 3
SKIPPED: 0

2021-04-22 15:32 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3837](http://condorpiedra.andes.gob.ar:85/3837/mochawesome.html)
CYPRESS RUN: [2900](https://dashboard.cypress.io/projects/xr7gft/runs/2900/specs)
TEST START: 2021-04-22T15:29:19.628Z
TOTAL: 366
SUCCESS: 366
FAIL: 0
SKIPPED: 0

2021-04-22 15:43 UTC, JSantarelli approved these changes

2021-04-23 16:41 UTC, sychus approved these changes
Piutiful :-)

2021-04-23 18:43 UTC, merged