fix(PDP):ordenar turnos de mas reciente a los mas viejos ultimos
andes/app pull request #2234
Opened 2021-04-21 12:19 UTC by waltergarrido

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/PDP-46
### Funcionalidad desarrollada 

1. ordenar turnos 
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-04-21 14:21 UTC, sychus requested changes

2021-04-21 14:21 UTC, sychus commented on projects/portal/src/app/pages/mis-turnos/mis-turnos.component.ts
> +        );
Ojo acá, el reverse simplemente cambiar el orden del array. Es decir, el que estaba al final al principio y así con cada elemento pero no necesariamente ordena. Esto está supeditado a como efectivamente se guarda. Lo idea sería recuperar la información ordenada desde la query en mongo o en su defecto hacer un sort en memoria creando en sort la función que ordene por ejemplo por fecha de turno.

2021-04-21 15:43 UTC, waltergarrido commented on projects/portal/src/app/pages/mis-turnos/mis-turnos.component.ts
> +        );
@sychus corregido

2021-04-22 03:12 UTC, sychus approved these changes

2021-04-22 13:22 UTC, liquid36 approved these changes

2021-04-22 13:39 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3834](http://condorpiedra.andes.gob.ar:85/3834/mochawesome.html)
CYPRESS RUN: [2897](https://dashboard.cypress.io/projects/xr7gft/runs/2897/specs)
TEST START: 2021-04-22T13:35:40.318Z
TOTAL: 366
SUCCESS: 366
FAIL: 0
SKIPPED: 0

2021-04-22 13:47 UTC, merged