COM: unidad destino derivación
andes/app pull request #2235
Opened 2021-04-22 12:28 UTC by plammel

### Requerimiento
 
https://github.com/andes/api/compare/COM-70
### Funcionalidad desarrollada 

1. Incluye unidad destino a derivación
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si https://github.com/andes/api/pull/1357
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2021-04-22 12:42 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [3830](http://condorpiedra.andes.gob.ar:85/3830/mochawesome.html)
CYPRESS RUN: [2893](https://dashboard.cypress.io/projects/xr7gft/runs/2893/specs)
TEST START: 2021-04-22T12:39:08.664Z
TOTAL: 366
SUCCESS: 366
FAIL: 0
SKIPPED: 0

2021-04-23 17:14 UTC, negro89 requested changes
Algunas preguntas/observaciones:
1. Al imprimir el comprobante de una derivación finalizada no se observa la unidad destino entre los datos, si embargo realizando la derivación se seleccionó unidad.
2. Quizás no sea un requerimiento en esta tarea pero observando desde el COM, o ya sea desde organización origen o destino una derivación finalizada, no se visualiza la unidad destino en los detalles del sidebar. Pero sí se muestra en el historial. Es correcto?

2021-04-23 18:11 UTC, plammel commented
> Algunas preguntas/observaciones:
> 
> 1. Al imprimir el comprobante de una derivación finalizada no se observa la unidad destino entre los datos, si embargo realizando la derivación se seleccionó unidad.
> 2. Quizás no sea un requerimiento en esta tarea pero observando desde el COM, o ya sea desde organización origen o destino una derivación finalizada, no se visualiza la unidad destino en los detalles del sidebar. Pero sí se muestra en el historial. Es correcto?

@negro89 no pude reproducir lo mencionado. Verifica que la tener la última versión de la brach COM-70 en la api. Si persiste, dar más detalles del caso
![image](https://user-images.githubusercontent.com/25707055/115912425-b0275b00-a445-11eb-8b75-2bad81cfc528.png)
![image](https://user-images.githubusercontent.com/25707055/115912531-d1884700-a445-11eb-8d23-3ebbb18935c3.png)

2021-04-26 20:16 UTC, sychus approved these changes

2021-04-27 18:28 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [3877](http://condorpiedra.andes.gob.ar:85/3877/mochawesome.html)
CYPRESS RUN: [2936](https://dashboard.cypress.io/projects/xr7gft/runs/2936/specs)
TEST START: 2021-04-27T18:28:03.196Z
TOTAL: 367
SUCCESS: 367
FAIL: 0
SKIPPED: 0

2021-04-28 12:24 UTC, sychus approved these changes
ahora va bárbaro!!!

2021-04-28 14:11 UTC, martinebucarey approved these changes

2021-04-28 14:13 UTC, liquid36 approved these changes

2021-04-28 14:31 UTC, merged