feat(MPI): se restringe tipos de datos en ventana popUp
andes/app pull request #2237
Opened 2021-04-23 13:19 UTC by waltergarrido

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/MPI-331
### Funcionalidad desarrollada 

1.En la ventana de popUp al momento de navegar el sistema de archivos, En lugar de permitirte seleccionar "todos", se  restringe a los tipo de datos que soporta, para que el usuario no elija un formato inválido 
2. 
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-04-23 13:42 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3848](http://condorpiedra.andes.gob.ar:85/3848/mochawesome.html)
CYPRESS RUN: [2911](https://dashboard.cypress.io/projects/xr7gft/runs/2911/specs)
TEST START: 2021-04-23T13:42:32.922Z
TOTAL: 366
SUCCESS: 359
FAIL: 7
SKIPPED: 0

2021-04-26 17:13 UTC, liquid36 approved these changes

2021-04-26 17:26 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3857](http://condorpiedra.andes.gob.ar:85/3857/mochawesome.html)
CYPRESS RUN: [2919](https://dashboard.cypress.io/projects/xr7gft/runs/2919/specs)
TEST START: 2021-04-26T17:26:16.040Z
TOTAL: 367
SUCCESS: 360
FAIL: 7
SKIPPED: 0

2021-04-26 17:37 UTC, liquid36 requested changes

2021-04-26 17:37 UTC, liquid36 commented on src/app/shared/components/upload-file.component.ts
> +        this.extensionesAceptadas = this.extensiones.map(ext => '.' + ext);
Fijate que a veces extesiones puede ser null y por eso estan fallando los test del COM.

2021-04-27 12:15 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3864](http://condorpiedra.andes.gob.ar:85/3864/mochawesome.html)
CYPRESS RUN: [2925](https://dashboard.cypress.io/projects/xr7gft/runs/2925/specs)
TEST START: 2021-04-27T12:15:06.130Z
TOTAL: 275
SUCCESS: 264
FAIL: 11
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-04-27 15:13 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3868](http://condorpiedra.andes.gob.ar:85/3868/mochawesome.html)
CYPRESS RUN: [2929](https://dashboard.cypress.io/projects/xr7gft/runs/2929/specs)
TEST START: 2021-04-27T15:13:34.183Z
TOTAL: 367
SUCCESS: 367
FAIL: 0
SKIPPED: 0

2021-05-03 11:52 UTC, MCele approved these changes

2021-05-03 12:32 UTC, palita1991 approved these changes

2021-05-04 12:39 UTC, liquid36 approved these changes

2021-05-04 12:46 UTC, merged