feat(login): se implementa v0.1
andes/app pull request #2238
Opened 2021-04-23 17:40 UTC by andrrrl

### Requerimiento
https://proyectos.andes.gob.ar/browse/PDP-50
 

### Funcionalidad desarrollada 

1. Se siguió el diseño desarrollado por @AgosLizzi para el login del portal
2. Hay aspectos visuales por resolver desde Plex (redondeado de inputs/botones)
3. No tiene funcionamiento, sólo el login que ya estaba funcionando.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-04-27 12:11 UTC, waltergarrido reviewed
existe la posibilidad de que el contenido de la etiqueta svg se llame desde alguna clase ? para tener el código un poco mas ordenado .

2021-04-28 16:16 UTC, palita1991 approved these changes

2021-05-06 16:28 UTC, negro89 reviewed
Excelente! El único detalle que noté es que el email del usuario no se ve por completo y quizas resulta un poco incómodo al momento de llenar el campo.
![image](https://user-images.githubusercontent.com/37875706/117332898-c1715e00-ae6e-11eb-9cbd-4503936b804b.png)

2021-05-06 16:28 UTC, negro89 commented on projects/portal/src/app/pages/login/login-portal-paciente.component.html
> +        <main justify="center">
Todo este bloque tiene un par de tabulaciones de más.

2021-05-19 16:56 UTC, condorpiedra commented
Hay codigo duplicado en la parte del svg

2021-05-19 16:57 UTC, condorpiedra requested changes
Reevisar código duplicado

2021-05-20 12:48 UTC, andrrrl commented
> Hay codigo duplicado en la parte del svg

Decías por el fill de los paths? en general es aceptable en SVGs, porque hacen que funcionen sin depender de una hoja de estilos. Igualmente lo que hice es crear un componente para que sea reusable. Gracias!!

2021-05-20 16:57 UTC, condorpiedra commented
> Excelente! El único detalle que noté es que el email del usuario no se ve por completo y quizas resulta un poco incómodo al momento de llenar el campo.
> ![image](https://user-images.githubusercontent.com/37875706/117332898-c1715e00-ae6e-11eb-9cbd-4503936b804b.png)

Sólo quedó esta revisión pendiente

2021-05-21 12:28 UTC, waltergarrido approved these changes

2021-05-27 16:30 UTC, andrrrl commented
> Reevisar código duplicado

re-review @condorpiedra VANESA

2021-05-27 17:26 UTC, liquid36 commented on projects/portal/src/app/pages/login/login-portal-paciente.component.html
> +        <pdp-logo></pdp-logo>
Porque no usan un assets, que de hecho lo están agregando en este PR?

2021-05-28 15:01 UTC, andrrrl commented on projects/portal/src/app/pages/login/login-portal-paciente.component.html
> +        <pdp-logo></pdp-logo>
Es como tenemos el logo de Andes, se puede usar uno u otro según se necesite. La única diferencia es que hice un componente normal, podría hacer que sea un selector como el logo de Andes (ver adjunto). 
![image](https://user-images.githubusercontent.com/11394455/120003690-5e29a600-bfac-11eb-94bd-3fba2405b319.png)

2021-05-31 11:30 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4211](http://condorpiedra.andes.gob.ar:85/4211/mochawesome.html)
CYPRESS RUN: [3238](https://dashboard.cypress.io/projects/xr7gft/runs/3238/specs)
TEST START: 2021-05-31T11:30:26.272Z
TOTAL: 395
SUCCESS: 395
FAIL: 0
SKIPPED: 0

2021-06-08 13:44 UTC, condorpiedra approved these changes

2021-06-08 13:47 UTC, merged