refactor(RUP): botón agregar paciente visible
andes/app pull request #2242
Opened 2021-04-27 16:08 UTC by palita1991

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-110

### Funcionalidad desarrollada 

1. Se acomoda código para que quedara fijo el plex-title al hacer scroll
2. Se cambia legend por plex-title en el componente que busca al paciente para agenda dinámica en sidebar

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2021-04-27 16:22 UTC, liquid36 requested changes

2021-04-27 16:22 UTC, liquid36 commented on src/app/modules/rup/components/ejecucion/puntoInicio.html
> +                <plex-button *ngIf="agendaSeleccionada.dinamica && !esFutura(agendaSeleccionada) && ((agendaSeleccionada.cupo && agendaSeleccionada.cupo > 0) || agendaSeleccionada.cupo < 0)"
Apenas entro a RUP me da error en esta linea de código porque agendaSeleccionada es null:

![image](https://user-images.githubusercontent.com/3813270/116277161-96468a80-a75b-11eb-9cb8-eeea7a24c26f.png)

2021-04-27 17:05 UTC, palita1991 commented on src/app/modules/rup/components/ejecucion/puntoInicio.html
> +                <plex-button *ngIf="agendaSeleccionada.dinamica && !esFutura(agendaSeleccionada) && ((agendaSeleccionada.cupo && agendaSeleccionada.cupo > 0) || agendaSeleccionada.cupo < 0)"
@liquid36 corregido

2021-04-27 17:17 UTC, liquid36 commented
USUARIO: mpalavecino  
BUILD NUMBER: [3874](http://condorpiedra.andes.gob.ar:85/3874/mochawesome.html)
CYPRESS RUN: [2934](https://dashboard.cypress.io/projects/xr7gft/runs/2934/specs)
TEST START: 2021-04-27T17:17:17.585Z
TOTAL: 333
SUCCESS: 322
FAIL: 11
SKIPPED: 0

2021-04-27 17:26 UTC, liquid36 commented
USUARIO: mpalavecino  
BUILD NUMBER: [3875](http://condorpiedra.andes.gob.ar:85/3875/mochawesome.html)
CYPRESS RUN: [2935](https://dashboard.cypress.io/projects/xr7gft/runs/2935/specs)
TEST START: 2021-04-27T17:26:09.074Z
TOTAL: 367
SUCCESS: 367
FAIL: 0
SKIPPED: 0

2021-04-28 15:08 UTC, negro89 approved these changes

2021-04-29 15:44 UTC, kroce approved these changes

2021-04-29 17:06 UTC, liquid36 approved these changes

2021-04-29 17:18 UTC, merged