VAC: permitir cambiar el grupo de inscripciones
andes/app pull request #2249
Opened 2021-04-28 19:28 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-50

### Funcionalidad desarrollada 
1. Permite cambiar de grupo en cualquier caso al editar inscripción

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-04-29 19:42 UTC, juuliotero commented
> * Cuando se selecciona el primer grupo de la lista al que se va a cambiar, la localidad desaparece
> * Cuando se selecciona a un inscripto del grupo "Personal de Salud" los select en el sidebar quedan cortados
> 
> ![image](https://user-images.githubusercontent.com/19696043/116576446-f23d1a80-a8e5-11eb-9dc8-7e43e8804636.png)

Corregido el problema de localidad al seleccionar personal-salud. Se arregla también en el formulario de inscripción. 
Lo del texto en el plex-radio se tiene que arreglar desde plex por lo que dice @andrrrl

2021-04-29 20:28 UTC, negro89 requested changes
Al editar un paciente mayor de 60 con factores de riesgo, el select del grupo queda en 'undefined' ya que el anteriormente asignado ahora no pertenece al array de grupos posibles. Adjunto captura:
![image](https://user-images.githubusercontent.com/37875706/116614264-17468300-a910-11eb-9932-40afcd0a36e3.png)

2021-04-30 12:51 UTC, juuliotero commented
> Al editar un paciente mayor de 60 con factores de riesgo, el select del grupo queda en 'undefined' ya que el anteriormente asignado ahora no pertenece al array de grupos posibles. Adjunto captura:
> ![image](https://user-images.githubusercontent.com/37875706/116614264-17468300-a910-11eb-9932-40afcd0a36e3.png)

Ahora, si se da un caso de una persona que está en un grupo y por edad no debería permitirlo, al editar va a aparecer el grupo como vacío para que seleccione uno dentro de los habilitados.
![image](https://user-images.githubusercontent.com/7090371/116697428-8fa55680-a999-11eb-86f2-c937e695a433.png)

2021-04-30 16:52 UTC, negro89 requested changes
Solucionado lo anterior, pero esta vez figura un undefined al final de la lista de grupos posibles (Mismo caso).

![image](https://user-images.githubusercontent.com/37875706/116727662-3a7a3c80-a9bb-11eb-8d9d-cbf05368c5cf.png)

2021-04-30 17:52 UTC, juuliotero commented
> Solucionado lo anterior, pero esta vez figura un undefined al final de la lista de grupos posibles (Mismo caso).
> 
> ![image](https://user-images.githubusercontent.com/37875706/116727662-3a7a3c80-a9bb-11eb-8d9d-cbf05368c5cf.png)

corregido

2021-04-30 18:08 UTC, kroce approved these changes

2021-04-30 18:11 UTC, condorpiedra approved these changes

2021-04-30 18:12 UTC, merged