VAC: poder elegir notas predefinidas o escribir una personalizada
andes/app pull request #2250
Opened 2021-04-29 13:57 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-52

### Funcionalidad desarrollada 
1. Poder elegir entra notas predefinidas o ingresar una personalizada
2. No permitir ingresar notas vacías

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-04-29 20:34 UTC, negro89 commented
Consulta: Se contempló el caso de querer borrar una nota hecha por error? Por seleccionar al paciente equivocado, por ejemplo.

2021-04-30 12:09 UTC, juuliotero commented
> Consulta: Se contempló el caso de querer borrar una nota hecha por error? Por seleccionar al paciente equivocado, por ejemplo.

Se carga una tarea para el borrado de notas https://proyectos.andes.gob.ar/browse/VAC-61

2021-04-30 14:38 UTC, negro89 approved these changes

2021-05-03 11:20 UTC, JSantarelli requested changes

2021-05-03 11:20 UTC, JSantarelli commented on src/app/apps/vacunacion/components/listado-inscriptos.html
> +                        <plex-text label="Ingrese nota" *ngIf="notaPredefinida?.id==='otra'"
Por la función que cumple, a este input lo haría multilínea. `multiline="true"`.
![andes-vac-nota-otra](https://user-images.githubusercontent.com/5895886/116870199-71816580-abe8-11eb-874c-c85074742fdf.PNG)

2021-05-03 12:04 UTC, juuliotero commented on src/app/apps/vacunacion/components/listado-inscriptos.html
> +                        <plex-text label="Ingrese nota" *ngIf="notaPredefinida?.id==='otra'"
Corregido

2021-05-03 12:26 UTC, palita1991 approved these changes

2021-05-03 15:25 UTC, AgosLizzi reviewed
Cuando elijo la opción de "modificar nota" directamente me elimina la "Nota actual" y me crea una nueva según la opcion que elija del listado. Debería existir una alternativa para realmente **editar** esa "Nota actual" y en el caso que sea necesario crear una nueva.

2021-05-03 17:47 UTC, kroce approved these changes

2021-05-03 17:55 UTC, JSantarelli approved these changes

2021-05-03 18:00 UTC, andrrrl commented
> Cuando elijo la opción de "modificar nota" directamente me elimina la "Nota actual" y me crea una nueva según la opcion que elija del listado. Debería existir una alternativa para realmente **editar** esa "Nota actual" y en el caso que sea necesario crear una nueva.

Me sumo a este pedido!

2021-05-03 18:12 UTC, kroce commented
> Cuando elijo la opción de "modificar nota" directamente me elimina la "Nota actual" y me crea una nueva según la opcion que elija del listado. Debería existir una alternativa para realmente **editar** esa "Nota actual" y en el caso que sea necesario crear una nueva.

@AgosLizzi por el momento no estaba planteado de esa manera, por ahora se utiliza como medio rapido para registrar si ocurrió algo en el momento que llaman al paciente inscripto. Esas notas no van a tener demasiada ida y vuelta.

2021-05-03 18:23 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [3905](http://condorpiedra.andes.gob.ar:85/3905/mochawesome.html)
CYPRESS RUN: [2961](https://dashboard.cypress.io/projects/xr7gft/runs/2961/specs)
TEST START: 2021-05-03T18:22:57.241Z
TOTAL: 349
SUCCESS: 348
FAIL: 1
SKIPPED: 0

2021-05-03 18:36 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [3906](http://condorpiedra.andes.gob.ar:85/3906/mochawesome.html)
CYPRESS RUN: [2962](https://dashboard.cypress.io/projects/xr7gft/runs/2962/specs)
TEST START: 2021-05-03T18:34:53.207Z
TOTAL: 19
SUCCESS: 19
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-05-03 18:37 UTC, merged