BUSCADOR-EPIDEMIO: Historial de fichas
andes/app pull request #2251
Opened 2021-04-29 17:29 UTC by martinebucarey

### Requerimiento
https://proyectos.andes.gob.ar/browse/EP-42

### Funcionalidad desarrollada 

1. Se agrega el componente _historial-ficha_ para visualizar el historial de cada ficha dentro del buscador de fichas epidemiológicas.
2. Se agrega icono en el buscador de fichas que permite visualizar el historial de una ficha en caso de tener el permiso correspondiente.
3. Al guardar o actualizar una ficha, se guarda un registro en una nueva colección _formsEpidemiologiaHistory_

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [x] Si Agregar en el sumodulo "buscador fichas" que esta dentro del modulo "Epidemiología" el permiso " "epidemiologia:historial:?"
- [ ] No

### Requiere actualizaciones en la API

- [x] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2021-04-29 17:43 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3894](http://condorpiedra.andes.gob.ar:85/3894/mochawesome.html)
CYPRESS RUN: [2952](https://dashboard.cypress.io/projects/xr7gft/runs/2952/specs)
TEST START: 2021-04-29T17:43:13.117Z
TOTAL: 367
SUCCESS: 367
FAIL: 0
SKIPPED: 0

2021-04-29 18:44 UTC, sychus approved these changes
Excelente tincho!!!

2021-04-30 16:10 UTC, negro89 requested changes
CombineLatest en desuso

https://github.com/andes/app/blob/8d063d12dcc1cda1bd8aefb612bb8d34b727cef2/src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts#L6

2021-04-30 16:10 UTC, negro89 commented on src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
> +          this.serviceHistory.save({ ficha: res }).subscribe();
Estas suscripciones anidadas pueden evitarse con el uso de operadores rxjs

2021-04-30 16:10 UTC, negro89 commented on src/app/modules/epidemiologia/components/historial-ficha/historial-ficha.component.ts
> +  ngOnInit(): void { }
Es necesario?

2021-05-04 13:51 UTC, martinebucarey commented on src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
> +                    <plex-button *ngIf="puedeVerHistorial" type="info" icon="history" size="sm"
Buena observacion, agregados

2021-05-04 13:51 UTC, martinebucarey commented on src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
> +          this.serviceHistory.save({ ficha: res }).subscribe();
Modificado

2021-05-04 14:13 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3912](http://condorpiedra.andes.gob.ar:85/3912/mochawesome.html)
CYPRESS RUN: [2968](https://dashboard.cypress.io/projects/xr7gft/runs/2968/specs)
TEST START: 2021-05-04T14:13:09.163Z
TOTAL: 367
SUCCESS: 367
FAIL: 0
SKIPPED: 0

2021-05-05 14:04 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3948](http://condorpiedra.andes.gob.ar:85/3948/mochawesome.html)
CYPRESS RUN: [2995](https://dashboard.cypress.io/projects/xr7gft/runs/2995/specs)
TEST START: 2021-05-05T14:03:57.746Z
TOTAL: 367
SUCCESS: 367
FAIL: 0
SKIPPED: 0

2021-05-06 11:50 UTC, closed without merging