VAC: monitoreo de inscriptos y gestión de turnos
andes/app pull request #2252
Opened 2021-05-03 14:26 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-58
https://proyectos.andes.gob.ar/browse/VAC-59

### Funcionalidad desarrollada 
1.Nueva pantalla para monitoreo de inscripciones y gestionar turnos 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [X] Si
- [ ] No

Reemplazar en la colección _modulos_ el llamado Vacunación COVID-19 por:

{
    "nombre" : "Vacunación COVID-19",
    "descripcion" : "Campaña de vacunación",
    "subtitulo" : "Campaña de vacunación",
    "linkAcceso" : "/vacunacion/listado",
    "color" : "#A74482",
    "icono" : null,
    "permisos" : [ 
        "vacunacion:?"
    ],
    "activo" : true,
    "orden" : 5,
    "submodulos" : [ 
        {
            "activo" : true,
            "permisos" : [ 
                "vacunacion:?"
            ],
            "nombre" : "Listado",
            "linkAcceso" : "/vacunacion/listado",
            "color" : "#413839",
            "icono" : "file-tree",
            "orden" : 1
        }, 
        {
            "activo" : true,
            "permisos" : [ 
                "vacunacion:dacion-turnos"
            ],
            "nombre" : "Dación de turnos",
            "linkAcceso" : "/vacunacion/monitoreo",
            "color" : "#6D6968",
            "icono" : "documento-paciente",
            "orden" : 2
        }
    ]
}

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1370
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-05-04 12:45 UTC, palita1991 reviewed
@juuliotero consultas:
1) En la parte de las notas, va a salir el combo para personalizar como en listado de inscriptos?
![image](https://user-images.githubusercontent.com/30004190/117004733-c7bfd880-acbc-11eb-8eb7-c284809e7469.png)

2) Al seleccionar un paciente, mientras tenga el sidebar abierto, puedo asignarle un turno, y despues otro, etc. Se van pisando las fechas en la base de datos, a pesar de que sale el toast al momento de asignar el turno, estaria bueno que si ya se le asigno uno y se mantiene el sidebar abierto y se asigna otro turno que se visualice como una modificación del que ya le asignaron

2021-05-04 14:42 UTC, kroce requested changes
Al cambiar de grupo debería cerrar el sidebar y limpiar el listado

2021-05-04 14:52 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [3915](http://condorpiedra.andes.gob.ar:85/3915/mochawesome.html)
CYPRESS RUN: [2971](https://dashboard.cypress.io/projects/xr7gft/runs/2971/specs)
TEST START: 2021-05-04T14:52:25.724Z
TOTAL: 367
SUCCESS: 367
FAIL: 0
SKIPPED: 0

2021-05-04 16:07 UTC, juuliotero commented
> @juuliotero consultas:
> 
> 1. En la parte de las notas, va a salir el combo para personalizar como en listado de inscriptos?
>    ![image](https://user-images.githubusercontent.com/30004190/117004733-c7bfd880-acbc-11eb-8eb7-c284809e7469.png)
> 2. Al seleccionar un paciente, mientras tenga el sidebar abierto, puedo asignarle un turno, y despues otro, etc. Se van pisando las fechas en la base de datos, a pesar de que sale el toast al momento de asignar el turno, estaria bueno que si ya se le asigno uno y se mantiene el sidebar abierto y se asigna otro turno que se visualice como una modificación del que ya le asignaron

Corregido

2021-05-04 16:07 UTC, juuliotero commented
@AgosLizzi se hace el cambio de las notas en este PR

2021-05-05 16:28 UTC, negro89 requested changes
1. Si se agrega una nota y luego se vuelve a clickear en el paciente, al recargar el sidebar la nota no aparece (Refrescar el listado).
2. Se que no es mi campo pero al clickear en 'editar inscripción' o 'dar turno' aparecen los botones aceptar y cancelar alineados con el título. En cambio, esto no sucede al agregar una nota.

2021-05-05 16:28 UTC, negro89 commented on src/app/apps/vacunacion/components/gestion-turnos/dacion-turno.component.ts
> +import { Component, Input, Output, EventEmitter, OnInit } from '@angular/core';
onInit sin usar

2021-05-05 16:28 UTC, negro89 commented on src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.ts
> +import { Observable, empty } from 'rxjs';
empty

2021-05-05 16:28 UTC, negro89 commented on src/app/apps/vacunacion/components/notas.component.ts
> +import { Component, Input, Output, EventEmitter, OnInit } from '@angular/core';
OnInit

2021-05-07 15:56 UTC, juuliotero commented on src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.ts
> +import { Observable, empty } from 'rxjs';
listo

2021-05-07 15:56 UTC, juuliotero commented on src/app/apps/vacunacion/components/notas.component.ts
> +import { Component, Input, Output, EventEmitter, OnInit } from '@angular/core';
listo

2021-05-07 15:56 UTC, juuliotero commented
> 1. Si se agrega una nota y luego se vuelve a clickear en el paciente, al recargar el sidebar la nota no aparece (Refrescar el listado).
> 2. Se que no es mi campo pero al clickear en 'editar inscripción' o 'dar turno' aparecen los botones aceptar y cancelar alineados con el título. En cambio, esto no sucede al agregar una nota.

se aplican cambios

2021-05-11 18:35 UTC, condorpiedra approved these changes

2021-05-12 15:00 UTC, kroce approved these changes

2021-05-12 15:11 UTC, merged