VAC - Nuevo estado 'fallecido' editando inscripción
andes/app pull request #2255
Opened 2021-05-04 13:26 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-63

### Funcionalidad desarrollada 

1. Poder editar el estado a 'fallecido'.
2. A un inscripto en estado fallecido solo se le puede editar el estado.

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-05-04 14:00 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3911](http://condorpiedra.andes.gob.ar:85/3911/mochawesome.html)
CYPRESS RUN: [2967](https://dashboard.cypress.io/projects/xr7gft/runs/2967/specs)
TEST START: 2021-05-04T14:00:19.601Z
TOTAL: 367
SUCCESS: 367
FAIL: 0
SKIPPED: 0

2021-05-05 12:13 UTC, palita1991 requested changes
@negro89 como para seguir la linea del diseño de los datos de inscripción, estaría bueno también poner el badge en ese sector cuando el paciente esta fallecido, como por ejemplo cuando está habilitado:
![image](https://user-images.githubusercontent.com/30004190/117138782-dfad6000-ad81-11eb-9a4c-c0170b68825a.png)

Datos de inscripcion - paciente fallecido
![image](https://user-images.githubusercontent.com/30004190/117138168-04ed9e80-ad81-11eb-9e4b-edaef8ba5176.png)

2021-05-05 15:30 UTC, AgosLizzi requested changes
Me sumo al pedido de @palita1991 para que aparezca el badge de "fallecido" sobre la slidebar...
Por otro lado, al editar los datos de un paciente **con factor de riesgo**, solo en algunos casos aparece un listado para agregar dichos factores. Adjunto imagen de referencia 
![listado-01](https://user-images.githubusercontent.com/72876985/117167316-86ebc080-ad9d-11eb-9462-49e633a7323d.jpg)
![listado-02](https://user-images.githubusercontent.com/72876985/117167328-881ced80-ad9d-11eb-8aa1-4a171c5c414c.jpg)

2021-05-05 15:45 UTC, AgosLizzi commented
Siguiendo con los paciente con factores de riesgos... cuando quiero editar para subir los factores no me deja guardar los cambios. Adjunto videito asi se ve mejor!

https://user-images.githubusercontent.com/72876985/117169430-789ea400-ad9f-11eb-803d-884c193816ed.mp4

2021-05-06 14:33 UTC, negro89 commented
@palita1991 @AgosLizzi chicos:
1. Badge en fallecidos: Este badge va a figurar en el detalle del paciente una vez que renaper actualice su estado (Así funciona actualmente) por lo tanto no habría necesidad de agregarlo en los detalles de la inscripción.
2. El listado de factores de riesgo aparece solo en el grupo de mayores entre 18 y 59 años. Esto estaría ok.
3. Lo del botón 'guardar' deshabilitado es un bug. Ahi agregué un commit más y un pr en api para que revisen si pueden reproducirlo.

Gracias!

2021-05-06 14:49 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3983](http://condorpiedra.andes.gob.ar:85/3983/mochawesome.html)
CYPRESS RUN: [3030](https://dashboard.cypress.io/projects/xr7gft/runs/3030/specs)
TEST START: 2021-05-06T14:49:40.979Z
TOTAL: 367
SUCCESS: 365
FAIL: 2
SKIPPED: 0

2021-05-06 15:41 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3988](http://condorpiedra.andes.gob.ar:85/3988/mochawesome.html)
CYPRESS RUN: [3034](https://dashboard.cypress.io/projects/xr7gft/runs/3034/specs)
TEST START: 2021-05-06T15:32:22.210Z
TOTAL: 367
SUCCESS: 362
FAIL: 5
SKIPPED: 0

2021-05-06 16:47 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3990](http://condorpiedra.andes.gob.ar:85/3990/mochawesome.html)
CYPRESS RUN: [3036](https://dashboard.cypress.io/projects/xr7gft/runs/3036/specs)
TEST START: 2021-05-06T16:47:08.548Z
TOTAL: 330
SUCCESS: 319
FAIL: 11
SKIPPED: 0

2021-05-06 17:07 UTC, palita1991 approved these changes

2021-05-06 17:30 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3992](http://condorpiedra.andes.gob.ar:85/3992/mochawesome.html)
CYPRESS RUN: [3038](https://dashboard.cypress.io/projects/xr7gft/runs/3038/specs)
TEST START: 2021-05-06T17:26:00.900Z
TOTAL: 335
SUCCESS: 323
FAIL: 12
SKIPPED: 0

2021-05-12 17:26 UTC, kroce requested changes
Hay un detalle al editar un paciente y ponerle el estado fallecido. Cuando vuelvo a editarlo los items de los radios no se ven (quedan en negro)
![image](https://user-images.githubusercontent.com/18030170/118018276-f6c5f200-b32d-11eb-9810-237cdaf0344a.png)

2021-05-12 17:55 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4038](http://condorpiedra.andes.gob.ar:85/4038/mochawesome.html)
CYPRESS RUN: [3076](https://dashboard.cypress.io/projects/xr7gft/runs/3076/specs)
TEST START: 2021-05-12T17:55:09.894Z
TOTAL: 385
SUCCESS: 381
FAIL: 4
SKIPPED: 0

2021-05-12 18:54 UTC, juuliotero commented
> Hay un detalle al editar un paciente y ponerle el estado fallecido. Cuando vuelvo a editarlo los items de los radios no se ven (quedan en negro)
> ![image](https://user-images.githubusercontent.com/18030170/118018276-f6c5f200-b32d-11eb-9810-237cdaf0344a.png)

se ocultan los campos de edición cuando se selecciona el estado 'fallecido', o es el estado actual de la inscripción

2021-05-13 12:01 UTC, kroce approved these changes

2021-05-13 12:34 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4047](http://condorpiedra.andes.gob.ar:85/4047/mochawesome.html)
CYPRESS RUN: [3084](https://dashboard.cypress.io/projects/xr7gft/runs/3084/specs)
TEST START: 2021-05-13T12:34:10.709Z
TOTAL: 385
SUCCESS: 384
FAIL: 1
SKIPPED: 0

2021-05-13 12:34 UTC, merged