VAC: en la columna certificado deberá decir "No corresponde" si es factores-riesgo y tiene entre 57 y 59 años
andes/app pull request #2267
Opened 2021-05-11 14:25 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-68

### Funcionalidad desarrollada 
1. En la columna certificado si es de factores-riesgo y tiene entre 57 y 59 años mostrar 'No corresponde'

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1382
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [x] Si - https://github.com/andes/andes-test-integracion/pull/356
- [ ] No

2021-05-12 12:00 UTC, andrrrl requested changes
La columna de **Certificado** se pierde (queda solapada por scroll horizontal). Sería mejor que mainSize sea 9 en lugar de 8 sólo para ese caso.

2021-05-13 12:34 UTC, juuliotero commented
> Al seleccionar un paciente de la lista, la columna de **Certificado** se pierde (queda solapada por scroll horizontal). Sería mejor que mainSize sea 9 en lugar de 8 sólo para ese caso. También habría que ver de poner ese dato junto a los demás datos en el sidebar.

listo

2021-05-13 15:21 UTC, andrrrl approved these changes

2021-05-19 16:55 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [4099](http://condorpiedra.andes.gob.ar:85/4099/mochawesome.html)
CYPRESS RUN: [3135](https://dashboard.cypress.io/projects/xr7gft/runs/3135/specs)
TEST START: 2021-05-19T16:54:53.572Z
TOTAL: 392
SUCCESS: 391
FAIL: 1
SKIPPED: 0

2021-05-19 17:11 UTC, kroce approved these changes

2021-05-19 17:25 UTC, palita1991 approved these changes

2021-05-19 17:44 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4102](http://condorpiedra.andes.gob.ar:85/4102/mochawesome.html)
CYPRESS RUN: [3138](https://dashboard.cypress.io/projects/xr7gft/runs/3138/specs)
TEST START: 2021-05-19T17:43:55.813Z
TOTAL: 393
SUCCESS: 392
FAIL: 1
SKIPPED: 0

2021-05-19 17:50 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4103](http://condorpiedra.andes.gob.ar:85/4103/mochawesome.html)
CYPRESS RUN: [3139](https://dashboard.cypress.io/projects/xr7gft/runs/3139/specs)
TEST START: 2021-05-19T17:48:47.868Z
TOTAL: 18
SUCCESS: 17
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-05-19 18:51 UTC, liquid36 commented
USUARIO: mpalavecino  
BUILD NUMBER: [4106](http://condorpiedra.andes.gob.ar:85/4106/mochawesome.html)
CYPRESS RUN: [3142](https://dashboard.cypress.io/projects/xr7gft/runs/3142/specs)
TEST START: 2021-05-19T18:51:16.756Z
TOTAL: 393
SUCCESS: 393
FAIL: 0
SKIPPED: 0

2021-05-20 11:12 UTC, merged