INT - Fix edición de egreso en internación validada
andes/app pull request #2269
Opened 2021-05-12 15:37 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-269

### Funcionalidad desarrollada 

1. Agrega propiedad readonly en campos de egreso cuando la internación ya fue validada

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-05-12 16:11 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4033](http://condorpiedra.andes.gob.ar:85/4033/mochawesome.html)
CYPRESS RUN: [3071](https://dashboard.cypress.io/projects/xr7gft/runs/3071/specs)
TEST START: 2021-05-12T16:11:11.404Z
TOTAL: 385
SUCCESS: 377
FAIL: 8
SKIPPED: 0

2021-05-12 16:21 UTC, liquid36 commented
Recordar que habiamos hablado de mostrar la componente <app-informe-egreso> cuando se puede editar. En la US se la linea de código donde se usa.

2021-05-13 18:29 UTC, palita1991 approved these changes

2021-05-14 18:31 UTC, juuliotero requested changes
Me pasa algo raro con los datos, como que tardan en cargar. Pero fuera de eso, cuando guardo cambios para un egreso, me deshabilita el tilde y si cambio de internación me lo deja deshabilitado. Sumo video.

https://www.loom.com/share/2faed09ae3fe435eb304bb0c027ffc0d

2021-05-14 20:35 UTC, negro89 commented
@juuliotero si, probaste el pr justo cuando estaba haciendo cambios. De todas formas hay una query que está demorando mucho, habría que investigar bien.

@liquid36 ya estan corregidos los cambios.

2021-05-17 12:37 UTC, liquid36 approved these changes

2021-05-17 12:53 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4074](http://condorpiedra.andes.gob.ar:85/4074/mochawesome.html)
CYPRESS RUN: [3110](https://dashboard.cypress.io/projects/xr7gft/runs/3110/specs)
TEST START: 2021-05-17T12:49:17.726Z
TOTAL: 306
SUCCESS: 279
FAIL: 27
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-05-17 13:19 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4076](http://condorpiedra.andes.gob.ar:85/4076/mochawesome.html)
CYPRESS RUN: [3112](https://dashboard.cypress.io/projects/xr7gft/runs/3112/specs)
TEST START: 2021-05-17T13:19:07.241Z
TOTAL: 313
SUCCESS: 294
FAIL: 19
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-05-17 13:54 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4079](http://condorpiedra.andes.gob.ar:85/4079/mochawesome.html)
CYPRESS RUN: [3115](https://dashboard.cypress.io/projects/xr7gft/runs/3115/specs)
TEST START: 2021-05-17T13:54:38.344Z
TOTAL: 388
SUCCESS: 375
FAIL: 13
SKIPPED: 0

2021-05-17 14:39 UTC, liquid36 commented
Revisar que fallan unos test de internación

2021-05-18 14:41 UTC, palita1991 approved these changes

2021-05-19 13:58 UTC, plammel approved these changes

2021-05-20 17:56 UTC, waltergarrido approved these changes

2021-05-21 17:11 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4148](http://condorpiedra.andes.gob.ar:85/4148/mochawesome.html)
CYPRESS RUN: [3183](https://dashboard.cypress.io/projects/xr7gft/runs/3183/specs)
TEST START: 2021-05-21T17:01:35.762Z
TOTAL: 291
SUCCESS: 275
FAIL: 16
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-05-21 17:54 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4156](http://condorpiedra.andes.gob.ar:85/4156/mochawesome.html)
CYPRESS RUN: [3190](https://dashboard.cypress.io/projects/xr7gft/runs/3190/specs)
TEST START: 2021-05-21T17:54:00.481Z
TOTAL: 393
SUCCESS: 393
FAIL: 0
SKIPPED: 0

2021-05-27 16:38 UTC, merged