Se actualiza layout de selección de Organización
andes/app pull request #2271
Opened 2021-05-12 19:04 UTC by andrrrl

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/MISC-158

### Funcionalidad desarrollada 

1. Se oculta navbar en pantalla de selección de Organización/Efector
2. Se usa plex-title en su lugar

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-05-13 11:49 UTC, liquid36 requested changes

2021-05-13 11:49 UTC, liquid36 commented on src/app/app.component.ts
> +        this.plex.navVisible(false);
Esto debería ir en la componente de seleccionar organización. Sino al actualizar el navegador cuando estas logeado desaparece el navbar.

2021-05-13 12:04 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4044](http://condorpiedra.andes.gob.ar:85/4044/mochawesome.html)
CYPRESS RUN: [3081](https://dashboard.cypress.io/projects/xr7gft/runs/3081/specs)
TEST START: 2021-05-13T12:03:58.402Z
TOTAL: 385
SUCCESS: 384
FAIL: 1
SKIPPED: 0

2021-05-13 12:10 UTC, juuliotero requested changes

2021-05-13 12:10 UTC, juuliotero commented on src/app/app.component.ts
> +        this.plex.navVisible(false);
Adhiero a esto

2021-05-13 18:51 UTC, andrrrl commented on src/app/app.component.ts
> +        this.plex.navVisible(false);
Veo de arreglar eso, en principio lo puse ahí porque en select-organizacion me tiraba error de ExpressionChnagedAfterNoSeQué, gracias!

2021-05-14 11:50 UTC, juuliotero approved these changes

2021-05-14 11:50 UTC, juuliotero commented on src/app/app.component.ts
> +
Este archivo solo sumó una linea en blanco. Fuera de eso, funciona todo bien!

2021-05-14 14:03 UTC, liquid36 approved these changes

2021-05-14 14:26 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4064](http://condorpiedra.andes.gob.ar:85/4064/mochawesome.html)
CYPRESS RUN: [3100](https://dashboard.cypress.io/projects/xr7gft/runs/3100/specs)
TEST START: 2021-05-14T14:26:14.097Z
TOTAL: 388
SUCCESS: 388
FAIL: 0
SKIPPED: 0

2021-05-17 17:41 UTC, merged