INT - Carga datos de internación anterior en nuevo ingreso
andes/app pull request #2272
Opened 2021-05-13 14:17 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-278

### Funcionalidad desarrollada 

1. Busca registros de ingresos anteriores y pre-setea combos de datos estadísticos

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-05-13 15:22 UTC, liquid36 requested changes
Hay dos temas:
1. Si estoy editando el ingreso, me vuelve a buscar valores y pisa lo que ya tenía almacenado.
2. Si no tiene ningún registro previo se pincha todo, faltan controles.

2021-05-14 14:08 UTC, negro89 commented
@liquid36 corregido!

2021-05-14 14:55 UTC, liquid36 commented on src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
> +                ingreso = ingreso.sort((a, b) => b.fecha.getTime() - a.fecha.getTime());
Agregue un ajuste porque los registros no venían ordenado. A la tercera internación agarraba cualquier valor y no el último

2021-05-14 14:56 UTC, liquid36 commented on src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
> +            // Pre-carga datos de una internación anterior si existe
Para la proxima, lo que se suele comentar es la función, no donde se llama.
 
```
/**
 * Pre-carga datos de una internación anterior si existe
 */
cargarUltimaInternacion(paciente: IPaciente) {
   ...
}
```

2021-05-14 14:57 UTC, liquid36 approved these changes

2021-05-14 15:09 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4066](http://condorpiedra.andes.gob.ar:85/4066/mochawesome.html)
CYPRESS RUN: [3102](https://dashboard.cypress.io/projects/xr7gft/runs/3102/specs)
TEST START: 2021-05-14T15:09:15.639Z
TOTAL: 388
SUCCESS: 382
FAIL: 6
SKIPPED: 0

2021-05-17 12:39 UTC, negro89 commented on src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
> +                ingreso = ingreso.sort((a, b) => b.fecha.getTime() - a.fecha.getTime());
Buenisimo marian, no me percaté de esto.

2021-05-17 13:05 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4075](http://condorpiedra.andes.gob.ar:85/4075/mochawesome.html)
CYPRESS RUN: [3111](https://dashboard.cypress.io/projects/xr7gft/runs/3111/specs)
TEST START: 2021-05-17T13:05:46.791Z
TOTAL: 336
SUCCESS: 334
FAIL: 2
SKIPPED: 0

2021-05-17 13:29 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4077](http://condorpiedra.andes.gob.ar:85/4077/mochawesome.html)
CYPRESS RUN: [3113](https://dashboard.cypress.io/projects/xr7gft/runs/3113/specs)
TEST START: 2021-05-17T13:29:14.284Z
TOTAL: 388
SUCCESS: 382
FAIL: 6
SKIPPED: 0

2021-05-17 13:38 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4078](http://condorpiedra.andes.gob.ar:85/4078/mochawesome.html)
CYPRESS RUN: [3114](https://dashboard.cypress.io/projects/xr7gft/runs/3114/specs)
TEST START: 2021-05-17T13:38:32.887Z
TOTAL: 388
SUCCESS: 388
FAIL: 0
SKIPPED: 0

2021-05-17 17:35 UTC, merged