VAC: ver mis inscripciones asignadas
andes/app pull request #2275
Opened 2021-05-14 15:38 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-71

### Funcionalidad desarrollada 
1. Permitir ver en gestión de turnos mis inscripciones asignadas

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1389
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-05-17 14:32 UTC, palita1991 requested changes
@juuliotero tengo dudas sobre el funcionamiento, en el video se puede ver como a un paciente le asigno un turno y luego pongo próximo llamado para que me aparezca uno nuevo hasta ese momento todo perfecto. Luego en mis asignadas al cargarle una nota al paciente que ya tiene un turno, me vuelve aparecer en el llamado de inscriptos. Eso esta bien? . 
A la otra paciente no la vi mas,  ahora solo la tengo en mis asignadas para poder darle turno y demás ediciones
https://www.loom.com/share/16c292c6061644e09065f27dd161d289
![image](https://user-images.githubusercontent.com/30004190/118505424-c4880c00-b702-11eb-8bb8-99265a46eac2.png)

2021-05-17 16:39 UTC, juuliotero commented
> A la otra paciente no la vi mas, ahora solo la tengo en mis asignadas para poder darle turno y demás ediciones

Quedó corregido eso pala!

2021-05-17 18:22 UTC, palita1991 approved these changes

2021-05-20 13:34 UTC, kroce requested changes
@juuliotero con los siguientes permisos me tira un error en consola y me vuelve al inicio. 

![permisos](https://user-images.githubusercontent.com/18030170/118987689-e083eb80-b956-11eb-9a9e-aba7809618dc.png)

![error](https://user-images.githubusercontent.com/18030170/118987683-df52be80-b956-11eb-8185-1ea3c9a776eb.png)

Solo me funciona cuando me doy permisos para todo el módulo de vacunación

Además, agregaría en "Mis Asignadas" una columna con fecha y hora de turno si es que tiene.  (En otra iteración serán filtros dinámicos)

2021-05-20 15:17 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4121](http://condorpiedra.andes.gob.ar:85/4121/mochawesome.html)
CYPRESS RUN: [3157](https://dashboard.cypress.io/projects/xr7gft/runs/3157/specs)
TEST START: 2021-05-20T15:17:40.470Z
TOTAL: 393
SUCCESS: 393
FAIL: 0
SKIPPED: 0

2021-05-20 18:07 UTC, juuliotero commented
> @juuliotero con los siguientes permisos me tira un error en consola y me vuelve al inicio.
> 
> ![permisos](https://user-images.githubusercontent.com/18030170/118987689-e083eb80-b956-11eb-9a9e-aba7809618dc.png)
> 
> ![error](https://user-images.githubusercontent.com/18030170/118987683-df52be80-b956-11eb-8185-1ea3c9a776eb.png)
> 
> Solo me funciona cuando me doy permisos para todo el módulo de vacunación
> 
> Además, agregaría en "Mis Asignadas" una columna con fecha y hora de turno si es que tiene. (En otra iteración serán filtros dinámicos)

Corregido todo esto

2021-05-20 18:28 UTC, palita1991 approved these changes

2021-05-21 14:20 UTC, kroce approved these changes

2021-05-21 14:34 UTC, merged