feat(Organizacion): Agregar zonas sanitarias dentro de organizacion
andes/app pull request #2278
Opened 2021-05-17 16:52 UTC by MarianoCampetella

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/MISC-156

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [X] Si
- [ ] No

2021-05-17 17:15 UTC, juuliotero requested changes

2021-05-17 17:15 UTC, juuliotero commented on src/app/components/organizacion/organizacion-create-update.html
> +                            <legend>Zonas Sanitarias</legend>
Si por organización solo se va a asignar una zona, cambiaría el título a 'Zona Sanitaria'

2021-05-17 17:15 UTC, juuliotero commented on src/app/components/organizacion/organizacion-create-update.html
> +                                <div class="row">
En lugar de usar un row e indicar las columnas, se puede insertar el select en un plex-wrapper, así se ajusta solo.

`
                            <plex-wrapper>
                                <plex-select name="zonasSanitarias" labelField="nombre" [data]="zonas"
                                             [(ngModel)]="organizacionModel.zonaSanitaria" placeholder="Seleccione...">
                                </plex-select>
                            </plex-wrapper>`

2021-05-17 17:45 UTC, MarianoCampetella commented on src/app/components/organizacion/organizacion-create-update.html
> +                                <div class="row">
Ya esta corregido lo que me mandastes.

2021-05-17 17:45 UTC, MarianoCampetella commented on src/app/components/organizacion/organizacion-create-update.html
> +                            <legend>Zonas Sanitarias</legend>
Ya esta corregido lo de zona sanitaria

2021-05-18 13:48 UTC, liquid36 approved these changes

2021-05-19 14:03 UTC, plammel approved these changes

2021-05-19 15:09 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4092](http://condorpiedra.andes.gob.ar:85/4092/mochawesome.html)
CYPRESS RUN: [3128](https://dashboard.cypress.io/projects/xr7gft/runs/3128/specs)
TEST START: 2021-05-19T15:09:42.030Z
TOTAL: 393
SUCCESS: 391
FAIL: 2
SKIPPED: 0

2021-05-19 15:23 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4093](http://condorpiedra.andes.gob.ar:85/4093/mochawesome.html)
CYPRESS RUN: [3129](https://dashboard.cypress.io/projects/xr7gft/runs/3129/specs)
TEST START: 2021-05-19T15:23:22.029Z
TOTAL: 393
SUCCESS: 393
FAIL: 0
SKIPPED: 0

2021-05-19 16:27 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4097](http://condorpiedra.andes.gob.ar:85/4097/mochawesome.html)
CYPRESS RUN: [3133](https://dashboard.cypress.io/projects/xr7gft/runs/3133/specs)
TEST START: 2021-05-19T16:27:01.070Z
TOTAL: 393
SUCCESS: 393
FAIL: 0
SKIPPED: 0

2021-05-19 16:52 UTC, merged