INT - Agregar columna 'unidad organizativa'
andes/app pull request #2283
Opened 2021-05-19 18:41 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-274

### Funcionalidad desarrollada 

1. Agrega columna 'unidad organizativa' en listado de internación
2. Agrega filtros por unidad organizativa

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si 
- [X] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1395
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-05-19 19:31 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4109](http://condorpiedra.andes.gob.ar:85/4109/mochawesome.html)
CYPRESS RUN: [3145](https://dashboard.cypress.io/projects/xr7gft/runs/3145/specs)
TEST START: 2021-05-19T19:30:46.210Z
TOTAL: 393
SUCCESS: 393
FAIL: 0
SKIPPED: 0

2021-05-20 14:23 UTC, liquid36 requested changes

2021-05-20 14:23 UTC, liquid36 commented on src/app/apps/rup/mapa-camas/views/listado-internacion/filtros-internacion/filtros-internacion.component.ts
> +        this.unidadesOrganizativas$ = this.camasHttp.snapshot('internacion', 'estadistica', new Date()).pipe(
Estos datos tienen que salir del mismo listado, no es necesario ir a ver las camas.

2021-05-20 14:23 UTC, liquid36 commented on src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.ts
> +        this.listadoInternacionService.listaInternacionFiltrada$.subscribe(lista => {
Acá podes crear un BehaviorSubject refresh, que no aplique ningún filtro pero que si ejecute de nuevo la consulta.

2021-05-21 04:36 UTC, negro89 commented
@liquid36 realizados los cambios.

2021-05-26 17:17 UTC, palita1991 approved these changes

2021-05-31 18:04 UTC, liquid36 approved these changes

2021-05-31 18:06 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4220](http://condorpiedra.andes.gob.ar:85/4220/mochawesome.html)
CYPRESS RUN: [3246](https://dashboard.cypress.io/projects/xr7gft/runs/3246/specs)
TEST START: 2021-05-31T18:05:26.581Z
TOTAL: 395
SUCCESS: 393
FAIL: 2
SKIPPED: 0

2021-05-31 18:28 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4222](http://condorpiedra.andes.gob.ar:85/4222/mochawesome.html)
CYPRESS RUN: [3248](https://dashboard.cypress.io/projects/xr7gft/runs/3248/specs)
TEST START: 2021-05-31T18:27:29.025Z
TOTAL: 395
SUCCESS: 393
FAIL: 2
SKIPPED: 0

2021-06-01 11:23 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4224](http://condorpiedra.andes.gob.ar:85/4224/mochawesome.html)
CYPRESS RUN: [3250](https://dashboard.cypress.io/projects/xr7gft/runs/3250/specs)
TEST START: 2021-06-01T11:23:12.380Z
TOTAL: 395
SUCCESS: 395
FAIL: 0
SKIPPED: 0

2021-06-03 16:17 UTC, merged