INT - Agrega columna 'obra social' en listado
andes/app pull request #2284
Opened 2021-05-19 19:04 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-259

### Funcionalidad desarrollada 

1. Agrega columna y filtros de obra social

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-05-19 19:17 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4108](http://condorpiedra.andes.gob.ar:85/4108/mochawesome.html)
CYPRESS RUN: [3144](https://dashboard.cypress.io/projects/xr7gft/runs/3144/specs)
TEST START: 2021-05-19T19:17:40.515Z
TOTAL: 326
SUCCESS: 315
FAIL: 11
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-05-19 21:00 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4110](http://condorpiedra.andes.gob.ar:85/4110/mochawesome.html)
CYPRESS RUN: [3146](https://dashboard.cypress.io/projects/xr7gft/runs/3146/specs)
TEST START: 2021-05-19T21:00:06.531Z
TOTAL: 393
SUCCESS: 393
FAIL: 0
SKIPPED: 0

2021-05-20 14:11 UTC, liquid36 requested changes
Esta todo mezclado con el otro PR de unidad organizativa.

2021-05-20 16:10 UTC, negro89 commented
> Esta todo mezclado con el otro PR de unidad organizativa.

Claro, porque hay cambios que competen a los dos (Para no replicar lo mismo en esta rama). Lo saco de master entonces.

2021-05-21 05:23 UTC, negro89 commented
Esta funcionalidad queda en el Pull Request https://github.com/andes/app/pull/2290

2021-05-21 05:23 UTC, closed without merging