feat(PACS):mapa de agendas con colores
andes/app pull request #2292
Opened 2021-05-26 13:44 UTC by waltergarrido

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/PACS-22
### Funcionalidad desarrollada 

1. se desarrollan componentes de semana , día y mes para generar un mapa visual de las agendas asociando un color con el tipo de prestación.
2. 
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2021-05-26 13:59 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [4172](http://condorpiedra.andes.gob.ar:85/4172/mochawesome.html)
CYPRESS RUN: [3205](https://dashboard.cypress.io/projects/xr7gft/runs/3205/specs)
TEST START: 2021-05-26T13:54:30.037Z
TOTAL: 340
SUCCESS: 331
FAIL: 9
SKIPPED: 0

2021-05-28 13:01 UTC, liquid36 reviewed
algunos pequeños comentarios iniciales

2021-06-02 17:15 UTC, sychus commented on src/app/components/turnos/gestor-agendas/mapa-agendas/mapa-agenda-mes.component.ts
> +            if (err) {
if err q hago?

2021-06-02 17:18 UTC, sychus reviewed
¿Es necesario 3 componentes para resolver esto? ¿tal vez tener un único componente que reciba por imput lo que necesite? ya que en definitiva no deja de ser más o menos lo mismo.

2021-07-01 16:23 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [4469](http://condorpiedra.andes.gob.ar:85/4469/mochawesome.html)
CYPRESS RUN: [3489](https://dashboard.cypress.io/projects/xr7gft/runs/3489/specs)
TEST START: 2021-07-01T16:23:37.048Z
TOTAL: 398
SUCCESS: 397
FAIL: 0
SKIPPED: 1

2021-07-01 16:39 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [4470](http://condorpiedra.andes.gob.ar:85/4470/mochawesome.html)
CYPRESS RUN: [3490](https://dashboard.cypress.io/projects/xr7gft/runs/3490/specs)
TEST START: 2021-07-01T16:38:59.190Z
TOTAL: 398
SUCCESS: 395
FAIL: 2
SKIPPED: 1

2021-07-02 13:30 UTC, liquid36 requested changes
![image](https://user-images.githubusercontent.com/3813270/124281419-130d3080-db20-11eb-906f-9279db1975a0.png)

El sidebar lo veo como muy azul más el invert. @JSantarelli no se que opinas, el color del turno prodría ser el success? 


![image](https://user-images.githubusercontent.com/3813270/124281706-5d8ead00-db20-11eb-8a70-0f83e265b58c.png)
La fila se exapnde cuando hay un punto, habíamos hablado de sacarlo los margenes que se agregan. Todas debería tener el mismo alto

2021-07-02 13:30 UTC, liquid36 commented on src/app/components/turnos/gestor-agendas/mapa-agendas/mapa-agendas.component.html
> +                                        subtitulo="Otro subtítulo" size="sm">
Ojo con estas cosas! Acá habíamos hablado que van los datos del paciente minimamante

2021-07-02 13:30 UTC, liquid36 commented on src/app/components/turnos/gestor-agendas/mapa-agendas/mapa-agendas.component.html
> +                            <plex-label titulo="{{turnoAsignado.horaInicio | date: 'dd/MM/yyyy'}} | {{turnoAsignado.horaInicio | date: 'HH:mm'}}"
Le fecha esta de más ya que esta en el detalle principal de sidebar.

2021-07-02 13:30 UTC, liquid36 commented on src/app/components/turnos/gestor-agendas/mapa-agendas/mapa-agendas.component.html
> +                        <plex-item [selectable]="turnoAsignado.selectable">
Minimamente al detalle del turno le agregaría el icono con el tooltip de la nota. 

nombre y apellido, documento, sexo,  capaz que edad del paciente.

2021-07-02 13:30 UTC, liquid36 commented on src/app/components/turnos/gestor-agendas/mapa-agendas/mapa-agendas.component.html
> +                <plex-list *ngIf="agenda.asignados.length>0">
Cuando no hay turnos asignados, agregaría un cartel descriptivo.

2021-07-02 13:32 UTC, liquid36 commented
![image](https://user-images.githubusercontent.com/3813270/124281966-a5153900-db20-11eb-87dc-234c12232587.png)

En el detalle del día, al seleccionar una franja, el tipo prestación es global, debería verse arriba de todo. 

La hora la pondria primero porque tiene que estar ordenado por hora, revisar si están los turnos ordenados.

2021-07-02 13:36 UTC, liquid36 commented
Se ven agendas de otras organizaciones

2021-07-02 13:37 UTC, liquid36 commented
No se ven los sobreturnos

2021-07-02 13:58 UTC, liquid36 requested changes
OJO con los nombre de variables que usa que confunden mucho.

2021-07-02 13:58 UTC, liquid36 commented on src/app/components/turnos/gestor-agendas/mapa-agendas/mapa-agenda-mes.component.ts
> +        this.mapaAgendasService.calendario$.subscribe(date => this.calendario = date);
La subscripción se tiene que hacer una sola vez cuando arranca la componente, y cuando se destruye hay que hacer un unsubscribe.

2021-07-02 13:58 UTC, liquid36 commented on src/app/services/turnos/mapa-agendas.service.ts
> +                let isThisMonth = inicio.isSameOrBefore(ultimoDiaMes) && inicio.isSameOrAfter(primerDiaMes);
Acá se podría haber usado `.isSame('2009-12-31', 'month');`

2021-07-02 13:58 UTC, liquid36 commented on src/app/services/turnos/mapa-agendas.service.ts
> +                                    turnosDia.push({
Como habíamos hablado, cada turno tiene su tipo prestación, 

Habíamos quedado lo siguiente:

Cada turno asignado con su tipo prestacion:
Los turnos disponibles asignarselo a la primera prestación del bloque como para arrancar.

2021-07-02 13:58 UTC, liquid36 commented on src/app/services/turnos/mapa-agendas.service.ts
> +                                    if (bloque.tipoPrestaciones[0].conceptId === tipoPrestacion.conceptId) {
Todo lo que hablamos del mapeo no lo aplicaste.

2021-07-02 13:58 UTC, liquid36 commented on src/app/services/turnos/mapa-agendas.service.ts
> +                    if (turnosDia?.length > 0) {
turnosDía siempre va a estar denifido. El signo  `?` esta demás, confunde.-

2021-07-02 13:58 UTC, liquid36 commented on src/app/services/turnos/mapa-agendas.service.ts
> +                            if (!turnosPrestacion.hasOwnProperty(x.tipoPrestacion.conceptId)) {
```suggestion
                            if (!turnosPrestacion[x.tipoPrestacion.conceptId]) {
```

2021-07-21 13:33 UTC, liquid36 approved these changes

2021-07-21 13:46 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4637](http://condorpiedra.andes.gob.ar:85/4637/mochawesome.html)
CYPRESS RUN: [3646](https://dashboard.cypress.io/projects/xr7gft/runs/3646/specs)
TEST START: 2021-07-21T13:45:50.608Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-07-21 15:36 UTC, merged