COM: asignar origen desde org COM
andes/app pull request #2296
Opened 2021-05-27 17:27 UTC by plammel

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/COM-80
### Funcionalidad desarrollada 

1.  Asignación de origen desde organización COM
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2021-05-27 17:43 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [4194](http://condorpiedra.andes.gob.ar:85/4194/mochawesome.html)
CYPRESS RUN: [3225](https://dashboard.cypress.io/projects/xr7gft/runs/3225/specs)
TEST START: 2021-05-27T17:43:23.872Z
TOTAL: 393
SUCCESS: 393
FAIL: 0
SKIPPED: 0

2021-05-28 11:32 UTC, liquid36 requested changes

2021-05-28 11:32 UTC, liquid36 commented on src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
> +        this.paramsSubscribe = this.route.params.pipe(
Si no vas a usar todas las cualidadesde RXJS directamente usa 

```
const paciente = this.route.snapshot.paramMap.get('paciente');
```

2021-05-28 11:32 UTC, liquid36 commented on src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
> +            switchMap(() => {
Este pipeline no tiene sentido, los parámetros de la URL no dependen del GET del a organización. Genera confusión sin sentido.

2021-06-02 12:51 UTC, liquid36 commented on src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
> +                map(org => {
Primero debería ser un `tap`
Segundo hacelo directamente en el `subscribe`, ensucia el código nomás si no usas el Observable para otra cosa.

2021-06-02 13:16 UTC, plammel commented on src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
> +                map(org => {
Updeteado

2021-06-02 13:55 UTC, sychus approved these changes

2021-06-02 17:16 UTC, martinebucarey approved these changes

2021-06-02 18:46 UTC, merged