IN - Anular internación con varios movimientos
andes/app pull request #2301
Opened 2021-05-31 11:58 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-259

### Funcionalidad desarrollada 

1. Agrega un identificador común (idMovimiento) al realizar un cambio de cama, tanto a la cama origen como a la destino.
2. Permite anular una internación con mas de un movimiento.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si  https://github.com/andes/api/pull/1409
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-05-31 12:12 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4212](http://condorpiedra.andes.gob.ar:85/4212/mochawesome.html)
CYPRESS RUN: [3239](https://dashboard.cypress.io/projects/xr7gft/runs/3239/specs)
TEST START: 2021-05-31T12:12:19.054Z
TOTAL: 395
SUCCESS: 394
FAIL: 1
SKIPPED: 0

2021-05-31 12:13 UTC, liquid36 requested changes

2021-05-31 12:13 UTC, liquid36 commented on src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
> -        this.hayMovimientosAt$ = combineLatest(
No quedo claro, pero vamo hacer que solo se puede deshacer una internación si todos los movimientos tienen idMovimiento o es de ingreso/egreso. 

NO vamos a correr un script para completar datos, se ira purgando la DB sola.

2021-05-31 17:06 UTC, negro89 commented on src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
> -        this.hayMovimientosAt$ = combineLatest(
hecho

2021-06-01 13:05 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4225](http://condorpiedra.andes.gob.ar:85/4225/mochawesome.html)
CYPRESS RUN: [3251](https://dashboard.cypress.io/projects/xr7gft/runs/3251/specs)
TEST START: 2021-06-01T13:04:54.413Z
TOTAL: 395
SUCCESS: 395
FAIL: 0
SKIPPED: 0

2021-06-02 11:25 UTC, waltergarrido approved these changes

2021-06-24 13:52 UTC, liquid36 approved these changes

2021-06-24 16:02 UTC, merged