feat(VAC-77) Mostrar las vacunas con sus lotes y agregar un nuevo lote
andes/app pull request #2304
Opened 2021-06-01 14:23 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-77

### Funcionalidad desarrollada 

1. Una vez que se pueden ver las vacunas en el listado, seleccionar una para ver sus detalles como así también los lotes que tiene asociada. 
2. Una vez seleccionada la vacuna se puede agregar un nuevo lote mediante un código y descripción que son obligatorios. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-06-01 14:39 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4226](http://condorpiedra.andes.gob.ar:85/4226/mochawesome.html)
CYPRESS RUN: [3252](https://dashboard.cypress.io/projects/xr7gft/runs/3252/specs)
TEST START: 2021-06-01T14:38:50.093Z
TOTAL: 395
SUCCESS: 395
FAIL: 0
SKIPPED: 0

2021-06-01 17:53 UTC, liquid36 requested changes

2021-06-01 17:53 UTC, liquid36 commented on src/app/apps/vacunacion/components/lote/lote.component.ts
> +      map(vacunas => {
Este `map` carece de sentido si solo si buscar filtrar algunos campos.

2021-06-01 17:53 UTC, liquid36 commented on src/app/apps/vacunacion/components/lote/lote.component.ts
> +    this.lotes$ = this.vacunasService.getNomivacLotes({ habilitado: true, sort: 'codigo' }).pipe(
La API de lotes acepta un parámetro para que solo devuelva los lotes referidos a la vacuna seleccionada.
```suggestion
    this.lotes$ = this.vacunasService.getNomivacLotes({ 
        habilitado: true, 
        vacuna: this.vacunaSelected._id ,
        sort: 'codigo'
    });
```

2021-06-01 17:53 UTC, liquid36 commented on src/app/apps/vacunacion/components/lote/lote.component.ts
> +import { Component, OnInit } from '@angular/core';
Fiajte de identar el archivo a 4 espacios, que toda la aplicación esta así.

2021-06-01 17:53 UTC, liquid36 commented on src/app/apps/vacunacion/components/lote/lote.component.html
> +            <plex-select name="lote" [(ngModel)]="lote" [data]="lotes$ | async"
Mostraría un listado (`plex-list`) más que un `plex-select`.

2021-06-01 17:53 UTC, liquid36 commented on src/app/apps/vacunacion/components/lote/lote.component.html
> +            <plex-label titulo="Snomed_conceptId" subtitulo="{{vacunaSelected?.snomed_conceptId}}">
No veo muy útil este dato si no esta el Term del concepto.

2021-06-01 17:53 UTC, liquid36 commented on src/app/apps/vacunacion/components/lote/lote.component.ts
> +      sorteable: true,
La columna es sorteable, pero falta la función de `sort`.

Ejemplo: https://github.com/andes/app/blob/master/src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.ts#L48

2021-06-01 17:53 UTC, liquid36 commented on src/app/apps/vacunacion/components/lote/lote.component.ts
> +        if (resultado) {
La API nunca va a devolver null,  el mensaje de error se handlea solo por lo general. Se puede usar el onError de los Observables de RxJS en todo caso. 

Pero ese IF nunca va a entrar en el else.

2021-06-02 12:20 UTC, JSantarelli requested changes

2021-06-02 12:20 UTC, JSantarelli commented on src/app/apps/vacunacion/components/lote/lote.component.html
> +        <plex-table [columns]="columns" #table="plTable">
Considerar utilizar una [`plex-list`](https://ui.andes.gob.ar/components/plex-list/overview) dadas las caracterísiticas de la info que se muestra (ver diferencia con [`plex-table`](https://ui.andes.gob.ar/components/plex-table/overview)). Independientemente del componente a utilizar, la recomendación es mejorar el tratamiento visual de los items para que se corresponda con el resto de la aplicación (ver adjunto). 
![listado-lote01](https://user-images.githubusercontent.com/5895886/120477251-f1ceee00-c381-11eb-9fe3-6958420ade0d.PNG)

2021-06-02 12:20 UTC, JSantarelli commented on src/app/apps/vacunacion/components/lote/lote.component.html
> +    <plex-layout-sidebar type="invert">
Los detalles en los sidebar usualmente se representan con el componente [`plex-detail`](https://ui.andes.gob.ar/components/plex-detail/overview) para poder jerarquizar la información. Adjunto propuesta visual.
![detalle-lote01](https://user-images.githubusercontent.com/5895886/120478841-ab7a8e80-c383-11eb-9608-2b8ce863306f.PNG)

2021-06-02 12:29 UTC, liquid36 commented on src/app/apps/vacunacion/components/lote/lote.component.html
> +        <plex-table [columns]="columns" #table="plTable">
Ojo con la info del badge que no esta disponible en el listado, y es más de un lote.

2021-06-02 12:30 UTC, JSantarelli commented on src/app/apps/vacunacion/components/lote/lote.component.html
> +            <plex-select name="lote" [(ngModel)]="lote" [data]="lotes$ | async"
Estas interacciones generalmente las resolvemos en dos momentos: uno de _carga/edición/eliminación_ y otro de _visualización_.
En el **primer momento**, figuraría el `plex-select` junto a otras operaciones que puedan agregarse eventualmente; el **segundo momento** se corresponde con la [`plex-list`](https://ui.andes.gob.ar/components/plex-list/overview) que referencia @liquid36. Grafico para reforzar teoria:

https://user-images.githubusercontent.com/5895886/120479783-baae0c00-c384-11eb-9510-f23293af4113.mp4

2021-06-03 10:52 UTC, JSantarelli commented on src/app/apps/vacunacion/components/lote/lote.component.html
> +        <plex-table [columns]="columns" #table="plTable">
Gracias @liquid36. Ahi actualicé el mock para que no genere confusión. El contenido del badge correspondía al lote cargado por el usuario en el sidebar.

2021-06-03 12:28 UTC, martinebucarey reviewed
Si creo un lote y lo guardo, cuando voy a crear otro no se limpian los dos input de código y descripción.Adjunto video

https://www.loom.com/share/dc12021aaf754dd48c6c8a4f7847cb7d

2021-06-03 19:04 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4247](http://condorpiedra.andes.gob.ar:85/4247/mochawesome.html)
CYPRESS RUN: [3273](https://dashboard.cypress.io/projects/xr7gft/runs/3273/specs)
TEST START: 2021-06-03T19:04:29.448Z
TOTAL: 395
SUCCESS: 395
FAIL: 0
SKIPPED: 0

2021-06-10 12:41 UTC, JSantarelli requested changes

2021-06-10 12:41 UTC, JSantarelli commented on src/app/apps/vacunacion/components/lote/lote.component.html
> +		<plex-title titulo="Lotes de vacunacion" size="sm"></plex-title>
En los paneles principales generalmente utilizamos plex-title tamaño 'md'

2021-06-10 12:41 UTC, JSantarelli commented on src/app/apps/vacunacion/components/lote/lote.component.html
> +			<plex-item *ngFor="let vacuna of vacunas$ | async" (click)="showInSideBar(vacuna)">
Faltaría agregar el estado seleccionado el plex-item. El componente tiene un [input 'selected'](https://www.andes.gob.ar/plex/doc/components/PlexItemComponent.html).
En este caso podría funcionar así:  `[selected]="vacunaSelected === vacuna"`

2021-06-10 12:41 UTC, JSantarelli commented on src/app/apps/vacunacion/components/lote/lote.component.html
> +					<plex-label titulo="Codigo" subtitulo="{{lote.codigo}}" size="xl"></plex-label>
El size de los plex-label en 'lg' para que no compita con el plex-detail (que tiene mayor jerarquía visual).
Dejo [video](https://www.loom.com/share/e80631e562174c83a7b0a1429088643a) con resultado esperado de todo lo anterior.

2021-06-10 12:41 UTC, JSantarelli commented on src/app/apps/vacunacion/components/lote/lote.component.html
> +		<plex-detail size="sm" direction="row">
Generalmente al primer (o en éste caso único) plex-detail le damos size 'md' o 'lg' para jerarquizarlo.

2021-06-11 11:45 UTC, JSantarelli approved these changes

2021-06-29 13:08 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4447](http://condorpiedra.andes.gob.ar:85/4447/mochawesome.html)
CYPRESS RUN: [3464](https://dashboard.cypress.io/projects/xr7gft/runs/3464/specs)
TEST START: 2021-06-29T13:08:38.052Z
TOTAL: 398
SUCCESS: 397
FAIL: 0
SKIPPED: 1

2021-06-29 14:51 UTC, condorpiedra approved these changes

2021-06-29 14:54 UTC, merged