IN - Agrega fecha de ingreso en censo diario
andes/app pull request #2308
Opened 2021-06-01 16:47 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-297

### Funcionalidad desarrollada 

1. 
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si  https://github.com/andes/api/pull/1415
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-06-01 17:02 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4230](http://condorpiedra.andes.gob.ar:85/4230/mochawesome.html)
CYPRESS RUN: [3256](https://dashboard.cypress.io/projects/xr7gft/runs/3256/specs)
TEST START: 2021-06-01T17:02:32.564Z
TOTAL: 395
SUCCESS: 394
FAIL: 1
SKIPPED: 0

2021-06-01 17:37 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4233](http://condorpiedra.andes.gob.ar:85/4233/mochawesome.html)
CYPRESS RUN: [3259](https://dashboard.cypress.io/projects/xr7gft/runs/3259/specs)
TEST START: 2021-06-01T17:36:59.116Z
TOTAL: 395
SUCCESS: 395
FAIL: 0
SKIPPED: 0

2021-06-01 18:02 UTC, liquid36 reviewed
Cambiemos el orden de las columnas casi al final, antes de `días de estadas`.

2021-06-01 19:06 UTC, negro89 commented
> Cambiemos el orden de las columnas casi al final, antes de `días de estadas`.

Hecho.

2021-06-02 10:35 UTC, liquid36 requested changes

2021-06-02 10:35 UTC, liquid36 commented on src/app/apps/rup/mapa-camas/views/censos/censo-diario/censo-diario.component.html
> +                        <th>Ingreso</th>
La columna ingreso tiene que ir donde estaba. Estabamos hablando de la columna fecha de ingreso.

2021-06-02 16:57 UTC, liquid36 approved these changes

2021-06-02 16:58 UTC, merged