IN - Nuevo tipo de egreso 'otro'
andes/app pull request #2310
Opened 2021-06-02 14:48 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-288

### Funcionalidad desarrollada 

1. Se agrega opcion 'otro' a a la constante de internación 'listaTipoegreso'

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-06-02 16:53 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4241](http://condorpiedra.andes.gob.ar:85/4241/mochawesome.html)
CYPRESS RUN: [3267](https://dashboard.cypress.io/projects/xr7gft/runs/3267/specs)
TEST START: 2021-06-02T16:53:18.605Z
TOTAL: 395
SUCCESS: 395
FAIL: 0
SKIPPED: 0

2021-06-02 17:11 UTC, sychus requested changes
En el caso del COM están todas las organizaciones que es posible trasladar. El campo organización tiene un flag para identificar las que aceptan traslado.
Por otro lado, no está bueno que quede con un texto libre ya q luego no nos permitirá hacer ningún tipo de estadística.
Hay que ver bien el requerimiento (considero que no está bien), ya que todos los traslados se solicitan al COM y son ellos quienes deciden a que institución se traslada.

2021-06-02 17:17 UTC, liquid36 requested changes
Hay incosistencia del tipo de dato de la variable `UnidadOrganizativaDestino`. En ambos casos debería ser un objeto con id y nombre.  En el caso de `otro` el id queda vacío. 

Al editar un egreso, se pierde el estado de `otro` y lo que escribí.

De Yapa agregar la info a la componente `informe-egreso`

2021-06-03 12:12 UTC, negro89 commented
Creo que tiene mucho sentido lo que dice @sychus. Quizás le haga falta un poco mas de análisis a esta tarea. 
@liquid36 no se entendrió lo de la yapa.

2021-06-03 12:33 UTC, sychus commented
> Creo que tiene mucho sentido lo que dice @sychus. Quizás le haga falta un poco mas de análisis a esta tarea.
> @liquid36 no se entendrió lo de la yapa.

Ayer hable con la gente del COM sobre este tema, 2 temas:
1) Todo lo que es derivación COVID es como comenté arriba, por lo tanto hay q darle una vuelta de rosca y ver bien el requerimiento tal vez es hora de enganchar con COM.
2) Todo lo que es NO COVID hoy no es posible absorverlo por el com debido a que no hay RRHH, pero a futuro todas las derivaciones van a pasar por COM. Sin bien el módulo de COM está preparado para cualquier tipo de derivación hoy lo que es NO COVID va por otra vía, tenemos que ver ahí que es lo mejor para poder hacerlo ordenado.

2021-06-03 15:38 UTC, liquid36 commented
Quedo charlado con @silviroa. Es un REQ que están pidiendo hace rato  María de Estadistica. 
Además el COM no tiene todos los traslado, no me parece prudente imponer bloqueos a la carga de datos en este momento . Si sería ideal mostrar datos de la derivación en el mapa de camas y a futuro sugerir que se fue por un traslado. 

La yapa es que al ver el resumen del egreso no se esta mostrando los datos del traslado. Esta es la componente:  https://github.com/andes/app/blob/master/src/app/apps/rup/mapa-camas/sidebar/egreso/informe-egreso.component.ts#L13

2021-06-09 10:56 UTC, liquid36 commented
@negro89  el caso de editar un egreso no había sido contemplado!

2021-06-09 10:56 UTC, liquid36 approved these changes

2021-06-09 13:39 UTC, merged