feat(mapa-camas):filtros por unidad organizativa y paciente
andes/app pull request #2313
Opened 2021-06-07 17:03 UTC by waltergarrido

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/IN-289
### Funcionalidad desarrollada 

1. 
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-06-07 17:17 UTC, liquid36 requested changes
El botón visualizar debería usarse solo para cuando cambiamos las fechas, todo lo demás debería reaccionar automáticamente.

2021-06-07 17:17 UTC, liquid36 commented on src/app/apps/rup/mapa-camas/views/timelinea-mapa-camas/timeline-mapa-camas.component.ts
> +        if (this.paciente && this.movimientos.length > 0) {
Los filtros deberían aplicarse sobre los datos ya procesados, ya que por ejemplo un movimiento de egreso no tiene info del paciente, así que lo estariamos elimionando y eso hace que en la visualización el paciente parezca que nunca egreso.

2021-06-07 17:17 UTC, liquid36 commented on src/app/apps/rup/mapa-camas/views/timelinea-mapa-camas/timeline-mapa-camas.component.ts
> +        if (this.paciente && this.movimientos.length > 0) {
Se deben realizar en `cargarMovimientos` antes de crear el timeline.

2021-06-09 15:13 UTC, waltergarrido commented on src/app/apps/rup/mapa-camas/views/timelinea-mapa-camas/timeline-mapa-camas.component.ts
> +        if (this.paciente && this.movimientos.length > 0) {
@liquid36  correcciones realizadas.

2021-06-09 18:16 UTC, liquid36 approved these changes

2021-06-11 16:30 UTC, merged