PDP - Registro de cuentas
andes/app pull request #2316
Opened 2021-06-08 15:43 UTC by palita1991

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/PDP-43

### Funcionalidad desarrollada 

1. Nueva pantalla para el registro de cuenta de usuarios

**IMPORTANTE:** para poder probar el scan en el celular seguir los siguientes pasos:
1) Buscar ip de la pc (000.000.0.00)
2) Ir al environment del portal y cambiar API: '//localhost:3002/api' por API: '//**000.000.0.00**:3002/api'
3) Levanta app como ** npx ng serve portal --host=000.000.0.00 (Ip de la pc) --ssl true **
4) En el celular abrir navegador http://000.000.0.00:4200/registro -> 
5) Probar funcionalidad de scanear el dni para que se completen automáticamente los campos de documento,sexo y número de trámite.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [x] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2021-06-10 19:36 UTC, negro89 approved these changes
El resto perfectirijillo!

2021-06-10 19:36 UTC, negro89 commented on projects/portal/src/app/logo-portal-paciente/logo-portal-paciente.component.ts
>    ngOnInit(): void {
Ya que se borró un salto de linea, se podría haber borrado también esta función que no está haciendo nada.

2021-06-10 19:36 UTC, negro89 commented on projects/portal/src/app/pages/registro-cuenta/registro-cuenta.component.ts
> +import { NgForm } from '@angular/forms';
Se podría agregar al import de la linea 2

2021-06-11 12:16 UTC, palita1991 commented on projects/portal/src/app/pages/registro-cuenta/registro-cuenta.component.ts
> +import { NgForm } from '@angular/forms';
Resuelto @negro89

2021-06-11 12:16 UTC, palita1991 commented on projects/portal/src/app/logo-portal-paciente/logo-portal-paciente.component.ts
>    ngOnInit(): void {
Resuelto @negro89

2021-06-29 17:07 UTC, kroce requested changes
@palita1991 probé realizar el registro manualmente (sin scan)  y me da Forbidden. Faltaría agregar el captcha para que esto funcione. Cuando se realiza el scan estaría bien que no lo pida.

2021-07-07 17:34 UTC, kroce requested changes
@palita1991 si bien ahora pude registrarme me salta un error en consola. Adjunto captura
![image (10)](https://user-images.githubusercontent.com/18030170/124804252-76d49680-df30-11eb-8bed-e86bcb028719.png)

2021-07-08 14:12 UTC, liquid36 reviewed
Faltaría agregar la configuración de habilitar o deshabilitar el captcha

2021-07-08 14:17 UTC, liquid36 commented on projects/shared/src/lib/server/server.service.ts
> +        if (response.error) {
¿Este cambio a que se debe?

2021-07-08 14:19 UTC, liquid36 commented
![image](https://user-images.githubusercontent.com/3813270/124938069-5bc06000-dfde-11eb-96a3-7c8aa320b9c1.png)
No estaría viendo bien el registro en mobile

2021-07-08 15:47 UTC, palita1991 commented on projects/shared/src/lib/server/server.service.ts
> +        if (response.error) {
@liquid36 esto es porque la api hace un return res.status(404).send('...') , entonces cuando queria mostrar el mensaje de error no podia. Al principio lo cambie como return next() pero fallaban en la app mobile

2021-07-08 17:21 UTC, palita1991 commented on projects/portal/src/app/pages/registro-cuenta/registro-cuenta.component.html
> +            <re-captcha name="recaptcha" formControlName="recaptcha" siteKey="6Lc5nUsaAAAAALJ15OtJMKpdW9XSEOl13A_3Hx6i"
Resuelto

2021-07-12 18:36 UTC, kroce approved these changes

2021-07-13 11:17 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4553](http://condorpiedra.andes.gob.ar:85/4553/mochawesome.html)
CYPRESS RUN: [3569](https://dashboard.cypress.io/projects/xr7gft/runs/3569/specs)
TEST START: 2021-07-13T11:16:47.200Z
TOTAL: 403
SUCCESS: 402
FAIL: 0
SKIPPED: 1

2021-07-13 11:53 UTC, merged