feat(rup): permisos especiales para validar
andes/app pull request #2322
Opened 2021-06-11 13:14 UTC by liquid36

### Requerimiento
Permisos especiales para validar prestaciones no creadas por mí. Ejemplos de uso:
1. Residentes-Medicos a cargo.
2. Edición de vacunas cuando la carga un NN.

### UserStory llegó a completarse
- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos
- [ ] Si
- [ ] No

### Requiere actualizaciones en la API
- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion 
- [ ] Si
- [ ] No

2021-06-11 13:33 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4328](http://condorpiedra.andes.gob.ar:85/4328/mochawesome.html)
CYPRESS RUN: [3351](https://dashboard.cypress.io/projects/xr7gft/runs/3351/specs)
TEST START: 2021-06-11T13:33:23.834Z
TOTAL: 395
SUCCESS: 386
FAIL: 9
SKIPPED: 0

2021-06-11 14:04 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4329](http://condorpiedra.andes.gob.ar:85/4329/mochawesome.html)
CYPRESS RUN: [3352](https://dashboard.cypress.io/projects/xr7gft/runs/3352/specs)
TEST START: 2021-06-11T14:03:50.033Z
TOTAL: 395
SUCCESS: 386
FAIL: 9
SKIPPED: 0

2021-06-11 14:50 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4330](http://condorpiedra.andes.gob.ar:85/4330/mochawesome.html)
CYPRESS RUN: [3353](https://dashboard.cypress.io/projects/xr7gft/runs/3353/specs)
TEST START: 2021-06-11T14:50:06.477Z
TOTAL: 395
SUCCESS: 392
FAIL: 3
SKIPPED: 0

2021-06-15 13:09 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4349](http://condorpiedra.andes.gob.ar:85/4349/mochawesome.html)
CYPRESS RUN: [3372](https://dashboard.cypress.io/projects/xr7gft/runs/3372/specs)
TEST START: 2021-06-15T13:09:15.491Z
TOTAL: 396
SUCCESS: 395
FAIL: 0
SKIPPED: 1

2021-06-15 15:50 UTC, negro89 approved these changes

2021-06-15 20:57 UTC, silviroa requested changes

2021-06-15 20:57 UTC, silviroa commented on src/app/modules/rup/components/ejecucion/puntoInicio.html
> +                                             *ngIf="prestacion.estados[prestacion.estados.length - 1].tipo === 'ejecucion' && checkPuedeValidar(prestacion)"
este mismo control no debería aparecer en el botón "VER RESUMEN"??

2021-06-16 11:39 UTC, liquid36 commented on src/app/modules/rup/components/ejecucion/puntoInicio.html
> +                                             *ngIf="prestacion.estados[prestacion.estados.length - 1].tipo === 'ejecucion' && checkPuedeValidar(prestacion)"
De hecho, ese control es innecesario ya que se chequea al crear el listado de fuera de agendas. Me di cuenta de eso cuando lo iba a agregar a `Ver Resumen`, pero no lo saque de continuar.

2021-06-28 16:54 UTC, condorpiedra approved these changes

2021-06-28 16:56 UTC, merged