COM: remover COM de origen
andes/app pull request #2325
Opened 2021-06-14 17:20 UTC by plammel

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/COM-90
### Funcionalidad desarrollada 

1. 
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si https://github.com/andes/api/pull/1428
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2021-06-14 17:35 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [4342](http://condorpiedra.andes.gob.ar:85/4342/mochawesome.html)
CYPRESS RUN: [3365](https://dashboard.cypress.io/projects/xr7gft/runs/3365/specs)
TEST START: 2021-06-14T17:35:00.408Z
TOTAL: 352
SUCCESS: 339
FAIL: 13
SKIPPED: 0

2021-06-14 17:53 UTC, sychus requested changes
remover esa variable y verificar test.

2021-06-14 17:53 UTC, sychus commented on src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
> +    organizacionOrganizacion: any;
organizacionOrganizacion? jkajajajaj

2021-06-15 16:57 UTC, liquid36 commented
USUARIO: hfernandez  
BUILD NUMBER: [4353](http://condorpiedra.andes.gob.ar:85/4353/mochawesome.html)
CYPRESS RUN: [3376](https://dashboard.cypress.io/projects/xr7gft/runs/3376/specs)
TEST START: 2021-06-15T16:57:43.490Z
TOTAL: 396
SUCCESS: 395
FAIL: 0
SKIPPED: 1

2021-06-15 18:44 UTC, sychus approved these changes

2021-06-16 13:37 UTC, martinebucarey approved these changes

2021-06-16 16:21 UTC, merged