IN - Fix fecha 'hoy' en egreso de paciente
andes/app pull request #2343
Opened 2021-06-24 13:21 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-309

### Funcionalidad desarrollada 

1. Corrige bug en fecha maxima para agregar procedimientos quirúrgicos durante el egreso del paciente
2. Correcciones varias para evitar errores por consola

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-06-24 13:51 UTC, liquid36 requested changes

2021-06-24 13:51 UTC, liquid36 commented on src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
> +        this.fechaMaxProcedimiento = moment(this.registro[1]?.valor.InformeEgreso.fechaEgreso).endOf('day');
Al editar el egreso no respeta la fecha ya que todavía no esta el dato en esta linea.

2021-06-24 13:51 UTC, liquid36 commented on src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.html
> +                    <plex-button type="danger" size="md" icon="trash-can" label="" [disabled]="prestacionValidada"
el boton borrar tiene que quedar donde estaba, al final de la linea.

2021-06-24 13:54 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4409](http://condorpiedra.andes.gob.ar:85/4409/mochawesome.html)
CYPRESS RUN: [3427](https://dashboard.cypress.io/projects/xr7gft/runs/3427/specs)
TEST START: 2021-06-24T13:54:19.407Z
TOTAL: 398
SUCCESS: 397
FAIL: 0
SKIPPED: 1

2021-06-28 13:05 UTC, JSantarelli requested changes
Siguiendo nuestro lineamiento para formularios y en base a situaciones similares en otros módulos/componentes, lo ideal sería que ese sub-proceso mediante el cual se agrega un procedimiento quirúrgico, tuviese un 'confirmar' y un 'cancelar' o su equivalente iconográfico.
Conceptualmente, uno elimina lo que ya existe (tachito de basura) y cancela/cierra lo que está en curso (crucecita). Se adjunta propuesta.

2021-06-28 13:41 UTC, liquid36 commented
ok
Va a quedar como una tarea de mejoras, porque este fix es medio urgente.

2021-06-28 17:21 UTC, liquid36 approved these changes

2021-06-29 11:46 UTC, JSantarelli commented
> ok
> Va a quedar como una tarea de mejoras, porque este fix es medio urgente.

No problem! Gracias por avisar. Aquí queda la [tarea cargada](https://proyectos.andes.gob.ar/browse/IN-311).

2021-06-29 15:22 UTC, negro89 commented
@JSantarelli @liquid36 Se dejó el botón borrar a la derecha del campo de fecha y se agregó el atributo ariaLabel

2021-06-29 17:09 UTC, merged