Vacunación -  Registrar fecha de próximo llamado
andes/app pull request #2344
Opened 2021-06-24 19:56 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-86

### Funcionalidad desarrollada 

1. Agrega botón para seleccionar fecha de próximo llamado.
2. Se reagrupan los botones y se agrega dropdown para distribuirlos.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1448
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-06-24 20:12 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4418](http://condorpiedra.andes.gob.ar:85/4418/mochawesome.html)
CYPRESS RUN: [3435](https://dashboard.cypress.io/projects/xr7gft/runs/3435/specs)
TEST START: 2021-06-24T20:07:56.877Z
TOTAL: 346
SUCCESS: 331
FAIL: 14
SKIPPED: 1

2021-06-25 15:42 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4423](http://condorpiedra.andes.gob.ar:85/4423/mochawesome.html)
CYPRESS RUN: [3440](https://dashboard.cypress.io/projects/xr7gft/runs/3440/specs)
TEST START: 2021-06-25T15:42:13.569Z
TOTAL: 398
SUCCESS: 396
FAIL: 1
SKIPPED: 1

2021-06-25 15:53 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4424](http://condorpiedra.andes.gob.ar:85/4424/mochawesome.html)
CYPRESS RUN: [3441](https://dashboard.cypress.io/projects/xr7gft/runs/3441/specs)
TEST START: 2021-06-25T15:53:06.729Z
TOTAL: 398
SUCCESS: 395
FAIL: 2
SKIPPED: 1

2021-06-25 16:27 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4426](http://condorpiedra.andes.gob.ar:85/4426/mochawesome.html)
CYPRESS RUN: [3443](https://dashboard.cypress.io/projects/xr7gft/runs/3443/specs)
TEST START: 2021-06-25T16:27:08.688Z
TOTAL: 398
SUCCESS: 396
FAIL: 1
SKIPPED: 1

2021-06-25 17:12 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4428](http://condorpiedra.andes.gob.ar:85/4428/mochawesome.html)
CYPRESS RUN: [3445](https://dashboard.cypress.io/projects/xr7gft/runs/3445/specs)
TEST START: 2021-06-25T17:12:04.575Z
TOTAL: 398
SUCCESS: 396
FAIL: 1
SKIPPED: 1

2021-06-25 18:23 UTC, liquid36 commented on src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.html
> +                             (click)="fechaProximoLlamado = undefined; setProximoLlamado()">
No hacer estas asignacciones en el HTML, son dificiles de debuggerar y seguir el códido.

2021-06-28 12:25 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4438](http://condorpiedra.andes.gob.ar:85/4438/mochawesome.html)
CYPRESS RUN: [3455](https://dashboard.cypress.io/projects/xr7gft/runs/3455/specs)
TEST START: 2021-06-28T12:24:47.653Z
TOTAL: 398
SUCCESS: 395
FAIL: 2
SKIPPED: 1

2021-06-28 13:08 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4439](http://condorpiedra.andes.gob.ar:85/4439/mochawesome.html)
CYPRESS RUN: [3456](https://dashboard.cypress.io/projects/xr7gft/runs/3456/specs)
TEST START: 2021-06-28T13:08:26.406Z
TOTAL: 398
SUCCESS: 397
FAIL: 0
SKIPPED: 1

2021-07-26 16:29 UTC, kroce requested changes
@negro89 No me habilita el llamador después de cargar una fecha de próximo llamado en el actual. Entiendo que debería permitirme llamar al próximo

2021-07-26 17:39 UTC, kroce approved these changes

2021-07-26 18:27 UTC, palita1991 approved these changes

2021-07-26 18:29 UTC, merged