MISC: componente semaforo priorizacion
andes/app pull request #2349
Opened 2021-06-25 17:29 UTC by plammel

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/MISC-171
### Funcionalidad desarrollada 

1. https://proyectos.andes.gob.ar/browse/MISC-171
2. 
3. 

### UserStory llegó a completarse

- [ ] Si https://proyectos.andes.gob.ar/browse/MISC-171
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si Colección `semaforo` 
[semaforo com.txt](https://github.com/andes/app/files/6717889/semaforo.com.txt)

- [ ] No

### Requiere actualizaciones en la API

- [x] Si https://github.com/andes/api/pull/1450
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2021-06-25 17:46 UTC, liquid36 commented on src/app/modules/semaforo-priorizacion/components/semaforo-priorizacion.component.ts
> +    setPrioridad(prioridad) {
Esta mal modificar un input, debería trabajarlo con @Output(). 

Ya que están armando todo una colección de semáforos configurable por módulos, pero la componente es rígida para el COM.

2021-06-25 18:50 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [4433](http://condorpiedra.andes.gob.ar:85/4433/mochawesome.html)
CYPRESS RUN: [3450](https://dashboard.cypress.io/projects/xr7gft/runs/3450/specs)
TEST START: 2021-06-25T18:50:20.789Z
TOTAL: 390
SUCCESS: 388
FAIL: 1
SKIPPED: 1

2021-06-28 17:23 UTC, plammel commented on src/app/modules/semaforo-priorizacion/components/semaforo-priorizacion.component.ts
> +    setPrioridad(prioridad) {
> Esta mal modificar un input, debería trabajarlo con @output().
> 
> Ya que están armando todo una colección de semáforos configurable por módulos, pero la componente es rígida para el COM.

updeteado!

2021-06-28 17:59 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [4441](http://condorpiedra.andes.gob.ar:85/4441/mochawesome.html)
CYPRESS RUN: [3458](https://dashboard.cypress.io/projects/xr7gft/runs/3458/specs)
TEST START: 2021-06-28T17:58:52.716Z
TOTAL: 377
SUCCESS: 374
FAIL: 2
SKIPPED: 1

2021-06-29 14:41 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [4449](http://condorpiedra.andes.gob.ar:85/4449/mochawesome.html)
CYPRESS RUN: [3466](https://dashboard.cypress.io/projects/xr7gft/runs/3466/specs)
TEST START: 2021-06-29T14:41:36.745Z
TOTAL: 398
SUCCESS: 397
FAIL: 0
SKIPPED: 1

2021-08-09 15:28 UTC, andrrrl requested changes
Todo lo demás anduvo OK!

2021-08-09 15:28 UTC, andrrrl commented on src/app/modules/semaforo-priorizacion/components/semaforo-priorizacion.component.ts
> +        this.semaforoService.findByName('com').subscribe(res =>  this.opciones = res.options);
Se pasa un `name` por input pero después está 'com' harcodeado. 
```suggestion
        this.semaforoService.findByName(name).subscribe(res =>  this.opciones = res.options);
```

2021-08-09 17:12 UTC, plammel commented on src/app/modules/semaforo-priorizacion/components/semaforo-priorizacion.component.ts
> +        this.semaforoService.findByName('com').subscribe(res =>  this.opciones = res.options);
Buen catch! Updeteado!

2021-08-09 17:16 UTC, andrrrl approved these changes
🥳

2021-08-10 11:48 UTC, liquid36 commented on src/app/modules/semaforo-priorizacion/components/semaforo-priorizacion.html
> +        <div [class]="p.label + ' box'" [ngStyle]="{ background: p.color }" [class.selected]="p.label === prioridad" (click)="select(p);" >
```suggestion
        <div class="box" [class]="p.label" [style.background]="p.color" [class.selected]="p.label === prioridad" (click)="select(p)" >
```

2021-08-10 11:52 UTC, liquid36 commented on src/app/modules/semaforo-priorizacion/components/semaforo-priorizacion.component.ts
> +    @Output() onChangeEvent = new EventEmitter<any>();
```suggestion
    @Output() change = new EventEmitter<any>();
```

2021-08-10 11:53 UTC, liquid36 commented on src/app/modules/semaforo-priorizacion/components/semaforo-priorizacion.component.ts
> +    opciones;
Estaría bueno armar la interfaz y tipar en todas las compoenntes, así ya queda...

2021-08-10 11:53 UTC, liquid36 commented on src/app/modules/semaforo-priorizacion/components/semaforo-priorizacion.component.ts
> +        private semaforoService: SemaforoService) { }
```suggestion
        private semaforoService: SemaforoService
     ) { }
```

2021-08-10 14:05 UTC, plammel commented
@liquid36 buenas observaciones! Listo todos los cambios!

2021-08-10 14:07 UTC, liquid36 approved these changes

2021-08-10 14:09 UTC, andrrrl approved these changes
👍

2021-08-10 17:07 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [4843](http://condorpiedra.andes.gob.ar:85/4843/mochawesome.html)
CYPRESS RUN: [3836](https://dashboard.cypress.io/projects/xr7gft/runs/3836/specs)
TEST START: 2021-08-10T17:06:55.189Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-08-10 17:08 UTC, merged