feat(VAC):agrega registro de llamados
andes/app pull request #2350
Opened 2021-06-25 18:35 UTC by palita1991

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/VAC-85

### Funcionalidad desarrollada 

1. Se agrego en sidebar del detalle del paciente una forma de visualizar, la cantidad de intentos de llamados que le hicieron al paciente y la fecha del último intento. 

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [x] Si https://github.com/andes/api/pull/1451
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2021-06-25 19:03 UTC, liquid36 commented
USUARIO: mpalavecino  
BUILD NUMBER: [4434](http://condorpiedra.andes.gob.ar:85/4434/mochawesome.html)
CYPRESS RUN: [3451](https://dashboard.cypress.io/projects/xr7gft/runs/3451/specs)
TEST START: 2021-06-25T19:03:21.882Z
TOTAL: 398
SUCCESS: 397
FAIL: 0
SKIPPED: 1

2021-06-30 14:21 UTC, negro89 approved these changes

2021-06-30 18:05 UTC, kroce requested changes

2021-06-30 18:05 UTC, kroce commented on src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.ts
> +        }
```suggestion
       let llamado = {
            fechaRealizacion: new Date(),
            usuario: this.auth.usuario,
            numeroIntento: 1
        };
        if (this.pacienteSelected.llamados?.length) {
            let ultimoLlamado = this.pacienteSelected.llamados[this.pacienteSelected.llamados.length - 1].numeroIntento;
            llamado.numeroIntento = ultimoLlamado + 1;
            this.pacienteSelected.llamados.push(llamado);
        } else {
            this.pacienteSelected.llamados = [llamado];
        }
```

2021-06-30 18:14 UTC, kroce requested changes

2021-06-30 18:14 UTC, kroce commented on src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.ts
> +            this.plex.toast('success', 'La incrementó cantidad de llamados correctamente');
Acá quedo mal redactado el mensaje

2021-06-30 18:46 UTC, palita1991 commented on src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.ts
> +        }
Resuelto @kroce :+1: Perfecta sugerencia

2021-06-30 18:46 UTC, palita1991 commented on src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.ts
> +            this.plex.toast('success', 'La incrementó cantidad de llamados correctamente');
Resuelto :+1:

2021-07-01 11:19 UTC, kroce approved these changes

2021-07-01 11:20 UTC, merged