VAC - Dación de turno desde la inscripción
andes/app pull request #2352
Opened 2021-06-29 14:00 UTC by negro89

### Requerimiento
 https://proyectos.andes.gob.ar/browse/VAC-83

### Funcionalidad desarrollada 

1. Selección de turno desde calendario de citas
2. Fix en actualización de contactos de paciente en componente darTurnos (Reemplazaba el valor de todos los contactos con ranking '0')

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1453
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-06-29 14:13 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4448](http://condorpiedra.andes.gob.ar:85/4448/mochawesome.html)
CYPRESS RUN: [3465](https://dashboard.cypress.io/projects/xr7gft/runs/3465/specs)
TEST START: 2021-06-29T14:13:12.522Z
TOTAL: 398
SUCCESS: 397
FAIL: 0
SKIPPED: 1

2021-07-01 17:35 UTC, plammel requested changes

2021-07-01 17:35 UTC, plammel commented on src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.ts
> +        this.conceptosTurneablesService.getAll().subscribe(data => {
Buscar el concepto por id y evitar traer todos los conceptos de la api.
```suggestion
        this.conceptosTurneablesService.search({id: this.idVacunacionCovid}).subscribe(data => {
```
En algunos casos como https://github.com/andes/app/blob/master/src/app/apps/rup/mapa-camas/constantes-internacion.ts, el concepto directamente está como constante del lado de la app. Evaluar mejor opción.

2021-07-01 17:35 UTC, plammel commented on src/app/components/turnos/dar-turnos/dar-turnos.component.ts
> +        return (this.organizacion.id === '5a5e3f7e0bd5677324737244' && !puco);
Ese id del CMI está medio fiero ahi... también esta repetido en https://github.com/andes/app/blob/4ed5805325fb482b8437e53dfc7340985f662e50/src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-turnos.component.ts#L38. Estaría bueno aprovechar la volteada para sacarlo de ahi y meterlo en una constante del módulo para consumirla desde ambos components

2021-07-06 14:54 UTC, negro89 commented on src/app/components/turnos/dar-turnos/dar-turnos.component.ts
> +        return (this.organizacion.id === '5a5e3f7e0bd5677324737244' && !puco);
Hecho

2021-07-20 19:02 UTC, plammel commented on src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.ts
> +    public idVacunacionCovid = '5fd9088a68796d29fcde55eb';
Estaría bueno que este conceptId en lugar de estar hardcodeado en el component, estuviera parametrizado en un servicio. Podria ser `elementosRup.service.ts`

2021-07-21 17:37 UTC, negro89 commented on src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.ts
> +    public idVacunacionCovid = '5fd9088a68796d29fcde55eb';
Quedó en el servicio de conceptos turneables porque no es un elemento rup

2021-07-21 17:54 UTC, plammel approved these changes

2021-07-29 13:38 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4753](http://condorpiedra.andes.gob.ar:85/4753/mochawesome.html)
CYPRESS RUN: [3749](https://dashboard.cypress.io/projects/xr7gft/runs/3749/specs)
TEST START: 2021-07-29T13:33:55.941Z
TOTAL: 341
SUCCESS: 326
FAIL: 14
SKIPPED: 1

2021-07-29 14:52 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4754](http://condorpiedra.andes.gob.ar:85/4754/mochawesome.html)
CYPRESS RUN: [3750](https://dashboard.cypress.io/projects/xr7gft/runs/3750/specs)
TEST START: 2021-07-29T14:52:05.485Z
TOTAL: 382
SUCCESS: 379
FAIL: 2
SKIPPED: 1

2021-07-29 15:05 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4755](http://condorpiedra.andes.gob.ar:85/4755/mochawesome.html)
CYPRESS RUN: [3751](https://dashboard.cypress.io/projects/xr7gft/runs/3751/specs)
TEST START: 2021-07-29T15:04:57.216Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

2021-07-29 15:41 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4756](http://condorpiedra.andes.gob.ar:85/4756/mochawesome.html)
CYPRESS RUN: [3752](https://dashboard.cypress.io/projects/xr7gft/runs/3752/specs)
TEST START: 2021-07-29T15:40:46.461Z
TOTAL: 334
SUCCESS: 321
FAIL: 12
SKIPPED: 1

2021-07-29 17:36 UTC, palita1991 requested changes

2021-07-29 17:36 UTC, palita1991 commented on src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.html
> -            </plex-button>
@negro89 se borro este boton en el rebase

2021-08-03 11:38 UTC, negro89 commented on src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.html
> -            </plex-button>
corregido, gracias!

2021-08-03 12:03 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4773](http://condorpiedra.andes.gob.ar:85/4773/mochawesome.html)
CYPRESS RUN: [3769](https://dashboard.cypress.io/projects/xr7gft/runs/3769/specs)
TEST START: 2021-08-03T11:54:06.222Z
TOTAL: 370
SUCCESS: 355
FAIL: 14
SKIPPED: 1

2021-08-03 12:48 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4776](http://condorpiedra.andes.gob.ar:85/4776/mochawesome.html)
CYPRESS RUN: [3772](https://dashboard.cypress.io/projects/xr7gft/runs/3772/specs)
TEST START: 2021-08-03T12:48:03.398Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

2021-08-04 11:50 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4796](http://condorpiedra.andes.gob.ar:85/4796/mochawesome.html)
CYPRESS RUN: [3791](https://dashboard.cypress.io/projects/xr7gft/runs/3791/specs)
TEST START: 2021-08-04T11:49:52.008Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-08-04 16:30 UTC, kroce requested changes

2021-08-04 16:30 UTC, kroce commented on src/app/services/conceptos-turneables.service.ts
> +    public static VacunacionCovid_Id = '5fd9088a68796d29fcde55eb';
Aca debería buscar por concepto y no por Id para que funcione en los distintos entotnos, el conceptId no varía, el id si. Por esto es que no podíamos probarlo local con @palita1991

2021-08-04 16:58 UTC, negro89 commented on src/app/services/conceptos-turneables.service.ts
> +    public static VacunacionCovid_Id = '5fd9088a68796d29fcde55eb';
corregido sra

2021-08-04 18:30 UTC, palita1991 requested changes
@negro89 Pude darle un turno al paciente esta vez desde del calendario, pero me surgio una duda, el botón de próximo llamado porque no se ve?
Local->
![image](https://user-images.githubusercontent.com/30004190/128235040-35727f8b-34f0-4dd7-87ff-a40055ab0858.png)

En demo actualmente ->
![image](https://user-images.githubusercontent.com/30004190/128235292-a1a2e02d-7ac5-4b52-a2f2-76bf17933d9b.png)

2021-08-05 15:37 UTC, kroce approved these changes

2021-08-05 16:04 UTC, kroce requested changes
yo de nuevo...tengo un tema cuando actualizo el teléfono del paciente en citas. No me está tomando el cambio

2021-08-06 13:29 UTC, kroce approved these changes

2021-08-06 14:47 UTC, palita1991 approved these changes

2021-08-06 15:20 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4821](http://condorpiedra.andes.gob.ar:85/4821/mochawesome.html)
CYPRESS RUN: [3815](https://dashboard.cypress.io/projects/xr7gft/runs/3815/specs)
TEST START: 2021-08-06T15:20:26.031Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

2021-08-06 15:25 UTC, merged