MPI - Seteo de atributos en paciente-detalle
andes/app pull request #2354
Opened 2021-07-02 18:17 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MISC-178

### Funcionalidad desarrollada 

1. Permite setear atributos 'size' e 'items' del componente plex-detail desde su componente padre paciente-detalle.

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-07-02 18:48 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4491](http://condorpiedra.andes.gob.ar:85/4491/mochawesome.html)
CYPRESS RUN: [3510](https://dashboard.cypress.io/projects/xr7gft/runs/3510/specs)
TEST START: 2021-07-02T18:48:36.824Z
TOTAL: 398
SUCCESS: 390
FAIL: 7
SKIPPED: 1

2021-07-06 11:43 UTC, liquid36 requested changes

2021-07-06 11:43 UTC, liquid36 commented on src/app/modules/mpi/components/paciente-detalle.component.ts
> +    @Input() detailSize: 'xs' | 'md' | 'lg' = 'lg';
```suggestion
    @Input() size: 'xs' | 'md' | 'lg' = 'lg';
```

2021-07-06 11:43 UTC, liquid36 commented on src/app/modules/mpi/components/paciente-detalle.component.ts
> +    @Input() detailSize: 'xs' | 'md' | 'lg' = 'lg';
El `<plex-detail>` tiene otro size por defecto (**md**). Esta bien que cambie el tamaño en toda la aplicación? @JSantarelli 

https://github.com/andes/plex/blob/master/src/lib/detail/detail.component.ts#L32

2021-07-06 11:43 UTC, liquid36 commented on src/app/modules/mpi/components/paciente-detalle.component.ts
> +    @Input() detailItems = [];
Es mala práctica ponerle nombres que hagan referencia a la implementación. El día de mañana se cambia la implementación interna y todos los inputs quedan en cumbia. 

```suggestion
    @Input() datos = [];
```

2021-07-06 13:41 UTC, negro89 commented on src/app/modules/mpi/components/paciente-detalle.component.ts
> +    @Input() detailSize: 'xs' | 'md' | 'lg' = 'lg';
El detalle-paciente se viene usando con un size de plex-detail en 'lg' asi que no influiría que quede asi por defecto

2021-07-06 13:41 UTC, negro89 commented on src/app/modules/mpi/components/paciente-detalle.component.ts
> +    @Input() detailItems = [];
Cambios hechos

2021-07-06 14:02 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4498](http://condorpiedra.andes.gob.ar:85/4498/mochawesome.html)
CYPRESS RUN: [3517](https://dashboard.cypress.io/projects/xr7gft/runs/3517/specs)
TEST START: 2021-07-06T14:02:18.384Z
TOTAL: 402
SUCCESS: 395
FAIL: 6
SKIPPED: 1

2021-07-06 14:34 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4499](http://condorpiedra.andes.gob.ar:85/4499/mochawesome.html)
CYPRESS RUN: [3518](https://dashboard.cypress.io/projects/xr7gft/runs/3518/specs)
TEST START: 2021-07-06T14:34:42.342Z
TOTAL: 402
SUCCESS: 401
FAIL: 0
SKIPPED: 1

2021-07-06 16:39 UTC, liquid36 commented on src/app/modules/mpi/components/paciente-detalle.html
> +    <plex-detail direction="{{ orientacion === 'vertical' ? 'column' : 'row' }}" size="{{ size }}" items="{{ datos }}"
```suggestion
    <plex-detail [direction]="orientacion === 'vertical' ? 'column' : 'row'" [size]="size" items="[datos]"
```

Es mala práctica usar las llaves `{{}}` para inputs de componentes. Si probas ahora el inputs items no te va a funcionar nada porque las llaves trasforman a la variable a un string.

2021-07-06 17:04 UTC, JSantarelli commented on src/app/modules/mpi/components/paciente-detalle.component.ts
> +    @Input() detailSize: 'xs' | 'md' | 'lg' = 'lg';
El size actualmente era fijo.. lo que se agrega es la posibilidad de configurarlo según el caso simplemente.

2021-07-20 18:11 UTC, liquid36 approved these changes

2021-07-20 18:12 UTC, merged