VAC-88: Mostrar esquemas y condiciones de una dosis
andes/app pull request #2366
Opened 2021-07-13 13:30 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-88

### Funcionalidad desarrollada 
1. Se muestran los esquemas y las condiciones de una dosis perteneciente a una vacuna.
2. Se incorporo la función de poder agregar una nueva dosis.

### UserStory llegó a completarse
- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos
- [ ] Si
- [X] No

### Requiere actualizaciones en la API
- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion
- [ ] Si
- [X] No

2021-07-13 13:43 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4557](http://condorpiedra.andes.gob.ar:85/4557/mochawesome.html)
CYPRESS RUN: [3573](https://dashboard.cypress.io/projects/xr7gft/runs/3573/specs)
TEST START: 2021-07-13T13:43:24.444Z
TOTAL: 403
SUCCESS: 402
FAIL: 0
SKIPPED: 1

2021-07-20 13:30 UTC, liquid36 requested changes
Como todo el código esta en la misma componente, la variable mostrarCondiciones es global a cada item: 

![image](https://user-images.githubusercontent.com/3813270/126331843-703e0cb6-264b-4358-b077-b19bc6a96846.png)

Así que al mostrar una condición se visualizan las de todos. La recomendación es empezar a dividir en varias componentes para emcapsular funcionalidades. 

También revisar los llamados a la API que se hacen demasiados.

2021-07-20 13:30 UTC, liquid36 commented on src/app/apps/vacunacion/components/lote/lote.component.ts
> +    let arre = Object.values(this.dosisSelected.nombre);
OJO con esto, porque el orden de los atributos no siempre puede ser el mismo. Distitnos navegadores, versiones, computadores pueden tener diferentes comportamientos. 

Ese dato viene de un plex-select así que debe tener su variable de acceso. 

PD: También tener cuidado con el nombre de las variables.

2021-07-28 15:55 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4742](http://condorpiedra.andes.gob.ar:85/4742/mochawesome.html)
CYPRESS RUN: [3739](https://dashboard.cypress.io/projects/xr7gft/runs/3739/specs)
TEST START: 2021-07-28T15:54:59.100Z
TOTAL: 320
SUCCESS: 307
FAIL: 12
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-07-28 16:11 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4743](http://condorpiedra.andes.gob.ar:85/4743/mochawesome.html)
CYPRESS RUN: [3740](https://dashboard.cypress.io/projects/xr7gft/runs/3740/specs)
TEST START: 2021-07-28T16:11:36.980Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-07-28 16:16 UTC, MarianoCampetella commented on src/app/apps/vacunacion/components/lote/lote.component.ts
> +    let arre = Object.values(this.dosisSelected.nombre);
Correcciones realizadas, muchas gracias por la ayuda!

2021-07-28 17:10 UTC, palita1991 reviewed
@MarianoCampetella  Me salio eso al querer guardar una dosis nueva, porque será ?
![image](https://user-images.githubusercontent.com/30004190/127366358-6a73a044-3ce8-4b83-b913-f3b062c08770.png)

2021-07-28 19:08 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4748](http://condorpiedra.andes.gob.ar:85/4748/mochawesome.html)
CYPRESS RUN: [3744](https://dashboard.cypress.io/projects/xr7gft/runs/3744/specs)
TEST START: 2021-07-28T19:08:22.438Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

2021-07-29 11:35 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4751](http://condorpiedra.andes.gob.ar:85/4751/mochawesome.html)
CYPRESS RUN: [3747](https://dashboard.cypress.io/projects/xr7gft/runs/3747/specs)
TEST START: 2021-07-29T11:28:33.257Z
TOTAL: 267
SUCCESS: 238
FAIL: 28
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-07-29 11:49 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4752](http://condorpiedra.andes.gob.ar:85/4752/mochawesome.html)
CYPRESS RUN: [3748](https://dashboard.cypress.io/projects/xr7gft/runs/3748/specs)
TEST START: 2021-07-29T11:49:06.185Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-07-29 11:58 UTC, MarianoCampetella commented on src/app/apps/vacunacion/components/lote/lote.component.ts
> +    let arre = Object.values(this.dosisSelected.nombre);
Corregido!!

2021-07-29 13:06 UTC, palita1991 requested changes
@MarianoCampetellaEn lineas generales esta todo bien, solo esta mal escrito el nombre de lote-esquemas.component.ts , le falta el **nt** .

2021-07-29 13:06 UTC, palita1991 commented on src/app/apps/vacunacion/components/lote/lote.component.ts
> +  ];
@MarianoCampetella esta variable no se esta utilizando

2021-07-29 19:19 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4760](http://condorpiedra.andes.gob.ar:85/4760/mochawesome.html)
CYPRESS RUN: [3756](https://dashboard.cypress.io/projects/xr7gft/runs/3756/specs)
TEST START: 2021-07-29T19:18:53.399Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-07-29 19:20 UTC, MarianoCampetella commented on src/app/apps/vacunacion/components/lote/lote.component.ts
> +  ];
Corregido!!

2021-07-30 13:29 UTC, palita1991 approved these changes

2021-08-05 14:22 UTC, kroce requested changes
No realiza ningún control de permisos de acceso. Agregar permisos de acceso específicos a esta funcionalidad dentro de los permisos correspondientes al módulo de vacunación.

2021-08-05 18:34 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4810](http://condorpiedra.andes.gob.ar:85/4810/mochawesome.html)
CYPRESS RUN: [3804](https://dashboard.cypress.io/projects/xr7gft/runs/3804/specs)
TEST START: 2021-08-05T18:32:01.937Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

2021-08-05 18:56 UTC, kroce approved these changes

2021-08-05 19:01 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4812](http://condorpiedra.andes.gob.ar:85/4812/mochawesome.html)
CYPRESS RUN: [3806](https://dashboard.cypress.io/projects/xr7gft/runs/3806/specs)
TEST START: 2021-08-05T18:59:13.919Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-08-06 11:11 UTC, JSantarelli requested changes

2021-08-06 11:11 UTC, JSantarelli commented on src/app/apps/vacunacion/components/lote/lote-esquemas.html
> +            <span>
Evitaría envolver el `plex-button` en otro elemento HTML ya que interfiere en el posicionamiento que le indica el `plex-item` a botones y badges. Si era la intención, emplear una envolvente ([plex-grid](https://www.andes.gob.ar/plex/doc/components/PlexGridComponent.html) o [plex-wrapper](https://www.andes.gob.ar/plex/doc/components/PlexWrapperComponent.html))

![item-btn-posiciones](https://user-images.githubusercontent.com/5895886/128501312-be602615-fc78-4bb5-9d5f-477b9420e829.PNG)

2021-08-06 11:11 UTC, JSantarelli commented on src/app/apps/vacunacion/components/lote/lote.component.html
>  				<plex-item *ngFor="let lote of lotes$ | async">
Si los lotes de las vacunas no son seleccionables, inhabilitar esta propiedad del `plex-item` con:
`[selectable]="false"`

2021-08-06 12:36 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4816](http://condorpiedra.andes.gob.ar:85/4816/mochawesome.html)
CYPRESS RUN: [3810](https://dashboard.cypress.io/projects/xr7gft/runs/3810/specs)
TEST START: 2021-08-06T12:36:26.987Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-08-06 12:39 UTC, MarianoCampetella commented on src/app/apps/vacunacion/components/lote/lote.component.html
>  				<plex-item *ngFor="let lote of lotes$ | async">
Corregido!

2021-08-06 12:40 UTC, MarianoCampetella commented on src/app/apps/vacunacion/components/lote/lote-esquemas.html
> +            <span>
Corregido! Fue necesario agregar el plex-grid type="full" para una mejor visibilidad al momento de desplegar el sidebar!

2021-08-06 12:40 UTC, MarianoCampetella commented on src/app/apps/vacunacion/components/lote/lote.component.html
> +								<div *ngIf="!mostrarCondiciones[dosis._id]">
Corregido!

2021-08-06 13:14 UTC, kroce approved these changes

2021-08-06 13:53 UTC, JSantarelli requested changes

2021-08-06 13:53 UTC, JSantarelli commented on src/app/apps/vacunacion/components/lote/lote-esquemas.html
> +            <span>
El `plex-grid` debe envolver a todos los elementos, incluídos plex-label y plex-badge y setearle un size. Si se usa plex-grid, no tiene sentido emplear plex-list > plex-item.

    <plex-grid type="full" size="md" justify align="center">
        <plex-label titulo="Código" subtitulo="{{esquema.codigo}}" size="md">
        </plex-label>
        <plex-button type="info" size="sm" (click)="cargarCondiciones(esquema.codigo, esquema.nombre)">
            CONDICIONES
        </plex-button>
        <plex-badge size="sm" type="info">{{esquema.nombre}}</plex-badge>
    </plex-grid>

 Otra opción más sencilla, es anidar los elementos en un `<section>` con la directiva 'justify'.

2021-08-06 14:29 UTC, JSantarelli approved these changes

2021-08-06 14:36 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4819](http://condorpiedra.andes.gob.ar:85/4819/mochawesome.html)
CYPRESS RUN: [3813](https://dashboard.cypress.io/projects/xr7gft/runs/3813/specs)
TEST START: 2021-08-06T14:36:28.038Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-08-06 18:20 UTC, merged