feat(PER-32): agregar filtros en modulo perinatal
andes/app pull request #2373
Opened 2021-07-16 15:29 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/PER-32

### Funcionalidad desarrollada 
1. Se agregaron dos filtros nuevos en el modulo de perinatal para buscar a un paciente por organizacion y/o por un profesional

### UserStory llegó a completarse
- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos
- [ ] Si
- [X] No

### Requiere actualizaciones en la API
- [X] Si  https://github.com/andes/api/pull/1474
- [ ] No

### Requiere actualizaciones en andes-test-integracion
- [ ] Si
- [X] No

2021-07-16 15:56 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4597](http://condorpiedra.andes.gob.ar:85/4597/mochawesome.html)
CYPRESS RUN: [3608](https://dashboard.cypress.io/projects/xr7gft/runs/3608/specs)
TEST START: 2021-07-16T15:56:40.119Z
TOTAL: 399
SUCCESS: 398
FAIL: 0
SKIPPED: 1

2021-07-19 14:31 UTC, plammel requested changes

2021-07-19 14:31 UTC, plammel commented on src/app/modules/perinatal/components/listado-perinatal.component.ts
> +import { Console } from 'console';
IOrganizacion y Console se importan pero no se utilizan
```suggestion
import { ProfesionalService } from 'src/app/services/profesional.service';
```

2021-07-19 15:16 UTC, plammel requested changes
Controlar la cantidad de requests que se disparan cada vez que se modifica un filtro de búsqueda.

![image](https://user-images.githubusercontent.com/25707055/126181053-bc2dcda9-621f-489d-a9e1-c73d47f94ca2.png)

2021-07-19 15:16 UTC, plammel commented on src/app/modules/perinatal/services/carnet-perinatal.service.ts
> +                }
El filtro de profesionales debería ser por el ObjectId del profesional, no por nombre y apellido.
El id del profesional ya lo obtenemos del GET de profesional que se llama para popular el combo de profesionales.

2021-07-19 19:15 UTC, plammel commented on src/app/modules/perinatal/services/carnet-perinatal.service.ts
> +                }
Los requests múltiples son un problema heredado, no introducido en este PR.
Ignorar y tratar en un requerimiento aparte: https://proyectos.andes.gob.ar/browse/PER-41

2021-07-21 11:48 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4634](http://condorpiedra.andes.gob.ar:85/4634/mochawesome.html)
CYPRESS RUN: [3643](https://dashboard.cypress.io/projects/xr7gft/runs/3643/specs)
TEST START: 2021-07-21T11:48:40.681Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-07-21 12:16 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4636](http://condorpiedra.andes.gob.ar:85/4636/mochawesome.html)
CYPRESS RUN: [3645](https://dashboard.cypress.io/projects/xr7gft/runs/3645/specs)
TEST START: 2021-07-21T12:16:35.561Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-07-21 16:06 UTC, plammel requested changes
Al abrir el sidebar, queda un espacio vacío en la segunda fila de filtros, desplazando la lista de resultados hacia abajo. @andes/ui-ux pueden dar una mano para acomodar los filtros?
![image](https://user-images.githubusercontent.com/25707055/126521644-e7f35481-bc78-4940-8ada-1debfd775d2b.png)

2021-07-21 16:06 UTC, plammel commented on src/app/modules/perinatal/components/listado-perinatal.component.html
> +                </plex-select>
Hay un detalle en probando el filtro de profesional en DEMO, que varios registros tienen controles de N. Huenchuman pero esa profesional no aparece entrelas opciones del select. 
Para plex-select con datos de tablas maestras, recomiendo usar las directivas `tmProfesionales` y `tmOrganizaciones`. Tener en cuenta importar el `DirectiveLibModule` en el `perinatal.module.ts` y remover los Observables del component.
```suggestion
                <plex-select [(ngModel)]="profesional" name="profesional" label="Profesional"
                    tmProfesionales (change)="filtrar()" labelField="nombre + apellido">
                </plex-select>

                <plex-select [(ngModel)]="organizacion" name="organizacion" label="Organizacion"
                    tmOrganizaciones (change)="filtrar()">
                </plex-select>
```

2021-07-21 16:06 UTC, plammel commented on src/app/modules/perinatal/components/listado-perinatal.component.ts
> +        this.profesionales$ = this.profesionalService.getProfesional(this.profesional);
Este get de profesionales se llama una única vez en el init, enviando un `undefined` como parametro. Probando los filtros en DEMO, se ve que varios registros tienen controles de N. Huenchuman pero esa profesional no aparece entrelas opciones del select. Suguiero remover los Observables y utilizar las directivas `tmProfesionales` y `tmOrganizaciones` para simplicar código y traer todos los profesionales.
```suggestion

```

2021-07-22 11:41 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4650](http://condorpiedra.andes.gob.ar:85/4650/mochawesome.html)
CYPRESS RUN: [3656](https://dashboard.cypress.io/projects/xr7gft/runs/3656/specs)
TEST START: 2021-07-22T11:40:31.005Z
TOTAL: 359
SUCCESS: 345
FAIL: 13
SKIPPED: 1

2021-07-22 12:23 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4652](http://condorpiedra.andes.gob.ar:85/4652/mochawesome.html)
CYPRESS RUN: [3658](https://dashboard.cypress.io/projects/xr7gft/runs/3658/specs)
TEST START: 2021-07-22T12:22:34.936Z
TOTAL: 334
SUCCESS: 320
FAIL: 14
SKIPPED: 0

2021-07-22 13:13 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4656](http://condorpiedra.andes.gob.ar:85/4656/mochawesome.html)
CYPRESS RUN: [3660](https://dashboard.cypress.io/projects/xr7gft/runs/3660/specs)
TEST START: 2021-07-22T13:12:53.844Z
TOTAL: 332
SUCCESS: 318
FAIL: 13
SKIPPED: 1

2021-07-22 16:28 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4669](http://condorpiedra.andes.gob.ar:85/4669/mochawesome.html)
CYPRESS RUN: [3672](https://dashboard.cypress.io/projects/xr7gft/runs/3672/specs)
TEST START: 2021-07-22T16:28:29.348Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-07-26 15:37 UTC, condorpiedra requested changes

2021-07-26 15:37 UTC, condorpiedra commented on src/app/modules/perinatal/services/carnet-perinatal.service.ts
> +                    params.organizacion = organizacion.nombre;
Debería ir el id de la organización

2021-07-26 16:59 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4704](http://condorpiedra.andes.gob.ar:85/4704/mochawesome.html)
CYPRESS RUN: [3704](https://dashboard.cypress.io/projects/xr7gft/runs/3704/specs)
TEST START: 2021-07-26T16:59:41.724Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

2021-07-26 17:39 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [4708](http://condorpiedra.andes.gob.ar:85/4708/mochawesome.html)
CYPRESS RUN: [3707](https://dashboard.cypress.io/projects/xr7gft/runs/3707/specs)
TEST START: 2021-07-26T17:37:50.958Z
TOTAL: 336
SUCCESS: 322
FAIL: 13
SKIPPED: 1

2021-07-26 19:07 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4713](http://condorpiedra.andes.gob.ar:85/4713/mochawesome.html)
CYPRESS RUN: [3712](https://dashboard.cypress.io/projects/xr7gft/runs/3712/specs)
TEST START: 2021-07-26T19:07:23.025Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

2021-07-27 11:37 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [4720](http://condorpiedra.andes.gob.ar:85/4720/mochawesome.html)
CYPRESS RUN: [3718](https://dashboard.cypress.io/projects/xr7gft/runs/3718/specs)
TEST START: 2021-07-27T11:37:21.337Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

2021-07-27 11:47 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4721](http://condorpiedra.andes.gob.ar:85/4721/mochawesome.html)
CYPRESS RUN: [3719](https://dashboard.cypress.io/projects/xr7gft/runs/3719/specs)
TEST START: 2021-07-27T11:47:28.039Z
TOTAL: 382
SUCCESS: 380
FAIL: 1
SKIPPED: 1

2021-07-27 11:58 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4722](http://condorpiedra.andes.gob.ar:85/4722/mochawesome.html)
CYPRESS RUN: [3720](https://dashboard.cypress.io/projects/xr7gft/runs/3720/specs)
TEST START: 2021-07-27T11:57:59.137Z
TOTAL: 348
SUCCESS: 333
FAIL: 14
SKIPPED: 1

2021-07-27 12:32 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [4724](http://condorpiedra.andes.gob.ar:85/4724/mochawesome.html)
CYPRESS RUN: [3721](https://dashboard.cypress.io/projects/xr7gft/runs/3721/specs)
TEST START: 2021-07-27T12:32:28.543Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-07-27 13:15 UTC, MCele approved these changes

2021-07-27 13:17 UTC, plammel approved these changes

2021-07-27 13:41 UTC, condorpiedra approved these changes

2021-07-27 13:41 UTC, merged