PDP - Ajustes de visualización
andes/app pull request #2380
Opened 2021-07-20 18:35 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/PDP-62

### Funcionalidad desarrollada 

1. Instala última version de plex (v7.18.2)
2. Ajustes generales de visualización

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-07-20 19:33 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4631](http://condorpiedra.andes.gob.ar:85/4631/mochawesome.html)
CYPRESS RUN: [3640](https://dashboard.cypress.io/projects/xr7gft/runs/3640/specs)
TEST START: 2021-07-20T19:24:29.948Z
TOTAL: 350
SUCCESS: 342
FAIL: 7
SKIPPED: 1

2021-07-21 11:34 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4633](http://condorpiedra.andes.gob.ar:85/4633/mochawesome.html)
CYPRESS RUN: [3642](https://dashboard.cypress.io/projects/xr7gft/runs/3642/specs)
TEST START: 2021-07-21T11:34:36.012Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-07-22 13:05 UTC, JSantarelli requested changes
Se ve bien, sólo algunos detalles en la navegación:

- Los ruteos desde el menu hamburguesa no están funcionando (por lo menos a las secciones que se han desarrollado: mis-turnos, mis-relaciones, etc.)
- En el caso de las relaciones, que el ruteo sea a 'mis-relaciones' en lugar de 'mis-familiares'

2021-07-28 11:31 UTC, JSantarelli approved these changes

2021-07-28 14:09 UTC, palita1991 approved these changes

2021-07-30 13:13 UTC, waltergarrido approved these changes

2021-08-04 11:28 UTC, merged