EP: clasificación final en HUDS
andes/app pull request #2381
Opened 2021-07-20 18:37 UTC by plammel

### Requerimiento
 
https://proyectos.andes.gob.ar/projects/EP/issues/EP-106
### Funcionalidad desarrollada 

1. 
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2021-07-20 18:41 UTC, liquid36 commented on src/app/modules/rup/components/ejecucion/hudsBusqueda.html
> +                                                    {{ prestacion.prestacion.term }} {{ prestacion.data.type ? prestacion.data.type.name : '' }}
Este dato lo correcto es setearlo donde se arma el listado. 

https://github.com/andes/app/blob/master/src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts#L395

En otro PR que estoy desarrollando, uso los mismos datos pero se cambia la vista. Ese sería un dato que estaría perdiendo.

2021-07-21 19:08 UTC, plammel commented on src/app/modules/rup/components/ejecucion/hudsBusqueda.html
> +                                                    {{ prestacion.prestacion.term }} {{ prestacion.data.type ? prestacion.data.type.name : '' }}
Hecho!

2021-07-21 19:21 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [4648](http://condorpiedra.andes.gob.ar:85/4648/mochawesome.html)
CYPRESS RUN: [3654](https://dashboard.cypress.io/projects/xr7gft/runs/3654/specs)
TEST START: 2021-07-21T19:21:20.947Z
TOTAL: 400
SUCCESS: 397
FAIL: 2
SKIPPED: 1

2021-07-22 11:20 UTC, liquid36 requested changes

2021-07-22 11:20 UTC, liquid36 commented on src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
> +    getClasificacionFinal(ficha) {
Esta función quedo sin usar.

2021-07-22 11:20 UTC, liquid36 commented on src/app/modules/rup/components/ejecucion/hudsBusqueda.html
> +                                                                <ng-container *ngIf="prestacion.tipo === 'ficha-epidemiologica'">
Usaría un `plex-badge` pero que opine @andes/ui-ux

2021-07-22 11:25 UTC, andrrrl commented on src/app/modules/rup/components/ejecucion/hudsBusqueda.html
> +                                                                <ng-container *ngIf="prestacion.tipo === 'ficha-epidemiologica'">
A ver che, en breve lo veo

2021-07-22 13:52 UTC, andrrrl requested changes

2021-07-22 13:52 UTC, andrrrl commented on src/app/modules/rup/components/ejecucion/hudsBusqueda.html
> +                                                                    </small>
Ahí lo charlamos en UI/UX, lo mejor por lo pronto es esto:
```suggestion
<plex-badge size="sm" type="info">clasificación: {{ prestacion.confirmacion }}</plex-badge>

```

2021-07-27 17:15 UTC, plammel commented on src/app/modules/rup/components/ejecucion/hudsBusqueda.html
> +                                                                    </small>
Hecho!
![image](https://user-images.githubusercontent.com/25707055/127198593-d8a376c7-95b9-49ed-9f36-7ea040ad9a95.png)

2021-07-27 17:15 UTC, plammel commented on src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
> +    getClasificacionFinal(ficha) {
Updated!

2021-07-27 17:19 UTC, liquid36 commented on src/app/modules/rup/components/ejecucion/hudsBusqueda.html
> +                                                                    </small>
Opinión personal, debería ser un badge al lado de VALIDADA y que diga el estado **solo**. Con un tooltip que diga _clasificación_.

2021-07-27 17:30 UTC, plammel commented on src/app/modules/rup/components/ejecucion/hudsBusqueda.html
> +                                                                    </small>
Usamos algún código de color? para diferenciar los tipos de clasificación (confirmado, descartado, etc) o color info para todo?

2021-07-27 18:26 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [4734](http://condorpiedra.andes.gob.ar:85/4734/mochawesome.html)
CYPRESS RUN: [3731](https://dashboard.cypress.io/projects/xr7gft/runs/3731/specs)
TEST START: 2021-07-27T18:26:17.807Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-07-28 12:30 UTC, palita1991 approved these changes

2021-08-05 17:07 UTC, liquid36 approved these changes

2021-08-05 17:24 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4808](http://condorpiedra.andes.gob.ar:85/4808/mochawesome.html)
CYPRESS RUN: [3802](https://dashboard.cypress.io/projects/xr7gft/runs/3802/specs)
TEST START: 2021-08-05T17:24:20.765Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-08-05 17:58 UTC, merged