feat(HUDS): se agrega estado solicitud y link a la prestación
andes/app pull request #2389
Opened 2021-07-28 11:44 UTC by waltergarrido

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/HUDS-39
### Funcionalidad desarrollada 

1. : Se agrega estado solicitud en el listado y un link a la prestación si esta validada
2. 
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-07-28 11:57 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [4737](http://condorpiedra.andes.gob.ar:85/4737/mochawesome.html)
CYPRESS RUN: [3734](https://dashboard.cypress.io/projects/xr7gft/runs/3734/specs)
TEST START: 2021-07-28T11:56:55.501Z
TOTAL: 320
SUCCESS: 309
FAIL: 10
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-07-28 11:59 UTC, palita1991 requested changes

2021-07-28 11:59 UTC, palita1991 commented on src/app/modules/rup/components/ejecucion/hudsBusqueda.html
> +                                                                    </ng-container>
@waltergarrido este ng-container sin contenido para que serviría?

2021-07-28 12:04 UTC, palita1991 requested changes

2021-07-28 12:04 UTC, palita1991 commented on src/app/modules/rup/components/huds/vistaContextoPrestacion.ts
> +    goto() {
@waltergarrido quizás la función podría tener un nombre mas descriptivo a su funcionamiento

2021-07-28 12:08 UTC, waltergarrido commented on src/app/modules/rup/components/ejecucion/hudsBusqueda.html
> +                                                                    </ng-container>
@palita1991 corregido .

2021-07-28 12:12 UTC, waltergarrido commented on src/app/modules/rup/components/huds/vistaContextoPrestacion.ts
> +    goto() {
@palita1991 puede ser pero la traducción del goto es ir a ,que creo describe lo que hace la función que es ir a la prestación.

2021-07-28 12:33 UTC, palita1991 commented on src/app/modules/rup/components/huds/vistaContextoPrestacion.ts
> +    goto() {
@waltergarrido si si ya se la traducción, pero bueno "ir a" como que no me dice donde. Es un detalle para que ya con el nombre de la función sepa donde va sin tener que ir al código.

2021-07-28 12:36 UTC, liquid36 commented on src/app/modules/rup/components/huds/vistaContextoPrestacion.ts
> +    goto() {
Igual no era lo que se pedía, tenes que abrir la prestación en otro pestaña. Como hiciste una vez ya con las relaciones y los conceptos.

2021-07-28 19:43 UTC, waltergarrido commented on src/app/modules/rup/components/huds/vistaContextoPrestacion.ts
> +    goto() {
@liquid36 corregido.

2021-07-28 19:54 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [4749](http://condorpiedra.andes.gob.ar:85/4749/mochawesome.html)
CYPRESS RUN: [3745](https://dashboard.cypress.io/projects/xr7gft/runs/3745/specs)
TEST START: 2021-07-28T19:54:40.203Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-08-03 14:20 UTC, liquid36 commented
![image](https://user-images.githubusercontent.com/3813270/128031733-e982d558-4205-4c50-b30f-580bd4b521e0.png)

El estado debería estar en un badge como en las otros lugares y solo si esta validada la solicitud. Es decir si se realizo.  Es lo que se intenta remarcar.

2021-08-03 14:34 UTC, liquid36 commented on src/app/modules/rup/components/huds/vistaContextoPrestacion.ts
> +            this.getPrestacion();
OJO acá porque el codigo nunca retorna y se ejecutan la apertura de los dos TABS, en este caso ya esta abierto por lo que se cierra.

2021-08-13 14:21 UTC, liquid36 approved these changes

2021-08-13 14:29 UTC, merged