PER - Descargar listado de controles
andes/app pull request #2390
Opened 2021-07-29 14:30 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/PER-37

### Funcionalidad desarrollada 

1. Botón 'descargar' que se habilita filtrando por fechas desde-hasta para descargar un csv del listado

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [X] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

Agregar en colección 'queries'

{
    "_id" : ObjectId("61016adf9dede83e3e6e0a1a"),
    "nombre" : "listado-perinatal",
    "coleccion" : "carnet-perinatal",
    "query" : [ 
        {
            "!match" : {
                "fecha" : {
                    "!gte" : "#fechaDesde",
                    "!lte" : "#fechaHasta"
                }
            }
        }, 
        {
            "!addFields" : {
                "ultimoControl" : {
                    "!arrayElemAt" : [ 
                        "$controles", 
                        -1
                    ]
                }
            }
        }, 
        {
            "!project" : {
                "_id" : 1,
                "fechaControl" : {
                    "!dateToString" : {
                        "format" : "%d-%m-%Y %H:%M",
                        "date" : "$ultimoControl.fechaControl",
                        "timezone" : "America/Argentina/Buenos_Aires"
                    }
                },
                "apellido" : "$paciente.apellido",
                "nombre" : "$paciente.nombre",
                "documento" : "$paciente.documento",
                "edad" : {
                    "!toInt" : {
                        "!divide" : [ 
                            {
                                "!subtract" : [ 
                                    "$fecha", 
                                    "$paciente.fechaNacimiento"
                                ]
                            }, 
                            NumberLong(31536000000)
                        ]
                    }
                },
                "fechaNacimiento" : {
                    "!dateToString" : {
                        "format" : "%d-%m-%Y %H:%M:%S",
                        "date" : "$paciente.fechaNacimiento",
                        "timezone" : "America/Argentina/Buenos_Aires"
                    }
                },
                "fechaUltimoControl" : {
                    "!dateToString" : {
                        "format" : "%d-%m-%Y %H:%M",
                        "date" : "$fechaUltimoControl",
                        "timezone" : "America/Argentina/Buenos_Aires"
                    }
                },
                "fechaProximoControl" : {
                    "!dateToString" : {
                        "format" : "%d-%m-%Y %H:%M",
                        "date" : "$fechaProximoControl",
                        "timezone" : "America/Argentina/Buenos_Aires"
                    }
                },
                "modificacion" : {
                    "!dateToString" : {
                        "format" : "%d-%m-%Y %H:%M:%S",
                        "date" : "$updatedAt",
                        "timezone" : "America/Argentina/Buenos_Aires"
                    }
                }
            }
        }, 
        {
            "!sort" : {
                "fechaControl" : -1
            }
        }
    ],
    "argumentos" : [ 
        {
            "key" : "fechaDesde",
            "tipo" : "date",
            "label" : "Fecha desde",
            "required" : false
        }, 
        {
            "key" : "fechaHasta",
            "tipo" : "date",
            "label" : "Fecha hasta",
            "required" : false
        }
    ]
}

2021-08-03 12:17 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4774](http://condorpiedra.andes.gob.ar:85/4774/mochawesome.html)
CYPRESS RUN: [3770](https://dashboard.cypress.io/projects/xr7gft/runs/3770/specs)
TEST START: 2021-08-03T12:17:22.792Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-08-06 15:07 UTC, MCele approved these changes

2021-08-06 15:29 UTC, liquid36 approved these changes

2021-08-06 15:45 UTC, MCele requested changes
No estaría filtrando por organizacion y demás filtros en la descarga. Solo por fecha desde/hasta

2021-08-09 18:50 UTC, condorpiedra approved these changes

2021-08-09 18:51 UTC, merged