Buscador Epidemiología: Agregar filtro de clasificación final y columna idPcr
andes/app pull request #2395
Opened 2021-08-03 16:52 UTC by martinebucarey

### Requerimiento
https://proyectos.andes.gob.ar/browse/EP-114

### Funcionalidad desarrollada 

1. Se agrega la columna PCR al buscador, si la ficha tiene el campo se muestra el mismo, caso contrario se muestra 'Sin PCR'.
2. Se agrega un nuevo filtro de clasificación final al buscador.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [x] Si https://github.com/andes/api/pull/1502
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2021-08-03 17:20 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [4789](http://condorpiedra.andes.gob.ar:85/4789/mochawesome.html)
CYPRESS RUN: [3785](https://dashboard.cypress.io/projects/xr7gft/runs/3785/specs)
TEST START: 2021-08-03T17:20:42.619Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

2021-08-04 11:33 UTC, JSantarelli requested changes
Un detalle, en la tabla la última columna (SISA) alinea a la derecha con la propiedad 'right' en 'true'.

2021-08-06 12:03 UTC, plammel approved these changes
Aprobado con suguerencia

2021-08-06 12:03 UTC, plammel commented on src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
> +            });
```suggestion
            resultados.forEach(ficha => {
              const seccionClasificacion = ficha.secciones.find(seccion => seccion.name === 'Tipo de confirmación y Clasificación Final');
              const idPcr = seccionClasificacion?.fields.find(field => field.identificadorpcr)?.identificadorpcr;
              ficha.idPcr = idPcr ? idPcr : 'Sin PCR';
            });
```

2021-08-06 13:35 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [4817](http://condorpiedra.andes.gob.ar:85/4817/mochawesome.html)
CYPRESS RUN: [3811](https://dashboard.cypress.io/projects/xr7gft/runs/3811/specs)
TEST START: 2021-08-06T13:35:47.156Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-08-06 13:57 UTC, JSantarelli approved these changes

2021-08-06 14:57 UTC, merged