feat(CIT): consultorio virtual
andes/app pull request #2399
Opened 2021-08-10 17:26 UTC by waltergarrido

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-113
### Funcionalidad desarrollada 

1. se agrega campo link para generar una agenda virtual 
2. se agrega icono para acceder a esa agenda virtual si la agenda es virtual desde inicio de RUP 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1510
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-08-30 10:59 UTC, liquid36 requested changes
Falta agregar la edición del link al momento de dar un sobreturno.

2021-08-30 10:59 UTC, liquid36 commented
@andes/ui-ux  La palabra "**link**" es entendible por un usuario razo?

2021-08-30 11:16 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4946](http://condorpiedra.andes.gob.ar:85/4946/mochawesome.html)
CYPRESS RUN: [3919](https://dashboard.cypress.io/projects/xr7gft/runs/3919/specs)
TEST START: 2021-08-30T11:16:14.213Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

2021-09-01 12:03 UTC, liquid36 approved these changes

2021-09-01 13:50 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4960](http://condorpiedra.andes.gob.ar:85/4960/mochawesome.html)
CYPRESS RUN: [3932](https://dashboard.cypress.io/projects/xr7gft/runs/3932/specs)
TEST START: 2021-09-01T13:50:20.969Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-09-06 14:10 UTC, andrrrl requested changes
Ya casi estamos Wal!

2021-09-06 14:10 UTC, andrrrl commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
> +                            </plex-bool>
@Walter! 
1. está bárbara la funcionalidad pero quedaron un bool como slider y el otro como checkbox. Te diría que dejes ambos como slider (cambiá el de Dinámica a `plex-bool type="slide"`)
![image](https://user-images.githubusercontent.com/11394455/132229049-99c6adfe-6146-46b2-a99b-334afd2ed543.png)

2. Cambiaría "Agenda Virtual" por "Agenda por video llamada" para que no se confunda con "Ventanilla virtual" en la configuración de turnos en el panel derecho. El tooltip está bárbaro así 👌 !

2021-09-06 14:36 UTC, andrrrl commented
> @andes/ui-ux La palabra "**link**" es entendible por un usuario razo?

No es muy entendible la verdad... calculo que estamos a tiempo de cambiarla en todos lados. Propongo algo como `urlConsultorioVirtual`. Cómo te ves cambiando eso en todos lados @waltergarrido jaja

2021-09-06 14:38 UTC, liquid36 commented
> > @andes/ui-ux La palabra "**link**" es entendible por un usuario razo?
> 
> No es muy entendible la verdad... calculo que estamos a tiempo de cambiarla en todos lados. Propongo algo como `urlConsultorioVirtual`. Cómo te ves cambiando eso en todos lados @waltergarrido jaja

No lo decía por el nombre de la variable, sino por el label que ve el usuario.

2021-09-06 14:42 UTC, andrrrl commented
> > > @andes/ui-ux La palabra "**link**" es entendible por un usuario razo?
> > 
> > 
> > No es muy entendible la verdad... calculo que estamos a tiempo de cambiarla en todos lados. Propongo algo como `urlConsultorioVirtual`. Cómo te ves cambiando eso en todos lados @waltergarrido jaja
> 
> No lo decía por el nombre de la variable, sino por el label que ve el usuario.

Ah si, también! Debería decir `Dirección web:`

2021-09-06 18:40 UTC, waltergarrido commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
> +                            </plex-bool>
@andrrrl corregido

2021-09-14 18:50 UTC, kroce requested changes
@waltergarrido estuve tratando de probar el PR y no me aparece el slide de Agenda virtual, si veo el cambio del check de dinamica por un slide.

2021-09-16 17:56 UTC, kroce approved these changes

2021-09-16 18:25 UTC, merged