Epidemiología - Agregar el profesional que confirmo y el que hisopo en la ficha covid 19
andes/app pull request #2404
Opened 2021-08-12 17:37 UTC by martinebucarey

### Requerimiento
https://proyectos.andes.gob.ar/browse/EP-115

### Funcionalidad desarrollada 

1. Se agrega la función getField() al service para tener una función que al mandarle por parámetro una ficha, una sección y un campo(opcional), busque en la ficha y retorne el resultado. Esto se hizo para no seguir pegando esa búsqueda en todos lados ( queda pendiente un refactor en la ficha cada vez que se hace una búsqueda de estas).
2. Se modifica la rup card de la ficha epidemiologica para que en la parte de profesional se muestre:

- Si la ficha esta confirmada, el profesional que hizo esta acción.
- Si la ficha no esta confirmada y se pidió un hisopado que fue al laboratorio, el profesional que hizo esta acción.
- Cualquier otro caso, quien creo la ficha.

![imagen](https://user-images.githubusercontent.com/56874534/129242757-fdfe5978-103f-4950-8dee-d09d70620be6.png)

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [x] Si Actualizar en la coleccion forms la ficha covid19: 
[fichacovid.txt](https://github.com/andes/app/files/6977429/fichacovid.txt)
- [ ] No

### Requiere actualizaciones en la API

- [x] Si https://github.com/andes/api/pull/1513
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2021-08-12 17:56 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [4863](http://condorpiedra.andes.gob.ar:85/4863/mochawesome.html)
CYPRESS RUN: [3855](https://dashboard.cypress.io/projects/xr7gft/runs/3855/specs)
TEST START: 2021-08-12T17:55:46.011Z
TOTAL: 315
SUCCESS: 302
FAIL: 12
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-08-12 18:07 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [4864](http://condorpiedra.andes.gob.ar:85/4864/mochawesome.html)
CYPRESS RUN: [3856](https://dashboard.cypress.io/projects/xr7gft/runs/3856/specs)
TEST START: 2021-08-12T18:07:22.074Z
TOTAL: 400
SUCCESS: 392
FAIL: 7
SKIPPED: 1

2021-08-13 14:39 UTC, plammel requested changes

2021-08-13 14:39 UTC, plammel commented on src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
> +                    const usuarioConfirma = this.formEpidemiologiaService.getField(f, 'Tipo de confirmación y Clasificación Final', 'usuarioconfirma');
Buena oportunidad para parametrizar el nombre de confirmación final en src/app/modules/epidemiologia/contantes.ts

2021-08-13 14:39 UTC, plammel commented on src/app/modules/epidemiologia/services/ficha-epidemiologia.service.ts
> +        return fieldBuscado ? fieldBuscado : seccionBuscada;
Me hace  ruido que pueda devolver el campo o la sección, en el sentido que el propósito de la función es o buscar un campo, o buscar una sección (no ambos). Por otro lado, quien llame al método no sabrá que esta recibiendo (ej: si se ingresa un parámetro de búsqueda de field y el field no se encuentra, en el retorno se recibirá la sección, pero pasará field)

2021-08-13 14:39 UTC, plammel commented on src/app/modules/epidemiologia/services/ficha-epidemiologia.service.ts
> +            });
```suggestion
            fieldBuscado = seccionBuscada.fields.find(field => field[fieldName])?.fieldName;
```

2021-08-18 11:07 UTC, martinebucarey commented on src/app/modules/epidemiologia/services/ficha-epidemiologia.service.ts
> +        return fieldBuscado ? fieldBuscado : seccionBuscada;
si es verdad lo del retorno si no encuentra el field, pero lo de la función para que devuelva el field mandandole los 3 parámetros la ves bien o solo mandarías un field y que lo busque??

2021-08-18 11:25 UTC, liquid36 commented on src/app/modules/epidemiologia/services/ficha-epidemiologia.service.ts
> +        return fieldBuscado ? fieldBuscado : seccionBuscada;
No lo veo tan mal, porque le tenes que pasar argumentos. Entonces si le pasas el nombre del `field` sabes que vas a recibir un campo y no una sección.

2021-08-18 11:26 UTC, liquid36 commented on src/app/modules/epidemiologia/services/ficha-epidemiologia.service.ts
> +            });
Creo que así queda más prolijo y sin variables auxiliares. 
```
return seccionBuscada.fields.find(field => field[fieldName])?.fieldName;
```

2021-08-18 12:31 UTC, plammel commented on src/app/modules/epidemiologia/services/ficha-epidemiologia.service.ts
> +        return fieldBuscado ? fieldBuscado : seccionBuscada;
En cuanto al tema de field por parámetro, si se deja así habría que asegurarse que en caso de recibir nombre de field y no encontrarlo devuelva un `null` y no la sección. Desde lo semántico, me sigue haciendo ruido que una función `getFields`  devuelva secciones.
Por otro lado, la búsqueda de campos puede resolverse en dos lineas (la de sección en 1). Me parece que tema no es tanto repetir los find de arrays, si no el repetir los parametros de búsqueda/nombre de sección/`'Tipo de confirmación y Clasificación Final'`

2021-08-19 13:19 UTC, martinebucarey commented on src/app/modules/epidemiologia/services/ficha-epidemiologia.service.ts
> +            });
Bueno ahí realice el cambio, no me deja acceder mediante el "punto" así que lo tuve que hacer de otra forma. Si tome en cuenta lo que decía rulo de que si no encuentra el field no me devuelva una sección sino que devuelve null. Cuéntenme que les parece.

2021-08-19 15:02 UTC, martinebucarey commented on src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
> +                        profesional: usuarioConfirma ? usuarioConfirma : usuarioPcr ? usuarioPcr : f.createdBy.nombreCompleto,
Modificado

2021-09-03 13:58 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [4975](http://condorpiedra.andes.gob.ar:85/4975/mochawesome.html)
CYPRESS RUN: [3947](https://dashboard.cypress.io/projects/xr7gft/runs/3947/specs)
TEST START: 2021-09-03T13:58:27.549Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-09-14 14:01 UTC, plammel approved these changes

2021-09-15 14:35 UTC, kroce approved these changes

2021-09-15 17:55 UTC, merged