EP: Asignar seguimiento a profesional
andes/app pull request #2419
Opened 2021-08-27 18:44 UTC by plammel

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/EP-123
### Funcionalidad desarrollada 

1. Se agrega la posibilidad de asignar profesional a seguimientos por parte de auditor
2. FIltro de profesional
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [x] Si https://github.com/andes/api/pull/1523
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [x] Si https://github.com/andes/andes-test-integracion/pull/387
- [ ] No

2021-08-30 17:52 UTC, martinebucarey requested changes
Despues de asignar un profesional me deja deshabilitado el botón de editar los datos.
https://www.loom.com/share/cf099f199aaa4a9eb59dfd4db16a4ac9

2021-08-30 17:59 UTC, plammel commented
> Despues de asignar un profesional me deja deshabilitado el botón de editar los datos.
> 
> https://www.loom.com/share/cf099f199aaa4a9eb59dfd4db16a4ac9

corregido

2021-08-30 18:39 UTC, martinebucarey commented
![image](https://user-images.githubusercontent.com/56874534/131388234-08b8e7b3-387e-4629-8510-6afbba89dd06.png)
Si selecciono todos y despues destildo alguno, el check seleccionar todos queda tildado

2021-09-02 15:37 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [4970](http://condorpiedra.andes.gob.ar:85/4970/mochawesome.html)
CYPRESS RUN: [3942](https://dashboard.cypress.io/projects/xr7gft/runs/3942/specs)
TEST START: 2021-09-02T15:33:55.262Z
TOTAL: 400
SUCCESS: 390
FAIL: 9
SKIPPED: 1

2021-09-02 16:41 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [4971](http://condorpiedra.andes.gob.ar:85/4971/mochawesome.html)
CYPRESS RUN: [3943](https://dashboard.cypress.io/projects/xr7gft/runs/3943/specs)
TEST START: 2021-09-02T16:40:48.862Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

2021-09-03 13:15 UTC, martinebucarey requested changes
@JSantarelli @andrrrl si alguno puede mirar sobre todo la parte de la lista y dar una devolucion estaria bueno, en demo hay varios seguimientos creados donde pueden ver.
Si no tienen el icono la url es : /epidemiologia/seguimiento
Los permisos que tienen que tener son:
epidemiologia:seguimiento:update
epidemiologia:seguimiento:auditoria

2021-09-03 13:15 UTC, martinebucarey commented on src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.html
>                                          <plex-icon type="danger" name="bell"></plex-icon>
Creo que dentro de los items esta faltando el nombre a quien se le asigno, porque no me lo esta mostrando y no lo veo en el código.

2021-09-08 12:54 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [5033](http://condorpiedra.andes.gob.ar:85/5033/mochawesome.html)
CYPRESS RUN: [4002](https://dashboard.cypress.io/projects/xr7gft/runs/4002/specs)
TEST START: 2021-09-08T12:54:03.900Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

2021-09-08 15:42 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [5040](http://condorpiedra.andes.gob.ar:85/5040/mochawesome.html)
CYPRESS RUN: [4009](https://dashboard.cypress.io/projects/xr7gft/runs/4009/specs)
TEST START: 2021-09-08T15:36:07.635Z
TOTAL: 306
SUCCESS: 273
FAIL: 32
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-09-09 13:09 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [5047](http://condorpiedra.andes.gob.ar:85/5047/mochawesome.html)
CYPRESS RUN: [4012](https://dashboard.cypress.io/projects/xr7gft/runs/4012/specs)
TEST START: 2021-09-09T13:02:15.562Z
TOTAL: 363
SUCCESS: 351
FAIL: 11
SKIPPED: 1

2021-09-09 13:27 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [5048](http://condorpiedra.andes.gob.ar:85/5048/mochawesome.html)
CYPRESS RUN: [4013](https://dashboard.cypress.io/projects/xr7gft/runs/4013/specs)
TEST START: 2021-09-09T13:27:00.400Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-09-10 12:55 UTC, martinebucarey approved these changes

2021-09-10 13:43 UTC, palita1991 approved these changes

2021-09-10 13:56 UTC, kroce commented
Para next...cuando se asigna un seguimiento y luego se vuelve a asignar no precarga el usuario ya asignado.

2021-09-10 15:04 UTC, kroce approved these changes

2021-09-10 15:06 UTC, merged