Dashboards CITAS - Turnos por Prestación
andes/app pull request #2426
Opened 2021-09-03 13:58 UTC by negro89

### Requerimiento
Dashboards CITAS: Turnos por Prestación

### Funcionalidad desarrollada 

1. Setea un maximo de prestaciones y profesionales para mostrar en el grafico

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-09-03 14:13 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4976](http://condorpiedra.andes.gob.ar:85/4976/mochawesome.html)
CYPRESS RUN: [3948](https://dashboard.cypress.io/projects/xr7gft/runs/3948/specs)
TEST START: 2021-09-03T14:13:16.877Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-09-06 16:09 UTC, kroce requested changes

2021-09-06 16:09 UTC, kroce commented on src/app/modules/estadisticas/components/citas/graficos.component.ts
> +    private DATA_MAX = 30;
Estuve probando y al achicar la pantalla 30 sigue siendo mucho. Lo dejaría en 20 este valor.

2021-09-06 16:14 UTC, negro89 commented on src/app/modules/estadisticas/components/citas/graficos.component.ts
> +    private DATA_MAX = 30;
hecho!

2021-09-06 16:20 UTC, kroce approved these changes

2021-09-06 16:50 UTC, martinebucarey approved these changes

2021-09-06 16:51 UTC, merged