RUP: turno Multiprestacion
andes/app pull request #2428
Opened 2021-09-03 17:06 UTC by waltergarrido

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/RUP-276
### Funcionalidad desarrollada 

1. un turno es multiprestacion , ejemplo pueden ejecutar el mismo turno un psiquiatra y un psicólogo
2. la funcionalidad es la misma en sobreturnos
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [X] agregar el json de ejemplo en conceptoTurneable , esta en la sección código relevante al pie del pr.
las prestaciones son : consulta de psiquiatría , consulta de psicología  y consulta con alergista 
- [ ] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1530
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-10-01 14:14 UTC, martinebucarey requested changes

2021-10-01 14:14 UTC, martinebucarey commented on src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
> +        if (prestacion.refsetIds?.length > 1) {
esta prestación siempre existe?? sino el find va a devolver undefined y cuando quiera buscar refsetIds va a pinchar

2021-10-01 14:14 UTC, martinebucarey commented on src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
> +                sobreturno['prestacion'] = prestaciones.length > 0 ? prestaciones : null;
```suggestion
                sobreturno['prestacion'] = prestaciones.length ? prestaciones : null;
```

2021-10-01 14:14 UTC, martinebucarey commented on src/app/modules/rup/components/ejecucion/puntoInicio.html
> +                                                     *ngIf="esFutura(agendaSeleccionada) && agendaSeleccionada.estado !== 'auditada' && turno.estado !== 'suspendido' && turno.paciente && !chequearPre
Ojo con esto de concatenar varios && chequear la guia de desarrollo:

_ngIf: Dentro del if solo se puede poner una condición. Nada de concatenar and con diferentes variables. Si este es el caso se debe llevar a un virtual a la componentes Se recomiendo precalcular el valor en el OnInit o OnChanges, pudiendo así desarrollar mejor la lógica del elemento._

[https://github.com/andes/app/wiki](url)

2021-10-15 17:05 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5309](http://condorpiedra.andes.gob.ar:85/5309/mochawesome.html)
CYPRESS RUN: [4254](https://dashboard.cypress.io/projects/xr7gft/runs/4254/specs)
TEST START: 2021-10-15T16:56:12.615Z
TOTAL: 212
SUCCESS: 169
FAIL: 42
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-11-15 12:12 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [5483](http://condorpiedra.andes.gob.ar:85/5483/mochawesome.html)
CYPRESS RUN: [4420](https://dashboard.cypress.io/projects/xr7gft/runs/4420/specs)
TEST START: 2021-11-15T12:12:43.863Z
TOTAL: 416
SUCCESS: 415
FAIL: 0
SKIPPED: 1

2021-12-21 14:41 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5698](http://condorpiedra.andes.gob.ar:85/5698/mochawesome.html)
CYPRESS RUN: [4622](https://dashboard.cypress.io/projects/xr7gft/runs/4622/specs)
TEST START: 2021-12-21T14:40:59.118Z
TOTAL: 404
SUCCESS: 402
FAIL: 1
SKIPPED: 1

2022-01-04 13:39 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5760](http://condorpiedra.andes.gob.ar:85/5760/mochawesome.html)
CYPRESS RUN: [4684](https://dashboard.cypress.io/projects/xr7gft/runs/4684/specs)
TEST START: 2022-01-04T13:38:47.004Z
TOTAL: 404
SUCCESS: 402
FAIL: 1
SKIPPED: 1

2022-01-04 14:04 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5761](http://condorpiedra.andes.gob.ar:85/5761/mochawesome.html)
CYPRESS RUN: [4685](https://dashboard.cypress.io/projects/xr7gft/runs/4685/specs)
TEST START: 2022-01-04T14:04:24.127Z
TOTAL: 404
SUCCESS: 403
FAIL: 0
SKIPPED: 1

2022-01-04 14:53 UTC, merged