VAC - Agrega nuevo estado de inscripción
andes/app pull request #2432
Opened 2021-09-06 15:52 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-103

### Funcionalidad desarrollada 

1. Nuevo estado "no completa esquema"

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si  https://github.com/andes/api/pull/1532
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-09-06 16:33 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5005](http://condorpiedra.andes.gob.ar:85/5005/mochawesome.html)
CYPRESS RUN: [3975](https://dashboard.cypress.io/projects/xr7gft/runs/3975/specs)
TEST START: 2021-09-06T16:32:47.010Z
TOTAL: 400
SUCCESS: 396
FAIL: 3
SKIPPED: 1

2021-09-07 11:49 UTC, palita1991 requested changes
@negro89 en estas dos pantallas me sale error al querer editarle y seleccionar el nuevo estado al paciente.  me faltara algo o funciona algo mal?

**/vacunacion/listado**
![citas1](https://user-images.githubusercontent.com/30004190/132337374-044470b6-fd81-48e8-8af6-e260b328350a.png)

**/vacunacion/monitoreo**
![citas2](https://user-images.githubusercontent.com/30004190/132339472-128e0237-feb9-4286-9d19-6d357896871b.png)

2021-09-07 13:30 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5020](http://condorpiedra.andes.gob.ar:85/5020/mochawesome.html)
CYPRESS RUN: [3989](https://dashboard.cypress.io/projects/xr7gft/runs/3989/specs)
TEST START: 2021-09-07T13:29:55.366Z
TOTAL: 400
SUCCESS: 396
FAIL: 3
SKIPPED: 1

2021-09-08 13:53 UTC, kroce approved these changes

2021-09-08 14:01 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [5036](http://condorpiedra.andes.gob.ar:85/5036/mochawesome.html)
CYPRESS RUN: [4005](https://dashboard.cypress.io/projects/xr7gft/runs/4005/specs)
TEST START: 2021-09-08T14:00:45.953Z
TOTAL: 400
SUCCESS: 395
FAIL: 4
SKIPPED: 1

2021-09-08 14:01 UTC, palita1991 approved these changes

2021-09-08 14:51 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5037](http://condorpiedra.andes.gob.ar:85/5037/mochawesome.html)
CYPRESS RUN: [4006](https://dashboard.cypress.io/projects/xr7gft/runs/4006/specs)
TEST START: 2021-09-08T14:42:17.919Z
TOTAL: 372
SUCCESS: 361
FAIL: 10
SKIPPED: 1

2021-09-08 15:10 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5038](http://condorpiedra.andes.gob.ar:85/5038/mochawesome.html)
CYPRESS RUN: [4007](https://dashboard.cypress.io/projects/xr7gft/runs/4007/specs)
TEST START: 2021-09-08T15:10:31.600Z
TOTAL: 384
SUCCESS: 381
FAIL: 2
SKIPPED: 1

2021-09-08 15:24 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5039](http://condorpiedra.andes.gob.ar:85/5039/mochawesome.html)
CYPRESS RUN: [4008](https://dashboard.cypress.io/projects/xr7gft/runs/4008/specs)
TEST START: 2021-09-08T15:24:25.743Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-09-08 16:37 UTC, merged