feat(IN):si tenes permiso de mapa de camas se agrega permiso registros
andes/app pull request #2434
Opened 2021-09-07 16:32 UTC by waltergarrido

…nes el permiso de ver mapaDeCama

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/IN-323
### Funcionalidad desarrollada 

1. se agrega funcion para agregar el permiso ver registros si tenes permisos de mapa de cama 
2. 
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1535
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2021-09-07 16:46 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [5026](http://condorpiedra.andes.gob.ar:85/5026/mochawesome.html)
CYPRESS RUN: [3995](https://dashboard.cypress.io/projects/xr7gft/runs/3995/specs)
TEST START: 2021-09-07T16:46:16.458Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

2021-09-07 17:16 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [5027](http://condorpiedra.andes.gob.ar:85/5027/mochawesome.html)
CYPRESS RUN: [3996](https://dashboard.cypress.io/projects/xr7gft/runs/3996/specs)
TEST START: 2021-09-07T17:11:40.459Z
TOTAL: 313
SUCCESS: 297
FAIL: 15
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-09-08 11:06 UTC, liquid36 requested changes
Falta la funcionalidad en el mapa de camas, y esto que presentas no es un script. ¿Que quisiste hacer?

2021-09-09 15:44 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [5050](http://condorpiedra.andes.gob.ar:85/5050/mochawesome.html)
CYPRESS RUN: [4015](https://dashboard.cypress.io/projects/xr7gft/runs/4015/specs)
TEST START: 2021-09-09T15:44:05.277Z
TOTAL: 398
SUCCESS: 384
FAIL: 13
SKIPPED: 1

2021-09-09 17:37 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [5053](http://condorpiedra.andes.gob.ar:85/5053/mochawesome.html)
CYPRESS RUN: [4018](https://dashboard.cypress.io/projects/xr7gft/runs/4018/specs)
TEST START: 2021-09-09T17:36:49.563Z
TOTAL: 400
SUCCESS: 397
FAIL: 2
SKIPPED: 1

2021-09-10 13:17 UTC, liquid36 commented
El tab `registros` no debería aparecer si no tenes el permiso.

2021-09-20 13:08 UTC, liquid36 approved these changes

2021-09-20 13:09 UTC, liquid36 approved these changes

2021-09-21 12:13 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [5116](http://condorpiedra.andes.gob.ar:85/5116/mochawesome.html)
CYPRESS RUN: [4074](https://dashboard.cypress.io/projects/xr7gft/runs/4074/specs)
TEST START: 2021-09-21T12:13:04.521Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-09-22 17:53 UTC, negro89 approved these changes

2021-09-23 15:06 UTC, merged