PDP - Visualizacion de turnos pendientes
andes/app pull request #2437
Opened 2021-09-08 20:01 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/PDP-72

### Funcionalidad desarrollada 

1. Se separa la visualización de turnos pendientes e historicos

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-09-09 16:52 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5051](http://condorpiedra.andes.gob.ar:85/5051/mochawesome.html)
CYPRESS RUN: [4016](https://dashboard.cypress.io/projects/xr7gft/runs/4016/specs)
TEST START: 2021-09-09T16:42:32.779Z
TOTAL: 319
SUCCESS: 299
FAIL: 19
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-09-09 16:57 UTC, martinebucarey commented on projects/portal/src/app/pages/mis-turnos/mis-turnos-detalles.component.html
> +                    subtitulo="{{ (turno.profesionales[0]?.nombre + turno.profesionales[0]?.apellido) || 'No asignado' }}"> </plex-label>
se toma el valor 0 por algo en especial?? si el turno tiene mas de un profesional en la app se usa el pipe "enumerar" para mostrar si tiene mas de un profesional. En la app mobile también lo use.
`turno.profesionales |  enumerar:['apellido','nombre']`

2021-09-09 17:02 UTC, martinebucarey requested changes

2021-09-09 17:02 UTC, martinebucarey commented on projects/portal/src/app/pages/mis-turnos/mis-turnos.component.ts
>          );
Cuando hay mas de una subscripcion, conviene ponerle cache al observable
```suggestion
        this.turnos$ = this.turnoService.turnosFiltrados$.pipe(
            map(turnos => this.sortTurnos(turnos)),
            cache()
        );
```

2021-09-10 14:21 UTC, negro89 commented on projects/portal/src/app/pages/mis-turnos/mis-turnos-detalles.component.html
> +                    subtitulo="{{ (turno.profesionales[0]?.nombre + turno.profesionales[0]?.apellido) || 'No asignado' }}"> </plex-label>
excelente! no la tenia esa

2021-09-10 14:21 UTC, negro89 commented on projects/portal/src/app/pages/mis-turnos/mis-turnos.component.ts
>          );
Bien ahi, se me pasó.

2021-09-10 14:26 UTC, martinebucarey approved these changes

2021-09-10 14:49 UTC, palita1991 requested changes
@negro89  Todo bien, solo este detalle que el nombre y el apellido del profesional no tienen espacio
![Captura de pantalla de 2021-09-10 11-46-48](https://user-images.githubusercontent.com/30004190/132872489-d6aa14e6-2341-4cc2-902e-666988c6dac7.png)

2021-09-10 14:51 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5058](http://condorpiedra.andes.gob.ar:85/5058/mochawesome.html)
CYPRESS RUN: [4023](https://dashboard.cypress.io/projects/xr7gft/runs/4023/specs)
TEST START: 2021-09-10T14:51:00.545Z
TOTAL: 396
SUCCESS: 394
FAIL: 1
SKIPPED: 1

2021-09-10 16:58 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5061](http://condorpiedra.andes.gob.ar:85/5061/mochawesome.html)
CYPRESS RUN: [4026](https://dashboard.cypress.io/projects/xr7gft/runs/4026/specs)
TEST START: 2021-09-10T16:58:36.744Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-09-10 18:40 UTC, palita1991 commented
> @negro89 Todo bien, solo este detalle que el nombre y el apellido del profesional no tienen espacio
> ![Captura de pantalla de 2021-09-10 11-46-48](https://user-images.githubusercontent.com/30004190/132872489-d6aa14e6-2341-4cc2-902e-666988c6dac7.png)

Después de varias verificaciones entre @negro89 y @martinebucarey , al parecer es un tema de cache mio este detalle del nombre y apellido. Lo demás esta todo OK

2021-09-10 18:40 UTC, palita1991 approved these changes

2021-09-16 12:22 UTC, merged