PDP - Recuperar contraseña
andes/app pull request #2439
Opened 2021-09-10 13:15 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/PDP-52

### Funcionalidad desarrollada 

1. Nueva funcion en servicio de auth para enviar código de recuparación por rutas de mobile

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-09-10 13:32 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5057](http://condorpiedra.andes.gob.ar:85/5057/mochawesome.html)
CYPRESS RUN: [4022](https://dashboard.cypress.io/projects/xr7gft/runs/4022/specs)
TEST START: 2021-09-10T13:22:30.393Z
TOTAL: 396
SUCCESS: 389
FAIL: 6
SKIPPED: 1

2021-09-14 13:51 UTC, plammel commented on projects/portal/src/app/pages/login/login-portal-paciente.ts
> +        if(this.usuario.length){
Algunos detalles de espacios en el formateo. Curioso que no haya saltado en el linteo

2021-09-16 16:05 UTC, negro89 commented on projects/portal/src/app/pages/login/login-portal-paciente.ts
> +        if(this.usuario.length){
los agregué a manopla porque el lint:fix no me los corregía

2021-09-16 17:59 UTC, juuliotero requested changes
Si no completo el formulario de login con la contraseña, no me habilita el botón de recuperar

https://www.loom.com/share/916b23b323d24763a81d1906ba335eaa

2021-09-20 14:08 UTC, liquid36 requested changes
Usar ruteos de angular y nuevas componentes para esta funcionalidad, es imposible mandar el linlk de recuperar contraseña de esta manera.

2021-09-20 14:22 UTC, liquid36 commented on projects/portal/src/app/pages/login/login-portal-paciente.ts
> +        if(this.usuario.length){
https://github.com/andes/api/pull/1552

2021-09-24 18:04 UTC, juuliotero requested changes
Si ingreso en el formulario para ingresar código, y pongo el que me genera, me da error.

En la colección SendMessageCache el subject que me guarda es 'ANDES - Restablecer contraseña app móvil'. ¿Va a quedar así o se va a modificar según de donde lo generen (app/pdp)?

Cuando ingreso un código en activar cuenta, me aparece el siguiente mensaje:
![image](https://user-images.githubusercontent.com/7090371/134720207-c031e245-6247-428b-bda7-485cc3c500f1.png)

Debería decir código en lugar de contraseña.

2021-09-30 19:52 UTC, negro89 commented
@juuliotero  se corrigieron algunas cositas.

2021-10-01 14:13 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5223](http://condorpiedra.andes.gob.ar:85/5223/mochawesome.html)
CYPRESS RUN: [4169](https://dashboard.cypress.io/projects/xr7gft/runs/4169/specs)
TEST START: 2021-10-01T14:04:11.303Z
TOTAL: 259
SUCCESS: 233
FAIL: 25
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-10-04 13:17 UTC, juuliotero approved these changes

2021-10-05 16:54 UTC, palita1991 approved these changes

2021-10-05 17:08 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5255](http://condorpiedra.andes.gob.ar:85/5255/mochawesome.html)
CYPRESS RUN: [4201](https://dashboard.cypress.io/projects/xr7gft/runs/4201/specs)
TEST START: 2021-10-05T17:08:27.532Z
TOTAL: 401
SUCCESS: 400
FAIL: 0
SKIPPED: 1

2021-10-05 18:18 UTC, merged