BI: mejora visual reportes c2
andes/app pull request #2449
Opened 2021-09-15 18:58 UTC by plammel

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/BI-89
### Funcionalidad desarrollada 

1. Mejora visual, muestra detalle de pacientes de diagnosticos en sidebar
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2021-09-16 15:21 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [5083](http://condorpiedra.andes.gob.ar:85/5083/mochawesome.html)
CYPRESS RUN: [4046](https://dashboard.cypress.io/projects/xr7gft/runs/4046/specs)
TEST START: 2021-09-16T15:21:28.986Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-09-17 11:19 UTC, JSantarelli submitted a review, later dismissed

2021-09-17 11:19 UTC, JSantarelli commented on src/app/components/reportes/encabezadoReportes.html
> +        <reporteC2 *ngIf="showReporteC2" [diagnosticos]="diagnosticos" (select)="diagnostico = $event"></reporteC2>
Quizás es un buen momento para sustituir esta tabla por una `plex-table`, así pueden sortear y ocultar columnas de ser necesario.

2021-09-17 11:19 UTC, JSantarelli commented on src/app/components/reportes/encabezadoReportes.html
> +            <plex-item *ngFor="let paciente of diagnostico.pacientes; let i = index" class="">
Considerando la cantidad de datos en el sidebar, se le podría reducir 1 columna y que lo gane el panel principal que aloja mucha info (9 col / 3 col). De paso al item le haría que no fuese visualmente seleccionable (con el atributo `selectable="false"`)

2021-09-17 12:25 UTC, plammel commented
@JSantarelli gracias por las observaciones! Hay un refactor visual en camino para este modulo, cuyo código es bastante antiguo. La idea de este PR es realizar una mejora visual puntal (la visualización del detalle de item en sidebar); una mejora que implica un cambio de código menor, pero un impacto sustancial en la visualización (hay varios cambios en este módulo, y la idea es ir implementandolos gradualmente, para evitar PRs monstruosos que resulten en conflictos de mergeo o cambios dificiles de identificar). SI te parece, después de implementar estos cambios, nos reunimos para delinear los alcances del nuevo refactor visual.

2021-09-17 12:36 UTC, JSantarelli commented
> @JSantarelli gracias por las observaciones! Hay un refactor visual en camino para este modulo, cuyo código es bastante antiguo. La idea de este PR es realizar una mejora visual puntal (la visualización del detalle de item en sidebar); una mejora que implica un cambio de código menor, pero un impacto sustancial en la visualización (hay varios cambios en este módulo, y la idea es ir implementandolos gradualmente, para evitar PRs monstruosos que resulten en conflictos de mergeo o cambios dificiles de identificar). SI te parece, después de implementar estos cambios, nos reunimos para delinear los alcances del nuevo refactor visual.

@plammel me parece perfecto! Totalmente entendible. Si hay alguna epic o tarea para ir registrando estas mejoras, avisanos y las sumamos.

2021-09-17 13:00 UTC, plammel commented
> > @JSantarelli gracias por las observaciones! Hay un refactor visual en camino para este modulo, cuyo código es bastante antiguo. La idea de este PR es realizar una mejora visual puntal (la visualización del detalle de item en sidebar); una mejora que implica un cambio de código menor, pero un impacto sustancial en la visualización (hay varios cambios en este módulo, y la idea es ir implementandolos gradualmente, para evitar PRs monstruosos que resulten en conflictos de mergeo o cambios dificiles de identificar). SI te parece, después de implementar estos cambios, nos reunimos para delinear los alcances del nuevo refactor visual.
> 
> @plammel me parece perfecto! Totalmente entendible. Si hay alguna epic o tarea para ir registrando estas mejoras, avisanos y las sumamos.

@JSantarelli acá podemos ir registrando  https://proyectos.andes.gob.ar/browse/BI-91

2021-09-17 17:47 UTC, kroce requested changes
@plammel sabés que me aparecen todos sin el DNI. Probé con mas casos y todos igual.

![listado](https://user-images.githubusercontent.com/18030170/133831796-bef154d2-33b8-4baf-aa64-7b256a137732.png)

2021-09-20 11:47 UTC, plammel commented
> @plammel sabés que me aparecen todos sin el DNI. Probé con mas casos y todos igual.
> 
> ![listado](https://user-images.githubusercontent.com/18030170/133831796-bef154d2-33b8-4baf-aa64-7b256a137732.png)

Fixeado!

2021-09-20 12:15 UTC, kroce approved these changes

2021-09-20 12:33 UTC, martinebucarey approved these changes

2021-09-20 12:39 UTC, juuliotero commented on src/app/components/reportes/encabezadoReportes.html
> +                    <!-- <plex-select label="Zona" [data]="zonaSanitaria$ | async"
Acá quedó código comentado, por ahí es por algún motivo

2021-09-20 12:39 UTC, juuliotero approved these changes

2021-09-20 12:43 UTC, merged