HUDS: solicitud, visualizar la prestación realizada.
andes/app pull request #2462
Opened 2021-09-21 13:54 UTC by waltergarrido

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/HUDS-44
### Funcionalidad desarrollada 

1. se agrega en la misma TAB la vista-prestación de la prestacion realizada
2. 
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-09-21 14:08 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [5118](http://condorpiedra.andes.gob.ar:85/5118/mochawesome.html)
CYPRESS RUN: [4076](https://dashboard.cypress.io/projects/xr7gft/runs/4076/specs)
TEST START: 2021-09-21T14:07:54.839Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

2021-09-21 14:31 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [5119](http://condorpiedra.andes.gob.ar:85/5119/mochawesome.html)
CYPRESS RUN: [4077](https://dashboard.cypress.io/projects/xr7gft/runs/4077/specs)
TEST START: 2021-09-21T14:30:42.287Z
TOTAL: 325
SUCCESS: 309
FAIL: 15
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-09-21 17:24 UTC, liquid36 commented on src/app/modules/rup/components/ejecucion/vistaHuds.html
> +                    <vista-prestacion *ngIf="registro.data.estadoActual.tipo === 'validada'"
Esto debería ir adentro de `<vista-solicitud-top>`, fijate que lo tuviste que hacer dos veces al cambio.

2021-09-21 17:56 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5123](http://condorpiedra.andes.gob.ar:85/5123/mochawesome.html)
CYPRESS RUN: [4081](https://dashboard.cypress.io/projects/xr7gft/runs/4081/specs)
TEST START: 2021-09-21T17:55:42.143Z
TOTAL: 312
SUCCESS: 297
FAIL: 14
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-09-22 14:42 UTC, waltergarrido commented on src/app/modules/rup/components/ejecucion/vistaHuds.html
> +                    <vista-prestacion *ngIf="registro.data.estadoActual.tipo === 'validada'"
@liquid36 corregido

2021-09-22 14:58 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [5142](http://condorpiedra.andes.gob.ar:85/5142/mochawesome.html)
CYPRESS RUN: [4096](https://dashboard.cypress.io/projects/xr7gft/runs/4096/specs)
TEST START: 2021-09-22T14:58:27.803Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

2021-09-22 17:11 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [5151](http://condorpiedra.andes.gob.ar:85/5151/mochawesome.html)
CYPRESS RUN: [4103](https://dashboard.cypress.io/projects/xr7gft/runs/4103/specs)
TEST START: 2021-09-22T17:11:38.497Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-09-23 15:46 UTC, liquid36 requested changes

2021-09-23 15:46 UTC, liquid36 commented on src/app/modules/rup/components/huds/vistaProcedimiento.html
> +        <vista-prestacion [prestacion]="prestacion" [paciente]="paciente">
Se esta mostrando la prestación donde se solicito y no la prestación donde se ejecuto la solicitud.

debería ser `[prestacion]="registro.dataPrestacion"`

2021-09-23 17:38 UTC, waltergarrido commented on src/app/modules/rup/components/huds/vistaProcedimiento.html
> +        <vista-prestacion [prestacion]="prestacion" [paciente]="paciente">
corregido

2021-11-30 16:34 UTC, liquid36 commented
No prosperó la idea y faltan definiciones. Se cierra por ahora. Se tendrá en cuenta más adelante.

2021-11-30 16:34 UTC, closed without merging