feat(RUP): acceso rapido a solicitud desde reglas
andes/app pull request #2463
Opened 2021-09-22 12:07 UTC by waltergarrido

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/RUP-278
### Funcionalidad desarrollada 

1. en el listado de reglas se agrega un botón 
2. Al hacer click en el botón debe agregar el concepto a la consulta en modo solicitud.
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-09-22 12:26 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [5129](http://condorpiedra.andes.gob.ar:85/5129/mochawesome.html)
CYPRESS RUN: [4087](https://dashboard.cypress.io/projects/xr7gft/runs/4087/specs)
TEST START: 2021-09-22T12:26:27.683Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-09-22 13:25 UTC, plammel requested changes

2021-09-22 13:25 UTC, plammel commented on src/app/components/top/reglas/visualizacionReglas.component.ts
> +                this.plex.toast('danger', `El paciente ya tiene una solicitud en curso para ${concepto.term}`);
Si ya se pide confirmación, está de más mostrar un toast con el mismo mensaje.
```suggestion
```

2021-09-22 13:25 UTC, plammel commented on src/app/components/top/reglas/visualizacionReglas.component.ts
> +        }, concepto.esSolicitud);
Acá no se puede directamente enviar el concepto, en lugar de traspasar los atributos a un objeto con los mismos keys?
```suggestion
        this.ejecucionService.agregarConcepto(concepto, concepto.esSolicitud);
```

2021-09-22 18:14 UTC, negro89 commented on src/app/components/top/reglas/visualizacionReglas.component.ts
> +                this.plex.toast('danger', `El paciente ya tiene una solicitud en curso para ${concepto.term}`);
Creo que la intención era confirmar la operación exitosa, puede ser? En ese caso debería ser otro el mensaje.

2021-09-23 11:17 UTC, liquid36 requested changes

2021-09-23 11:17 UTC, liquid36 commented on src/app/components/top/reglas/visualizacionReglas.html
> +                    <plex-button type="primary" size="sm" icon="plus" tooltip="agregar a la consulta"
La visualización de reglas se usa desde otras pantallas más,así que debería tener algún Input para elegir mostrar o no el botón,
Segundo el comportamiento del botón depende de la pantalla donde se use, así que usaría un Output  para notificar que se hizo click, y desde la otra componente (en este caso) agregar el concepto.

2021-09-23 11:17 UTC, liquid36 commented on src/app/components/top/reglas/visualizacionReglas.component.ts
> +    public seleccionarConcepto(concepto) {
OJO!!! :eye::eye:  
Estás copiando código sin sentido. Tenías que llamar la función del servicio directamente y problema resuelto. Para algo esta hecha la funcionalidad en el servicio.

2021-09-28 13:00 UTC, liquid36 approved these changes

2021-09-28 13:04 UTC, merged