HUDS: prestamo-carpeta, error al cargar dos historias clínicas
andes/app pull request #2464
Opened 2021-09-22 13:29 UTC by waltergarrido

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/HUDS-45
### Funcionalidad desarrollada 

1. se cambia formato a la fecha.
2. 
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1557
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-09-22 13:41 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [5135](http://condorpiedra.andes.gob.ar:85/5135/mochawesome.html)
CYPRESS RUN: [4089](https://dashboard.cypress.io/projects/xr7gft/runs/4089/specs)
TEST START: 2021-09-22T13:41:44.228Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-09-22 18:21 UTC, negro89 approved these changes

2021-09-23 11:13 UTC, liquid36 requested changes
Hay cambios de otro PR que no tienen nada que ver con esto

2021-09-23 11:13 UTC, liquid36 commented on src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.ts
> +                fecha: moment().toDate(),
Es exactamente lo mismo a como estaba antes.

2021-09-23 11:35 UTC, closed without merging

2021-09-23 11:36 UTC, waltergarrido commented
La tarea no requiere cambios en app