PDP - Implementación de punto de inicio
andes/app pull request #2466
Opened 2021-09-22 17:03 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/PDP-79

### Funcionalidad desarrollada 

1. Actualiza a version de plex 7.19.0
2. Nuevo punto de inicio del paciente
3. Reagrupamiento de elementos versión mobile

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-09-22 17:51 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5153](http://condorpiedra.andes.gob.ar:85/5153/mochawesome.html)
CYPRESS RUN: [4105](https://dashboard.cypress.io/projects/xr7gft/runs/4105/specs)
TEST START: 2021-09-22T17:51:05.670Z
TOTAL: 383
SUCCESS: 365
FAIL: 17
SKIPPED: 1

2021-09-23 12:37 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5157](http://condorpiedra.andes.gob.ar:85/5157/mochawesome.html)
CYPRESS RUN: [4109](https://dashboard.cypress.io/projects/xr7gft/runs/4109/specs)
TEST START: 2021-09-23T12:37:03.547Z
TOTAL: 400
SUCCESS: 395
FAIL: 4
SKIPPED: 1

2021-09-23 13:22 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5160](http://condorpiedra.andes.gob.ar:85/5160/mochawesome.html)
CYPRESS RUN: [4112](https://dashboard.cypress.io/projects/xr7gft/runs/4112/specs)
TEST START: 2021-09-23T13:22:39.712Z
TOTAL: 400
SUCCESS: 395
FAIL: 4
SKIPPED: 1

2021-09-24 19:22 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5171](http://condorpiedra.andes.gob.ar:85/5171/mochawesome.html)
CYPRESS RUN: [4121](https://dashboard.cypress.io/projects/xr7gft/runs/4121/specs)
TEST START: 2021-09-24T19:21:41.378Z
TOTAL: 396
SUCCESS: 380
FAIL: 15
SKIPPED: 1

2021-09-27 17:01 UTC, juuliotero requested changes

2021-09-27 17:01 UTC, juuliotero commented on projects/portal/src/app/pages/mi-inicio/mi-inicio.component.ts
> +        this.cards = CARDS.filter(c => c.path !== 'mi-inicio' && c.path !== 'mis-datos-personales');
Se podría guardar en cada card con un flag si se muestra en inicio o no

2021-10-01 13:02 UTC, negro89 commented on projects/portal/src/app/components/paciente-detalle.component.ts
> +    ];;
corregidooo

2021-10-01 13:52 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5222](http://condorpiedra.andes.gob.ar:85/5222/mochawesome.html)
CYPRESS RUN: [4168](https://dashboard.cypress.io/projects/xr7gft/runs/4168/specs)
TEST START: 2021-10-01T13:52:43.863Z
TOTAL: 401
SUCCESS: 394
FAIL: 6
SKIPPED: 1

2021-10-01 17:19 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5225](http://condorpiedra.andes.gob.ar:85/5225/mochawesome.html)
CYPRESS RUN: [4171](https://dashboard.cypress.io/projects/xr7gft/runs/4171/specs)
TEST START: 2021-10-01T17:19:36.188Z
TOTAL: 401
SUCCESS: 394
FAIL: 6
SKIPPED: 1

2021-10-04 11:13 UTC, JSantarelli approved these changes

2021-10-04 12:08 UTC, juuliotero approved these changes

2021-10-04 19:20 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5239](http://condorpiedra.andes.gob.ar:85/5239/mochawesome.html)
CYPRESS RUN: [4185](https://dashboard.cypress.io/projects/xr7gft/runs/4185/specs)
TEST START: 2021-10-04T19:20:32.394Z
TOTAL: 401
SUCCESS: 396
FAIL: 4
SKIPPED: 1

2021-10-05 11:36 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [5242](http://condorpiedra.andes.gob.ar:85/5242/mochawesome.html)
CYPRESS RUN: [4188](https://dashboard.cypress.io/projects/xr7gft/runs/4188/specs)
TEST START: 2021-10-05T11:36:33.382Z
TOTAL: 383
SUCCESS: 375
FAIL: 7
SKIPPED: 1

2021-10-05 13:08 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [5246](http://condorpiedra.andes.gob.ar:85/5246/mochawesome.html)
CYPRESS RUN: [4192](https://dashboard.cypress.io/projects/xr7gft/runs/4192/specs)
TEST START: 2021-10-05T13:07:58.841Z
TOTAL: 401
SUCCESS: 393
FAIL: 7
SKIPPED: 1

2021-10-05 13:54 UTC, palita1991 approved these changes

2021-10-05 14:06 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [5248](http://condorpiedra.andes.gob.ar:85/5248/mochawesome.html)
CYPRESS RUN: [4194](https://dashboard.cypress.io/projects/xr7gft/runs/4194/specs)
TEST START: 2021-10-05T14:06:16.089Z
TOTAL: 401
SUCCESS: 400
FAIL: 0
SKIPPED: 1

2021-10-05 14:11 UTC, liquid36 commented
USUARIO: mpalavecino  
BUILD NUMBER: [5249](http://condorpiedra.andes.gob.ar:85/5249/mochawesome.html)
CYPRESS RUN: [4195](https://dashboard.cypress.io/projects/xr7gft/runs/4195/specs)
TEST START: 2021-10-05T14:08:27.002Z
TOTAL: 5
SUCCESS: 4
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-10-05 15:16 UTC, merged