Dashboard HUDS (Fix) - Filtros que se ocultan
andes/app pull request #2471
Opened 2021-09-24 19:02 UTC by negro89

se encapsulan filtros en un plex-help para aprovechar mejro el espacio

### Requerimiento
https://proyectos.andes.gob.ar/browse/BI-93

### Funcionalidad desarrollada 

1. Se reemplaza la sección de filtros por un un plex-help con el fin de aprovechar el espacio de la pantalla. Des esta manera también se soluciona el el requerimiento de la tarea.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-09-24 19:48 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5173](http://condorpiedra.andes.gob.ar:85/5173/mochawesome.html)
CYPRESS RUN: [4123](https://dashboard.cypress.io/projects/xr7gft/runs/4123/specs)
TEST START: 2021-09-24T19:48:32.837Z
TOTAL: 401
SUCCESS: 400
FAIL: 0
SKIPPED: 1

2021-09-27 11:04 UTC, liquid36 approved these changes

2021-09-27 11:04 UTC, liquid36 commented on src/app/modules/estadisticas/components/rup/rup-pacientes.html
> +            <section justify="around">
Si los filtros no desaparecen, todo esto no va más

2021-09-30 12:44 UTC, palita1991 requested changes
@negro89 Al filtrar y luego seleccionar con la **X** se puede observar que salen errores en la consola.
https://www.loom.com/share/dc37e8ee525d4b77bd414539595152e7

2021-09-30 17:21 UTC, negro89 commented
@liquid36 @palita1991  corregidooo

2021-09-30 18:17 UTC, kroce approved these changes

2021-09-30 18:20 UTC, merged