VAC - Agrega control etareo segun dosis
andes/app pull request #2500
Opened 2021-10-14 18:49 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-105

### Funcionalidad desarrollada 

1. Controla que la edad del paciente este dentro del rango especificado por la dosis

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-11-03 19:48 UTC, negro89 commented
@liquid36 corregidooo

2021-11-09 12:41 UTC, martinebucarey requested changes
El funcionamiento OK! lo único que me genera dudas es que revisando otro PR de vacunas (https://github.com/andes/app/pull/2505) , el plex-info que se abre en este PR es de tipo danger y el que se abre en el otro es de tipo warning. Entiendo que los "errores" serian del mismo tipo en ambos PR. ver opinion de @andrrrl

2021-11-09 12:41 UTC, martinebucarey commented on src/app/modules/rup/components/elementos/vacunas.component.ts
> +                const diasdiferencia = vacuna.fechaAplicacion.getTime() - ultimoRegistro.fechaAplicacion.getTime();
```suggestion
                const diasDiferencia = vacuna.fechaAplicacion.getTime() - ultimoRegistro.fechaAplicacion.getTime();
```

2021-11-16 13:39 UTC, negro89 commented on src/app/modules/rup/components/elementos/vacunas.component.ts
> +                const diasdiferencia = vacuna.fechaAplicacion.getTime() - ultimoRegistro.fechaAplicacion.getTime();
corregidooo

2021-12-01 13:56 UTC, liquid36 approved these changes

2021-12-01 14:55 UTC, merged