TM - Refactor de pantalla de configuración de servicios
andes/app pull request #2511
Opened 2021-11-01 20:04 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/TM-17

### Funcionalidad desarrollada 

1. Agrega label en caso de efector sin servicios
2. Elimina footer. Los botones quedan en el title, a la derecha
3. Agrega botón editar. Mientras no se este editando ningun servicio, los campos no pueden modificarse
4. Agrega boton volver
5. Al guardar cambios, redirecciona al listado de organizaciones

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-11-01 20:18 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5423](http://condorpiedra.andes.gob.ar:85/5423/mochawesome.html)
CYPRESS RUN: [4361](https://dashboard.cypress.io/projects/xr7gft/runs/4361/specs)
TEST START: 2021-11-01T20:17:47.319Z
TOTAL: 404
SUCCESS: 403
FAIL: 0
SKIPPED: 1

2021-11-03 17:21 UTC, palita1991 reviewed
@negro89 Solo un detalle, el boton "guardar" siempre queda habilitado? todo el tiempo se puede  hacer clic en el botón

2021-11-10 12:46 UTC, kroce requested changes
Da un error en consola cuando la organización no tiene el campo configuraciones.

2021-11-11 15:21 UTC, kroce approved these changes

2021-11-11 15:23 UTC, martinebucarey approved these changes

2021-11-11 15:23 UTC, negro89 commented
listooo @palita1991 @kroce

2021-11-11 15:24 UTC, merged