TM - ABM para configuración de internación
andes/app pull request #2519
Opened 2021-11-09 14:39 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-349

### Funcionalidad desarrollada 

1. Agrega dropdown en listado de organizaciones para acceder a configuracion de servicios e internacion
2. Nueva pantalla para configurar los controles de internación de cada efector

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-11-09 14:57 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5458](http://condorpiedra.andes.gob.ar:85/5458/mochawesome.html)
CYPRESS RUN: [4395](https://dashboard.cypress.io/projects/xr7gft/runs/4395/specs)
TEST START: 2021-11-09T14:57:17.009Z
TOTAL: 332
SUCCESS: 321
FAIL: 10
SKIPPED: 1

2021-11-09 15:44 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5460](http://condorpiedra.andes.gob.ar:85/5460/mochawesome.html)
CYPRESS RUN: [4397](https://dashboard.cypress.io/projects/xr7gft/runs/4397/specs)
TEST START: 2021-11-09T15:43:51.235Z
TOTAL: 404
SUCCESS: 403
FAIL: 0
SKIPPED: 1

2021-11-29 16:25 UTC, juuliotero reviewed
En el select de conceptos, se podría poner un mensaje que indique que debe escribir para que muestre opciones. Ahora dice seleccione y puede confundir.

2021-11-29 17:10 UTC, juuliotero requested changes
Si el formulario no valida, deshabilitar el botón de guardar.

Cuando entro a editar internación en una organización, entro a capa médica y me cambio a otra, no me deja guardar pero no me dice por qué  --> https://www.loom.com/share/6dd83363cae24034bb14573d78b856e6

Si cargo acciones en una capa (por ejemplo estadística), no completo los campos y le doy a guardar, no me deja. Pero si me muevo de capa puedo guardar y me guarda esas acciones incompletas --> https://www.loom.com/share/96a375eb375b4693a930037bde9b6fe7

2021-12-09 12:25 UTC, negro89 commented
@juuliotero corregido!
1. Botón guardar queda siempre habilitado de manera que si el formulario de la capa actual es correcto, se permite al uss guardar pero se le avisa que hay capas con registros incompletos
2. Se agrega cacheo a la búsqueda de unidad organizativa
3. Se modifica el placeholder del select para indicarle al uss que comience a escribir

2021-12-16 18:05 UTC, martinebucarey reviewed
Cuando ingreso a configurar una capa, me muestra como un error los campos obligatorios, convendría marcarlos con * creo
https://www.loom.com/share/0427bf407a4f45f4bb159bece9a157c8

2022-01-04 12:06 UTC, liquid36 requested changes
Van algunos detalles, este PR esta viejo y no es prioritario. Realizar los cambios al final de sprint cuando queden las demás tareas pendientes. 

Revisar todos los _estados[1]_ .

2022-01-04 12:06 UTC, liquid36 commented on src/app/components/organizacion/configuracion-internacion.component.ts
> +            });
un detalle
```suggestion
            const saveArray = this.capas.map((c: any) => {
                const organizacionCapa = this.organizacionActual[c.id];
                // por cada acción se buscan unidades organizativas exceptuadas
                organizacionCapa.estados[1]?.acciones.map(acc => {
                    const unidadOrg = acc.parametros.unidadOrganizativa[0];
                    if (acc.parametros.unidadExceptuada) {
                        acc.parametros.unidadOrganizativa[0] = `!${unidadOrg?.conceptId || unidadOrg}`;
                    } else {
                        acc.parametros.unidadOrganizativa[0] = unidadOrg?.conceptId || unidadOrg;
                    }
                    delete acc.parametros.unidadExceptuada;
                });
                return this.maquinaEstadosService.save(organizacionCapa);
            });
```

2022-01-04 12:06 UTC, liquid36 commented on src/app/apps/mitos/services/snomed.service.ts
> +    @Cache({ key: null})
Esto no es correcto, ya que no tiene en cuenta los parámetros de busqueda. En este caso la expressión de snomed va cambiando en toda la aplicaión.

2022-01-04 12:06 UTC, liquid36 commented on src/app/components/organizacion/configuracion-internacion.html
> +                                    (getData)="loadConceptos($event)" [(ngModel)]="accion.parametros.concepto" [required]="true"></plex-select>
Existe la directiva _[snomedSemantic]_ para ahorrarse código.

2022-07-14 17:17 UTC, martinebucarey commented
FIltro por concepto para el ambito internacion solamente no todos. 

reemplazar el campo de texto libre por un select para el registro

2022-08-03 14:40 UTC, negro89 commented
@martinebucarey no es posible ya que no busca los conceptos en la base sino desde el servidor de snomed

2022-08-04 12:14 UTC, martinebucarey commented
> 

Lo del texto libre en el registro si se puede hacer si no me equivoco.

2022-09-14 17:29 UTC, silviroa commented
USUARIO: silviroa  
BUILD NUMBER: [7634](http://condorpiedra.andes.gob.ar:85/7634/mochawesome.html)
CYPRESS RUN: [6480](https://dashboard.cypress.io/projects/xr7gft/runs/6480/specs)
TEST START: 2022-09-14T17:29:05.276Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-09-19 17:03 UTC, merged