Visualización de solicitudes en ejecución en RUP
andes/app pull request #2521
Opened 2021-11-10 12:29 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/TOP-120

### Funcionalidad desarrollada 
1. Se buscaron desde la base las solicitudes de top y se lo concatena al arreglo de prestaciones.
2. 

### UserStory llegó a completarse
- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API
- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion
- [ ] Si
- [X] No

2021-11-10 12:47 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5467](http://condorpiedra.andes.gob.ar:85/5467/mochawesome.html)
CYPRESS RUN: [4404](https://dashboard.cypress.io/projects/xr7gft/runs/4404/specs)
TEST START: 2021-11-10T12:38:01.756Z
TOTAL: 416
SUCCESS: 401
FAIL: 14
SKIPPED: 1

2021-11-10 13:32 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5469](http://condorpiedra.andes.gob.ar:85/5469/mochawesome.html)
CYPRESS RUN: [4406](https://dashboard.cypress.io/projects/xr7gft/runs/4406/specs)
TEST START: 2021-11-10T13:32:21.945Z
TOTAL: 416
SUCCESS: 415
FAIL: 0
SKIPPED: 1

2021-11-10 17:18 UTC, palita1991 requested changes

2021-11-10 17:18 UTC, palita1991 commented on src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
> -            this.servicioIntermedioItems = data[2] || [];
@MarianoCampetella  esta linea fue eliminada por alguna razón?

2021-11-10 18:10 UTC, MarianoCampetella commented on src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
> -            this.servicioIntermedioItems = data[2] || [];
Esa linea fue eliminada porque data[2] siempre daba undefined, y en la linea 49 ya se crea como un arreglo vacío.

2021-11-10 18:21 UTC, palita1991 commented on src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
> -            this.servicioIntermedioItems = data[2] || [];
Habría que ver si tiene repercusión con lo realizado en este PR realizado por @liquid36  https://github.com/andes/app/pull/2431 , ya que esa linea fue agregada en ese momento.

2021-11-11 12:01 UTC, liquid36 requested changes

2021-11-11 12:01 UTC, liquid36 commented on src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
> -            this.servicioIntermedioItems = data[2] || [];
Campe, fijate que ese request es opcional según permisos. Así que no hay que eliminarlo pero si refactorizarlo al indice numero 3. 

https://github.com/andes/app/blob/master/src/app/modules/rup/components/ejecucion/puntoInicio.component.ts#L179

2021-11-11 15:23 UTC, liquid36 commented
![image](https://user-images.githubusercontent.com/3813270/141323587-7e2caf50-8ea1-4e7c-9af1-7c231e9b989b.png)

Probe desde DEMO y si veo la solicitud en ejecución. Aparece como fuera de agenda pero si aparece. Capaz que se podría hacer algún cambio en TOP para que pueda continuar el registro. 

Pero este GET no me parece necesario.

2021-11-25 13:59 UTC, MarianoCampetella commented
@liquid36 EL bug ocurre en la organización "Subsecretaria de Salud" ya que en el Castro Rendom si aparece como lo mostraste anteriormente. De todas formas le agregue la linea que había borrado antes.

2021-11-26 14:37 UTC, liquid36 commented
Como hablamos personalmente estos cambios no son necesarios.  Hay que agregar le botón "Continuar prestación" desde TOP. 

Este bug es un problema de configuración de permisos, no de código.

2021-11-30 13:46 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5543](http://condorpiedra.andes.gob.ar:85/5543/mochawesome.html)
CYPRESS RUN: [4478](https://dashboard.cypress.io/projects/xr7gft/runs/4478/specs)
TEST START: 2021-11-30T13:45:44.908Z
TOTAL: 351
SUCCESS: 337
FAIL: 13
SKIPPED: 1

2021-11-30 14:35 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5544](http://condorpiedra.andes.gob.ar:85/5544/mochawesome.html)
CYPRESS RUN: [4479](https://dashboard.cypress.io/projects/xr7gft/runs/4479/specs)
TEST START: 2021-11-30T14:17:39.863Z
TOTAL: 329
SUCCESS: 276
FAIL: 52
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-11-30 14:38 UTC, liquid36 approved these changes
Excelente!

2021-11-30 15:03 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5546](http://condorpiedra.andes.gob.ar:85/5546/mochawesome.html)
CYPRESS RUN: [4481](https://dashboard.cypress.io/projects/xr7gft/runs/4481/specs)
TEST START: 2021-11-30T15:03:43.815Z
TOTAL: 402
SUCCESS: 401
FAIL: 0
SKIPPED: 1

2021-11-30 15:05 UTC, merged