PER - Actualización de fecha de inicio al cargar un control antiguo a un paciente
andes/app pull request #2522
Opened 2021-11-11 16:47 UTC by MarianoCampetella

…tiguo

### Requerimiento
https://proyectos.andes.gob.ar/browse/PER-63

### Funcionalidad desarrollada 
1.  Se cambio la forma de mostrar los datos de la fecha de inicio

### UserStory llegó a completarse
- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos
- [ ] Si
- [X] No

### Requiere actualizaciones en la API
- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion
- [ ] Si
- [X] No

2021-11-11 17:05 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5475](http://condorpiedra.andes.gob.ar:85/5475/mochawesome.html)
CYPRESS RUN: [4412](https://dashboard.cypress.io/projects/xr7gft/runs/4412/specs)
TEST START: 2021-11-11T17:05:06.270Z
TOTAL: 416
SUCCESS: 415
FAIL: 0
SKIPPED: 1

2021-11-17 16:20 UTC, liquid36 requested changes
Esto se debería actualizar en la base de datos más qe desde la UI, porque va a aparecer el mismo problema en listados, consultas y demás.

2021-11-24 13:32 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5515](http://condorpiedra.andes.gob.ar:85/5515/mochawesome.html)
CYPRESS RUN: [4450](https://dashboard.cypress.io/projects/xr7gft/runs/4450/specs)
TEST START: 2021-11-24T13:31:42.137Z
TOTAL: 287
SUCCESS: 244
FAIL: 42
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-11-24 13:58 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5516](http://condorpiedra.andes.gob.ar:85/5516/mochawesome.html)
CYPRESS RUN: [4451](https://dashboard.cypress.io/projects/xr7gft/runs/4451/specs)
TEST START: 2021-11-24T13:58:16.608Z
TOTAL: 289
SUCCESS: 277
FAIL: 11
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-11-24 14:17 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5517](http://condorpiedra.andes.gob.ar:85/5517/mochawesome.html)
CYPRESS RUN: [4452](https://dashboard.cypress.io/projects/xr7gft/runs/4452/specs)
TEST START: 2021-11-24T14:17:29.942Z
TOTAL: 307
SUCCESS: 295
FAIL: 11
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-11-24 14:50 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5519](http://condorpiedra.andes.gob.ar:85/5519/mochawesome.html)
CYPRESS RUN: [4454](https://dashboard.cypress.io/projects/xr7gft/runs/4454/specs)
TEST START: 2021-11-24T14:50:02.278Z
TOTAL: 334
SUCCESS: 331
FAIL: 2
SKIPPED: 1

2021-11-25 12:20 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5522](http://condorpiedra.andes.gob.ar:85/5522/mochawesome.html)
CYPRESS RUN: [4457](https://dashboard.cypress.io/projects/xr7gft/runs/4457/specs)
TEST START: 2021-11-25T12:16:25.664Z
TOTAL: 105
SUCCESS: 3
FAIL: 102
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-11-26 16:29 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5532](http://condorpiedra.andes.gob.ar:85/5532/mochawesome.html)
CYPRESS RUN: [4467](https://dashboard.cypress.io/projects/xr7gft/runs/4467/specs)
TEST START: 2021-11-26T16:28:58.341Z
TOTAL: 402
SUCCESS: 401
FAIL: 0
SKIPPED: 1

2021-12-03 12:59 UTC, martinebucarey commented
Se cierra porque no tiene cambios

2021-12-03 12:59 UTC, closed without merging