IN - Registro de uso de respirador en colección internacionPacienteResumen
andes/app pull request #2525
Opened 2021-11-15 22:53 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-353
https://proyectos.andes.gob.ar/browse/IN-354

### Funcionalidad desarrollada 

1. Nuevos componentes para registro de asistencia respiratoria y destete de ventilacion mecánica de RUP
2. Visualización de uso de respirador no perteneciente a la cama (En mapa de camas -> detalle de la cama)

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [X] Si (Ver pr de api)
- [ ] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1615
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-11-16 11:51 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5487](http://condorpiedra.andes.gob.ar:85/5487/mochawesome.html)
CYPRESS RUN: [4424](https://dashboard.cypress.io/projects/xr7gft/runs/4424/specs)
TEST START: 2021-11-16T11:51:30.179Z
TOTAL: 358
SUCCESS: 355
FAIL: 2
SKIPPED: 1

2021-11-16 12:46 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5488](http://condorpiedra.andes.gob.ar:85/5488/mochawesome.html)
CYPRESS RUN: [4425](https://dashboard.cypress.io/projects/xr7gft/runs/4425/specs)
TEST START: 2021-11-16T12:46:04.644Z
TOTAL: 416
SUCCESS: 415
FAIL: 0
SKIPPED: 1

2021-11-18 12:56 UTC, liquid36 requested changes
Estuve charlando con Silvina, en ningún momento se pidio crear moléculas para los conceptos. Se registran tal cual están ahora.

2021-12-10 11:26 UTC, negro89 commented
@liquid36 aviso que estas correcciones ya fueron hechas

2022-01-10 12:52 UTC, liquid36 approved these changes

2022-01-10 14:10 UTC, martinebucarey approved these changes

2022-01-10 15:51 UTC, merged