CIT: carga masiva de pacientes
andes/app pull request #2526
Opened 2021-11-18 17:46 UTC by plammel

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-134
### Funcionalidad desarrollada 

1. Permite carga masiva de pacientes por consulta
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2021-11-19 12:43 UTC, martinebucarey requested changes
![imagen](https://user-images.githubusercontent.com/56874534/142624499-ce7e478d-56ac-472e-981c-cb865a6cc733.png)

- Cuando asignas los turnos, queda un disponible medio raro en los turnos
- Por otro lado vamos a validar si con el permiso y que la agenda tenga pacientes simultáneos alcanza para que ya se pueda cargar masivamente. O que pueda llegar a haber agendas sin pacientes simultáneos que también se quieran cargar.

2021-11-19 12:43 UTC, martinebucarey commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts
> +        const puedeCargar = true;
```suggestion
        const puedeCargar = this.auth.getPermissions('turnos:agenda:asignacionMasiva:').length > 0;
```

2021-11-19 12:43 UTC, martinebucarey commented on src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.html
>                          type="default" size="xl" icon="arrow-up"></plex-label>
En la linea 70 ( no me deja agregarlo ) *ngIf="!type" para que no muestre el label cuando mando un type

2021-12-07 13:56 UTC, liquid36 commented on src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
> +        this.agendasSeleccionadas[0].bloques.forEach(b => {
Para analizar, si no hay lugar en la agenda no metería la mitad de los pacientes.  Arrojaría un error. 

Si la agenda es dinámica que pasa?

2021-12-07 14:01 UTC, liquid36 requested changes
Queda pendiente sacar las queries desde los conceptos turneables.

2021-12-07 14:01 UTC, liquid36 commented on src/app/components/turnos/gestor-agendas/gestor-agendas.html
> +                <plex-box *ngIf="enableQueries">
el plex-box esta deprecado.

2021-12-07 14:01 UTC, liquid36 commented on src/app/components/turnos/gestor-agendas/gestor-agendas.html
> +                    <app-bi-queries type="inscriptos-vacunacion">
Esta prohibido meter un `plex-layout` dentro de otro `plex-layout`. Acostumbrense a refactorizar componentes para que sean más reutilizables intramodulos.

2021-12-07 14:01 UTC, liquid36 commented on src/app/components/turnos/gestor-agendas/gestor-agendas.html
> +                    <app-bi-queries type="inscriptos-vacunacion">
La componente de bi-query debería quedar separada en dos. Una es la componente del routing y otra el motor que genera los argumentos dinámicamente.

2021-12-15 12:49 UTC, martinebucarey reviewed
No entiendo la separación de componentes bi, hay dos exactamente iguales y solo cambia la vista que uno llama al otro. Se hace por algo en especial así??

2021-12-15 12:49 UTC, martinebucarey commented on src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
> +    @Input() type;
Teniendo el array de queries, el type seguiría siendo necesario?? yo pensaba controlar lo que se hacia por el type, ahora por el array

2021-12-15 13:35 UTC, plammel commented on src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
> +    @Input() type;
removido el type

2021-12-15 13:41 UTC, martinebucarey requested changes

2021-12-15 13:41 UTC, martinebucarey commented on src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.html
> +            <plex-button *ngIf="!type" size="sm" type="success" (click)="descargar()" [disabled]="form.invalid">
```suggestion
            <plex-button *ngIf="!queries.length" size="sm" type="success" (click)="descargar()" [disabled]="form.invalid">
```

2021-12-15 13:41 UTC, martinebucarey commented on src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.html
> +            <plex-label *ngIf="!type" titulo="Comience seleccionando una consulta" direction="column"
```suggestion
            <plex-label *ngIf="!queries.length" titulo="Comience seleccionando una consulta" direction="column"
```

2021-12-21 14:49 UTC, plammel commented on src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.html
> +            <plex-label *ngIf="!type" titulo="Comience seleccionando una consulta" direction="column"
hecho!

2021-12-22 12:31 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [5704](http://condorpiedra.andes.gob.ar:85/5704/mochawesome.html)
CYPRESS RUN: [4628](https://dashboard.cypress.io/projects/xr7gft/runs/4628/specs)
TEST START: 2021-12-22T12:31:01.332Z
TOTAL: 404
SUCCESS: 401
FAIL: 2
SKIPPED: 1

2021-12-22 18:08 UTC, martinebucarey requested changes

2021-12-22 18:08 UTC, martinebucarey commented on src/app/components/turnos/gestor-agendas/gestor-agendas.html
> +                        <plex-button size="sm" type="danger" (click)="cerrarCargarPacientes()">Cerrara</plex-button>
```suggestion
                        <plex-button size="sm" type="danger" (click)="cerrarCargarPacientes()">Cerrar</plex-button>
```

2021-12-22 18:13 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [5709](http://condorpiedra.andes.gob.ar:85/5709/mochawesome.html)
CYPRESS RUN: [4633](https://dashboard.cypress.io/projects/xr7gft/runs/4633/specs)
TEST START: 2021-12-22T18:01:49.058Z
TOTAL: 404
SUCCESS: 384
FAIL: 19
SKIPPED: 1

2021-12-22 18:43 UTC, martinebucarey requested changes
Revisar que hay casos donde no se estan setenado los id de los pacientes en el turno y por ese motivo se asignan los turnos pero no se muestran en el sidebar

2022-01-03 13:18 UTC, plammel commented
> Revisar que hay casos donde no se estan setenado los id de los pacientes en el turno y por ese motivo se asignan los turnos pero no se muestran en el sidebar

Updeteado!

2022-01-03 13:34 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [5745](http://condorpiedra.andes.gob.ar:85/5745/mochawesome.html)
CYPRESS RUN: [4669](https://dashboard.cypress.io/projects/xr7gft/runs/4669/specs)
TEST START: 2022-01-03T13:33:23.893Z
TOTAL: 382
SUCCESS: 367
FAIL: 14
SKIPPED: 1

2022-01-03 14:37 UTC, martinebucarey commented
> No entiendo la separación de componentes bi, hay dos exactamente iguales y solo cambia la vista que uno llama al otro. Se hace por algo en especial así??

@liquid36

2022-01-06 14:01 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [5776](http://condorpiedra.andes.gob.ar:85/5776/mochawesome.html)
CYPRESS RUN: [4699](https://dashboard.cypress.io/projects/xr7gft/runs/4699/specs)
TEST START: 2022-01-06T14:01:15.914Z
TOTAL: 404
SUCCESS: 401
FAIL: 2
SKIPPED: 1

2022-01-07 12:19 UTC, martinebucarey commented
Por alguna razon esta guardando vacio el array de queries cuando creo la agenda, adjunto las imagenes de lo que tiene la agenda y como esta en la base el concepto, lo probe en demo y local y me pasa lo mismo

![imagen](https://user-images.githubusercontent.com/56874534/148543088-5346b719-ffd0-4673-bec0-5a8926e0e06e.png)
![imagen](https://user-images.githubusercontent.com/56874534/148543131-5cc61819-04bd-4b87-b0d6-a08ce07d11e0.png)

2022-02-15 15:08 UTC, plammel commented
> Por alguna razon esta guardando vacio el array de queries cuando creo la agenda, adjunto las imagenes de lo que tiene la agenda y como esta en la base el concepto, lo probe en demo y local y me pasa lo mismo
> 
> ![imagen](https://user-images.githubusercontent.com/56874534/148543088-5346b719-ffd0-4673-bec0-5a8926e0e06e.png) ![imagen](https://user-images.githubusercontent.com/56874534/148543131-5cc61819-04bd-4b87-b0d6-a08ce07d11e0.png)

updated!

2022-02-15 17:11 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [5931](http://condorpiedra.andes.gob.ar:85/5931/mochawesome.html)
CYPRESS RUN: [4848](https://dashboard.cypress.io/projects/xr7gft/runs/4848/specs)
TEST START: 2022-02-15T17:11:09.922Z
TOTAL: 404
SUCCESS: 402
FAIL: 1
SKIPPED: 1

2022-02-15 17:20 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [5932](http://condorpiedra.andes.gob.ar:85/5932/mochawesome.html)
CYPRESS RUN: [4849](https://dashboard.cypress.io/projects/xr7gft/runs/4849/specs)
TEST START: 2022-02-15T17:20:46.572Z
TOTAL: 404
SUCCESS: 402
FAIL: 1
SKIPPED: 1

2022-02-17 16:03 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [5941](http://condorpiedra.andes.gob.ar:85/5941/mochawesome.html)
CYPRESS RUN: [4858](https://dashboard.cypress.io/projects/xr7gft/runs/4858/specs)
TEST START: 2022-02-17T16:03:17.174Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

2022-02-17 16:50 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [5942](http://condorpiedra.andes.gob.ar:85/5942/mochawesome.html)
CYPRESS RUN: [4859](https://dashboard.cypress.io/projects/xr7gft/runs/4859/specs)
TEST START: 2022-02-17T16:49:59.340Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-02-17 16:52 UTC, merged