TM: refactor pantalla organizaciones
andes/app pull request #2528
Opened 2021-11-19 17:04 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/TM-16

### Funcionalidad desarrollada 
1. Refactor de pantalla de tablas maestras organizaciones

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-12-03 12:57 UTC, martinebucarey commented on src/app/components/organizacion/organizacion.html
>          <header>
Eliminar la etiqueta header así queda el titulo como en toda la app.
![imagen](https://user-images.githubusercontent.com/56874534/144606276-c9eb310d-ef2f-4e6f-bec9-d80509987a83.png)

2021-12-03 18:41 UTC, plammel approved these changes

2021-12-06 16:02 UTC, liquid36 requested changes

2021-12-07 18:00 UTC, juuliotero commented on src/app/components/organizacion/organizacion-create-update.html
> +                <div class="w-100" *ngFor="let unidadOrganizativa of organizacionModel.unidadesOrganizativas; let i = index"
listo

2021-12-07 18:21 UTC, liquid36 commented on src/app/components/organizacion/organizacion-create-update.html
> +                <div class="w-100" *ngFor="let unidadOrganizativa of organizacionModel.unidadesOrganizativas; let i = index"
sigue estando como divs (?)

2021-12-13 18:45 UTC, liquid36 approved these changes

2021-12-14 11:26 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5608](http://condorpiedra.andes.gob.ar:85/5608/mochawesome.html)
CYPRESS RUN: [4543](https://dashboard.cypress.io/projects/xr7gft/runs/4543/specs)
TEST START: 2021-12-14T11:25:51.840Z
TOTAL: 402
SUCCESS: 401
FAIL: 0
SKIPPED: 1

2021-12-14 11:27 UTC, merged