MISC: refactor de pantalla de padrones
andes/app pull request #2530
Opened 2021-11-24 18:16 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/MISC-205

### Funcionalidad desarrollada 
1. Refactor plex de pantalla de padrones

### UserStory llegó a completarse

- [X] Si https://proyectos.andes.gob.ar/browse/MISC-205
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-11-25 15:22 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [5524](http://condorpiedra.andes.gob.ar:85/5524/mochawesome.html)
CYPRESS RUN: [4459](https://dashboard.cypress.io/projects/xr7gft/runs/4459/specs)
TEST START: 2021-11-25T15:21:35.365Z
TOTAL: 402
SUCCESS: 398
FAIL: 3
SKIPPED: 1

2021-11-25 15:41 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [5526](http://condorpiedra.andes.gob.ar:85/5526/mochawesome.html)
CYPRESS RUN: [4461](https://dashboard.cypress.io/projects/xr7gft/runs/4461/specs)
TEST START: 2021-11-25T15:40:44.835Z
TOTAL: 402
SUCCESS: 398
FAIL: 3
SKIPPED: 1

2021-11-26 12:38 UTC, liquid36 requested changes

2021-11-26 12:38 UTC, liquid36 commented on src/app/components/puco/puco.html
> +            <plex-text type="number" [(ngModel)]="searchTerm" name="searchTerm" (change)="buscar()"
Si solo acepta numeros debería ser un plex-int:

```suggestion
            <plex-int [(ngModel)]="searchTerm" name="searchTerm" (change)="buscar()"
```

2021-11-30 14:22 UTC, liquid36 requested changes
```
error-handler.service.ts:50 TypeError: this.searchTerm.trim is not a function
    at PucoComponent.buscar (puco.component.ts:176)
    at PucoComponent_plex_layout_0_Template_plex_int_change_4_listener (template.html:5)
    at executeListenerWithErrorHandling (core.js:21819)
    at wrapListenerIn_markDirtyAndPreventDefault (core.js:21861)
    at SafeSubscriber.schedulerFn [as _next] (core.js:37184)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183)
    at SafeSubscriber.next (Subscriber.js:122)
    at Subscriber._next (Subscriber.js:72)
    at Subscriber.next (Subscriber.js:49)
    at EventEmitter.next (Subject.js:39)
```

Hay un error ahora, sucede que el plex-int devuelve un enetero y no un string.

2021-11-30 14:50 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5545](http://condorpiedra.andes.gob.ar:85/5545/mochawesome.html)
CYPRESS RUN: [4480](https://dashboard.cypress.io/projects/xr7gft/runs/4480/specs)
TEST START: 2021-11-30T14:48:58.194Z
TOTAL: 402
SUCCESS: 398
FAIL: 3
SKIPPED: 1

2021-11-30 14:52 UTC, liquid36 commented
Los test se ve que no andan por eso

2021-12-02 18:21 UTC, juuliotero commented
> ```
> error-handler.service.ts:50 TypeError: this.searchTerm.trim is not a function
>     at PucoComponent.buscar (puco.component.ts:176)
>     at PucoComponent_plex_layout_0_Template_plex_int_change_4_listener (template.html:5)
>     at executeListenerWithErrorHandling (core.js:21819)
>     at wrapListenerIn_markDirtyAndPreventDefault (core.js:21861)
>     at SafeSubscriber.schedulerFn [as _next] (core.js:37184)
>     at SafeSubscriber.__tryOrUnsub (Subscriber.js:183)
>     at SafeSubscriber.next (Subscriber.js:122)
>     at Subscriber._next (Subscriber.js:72)
>     at Subscriber.next (Subscriber.js:49)
>     at EventEmitter.next (Subject.js:39)
> ```
> 
> Hay un error ahora, sucede que el plex-int devuelve un enetero y no un string.

corregido

2021-12-02 18:34 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [5561](http://condorpiedra.andes.gob.ar:85/5561/mochawesome.html)
CYPRESS RUN: [4496](https://dashboard.cypress.io/projects/xr7gft/runs/4496/specs)
TEST START: 2021-12-02T18:33:58.147Z
TOTAL: 402
SUCCESS: 401
FAIL: 0
SKIPPED: 1

2021-12-03 11:29 UTC, liquid36 approved these changes

2021-12-03 11:37 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5563](http://condorpiedra.andes.gob.ar:85/5563/mochawesome.html)
CYPRESS RUN: [4498](https://dashboard.cypress.io/projects/xr7gft/runs/4498/specs)
TEST START: 2021-12-03T11:36:44.987Z
TOTAL: 402
SUCCESS: 396
FAIL: 5
SKIPPED: 1

2021-12-03 11:45 UTC, merged