TOP (Fix) - Eliminación de ultima regla
andes/app pull request #2537
Opened 2021-11-29 21:33 UTC by negro89

se actualiza además el uso de componentes plex en el template

### Requerimiento
https://proyectos.andes.gob.ar/browse/TOP-121

### Funcionalidad desarrollada 

1. Actualiza uso de componentes plex
2. Refactor para eliminación de organización de origen (con todas sus reglas) o todas las prestaciones origen de una organizacion

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-11-29 21:46 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5540](http://condorpiedra.andes.gob.ar:85/5540/mochawesome.html)
CYPRESS RUN: [4475](https://dashboard.cypress.io/projects/xr7gft/runs/4475/specs)
TEST START: 2021-11-29T21:46:20.731Z
TOTAL: 402
SUCCESS: 401
FAIL: 0
SKIPPED: 1

2021-11-30 12:28 UTC, liquid36 requested changes
![image](https://user-images.githubusercontent.com/3813270/144047278-e39cf46e-aede-4b04-9120-e8d214da3fd9.png)

Cuando la regla queda sin organizaciones destino no me avisa que se va a borrar todo.

2021-11-30 12:28 UTC, liquid36 commented on src/app/components/top/reglas/reglas.component.ts
>              if (this.reglaCorrecta) {
Estaría bueno acomodar el código,  verificarRegla debería devolver un booleano en vez de asignar una variable para su posterior uso. Ver todos los lugares donde se usa. 

```suggestion
            if (this.verificarRegla()) {
```

2021-11-30 12:28 UTC, liquid36 commented on src/app/components/top/reglas/reglas.component.html
> +                <plex-grid cols="2" size="sm" justify="around" class="mt-0 pt-0">
`plex-grid` no va a dentro de un `plex-item`. Qué problema tuviste?

2021-12-07 12:35 UTC, negro89 commented on src/app/components/top/reglas/reglas.component.html
> +                <plex-grid cols="2" size="sm" justify="around" class="mt-0 pt-0">
La dificultad fue para alinear el contenido dentro del item (El checkbox queda forzadamente al principo y el label alineado al principio. Ver imagen). El grid fue lo único que me resultó.
![image](https://user-images.githubusercontent.com/37875706/145029987-cd6933e7-0c34-4095-b5e3-2ca730b10a08.png)

2021-12-07 12:39 UTC, liquid36 commented on src/app/components/top/reglas/reglas.component.html
> +                <plex-grid cols="2" size="sm" justify="around" class="mt-0 pt-0">
Podes usar un `ngProjectAs="plex-label"`  para acomodarlo segundo. Fuera de ese truco estaría bueno saber que opina @andrrrl @AgosLizzi

2021-12-07 13:43 UTC, andrrrl commented on src/app/components/top/reglas/reglas.component.html
> +                <plex-grid cols="2" size="sm" justify="around" class="mt-0 pt-0">
Coincido con @liquid36! Adjunto snippet para que el contenido del item quede alineado y el título de la prestación capitalizado:
```html
<plex-item case="capitalize">
                <plex-label *ngIf="prestacion.prestacion?.term" titulo="{{ prestacion.prestacion.term }}"
                    [tituloBold]="false" subtitulo=""></plex-label>
                <plex-bool ngProjectAs="plex-label" [(ngModel)]="prestacion.auditable" name="prestacionAuditable{{i}}"
                    label="Auditable" class="mb-1">
                </plex-bool>
                <plex-button icon="delete" type="danger" size="sm" (click)="deletePrestacion(i)">
                </plex-button>
</plex-item>
```

2021-12-07 14:21 UTC, negro89 commented on src/app/components/top/reglas/reglas.component.html
> +                <plex-grid cols="2" size="sm" justify="around" class="mt-0 pt-0">
Excelenteee. Corregido!
@liquid36 se agregó también un control/aviso para cuando se borraron las reglas existentes (No hay organización origen).

2021-12-07 14:52 UTC, liquid36 commented on src/app/components/top/reglas/reglas.component.ts
> +            if (this.reglaCorrecta()) {
Esta arrojando esta regla al querer guardar una regla.

```
TypeError: this.reglaCorrecta is not a function
    at ReglasComponent.save (reglas.component.ts:175)
    at ReglasComponent.preSave (reglas.component.ts:169)
    at ReglasComponent_Template_plex_button_click_18_listener (template.html:65)
    at executeListenerWithErrorHandling (core.js:21819)
    at wrapListenerIn_markDirtyAndPreventDefault (core.js:21868)
    at HTMLElement.<anonymous> (platform-browser.js:976)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41645)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
```

2021-12-07 15:45 UTC, negro89 commented on src/app/components/top/reglas/reglas.component.ts
> +            if (this.reglaCorrecta()) {
Corregido

2021-12-09 14:36 UTC, liquid36 approved these changes

2021-12-09 15:43 UTC, merged