IN: completar informe desde capa carga
andes/app pull request #2539
Opened 2021-12-02 13:31 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-351

### Funcionalidad desarrollada 
1. Permitir finalizar le ingreso de un paciente desde la capa carga

### UserStory llegó a completarse

- [ ] Si
- [X] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si 
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-12-23 16:10 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [5719](http://condorpiedra.andes.gob.ar:85/5719/mochawesome.html)
CYPRESS RUN: [4643](https://dashboard.cypress.io/projects/xr7gft/runs/4643/specs)
TEST START: 2021-12-23T16:10:28.105Z
TOTAL: 404
SUCCESS: 400
FAIL: 3
SKIPPED: 1

2021-12-27 14:17 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [5732](http://condorpiedra.andes.gob.ar:85/5732/mochawesome.html)
CYPRESS RUN: [4656](https://dashboard.cypress.io/projects/xr7gft/runs/4656/specs)
TEST START: 2021-12-27T14:16:57.614Z
TOTAL: 404
SUCCESS: 400
FAIL: 3
SKIPPED: 1

2022-01-03 15:38 UTC, liquid36 commented on src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
> +            return this.camasHTTP.save(this.ambito, capaSave, fecha, data);
esta modificación no es necesaria, ya la resuelve el backend.

2022-01-03 15:38 UTC, liquid36 commented on src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
> +        this.servicioPrestacion.post(nuevaPrestacion).subscribe((prestacion) => {
Se podría refactorizar este código que lo están duplicando.

2022-01-03 15:38 UTC, liquid36 commented
van primeros comentarios

2022-01-04 12:59 UTC, liquid36 commented on src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
> +                        return this.internacionResumenHTTP.get(idInternacion).pipe(
ya existe un observable en el servicio que trae y cachea el resumen: _resumenInternacion$_

2022-01-04 13:04 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5759](http://condorpiedra.andes.gob.ar:85/5759/mochawesome.html)
CYPRESS RUN: [4683](https://dashboard.cypress.io/projects/xr7gft/runs/4683/specs)
TEST START: 2022-01-04T13:01:49.103Z
TOTAL: 404
SUCCESS: 393
FAIL: 10
SKIPPED: 1

2022-01-04 17:51 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [5763](http://condorpiedra.andes.gob.ar:85/5763/mochawesome.html)
CYPRESS RUN: [4686](https://dashboard.cypress.io/projects/xr7gft/runs/4686/specs)
TEST START: 2022-01-04T17:51:36.108Z
TOTAL: 404
SUCCESS: 403
FAIL: 0
SKIPPED: 1

2022-01-05 14:43 UTC, negro89 approved these changes

2022-01-05 18:25 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [5770](http://condorpiedra.andes.gob.ar:85/5770/mochawesome.html)
CYPRESS RUN: [4693](https://dashboard.cypress.io/projects/xr7gft/runs/4693/specs)
TEST START: 2022-01-05T18:25:02.602Z
TOTAL: 404
SUCCESS: 403
FAIL: 0
SKIPPED: 1

2022-01-13 15:19 UTC, liquid36 requested changes
- Al completar la primera vez el informe de ingreso se busca la prestación con undefined. (No debería buscarse)

- Listado Internación:
  - No veo ingreso
  - Error en consola

![image](https://user-images.githubusercontent.com/3813270/149356851-38cdbed7-a743-45ea-b7e1-e86f374ee1f3.png)
![image](https://user-images.githubusercontent.com/3813270/149356851-38cdbed7-a743-45ea-b7e1-e86f374ee1f3.png)


- Egreso: 
  -  Días de estada no se visualizan
  - Cuando el medico egresa el paciente, desde el listado de internación no se ve la fecha de egreso al editar el informe de egreso. 

- Censo no anda, siempre me muestra cero personas internadas.

2022-01-13 15:19 UTC, liquid36 commented on src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
> +                <plex-button *ngIf="(puedeVerListado$ | async) && (mapaCamasService.capa === 'estadistica' || mapaCamasService.capa === 'estadistica-v2')"
Si cambiamos a configuración por estado, los otros if no son necesarios.

2022-01-14 11:36 UTC, liquid36 commented
También chequear el anular internaciones.

2022-02-01 11:43 UTC, liquid36 commented on src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
> +        this.resumenDesdePrestacion$ = this.selectedPrestacion.pipe(
En el caso de venir desde el mapa de cama, el resumen ya esta en memoría. El úni problema es desde el listado de internación. Eliminaría esta variable y refactorizaría la otra _resumenInternacion$_ para que sepa si esta en mapa de camas o listado internación.

2022-02-10 15:07 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5906](http://condorpiedra.andes.gob.ar:85/5906/mochawesome.html)
CYPRESS RUN: [4824](https://dashboard.cypress.io/projects/xr7gft/runs/4824/specs)
TEST START: 2022-02-10T15:07:39.968Z
TOTAL: 407
SUCCESS: 403
FAIL: 3
SKIPPED: 1

2022-02-10 15:23 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5907](http://condorpiedra.andes.gob.ar:85/5907/mochawesome.html)
CYPRESS RUN: [4825](https://dashboard.cypress.io/projects/xr7gft/runs/4825/specs)
TEST START: 2022-02-10T15:23:30.697Z
TOTAL: 407
SUCCESS: 404
FAIL: 2
SKIPPED: 1

2022-02-15 11:26 UTC, liquid36 requested changes
1. Cuando completo el informe de ingreso se me esta duplicando el paciente: 

![image](https://user-images.githubusercontent.com/3813270/154053007-805656d2-3ce0-44c0-881b-c496bb0d719e.png)

2022-02-15 11:32 UTC, liquid36 requested changes
en la capa médica esta apareciendo el botón de "convertir a censable".

![image](https://user-images.githubusercontent.com/3813270/154054026-391c9f7c-4dbe-48d2-9e17-c988de64e95b.png)

2022-02-15 11:42 UTC, liquid36 requested changes
![image](https://user-images.githubusercontent.com/3813270/154055351-316a4a30-d963-43dd-88a2-757fada11262.png)

Al seleccionar una cama, se esta realizando dos veces un GET al resumen de internación.

2022-02-16 14:29 UTC, liquid36 submitted a review, later dismissed
![image](https://user-images.githubusercontent.com/3813270/154285576-8c250829-3bbc-4cad-bf28-3a9ad54274e3.png)
No se previsualizan todos los datos del informe de ingreso.

2022-02-16 19:14 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5937](http://condorpiedra.andes.gob.ar:85/5937/mochawesome.html)
CYPRESS RUN: [4854](https://dashboard.cypress.io/projects/xr7gft/runs/4854/specs)
TEST START: 2022-02-16T19:14:44.750Z
TOTAL: 407
SUCCESS: 401
FAIL: 5
SKIPPED: 1

2022-02-17 18:35 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5946](http://condorpiedra.andes.gob.ar:85/5946/mochawesome.html)
CYPRESS RUN: [4863](https://dashboard.cypress.io/projects/xr7gft/runs/4863/specs)
TEST START: 2022-02-17T18:34:23.557Z
TOTAL: 363
SUCCESS: 349
FAIL: 13
SKIPPED: 1

2022-02-17 18:49 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5947](http://condorpiedra.andes.gob.ar:85/5947/mochawesome.html)
CYPRESS RUN: [4864](https://dashboard.cypress.io/projects/xr7gft/runs/4864/specs)
TEST START: 2022-02-17T18:48:51.259Z
TOTAL: 401
SUCCESS: 398
FAIL: 2
SKIPPED: 1

2022-02-17 19:02 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5948](http://condorpiedra.andes.gob.ar:85/5948/mochawesome.html)
CYPRESS RUN: [4865](https://dashboard.cypress.io/projects/xr7gft/runs/4865/specs)
TEST START: 2022-02-17T19:02:20.016Z
TOTAL: 409
SUCCESS: 407
FAIL: 1
SKIPPED: 1

2022-02-18 11:53 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5950](http://condorpiedra.andes.gob.ar:85/5950/mochawesome.html)
CYPRESS RUN: [4867](https://dashboard.cypress.io/projects/xr7gft/runs/4867/specs)
TEST START: 2022-02-18T11:53:24.387Z
TOTAL: 391
SUCCESS: 379
FAIL: 11
SKIPPED: 1

2022-02-18 12:14 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5951](http://condorpiedra.andes.gob.ar:85/5951/mochawesome.html)
CYPRESS RUN: [4868](https://dashboard.cypress.io/projects/xr7gft/runs/4868/specs)
TEST START: 2022-02-18T12:14:38.074Z
TOTAL: 409
SUCCESS: 408
FAIL: 0
SKIPPED: 1

2022-02-24 12:56 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [5987](http://condorpiedra.andes.gob.ar:85/5987/mochawesome.html)
CYPRESS RUN: [4902](https://dashboard.cypress.io/projects/xr7gft/runs/4902/specs)
TEST START: 2022-02-24T12:39:52.478Z
TOTAL: 380
SUCCESS: 340
FAIL: 39
SKIPPED: 1

2022-02-24 14:06 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [5989](http://condorpiedra.andes.gob.ar:85/5989/mochawesome.html)
CYPRESS RUN: [4904](https://dashboard.cypress.io/projects/xr7gft/runs/4904/specs)
TEST START: 2022-02-24T14:06:12.641Z
TOTAL: 409
SUCCESS: 408
FAIL: 0
SKIPPED: 1

2022-02-25 12:19 UTC, waltergarrido approved these changes

2022-03-07 18:00 UTC, martinebucarey commented
USUARIO: wgarrido  
BUILD NUMBER: [6036](http://condorpiedra.andes.gob.ar:85/6036/mochawesome.html)
CYPRESS RUN: [4947](https://dashboard.cypress.io/projects/xr7gft/runs/4947/specs)
TEST START: 2022-03-07T18:00:39.403Z
TOTAL: 409
SUCCESS: 398
FAIL: 10
SKIPPED: 1

2022-03-21 14:06 UTC, MCele commented
Desde el mapa de camas, en un efector que aún no utiliza la fusion de capas, cuando se observa en el sidebar la solapa "Ingreso" no se visualiza información (capa medica o enfermería)
![image](https://user-images.githubusercontent.com/19591224/159277455-3c78660b-0c57-49c4-90ce-829ea13d7619.png)

2022-06-08 14:50 UTC, merged