MISC - Visualización de las matriculas de un profesional
andes/app pull request #2540
Opened 2021-12-02 14:31 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MISC-203

### Funcionalidad desarrollada 

1. Se muestra un detalle del profesional que se encuentra logueado con la información de sus profesiones. En caso de no estar logueado no se muestra nada de lo dicho anteriormente. 

### UserStory llegó a completarse
- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos
- [ ] Si
- [X] No

### Requiere actualizaciones en la API
- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion
- [ ] Si
- [X] No

2021-12-02 14:59 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5558](http://condorpiedra.andes.gob.ar:85/5558/mochawesome.html)
CYPRESS RUN: [4493](https://dashboard.cypress.io/projects/xr7gft/runs/4493/specs)
TEST START: 2021-12-02T14:58:37.699Z
TOTAL: 320
SUCCESS: 267
FAIL: 52
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-12-02 15:29 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5560](http://condorpiedra.andes.gob.ar:85/5560/mochawesome.html)
CYPRESS RUN: [4495](https://dashboard.cypress.io/projects/xr7gft/runs/4495/specs)
TEST START: 2021-12-02T15:29:15.202Z
TOTAL: 402
SUCCESS: 360
FAIL: 41
SKIPPED: 1

2021-12-02 15:58 UTC, liquid36 requested changes

2021-12-03 12:34 UTC, MarianoCampetella commented on src/app/app.component.ts
> +                    this.formacionGrado = profesional[0].formacionGrado;
Corregido!

2021-12-03 12:34 UTC, MarianoCampetella commented on src/app/app.component.ts
> +                    this.profesional = profesional;
Ordenado!

2021-12-03 12:35 UTC, MarianoCampetella commented on src/app/app.component.html
> +    <div *ngIf="profesional" class="user-profile">
![captura](https://user-images.githubusercontent.com/65697028/144603483-d0a43bbe-4f7d-4d79-9da0-0cd14d7cbb92.png)

2021-12-03 12:43 UTC, martinebucarey commented on src/app/app.component.html
> +    <div *ngIf="profesional" class="user-profile">
Para la próxima, cuando se hace algún cambio en alguna dependencia, en este caso plex, por ahí para entenderlo mas rápido conviene o subir el package con la dependencia actualizada o aclarar en la descripción del PR que se utiliza tal versión de la librería.

2021-12-03 12:51 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5567](http://condorpiedra.andes.gob.ar:85/5567/mochawesome.html)
CYPRESS RUN: [4502](https://dashboard.cypress.io/projects/xr7gft/runs/4502/specs)
TEST START: 2021-12-03T12:51:42.065Z
TOTAL: 402
SUCCESS: 382
FAIL: 19
SKIPPED: 1

2021-12-03 14:36 UTC, liquid36 commented on src/app/app.component.html
> +    <div *ngIf="profesional" class="user-profile">
Claro, hay que actualizar plex y pushear el package.

2021-12-07 13:10 UTC, liquid36 commented on src/app/app.component.html
> +        <plex-title titulo="Matrículas" size="sm"></plex-title>
Si el usuario no es profesional o no tiene matriculas estaría bueno ocultar toda la tabla.

2021-12-07 13:12 UTC, liquid36 commented on src/app/app.component.ts
> +                        this.profesional = profesional;
Están repetidas las lineas.

2021-12-07 13:14 UTC, liquid36 requested changes

2021-12-09 12:47 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5584](http://condorpiedra.andes.gob.ar:85/5584/mochawesome.html)
CYPRESS RUN: [4519](https://dashboard.cypress.io/projects/xr7gft/runs/4519/specs)
TEST START: 2021-12-09T12:46:14.177Z
TOTAL: 402
SUCCESS: 378
FAIL: 23
SKIPPED: 1

2021-12-09 13:40 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5585](http://condorpiedra.andes.gob.ar:85/5585/mochawesome.html)
CYPRESS RUN: [4520](https://dashboard.cypress.io/projects/xr7gft/runs/4520/specs)
TEST START: 2021-12-09T13:40:31.437Z
TOTAL: 402
SUCCESS: 389
FAIL: 12
SKIPPED: 1

2021-12-10 12:34 UTC, martinebucarey commented on src/app/app.component.html
> +        <plex-title titulo="Matrículas" size="sm"></plex-title>
Si queda medio fiero
![imagen](https://user-images.githubusercontent.com/56874534/145574863-2fa8ce5b-53aa-4218-8fbe-f1188b3f9f35.png)

2021-12-13 18:38 UTC, liquid36 approved these changes

2021-12-13 18:46 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5604](http://condorpiedra.andes.gob.ar:85/5604/mochawesome.html)
CYPRESS RUN: [4539](https://dashboard.cypress.io/projects/xr7gft/runs/4539/specs)
TEST START: 2021-12-13T18:45:47.013Z
TOTAL: 402
SUCCESS: 389
FAIL: 12
SKIPPED: 1

2021-12-13 19:11 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5606](http://condorpiedra.andes.gob.ar:85/5606/mochawesome.html)
CYPRESS RUN: [4541](https://dashboard.cypress.io/projects/xr7gft/runs/4541/specs)
TEST START: 2021-12-13T19:11:09.526Z
TOTAL: 402
SUCCESS: 378
FAIL: 23
SKIPPED: 1

2021-12-14 11:42 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5609](http://condorpiedra.andes.gob.ar:85/5609/mochawesome.html)
CYPRESS RUN: [4544](https://dashboard.cypress.io/projects/xr7gft/runs/4544/specs)
TEST START: 2021-12-14T11:41:57.630Z
TOTAL: 402
SUCCESS: 388
FAIL: 13
SKIPPED: 1

2021-12-14 12:10 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5611](http://condorpiedra.andes.gob.ar:85/5611/mochawesome.html)
CYPRESS RUN: [4546](https://dashboard.cypress.io/projects/xr7gft/runs/4546/specs)
TEST START: 2021-12-14T12:09:57.411Z
TOTAL: 287
SUCCESS: 265
FAIL: 21
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-12-14 12:43 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5613](http://condorpiedra.andes.gob.ar:85/5613/mochawesome.html)
CYPRESS RUN: [4548](https://dashboard.cypress.io/projects/xr7gft/runs/4548/specs)
TEST START: 2021-12-14T12:43:00.680Z
TOTAL: 400
SUCCESS: 389
FAIL: 10
SKIPPED: 1

2021-12-14 13:48 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5618](http://condorpiedra.andes.gob.ar:85/5618/mochawesome.html)
CYPRESS RUN: [4553](https://dashboard.cypress.io/projects/xr7gft/runs/4553/specs)
TEST START: 2021-12-14T13:48:07.475Z
TOTAL: 340
SUCCESS: 317
FAIL: 22
SKIPPED: 1

2021-12-14 14:05 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5619](http://condorpiedra.andes.gob.ar:85/5619/mochawesome.html)
CYPRESS RUN: [4554](https://dashboard.cypress.io/projects/xr7gft/runs/4554/specs)
TEST START: 2021-12-14T14:05:27.629Z
TOTAL: 400
SUCCESS: 388
FAIL: 11
SKIPPED: 1

2021-12-14 14:20 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5620](http://condorpiedra.andes.gob.ar:85/5620/mochawesome.html)
CYPRESS RUN: [4555](https://dashboard.cypress.io/projects/xr7gft/runs/4555/specs)
TEST START: 2021-12-14T14:20:15.586Z
TOTAL: 400
SUCCESS: 389
FAIL: 10
SKIPPED: 1

2021-12-14 14:41 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5621](http://condorpiedra.andes.gob.ar:85/5621/mochawesome.html)
CYPRESS RUN: [4556](https://dashboard.cypress.io/projects/xr7gft/runs/4556/specs)
TEST START: 2021-12-14T14:31:02.013Z
TOTAL: 350
SUCCESS: 78
FAIL: 271
SKIPPED: 1

2021-12-14 15:00 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5623](http://condorpiedra.andes.gob.ar:85/5623/mochawesome.html)
CYPRESS RUN: [4557](https://dashboard.cypress.io/projects/xr7gft/runs/4557/specs)
TEST START: 2021-12-14T15:00:43.666Z
TOTAL: 402
SUCCESS: 398
FAIL: 3
SKIPPED: 1

2021-12-14 15:35 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5626](http://condorpiedra.andes.gob.ar:85/5626/mochawesome.html)
CYPRESS RUN: [4559](https://dashboard.cypress.io/projects/xr7gft/runs/4559/specs)
TEST START: 2021-12-14T15:25:57.405Z
TOTAL: 350
SUCCESS: 336
FAIL: 13
SKIPPED: 1

2021-12-14 16:21 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5630](http://condorpiedra.andes.gob.ar:85/5630/mochawesome.html)
CYPRESS RUN: [4563](https://dashboard.cypress.io/projects/xr7gft/runs/4563/specs)
TEST START: 2021-12-14T16:21:06.444Z
TOTAL: 402
SUCCESS: 398
FAIL: 3
SKIPPED: 1

2021-12-14 17:57 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5633](http://condorpiedra.andes.gob.ar:85/5633/mochawesome.html)
CYPRESS RUN: [4566](https://dashboard.cypress.io/projects/xr7gft/runs/4566/specs)
TEST START: 2021-12-14T17:56:51.170Z
TOTAL: 402
SUCCESS: 399
FAIL: 2
SKIPPED: 1

2021-12-15 11:40 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5635](http://condorpiedra.andes.gob.ar:85/5635/mochawesome.html)
CYPRESS RUN: [4568](https://dashboard.cypress.io/projects/xr7gft/runs/4568/specs)
TEST START: 2021-12-15T11:39:48.995Z
TOTAL: 402
SUCCESS: 397
FAIL: 4
SKIPPED: 1

2021-12-15 13:07 UTC, merged