CIT: dar sobreturno desde punto inicio
andes/app pull request #2541
Opened 2021-12-03 13:16 UTC by plammel

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-148
### Funcionalidad desarrollada 

1. 
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si https://github.com/andes/api/pull/1623
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2021-12-10 13:10 UTC, martinebucarey commented
Funcionamiento joya, resta mockup de @andrrrl @AgosLizzi para lo visual

2021-12-16 17:31 UTC, liquid36 requested changes
cuando quiero dar un sobreturno desde el gestor me aparece el siguiente error: 

![image](https://user-images.githubusercontent.com/3813270/146420261-59f9177f-0344-4434-871a-4d71785e709a.png)

2021-12-16 17:31 UTC, liquid36 requested changes

2021-12-16 17:31 UTC, liquid36 commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.component.ts
> +                    this.servicePaciente.getById(params.paciente).subscribe(res => {
no se controla si no viene el paciente.

2021-12-21 14:34 UTC, plammel commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.component.ts
> +                    this.servicePaciente.getById(params.paciente).subscribe(res => {
fixed!

2021-12-21 14:49 UTC, liquid36 commented
![image](https://user-images.githubusercontent.com/3813270/146949344-d9d880d7-a54b-4d1b-a41f-2614a31ddd68.png)

cuando doy sobreturno desde el punto de inicio de CITAS, no me aparece para elegir las obra sociales. No aparecen los plex-radio correspondiente.

2021-12-21 19:01 UTC, plammel commented
> ![image](https://user-images.githubusercontent.com/3813270/146949344-d9d880d7-a54b-4d1b-a41f-2614a31ddd68.png)
> 
> cuando doy sobreturno desde el punto de inicio de CITAS, no me aparece para elegir las obra sociales. No aparecen los plex-radio correspondiente.

fixed!

2021-12-22 11:25 UTC, martinebucarey approved these changes

2021-12-22 12:17 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [5703](http://condorpiedra.andes.gob.ar:85/5703/mochawesome.html)
CYPRESS RUN: [4627](https://dashboard.cypress.io/projects/xr7gft/runs/4627/specs)
TEST START: 2021-12-22T12:16:57.184Z
TOTAL: 404
SUCCESS: 402
FAIL: 1
SKIPPED: 1

2021-12-22 12:47 UTC, liquid36 approved these changes

2021-12-22 13:23 UTC, merged