CIT: refactor visual header dar turno
andes/app pull request #2543
Opened 2021-12-07 15:47 UTC by plammel

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-150
### Funcionalidad desarrollada 

1. 
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2021-12-07 17:18 UTC, andrrrl requested changes
Eso nomás!

2021-12-07 17:18 UTC, andrrrl commented on src/app/components/turnos/dar-turnos/dar-turnos.html
> +                </plex-bool>
Por defecto se muestran sábados y domingos, por tanto debería estar activado por defecto ese `plex-bool`.

2021-12-07 17:23 UTC, andrrrl commented
En `calendaario.scss` cambiá esta parte si sos tan amable: 
```scss
// Cells
    td {
        padding: 0.75rem;
        vertical-align: top;
        max-width: 40px;
        max-height: 40px;
        small {
            display: block;
            height: 0;
        }
    }
```
Hace que las celdas que tienen agenda no sean más altas que las demás. Queda más ordenado todo y evita que se genere scroll.

2021-12-07 19:03 UTC, plammel commented
> En `calendaario.scss` cambiá esta parte si sos tan amable:
> 
> ```css-scss
> // Cells
>     td {
>         padding: 0.75rem;
>         vertical-align: top;
>         max-width: 40px;
>         max-height: 40px;
>         small {
>             display: block;
>             height: 0;
>         }
>     }
> ```
> 
> Hace que las celdas que tienen agenda no sean más altas que las demás. Queda más ordenado todo y evita que se genere scroll.

Listo los cambios! Aplique los estilos pero no surtieron efecto :(

2021-12-09 11:28 UTC, liquid36 requested changes

2021-12-09 11:28 UTC, liquid36 commented on src/app/components/turnos/dar-turnos/dar-turnos.html
> +<plex-layout main="8">
La pantalla de dar turno se usa como componente incrustada en otras componentes (futuro refactor). 
Esta mal que tenga un `plex-layout` adentro.

2021-12-09 11:31 UTC, martinebucarey requested changes

2021-12-09 11:31 UTC, martinebucarey commented on src/app/components/turnos/dar-turnos/dar-turnos.html
> -                </plex-button>
Este botón yo no lo volaría. Si bien después tiene otro refactor cuando subamos esto va a desaparecer

2021-12-10 18:00 UTC, liquid36 commented on src/app/components/turnos/dar-turnos/dar-turnos.html
> +<plex-layout main="8">
Este comentario no va.

2021-12-13 11:18 UTC, plammel commented on src/app/components/turnos/dar-turnos/dar-turnos.html
> -                </plex-button>
Ese botón no fue removido. Fue trasladado al title con otro label, a fines de refactor, misma funcionalidad.

2021-12-13 13:24 UTC, martinebucarey commented on src/app/components/turnos/dar-turnos/dar-turnos.html
> -                </plex-button>
Ah se cambio el nombre por eso no lo encontraba.

2021-12-13 13:25 UTC, martinebucarey approved these changes

2021-12-13 17:08 UTC, liquid36 approved these changes

2021-12-13 18:07 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [5601](http://condorpiedra.andes.gob.ar:85/5601/mochawesome.html)
CYPRESS RUN: [4536](https://dashboard.cypress.io/projects/xr7gft/runs/4536/specs)
TEST START: 2021-12-13T17:56:10.177Z
TOTAL: 402
SUCCESS: 374
FAIL: 27
SKIPPED: 1

2021-12-14 13:11 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [5615](http://condorpiedra.andes.gob.ar:85/5615/mochawesome.html)
CYPRESS RUN: [4550](https://dashboard.cypress.io/projects/xr7gft/runs/4550/specs)
TEST START: 2021-12-14T13:11:47.679Z
TOTAL: 402
SUCCESS: 393
FAIL: 8
SKIPPED: 1

2021-12-14 15:59 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [5628](http://condorpiedra.andes.gob.ar:85/5628/mochawesome.html)
CYPRESS RUN: [4561](https://dashboard.cypress.io/projects/xr7gft/runs/4561/specs)
TEST START: 2021-12-14T15:58:52.057Z
TOTAL: 342
SUCCESS: 333
FAIL: 9
SKIPPED: 0

2021-12-14 16:11 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [5629](http://condorpiedra.andes.gob.ar:85/5629/mochawesome.html)
CYPRESS RUN: [4562](https://dashboard.cypress.io/projects/xr7gft/runs/4562/specs)
TEST START: 2021-12-14T16:02:37.267Z
TOTAL: 389
SUCCESS: 382
FAIL: 6
SKIPPED: 1

2021-12-14 16:45 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [5631](http://condorpiedra.andes.gob.ar:85/5631/mochawesome.html)
CYPRESS RUN: [4564](https://dashboard.cypress.io/projects/xr7gft/runs/4564/specs)
TEST START: 2021-12-14T16:45:03.978Z
TOTAL: 352
SUCCESS: 350
FAIL: 1
SKIPPED: 1

2021-12-14 16:56 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [5632](http://condorpiedra.andes.gob.ar:85/5632/mochawesome.html)
CYPRESS RUN: [4565](https://dashboard.cypress.io/projects/xr7gft/runs/4565/specs)
TEST START: 2021-12-14T16:56:39.313Z
TOTAL: 402
SUCCESS: 401
FAIL: 0
SKIPPED: 1

2021-12-14 17:01 UTC, merged