feat(IN):plan-indicaciones, editar una indicación
andes/app pull request #2545
Opened 2021-12-09 19:02 UTC by waltergarrido

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/IN-357
### Funcionalidad desarrollada 

1. Si esta en borrador, se edita directamente. 
2. Si ya esta validada, (internamente) se suspende la actual y se cargar una nueva.
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-12-10 12:47 UTC, liquid36 requested changes
1. Cuando quiero editar un borrador me muestra le buscador, en vez de mostrarme el formulario de una.
2. Cuando quiero editar un pendiente de revisión no me deja, esos son activos también.
3. Cuando edito uno activo no me precarga ningún valor viejo.

2021-12-13 12:59 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [5598](http://condorpiedra.andes.gob.ar:85/5598/mochawesome.html)
CYPRESS RUN: [4533](https://dashboard.cypress.io/projects/xr7gft/runs/4533/specs)
TEST START: 2021-12-13T12:59:30.930Z
TOTAL: 402
SUCCESS: 400
FAIL: 1
SKIPPED: 1

2021-12-15 11:48 UTC, waltergarrido commented
> * Cuando quiero editar un borrador me muestra le buscador, en vez de mostrarme el formulario de una.
> * Cuando quiero editar un pendiente de revisión no me deja, esos son activos también.
> * Cuando edito uno activo no me precarga ningún valor viejo.

@liquid36 quedan corregidos los puntos , agregaría una tarea para resolver la visualización cuando se edita una indicación validada , en este caso queda en estado suspendida y se agrega una nueva.

2021-12-16 17:46 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5653](http://condorpiedra.andes.gob.ar:85/5653/mochawesome.html)
CYPRESS RUN: [4586](https://dashboard.cypress.io/projects/xr7gft/runs/4586/specs)
TEST START: 2021-12-16T17:46:36.258Z
TOTAL: 402
SUCCESS: 400
FAIL: 1
SKIPPED: 1

2021-12-20 17:16 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [5683](http://condorpiedra.andes.gob.ar:85/5683/mochawesome.html)
CYPRESS RUN: [4611](https://dashboard.cypress.io/projects/xr7gft/runs/4611/specs)
TEST START: 2021-12-20T17:16:17.374Z
TOTAL: 402
SUCCESS: 400
FAIL: 1
SKIPPED: 1

2021-12-20 17:48 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [5685](http://condorpiedra.andes.gob.ar:85/5685/mochawesome.html)
CYPRESS RUN: [4613](https://dashboard.cypress.io/projects/xr7gft/runs/4613/specs)
TEST START: 2021-12-20T17:48:21.934Z
TOTAL: 402
SUCCESS: 400
FAIL: 1
SKIPPED: 1

2021-12-20 18:12 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [5686](http://condorpiedra.andes.gob.ar:85/5686/mochawesome.html)
CYPRESS RUN: [4614](https://dashboard.cypress.io/projects/xr7gft/runs/4614/specs)
TEST START: 2021-12-20T18:11:23.991Z
TOTAL: 340
SUCCESS: 326
FAIL: 13
SKIPPED: 1

2021-12-21 13:23 UTC, liquid36 approved these changes

2021-12-21 13:28 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5692](http://condorpiedra.andes.gob.ar:85/5692/mochawesome.html)
CYPRESS RUN: [4619](https://dashboard.cypress.io/projects/xr7gft/runs/4619/specs)
TEST START: 2021-12-21T13:28:29.960Z
TOTAL: 402
SUCCESS: 400
FAIL: 1
SKIPPED: 1

2021-12-21 13:29 UTC, merged