CIT - Ocultar botón disponible en agendas con turnos del dia/programados
andes/app pull request #2546
Opened 2021-12-10 14:23 UTC by MarianoCampetella

… dia/programados

### Requerimiento
https://proyectos.andes.gob.ar/browse/CIT-138

### Funcionalidad desarrollada 
1. Se modifico la función puedoDisponer() para que no aparezca el botón disponible cuando exista una agenda con turnos del día y/o programados.

### UserStory llegó a completarse
- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos
- [ ] Si
- [X] No

### Requiere actualizaciones en la API
- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion
- [ ] Si
- [X] No

2021-12-14 12:37 UTC, martinebucarey commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts
> +            return agenda.bloques.some(b => b.reservadoGestion > 0 || b.reservadoProfesional > 0);
Esto se agrego por alguna razón especial?? no lo veo en la user y tampoco veo que se controlara antes.

2021-12-17 13:27 UTC, martinebucarey commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts
> +            return agenda.bloques.some(b => b.reservadoGestion > 0 || b.reservadoProfesional > 0);
??

2021-12-17 15:56 UTC, MarianoCampetella commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts
> +            return agenda.bloques.some(b => b.reservadoGestion > 0 || b.reservadoProfesional > 0);
La condición se usa para verificar si, cuando se arma la agenda y se le asignan turnos con llave o del profesional, se modifica el valor de reservadoGestion o reservadoProfesional que aparecen en los bloques de una agenda. Y eso que nos devuelva un true o false para que después en el HTML dependiendo de la condición figure o no el botón "disponible"

2021-12-20 14:03 UTC, martinebucarey commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts
> +            return agenda.bloques.some(b => b.reservadoGestion > 0 || b.reservadoProfesional > 0);
Okk, correr test

2021-12-20 15:50 UTC, liquid36 approved these changes

2021-12-20 16:32 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5681](http://condorpiedra.andes.gob.ar:85/5681/mochawesome.html)
CYPRESS RUN: [4609](https://dashboard.cypress.io/projects/xr7gft/runs/4609/specs)
TEST START: 2021-12-20T16:31:49.884Z
TOTAL: 402
SUCCESS: 398
FAIL: 3
SKIPPED: 1

2021-12-20 16:32 UTC, martinebucarey approved these changes

2021-12-20 16:40 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5682](http://condorpiedra.andes.gob.ar:85/5682/mochawesome.html)
CYPRESS RUN: [4610](https://dashboard.cypress.io/projects/xr7gft/runs/4610/specs)
TEST START: 2021-12-20T16:40:43.329Z
TOTAL: 354
SUCCESS: 348
FAIL: 5
SKIPPED: 1

2021-12-21 11:38 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5688](http://condorpiedra.andes.gob.ar:85/5688/mochawesome.html)
CYPRESS RUN: [4616](https://dashboard.cypress.io/projects/xr7gft/runs/4616/specs)
TEST START: 2021-12-21T11:38:17.518Z
TOTAL: 402
SUCCESS: 398
FAIL: 3
SKIPPED: 1

2021-12-21 14:34 UTC, martinebucarey requested changes
@MarianoCampetella hay test que están rompiendo por el cambio, corregirlos así los subimos

2021-12-21 18:26 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5700](http://condorpiedra.andes.gob.ar:85/5700/mochawesome.html)
CYPRESS RUN: [4624](https://dashboard.cypress.io/projects/xr7gft/runs/4624/specs)
TEST START: 2021-12-21T18:26:14.471Z
TOTAL: 404
SUCCESS: 402
FAIL: 1
SKIPPED: 1

2021-12-21 18:43 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5701](http://condorpiedra.andes.gob.ar:85/5701/mochawesome.html)
CYPRESS RUN: [4625](https://dashboard.cypress.io/projects/xr7gft/runs/4625/specs)
TEST START: 2021-12-21T18:43:35.437Z
TOTAL: 404
SUCCESS: 402
FAIL: 1
SKIPPED: 1

2021-12-22 13:12 UTC, martinebucarey approved these changes

2021-12-22 13:14 UTC, merged