CITAS - Filtro por profesional en auditoría de fuera de agenda
andes/app pull request #2548
Opened 2021-12-14 14:16 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/CIT-141

### Funcionalidad desarrollada 

1. Agrega select para filtrar agendas por profesional

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1629
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2021-12-15 16:14 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5641](http://condorpiedra.andes.gob.ar:85/5641/mochawesome.html)
CYPRESS RUN: [4574](https://dashboard.cypress.io/projects/xr7gft/runs/4574/specs)
TEST START: 2021-12-15T16:14:17.409Z
TOTAL: 402
SUCCESS: 400
FAIL: 1
SKIPPED: 1

2021-12-15 19:30 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5643](http://condorpiedra.andes.gob.ar:85/5643/mochawesome.html)
CYPRESS RUN: [4576](https://dashboard.cypress.io/projects/xr7gft/runs/4576/specs)
TEST START: 2021-12-15T19:29:58.352Z
TOTAL: 384
SUCCESS: 381
FAIL: 2
SKIPPED: 1

2021-12-17 14:44 UTC, liquid36 commented on src/app/components/turnos/gestor-agendas/revision/fuera-agenda.html
> +            <plex-select [(ngModel)]="profesional" label="Profesional"
se podría haber usado la directiva **tmProfesionales** para ahorrarse todo el copy/pasteo.

2021-12-17 14:46 UTC, liquid36 commented on src/app/components/turnos/gestor-agendas/revision/fuera-agenda.component.ts
> +                this.plex.info('danger', 'Ocurrió un error cargando las prestaciones.');
El sistema arroja automáticamente una alerta si falla el request, no es necesario agregar otro. Se puede eliminar completamente la función de error de la suscripción.

2021-12-17 15:00 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5657](http://condorpiedra.andes.gob.ar:85/5657/mochawesome.html)
CYPRESS RUN: [4590](https://dashboard.cypress.io/projects/xr7gft/runs/4590/specs)
TEST START: 2021-12-17T14:59:57.066Z
TOTAL: 402
SUCCESS: 401
FAIL: 0
SKIPPED: 1

2021-12-20 15:58 UTC, negro89 commented on src/app/components/turnos/gestor-agendas/revision/fuera-agenda.html
> +            <plex-select [(ngModel)]="profesional" label="Profesional"
Lo tomo. Ya esta corregido

2021-12-21 11:21 UTC, liquid36 approved these changes

2021-12-21 11:39 UTC, martinebucarey requested changes

2021-12-21 11:39 UTC, martinebucarey commented on src/app/components/turnos/gestor-agendas/revision/fuera-agenda.component.ts
> +
Limpiar lineas comentadas

2021-12-21 13:06 UTC, martinebucarey approved these changes

2021-12-21 13:47 UTC, merged