fix(CIT-158): verificar solapamiento al clonar agendas
andes/app pull request #2566
Opened 2022-01-07 17:53 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/CIT-158

### Funcionalidad desarrollada 
1. Se recupera el primer elemento del arreglo 'seleccionados' de tal forma que si se intento clonar sobre una agenda con el mismo profesional o espacio físico, pueda volver a seleccionar otras fechas y generar la acción clonar sin problemas.  
2. 
3. 

### UserStory llegó a completarse
- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos
- [ ] Si
- [X] No

### Requiere actualizaciones en la API
- [X] Si   https://github.com/andes/api/pull/1646
- [ ] No

### Requiere actualizaciones en andes-test-integracion
- [ ] Si
- [X] No

2022-01-07 18:18 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5791](http://condorpiedra.andes.gob.ar:85/5791/mochawesome.html)
CYPRESS RUN: [4714](https://dashboard.cypress.io/projects/xr7gft/runs/4714/specs)
TEST START: 2022-01-07T18:08:38.598Z
TOTAL: 336
SUCCESS: 328
FAIL: 7
SKIPPED: 1

2022-01-07 18:41 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5793](http://condorpiedra.andes.gob.ar:85/5793/mochawesome.html)
CYPRESS RUN: [4716](https://dashboard.cypress.io/projects/xr7gft/runs/4716/specs)
TEST START: 2022-01-07T18:40:59.257Z
TOTAL: 404
SUCCESS: 403
FAIL: 0
SKIPPED: 1

2022-01-18 12:00 UTC, martinebucarey commented
El funcionamiento va bien, queda actualizar el PR de la api que tiene lineas borradas de mas y actualizar el modal segun lo charlado en la demo ( agregar sobre el mismo pr)

2022-01-19 15:58 UTC, plammel approved these changes

2022-01-21 16:17 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5837](http://condorpiedra.andes.gob.ar:85/5837/mochawesome.html)
CYPRESS RUN: [4756](https://dashboard.cypress.io/projects/xr7gft/runs/4756/specs)
TEST START: 2022-01-21T16:03:36.026Z
TOTAL: 404
SUCCESS: 378
FAIL: 25
SKIPPED: 1

2022-01-21 17:26 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5838](http://condorpiedra.andes.gob.ar:85/5838/mochawesome.html)
CYPRESS RUN: [4757](https://dashboard.cypress.io/projects/xr7gft/runs/4757/specs)
TEST START: 2022-01-21T17:25:52.107Z
TOTAL: 386
SUCCESS: 382
FAIL: 3
SKIPPED: 1

2022-01-21 17:49 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5839](http://condorpiedra.andes.gob.ar:85/5839/mochawesome.html)
CYPRESS RUN: [4758](https://dashboard.cypress.io/projects/xr7gft/runs/4758/specs)
TEST START: 2022-01-21T17:49:12.205Z
TOTAL: 336
SUCCESS: 331
FAIL: 4
SKIPPED: 1

2022-01-25 15:31 UTC, liquid36 approved these changes

2022-01-25 19:12 UTC, AgosLizzi reviewed
Campe ... sobre el modal. Me parece una buena implementación pero ajustaría un par de cositas:
1. Esta excesivamente muy grande. Tal vez no necesita ese tamaño y se podría achicar unos puntos.
2. El scroll es innecesario
3.  El último icono "prestación", tendría que ir al costado de centro de salud. En caso de que esa disposición altere los componentes, deberiamos re ordenarlos.
4. El botón aceptar debería ir como sucess, es decir, en verde.
5. No me termina de cerrar el writing del título.

* Si necesitas que te arme mockup o que lo veamos, avisame!

2022-01-31 17:27 UTC, martinebucarey requested changes
![imagen](https://user-images.githubusercontent.com/56874534/151842691-6ec82baa-d92f-4645-be87-44d38cb27fcc.png)
Cuando el solapamiento es por espacio físico me aparecen todos los detalles vacíos, esta prueba fue en demo queriendo guardar una agenda que solapaba el espacio físico

2022-01-31 17:41 UTC, martinebucarey requested changes

2022-01-31 17:41 UTC, martinebucarey commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/modal-agenda.component.ts
> +    <main style="overflow-y: hidden;">
Para agregar un style lo mejor es agregarlo en una hoja de estilos como:
.hide-scroll {
    overflow-y: hidden !important;
}
y despues dentro del html llamarlo como class="hide-scroll"

2022-02-01 14:25 UTC, MarianoCampetella commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/modal-agenda.component.ts
> +    <main style="overflow-y: hidden;">
Corregido, se creo una nueva hoja de estilo para eliminar el scroll del modal!

2022-02-01 14:26 UTC, MarianoCampetella commented
> ![imagen](https://user-images.githubusercontent.com/56874534/151842691-6ec82baa-d92f-4645-be87-44d38cb27fcc.png) Cuando el solapamiento es por espacio físico me aparecen todos los detalles vacíos, esta prueba fue en demo queriendo guardar una agenda que solapaba el espacio físico

Corregido, ahora vienen los datos y se visualizan en el modal de forma correcta.

2022-02-01 14:28 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5881](http://condorpiedra.andes.gob.ar:85/5881/mochawesome.html)
CYPRESS RUN: [4799](https://dashboard.cypress.io/projects/xr7gft/runs/4799/specs)
TEST START: 2022-02-01T14:28:01.935Z
TOTAL: 325
SUCCESS: 299
FAIL: 25
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-02-01 14:40 UTC, martinebucarey approved these changes

2022-02-01 14:41 UTC, martinebucarey commented
Joya @MarianoCampetella  pasan los test y salee

2022-02-01 14:41 UTC, martinebucarey approved these changes

2022-02-01 14:48 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5882](http://condorpiedra.andes.gob.ar:85/5882/mochawesome.html)
CYPRESS RUN: [4800](https://dashboard.cypress.io/projects/xr7gft/runs/4800/specs)
TEST START: 2022-02-01T14:48:46.634Z
TOTAL: 404
SUCCESS: 402
FAIL: 1
SKIPPED: 1

2022-02-01 15:09 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5883](http://condorpiedra.andes.gob.ar:85/5883/mochawesome.html)
CYPRESS RUN: [4801](https://dashboard.cypress.io/projects/xr7gft/runs/4801/specs)
TEST START: 2022-02-01T15:09:05.289Z
TOTAL: 404
SUCCESS: 403
FAIL: 0
SKIPPED: 1

2022-02-01 17:17 UTC, merged