CITAS - Plex en sidebar de Dar turno
andes/app pull request #2575
Opened 2022-01-26 19:16 UTC by palita1991

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-161

### Funcionalidad desarrollada 

1. Se actualiza código del sidebar de dar turno para que quede actualizado con plex
2. Se elimina funcionalidad y código que no se utilizaba

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [x] Si https://github.com/andes/andes-test-integracion/pull/411
- [ ] No

2022-01-27 11:37 UTC, liquid36 commented
USUARIO: mpalavecino  
BUILD NUMBER: [5855](http://condorpiedra.andes.gob.ar:85/5855/mochawesome.html)
CYPRESS RUN: [4773](https://dashboard.cypress.io/projects/xr7gft/runs/4773/specs)
TEST START: 2022-01-27T11:35:54.127Z
TOTAL: 396
SUCCESS: 381
FAIL: 14
SKIPPED: 1

2022-01-27 11:49 UTC, martinebucarey requested changes

2022-01-27 12:28 UTC, palita1991 commented on src/app/components/turnos/dar-turnos/dar-turnos.html
> +                    </plex-label>
@martinebucarey joya gracias no sabia de ese enumerar.pipe, ahora lo cambio

2022-01-27 12:29 UTC, liquid36 commented
USUARIO: mpalavecino  
BUILD NUMBER: [5856](http://condorpiedra.andes.gob.ar:85/5856/mochawesome.html)
CYPRESS RUN: [4774](https://dashboard.cypress.io/projects/xr7gft/runs/4774/specs)
TEST START: 2022-01-27T12:28:42.034Z
TOTAL: 356
SUCCESS: 345
FAIL: 11
SKIPPED: 0

2022-01-27 13:28 UTC, palita1991 commented on src/app/components/turnos/dar-turnos/dar-turnos.html
> +                    </plex-label>
@martinebucarey resueltoo

2022-01-27 13:41 UTC, liquid36 commented
USUARIO: mpalavecino  
BUILD NUMBER: [5857](http://condorpiedra.andes.gob.ar:85/5857/mochawesome.html)
CYPRESS RUN: [4775](https://dashboard.cypress.io/projects/xr7gft/runs/4775/specs)
TEST START: 2022-01-27T13:41:27.262Z
TOTAL: 404
SUCCESS: 402
FAIL: 1
SKIPPED: 1

2022-01-27 13:44 UTC, liquid36 commented
![image](https://user-images.githubusercontent.com/3813270/151370663-ac48d8b2-cd35-44c7-93d5-cdb4d3195b46.png)

No me parece correcto que haya que scrollear para ver los horarios de los turnos. Además que laa información adicional antes estaba secuencializada y ahora no. Eso es parte del cambio?

2022-01-27 13:46 UTC, liquid36 commented
USUARIO: mpalavecino  
BUILD NUMBER: [5858](http://condorpiedra.andes.gob.ar:85/5858/mochawesome.html)
CYPRESS RUN: [4776](https://dashboard.cypress.io/projects/xr7gft/runs/4776/specs)
TEST START: 2022-01-27T13:44:32.860Z
TOTAL: 1
SUCCESS: 0
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-01-27 14:05 UTC, palita1991 commented
> ![image](https://user-images.githubusercontent.com/3813270/151370663-ac48d8b2-cd35-44c7-93d5-cdb4d3195b46.png)
> 
> No me parece correcto que haya que scrollear para ver los horarios de los turnos. Además que laa información adicional antes estaba secuencializada y ahora no. Eso es parte del cambio?

@liquid36 Se replico lo que estaba plasmado en el mockup de la tarea, de tener todo en una sola pantalla. Lo que quizas no se contemplo es que en la información adicional hay muchos campos que no se pueden sacar asi por que si. Ahora nos reunimos con @AgosLizzi para ver si se puede mejorar un poco más.

2022-01-28 16:28 UTC, AgosLizzi approved these changes

2022-02-07 13:35 UTC, martinebucarey requested changes
Dos cositas:
Para no repetir informacion, si ponemos en el sidebar los datos del paciente, los sacaria del header
![imagen](https://user-images.githubusercontent.com/56874534/152797843-064ccc86-6004-4e0e-8a0e-b2b0faf562a8.png)

Y el tema de los horarios, yo no lo subiría hasta no encontrar la vuelta para achicar esas cards porque ocupan demasiado espacio y va a terminar siendo mas incomodo que cómodo en agendas con muchos turnos.

2022-02-23 14:26 UTC, palita1991 commented
> Dos cositas: Para no repetir informacion, si ponemos en el sidebar los datos del paciente, los sacaria del header ![imagen](https://user-images.githubusercontent.com/56874534/152797843-064ccc86-6004-4e0e-8a0e-b2b0faf562a8.png)
> 
> Y el tema de los horarios, yo no lo subiría hasta no encontrar la vuelta para achicar esas cards porque ocupan demasiado espacio y va a terminar siendo mas incomodo que cómodo en agendas con muchos turnos.

Corregido

2022-02-23 19:12 UTC, martinebucarey commented
USUARIO: mpalavecino  
BUILD NUMBER: [5982](http://condorpiedra.andes.gob.ar:85/5982/mochawesome.html)
CYPRESS RUN: [4897](https://dashboard.cypress.io/projects/xr7gft/runs/4897/specs)
TEST START: 2022-02-23T19:11:44.808Z
TOTAL: 360
SUCCESS: 346
FAIL: 13
SKIPPED: 1

2022-02-24 11:37 UTC, martinebucarey commented
USUARIO: mpalavecino  
BUILD NUMBER: [5985](http://condorpiedra.andes.gob.ar:85/5985/mochawesome.html)
CYPRESS RUN: [4900](https://dashboard.cypress.io/projects/xr7gft/runs/4900/specs)
TEST START: 2022-02-24T11:36:53.123Z
TOTAL: 406
SUCCESS: 394
FAIL: 11
SKIPPED: 1

2022-02-24 16:18 UTC, martinebucarey commented
USUARIO: mpalavecino  
BUILD NUMBER: [5991](http://condorpiedra.andes.gob.ar:85/5991/mochawesome.html)
CYPRESS RUN: [4906](https://dashboard.cypress.io/projects/xr7gft/runs/4906/specs)
TEST START: 2022-02-24T16:17:56.321Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

2022-02-24 16:22 UTC, martinebucarey commented
USUARIO: mpalavecino  
BUILD NUMBER: [5992](http://condorpiedra.andes.gob.ar:85/5992/mochawesome.html)
CYPRESS RUN: [4907](https://dashboard.cypress.io/projects/xr7gft/runs/4907/specs)
TEST START: 2022-02-24T16:21:01.631Z
TOTAL: 1
SUCCESS: 0
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-03-02 18:09 UTC, martinebucarey commented
USUARIO: mpalavecino  
BUILD NUMBER: [6003](http://condorpiedra.andes.gob.ar:85/6003/mochawesome.html)
CYPRESS RUN: [4918](https://dashboard.cypress.io/projects/xr7gft/runs/4918/specs)
TEST START: 2022-03-02T18:08:42.047Z
TOTAL: 406
SUCCESS: 392
FAIL: 13
SKIPPED: 1

2022-03-08 12:12 UTC, martinebucarey commented
USUARIO: mpalavecino  
BUILD NUMBER: [6041](http://condorpiedra.andes.gob.ar:85/6041/mochawesome.html)
CYPRESS RUN: [4952](https://dashboard.cypress.io/projects/xr7gft/runs/4952/specs)
TEST START: 2022-03-08T12:12:22.183Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

2022-03-30 14:19 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [6150](http://condorpiedra.andes.gob.ar:85/6150/mochawesome.html)
CYPRESS RUN: [5049](https://dashboard.cypress.io/projects/xr7gft/runs/5049/specs)
TEST START: 2022-03-30T14:19:17.886Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

2022-03-30 14:30 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [6151](http://condorpiedra.andes.gob.ar:85/6151/mochawesome.html)
CYPRESS RUN: [5050](https://dashboard.cypress.io/projects/xr7gft/runs/5050/specs)
TEST START: 2022-03-30T14:30:07.268Z
TOTAL: 346
SUCCESS: 331
FAIL: 14
SKIPPED: 1

2022-03-30 14:52 UTC, martinebucarey commented
USUARIO: mpalavecino  
BUILD NUMBER: [6153](http://condorpiedra.andes.gob.ar:85/6153/mochawesome.html)
CYPRESS RUN: [5051](https://dashboard.cypress.io/projects/xr7gft/runs/5051/specs)
TEST START: 2022-03-30T14:51:53.148Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

2022-03-30 15:02 UTC, martinebucarey commented
USUARIO: mpalavecino  
BUILD NUMBER: [6154](http://condorpiedra.andes.gob.ar:85/6154/mochawesome.html)
CYPRESS RUN: [5052](https://dashboard.cypress.io/projects/xr7gft/runs/5052/specs)
TEST START: 2022-03-30T15:02:23.196Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

2022-03-30 15:54 UTC, martinebucarey commented
USUARIO: mpalavecino  
BUILD NUMBER: [6155](http://condorpiedra.andes.gob.ar:85/6155/mochawesome.html)
CYPRESS RUN: [5053](https://dashboard.cypress.io/projects/xr7gft/runs/5053/specs)
TEST START: 2022-03-30T15:53:55.455Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-03-30 15:57 UTC, martinebucarey approved these changes

2022-03-30 15:58 UTC, merged