BI - Proximos padres
andes/app pull request #2591
Opened 2022-02-21 14:23 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/BI-109

### Funcionalidad desarrollada 
1. Se modifico el html para poder mostrar la informacion de los padre y los aconceptos a agrupar. Tambien se hizo un refactor de la pantalla para visualizar mejor los datos y que esten de forma ordenada.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si   https://github.com/andes/api/pull/1665
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-02-21 14:42 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5963](http://condorpiedra.andes.gob.ar:85/5963/mochawesome.html)
CYPRESS RUN: [4880](https://dashboard.cypress.io/projects/xr7gft/runs/4880/specs)
TEST START: 2022-02-21T14:41:49.904Z
TOTAL: 402
SUCCESS: 400
FAIL: 1
SKIPPED: 1

2022-02-21 14:53 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5964](http://condorpiedra.andes.gob.ar:85/5964/mochawesome.html)
CYPRESS RUN: [4881](https://dashboard.cypress.io/projects/xr7gft/runs/4881/specs)
TEST START: 2022-02-21T14:53:40.764Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-02-24 15:52 UTC, AgosLizzi reviewed
Bien resuelto el sidebar. Dejo algunos detalles: 
1. La pantalla principal no tiene título
2. Sobre el tab "jerarquias", no me cierra que la acción que abre "conceptos a agrupar" sea un click. Tal vez buscaria una variable más intuitiva como un botón (como ejemplo rápido, deberiamos analizarlo)
3. Por último, el tabs implementado sobre el side bar me da la sensación que no tiene un contexto y esta flotando. (adjunto foto). Habría que evaluar la posibilidad de otro componente.
![Captura](https://user-images.githubusercontent.com/72876985/155559078-337a98b8-7746-4928-93b0-8400bb27c53b.JPG)

2022-03-08 12:05 UTC, martinebucarey requested changes

2022-03-08 17:46 UTC, MarianoCampetella commented on src/app/modules/estadisticas/components/rup/rup-pacientes.component.ts
> +    ];
Corregido!

2022-03-29 11:36 UTC, martinebucarey approved these changes

2022-03-29 11:44 UTC, merged