EP - Muestra el numero total de fichas filtradas por el buscador
andes/app pull request #2594
Opened 2022-02-23 17:36 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/EP-184

### Funcionalidad desarrollada 

1. Badge con detalle de total de fichas filtradas
2. Nueva ruta 'search' en servicio de seguimiento

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1668
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-02-23 17:49 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [5978](http://condorpiedra.andes.gob.ar:85/5978/mochawesome.html)
CYPRESS RUN: [4894](https://dashboard.cypress.io/projects/xr7gft/runs/4894/specs)
TEST START: 2022-02-23T17:49:40.600Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

2022-02-23 19:01 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [5980](http://condorpiedra.andes.gob.ar:85/5980/mochawesome.html)
CYPRESS RUN: [4896](https://dashboard.cypress.io/projects/xr7gft/runs/4896/specs)
TEST START: 2022-02-23T18:47:51.656Z
TOTAL: 406
SUCCESS: 380
FAIL: 25
SKIPPED: 1

2022-02-24 12:33 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [5986](http://condorpiedra.andes.gob.ar:85/5986/mochawesome.html)
CYPRESS RUN: [4901](https://dashboard.cypress.io/projects/xr7gft/runs/4901/specs)
TEST START: 2022-02-24T12:33:09.531Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

2022-02-24 14:45 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [5990](http://condorpiedra.andes.gob.ar:85/5990/mochawesome.html)
CYPRESS RUN: [4905](https://dashboard.cypress.io/projects/xr7gft/runs/4905/specs)
TEST START: 2022-02-24T14:45:30.188Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

2022-02-25 19:16 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [5996](http://condorpiedra.andes.gob.ar:85/5996/mochawesome.html)
CYPRESS RUN: [4911](https://dashboard.cypress.io/projects/xr7gft/runs/4911/specs)
TEST START: 2022-02-25T19:16:10.965Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

2022-03-29 15:47 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [6129](http://condorpiedra.andes.gob.ar:85/6129/mochawesome.html)
CYPRESS RUN: [5028](https://dashboard.cypress.io/projects/xr7gft/runs/5028/specs)
TEST START: 2022-03-29T15:47:09.084Z
TOTAL: 406
SUCCESS: 401
FAIL: 4
SKIPPED: 1

2022-03-29 17:52 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [6133](http://condorpiedra.andes.gob.ar:85/6133/mochawesome.html)
CYPRESS RUN: [5032](https://dashboard.cypress.io/projects/xr7gft/runs/5032/specs)
TEST START: 2022-03-29T17:52:13.950Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

2022-03-29 18:30 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [6135](http://condorpiedra.andes.gob.ar:85/6135/mochawesome.html)
CYPRESS RUN: [5034](https://dashboard.cypress.io/projects/xr7gft/runs/5034/specs)
TEST START: 2022-03-29T18:29:25.726Z
TOTAL: 363
SUCCESS: 346
FAIL: 16
SKIPPED: 1

2022-03-30 13:59 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [6149](http://condorpiedra.andes.gob.ar:85/6149/mochawesome.html)
CYPRESS RUN: [5048](https://dashboard.cypress.io/projects/xr7gft/runs/5048/specs)
TEST START: 2022-03-30T13:59:17.505Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

2022-03-31 18:53 UTC, plammel requested changes

2022-04-06 20:00 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [6188](http://condorpiedra.andes.gob.ar:85/6188/mochawesome.html)
CYPRESS RUN: [5084](https://dashboard.cypress.io/projects/xr7gft/runs/5084/specs)
TEST START: 2022-04-06T19:44:20.099Z
TOTAL: 406
SUCCESS: 379
FAIL: 26
SKIPPED: 1

2022-04-07 14:20 UTC, plammel reviewed
ver comentarios en https://github.com/andes/api/pull/1668/files

2022-04-20 17:14 UTC, martinebucarey commented on src/app/modules/epidemiologia/services/seguimiento-pacientes.service.ts
> +        return this.server.get(`${this.url}/search/v2`, { params });
No hay una actualizacion en la api por esto?? porque no encuentro la ruta esa y por otro lado porque no iria dentro del mismo search que ya se usa??

2022-04-20 19:25 UTC, negro89 commented on src/app/modules/epidemiologia/services/seguimiento-pacientes.service.ts
> +        return this.server.get(`${this.url}/search/v2`, { params });
No no hay. Fue un error de actualización. Ya quedo corregido :+1:

2022-04-21 15:54 UTC, martinebucarey approved these changes

2022-04-22 12:55 UTC, AgosLizzi approved these changes

2022-05-19 13:16 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [6468](http://condorpiedra.andes.gob.ar:85/6468/mochawesome.html)
CYPRESS RUN: [5350](https://dashboard.cypress.io/projects/xr7gft/runs/5350/specs)
TEST START: 2022-05-19T13:15:56.482Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-05-19 16:51 UTC, plammel approved these changes

2022-05-26 12:59 UTC, merged