Top 125
andes/app pull request #2596
Opened 2022-02-26 05:54 UTC by leon-bravo

### Requerimiento
 
TOP - se cambio la visibilidad del botón Iniciar prestación para que solo se muestre para las practicas que el prestador tiene habilitadas
### Funcionalidad desarrollada 

1. se cambio la visibilidad del botón Iniciar prestación para que solo se muestre para las practicas que el prestador tiene habilitadas
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [x] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

![Sevisualiza solo el boton en la practica habilitada](https://user-images.githubusercontent.com/5743147/155831296-cd1d448d-0186-420c-825c-af473bd58492.png)

2022-03-02 19:08 UTC, martinebucarey commented
USUARIO: lbravo  
BUILD NUMBER: [6005](http://condorpiedra.andes.gob.ar:85/6005/mochawesome.html)
CYPRESS RUN: [4919](https://dashboard.cypress.io/projects/xr7gft/runs/4919/specs)
TEST START: 2022-03-02T19:08:07.557Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-03-07 14:02 UTC, martinebucarey requested changes

2022-03-07 14:02 UTC, martinebucarey commented on src/app/components/top/solicitudes/solicitudes.component.ts
> +        return enabled;
Esto puede quedar en una linea:

```suggestion
        return this.auth.check('rup:tipoPrestacion:' + prestacion.solicitud.tipoPrestacion.id);
```
o:
```suggestion
        const enabled = this.auth.check('rup:tipoPrestacion:' + prestacion.solicitud.tipoPrestacion.id);
        return enabled;
```
El this.auth.check retorna true/false siempre

2022-03-08 12:40 UTC, martinebucarey approved these changes

2022-03-08 13:00 UTC, palita1991 approved these changes

2022-03-08 13:26 UTC, merged