RUP - aplicar prototipo de edicion a formulas
andes/app pull request #2605
Opened 2022-03-17 15:28 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/RUP-308

### Funcionalidad desarrollada 

1. Se realizo un refactor sobre la edad gestacional dentro de RUP

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-03-18 12:11 UTC, martinebucarey requested changes
1. No subir package.lock cuando no hay cambios en el package.json
2. Correr test
3. @AgosLizzi yo la veo bien esperamos tu revisión,

2022-03-18 12:11 UTC, martinebucarey commented on src/app/modules/rup/components/elementos/FormulaBase.html
> +                         (click)="changeValorManual(true)" tooltip="Agregar manualmente">
Se corta el tooltip, agregar posición o recortar la frase

```suggestion
            <plex-button *ngIf="!valorManual && !soloValores" type="warning" icon="pencil"
                         (click)="changeValorManual(true)" tooltip="Agregar manualmente" tooltipPosition="left">
```

2022-03-18 14:02 UTC, AgosLizzi commented
Al no colocar ningun valor sobre el campo "fecha última menstruación" me sigue desplazando el botón editar. Adjunto foto de ambos casos.
![pruebas_Mesa de trabajo 1](https://user-images.githubusercontent.com/72876985/159016855-b0561ab2-bbc6-44e8-8f71-acac9ab72c70.jpg)
![pruebas-02](https://user-images.githubusercontent.com/72876985/159016860-34bf75a9-c801-4185-8a0b-689ddc3a5247.jpg)

Me sumo al pedido de @martinebucarey sobre los tooltips.

2022-03-21 12:26 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6087](http://condorpiedra.andes.gob.ar:85/6087/mochawesome.html)
CYPRESS RUN: [4995](https://dashboard.cypress.io/projects/xr7gft/runs/4995/specs)
TEST START: 2022-03-21T12:26:39.682Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-03-21 12:37 UTC, MarianoCampetella commented
> 1. No subir package.lock cuando no hay cambios en el package.json
> 2. Correr test
> 3. @AgosLizzi yo la veo bien esperamos tu revisión,

Ya se soluciono lo del package.lock, los test fueron ejecutados correctamente y se corrigieron los detalles que pedia @AgosLizzi

2022-03-21 15:35 UTC, martinebucarey commented
> > 1. No subir package.lock cuando no hay cambios en el package.json
> > 2. Correr test
> > 3. @AgosLizzi yo la veo bien esperamos tu revisión,
> 
> Ya se soluciono lo del package.lock, los test fueron ejecutados correctamente y se corrigieron los detalles que pedia @AgosLizzi

sigue apareciendo el package jaja

2022-03-29 11:55 UTC, martinebucarey approved these changes

2022-03-29 12:05 UTC, merged