Rup 309
andes/app pull request #2607
Opened 2022-03-18 15:03 UTC by waltergarrido

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/RUP-309
### Funcionalidad desarrollada 

1. sobreturno en punto de inicio RUP
2. 
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-03-18 15:29 UTC, martinebucarey commented
USUARIO: wgarrido  
BUILD NUMBER: [6073](http://condorpiedra.andes.gob.ar:85/6073/mochawesome.html)
CYPRESS RUN: [4983](https://dashboard.cypress.io/projects/xr7gft/runs/4983/specs)
TEST START: 2022-03-18T15:25:00.520Z
TOTAL: 106
SUCCESS: 4
FAIL: 102
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-03-18 15:55 UTC, martinebucarey requested changes
no subir el package-lock si no hay cambios en el package.json

2022-03-18 17:07 UTC, martinebucarey commented
USUARIO: wgarrido  
BUILD NUMBER: [6075](http://condorpiedra.andes.gob.ar:85/6075/mochawesome.html)
CYPRESS RUN: [4985](https://dashboard.cypress.io/projects/xr7gft/runs/4985/specs)
TEST START: 2022-03-18T16:58:11.002Z
TOTAL: 385
SUCCESS: 377
FAIL: 7
SKIPPED: 1

2022-03-18 17:26 UTC, martinebucarey commented
USUARIO: wgarrido  
BUILD NUMBER: [6077](http://condorpiedra.andes.gob.ar:85/6077/mochawesome.html)
CYPRESS RUN: [4986](https://dashboard.cypress.io/projects/xr7gft/runs/4986/specs)
TEST START: 2022-03-18T17:26:18.845Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

2022-03-18 18:06 UTC, martinebucarey commented
USUARIO: wgarrido  
BUILD NUMBER: [6081](http://condorpiedra.andes.gob.ar:85/6081/mochawesome.html)
CYPRESS RUN: [4989](https://dashboard.cypress.io/projects/xr7gft/runs/4989/specs)
TEST START: 2022-03-18T18:06:11.519Z
TOTAL: 372
SUCCESS: 350
FAIL: 21
SKIPPED: 1

2022-04-08 13:51 UTC, plammel commented
Se implementa en https://github.com/andes/app/pull/2620

2022-04-08 13:51 UTC, closed without merging