feat:(CITAS): agregar icono si es un turno virtual
andes/app pull request #2609
Opened 2022-03-22 12:01 UTC by leon-bravo

* **seguimiento:** semaforo ([#2600](https://github.com/andes/app/issues/2600)) ([fbeed69](https://github.com/andes/app/commit/fbeed69b31d48b1b889cdfc614c4d3a09efed7f3))

* **EP:** filtro score seguimiento ([#2590](https://github.com/andes/app/issues/2590)) ([522ccdf](https://github.com/andes/app/commit/522ccdf1de6f2b04218c13543082b611904e7971))
* **mpi:** se agrega la validación por sexo no binario ([#2588](https://github.com/andes/app/issues/2588)) ([22c019d](https://github.com/andes/app/commit/22c019dee7f52d09b774bd392bdf8ff3f52a70ce))
* **seguimiento:** orden prioridad o fecha ([#2599](https://github.com/andes/app/issues/2599)) ([4616b67](https://github.com/andes/app/commit/4616b67cb7030740475b195a63981fb501dec1eb))
* **UIUX:** acomoda correctamente header de paciente en navbar ([#2598](https://github.com/andes/app/issues/2598)) ([b1d93db](https://github.com/andes/app/commit/b1d93dbbd44779371d66a10acfacd50e0d9b415f))

### Requerimiento
 
[CIT-164](https://proyectos.andes.gob.ar/browse/CIT-164)
agendas-virtuales: en top visualizar que el turno dado es virtual

### Funcionalidad desarrollada 

1. se agrega un icono de televisor en el listado de las consultas para indicar cuales son virtuales
2. 
3. 

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2022-03-22 12:25 UTC, palita1991 requested changes

2022-03-22 12:25 UTC, palita1991 commented on src/app/components/top/solicitudes/solicitudes.component.ts
> +            if (prestacion.solicitud && prestacion.solicitud.turno) {
Esto se puede poner asi `if(prestacion.solicitud?.turno)`

2022-03-22 12:25 UTC, palita1991 commented on src/app/components/top/solicitudes/solicitudes.component.ts
> +            if (prestacion.solicitud.actualizado === true) { return prestacion.solicitud.turno_virtual; } else {return false;}
Esto se puede poner asi `if(prestacion.solicitud.actualizado)` ahi ya evalua si es true

2022-03-22 12:25 UTC, palita1991 commented on src/app/components/top/solicitudes/solicitudes.html
> +                                <plex-badge *ngIf="prestacion.solicitud.turno && isVirtualTurn(prestacion)" class="mr-1" type="info" tooltip="Agenda Virtual" tooltipPosition="top">
en el *ngIf es necesario preguntar por **prestacion.solicitud.turno** si adentro de isVirtualTurn(prestacion) ya se evalúa esa condición en la linea 250

2022-03-22 12:40 UTC, martinebucarey commented
USUARIO: lbravo  
BUILD NUMBER: [6092](http://condorpiedra.andes.gob.ar:85/6092/mochawesome.html)
CYPRESS RUN: [5000](https://dashboard.cypress.io/projects/xr7gft/runs/5000/specs)
TEST START: 2022-03-22T12:39:43.755Z
TOTAL: 361
SUCCESS: 349
FAIL: 11
SKIPPED: 1

2022-03-23 17:51 UTC, martinebucarey commented
USUARIO: lbravo  
BUILD NUMBER: [6100](http://condorpiedra.andes.gob.ar:85/6100/mochawesome.html)
CYPRESS RUN: [5007](https://dashboard.cypress.io/projects/xr7gft/runs/5007/specs)
TEST START: 2022-03-23T17:50:55.482Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-03-31 18:50 UTC, plammel requested changes

2022-03-31 18:50 UTC, plammel commented on src/app/components/top/solicitudes/solicitudes.component.ts
> +                    if (link !== undefined) {
`null`  o `''` son valores válidos?
```suggestion
                    if (link) {
```

2022-03-31 18:50 UTC, plammel commented on src/app/components/top/solicitudes/solicitudes.component.ts
> +            if (prestacion.solicitud.actualizado) { return prestacion.solicitud.turno_virtual; } else { return false; }
Identar

2022-04-06 17:31 UTC, martinebucarey commented
Revisar cambios para subir PR

2022-04-07 13:10 UTC, leon-bravo commented on src/app/components/top/solicitudes/solicitudes.component.ts
> +            if (prestacion.solicitud.actualizado) { return prestacion.solicitud.turno_virtual; } else { return false; }
ahi ya quedo listo

2022-04-07 14:06 UTC, plammel submitted a review, later dismissed

2022-04-07 14:06 UTC, plammel commented on src/app/components/top/solicitudes/solicitudes.component.ts
> +    isVirtualTurn(prestacion) {
Algunos comentarios sobre esta función:

- Siendo que el equipo que desarrolla, revisa y testea es hispanoparlante, preferir comentarios explicativos en español.
- `prestacion.solicitud.actualizado` no existe en el schema original de prestaciones
- Si entiendo bien la implementación, la función se vale de la detección de cambios de Angular para ser ejecutada una y otra vez, de manera que la primera vez flagee la prestación, y las siguientes retorne el booleano basado en la "actualización"  inicial. Pero esto no es correcto:
- La función debería o setear el flag, o retornar un booleano, pero no ambas. Es decir, la función debería "servir para una cosa", y no "servir para una cosa u otra, dependiendo el estado del input".
- Si no es aconsejable llamar funciones directamente desde un template de Angular (por ser llamada recurrentemente cada vez que se detecta un cambio), mucho menos es que estas realicen requests a la api.

Para casos como este, lo ideal seria implementar un pipe. ver por ej https://github.com/andes/app/blob/master/src/app/modules/epidemiologia/pipes/checkEdit.pipe.ts

2022-04-12 12:50 UTC, martinebucarey commented
Revisar comentarios  para subir PR

2022-04-19 12:14 UTC, martinebucarey commented
Revisar comentarios

2022-04-19 12:56 UTC, AgosLizzi approved these changes

2022-04-22 18:48 UTC, martinebucarey commented
USUARIO: lbravo  
BUILD NUMBER: [6267](http://condorpiedra.andes.gob.ar:85/6267/mochawesome.html)
CYPRESS RUN: [5162](https://dashboard.cypress.io/projects/xr7gft/runs/5162/specs)
TEST START: 2022-04-22T18:47:39.037Z
TOTAL: 298
SUCCESS: 271
FAIL: 26
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-04-22 19:46 UTC, martinebucarey commented
USUARIO: lbravo  
BUILD NUMBER: [6268](http://condorpiedra.andes.gob.ar:85/6268/mochawesome.html)
CYPRESS RUN: [5163](https://dashboard.cypress.io/projects/xr7gft/runs/5163/specs)
TEST START: 2022-04-22T19:46:30.060Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-04-26 11:37 UTC, martinebucarey requested changes

2022-04-26 11:37 UTC, martinebucarey commented on src/app/components/top/pipes/linkTurnoRemoto.pipe.ts
> +        return of(false);
Esto va a retornar siempre false, no debería retornar si tiene link o no??

2022-04-26 16:10 UTC, leon-bravo commented on src/app/components/top/pipes/linkTurnoRemoto.pipe.ts
> +        return of(false);
en teoría, o al menos esa fue la intención, jaja. Devolvería un observable con false en caso de que la consulta no tenga turnos y en caso contrario, un observable provisto por el método pipe, que resolvería internamente a true o false. Me parecio mas simple un valor booleano, aunque capaz es confuso el nombre. Se me ocurre que puedo cambiar el nombre; o devolver el link con el turno o blanco en caso de que no tenga y crear un pipe que lo convierta a booleano según el caso

2022-04-26 16:14 UTC, martinebucarey commented on src/app/components/top/pipes/linkTurnoRemoto.pipe.ts
> +        return of(false);
no me cierra mucho la idea o no la entiendo pero en ese caso vos definis la variable conLink en false, y si no entra al if sigue estando en false, por lo tanto en una de esas se puede devolver esa variable y que quede mas limpio el codigo y no con tanto return

2022-04-26 23:26 UTC, martinebucarey commented
USUARIO: lbravo  
BUILD NUMBER: [6287](http://condorpiedra.andes.gob.ar:85/6287/mochawesome.html)
CYPRESS RUN: [5180](https://dashboard.cypress.io/projects/xr7gft/runs/5180/specs)
TEST START: 2022-04-26T23:26:02.192Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

2022-04-27 11:48 UTC, martinebucarey commented
USUARIO: lbravo  
BUILD NUMBER: [6289](http://condorpiedra.andes.gob.ar:85/6289/mochawesome.html)
CYPRESS RUN: [5182](https://dashboard.cypress.io/projects/xr7gft/runs/5182/specs)
TEST START: 2022-04-27T11:47:55.979Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-04-27 12:48 UTC, martinebucarey approved these changes

2022-04-27 12:59 UTC, merged