TOP - Error al listar solicitudes Asignadas cuando se accede desde RUP
andes/app pull request #2619
Opened 2022-04-07 20:05 UTC by leon-bravo

### Requerimiento
 
TOP-126 - Error al listar solicitudes Asignadas cuando se accede desde RUP
### Funcionalidad desarrollada 

1.  Se controla la fecha desde hasta para que no supere un intervalo de tiempo
2. 
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-04-08 15:20 UTC, plammel requested changes

2022-04-08 15:20 UTC, plammel commented on src/app/components/top/solicitudes/solicitudes.component.ts
> +        if ( !(this.fechaDesdeEntrada === undefined) && !(this.fechaDesdeEntrada === null) ) {
```suggestion
        if (this.fechaDesdeEntrada) {
```

2022-04-08 15:20 UTC, plammel commented on src/app/components/top/solicitudes/solicitudes.component.ts
> +        const diasAntes = 1000 * 60 * 60 * 24 * this.diasAntes;
Para manipular fechas, usar [moment](https://www.npmjs.com/package/moment)

2022-04-08 15:20 UTC, plammel commented on src/app/components/top/solicitudes/solicitudes.component.ts
> +        if ( !(this.fechaHastaEntrada === undefined) && !(this.fechaHastaEntrada === null) ) {
```suggestion
        if (this.fechaHastaEntrada) {
```

2022-04-19 12:42 UTC, martinebucarey requested changes
- Hay un tema con los filtros de fecha, cuando ingreso a TOP por primera vez me muestra un listado filtrado sin fecha desde y hasta y luego cuando cambio de solapa me desaparece, creo que eso no deberia cambiar como esta ahora (segunda pestaña del video) 

https://www.loom.com/share/b20bbe240c5a446a8d1fa91608ca817c

-  Me parece que un limite de fechas no es la idea de la tarea porque limita mucho al usuario, con un scroll infinito en el caso que eso funcione mal se podría solucionar. Ver si la idea es un limite de fechas con @silviroa . En el caso que sea así, el plex-datetime tiene un min y un max que soluciona eso.
- Recordar poner el link de la tarea de jira en el PR para  que sea mas fácil la revisión, y correr test.

2022-04-28 15:35 UTC, martinebucarey commented
USUARIO: lbravo  
BUILD NUMBER: [6303](http://condorpiedra.andes.gob.ar:85/6303/mochawesome.html)
CYPRESS RUN: [5194](https://dashboard.cypress.io/projects/xr7gft/runs/5194/specs)
TEST START: 2022-04-28T15:35:13.662Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-04-28 18:09 UTC, martinebucarey commented
USUARIO: lbravo  
BUILD NUMBER: [6310](http://condorpiedra.andes.gob.ar:85/6310/mochawesome.html)
CYPRESS RUN: [5201](https://dashboard.cypress.io/projects/xr7gft/runs/5201/specs)
TEST START: 2022-04-28T18:09:32.853Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-04-29 11:03 UTC, martinebucarey approved these changes

2022-05-04 13:25 UTC, martinebucarey commented
Se soluciona en https://github.com/andes/app/pull/2643

2022-05-04 13:25 UTC, martinebucarey commented
Se soluciona en https://github.com/andes/app/pull/2643

2022-05-04 13:25 UTC, closed without merging