MAT: eliminar validacion nro tramite
andes/app pull request #2621
Opened 2022-04-08 18:50 UTC by plammel

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/MAT-95
### Funcionalidad desarrollada 

1. En inscripcion de profesional para emision de certificado covid19, se elimina validacion de nro de tramite de dni
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [x] Si https://github.com/andes/api/pull/1692
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [x] Si https://github.com/andes/andes-test-integracion/pull/425
- [ ] No

2022-04-12 12:05 UTC, martinebucarey requested changes
Se esta haciendo la comprobación de la vigencia de la matricula todavía y también muestra el check para emitir certificados covid y el titulo de la pantalla tambien sigue apareciendo como covid:
![imagen](https://user-images.githubusercontent.com/56874534/162958683-16b0d115-21c6-4773-b092-f4bade153f94.png)
Esas especificaciones no están en el ticket, actualizar porfa!

2022-04-18 17:00 UTC, plammel commented
> Se esta haciendo la comprobación de la vigencia de la matricula todavía y también muestra el check para emitir certificados covid y el titulo de la pantalla tambien sigue apareciendo como covid: ![imagen](https://user-images.githubusercontent.com/56874534/162958683-16b0d115-21c6-4773-b092-f4bade153f94.png) Esas especificaciones no están en el ticket, actualizar porfa!

@martinebucarey Updeteado!

2022-04-18 17:46 UTC, martinebucarey reviewed
Quedaron colgados archivos de otro PR me parece, de relaciones

2022-04-19 12:11 UTC, AgosLizzi reviewed
Rulito dos cositas:
El botón volver este en naranja. 
![volver](https://user-images.githubusercontent.com/72876985/163999907-cb5f1e24-d9b4-4c6c-8766-bfd83aac3771.JPG)
 Y si es posible, intentaría despegar un poco el boton de "nuevo usuario" del campo de texto. Para que las acciones se diferencien mejor
![nuevousuario](https://user-images.githubusercontent.com/72876985/163999994-4fad4abe-e230-4900-8dd5-d0eea0ae6906.JPG)

2022-04-19 14:11 UTC, martinebucarey commented
Correr los test y revisar, habia test de esta pantalla hechos que seguro hay que actualizar

2022-04-21 13:58 UTC, martinebucarey commented
USUARIO: plammel  
BUILD NUMBER: [6250](http://condorpiedra.andes.gob.ar:85/6250/mochawesome.html)
CYPRESS RUN: [5145](https://dashboard.cypress.io/projects/xr7gft/runs/5145/specs)
TEST START: 2022-04-21T13:56:54.842Z
TOTAL: 406
SUCCESS: 401
FAIL: 4
SKIPPED: 1

2022-04-21 15:42 UTC, martinebucarey commented
USUARIO: plammel  
BUILD NUMBER: [6254](http://condorpiedra.andes.gob.ar:85/6254/mochawesome.html)
CYPRESS RUN: [5149](https://dashboard.cypress.io/projects/xr7gft/runs/5149/specs)
TEST START: 2022-04-21T15:42:14.718Z
TOTAL: 406
SUCCESS: 402
FAIL: 3
SKIPPED: 1

2022-04-21 18:22 UTC, martinebucarey commented
USUARIO: plammel  
BUILD NUMBER: [6257](http://condorpiedra.andes.gob.ar:85/6257/mochawesome.html)
CYPRESS RUN: [5152](https://dashboard.cypress.io/projects/xr7gft/runs/5152/specs)
TEST START: 2022-04-21T18:22:37.347Z
TOTAL: 404
SUCCESS: 402
FAIL: 1
SKIPPED: 1

2022-04-22 16:27 UTC, martinebucarey commented
USUARIO: plammel  
BUILD NUMBER: [6261](http://condorpiedra.andes.gob.ar:85/6261/mochawesome.html)
CYPRESS RUN: [5156](https://dashboard.cypress.io/projects/xr7gft/runs/5156/specs)
TEST START: 2022-04-22T16:26:25.355Z
TOTAL: 357
SUCCESS: 344
FAIL: 12
SKIPPED: 1

2022-04-22 17:02 UTC, martinebucarey commented
USUARIO: plammel  
BUILD NUMBER: [6262](http://condorpiedra.andes.gob.ar:85/6262/mochawesome.html)
CYPRESS RUN: [5157](https://dashboard.cypress.io/projects/xr7gft/runs/5157/specs)
TEST START: 2022-04-22T16:53:14.912Z
TOTAL: 340
SUCCESS: 324
FAIL: 15
SKIPPED: 1

2022-04-25 16:49 UTC, martinebucarey commented
USUARIO: plammel  
BUILD NUMBER: [6274](http://condorpiedra.andes.gob.ar:85/6274/mochawesome.html)
CYPRESS RUN: [5169](https://dashboard.cypress.io/projects/xr7gft/runs/5169/specs)
TEST START: 2022-04-25T16:46:46.831Z
TOTAL: 404
SUCCESS: 401
FAIL: 2
SKIPPED: 1

2022-04-28 14:33 UTC, martinebucarey commented
USUARIO: plammel  
BUILD NUMBER: [6302](http://condorpiedra.andes.gob.ar:85/6302/mochawesome.html)
CYPRESS RUN: [5193](https://dashboard.cypress.io/projects/xr7gft/runs/5193/specs)
TEST START: 2022-04-28T14:33:34.310Z
TOTAL: 404
SUCCESS: 402
FAIL: 1
SKIPPED: 1

2022-04-28 16:52 UTC, martinebucarey commented
USUARIO: plammel  
BUILD NUMBER: [6304](http://condorpiedra.andes.gob.ar:85/6304/mochawesome.html)
CYPRESS RUN: [5195](https://dashboard.cypress.io/projects/xr7gft/runs/5195/specs)
TEST START: 2022-04-28T16:51:19.374Z
TOTAL: 393
SUCCESS: 390
FAIL: 2
SKIPPED: 1

2022-05-16 12:39 UTC, AgosLizzi approved these changes

2022-06-13 12:23 UTC, silviroa requested changes
La tarea plantea realizar un matcheo con los datos básicos de la persona, para la validación...

"Se debería solicitar: Documento, sexo, nombre, apellido, fecha de nacimiento y un numero de matricula."

2022-06-13 12:23 UTC, silviroa commented on src/app/components/profesional/inscripcion-profesionales/inscripcion-profesionales.component.ts
> +            resultado['numeroMatricula'] = ultimaMatricula.matriculaNumero;
La renovación de matriculas va a realizarse para las matriculas de grado. ... por eso pienso que seria mejor mostrar las matriculas de grado (si hay más de una deberían aparecer todas).... no las especialidades (postgrado).

2022-06-13 12:23 UTC, silviroa commented on src/app/components/profesional/inscripcion-profesionales/inscripcion-profesionales.component.ts
> +            resultado['numeroMatricula'] = ultimaMatricula.matriculaNumero;
La renovación de matriculas va a realizarse para las matriculas de grado. ... por eso pienso que seria mejor mostrar las matriculas de grado (si hay más de una deberían aparecer todas).... no las especialidades (postgrado).

2022-06-13 14:40 UTC, plammel commented on src/app/components/profesional/inscripcion-profesionales/inscripcion-profesionales.component.ts
> +            resultado['numeroMatricula'] = ultimaMatricula.matriculaNumero;
@silviroa Actualizado

2022-07-14 15:23 UTC, martinebucarey commented
USUARIO: plammel  
BUILD NUMBER: [6915](http://condorpiedra.andes.gob.ar:85/6915/mochawesome.html)
CYPRESS RUN: [5759](https://dashboard.cypress.io/projects/xr7gft/runs/5759/specs)
TEST START: 2022-07-14T15:23:56.939Z
TOTAL: 406
SUCCESS: 401
FAIL: 4
SKIPPED: 1

2022-08-02 15:54 UTC, silviroa approved these changes

2022-08-03 12:41 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7291](http://condorpiedra.andes.gob.ar:85/7291/mochawesome.html)
CYPRESS RUN: [6049](https://dashboard.cypress.io/projects/xr7gft/runs/6049/specs)
TEST START: 2022-08-03T12:31:46.855Z
TOTAL: 406
SUCCESS: 390
FAIL: 15
SKIPPED: 1

2022-08-03 13:02 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7293](http://condorpiedra.andes.gob.ar:85/7293/mochawesome.html)
CYPRESS RUN: [6051](https://dashboard.cypress.io/projects/xr7gft/runs/6051/specs)
TEST START: 2022-08-03T13:02:27.900Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-08-03 14:25 UTC, martinebucarey approved these changes

2022-08-03 14:35 UTC, merged