RUP: fix buscador clasificacion rup card
andes/app pull request #2623
Opened 2022-04-12 18:51 UTC by plammel

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/RUP-311
### Funcionalidad desarrollada 

1. En buscador de conceptos en RUP, corrige el badge de solicitudes en filtro 'todos'
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2022-04-19 13:36 UTC, martinebucarey reviewed
Probe en demo y en test (sin estar parado en esta rama) y veo bien los dos conceptos, se podria haber fixeado en otro lado?
![imagen](https://user-images.githubusercontent.com/56874534/164016133-a278794b-10db-4a84-8034-c0724f24be24.png)

2022-04-19 18:54 UTC, MCele requested changes
Me aparece un error en el inspector de la pantalla _/dashboard/ambulatorio_ al querer visualizar un registro (no se ven los detalles del registro en el sidebar).

2022-04-20 12:52 UTC, martinebucarey commented
> > Probe en demo y en test (sin estar parado en esta rama) y veo bien los dos conceptos, se podria haber fixeado en otro lado? ![imagen](https://user-images.githubusercontent.com/56874534/164016133-a278794b-10db-4a84-8034-c0724f24be24.png)
> 
> El error está ahi. En el segundo card el badge debería ser "solicitud"

jaaa, alto ciego no se porque creí que era en el icono

2022-04-21 17:01 UTC, MCele approved these changes

2022-04-21 17:12 UTC, martinebucarey approved these changes

2022-04-21 17:25 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [6255](http://condorpiedra.andes.gob.ar:85/6255/mochawesome.html)
CYPRESS RUN: [5150](https://dashboard.cypress.io/projects/xr7gft/runs/5150/specs)
TEST START: 2022-04-21T17:25:24.040Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-04-21 17:26 UTC, merged