IN - Controlar registro de prestaciones fuera del horario de internacion
andes/app pull request #2625
Opened 2022-04-18 15:24 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-402

### Funcionalidad desarrollada 

1. Se agrega control en la fecha y hora de inicio de prestacion para una internacion. Se toma como fecha valida una que este dentro del periodo de internacion del paciente.

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-04-18 15:40 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [6223](http://condorpiedra.andes.gob.ar:85/6223/mochawesome.html)
CYPRESS RUN: [5118](https://dashboard.cypress.io/projects/xr7gft/runs/5118/specs)
TEST START: 2022-04-18T15:40:25.419Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

2022-04-18 17:15 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [6227](http://condorpiedra.andes.gob.ar:85/6227/mochawesome.html)
CYPRESS RUN: [5122](https://dashboard.cypress.io/projects/xr7gft/runs/5122/specs)
TEST START: 2022-04-18T17:14:52.478Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

2022-04-18 19:04 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [6230](http://condorpiedra.andes.gob.ar:85/6230/mochawesome.html)
CYPRESS RUN: [5125](https://dashboard.cypress.io/projects/xr7gft/runs/5125/specs)
TEST START: 2022-04-18T19:04:01.076Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-04-19 14:02 UTC, martinebucarey requested changes
Hay un tema con el control de la hora, se queda bugueado en el mínimo por lo visto.
https://www.loom.com/share/ae33a57717554311a9c0cfcb0ea4c497

2022-04-22 16:41 UTC, negro89 commented
@martinebucarey corregidooo

2022-04-28 14:12 UTC, negro89 commented
> > @martinebucarey corregidooo
> 
> quedo algo raro en la hora che, no me deja borrar y cuando modifico la hora esta raro: https://www.loom.com/share/c0c71fa5cc714edbab5d9401d2ca3f2e

@martinebucarey corregidooo

2022-04-28 19:07 UTC, plammel commented on src/app/apps/rup/mapa-camas/sidebar/nuevo-registro-salud/nuevo-registro-salud.component.ts
> +            this.hora = moment(this.dia || undefined).hours(hora.hours()).minutes(hora.minutes());
entiendo que si `moment` recibe un `undefined`, devolvería la fecha de ahora, es el comportamiento deseado?

2022-05-02 17:18 UTC, martinebucarey approved these changes

2022-05-02 17:18 UTC, martinebucarey commented on src/app/apps/rup/mapa-camas/sidebar/nuevo-registro-salud/nuevo-registro-salud.component.ts
> +            this.hora = moment(this.dia || undefined).hours(hora.hours()).minutes(hora.minutes());
@negro89 revisar comentario para subir si esta todo ok

2022-05-10 13:22 UTC, negro89 commented on src/app/apps/rup/mapa-camas/sidebar/nuevo-registro-salud/nuevo-registro-salud.component.ts
> +            this.hora = moment(this.dia || undefined).hours(hora.hours()).minutes(hora.minutes());
si, es asi @plammel

2022-05-13 11:25 UTC, merged