fix(RUP-313): Error en formulas
andes/app pull request #2628
Opened 2022-04-19 18:02 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/RUP-313

### Funcionalidad desarrollada 
1. Se agregaron condiciones para verificar si el elemento rup tiene el atributo valor editable y de esta forma que se pueda editar manualmente el valor calculado.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-04-19 18:22 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6239](http://condorpiedra.andes.gob.ar:85/6239/mochawesome.html)
CYPRESS RUN: [5134](https://dashboard.cypress.io/projects/xr7gft/runs/5134/specs)
TEST START: 2022-04-19T18:22:27.332Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-04-20 17:32 UTC, MCele commented on src/app/modules/rup/components/elementos/FormulaBase.component.ts
> +    public hasParams;
creo que la variable hasParams es muy general a lo que representa, le cambiaría el nombre a algo más específico como esValorEditable o similar

2022-04-20 17:39 UTC, MCele requested changes

2022-04-21 17:50 UTC, martinebucarey commented
USUARIO: cramos  
BUILD NUMBER: [6256](http://condorpiedra.andes.gob.ar:85/6256/mochawesome.html)
CYPRESS RUN: [5151](https://dashboard.cypress.io/projects/xr7gft/runs/5151/specs)
TEST START: 2022-04-21T17:50:16.164Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-04-21 18:11 UTC, MCele approved these changes

2022-04-21 19:18 UTC, negro89 reviewed
De funcionamiento, excelente. Un par de observaciones en general.
1. Creo que seria necesario comentar el uso de las variables (Las agregue yo en otro PR y no lo hice, mala mia) para poder entender mejor el codigo ya que es confuso:
valorEditable: indica si se puede editar el resultado de la formula manualmente
valorManual: indica si el usuario efectivamente editó manualmente el resultado
2. Despues hay unas indentaciones en el html cuando se llama al componente rup (lineas 10 y 21 y alrededores) que estan mal, y el div de la linea 28 esta de mas.
Por lo demás, todo de 10.

2022-04-25 19:17 UTC, negro89 approved these changes

2022-04-27 14:02 UTC, merged