MISC - No se muestran bien los resultados al filtrar por organizacion
andes/app pull request #2631
Opened 2022-04-21 14:24 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MISC-224

### Funcionalidad desarrollada 
1. Se corrigió el filtro de organizaciones para que pueda filtrar por id y traer los valores correctamente

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-04-21 14:43 UTC, martinebucarey requested changes

2022-04-21 14:43 UTC, martinebucarey commented on src/app/components/reportes/encabezadoReportes.html
> +                                 name="organizacion" [readonly]="totalOrganizaciones || zonaSanitaria">
Con la directiva tmOrganizaciones ya te trae todas las organizaciones, no es necesario ponerle el [data]="organizacion"

2022-04-21 14:45 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6251](http://condorpiedra.andes.gob.ar:85/6251/mochawesome.html)
CYPRESS RUN: [5146](https://dashboard.cypress.io/projects/xr7gft/runs/5146/specs)
TEST START: 2022-04-21T14:45:29.489Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

2022-04-21 15:09 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6252](http://condorpiedra.andes.gob.ar:85/6252/mochawesome.html)
CYPRESS RUN: [5147](https://dashboard.cypress.io/projects/xr7gft/runs/5147/specs)
TEST START: 2022-04-21T15:09:31.428Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-04-27 14:12 UTC, martinebucarey requested changes
Hay un tema acá, en el select de las organizaciones solo aparece la que esta logueada para seleccionar, pero si la borramos va a buscar las prestaciones de todas las organizaciones entonces es medio inconsistente esto. Hablar con @silviroa si se pone como obligatorio el campo orgnaizaciones y permitimos filtrar por todas las organizaciones que el usuario tenga permisos o si se deja readonly el campo y solo se muestran las prestaciones de la organizacion logueada

2022-04-27 14:13 UTC, martinebucarey requested changes
Hay un tema acá, en el select de las organizaciones solo aparece la que esta logueada para seleccionar, pero si la borramos va a buscar las prestaciones de todas las organizaciones entonces es medio inconsistente esto. Hablar con @silviroa si se pone como obligatorio el campo organizaciones y permitimos filtrar por todas las organizaciones que el usuario tenga permisos o si se deja readonly el campo y solo se muestran las prestaciones de la organización logueada

2022-04-28 18:30 UTC, plammel submitted a review, later dismissed

2022-04-28 18:30 UTC, plammel commented on src/app/components/reportes/encabezadoReportes.component.ts
> +        }];
Entiendo que quisiste forzar las opciones con la selección por defecto, pero no estaría funcionando

2022-04-29 17:40 UTC, MarianoCampetella commented on src/app/components/reportes/encabezadoReportes.html
> +                    <plex-select tmOrganizaciones label="Organización" [data]="organizacion"
Corregido

2022-04-29 17:40 UTC, MarianoCampetella commented on src/app/components/reportes/encabezadoReportes.component.ts
> +        }];
Corregido! Ahora el usuario solamente va a poder filtrar por las organizaciones a las cuales tiene permiso.

2022-05-02 15:57 UTC, AgosLizzi approved these changes

2022-05-02 17:38 UTC, martinebucarey requested changes

2022-05-02 17:38 UTC, martinebucarey commented on src/app/components/reportes/encabezadoReportes.component.ts
> +    public organizacionSelected;
Esta variable que se agrego no se esta usando

2022-05-02 19:01 UTC, MarianoCampetella commented on src/app/components/reportes/encabezadoReportes.component.ts
> +    public organizacionSelected;
Corregido!

2022-05-03 11:59 UTC, martinebucarey approved these changes

2022-05-03 12:00 UTC, merged