feat(TOP): agregar campo de busqueda por profesional destino
andes/app pull request #2632
Opened 2022-04-22 18:42 UTC by leon-bravo

### Requerimiento
[TOP-128](https://proyectos.andes.gob.ar/browse/TOP-128)
 

### Funcionalidad desarrollada 

1. Se agrego un filtro por profesional para poder filtrar por profesional destino
2. 
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-04-25 19:10 UTC, negro89 requested changes

2022-04-25 19:10 UTC, negro89 commented on src/app/components/top/solicitudes/solicitudes.component.ts
> +                    if (this.profesionalDestino) {
Aca se escapó dos veces el mismo control

2022-04-26 13:04 UTC, leon-bravo commented on src/app/components/top/solicitudes/solicitudes.component.ts
> +                    if (this.profesionalDestino) {
ahi esta corregido, muchas gracias

2022-04-28 18:59 UTC, plammel approved these changes

2022-04-28 18:59 UTC, plammel commented on src/app/components/top/solicitudes/solicitudes.component.ts
> +                if (this.profesionalDestino?.id) {
```suggestion
            } else if (this.profesionalDestino?.id) {
```

2022-05-02 17:49 UTC, merged