MISC - Agregar filtro por conceptos en el reporte c2
andes/app pull request #2634
Opened 2022-04-26 17:54 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MISC-225

### Funcionalidad desarrollada 

1. Se agrego un nuevo filtro de cie10.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si   https://github.com/andes/api/pull/1701
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-04-28 18:47 UTC, plammel requested changes

2022-04-28 18:47 UTC, plammel commented on src/app/components/reportes/encabezadoReportes.component.ts
> +        if (tipo === 'reporte') {
```suggestion
        } else if (tipo === 'reporte') {
```

2022-04-28 18:47 UTC, plammel commented on src/app/components/reportes/encabezadoReportes.component.ts
> +            (this.tipoReportes?.nombre === 'Reporte C2') ? this.reportes = false : this.reportes = true;
```suggestion
            this.reportes = this.tipoReportes?.nombre === 'Reporte C2';
```

2022-04-28 18:47 UTC, plammel commented on src/app/components/reportes/encabezadoReportes.component.ts
> +        if (event && event.query) {
```suggestion
        if (event?.query) {
```

2022-04-28 18:47 UTC, plammel commented on src/app/components/reportes/encabezadoReportes.component.ts
> +                datos.map(dato => {
`map` si obtenemos un nuevo array, sino `forEach`
```suggestion
                datos.forEach(dato => {
```

2022-04-28 18:47 UTC, plammel commented on src/app/components/reportes/encabezadoReportes.component.ts
> +                datos.map(dato => {
O mejor:
```
const cie10s = datos.map(dato => ({
      id: dato.id,
      nombre: `(${dato.codigo})  ${dato.nombre}`
}))
```
La explicación seria que en lugar de mandar el array con los objetos completos, retornamos unicamente las tuplas `id, nombre` que son los datos que necesitamos para desplegar las opciones

2022-04-29 12:42 UTC, MarianoCampetella commented on src/app/components/reportes/encabezadoReportes.component.ts
> +        if (tipo === 'reporte') {
Corregido!

2022-04-29 12:42 UTC, MarianoCampetella commented on src/app/components/reportes/encabezadoReportes.component.ts
> +            (this.tipoReportes?.nombre === 'Reporte C2') ? this.reportes = false : this.reportes = true;
Corregido.

2022-04-29 12:42 UTC, MarianoCampetella commented on src/app/components/reportes/encabezadoReportes.component.ts
> +        if (event && event.query) {
Corregido.

2022-04-29 12:42 UTC, MarianoCampetella commented on src/app/components/reportes/encabezadoReportes.component.ts
> +                datos.map(dato => {
Corregido!

2022-05-05 12:37 UTC, martinebucarey requested changes

2022-05-05 12:37 UTC, martinebucarey commented on src/app/components/reportes/encabezadoReportes.html
> +                    <plex-select tmOrganizaciones label="Organización"
Ojo!! se estas cambiando lo que hiciste acá https://github.com/andes/app/pull/2631/files#

2022-05-05 17:10 UTC, MarianoCampetella commented on src/app/components/reportes/encabezadoReportes.html
> +                    <plex-select tmOrganizaciones label="Organización"
COrregido!

2022-05-10 17:48 UTC, plammel requested changes

2022-05-10 17:48 UTC, plammel commented on src/app/components/reportes/encabezadoReportes.component.ts
> +            (value.value) ? this.parametros['cie10'] = this.cie10.codigo : this.parametros['cie10'] = null;
```suggestion
            this.parametros['cie10'] = value.value ? this.cie10.codigo : null;
```

2022-05-11 13:17 UTC, MarianoCampetella commented on src/app/components/reportes/encabezadoReportes.component.ts
> +            (value.value) ? this.parametros['cie10'] = this.cie10.codigo : this.parametros['cie10'] = null;
Corregido!

2022-05-11 13:29 UTC, MarianoCampetella commented
> 

En el listado hay códigos como el A51, A53, etc los cuales no existen tanto en demo como en producción. Por esa razón al momento de buscarlos no devuelve ningún resultado. Hay que consultar si faltan cargar los códigos a la BD.

2022-05-13 11:09 UTC, martinebucarey commented
Como el filtro es solo para los reportes C2 solo debería aparecer cuando se selecciona ese reporte, actualmente si cambiamos de reporte sigue apareciendo y se esta enviando como parámetro de la query cuando se realiza la consulta por prestacion, ademas si se cambia de reporte el select queda como readonly y no cambia mas
https://www.loom.com/share/616d3be5f301486e886335373777bb9d

2022-05-16 13:23 UTC, MarianoCampetella commented
> Como el filtro es solo para los reportes C2 solo debería aparecer cuando se selecciona ese reporte, actualmente si cambiamos de reporte sigue apareciendo y se esta enviando como parámetro de la query cuando se realiza la consulta por prestacion, ademas si se cambia de reporte el select queda como readonly y no cambia mas https://www.loom.com/share/616d3be5f301486e886335373777bb9d

Corregido! ahora cada ves que se cambie el reporte a "consultas por prestacion" el filtro desaparece.

2022-06-10 12:07 UTC, martinebucarey approved these changes

2022-06-16 12:24 UTC, martinebucarey commented
Resolver conflictos para subir

2022-06-29 12:29 UTC, martinebucarey commented
Resolver conflictos para subir

2022-06-30 12:45 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6720](http://condorpiedra.andes.gob.ar:85/6720/mochawesome.html)
CYPRESS RUN: [5573](https://dashboard.cypress.io/projects/xr7gft/runs/5573/specs)
TEST START: 2022-06-30T12:45:24.548Z
TOTAL: 408
SUCCESS: 404
FAIL: 0
SKIPPED: 4

2022-06-30 13:48 UTC, martinebucarey commented
https://www.loom.com/share/97985ed5ff114e05829acb0e133469f4

2022-07-01 13:51 UTC, merged