TOP - Agregar filtro por ámbito ambulatorio en reglas
andes/app pull request #2636
Opened 2022-04-27 15:56 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/TOP-127

### Funcionalidad desarrollada 

1. Se agrega un imput a la directiva tmPrestaciones para que pueda filtrar por el ambito que le corresponda.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-04-27 16:16 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6292](http://condorpiedra.andes.gob.ar:85/6292/mochawesome.html)
CYPRESS RUN: [5184](https://dashboard.cypress.io/projects/xr7gft/runs/5184/specs)
TEST START: 2022-04-27T16:16:12.163Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

2022-05-04 13:16 UTC, martinebucarey requested changes
Estuve probando y no esta llegando el ambito=ambulatorio a la directiva, en la consola se ve como sigue en null y por lo tanto me sigue trayendo todos los conceptos turneables.
El console.log esta en el onInit de la directiva

![imagen](https://user-images.githubusercontent.com/56874534/166689062-5e1b2b8b-3f89-4e93-8570-406c52a4fe60.png)

2022-05-04 14:06 UTC, martinebucarey approved these changes

2022-05-06 12:48 UTC, AgosLizzi approved these changes

2022-05-12 13:01 UTC, merged