CIT - Agregar filtro por ambito ambulatorio al crear una agenda
andes/app pull request #2637
Opened 2022-04-28 11:57 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/CIT-168

### Funcionalidad desarrollada 
1. Se agrego un filtro para que al momento de crear una nueva agenda, las prestaciones filtren solamente por ámbito ambulatorio

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-04-28 12:34 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6295](http://condorpiedra.andes.gob.ar:85/6295/mochawesome.html)
CYPRESS RUN: [5186](https://dashboard.cypress.io/projects/xr7gft/runs/5186/specs)
TEST START: 2022-04-28T12:23:06.417Z
TOTAL: 406
SUCCESS: 388
FAIL: 17
SKIPPED: 1

2022-04-28 13:15 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6298](http://condorpiedra.andes.gob.ar:85/6298/mochawesome.html)
CYPRESS RUN: [5189](https://dashboard.cypress.io/projects/xr7gft/runs/5189/specs)
TEST START: 2022-04-28T13:03:43.512Z
TOTAL: 406
SUCCESS: 388
FAIL: 17
SKIPPED: 1

2022-04-28 17:43 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6308](http://condorpiedra.andes.gob.ar:85/6308/mochawesome.html)
CYPRESS RUN: [5199](https://dashboard.cypress.io/projects/xr7gft/runs/5199/specs)
TEST START: 2022-04-28T17:42:50.124Z
TOTAL: 406
SUCCESS: 402
FAIL: 3
SKIPPED: 1

2022-04-28 18:57 UTC, plammel requested changes

2022-04-28 18:57 UTC, plammel commented on src/app/services/conceptos-turneables.service.ts
> +                key: 'conceptos-turneables-' + permisos + ambito,
ojo aca: si alguno de estos parametros no entra y toma el valor `undefined` y se 'suman' algo tipo `'abcdundefined'`. Por otro lado creo q es redundante definir un valor inexistente como `undefined`. Probar esta función en cada posibilidad de input

2022-04-29 15:18 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6318](http://condorpiedra.andes.gob.ar:85/6318/mochawesome.html)
CYPRESS RUN: [5209](https://dashboard.cypress.io/projects/xr7gft/runs/5209/specs)
TEST START: 2022-04-29T15:06:37.263Z
TOTAL: 406
SUCCESS: 342
FAIL: 63
SKIPPED: 1

2022-05-03 13:05 UTC, MarianoCampetella commented on src/app/services/conceptos-turneables.service.ts
> +                key: 'conceptos-turneables-' + permisos + ambito,
Corregido! Se saco las variables definidas con undefined. En cuanto a la concatenación de permisos y ámbito se chequeo en varios lados y no afecta su normal funcionamiento.

2022-05-03 13:35 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6332](http://condorpiedra.andes.gob.ar:85/6332/mochawesome.html)
CYPRESS RUN: [5219](https://dashboard.cypress.io/projects/xr7gft/runs/5219/specs)
TEST START: 2022-05-03T13:35:09.526Z
TOTAL: 106
SUCCESS: 4
FAIL: 102
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-05-03 14:05 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6333](http://condorpiedra.andes.gob.ar:85/6333/mochawesome.html)
CYPRESS RUN: [5220](https://dashboard.cypress.io/projects/xr7gft/runs/5220/specs)
TEST START: 2022-05-03T14:02:03.947Z
TOTAL: 406
SUCCESS: 333
FAIL: 72
SKIPPED: 1

2022-05-03 14:25 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6334](http://condorpiedra.andes.gob.ar:85/6334/mochawesome.html)
CYPRESS RUN: [5221](https://dashboard.cypress.io/projects/xr7gft/runs/5221/specs)
TEST START: 2022-05-03T14:13:29.757Z
TOTAL: 406
SUCCESS: 343
FAIL: 62
SKIPPED: 1

2022-05-10 18:48 UTC, plammel requested changes
Así como se agrega el filtro por ámbito para prestaciones en planificación de agenda, igualmente deberian limitarse las prestaciónes por ambito para el filtro por prestaciones en el buscador del gestor de agendas

2022-05-11 13:50 UTC, MarianoCampetella commented
> Así como se agrega el filtro por ámbito para prestaciones en planificación de agenda, igualmente deberian limitarse las prestaciónes por ambito para el filtro por prestaciones en el buscador del gestor de agendas

No se especificó en la tarea pero se resolvió de todas formas!!

2022-05-11 15:24 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6412](http://condorpiedra.andes.gob.ar:85/6412/mochawesome.html)
CYPRESS RUN: [5294](https://dashboard.cypress.io/projects/xr7gft/runs/5294/specs)
TEST START: 2022-05-11T15:24:41.752Z
TOTAL: 406
SUCCESS: 394
FAIL: 11
SKIPPED: 1

2022-05-12 13:43 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6418](http://condorpiedra.andes.gob.ar:85/6418/mochawesome.html)
CYPRESS RUN: [5300](https://dashboard.cypress.io/projects/xr7gft/runs/5300/specs)
TEST START: 2022-05-12T13:43:22.531Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-05-16 18:34 UTC, plammel approved these changes

2022-05-16 19:03 UTC, martinebucarey commented
USUARIO: plammel  
BUILD NUMBER: [6442](http://condorpiedra.andes.gob.ar:85/6442/mochawesome.html)
CYPRESS RUN: [5324](https://dashboard.cypress.io/projects/xr7gft/runs/5324/specs)
TEST START: 2022-05-16T19:03:33.802Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

2022-05-26 14:15 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6501](http://condorpiedra.andes.gob.ar:85/6501/mochawesome.html)
CYPRESS RUN: [5382](https://dashboard.cypress.io/projects/xr7gft/runs/5382/specs)
TEST START: 2022-05-26T14:15:10.606Z
TOTAL: 320
SUCCESS: 307
FAIL: 12
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-05-26 14:43 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6503](http://condorpiedra.andes.gob.ar:85/6503/mochawesome.html)
CYPRESS RUN: [5384](https://dashboard.cypress.io/projects/xr7gft/runs/5384/specs)
TEST START: 2022-05-26T14:43:10.062Z
TOTAL: 398
SUCCESS: 394
FAIL: 3
SKIPPED: 1

2022-05-26 15:09 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6505](http://condorpiedra.andes.gob.ar:85/6505/mochawesome.html)
CYPRESS RUN: [5386](https://dashboard.cypress.io/projects/xr7gft/runs/5386/specs)
TEST START: 2022-05-26T15:09:09.131Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-06-03 12:56 UTC, martinebucarey approved these changes

2022-06-03 13:05 UTC, merged