MISC - Label de resultados
andes/app pull request #2649
Opened 2022-05-06 15:16 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MISC-233

### Funcionalidad desarrollada 

1. Se agrego un label para informarle al usuario que no se encontró ningún resultado de la búsqueda
2. Se agrego un label para indicarle al usuario, una ves ingresado al modulo de reportes, que es lo que debe hacer.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-05-09 18:53 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6393](http://condorpiedra.andes.gob.ar:85/6393/mochawesome.html)
CYPRESS RUN: [5278](https://dashboard.cypress.io/projects/xr7gft/runs/5278/specs)
TEST START: 2022-05-09T18:53:35.644Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-05-10 12:04 UTC, plammel commented on src/app/components/reportes/encabezadoReportes.html
> +        <div *ngIf="!inicio && estaVacio" justify="center" class="h-50">
Sugiero evaluar directamente el length de los resultados, y prescindir del flag `estaVacio`. De esta manera escribimos menos lineas de código y nos evitamos tener que esta actualizando el flag en el component cada vez que actualizamos los resultados
```suggestion
        <div *ngIf="!inicio && diagnosticos.length" justify="center" class="h-50">
```

2022-05-10 18:44 UTC, MarianoCampetella commented on src/app/components/reportes/encabezadoReportes.html
> +        <div *ngIf="!inicio && estaVacio" justify="center" class="h-50">
Corregido!

2022-05-11 12:09 UTC, martinebucarey requested changes
El label se debería mostrar al momento de apretar en el botón "Generar reporte" sino da confusión que cada vez que se cambie un filtro muestre que no hay resultados como pasa en el video: https://www.loom.com/share/a5bdba1bf3404203aadb83f7940053c3

2022-05-12 16:43 UTC, AgosLizzi submitted a review, later dismissed
Campe, varias cositas sobre este pr:

- El icono que acompaña el label de ayuda al usuario, me parece totalmente aleatorio. Entiendo que tal vez se quiso incorporar "esa flechita" para usar la "lupa" sobre el otro, pero no me parece una decisión correcta.
![image](https://user-images.githubusercontent.com/72876985/168123455-7f595a43-ee32-4490-a318-8ccb1b841f40.png)

- Respecto al segundo label de "No hay resultados para esta búsqueda..." buscaría la manera de que se visualice diferente con respecto al otro. Se podría aplicar algún cambio de color sobre el título principal y un icono que represente bien el mensaje. 

- Dejo este video con un comportamiento raro que sucede. Cuando me salta el mensaje de "No hay resultados..." y aprieto el botón generar reporte, lo genera tranquilamente. En teoría no deberia suceder si me esta avisando por medio de un msj que no hay resultados. Raro
https://www.loom.com/share/dce6e3ee693643e18b5d948d8c476771

2022-05-16 12:14 UTC, MarianoCampetella commented
> El label se debería mostrar al momento de apretar en el botón "Generar reporte" sino da confusión que cada vez que se cambie un filtro muestre que no hay resultados como pasa en el video: https://www.loom.com/share/a5bdba1bf3404203aadb83f7940053c3

Corregido! Se agrego nuevamente la variable booleana estaVacio ya que me va a permitir mostrar solamente el label de resultado vacio y no cuando se edite algún filtro como sucedía antes. También se edito el color de los labels a igual que los símbolos para diferenciarlos.

2022-06-10 16:29 UTC, AgosLizzi approved these changes

2022-06-13 13:47 UTC, merged