CIT - filtrar por ámbito ambulatorio en prestación fuera de agenda
andes/app pull request #2650
Opened 2022-05-10 15:44 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/CIT-175

### Funcionalidad desarrollada 

1. Se agrego el ambito ambulatorio a la directiva de prestaciones
2. se modificaron los filtros para que incluya el ambito ambulatorio en las busquedas de las prestaciones

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-05-12 14:25 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6419](http://condorpiedra.andes.gob.ar:85/6419/mochawesome.html)
CYPRESS RUN: [5301](https://dashboard.cypress.io/projects/xr7gft/runs/5301/specs)
TEST START: 2022-05-12T14:11:08.196Z
TOTAL: 406
SUCCESS: 381
FAIL: 24
SKIPPED: 1

2022-05-16 14:46 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6434](http://condorpiedra.andes.gob.ar:85/6434/mochawesome.html)
CYPRESS RUN: [5316](https://dashboard.cypress.io/projects/xr7gft/runs/5316/specs)
TEST START: 2022-05-16T14:45:41.142Z
TOTAL: 303
SUCCESS: 288
FAIL: 14
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-05-16 15:50 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6437](http://condorpiedra.andes.gob.ar:85/6437/mochawesome.html)
CYPRESS RUN: [5319](https://dashboard.cypress.io/projects/xr7gft/runs/5319/specs)
TEST START: 2022-05-16T15:50:31.397Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-05-19 12:45 UTC, martinebucarey reviewed
En este pr https://github.com/andes/app/pull/2636/files ya se había modificado la directiva, acá se vuelve a modificar por algo??

2022-05-19 12:59 UTC, MarianoCampetella commented
> En este pr https://github.com/andes/app/pull/2636/files ya se había modificado la directiva, acá se vuelve a modificar por algo??

La misma directiva fue modificada en diferentes prs para que se pueda resolver y ver los resultados obtenidos. Con mergear una no seria necesario que en ambos prs esten modificadas.

2022-05-19 13:03 UTC, martinebucarey commented
> > En este pr https://github.com/andes/app/pull/2636/files ya se había modificado la directiva, acá se vuelve a modificar por algo??
> 
> La misma directiva fue modificada en diferentes prs para que se pueda resolver y ver los resultados obtenidos. Con mergear una no seria necesario que en ambos prs esten modificadas.

Por eso mismo, la del pr que te digo ya esta mergeada y acá la volves a modificar. No estan iguales

2022-05-23 14:16 UTC, MarianoCampetella commented on src/app/services/conceptos-turneables.service.ts
> +        return this.search({ permisos, ambito }).pipe(
Corregido, ahora ámbito esta declarado de la misma forma que permisos, en caso de no venir con nada se lo declara como nulo y no pincha en ningún lado!

2022-06-03 13:07 UTC, martinebucarey requested changes
Resolver conflictos

2022-06-08 12:15 UTC, martinebucarey approved these changes

2022-06-08 12:24 UTC, merged