INT: Visualizar información de indicaciones
andes/app pull request #2655
Opened 2022-05-12 18:16 UTC by plammel

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/IN-423
### Funcionalidad desarrollada 

1. Se incluye información adicional de indicaciones en la visualización de plan de indaciones
2. 
3. 

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2022-05-12 18:17 UTC, plammel commented
@AgosLizzi necesito tu magía para ordenar nuevos datos visualizados

2022-05-13 14:08 UTC, AgosLizzi requested changes
Rulo, vi varias cositas en este pr:

1.  Sobre algunas indicaciones no se esta mostrando el icono, te dejo dos ejemplos que vi. 
![cosas02](https://user-images.githubusercontent.com/72876985/168295874-29d5ca2f-52e2-495e-a5b7-5c99abc40e57.JPG)
![no muestra icono](https://user-images.githubusercontent.com/72876985/168295881-bac94016-2779-4d83-a972-50be66896b5b.JPG)
2. El hint aca se corta. Dejo imagen con ejemplo: 
![hint](https://user-images.githubusercontent.com/72876985/168301255-b5517339-b1ec-43cf-80ad-462977c8302a.JPG)
3. Cuando hago mouseover sobre un medicamento hace "como" un amague para abrir el sidebar, me desplaza los badge a un segundo nivel, y cuando doy el click para abrir el sidebar no responde. Dejo un videito con ejemplo: https://www.loom.com/share/840ccb0e843345bb94b3816fc12a7514

2022-05-13 14:15 UTC, AgosLizzi commented
Sigo acá:
- La idea de tener tantos badge en un listado, no me termina de cerar por varias cosas:
1.  La información en ciertos badge es repetitiva. Si en el titulo del medicamento agregado ya tengo la indicaciones del medicamento y dosis, para que repetirla en un badge? 
![listado01](https://user-images.githubusercontent.com/72876985/168302826-15fae937-214e-483a-b2f4-fd21933a5504.JPG)
Esto tal vez podriamos verlo bien con @martinebucarey y @silviroa

2022-05-13 14:46 UTC, plammel commented
> Sigo acá:
> 
> * La idea de tener tantos badge en un listado, no me termina de cerar por varias cosas:
> 
> 1. La información en ciertos badge es repetitiva. Si en el titulo del medicamento agregado ya tengo la indicaciones del medicamento y dosis, para que repetirla en un badge?
>    ![listado01](https://user-images.githubusercontent.com/72876985/168302826-15fae937-214e-483a-b2f4-fd21933a5504.JPG)
>    Esto tal vez podriamos verlo bien con @martinebucarey y @silviroa
> 
> Como consecuencia de esto, empiezan a aparecer varias cosas. Si tengo medicamentos con nombres largos, me hace bajada de lineas que visualmente no quedan agradables y empiezan a deformar el listado en si. ![4 LINEAS](https://user-images.githubusercontent.com/72876985/168303342-f2bf840b-afe6-45d0-8405-e12edbea8259.JPG)
> 
> Se observa también que al abrir el sidebar el título se corta: https://www.loom.com/share/90a31104ac92457284f41fdef968401a

@AgosLizzi gracias Agos!! Se cambiaron los labels por texto tipo bajada del título. Voy a revisar el tema de los iconos, pareciera ser una situación particular en el ambiente de DEMO. Decime como la ves :)

2022-05-13 14:48 UTC, martinebucarey commented
> Se observa también que al abrir el sidebar el título se corta: https://www.loom.com/share/90a31104ac92457284f41fdef968401a

Esto se esta solucionando en una tarea aparte.

2022-05-26 12:46 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [6497](http://condorpiedra.andes.gob.ar:85/6497/mochawesome.html)
CYPRESS RUN: [5378](https://dashboard.cypress.io/projects/xr7gft/runs/5378/specs)
TEST START: 2022-05-26T12:45:46.478Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

2022-05-26 13:17 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [6499](http://condorpiedra.andes.gob.ar:85/6499/mochawesome.html)
CYPRESS RUN: [5380](https://dashboard.cypress.io/projects/xr7gft/runs/5380/specs)
TEST START: 2022-05-26T13:17:06.335Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-05-26 14:13 UTC, merged