feat(MPI): No mostrar inactivos en las relaciones
andes/app pull request #2662
Opened 2022-05-26 16:53 UTC by leon-bravo

### Requerimiento
 
[MPI-383](https://proyectos.andes.gob.ar/browse/MPI-383) - No mostrar pacientes inactivos en las relaciones de un paciente
### Funcionalidad desarrollada 

1. Se modifico el componente de visualización de las relaciones de pacientes para que solo se incluyan los que estan activos
2. 
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-05-26 17:00 UTC, martinebucarey commented
USUARIO: lbravo  
BUILD NUMBER: [6509](http://condorpiedra.andes.gob.ar:85/6509/mochawesome.html)
CYPRESS RUN: [5390](https://dashboard.cypress.io/projects/xr7gft/runs/5390/specs)
TEST START: 2022-05-26T16:59:55.659Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-05-27 18:22 UTC, palita1991 requested changes
https://www.loom.com/share/446df8b870ad4e3eb8a36d0bfaef0c6c
La funcionalidad de inactivar paciente y que luego no aparezcan en el listado, se ve que funciona bien. Pero me dio duda que al principio antes de inactivar al paciente el listado ya era distinto, en mi local estaba conectado a la BD de demo para comparar.

2022-05-31 19:21 UTC, MCele commented
![imagen](https://user-images.githubusercontent.com/19591224/171268025-8603008d-d5a4-4901-aafc-01713c81a746.png)
 me tira un error en la consola con algunos pacientes

2022-06-07 02:45 UTC, leon-bravo commented
> https://www.loom.com/share/446df8b870ad4e3eb8a36d0bfaef0c6c La funcionalidad de inactivar paciente y que luego no aparezcan en el listado, se ve que funciona bien. Pero me dio duda que al principio antes de inactivar al paciente el listado ya era distinto, en mi local estaba conectado a la BD de demo para comparar.

Gracias palita, ahi pude resolverlo, gracias a tu comentario y al de cele. Creo que ya quedo

2022-06-07 02:47 UTC, leon-bravo commented
> ![imagen](https://user-images.githubusercontent.com/19591224/171268025-8603008d-d5a4-4901-aafc-01713c81a746.png) me tira un error en la consola con algunos pacientes. Creo que es en aquellos que no contienene el campo inactivo. (estimo que es lo que muestra el Pala en el video, ya que el paciente que no coincide no tiene el campo "inactivo"). Se debería agregar un control para estos casos

Cele tenias razón, el problema se daba justamente por aquellos pacientes que no tienen el campo activo, el mismo problema ocurre aparentemente en la funcionalidad de inactivar. En el listado de relaciones

2022-06-09 14:04 UTC, plammel approved these changes

2022-06-10 12:27 UTC, martinebucarey requested changes

2022-06-10 12:27 UTC, martinebucarey commented on src/app/modules/mpi/components/paciente-relaciones.component.ts
> +            if (existe) {return rel.activo;} else {return true;}
```suggestion
         rreturn existe ? rel.activo : true;
```

2022-06-16 12:31 UTC, palita1991 approved these changes

2022-06-16 16:52 UTC, MCele approved these changes

2022-06-16 18:33 UTC, merged