Misc 228
andes/app pull request #2668
Opened 2022-06-08 14:20 UTC by leon-bravo

### Requerimiento
 
[MISC-228](https://proyectos.andes.gob.ar/browse/MISC-228) - Agregar filtro a la pantalla de descargas pendientes

### Funcionalidad desarrollada 

1. Se cambio el tamaño del titulo y de los iconos para que sean mas estéticos
2. Se agregaron filtros por fecha desde y hasta, que inician con la fecha del día de hoy
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1719
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-06-09 12:15 UTC, plammel requested changes
Cuando se busca por un día en particular, la búsqueda no arroja resultados. https://www.loom.com/share/7e4169a508bd47288ae9859afc51baad
Por otro lado, si se filtra por fecha estaría bueno mostrar la fecha de la descarga en el detalle de la misma

2022-06-09 14:45 UTC, leon-bravo commented
> Cuando se busca por un día en particular, la búsqueda no arroja resultados. https://www.loom.com/share/7e4169a508bd47288ae9859afc51baad Por otro lado, si se filtra por fecha estaría bueno mostrar la fecha de la descarga en el detalle de la misma

Si tenes razón que es mas informativo, ahí lo agrego

2022-06-10 13:18 UTC, leon-bravo commented
> > Cuando se busca por un día en particular, la búsqueda no arroja resultados. https://www.loom.com/share/7e4169a508bd47288ae9859afc51baad Por otro lado, si se filtra por fecha estaría bueno mostrar la fecha de la descarga en el detalle de la misma
> 
> Si tenes razón que es mas informativo, ahí lo agrego

2022-06-10 13:19 UTC, leon-bravo commented
||

2022-06-10 13:21 UTC, plammel approved these changes

2022-06-10 18:08 UTC, AgosLizzi approved these changes

2022-06-16 12:29 UTC, martinebucarey commented
USUARIO: lbravo  
BUILD NUMBER: [6629](http://condorpiedra.andes.gob.ar:85/6629/mochawesome.html)
CYPRESS RUN: [5483](https://dashboard.cypress.io/projects/xr7gft/runs/5483/specs)
TEST START: 2022-06-16T12:29:40.489Z
TOTAL: 409
SUCCESS: 401
FAIL: 7
SKIPPED: 1

2022-06-16 15:48 UTC, palita1991 approved these changes

2022-06-30 12:14 UTC, martinebucarey commented
USUARIO: lbravo  
BUILD NUMBER: [6718](http://condorpiedra.andes.gob.ar:85/6718/mochawesome.html)
CYPRESS RUN: [5571](https://dashboard.cypress.io/projects/xr7gft/runs/5571/specs)
TEST START: 2022-06-30T12:14:00.081Z
TOTAL: 353
SUCCESS: 338
FAIL: 14
SKIPPED: 1

2022-07-12 14:39 UTC, martinebucarey commented
Ahora que estas con lo de rxjs es el mismo comentario que te hice antes, es mas el next que cambiaste por la subscripcion al evento es para laburar así.

2022-07-28 18:32 UTC, martinebucarey requested changes
Ahora que estas con lo de rxjs es el mismo comentario que te hice antes, es mas el next que cambiaste por la subscripcion al evento es para laburar así.

2022-08-31 16:58 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7549](http://condorpiedra.andes.gob.ar:85/7549/mochawesome.html)
CYPRESS RUN: [6357](https://dashboard.cypress.io/projects/xr7gft/runs/6357/specs)
TEST START: 2022-08-31T16:58:47.453Z
TOTAL: 406
SUCCESS: 402
FAIL: 3
SKIPPED: 1

2022-08-31 17:36 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7551](http://condorpiedra.andes.gob.ar:85/7551/mochawesome.html)
CYPRESS RUN: [6359](https://dashboard.cypress.io/projects/xr7gft/runs/6359/specs)
TEST START: 2022-08-31T17:35:43.530Z
TOTAL: 390
SUCCESS: 380
FAIL: 9
SKIPPED: 1

2022-09-27 13:04 UTC, silviroa commented
revisar Test

2022-09-28 18:06 UTC, MarianoCampetella commented
> revisar Test

Los test que fallaban eran de Exportar HUDS los cuales al modificar los labels de fecha desde y hasta se resuelve el problema.

2022-09-28 19:03 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [7701](http://condorpiedra.andes.gob.ar:85/7701/mochawesome.html)
CYPRESS RUN: [6691](https://dashboard.cypress.io/projects/xr7gft/runs/6691/specs)
TEST START: 2022-09-28T19:02:03.332Z
TOTAL: 390
SUCCESS: 384
FAIL: 5
SKIPPED: 1

2022-10-24 13:04 UTC, MarianoCampetella commented
Resta resolver si se dejan los cambios que estan ahora o se vuelve al commit anterior. Los test ya estan resueltos!

2023-05-10 18:39 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8868](http://condorpiedra.andes.gob.ar:85/8868/mochawesome.html)
CYPRESS RUN: [8035](https://dashboard.cypress.io/projects/xr7gft/runs/8035/specs)
TEST START: 2023-05-10T18:39:14.399Z
TOTAL: 393
SUCCESS: 386
FAIL: 5
SKIPPED: 2

2023-05-10 18:58 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8869](http://condorpiedra.andes.gob.ar:85/8869/mochawesome.html)
CYPRESS RUN: [8036](https://dashboard.cypress.io/projects/xr7gft/runs/8036/specs)
TEST START: 2023-05-10T18:57:24.112Z
TOTAL: 335
SUCCESS: 325
FAIL: 8
SKIPPED: 2

2023-05-11 17:19 UTC, negro89 approved these changes

2023-05-12 17:11 UTC, merged