feat(IN-442): Labels de resultados en pantalla de censos
andes/app pull request #2672
Opened 2022-06-09 12:08 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-442

### Funcionalidad desarrollada 

1. Se agregaron dos labels diferentes para indicarle al usuario como debe comenzar y que no hay resultados de la busqueda que realizó. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-06-10 13:48 UTC, martinebucarey approved these changes

2022-06-10 17:48 UTC, AgosLizzi approved these changes

2022-06-15 16:44 UTC, palita1991 requested changes
@MarianoCampetella El label dice "Generar Reporte" y el botón dice "Generar Censo"

2022-06-15 18:25 UTC, MarianoCampetella commented
> @MarianoCampetella El label dice "Generar Reporte" y el botón dice "Generar Censo"

Corregido!

2022-06-21 11:52 UTC, palita1991 approved these changes

2022-06-30 14:09 UTC, martinebucarey commented
correr test para subir
\

2022-06-30 16:12 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6729](http://condorpiedra.andes.gob.ar:85/6729/mochawesome.html)
CYPRESS RUN: [5582](https://dashboard.cypress.io/projects/xr7gft/runs/5582/specs)
TEST START: 2022-06-30T16:03:06.772Z
TOTAL: 344
SUCCESS: 328
FAIL: 12
SKIPPED: 4

2022-06-30 16:39 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6731](http://condorpiedra.andes.gob.ar:85/6731/mochawesome.html)
CYPRESS RUN: [5584](https://dashboard.cypress.io/projects/xr7gft/runs/5584/specs)
TEST START: 2022-06-30T16:39:07.910Z
TOTAL: 408
SUCCESS: 402
FAIL: 2
SKIPPED: 4

2022-06-30 17:33 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6733](http://condorpiedra.andes.gob.ar:85/6733/mochawesome.html)
CYPRESS RUN: [5586](https://dashboard.cypress.io/projects/xr7gft/runs/5586/specs)
TEST START: 2022-06-30T17:24:16.112Z
TOTAL: 341
SUCCESS: 322
FAIL: 15
SKIPPED: 4

2022-06-30 18:05 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6735](http://condorpiedra.andes.gob.ar:85/6735/mochawesome.html)
CYPRESS RUN: [5588](https://dashboard.cypress.io/projects/xr7gft/runs/5588/specs)
TEST START: 2022-06-30T17:55:36.349Z
TOTAL: 340
SUCCESS: 317
FAIL: 19
SKIPPED: 4

2022-06-30 18:22 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6736](http://condorpiedra.andes.gob.ar:85/6736/mochawesome.html)
CYPRESS RUN: [5589](https://dashboard.cypress.io/projects/xr7gft/runs/5589/specs)
TEST START: 2022-06-30T18:21:56.128Z
TOTAL: 408
SUCCESS: 402
FAIL: 2
SKIPPED: 4

2022-06-30 18:38 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6737](http://condorpiedra.andes.gob.ar:85/6737/mochawesome.html)
CYPRESS RUN: [5590](https://dashboard.cypress.io/projects/xr7gft/runs/5590/specs)
TEST START: 2022-06-30T18:38:02.049Z
TOTAL: 408
SUCCESS: 405
FAIL: -1
SKIPPED: 4

2022-07-01 14:00 UTC, merged