RUP - Componente para visualización de alergias
andes/app pull request #2679
Opened 2022-06-13 12:19 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/RUP-317

### Funcionalidad desarrollada 

1. Nuevo componente para visualizar las alergias del paciente registradas previamente en rup

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1723
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-06-13 13:12 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [6603](http://condorpiedra.andes.gob.ar:85/6603/mochawesome.html)
CYPRESS RUN: [5460](https://dashboard.cypress.io/projects/xr7gft/runs/5460/specs)
TEST START: 2022-06-13T13:12:05.119Z
TOTAL: 383
SUCCESS: 371
FAIL: 11
SKIPPED: 1

2022-06-13 18:43 UTC, plammel requested changes
El info se rompe al abrir el sidebar.
![image](https://user-images.githubusercontent.com/25707055/173422418-5d41f32e-bbcf-4cbc-99b6-c254c8b3bacb.png)
Por otro lado creo que el badge se vería mejor sin estar en negrita.
El resto, ok 👌

2022-06-14 12:25 UTC, AgosLizzi requested changes
Laucha un detalle, cuando agrego las alergias y escribo con salto de linea, como también alguna variante (bold, italic). Te dejo captura:

![real](https://user-images.githubusercontent.com/72876985/173576464-0b0c306f-a985-40c6-8840-71301ecf57c0.JPG)
![saltodelinea](https://user-images.githubusercontent.com/72876985/173576469-1e17b72a-835e-4041-9a70-d2b3491390df.JPG)

2022-06-16 22:03 UTC, negro89 commented
> Laucha un detalle, cuando agrego las alergias y escribo con salto de linea, como también alguna variante (bold, italic). Te dejo captura:
> 
> ![real](https://user-images.githubusercontent.com/72876985/173576464-0b0c306f-a985-40c6-8840-71301ecf57c0.JPG) ![saltodelinea](https://user-images.githubusercontent.com/72876985/173576469-1e17b72a-835e-4041-9a70-d2b3491390df.JPG)

2022-06-16 22:03 UTC, closed without merging

2022-06-21 12:27 UTC, martinebucarey commented
se cerro por error