CITAS - Refactor creación de agenda
andes/app pull request #2680
Opened 2022-06-13 16:00 UTC by palita1991

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-177

### Funcionalidad desarrollada 

1. Notificaciones que salían antes en el footer, ahora se pueden ver en el plex-layout-main y sidebar respectivamente en el sector de arriba.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2022-06-14 13:52 UTC, martinebucarey commented
USUARIO: mpalavecino  
BUILD NUMBER: [6611](http://condorpiedra.andes.gob.ar:85/6611/mochawesome.html)
CYPRESS RUN: [5466](https://dashboard.cypress.io/projects/xr7gft/runs/5466/specs)
TEST START: 2022-06-14T13:52:11.648Z
TOTAL: 409
SUCCESS: 402
FAIL: 6
SKIPPED: 1

2022-06-14 15:24 UTC, plammel requested changes
Algunas observaciones para mejorar:

- Al desplejarse el sidebar, se quiebra el título. 

![image](https://user-images.githubusercontent.com/25707055/173605707-ed43fa54-fb75-4e81-a6ad-b6936593cc00.png)
- Tal vez sería una opción sería llevar el title con la botonera hacia la cabecera del contenedor principal por encima y a lo ancho de los dos layouts (por tamaño y contexto de las acciones). Para evaluar.
- Estos tres campos deberían estar sobre una misma única linea:
![image](https://user-images.githubusercontent.com/25707055/173608080-5a39718b-c7dd-42bd-8612-4961874a2c2f.png)
- Al contraer el sidebar se rompe el layout. Por otro lado, no encuentro mucho sentido en dar la opción de contraer el sidebar, siendo que la mayor densidad del formulario se concentra en ese contenedor.
![image](https://user-images.githubusercontent.com/25707055/173609759-a3256dd1-ea12-46a8-80d7-9f7e9ef7b0d1.png)

- Estos elementos para '%' y 'minutos' entiendo que deberian estar coloreados 'azul info' . Por otro lado estan descuadrados con los campos relacionados.
![image](https://user-images.githubusercontent.com/25707055/173610899-343a7f6d-62d5-4102-b816-5197d11eafd6.png)

- El crear nuevos bloques, no permite seleccionar otros bloques. Tampoco se resalta el elemento de bloque como seleccionado.
- No se están visualizando las alertas de ayuda. 
![image](https://user-images.githubusercontent.com/25707055/173614065-ba626e91-78f1-4cc1-9d6e-de08934076f3.png)

- Estaría bueno hacer otra iteración sobre la distribución/tamaño de los campos. Visualmente da la senseción de estar más ceñido que el form actual.

2022-06-15 11:29 UTC, palita1991 commented
@plammel estuve leyendo los comentarios y no coinciden con lo que subi, creo que quedaste con una version vieja de la rama, igualmente te respondo algunos detalles
![image](https://user-images.githubusercontent.com/30004190/173815832-ee08456a-4c1e-43be-9859-a6d8144664ce.png)

- **No se están visualizando las alertas de ayuda.** -> SI visualizan abajo del los plex-title principales
- **Estos tres campos deberían estar sobre una misma única linea:** -> Como se puede visualizar en la captura que adjunte, estan en la misma linea.
- **Estos elementos para '%' y 'minutos' entiendo que deberian estar coloreados 'azul info' . Por otro lado estan descuadrados con los campos relacionados.** -> Esto se puede evaluar a ver si se pueden modificar con css
- **El crear nuevos bloques, no permite seleccionar otros bloques. Tampoco se resalta el elemento de bloque como seleccionado.** -> esto si se puede y queda seleccionado el bloque que esta seleccionado actualmente
- **Estaría bueno hacer otra iteración sobre la distribución/tamaño de los campos. Visualmente da la senseción de estar más ceñido que el form actual.** -> Estaria bueno ver lo ultimo que subi asi vemos bien esto, porque se hizo lo que estaba en el mockup.
- **Al contraer el sidebar se rompe el layout. Por otro lado, no encuentro mucho sentido en dar la opción de contraer el sidebar, siendo que la mayor densidad del formulario se concentra en ese contenedor.** -> Cuando se abre el sidebar se observan correctamente los campos.
- **Al desplejarse el sidebar, se quiebra el título.** -> Se puede ver que no coincide con el codigo porque los botones estan con size="sm" por lo que no se deberian ver como tus capturas.

2022-06-15 12:00 UTC, martinebucarey commented
USUARIO: mpalavecino  
BUILD NUMBER: [6617](http://condorpiedra.andes.gob.ar:85/6617/mochawesome.html)
CYPRESS RUN: [5472](https://dashboard.cypress.io/projects/xr7gft/runs/5472/specs)
TEST START: 2022-06-15T12:00:11.990Z
TOTAL: 409
SUCCESS: 401
FAIL: 7
SKIPPED: 1

2022-06-15 13:16 UTC, martinebucarey commented
USUARIO: mpalavecino  
BUILD NUMBER: [6620](http://condorpiedra.andes.gob.ar:85/6620/mochawesome.html)
CYPRESS RUN: [5475](https://dashboard.cypress.io/projects/xr7gft/runs/5475/specs)
TEST START: 2022-06-15T13:16:15.191Z
TOTAL: 409
SUCCESS: 390
FAIL: 18
SKIPPED: 1

2022-06-16 11:22 UTC, AgosLizzi approved these changes

2022-06-16 12:06 UTC, martinebucarey commented
USUARIO: mpalavecino  
BUILD NUMBER: [6627](http://condorpiedra.andes.gob.ar:85/6627/mochawesome.html)
CYPRESS RUN: [5481](https://dashboard.cypress.io/projects/xr7gft/runs/5481/specs)
TEST START: 2022-06-16T12:06:14.205Z
TOTAL: 409
SUCCESS: 402
FAIL: 6
SKIPPED: 1

2022-06-21 16:16 UTC, palita1991 commented
> Buenísimo @palita1991 Sigo viendo el resize del sidebar pero ya no hace nada. Si no lo vamos a usar habria que removerlo ![image](https://github.com/assets/25707055/906f8145-15c8-4778-802c-5af928d27e1c)

Corregido @plammel querido :)

2022-07-27 14:39 UTC, martinebucarey approved these changes

2022-07-27 14:47 UTC, merged