FORM - Refactor Form Builder
andes/app pull request #2682
Opened 2022-06-15 13:59 UTC by martinebucarey

### Requerimiento
https://proyectos.andes.gob.ar/browse/EP-107

### Funcionalidad desarrollada 

1. Se completa el refactor del form builder con componentes plex.
2. Se separa la ficha covid19 de las demás fichas que pueden ser creadas desde el form builder. Esto se hace porque la ficha covid tiene mucha lógica propia y se hace imposible generalizar todo.
3. Se agrega un componente para que desde el form builder se pueda configurar uno o mas eventos sisa que luego en la api mediante esta configuración abrirá el evento en el snvs.
4. Se agrega en el FormPresetResourcesService dos secciones que podrán agregarse en el formBuilder de manera automática, estas se definen por base de datos.

### UserStory llegó a completarse

- [ ] Si
- [x] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [x] Si https://github.com/andes/api/pull/1725
- [ ] No

### Requiere actualizaciones en la API

- [x] Si https://github.com/andes/api/pull/1725
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2022-06-16 13:50 UTC, palita1991 requested changes
Al title de configuración sacarle el size para que quede alineado al plex-title de ALTA DE TIPO DE FORMULARIO
![image](https://user-images.githubusercontent.com/30004190/174084565-a3e9b8f7-9746-44cd-bf4f-37ad710f996d.png)

2022-06-16 13:50 UTC, palita1991 commented on src/app/modules/forms-builder/components/form-config/form-config.component.html
> +<plex-button class="float-right mt-1" size="sm" type="success" (click)="addConfig()">Agregar
Una opción es dejarlo ahi donde esta pero son size="md". Otra opcion es dejarlo en size="sm" pero el title de Eventos SNVS

2022-06-16 13:54 UTC, palita1991 commented on src/app/modules/forms-builder/components/forms-crud/forms-crud.component.html
> +                               [items]="itemsDropdown" size="sm" icon="plus" label="">
este plex-dropdown le dejaria el class="mr-1" y quizas podría ir en azul type="info" y el boton de AGREGAR CAMPO con type="success"

2022-06-22 12:09 UTC, martinebucarey commented
@palita1991 modificaciones hechas.

2022-06-23 11:33 UTC, palita1991 approved these changes

2022-06-28 18:34 UTC, AgosLizzi reviewed
Panchito, te dejo un detalle que vi:
- Lo que sucede cuando doy accionar al bool me parece raro, por un lado genera un scroll innecesario, producto de eso da la sensación que los componentes se "mueven" y por el otro, el campo de texto que aparece me queda pegadito al otro bool. 
https://www.loom.com/share/c9d84e962eb148a394e0d072873b780e

Estaba pensando alguna opción para poder "corregir" eso... 
- La primera, habría forma de que los campos de texto "nombre" y "Tipo/clave" ocupen todo el ancho y los bool quedarían por debajo?
- Segunda, generar otro plex title que aloje unicamente los bool. Algo asi (es del mockup para crear agendas):
![ejemplo-09](https://user-images.githubusercontent.com/72876985/176256935-5b37ab7b-8a8c-44a9-ad26-3ed440370a84.jpg)

2022-06-29 12:48 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [6694](http://condorpiedra.andes.gob.ar:85/6694/mochawesome.html)
CYPRESS RUN: [5548](https://dashboard.cypress.io/projects/xr7gft/runs/5548/specs)
TEST START: 2022-06-29T12:47:53.470Z
TOTAL: 408
SUCCESS: 402
FAIL: 2
SKIPPED: 4

2022-06-29 13:29 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [6698](http://condorpiedra.andes.gob.ar:85/6698/mochawesome.html)
CYPRESS RUN: [5552](https://dashboard.cypress.io/projects/xr7gft/runs/5552/specs)
TEST START: 2022-06-29T13:29:13.371Z
TOTAL: 408
SUCCESS: 403
FAIL: 1
SKIPPED: 4

2022-06-29 14:38 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [6703](http://condorpiedra.andes.gob.ar:85/6703/mochawesome.html)
CYPRESS RUN: [5556](https://dashboard.cypress.io/projects/xr7gft/runs/5556/specs)
TEST START: 2022-06-29T14:38:00.230Z
TOTAL: 408
SUCCESS: 403
FAIL: 1
SKIPPED: 4

2022-07-05 11:39 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [6775](http://condorpiedra.andes.gob.ar:85/6775/mochawesome.html)
CYPRESS RUN: [5627](https://dashboard.cypress.io/projects/xr7gft/runs/5627/specs)
TEST START: 2022-07-05T11:39:09.248Z
TOTAL: 409
SUCCESS: 404
FAIL: 3
SKIPPED: 2

2022-08-23 15:12 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7494](http://condorpiedra.andes.gob.ar:85/7494/mochawesome.html)
CYPRESS RUN: [6301](https://dashboard.cypress.io/projects/xr7gft/runs/6301/specs)
TEST START: 2022-08-23T15:12:33.863Z
TOTAL: 406
SUCCESS: 397
FAIL: 8
SKIPPED: 1

2022-08-23 15:59 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7499](http://condorpiedra.andes.gob.ar:85/7499/mochawesome.html)
CYPRESS RUN: [6305](https://dashboard.cypress.io/projects/xr7gft/runs/6305/specs)
TEST START: 2022-08-23T15:56:45.927Z
TOTAL: 397
SUCCESS: 391
FAIL: 5
SKIPPED: 1

2022-08-23 17:13 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7503](http://condorpiedra.andes.gob.ar:85/7503/mochawesome.html)
CYPRESS RUN: [6308](https://dashboard.cypress.io/projects/xr7gft/runs/6308/specs)
TEST START: 2022-08-23T17:13:08.987Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

2022-08-23 17:50 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7504](http://condorpiedra.andes.gob.ar:85/7504/mochawesome.html)
CYPRESS RUN: [6309](https://dashboard.cypress.io/projects/xr7gft/runs/6309/specs)
TEST START: 2022-08-23T17:49:42.657Z
TOTAL: 377
SUCCESS: 369
FAIL: 7
SKIPPED: 1

2022-08-24 13:49 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7509](http://condorpiedra.andes.gob.ar:85/7509/mochawesome.html)
CYPRESS RUN: [6316](https://dashboard.cypress.io/projects/xr7gft/runs/6316/specs)
TEST START: 2022-08-24T13:41:35.905Z
TOTAL: 99
SUCCESS: 0
FAIL: 99
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-08-24 16:56 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7513](http://condorpiedra.andes.gob.ar:85/7513/mochawesome.html)
CYPRESS RUN: [6320](https://dashboard.cypress.io/projects/xr7gft/runs/6320/specs)
TEST START: 2022-08-24T16:56:43.298Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

2022-08-24 17:15 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7514](http://condorpiedra.andes.gob.ar:85/7514/mochawesome.html)
CYPRESS RUN: [6321](https://dashboard.cypress.io/projects/xr7gft/runs/6321/specs)
TEST START: 2022-08-24T17:14:34.243Z
TOTAL: 376
SUCCESS: 366
FAIL: 9
SKIPPED: 1

2022-08-24 17:40 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7515](http://condorpiedra.andes.gob.ar:85/7515/mochawesome.html)
CYPRESS RUN: [6322](https://dashboard.cypress.io/projects/xr7gft/runs/6322/specs)
TEST START: 2022-08-24T17:39:38.875Z
TOTAL: 348
SUCCESS: 340
FAIL: 7
SKIPPED: 1

2022-08-24 18:27 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7516](http://condorpiedra.andes.gob.ar:85/7516/mochawesome.html)
CYPRESS RUN: [6323](https://dashboard.cypress.io/projects/xr7gft/runs/6323/specs)
TEST START: 2022-08-24T18:05:57.245Z
TOTAL: 390
SUCCESS: 374
FAIL: 15
SKIPPED: 1

2022-08-25 14:24 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7522](http://condorpiedra.andes.gob.ar:85/7522/mochawesome.html)
CYPRESS RUN: [6329](https://dashboard.cypress.io/projects/xr7gft/runs/6329/specs)
TEST START: 2022-08-25T14:23:28.044Z
TOTAL: 315
SUCCESS: 306
FAIL: 8
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-08-25 15:06 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7523](http://condorpiedra.andes.gob.ar:85/7523/mochawesome.html)
CYPRESS RUN: [6330](https://dashboard.cypress.io/projects/xr7gft/runs/6330/specs)
TEST START: 2022-08-25T15:06:21.450Z
TOTAL: 406
SUCCESS: 398
FAIL: 7
SKIPPED: 1

2022-08-26 12:56 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7525](http://condorpiedra.andes.gob.ar:85/7525/mochawesome.html)
CYPRESS RUN: [6332](https://dashboard.cypress.io/projects/xr7gft/runs/6332/specs)
TEST START: 2022-08-26T12:55:38.085Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

2022-08-26 13:37 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7526](http://condorpiedra.andes.gob.ar:85/7526/mochawesome.html)
CYPRESS RUN: [6333](https://dashboard.cypress.io/projects/xr7gft/runs/6333/specs)
TEST START: 2022-08-26T13:15:35.082Z
TOTAL: 406
SUCCESS: 400
FAIL: 5
SKIPPED: 1

2022-08-26 16:00 UTC, AgosLizzi requested changes
Algunos detalles visuales, el funcionamento lo veo bien!
1. El botón cancelar aca debería decir **volver** 
![image](https://user-images.githubusercontent.com/72876985/186943505-e2a8b01d-8ff4-4f48-b7d1-db19af5147e5.png)
2. Esta es una pregunta, si yo creo un formulario y por alguna razón lo quiero eliminar, como ejecuto esa acción?
3. Botón configuración esta con color warning. Habría que repensar si realmente estamos configurando, el color debería ser otro. 
4. Cuando tengo activado el **bool snomed** sobre la pantala me realiza doble scroll 
![image](https://user-images.githubusercontent.com/72876985/186945363-98fab636-3dac-4c26-90e9-eabeeae68ff2.png)

2023-04-12 18:23 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [8697](http://condorpiedra.andes.gob.ar:85/8697/mochawesome.html)
CYPRESS RUN: [7872](https://dashboard.cypress.io/projects/xr7gft/runs/7872/specs)
TEST START: 2023-04-12T18:23:05.657Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-04-19 14:51 UTC, silviroa commented
USUARIO: silviroa  
BUILD NUMBER: [8729](http://condorpiedra.andes.gob.ar:85/8729/mochawesome.html)
CYPRESS RUN: [7904](https://dashboard.cypress.io/projects/xr7gft/runs/7904/specs)
TEST START: 2023-04-19T14:51:01.748Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-04-27 14:36 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [8785](http://condorpiedra.andes.gob.ar:85/8785/mochawesome.html)
CYPRESS RUN: [7955](https://dashboard.cypress.io/projects/xr7gft/runs/7955/specs)
TEST START: 2023-04-27T14:34:31.168Z
TOTAL: 5
SUCCESS: 4
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-04-28 12:14 UTC, silviroa commented
USUARIO: silviroa  
BUILD NUMBER: [8794](http://condorpiedra.andes.gob.ar:85/8794/mochawesome.html)
CYPRESS RUN: [7964](https://dashboard.cypress.io/projects/xr7gft/runs/7964/specs)
TEST START: 2023-04-28T12:14:33.714Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-04-28 16:11 UTC, silviroa approved these changes

2023-05-12 18:38 UTC, negro89 commented
@silviroa @MCele en que estado quedó esto? Se corrigio la observacion de agos?

2023-05-16 18:07 UTC, silviroa commented
USUARIO: silviroa  
BUILD NUMBER: [8903](http://condorpiedra.andes.gob.ar:85/8903/mochawesome.html)
CYPRESS RUN: [8068](https://dashboard.cypress.io/projects/xr7gft/runs/8068/specs)
TEST START: 2023-05-16T18:06:00.731Z
TOTAL: 368
SUCCESS: 357
FAIL: 9
SKIPPED: 2

2023-05-16 18:41 UTC, silviroa commented
USUARIO: silviroa  
BUILD NUMBER: [8904](http://condorpiedra.andes.gob.ar:85/8904/mochawesome.html)
CYPRESS RUN: [8069](https://dashboard.cypress.io/projects/xr7gft/runs/8069/specs)
TEST START: 2023-05-16T18:41:29.744Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-05-17 13:14 UTC, merged