CITAS - Limpiar historial de selección de agendas
andes/app pull request #2690
Opened 2022-06-28 11:56 UTC by leon-bravo

### Requerimiento
 
[CIT-179](https://proyectos.andes.gob.ar/browse/CIT-179) - De-seleccionar las agendas seleccionas en el listado de agendas luego de agregar una nueva
### Funcionalidad desarrollada 

1. Al agregar una nueva agenda ahora se de-seleccionan las agendas previamente seleccionadas
2. 
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-06-28 17:24 UTC, AgosLizzi approved these changes

2022-06-29 11:57 UTC, martinebucarey commented
USUARIO: lbravo  
BUILD NUMBER: [6692](http://condorpiedra.andes.gob.ar:85/6692/mochawesome.html)
CYPRESS RUN: [5546](https://dashboard.cypress.io/projects/xr7gft/runs/5546/specs)
TEST START: 2022-06-29T11:57:01.749Z
TOTAL: 338
SUCCESS: 325
FAIL: 9
SKIPPED: 4

2022-06-29 13:36 UTC, martinebucarey requested changes

2022-06-29 13:36 UTC, martinebucarey commented on src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
> +        });
Esta subscripcion a un evento me hace un poco de ruido, primero porque creo que al ser una subscripcion a un evento, si no se desuscribe nunca queda ocupando memoria. Segundo porque me parece que se puede hacer mas performante usando algún BehaviorSubject y de paso te metes en el fantástico mundo de rxjs (hay varios ejemplos en la app para que chusmees). Confirmame @negro89 si esta bien lo que digo porfa

2022-06-29 19:11 UTC, leon-bravo commented on src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
> +        });
santos protones!!! jaja, busco a ver de que se trata, que todavía no lo había visto.

2022-07-05 19:07 UTC, negro89 commented on src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
> +        });
Correctooo, si no se configura una desubscripcion en el ngOnDestroy, se queda escuchando constantemente y quizas no se justifica para la creacion de agendas (Que no tiene interaccion con nada). Por ahi atacarlo por el lado del emit que recibe el gestor a la vuelta del save de la planificacion :+1:

2022-07-13 23:17 UTC, martinebucarey commented
USUARIO: lbravo  
BUILD NUMBER: [6905](http://condorpiedra.andes.gob.ar:85/6905/mochawesome.html)
CYPRESS RUN: [5749](https://dashboard.cypress.io/projects/xr7gft/runs/5749/specs)
TEST START: 2022-07-13T23:17:14.349Z
TOTAL: 409
SUCCESS: 407
FAIL: 1
SKIPPED: 1

2022-07-13 23:40 UTC, martinebucarey commented
USUARIO: lbravo  
BUILD NUMBER: [6906](http://condorpiedra.andes.gob.ar:85/6906/mochawesome.html)
CYPRESS RUN: [5750](https://dashboard.cypress.io/projects/xr7gft/runs/5750/specs)
TEST START: 2022-07-13T23:40:23.718Z
TOTAL: 409
SUCCESS: 407
FAIL: 1
SKIPPED: 1

2022-07-14 12:51 UTC, martinebucarey approved these changes

2022-07-14 12:59 UTC, merged