RUP - Refactor pantalla de paciente autocitado
andes/app pull request #2691
Opened 2022-06-28 15:03 UTC by palita1991

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/RUP-318

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [x] Si https://github.com/andes/andes-test-integracion/pull/440
- [ ] No

2022-06-28 15:27 UTC, martinebucarey commented
USUARIO: mpalavecino  
BUILD NUMBER: [6685](http://condorpiedra.andes.gob.ar:85/6685/mochawesome.html)
CYPRESS RUN: [5539](https://dashboard.cypress.io/projects/xr7gft/runs/5539/specs)
TEST START: 2022-06-28T15:27:45.274Z
TOTAL: 408
SUCCESS: 401
FAIL: 3
SKIPPED: 4

2022-06-28 16:17 UTC, martinebucarey commented
USUARIO: mpalavecino  
BUILD NUMBER: [6689](http://condorpiedra.andes.gob.ar:85/6689/mochawesome.html)
CYPRESS RUN: [5543](https://dashboard.cypress.io/projects/xr7gft/runs/5543/specs)
TEST START: 2022-06-28T16:16:37.513Z
TOTAL: 338
SUCCESS: 321
FAIL: 15
SKIPPED: 2

2022-06-29 16:32 UTC, martinebucarey commented
USUARIO: mpalavecino  
BUILD NUMBER: [6708](http://condorpiedra.andes.gob.ar:85/6708/mochawesome.html)
CYPRESS RUN: [5561](https://dashboard.cypress.io/projects/xr7gft/runs/5561/specs)
TEST START: 2022-06-29T16:32:00.713Z
TOTAL: 408
SUCCESS: 401
FAIL: 3
SKIPPED: 4

2022-06-29 17:36 UTC, martinebucarey commented
USUARIO: mpalavecino  
BUILD NUMBER: [6709](http://condorpiedra.andes.gob.ar:85/6709/mochawesome.html)
CYPRESS RUN: [5562](https://dashboard.cypress.io/projects/xr7gft/runs/5562/specs)
TEST START: 2022-06-29T17:36:37.252Z
TOTAL: 408
SUCCESS: 402
FAIL: 2
SKIPPED: 4

2022-06-29 18:45 UTC, martinebucarey commented
USUARIO: mpalavecino  
BUILD NUMBER: [6711](http://condorpiedra.andes.gob.ar:85/6711/mochawesome.html)
CYPRESS RUN: [5564](https://dashboard.cypress.io/projects/xr7gft/runs/5564/specs)
TEST START: 2022-06-29T18:45:41.135Z
TOTAL: 408
SUCCESS: 401
FAIL: 3
SKIPPED: 4

2022-06-30 12:57 UTC, martinebucarey commented
USUARIO: mpalavecino  
BUILD NUMBER: [6721](http://condorpiedra.andes.gob.ar:85/6721/mochawesome.html)
CYPRESS RUN: [5574](https://dashboard.cypress.io/projects/xr7gft/runs/5574/specs)
TEST START: 2022-06-30T12:57:46.368Z
TOTAL: 408
SUCCESS: 402
FAIL: 2
SKIPPED: 4

2022-07-07 17:14 UTC, AgosLizzi requested changes
Palita, un comentario sobre los modals ...
No veo bien esa "doble confirmación" que surge a raíz de dos modals presentes. Es como si uno de los dos molestara y estaría de más. En mi opinión, solo debe existir uno!

- Si consideramos dejar el primero, seguido al confirmar utilizaría un toast. Y ahí terminaría la acción.
![image](https://user-images.githubusercontent.com/72876985/177830479-9884350e-0202-47d5-915d-5c057bbbfa8e.png)

- Si consideramos dejar el segundo, deberíamos modificarlo un poco. El writing debería ser diferente como también habría que agregar un botón cancelar. Específicamente sobre la parte visual del modal, es posible sacarle todo el espacio en blanco que esta de sobra,(achicarlo)? de está manera se lograría una coherencia visual.
![image](https://user-images.githubusercontent.com/72876985/177830720-f56c2b91-e5df-4105-a2ce-e01915402d6e.png)

te dejo el video por las dudas:
https://www.loom.com/share/e70af92c3cdb4175838198c5865f7369

2022-07-08 15:59 UTC, palita1991 commented
> Palita, un comentario sobre los modals ... No veo bien esa "doble confirmación" que surge a raíz de dos modals presentes. Es como si uno de los dos molestara y estaría de más. En mi opinión, solo debe existir uno!
> 
> * Si consideramos dejar el primero, seguido al confirmar utilizaría un toast. Y ahí terminaría la acción.
>   ![image](https://user-images.githubusercontent.com/72876985/177830479-9884350e-0202-47d5-915d-5c057bbbfa8e.png)
> * Si consideramos dejar el segundo, deberíamos modificarlo un poco. El writing debería ser diferente como también habría que agregar un botón cancelar. Específicamente sobre la parte visual del modal, es posible sacarle todo el espacio en blanco que esta de sobra,(achicarlo)? de está manera se lograría una coherencia visual.
>   ![image](https://user-images.githubusercontent.com/72876985/177830720-f56c2b91-e5df-4105-a2ce-e01915402d6e.png)
> 
> te dejo el video por las dudas: https://www.loom.com/share/e70af92c3cdb4175838198c5865f7369

Corregido

2022-07-08 17:51 UTC, martinebucarey commented
USUARIO: mpalavecino  
BUILD NUMBER: [6835](http://condorpiedra.andes.gob.ar:85/6835/mochawesome.html)
CYPRESS RUN: [5683](https://dashboard.cypress.io/projects/xr7gft/runs/5683/specs)
TEST START: 2022-07-08T17:50:55.356Z
TOTAL: 375
SUCCESS: 360
FAIL: 13
SKIPPED: 2

2022-07-11 15:57 UTC, AgosLizzi approved these changes

2022-08-04 14:33 UTC, martinebucarey reviewed
Se ve de 10, solo me queda una duda con respecto al flujo, no entiendo porque debería apretar en el botón "Dar turno autocitado" para que me muestre las agendas disponibles cuando en el paso anterior, apreté en "Paciente autocitado" por lo menos a mi me confundió un poco. No se si es algo que tiene que estar o no. @AgosLizzi @palita1991 
https://www.loom.com/share/10e8d5be2af34381a92eeac54b96f171

2022-08-05 16:41 UTC, palita1991 commented
> Se ve de 10, solo me queda una duda con respecto al flujo, no entiendo porque debería apretar en el botón "Dar turno autocitado" para que me muestre las agendas disponibles cuando en el paso anterior, apreté en "Paciente autocitado" por lo menos a mi me confundió un poco. No se si es algo que tiene que estar o no. @AgosLizzi @palita1991 https://www.loom.com/share/10e8d5be2af34381a92eeac54b96f171

Corregido @martinebucarey

2022-08-05 17:25 UTC, martinebucarey commented
> > Se ve de 10, solo me queda una duda con respecto al flujo, no entiendo porque debería apretar en el botón "Dar turno autocitado" para que me muestre las agendas disponibles cuando en el paso anterior, apreté en "Paciente autocitado" por lo menos a mi me confundió un poco. No se si es algo que tiene que estar o no. @AgosLizzi @palita1991 https://www.loom.com/share/10e8d5be2af34381a92eeac54b96f171
> 
> Corregido @martinebucarey

esoo ahí me gusto

2022-08-05 17:25 UTC, martinebucarey approved these changes

2022-08-29 15:48 UTC, martinebucarey commented
USUARIO: mpalavecino  
BUILD NUMBER: [7532](http://condorpiedra.andes.gob.ar:85/7532/mochawesome.html)
CYPRESS RUN: [6339](https://dashboard.cypress.io/projects/xr7gft/runs/6339/specs)
TEST START: 2022-08-29T15:47:22.971Z
TOTAL: 335
SUCCESS: 315
FAIL: 19
SKIPPED: 1

2022-09-19 11:42 UTC, silviroa commented
USUARIO: mpalavecino  
BUILD NUMBER: [7659](http://condorpiedra.andes.gob.ar:85/7659/mochawesome.html)
CYPRESS RUN: [6590](https://dashboard.cypress.io/projects/xr7gft/runs/6590/specs)
TEST START: 2022-09-19T11:42:09.929Z
TOTAL: 406
SUCCESS: 402
FAIL: 3
SKIPPED: 1

2022-09-19 12:25 UTC, silviroa commented
USUARIO: mpalavecino  
BUILD NUMBER: [7660](http://condorpiedra.andes.gob.ar:85/7660/mochawesome.html)
CYPRESS RUN: [6591](https://dashboard.cypress.io/projects/xr7gft/runs/6591/specs)
TEST START: 2022-09-19T12:23:02.456Z
TOTAL: 4
SUCCESS: 2
FAIL: 2
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-09-19 12:39 UTC, silviroa commented
USUARIO: mpalavecino  
BUILD NUMBER: [7661](http://condorpiedra.andes.gob.ar:85/7661/mochawesome.html)
CYPRESS RUN: [6592](https://dashboard.cypress.io/projects/xr7gft/runs/6592/specs)
TEST START: 2022-09-19T12:37:52.882Z
TOTAL: 4
SUCCESS: 4
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-09-19 12:41 UTC, silviroa commented
USUARIO: mpalavecino  
BUILD NUMBER: [7662](http://condorpiedra.andes.gob.ar:85/7662/mochawesome.html)
CYPRESS RUN: [6593](https://dashboard.cypress.io/projects/xr7gft/runs/6593/specs)
TEST START: 2022-09-19T12:41:23.171Z
TOTAL: 4
SUCCESS: 4
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-10-19 18:15 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7797](http://condorpiedra.andes.gob.ar:85/7797/mochawesome.html)
CYPRESS RUN: [6935](https://dashboard.cypress.io/projects/xr7gft/runs/6935/specs)
TEST START: 2022-10-19T18:15:34.371Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

2022-10-19 18:29 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [7798](http://condorpiedra.andes.gob.ar:85/7798/mochawesome.html)
CYPRESS RUN: [6936](https://dashboard.cypress.io/projects/xr7gft/runs/6936/specs)
TEST START: 2022-10-19T18:19:40.643Z
TOTAL: 406
SUCCESS: 390
FAIL: 15
SKIPPED: 1

2022-10-19 18:39 UTC, MarianoCampetella approved these changes

2022-10-20 15:58 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7805](http://condorpiedra.andes.gob.ar:85/7805/mochawesome.html)
CYPRESS RUN: [6942](https://dashboard.cypress.io/projects/xr7gft/runs/6942/specs)
TEST START: 2022-10-20T15:58:07.008Z
TOTAL: 398
SUCCESS: 389
FAIL: 8
SKIPPED: 1

2022-10-21 13:22 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7814](http://condorpiedra.andes.gob.ar:85/7814/mochawesome.html)
CYPRESS RUN: [6951](https://dashboard.cypress.io/projects/xr7gft/runs/6951/specs)
TEST START: 2022-10-21T13:21:56.445Z
TOTAL: 406
SUCCESS: 398
FAIL: 7
SKIPPED: 1

2022-10-25 15:47 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [7840](http://condorpiedra.andes.gob.ar:85/7840/mochawesome.html)
CYPRESS RUN: [6975](https://dashboard.cypress.io/projects/xr7gft/runs/6975/specs)
TEST START: 2022-10-25T15:44:04.014Z
TOTAL: 406
SUCCESS: 382
FAIL: 23
SKIPPED: 1

2022-10-25 15:59 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [7841](http://condorpiedra.andes.gob.ar:85/7841/mochawesome.html)
CYPRESS RUN: [6976](https://dashboard.cypress.io/projects/xr7gft/runs/6976/specs)
TEST START: 2022-10-25T15:58:40.546Z
TOTAL: 406
SUCCESS: 402
FAIL: 3
SKIPPED: 1

2022-10-25 18:05 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [7842](http://condorpiedra.andes.gob.ar:85/7842/mochawesome.html)
CYPRESS RUN: [6977](https://dashboard.cypress.io/projects/xr7gft/runs/6977/specs)
TEST START: 2022-10-25T18:04:44.933Z
TOTAL: 406
SUCCESS: 397
FAIL: 8
SKIPPED: 1

2022-11-08 17:22 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7878](http://condorpiedra.andes.gob.ar:85/7878/mochawesome.html)
CYPRESS RUN: [7016](https://dashboard.cypress.io/projects/xr7gft/runs/7016/specs)
TEST START: 2022-11-08T17:20:47.484Z
TOTAL: 382
SUCCESS: 374
FAIL: 7
SKIPPED: 1

2022-11-08 17:57 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7880](http://condorpiedra.andes.gob.ar:85/7880/mochawesome.html)
CYPRESS RUN: [7020](https://dashboard.cypress.io/projects/xr7gft/runs/7020/specs)
TEST START: 2022-11-08T17:57:31.317Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

2022-11-08 18:13 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7881](http://condorpiedra.andes.gob.ar:85/7881/mochawesome.html)
CYPRESS RUN: [7023](https://dashboard.cypress.io/projects/xr7gft/runs/7023/specs)
TEST START: 2022-11-08T18:03:55.062Z
TOTAL: 406
SUCCESS: 390
FAIL: 15
SKIPPED: 1

2022-11-08 18:27 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7882](http://condorpiedra.andes.gob.ar:85/7882/mochawesome.html)
CYPRESS RUN: [7026](https://dashboard.cypress.io/projects/xr7gft/runs/7026/specs)
TEST START: 2022-11-08T18:27:18.417Z
TOTAL: 397
SUCCESS: 396
FAIL: 0
SKIPPED: 1

2022-11-08 18:57 UTC, merged