IN - Nueva prescripcion disponible hasta siguiente medio dia
andes/app pull request #2699
Opened 2022-07-05 17:52 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-445

### Funcionalidad desarrollada 

1. Al crear una nueva prescripción, se marcan los horarios de la indicación en la grilla  a modo de visualización.. Estos eventos quedan en espera ('on-hold').
2. Nuevo servicio para recurso 'constantes' que funcionan de insumo para el select de 'frecuencia'.
3. Se edita algun contenido visual en el sidebar.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [X] Si [Coleccion **constantes**](https://proyectos.andes.gob.ar/secure/attachment/12430/Consulta%20insert%20constantes)
- [ ] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1732
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-07-06 12:16 UTC, martinebucarey requested changes
Si no registro una frecuencia, no me deja agregar un horario para el caso en el que quiera activar el campo 'única vez'
https://www.loom.com/share/ff01e75956c4451196a69164267281cd

2022-07-12 15:22 UTC, negro89 commented
@martinebucarey corregido

2022-07-14 13:51 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [6913](http://condorpiedra.andes.gob.ar:85/6913/mochawesome.html)
CYPRESS RUN: [5757](https://dashboard.cypress.io/projects/xr7gft/runs/5757/specs)
TEST START: 2022-07-14T13:50:49.768Z
TOTAL: 409
SUCCESS: 372
FAIL: 36
SKIPPED: 1

2022-07-22 19:18 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7096](http://condorpiedra.andes.gob.ar:85/7096/mochawesome.html)
CYPRESS RUN: [5883](https://dashboard.cypress.io/projects/xr7gft/runs/5883/specs)
TEST START: 2022-07-22T19:17:48.639Z
TOTAL: 409
SUCCESS: 372
FAIL: 36
SKIPPED: 1

2022-08-01 17:22 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7255](http://condorpiedra.andes.gob.ar:85/7255/mochawesome.html)
CYPRESS RUN: [6013](https://dashboard.cypress.io/projects/xr7gft/runs/6013/specs)
TEST START: 2022-08-01T17:22:00.737Z
TOTAL: 389
SUCCESS: 347
FAIL: 41
SKIPPED: 1

2022-08-02 17:32 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7283](http://condorpiedra.andes.gob.ar:85/7283/mochawesome.html)
CYPRESS RUN: [6041](https://dashboard.cypress.io/projects/xr7gft/runs/6041/specs)
TEST START: 2022-08-02T17:32:27.577Z
TOTAL: 408
SUCCESS: 373
FAIL: 34
SKIPPED: 1

2022-08-02 17:46 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7284](http://condorpiedra.andes.gob.ar:85/7284/mochawesome.html)
CYPRESS RUN: [6042](https://dashboard.cypress.io/projects/xr7gft/runs/6042/specs)
TEST START: 2022-08-02T17:44:01.471Z
TOTAL: 321
SUCCESS: 285
FAIL: 35
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-08-02 18:38 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7285](http://condorpiedra.andes.gob.ar:85/7285/mochawesome.html)
CYPRESS RUN: [6043](https://dashboard.cypress.io/projects/xr7gft/runs/6043/specs)
TEST START: 2022-08-02T18:29:41.481Z
TOTAL: 378
SUCCESS: 332
FAIL: 45
SKIPPED: 1

2022-08-03 11:20 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7288](http://condorpiedra.andes.gob.ar:85/7288/mochawesome.html)
CYPRESS RUN: [6046](https://dashboard.cypress.io/projects/xr7gft/runs/6046/specs)
TEST START: 2022-08-03T11:20:40.311Z
TOTAL: 408
SUCCESS: 371
FAIL: 36
SKIPPED: 1

2022-08-03 12:20 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7290](http://condorpiedra.andes.gob.ar:85/7290/mochawesome.html)
CYPRESS RUN: [6048](https://dashboard.cypress.io/projects/xr7gft/runs/6048/specs)
TEST START: 2022-08-03T12:20:39.025Z
TOTAL: 392
SUCCESS: 353
FAIL: 38
SKIPPED: 1

2022-08-03 12:53 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7292](http://condorpiedra.andes.gob.ar:85/7292/mochawesome.html)
CYPRESS RUN: [6050](https://dashboard.cypress.io/projects/xr7gft/runs/6050/specs)
TEST START: 2022-08-03T12:53:27.202Z
TOTAL: 408
SUCCESS: 373
FAIL: 34
SKIPPED: 1

2022-08-03 14:50 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7294](http://condorpiedra.andes.gob.ar:85/7294/mochawesome.html)
CYPRESS RUN: [6052](https://dashboard.cypress.io/projects/xr7gft/runs/6052/specs)
TEST START: 2022-08-03T14:48:50.954Z
TOTAL: 215
SUCCESS: 162
FAIL: 53
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-08-03 15:15 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7295](http://condorpiedra.andes.gob.ar:85/7295/mochawesome.html)
CYPRESS RUN: [6053](https://dashboard.cypress.io/projects/xr7gft/runs/6053/specs)
TEST START: 2022-08-03T15:15:08.899Z
TOTAL: 406
SUCCESS: 369
FAIL: 36
SKIPPED: 1

2022-08-03 16:23 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7296](http://condorpiedra.andes.gob.ar:85/7296/mochawesome.html)
CYPRESS RUN: [6054](https://dashboard.cypress.io/projects/xr7gft/runs/6054/specs)
TEST START: 2022-08-03T16:22:37.169Z
TOTAL: 99
SUCCESS: 0
FAIL: 99
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-08-04 11:22 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7303](http://condorpiedra.andes.gob.ar:85/7303/mochawesome.html)
CYPRESS RUN: [6061](https://dashboard.cypress.io/projects/xr7gft/runs/6061/specs)
TEST START: 2022-08-04T11:21:52.920Z
TOTAL: 406
SUCCESS: 371
FAIL: 34
SKIPPED: 1

2022-08-10 15:51 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7388](http://condorpiedra.andes.gob.ar:85/7388/mochawesome.html)
CYPRESS RUN: [6134](https://dashboard.cypress.io/projects/xr7gft/runs/6134/specs)
TEST START: 2022-08-10T15:49:51.825Z
TOTAL: 99
SUCCESS: 0
FAIL: 99
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-08-10 17:25 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7393](http://condorpiedra.andes.gob.ar:85/7393/mochawesome.html)
CYPRESS RUN: [6139](https://dashboard.cypress.io/projects/xr7gft/runs/6139/specs)
TEST START: 2022-08-10T17:25:33.587Z
TOTAL: 406
SUCCESS: 370
FAIL: 35
SKIPPED: 1

2022-08-10 18:09 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7396](http://condorpiedra.andes.gob.ar:85/7396/mochawesome.html)
CYPRESS RUN: [6142](https://dashboard.cypress.io/projects/xr7gft/runs/6142/specs)
TEST START: 2022-08-10T18:09:23.200Z
TOTAL: 406
SUCCESS: 371
FAIL: 34
SKIPPED: 1

2022-08-10 18:51 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7397](http://condorpiedra.andes.gob.ar:85/7397/mochawesome.html)
CYPRESS RUN: [6143](https://dashboard.cypress.io/projects/xr7gft/runs/6143/specs)
TEST START: 2022-08-10T18:50:46.862Z
TOTAL: 406
SUCCESS: 371
FAIL: 34
SKIPPED: 1

2022-08-11 13:34 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7400](http://condorpiedra.andes.gob.ar:85/7400/mochawesome.html)
CYPRESS RUN: [6147](https://dashboard.cypress.io/projects/xr7gft/runs/6147/specs)
TEST START: 2022-08-11T13:33:33.742Z
TOTAL: 99
SUCCESS: 0
FAIL: 99
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-08-11 13:50 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7402](http://condorpiedra.andes.gob.ar:85/7402/mochawesome.html)
CYPRESS RUN: [6148](https://dashboard.cypress.io/projects/xr7gft/runs/6148/specs)
TEST START: 2022-08-11T13:50:03.092Z
TOTAL: 406
SUCCESS: 364
FAIL: 41
SKIPPED: 1

2022-08-11 14:02 UTC, AgosLizzi requested changes
Lauti, las funcionalidades del pr las veo bien, pero cuando empeizo a agregar indicaciones, suspenderla, etc. me aparecen estos errores en la consola 
![2022-08-11 (2)](https://user-images.githubusercontent.com/72876985/184151561-362090f2-26a6-40b9-b9bc-f111d2ff24b8.png)

2022-08-11 14:23 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7403](http://condorpiedra.andes.gob.ar:85/7403/mochawesome.html)
CYPRESS RUN: [6149](https://dashboard.cypress.io/projects/xr7gft/runs/6149/specs)
TEST START: 2022-08-11T14:21:47.333Z
TOTAL: 99
SUCCESS: 0
FAIL: 99
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-08-11 16:17 UTC, negro89 commented
@AgosLizzi corregido. Eso pasa cuando no se completa algun campo del formulario (Esta bien) y despues quiere visualizarse el contenido. Es algo para corregir en plex, cuando hay un label dentro de in grid sin subtitulo.
Lo voy a agregar como tarea de plex para @palita1991 jejejejj

2022-08-11 17:54 UTC, AgosLizzi approved these changes

2022-08-11 18:12 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7406](http://condorpiedra.andes.gob.ar:85/7406/mochawesome.html)
CYPRESS RUN: [6155](https://dashboard.cypress.io/projects/xr7gft/runs/6155/specs)
TEST START: 2022-08-11T18:12:24.356Z
TOTAL: 406
SUCCESS: 371
FAIL: 34
SKIPPED: 1

2022-08-11 18:53 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7407](http://condorpiedra.andes.gob.ar:85/7407/mochawesome.html)
CYPRESS RUN: [6156](https://dashboard.cypress.io/projects/xr7gft/runs/6156/specs)
TEST START: 2022-08-11T18:52:14.365Z
TOTAL: 365
SUCCESS: 329
FAIL: 35
SKIPPED: 1

2022-08-12 12:27 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7409](http://condorpiedra.andes.gob.ar:85/7409/mochawesome.html)
CYPRESS RUN: [6162](https://dashboard.cypress.io/projects/xr7gft/runs/6162/specs)
TEST START: 2022-08-12T12:27:06.067Z
TOTAL: 406
SUCCESS: 370
FAIL: 35
SKIPPED: 1

2022-08-12 12:52 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [7410](http://condorpiedra.andes.gob.ar:85/7410/mochawesome.html)
CYPRESS RUN: [6163](https://dashboard.cypress.io/projects/xr7gft/runs/6163/specs)
TEST START: 2022-08-12T12:51:47.846Z
TOTAL: 398
SUCCESS: 362
FAIL: 35
SKIPPED: 1

2022-08-12 16:36 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7413](http://condorpiedra.andes.gob.ar:85/7413/mochawesome.html)
CYPRESS RUN: [6166](https://dashboard.cypress.io/projects/xr7gft/runs/6166/specs)
TEST START: 2022-08-12T16:36:17.862Z
TOTAL: 406
SUCCESS: 370
FAIL: 35
SKIPPED: 1

2022-08-17 12:26 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7428](http://condorpiedra.andes.gob.ar:85/7428/mochawesome.html)
CYPRESS RUN: [6220](https://dashboard.cypress.io/projects/xr7gft/runs/6220/specs)
TEST START: 2022-08-17T12:25:56.047Z
TOTAL: 406
SUCCESS: 369
FAIL: 36
SKIPPED: 1

2022-08-17 18:06 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7443](http://condorpiedra.andes.gob.ar:85/7443/mochawesome.html)
CYPRESS RUN: [6243](https://dashboard.cypress.io/projects/xr7gft/runs/6243/specs)
TEST START: 2022-08-17T18:06:09.549Z
TOTAL: 402
SUCCESS: 365
FAIL: 36
SKIPPED: 1

2022-08-17 18:20 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7444](http://condorpiedra.andes.gob.ar:85/7444/mochawesome.html)
CYPRESS RUN: [6244](https://dashboard.cypress.io/projects/xr7gft/runs/6244/specs)
TEST START: 2022-08-17T18:19:12.438Z
TOTAL: 365
SUCCESS: 347
FAIL: 17
SKIPPED: 1

2022-08-17 18:57 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7445](http://condorpiedra.andes.gob.ar:85/7445/mochawesome.html)
CYPRESS RUN: [6245](https://dashboard.cypress.io/projects/xr7gft/runs/6245/specs)
TEST START: 2022-08-17T18:36:08.985Z
TOTAL: 291
SUCCESS: 263
FAIL: 27
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-08-18 18:28 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7454](http://condorpiedra.andes.gob.ar:85/7454/mochawesome.html)
CYPRESS RUN: [6260](https://dashboard.cypress.io/projects/xr7gft/runs/6260/specs)
TEST START: 2022-08-18T18:28:32.361Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

2022-08-22 16:41 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7475](http://condorpiedra.andes.gob.ar:85/7475/mochawesome.html)
CYPRESS RUN: [6284](https://dashboard.cypress.io/projects/xr7gft/runs/6284/specs)
TEST START: 2022-08-22T16:41:05.662Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

2022-08-22 17:24 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7477](http://condorpiedra.andes.gob.ar:85/7477/mochawesome.html)
CYPRESS RUN: [6286](https://dashboard.cypress.io/projects/xr7gft/runs/6286/specs)
TEST START: 2022-08-22T17:22:57.793Z
TOTAL: 386
SUCCESS: 377
FAIL: 8
SKIPPED: 1

2022-08-22 19:37 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7483](http://condorpiedra.andes.gob.ar:85/7483/mochawesome.html)
CYPRESS RUN: [6291](https://dashboard.cypress.io/projects/xr7gft/runs/6291/specs)
TEST START: 2022-08-22T19:37:10.143Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

2022-08-23 13:49 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7489](http://condorpiedra.andes.gob.ar:85/7489/mochawesome.html)
CYPRESS RUN: [6298](https://dashboard.cypress.io/projects/xr7gft/runs/6298/specs)
TEST START: 2022-08-23T13:49:03.421Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

2022-08-23 15:48 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7498](http://condorpiedra.andes.gob.ar:85/7498/mochawesome.html)
CYPRESS RUN: [6304](https://dashboard.cypress.io/projects/xr7gft/runs/6304/specs)
TEST START: 2022-08-23T15:48:10.098Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-08-23 16:51 UTC, martinebucarey approved these changes

2022-08-23 16:51 UTC, merged