IN - Agregar restricciones de visualizacion en capa interconsultores
andes/app pull request #2700
Opened 2022-07-11 12:45 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-462

### Funcionalidad desarrollada 

1. Se eliminaron los botones: desocupar, editar cama, admitir paciente, nuevo recurso, deshacer internacion, internar paciente, bloquear y prestar/desocupar

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-07-14 12:10 UTC, AgosLizzi approved these changes

2022-07-19 11:22 UTC, martinebucarey commented on src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
> +        public mapaCamasService: MapaCamasService,
Esto por que se cambio a public??

2022-07-19 11:22 UTC, martinebucarey commented on src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
> +                                    || (relacion.nombre === 'Bloquear' && permisosMapaCamasService.bloqueo && !cama.sala))">
Se podria aprovechar y pasarse al componente este ngIf interminable:
https://github.com/andes/app/wiki#template-html

2022-07-19 13:15 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
> +        public mapaCamasService: MapaCamasService,
Corregido! se paso a private

2022-07-19 13:22 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
> +                                    || (relacion.nombre === 'Bloquear' && permisosMapaCamasService.bloqueo && !cama.sala))">
Corregido! se agrego el enorme *ngIf en una variable

2022-07-20 12:31 UTC, martinebucarey requested changes

2022-07-20 12:31 UTC, martinebucarey commented on src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.ts
> +        public mapaCamasService: MapaCamasService,
esto es lo mismo que lo anterior

2022-07-21 12:51 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
> +            (relacion[0].nombre === 'Bloquear' && this.permisosMapaCamasService.bloqueo && !this.cama.sala)));
Corregido! ahora esta implementada en una función!

2022-07-21 12:51 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.ts
> +        public mapaCamasService: MapaCamasService,
Corregido!

2022-07-21 15:19 UTC, martinebucarey submitted a review, later dismissed

2022-07-21 15:19 UTC, martinebucarey commented on src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
> +    public relacionesYpermisos;
esta quedo de mas

2022-07-21 15:33 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
> +    public relacionesYpermisos;
Corregido

2022-08-04 13:31 UTC, martinebucarey commented
Resolver conflictos

2022-08-05 12:16 UTC, MarianoCampetella commented
> Resolver conflictos

Resueltos!!

2022-09-29 19:23 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [7712](http://condorpiedra.andes.gob.ar:85/7712/mochawesome.html)
CYPRESS RUN: [6703](https://dashboard.cypress.io/projects/xr7gft/runs/6703/specs)
TEST START: 2022-09-29T19:14:10.478Z
TOTAL: 406
SUCCESS: 390
FAIL: 15
SKIPPED: 1

2022-09-29 20:04 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [7714](http://condorpiedra.andes.gob.ar:85/7714/mochawesome.html)
CYPRESS RUN: [6705](https://dashboard.cypress.io/projects/xr7gft/runs/6705/specs)
TEST START: 2022-09-29T20:03:52.042Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

2022-09-30 15:31 UTC, MCele approved these changes

2022-09-30 16:49 UTC, merged