IN (Fix): Error al inactivar cama
andes/app pull request #2703
Opened 2022-07-11 19:41 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-463

### Funcionalidad desarrollada 

1. Se refactorean algunos request y se reemplaza una funcion por un observable ya que no se subscribia correctamente
2. Además se corrige la redireccion al guardar, ya que volvía a solicitar capa para ingresar al mapa de camas

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-07-15 13:58 UTC, martinebucarey requested changes

2022-07-15 13:58 UTC, martinebucarey commented on src/app/apps/rup/mapa-camas/views/cama/cama.component.ts
> +                this.plex.info('warning', 'ERROR: Ocurrio un problema al guardar la cama');
Este info debería ser danger me parece

2022-07-15 13:58 UTC, martinebucarey commented on src/app/apps/rup/mapa-camas/views/cama/cama.component.ts
> +                    this.plex.info('warning', 'ERROR: Ocurrio un problema al guardar la cama');
```suggestion
                    this.plex.info('danger', 'ERROR: Ocurrio un problema al guardar la cama');
```

2022-07-15 13:58 UTC, martinebucarey commented on src/app/apps/rup/mapa-camas/views/cama/cama.component.ts
> +import { Observable, forkJoin, of } from 'rxjs';
```suggestion
import { Observable, forkJoin} from 'rxjs';
```

2022-07-15 13:58 UTC, martinebucarey commented on src/app/apps/rup/mapa-camas/views/cama/cama.component.html
> +                             [disabled]="!(verificarBaja$ | async) || disabled" label="INACTIVAR CAMA" type="warning"
este doble pipe async hace dos suscripciones, se podría evitar esto usando cache() que evita multiples suscripciones a un mismo observable, lo dejo en la linea donde se creo el verificarBaja$

2022-07-15 13:58 UTC, martinebucarey commented on src/app/apps/rup/mapa-camas/views/cama/cama.component.ts
> +        );
```suggestion
        this.verificarBaja$ = this.capas$.pipe(
            map(capas => {
                let contador = 0;
                capas.map(capa => {
                    const maquinaEstados = this.infoCama[capa][0];
                    const snap = this.infoCama[capa][1];
                    if (maquinaEstados) {
                        for (const relacion of maquinaEstados.relaciones) {
                            if ((relacion.destino === 'inactiva') && (relacion.origen === snap?.estado)) {
                                contador++;
                            }
                        }
                    }
                });
                return (contador === capas.length);
            }),
            cache()
        );
```

2022-07-20 11:07 UTC, martinebucarey approved these changes

2022-07-20 18:04 UTC, plammel approved these changes

2022-07-22 16:08 UTC, palita1991 approved these changes

2022-07-22 18:39 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7094](http://condorpiedra.andes.gob.ar:85/7094/mochawesome.html)
CYPRESS RUN: [5881](https://dashboard.cypress.io/projects/xr7gft/runs/5881/specs)
TEST START: 2022-07-22T18:39:03.042Z
TOTAL: 409
SUCCESS: 407
FAIL: 1
SKIPPED: 1

2022-07-25 12:42 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7101](http://condorpiedra.andes.gob.ar:85/7101/mochawesome.html)
CYPRESS RUN: [5888](https://dashboard.cypress.io/projects/xr7gft/runs/5888/specs)
TEST START: 2022-07-25T12:42:36.922Z
TOTAL: 409
SUCCESS: 408
FAIL: 0
SKIPPED: 1

2022-07-25 13:59 UTC, merged