feat(INT): registra eventos solo validadas
andes/app pull request #2708
Opened 2022-07-19 18:07 UTC by plammel

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/IN-470
### Funcionalidad desarrollada 

1. Se permite registrar eventos solo para indicaciones validadas 
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2022-07-25 12:17 UTC, AgosLizzi requested changes
Rulo, la tarea principal del pr funciona, si no estan validadas no me deja marcar completa/incompleta/ no realizada. Pero al querer validar y marcar, me sucede lo siguiente:
https://www.loom.com/share/b5b9aab51d2545dabf507d9e406d44df
Sobre la consola me aparece esto:
![image](https://user-images.githubusercontent.com/72876985/180775756-9dc1d9f3-3028-4ac3-948b-fe927a5a1968.png)

2022-08-19 18:30 UTC, plammel commented
> Rulo, la tarea principal del pr funciona, si no estan validadas no me deja marcar completa/incompleta/ no realizada. Pero al querer validar y marcar, me sucede lo siguiente: https://www.loom.com/share/b5b9aab51d2545dabf507d9e406d44df

El error no está relacionado a estos cambios. Habría q reportarlo e incluirlo al backlog

2022-08-22 11:11 UTC, AgosLizzi approved these changes

2022-12-29 16:51 UTC, silviroa approved these changes

2022-12-29 16:58 UTC, silviroa commented
USUARIO: silviroa  
BUILD NUMBER: [8184](http://condorpiedra.andes.gob.ar:85/8184/mochawesome.html)
CYPRESS RUN: [7371](https://dashboard.cypress.io/projects/xr7gft/runs/7371/specs)
TEST START: 2022-12-29T16:57:10.238Z
TOTAL: 388
SUCCESS: 381
FAIL: 5
SKIPPED: 2

2022-12-29 17:25 UTC, silviroa commented
USUARIO: silviroa  
BUILD NUMBER: [8186](http://condorpiedra.andes.gob.ar:85/8186/mochawesome.html)
CYPRESS RUN: [7372](https://dashboard.cypress.io/projects/xr7gft/runs/7372/specs)
TEST START: 2022-12-29T17:25:14.298Z
TOTAL: 406
SUCCESS: 396
FAIL: 8
SKIPPED: 2

2022-12-29 17:49 UTC, silviroa commented
USUARIO: silviroa  
BUILD NUMBER: [8187](http://condorpiedra.andes.gob.ar:85/8187/mochawesome.html)
CYPRESS RUN: [7373](https://dashboard.cypress.io/projects/xr7gft/runs/7373/specs)
TEST START: 2022-12-29T17:49:15.228Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-02-24 19:06 UTC, negro89 approved these changes

2023-03-03 13:30 UTC, merged