IN - formulario egreso estadistico
andes/app pull request #2709
Opened 2022-07-20 16:51 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-476

### Funcionalidad desarrollada 

1.  Se agregaron nuevos filtros para buscar los codigos cie10 según corresponda

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-08-18 18:02 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7452](http://condorpiedra.andes.gob.ar:85/7452/mochawesome.html)
CYPRESS RUN: [6258](https://dashboard.cypress.io/projects/xr7gft/runs/6258/specs)
TEST START: 2022-08-18T18:02:16.347Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-08-18 18:49 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7456](http://condorpiedra.andes.gob.ar:85/7456/mochawesome.html)
CYPRESS RUN: [6262](https://dashboard.cypress.io/projects/xr7gft/runs/6262/specs)
TEST START: 2022-08-18T18:49:24.664Z
TOTAL: 356
SUCCESS: 354
FAIL: 1
SKIPPED: 1

2022-08-18 19:02 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7457](http://condorpiedra.andes.gob.ar:85/7457/mochawesome.html)
CYPRESS RUN: [6263](https://dashboard.cypress.io/projects/xr7gft/runs/6263/specs)
TEST START: 2022-08-18T19:02:13.331Z
TOTAL: 356
SUCCESS: 353
FAIL: 2
SKIPPED: 1

2022-08-19 13:59 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7459](http://condorpiedra.andes.gob.ar:85/7459/mochawesome.html)
CYPRESS RUN: [6266](https://dashboard.cypress.io/projects/xr7gft/runs/6266/specs)
TEST START: 2022-08-19T13:51:14.205Z
TOTAL: 99
SUCCESS: 0
FAIL: 99
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-08-22 16:16 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7473](http://condorpiedra.andes.gob.ar:85/7473/mochawesome.html)
CYPRESS RUN: [6282](https://dashboard.cypress.io/projects/xr7gft/runs/6282/specs)
TEST START: 2022-08-22T16:15:41.234Z
TOTAL: 323
SUCCESS: 288
FAIL: 34
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-08-22 17:42 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7478](http://condorpiedra.andes.gob.ar:85/7478/mochawesome.html)
CYPRESS RUN: [6287](https://dashboard.cypress.io/projects/xr7gft/runs/6287/specs)
TEST START: 2022-08-22T17:41:41.012Z
TOTAL: 406
SUCCESS: 402
FAIL: 3
SKIPPED: 1

2022-08-22 18:05 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7479](http://condorpiedra.andes.gob.ar:85/7479/mochawesome.html)
CYPRESS RUN: [6288](https://dashboard.cypress.io/projects/xr7gft/runs/6288/specs)
TEST START: 2022-08-22T18:05:12.413Z
TOTAL: 402
SUCCESS: 400
FAIL: 1
SKIPPED: 1

2022-08-22 18:34 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7480](http://condorpiedra.andes.gob.ar:85/7480/mochawesome.html)
CYPRESS RUN: [6289](https://dashboard.cypress.io/projects/xr7gft/runs/6289/specs)
TEST START: 2022-08-22T18:24:42.748Z
TOTAL: 394
SUCCESS: 377
FAIL: 16
SKIPPED: 1

2022-08-24 15:48 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7512](http://condorpiedra.andes.gob.ar:85/7512/mochawesome.html)
CYPRESS RUN: [6319](https://dashboard.cypress.io/projects/xr7gft/runs/6319/specs)
TEST START: 2022-08-24T15:48:10.945Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-09-27 12:13 UTC, negro89 commented
Hay comentarios sin responder en el pr!

2022-09-27 12:14 UTC, negro89 requested changes

2022-09-27 12:15 UTC, negro89 commented
Hay comentarios sin responder en este pr! requesteo cambios para llamar la atencion

2022-11-22 13:30 UTC, silviroa requested changes

2022-11-22 13:30 UTC, silviroa commented on src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
> +                    filtro = [{ desde: 'Y40', hasta: 'Y98' }];
Este cambio debería agregar el rango de 'Y40' al Y98 al que ya estaba (V01 a la X60) no reemplazarlo

2022-11-24 11:16 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
> +                    filtro = [{ desde: 'Y40', hasta: 'Y98' }];
Corregido!

2022-11-29 13:46 UTC, silviroa approved these changes

2022-11-29 14:05 UTC, silviroa commented
USUARIO: silviroa  
BUILD NUMBER: [8032](http://condorpiedra.andes.gob.ar:85/8032/mochawesome.html)
CYPRESS RUN: [7225](https://dashboard.cypress.io/projects/xr7gft/runs/7225/specs)
TEST START: 2022-11-29T14:05:09.482Z
TOTAL: 406
SUCCESS: 397
FAIL: 7
SKIPPED: 2

2022-11-29 14:17 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8033](http://condorpiedra.andes.gob.ar:85/8033/mochawesome.html)
CYPRESS RUN: [7226](https://dashboard.cypress.io/projects/xr7gft/runs/7226/specs)
TEST START: 2022-11-29T14:16:47.432Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2022-11-29 15:19 UTC, merged