IN - boton volver en plan de indicaciones
andes/app pull request #2710
Opened 2022-07-20 17:49 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-472

### Funcionalidad desarrollada 
1. Se corrigio el boton volver del plan de indicacion y se agrego en una nueva funcion la direccion a la cual debe volver. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-07-20 18:30 UTC, plammel approved these changes

2022-07-22 15:56 UTC, palita1991 approved these changes

2022-07-25 11:58 UTC, AgosLizzi requested changes
Campe, sobre el botón volver perfecto, la función es correcta. Tengo una duda, cada vez que agrego alguna medicación me cambia de lugar las acciones para validar /suspender ...

![2022-07-25 (1)](https://user-images.githubusercontent.com/72876985/180772587-6cbc4e18-b6a2-4a40-bde0-68a7b192c253.png)
![2022-07-25 (2)](https://user-images.githubusercontent.com/72876985/180772589-8a931981-7ed1-4a86-888c-6baa6915de3a.png)

Se muestran a la izquierda, cuando deberían aparecer sobre la derecha

2022-07-25 16:05 UTC, MarianoCampetella commented
> Campe, sobre el botón volver perfecto, la función es correcta. Tengo una duda, cada vez que agrego alguna medicación me cambia de lugar las acciones para validar /suspender ...
> 
> ![2022-07-25 (1)](https://user-images.githubusercontent.com/72876985/180772587-6cbc4e18-b6a2-4a40-bde0-68a7b192c253.png) ![2022-07-25 (2)](https://user-images.githubusercontent.com/72876985/180772589-8a931981-7ed1-4a86-888c-6baa6915de3a.png)
> 
> Se muestran a la izquierda, cuando deberían aparecer sobre la derecha

Corregido!!

2022-07-26 13:50 UTC, martinebucarey commented on src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
> +                                        Validar Pendientes
Estos cambios de donde salieron??

2022-07-26 13:50 UTC, martinebucarey commented on src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
> +import { Router } from '@angular/router';
Ya esta arriba importado @angular/router agregar el import ahi

2022-07-26 14:39 UTC, AgosLizzi approved these changes

2022-07-26 14:51 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
> +import { Router } from '@angular/router';
Corregido!

2022-07-26 14:53 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
> +                                        Validar Pendientes
Acá no se agrego código sino que por una cuestión de identacion al momento de guardar cambios hechos en el html (borrado de comentario) se acomodaron y figuran de esa manera.

2022-07-26 15:10 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7136](http://condorpiedra.andes.gob.ar:85/7136/mochawesome.html)
CYPRESS RUN: [5917](https://dashboard.cypress.io/projects/xr7gft/runs/5917/specs)
TEST START: 2022-07-26T15:08:50.197Z
TOTAL: 343
SUCCESS: 332
FAIL: 10
SKIPPED: 1

2022-07-26 15:37 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7138](http://condorpiedra.andes.gob.ar:85/7138/mochawesome.html)
CYPRESS RUN: [5919](https://dashboard.cypress.io/projects/xr7gft/runs/5919/specs)
TEST START: 2022-07-26T15:37:04.993Z
TOTAL: 409
SUCCESS: 408
FAIL: 0
SKIPPED: 1

2022-07-27 12:53 UTC, merged