IN: acciones solo indicacion del dia
andes/app pull request #2713
Opened 2022-07-22 16:51 UTC by plammel

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/IN-464
### Funcionalidad desarrollada 

1. habilitar continuar y suspender solo indicaciones del día
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2022-07-22 18:44 UTC, palita1991 approved these changes

2022-07-25 11:15 UTC, AgosLizzi approved these changes

2022-07-25 14:33 UTC, martinebucarey commented
USUARIO: plammel  
BUILD NUMBER: [7108](http://condorpiedra.andes.gob.ar:85/7108/mochawesome.html)
CYPRESS RUN: [5895](https://dashboard.cypress.io/projects/xr7gft/runs/5895/specs)
TEST START: 2022-07-25T14:33:05.623Z
TOTAL: 409
SUCCESS: 401
FAIL: 7
SKIPPED: 1

2022-08-19 12:45 UTC, negro89 requested changes

2022-08-19 12:45 UTC, negro89 commented on src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
> +                                    <plex-button *ngIf="isToday && (detener$ | async)" type="danger" icon="stop" size="sm"
El control deberpia realizarse teniendo en cuenta que los turnos del plan van de 6am de hoy a 6am del dia siguiente para que no haya inconvenientes en la franja horaria de 00.00 a 05.59 hs.
Por otro lado, dejo captura de indicacion actualizada por ultima vez uan semana atras y que permite continuar y suspender.

![image](https://user-images.githubusercontent.com/37875706/185620454-4bb659a7-0fc6-47bd-baeb-d24f6c02f8bf.png)

2023-03-13 17:39 UTC, MCele commented
se resuelve en otra tarea

2023-03-13 17:40 UTC, MCele commented
se resuelve en otra tarea

2023-03-13 17:40 UTC, closed without merging