TOP: no se visualiza el estado correcto de la solicitud
andes/app pull request #2715
Opened 2022-07-25 12:55 UTC by leon-bravo

### Requerimiento
 
[HUDS-51](https://proyectos.andes.gob.ar/browse/HUDS-51) - No se visualiza el estado correcto de la solicitud
### Funcionalidad desarrollada 

1. Se modifico la busqueda para que traiga todas las prestaciones de una sola ves y con el campo de prestacion de forma adecuada
2. 
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si  https://github.com/andes/api/pull/1735
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-07-25 19:24 UTC, plammel requested changes

2022-07-25 19:24 UTC, plammel commented on src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
> -            this.servicioPrestacion.getByPacienteSolicitud(this.paciente.id).subscribe((solicitudes) => {
No hay remover este request! Las solicitudes pueden venir de top y desde rup, por eso se consultan de dos fuentes y se concatenan `cargarSolicitudesMezcladas` . Ver que dejaron de visualizarse las prescripciones de medicamentos

2022-07-29 16:28 UTC, martinebucarey commented
USUARIO: lbravo  
BUILD NUMBER: [7231](http://condorpiedra.andes.gob.ar:85/7231/mochawesome.html)
CYPRESS RUN: [5989](https://dashboard.cypress.io/projects/xr7gft/runs/5989/specs)
TEST START: 2022-07-29T16:28:13.963Z
TOTAL: 365
SUCCESS: 357
FAIL: 7
SKIPPED: 1

2022-08-24 02:09 UTC, leon-bravo commented on src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
> -            this.servicioPrestacion.getByPacienteSolicitud(this.paciente.id).subscribe((solicitudes) => {
como en este caso se requeria recuperar ambos ingresos, top y rup, se opto por modificar el api y que traiga ambos ingresos juntos asi nos ahorramos una busqueda y el tener que ordenarlos, el pr que modifica el api es  el  https://github.com/andes/api/pull/1735/files

2022-08-24 13:54 UTC, plammel commented on src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
> -            this.servicioPrestacion.getByPacienteSolicitud(this.paciente.id).subscribe((solicitudes) => {
Como mencioné, hay solicitudes asociadas a turnos que se consultan en TOP, y hay solicitudes (x ej. las de internación), que no tienen turno asociado y se consultan a prestaciones (RUP).
Ver siguiente caso de prueba:
https://www.loom.com/share/1ef1c3bff44a46328acb4199e1fae7a7

2022-08-24 13:59 UTC, plammel commented on src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
> -            this.servicioPrestacion.getByPacienteSolicitud(this.paciente.id).subscribe((solicitudes) => {
Este requerimiento está relacionado con display de badges. A priori no habría que tocar nada relacionado a la api o a los requests, sino los condicionales que "calculan" los bagdes en los htmls o los pipes, según corresponda

2022-08-26 17:15 UTC, plammel commented
Valdiar si se soluciona con https://github.com/andes/app/pull/2746

2023-01-20 17:33 UTC, negro89 commented
se resuelve con https://github.com/andes/app/pull/2746

2023-01-20 17:33 UTC, closed without merging