feat(BI-127): Permisos en organizaciones
andes/app pull request #2717
Opened 2022-07-25 15:02 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/BI-127

### Funcionalidad desarrollada 

1. Se modifico la ruta donde se obtienen las organizaciones en el modulo de bi-queries
2. Se agrego el select para unidades organizativas.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si   https://github.com/andes/api/pull/1737
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-07-25 16:02 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7114](http://condorpiedra.andes.gob.ar:85/7114/mochawesome.html)
CYPRESS RUN: [5901](https://dashboard.cypress.io/projects/xr7gft/runs/5901/specs)
TEST START: 2022-07-25T16:01:20.356Z
TOTAL: 366
SUCCESS: 358
FAIL: 8
SKIPPED: 0

2022-07-25 18:51 UTC, plammel requested changes

2022-07-25 18:51 UTC, plammel commented on src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
> +            this.organizaciones$ = this.server.get('/auth/bi-queries/organizaciones').pipe(
el GET a esa ruta no se debería hacer desde el component, sino a traves del servicio de auth

2022-07-26 14:44 UTC, MarianoCampetella commented on src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
> +            this.organizaciones$ = this.server.get('/auth/bi-queries/organizaciones').pipe(
Corregido!!

2022-07-26 15:49 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7139](http://condorpiedra.andes.gob.ar:85/7139/mochawesome.html)
CYPRESS RUN: [5920](https://dashboard.cypress.io/projects/xr7gft/runs/5920/specs)
TEST START: 2022-07-26T15:49:26.374Z
TOTAL: 409
SUCCESS: 408
FAIL: 0
SKIPPED: 1

2022-07-27 12:57 UTC, martinebucarey requested changes

2022-07-27 12:57 UTC, martinebucarey commented on src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
> +import { Server } from '@andes/shared';
Este import esta de mas

2022-07-27 12:57 UTC, martinebucarey commented on src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
> +        private server: Server
```suggestion

```

2022-07-27 12:57 UTC, martinebucarey commented on projects/auth/src/lib/auth.service.ts
> +            refCount()
Estos operadores por que se agregaron?? veo que hay una sola suscripción en el componente

2022-07-28 18:30 UTC, MarianoCampetella commented on src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
> +import { Server } from '@andes/shared';
Corregido!

2022-07-28 18:30 UTC, MarianoCampetella commented on src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
> +        private server: Server
Corregido!

2022-07-28 18:31 UTC, MarianoCampetella commented on projects/auth/src/lib/auth.service.ts
> +            refCount()
Corregido! Los operadores fueron sacados ya que no son necesarios!

2022-07-28 18:33 UTC, martinebucarey commented on projects/auth/src/lib/auth.service.ts
> +            refCount()
Era una pregunta de si estaban por algo, no para que los saques

2022-07-28 18:48 UTC, MarianoCampetella commented on projects/auth/src/lib/auth.service.ts
> +            refCount()
No estaban por algo en particual. Como el comportamiento es el mismo este o no esten se decidio sacarlo.

2023-02-09 19:54 UTC, negro89 approved these changes

2023-02-10 14:38 UTC, MCele approved these changes

2023-02-14 17:22 UTC, merged