IN - Permitir validar indicaciones selecccionadas
andes/app pull request #2719
Opened 2022-07-26 20:23 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-474

### Funcionalidad desarrollada 

1. Si se seleccionan solo indicaciones en estado **borrador** se habilita un dropdown _validar indicaciones -> seleccionadas_.
De lo contrario continúa vigente la opción de validar pendientes.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-07-27 14:53 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7163](http://condorpiedra.andes.gob.ar:85/7163/mochawesome.html)
CYPRESS RUN: [5941](https://dashboard.cypress.io/projects/xr7gft/runs/5941/specs)
TEST START: 2022-07-27T14:44:04.552Z
TOTAL: 408
SUCCESS: 392
FAIL: 15
SKIPPED: 1

2022-07-27 17:11 UTC, plammel commented on src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
> +        const indicaciones = seleccionadas ? Object.keys(this.selectedIndicacion).filter(k => this.selectedIndicacion[k]).map(k => this.indicaciones.find(i => i.id === k)) : this.indicaciones;
Se hace un poco confuso el filtrado y comparación de indicaciones seleccionadas. Una opción un poco mas elegante podría ser en `onSelectedChange` mantener un array adicional con las ids de los drafts seleccionadas, para no necesitar filtrar el array de indicaciones seleccionadas cada vez

2022-07-27 17:11 UTC, plammel commented on src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
> +        const indicaciones = seleccionadas ? Object.keys(this.selectedIndicacion).filter(k => this.selectedIndicacion[k]).map(k => this.indicaciones.find(i => i.id === k)) : this.indicaciones;
Ya existe un atributo de clase con el nombre `indicaciones`

2022-07-27 17:11 UTC, plammel commented on src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
> +                                        <plex-dropdown right="true" size="sm" label="Validar indicaciones"
```suggestion
                     <plex-dropdown *ngIf="borradores.length" right="true" size="sm" label="Validar indicaciones"
```

2022-07-29 11:19 UTC, AgosLizzi requested changes
Lauti, no me cierra la propuesta. La primera pregunta que me hago como persona usuaria sería...
¿Cúal de estas indicaciones que estoy viendo corresponde al termino "pendientes"?
![image](https://user-images.githubusercontent.com/72876985/181747682-d5b52f16-9043-4085-80b6-da7b11589492.png)

Buscaría una propuesta que sea más facil de identificar y no genere dudas. Te dejo como ejemplo el sidebar del gestor de agendas:
![image](https://user-images.githubusercontent.com/72876985/181748303-83d6ebc5-f99f-4af7-b464-8650a71718a1.png)
![image](https://user-images.githubusercontent.com/72876985/181748344-b39d9c15-461d-4739-bae8-ebbafae564a8.png)

2022-07-29 14:24 UTC, negro89 commented on src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
> +                return i.estadoActual.tipo !== 'draft' || moment(i.createdAt).isBetween(inicioDia, finDia, null, '[)');
Esta no seria una comparación de dia, sino de un rango horario. Los dias en el cronograma del plan inician a las 6am y finalizan mismo horario pero del dia siguiente. Es por eso que no sirve el isSame en este caso.

2022-07-29 14:36 UTC, negro89 commented on src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
> +            this.borradores = this.indicaciones.filter(i => i.estado.tipo === 'draft');
El filtro de fraft del dia deja pasar las prescripciones activas. Se podria adaptar el codigo para que queden juntos (la sugerencia y el bloque en cuestion) pero no evitariamos 'filtrar' dos veces

2022-07-29 14:53 UTC, negro89 commented on src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
> +        const indicaciones = seleccionadas ? Object.keys(this.selectedIndicacion).filter(k => this.selectedIndicacion[k]).map(k => this.indicaciones.find(i => i.id === k)) : this.indicaciones;
Te referis a un array para la clase o una constante para la funcion? Esa funcion ya tiene una constante **arraySeleccion**.
Si es la primera opción quizás se pueda pensar una tarea para cambiar el objeto **selectedIndicacion** y convertirlo en un array. Asi no se suman cosas para testear en esta tarea.

2022-07-29 14:55 UTC, negro89 commented on src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
> +                                        <plex-dropdown right="true" size="sm" label="Validar indicaciones"
corregidooo

2022-07-29 15:17 UTC, negro89 commented
@AgosLizzi las indicaciones pendientes son aquellas que estan como 'borrador' (En el caso de tu captura son todas). Eso un usuario, previa capacitación, lo sabe.
El boton 'validar pendientes' actualmente existe solo que se ve de otra manera (Dejo captura), en la tarea solo se agrega el dropdown para agrupar esta acción con la nueva 'validar seleccionadas'. 
De todas maneras quizas se pueda reveer, porque en caso de existir indicaciones 'pendientes de revisión' tambien se puede prestar a confusión por la palabra 'pendiente'.
![image](https://user-images.githubusercontent.com/37875706/181790591-3921b684-8bca-4857-9f0f-3c0b9ee931f6.png)

2022-08-01 16:54 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7253](http://condorpiedra.andes.gob.ar:85/7253/mochawesome.html)
CYPRESS RUN: [6011](https://dashboard.cypress.io/projects/xr7gft/runs/6011/specs)
TEST START: 2022-08-01T16:54:29.568Z
TOTAL: 408
SUCCESS: 406
FAIL: 1
SKIPPED: 1

2022-08-02 15:07 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7276](http://condorpiedra.andes.gob.ar:85/7276/mochawesome.html)
CYPRESS RUN: [6034](https://dashboard.cypress.io/projects/xr7gft/runs/6034/specs)
TEST START: 2022-08-02T14:59:05.661Z
TOTAL: 99
SUCCESS: 0
FAIL: 99
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-08-10 16:55 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7391](http://condorpiedra.andes.gob.ar:85/7391/mochawesome.html)
CYPRESS RUN: [6137](https://dashboard.cypress.io/projects/xr7gft/runs/6137/specs)
TEST START: 2022-08-10T16:54:48.929Z
TOTAL: 355
SUCCESS: 354
FAIL: 0
SKIPPED: 1

2022-08-10 17:24 UTC, negro89 commented
@AgosLizzi @martinebucarey reemplazamos 'validar pendientes' por 'validar borradores' ??

2022-08-10 17:26 UTC, martinebucarey commented
> @AgosLizzi @martinebucarey reemplazamos 'validar pendientes' por 'validar borradores' ??
Me suena un poco menos confuso, pero la que sabe es la piba ui/ux

2022-08-11 11:02 UTC, AgosLizzi commented
@martinebucarey Ahí lo charle con Lauti, me parece mejor que quede "validar borradores" + dropdow (1- selccionadas /1 todas)

2022-08-19 11:02 UTC, martinebucarey commented
> @negro89 @martinebucarey Ahí lo charle con Lauti, me parece mejor que quede "validar borradores" + dropdow (1- selccionadas /1 todas)

Oka , no veo este cambio todavia lo dejo aca por las dudas

2022-08-19 18:58 UTC, negro89 commented
@AgosLizzi al fin corregidoooo :smile:

2022-08-23 11:28 UTC, AgosLizzi commented
> @AgosLizzial fin corregidoooo😄

No veo los cambios lauti :,(

2022-08-24 13:23 UTC, martinebucarey reviewed
No me esta validando las indicaciones 
https://www.loom.com/share/d314a1e65658462085beadd88be2fbdc

2022-08-25 12:04 UTC, merged