IN - Perfil interconsultor para farmacia
andes/app pull request #2720
Opened 2022-07-28 18:31 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-469

### Funcionalidad desarrollada 

1. Verificacion de prescripciones desde capa interconsultores
2. Edición de componente **motivoSuspencion** para hacerlo mas generico y poder editar motivos en casos necesarios

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1738
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-07-28 19:03 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7201](http://condorpiedra.andes.gob.ar:85/7201/mochawesome.html)
CYPRESS RUN: [5976](https://dashboard.cypress.io/projects/xr7gft/runs/5976/specs)
TEST START: 2022-07-28T19:02:39.883Z
TOTAL: 299
SUCCESS: 284
FAIL: 14
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-08-01 16:40 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7252](http://condorpiedra.andes.gob.ar:85/7252/mochawesome.html)
CYPRESS RUN: [6010](https://dashboard.cypress.io/projects/xr7gft/runs/6010/specs)
TEST START: 2022-08-01T16:40:23.480Z
TOTAL: 408
SUCCESS: 405
FAIL: 2
SKIPPED: 1

2022-08-02 14:29 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7275](http://condorpiedra.andes.gob.ar:85/7275/mochawesome.html)
CYPRESS RUN: [6033](https://dashboard.cypress.io/projects/xr7gft/runs/6033/specs)
TEST START: 2022-08-02T14:18:56.096Z
TOTAL: 408
SUCCESS: 390
FAIL: 17
SKIPPED: 1

2022-08-05 14:53 UTC, AgosLizzi requested changes
Lauti, un par de cositas que vi sobre los badge:

1. Mismo paciente, diferentes capas, los badge cambian su anatomía 
![2022-08-05 (1)](https://user-images.githubusercontent.com/72876985/183102583-a4afcbd4-dd5a-4f51-89e6-81612422034f.png)
![2022-08-05 (2)](https://user-images.githubusercontent.com/72876985/183102595-f4b1284a-63ee-4e57-b80c-c22cb270962c.png)

2. En el siguiente ejemplo pasa algo parecido, pero se entorpece cuando aparece otro badge
![2022-08-05 (3)](https://user-images.githubusercontent.com/72876985/183103095-bd49e165-dc93-4f9c-9648-24c1b259d226.png)
![2022-08-05 (4)](https://user-images.githubusercontent.com/72876985/183103102-2ea91ed4-0754-4dd8-8333-7c88dc9be275.png)

2022-08-09 20:02 UTC, negro89 commented
Si, es cierto agos. Eso es por la cantidad de contenido según cada caso. Ahora que hay mas datos a visualizar quizas va siendo momento de agruparlo pero todavia hay algun pr que filtra los badges que puede ver cada capa. A medida que se vayan mergeando vamos actualizando el pr para que quede mejor :+1:

2022-08-10 15:27 UTC, negro89 commented
@AgosLizzi ahora la capa interconsultores debería ver menos información. Quizas quede un poco mejor.

2022-08-10 16:04 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7389](http://condorpiedra.andes.gob.ar:85/7389/mochawesome.html)
CYPRESS RUN: [6135](https://dashboard.cypress.io/projects/xr7gft/runs/6135/specs)
TEST START: 2022-08-10T16:04:10.633Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-08-11 14:34 UTC, AgosLizzi requested changes
Lauti, una duda/consulta. Debería dejarme "aceptar o rechazar" una indicación que ya esta suspendida?  te dejo el caso:
![2022-08-11 (3)](https://user-images.githubusercontent.com/72876985/184157753-56e6ecab-38b7-49ac-baf0-d1f025f3100d.png)
y luego vi esto, cuando le doy aceptar a una indicación, me cambia el estado de las suspendidas. Me parecio raro, te dejo el video:
https://www.loom.com/share/32c560d129e744f0ba682356cdfbd981

2022-08-11 19:15 UTC, negro89 commented
@AgosLizzi ahi restringí algunas cosas mas, entre ellas las indicaciones suspendidas (Solo deberían ver las activas). Además agregué desde el lado de capa médica un hint sobre el badge de 'rechazada' para que puedan ver el motivo de manera rapida (Espero tu opinion).

2022-08-19 10:47 UTC, martinebucarey approved these changes
Pareciera funcionar bien, dos cosas para una próxima iteración y para que charlemos:

1.  Creo que al crear una indicación el que esta en capa medica debería tener un estado mas que sea "en espera" y que va  a cambiar cuando el de farmacia acepte o rechace la solicitud.
2. Con lo del hint estoy en duda porque si es muy largo se va a cortar y no se va a ver completo el motivo, pero tampoco me parece que esta bueno seguir cargando el sidebar con cosas así que por ahora lo podemos dejar y ver que piensa el usuario,

2022-08-25 17:09 UTC, merged