RUP - Se visualiza la misma prestación que genera la consulta
andes/app pull request #2721
Opened 2022-07-29 04:14 UTC by leon-bravo

### Requerimiento
 
[RUP-325](https://proyectos.andes.gob.ar/browse/RUP-325) - Se visualiza la misma prestación que genera la consulta

### Funcionalidad desarrollada 

1. Se filtran la practicas que se pueden registrar para que no coincida con la actual
2. 
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-08-02 18:49 UTC, martinebucarey requested changes

2022-08-02 18:49 UTC, martinebucarey commented on src/app/modules/rup/components/ejecucion/buscador.component.ts
> +                        return matchTerm;
Para no repetir este  bloque de código (esta en la linea 210) se podría pasar a una función y llamar a esta desde ambos lados.

2022-08-03 15:58 UTC, martinebucarey commented
Cuando se usa el buscador se rompe y muestra este error por consola
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/56874534/182654781-971b2026-c4ee-43f7-b188-77cdc30a6568.png">

2022-08-23 22:28 UTC, martinebucarey commented
USUARIO: lbravo  
BUILD NUMBER: [7507](http://condorpiedra.andes.gob.ar:85/7507/mochawesome.html)
CYPRESS RUN: [6312](https://dashboard.cypress.io/projects/xr7gft/runs/6312/specs)
TEST START: 2022-08-23T22:27:57.082Z
TOTAL: 406
SUCCESS: 396
FAIL: 9
SKIPPED: 1

2022-08-24 00:14 UTC, leon-bravo commented on src/app/modules/rup/components/ejecucion/buscador.component.ts
> +                        return matchTerm;
> Para no repetir este bloque de código (esta en la linea 210) se podría pasar a una función y llamar a esta desde ambos lados.

ahi ya se realizo el cambio

2023-03-08 18:59 UTC, ma7payne approved these changes

2023-04-27 16:40 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8789](http://condorpiedra.andes.gob.ar:85/8789/mochawesome.html)
CYPRESS RUN: [7959](https://dashboard.cypress.io/projects/xr7gft/runs/7959/specs)
TEST START: 2023-04-27T16:40:08.080Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-04-27 17:27 UTC, merged