IN - Pan indiaciones: Actualizar vista al validar indicaciones pendientes
andes/app pull request #2723
Opened 2022-08-02 18:44 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-475

### Funcionalidad desarrollada 

1. Reemplaza subscribes anidados de funcion actualizar() por rxjs.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [X] Si (Ver PR api)
- [ ] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1739
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-08-02 18:58 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7286](http://condorpiedra.andes.gob.ar:85/7286/mochawesome.html)
CYPRESS RUN: [6044](https://dashboard.cypress.io/projects/xr7gft/runs/6044/specs)
TEST START: 2022-08-02T18:58:01.257Z
TOTAL: 408
SUCCESS: 406
FAIL: 1
SKIPPED: 1

2022-08-04 17:59 UTC, palita1991 approved these changes

2022-08-10 14:41 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7386](http://condorpiedra.andes.gob.ar:85/7386/mochawesome.html)
CYPRESS RUN: [6132](https://dashboard.cypress.io/projects/xr7gft/runs/6132/specs)
TEST START: 2022-08-10T14:40:45.167Z
TOTAL: 99
SUCCESS: 0
FAIL: 99
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-08-10 16:40 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7390](http://condorpiedra.andes.gob.ar:85/7390/mochawesome.html)
CYPRESS RUN: [6136](https://dashboard.cypress.io/projects/xr7gft/runs/6136/specs)
TEST START: 2022-08-10T16:38:43.327Z
TOTAL: 99
SUCCESS: 0
FAIL: 99
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-08-11 16:05 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7405](http://condorpiedra.andes.gob.ar:85/7405/mochawesome.html)
CYPRESS RUN: [6153](https://dashboard.cypress.io/projects/xr7gft/runs/6153/specs)
TEST START: 2022-08-11T16:04:53.894Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-08-22 12:25 UTC, AgosLizzi requested changes
Lauti, sobre este pr me quedan unas dudas. Cuando agrego una nueva indicación, no hay problema con la actualización. Pero cuando quiero validar las que estan en el listado, no me realiza la acción ... https://www.loom.com/share/5b27f0097e554c29b45b80e738e21b2c

Sobre los errores en la consola, me parece que tienen que ver con loom. Porque me aparecen apenas lo abro, te los dejo por las dudas:
![image](https://user-images.githubusercontent.com/72876985/185920807-435dd2a5-92a4-47c5-8f91-edb0b4aa3c4d.png)

2022-08-24 18:25 UTC, martinebucarey approved these changes

2022-08-24 18:39 UTC, merged