fix(in): guarda motivo de suspencionPlan indicaciones - Mostrar en el sidebar el motivo de suspension
andes/app pull request #2724
Opened 2022-08-03 18:22 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-478

### Funcionalidad desarrollada 

1. Guarda motivo de suspencion (Fix)
2. Agrega visualización de motivo de suspención en el historial de la prescrición

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-08-03 18:49 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7299](http://condorpiedra.andes.gob.ar:85/7299/mochawesome.html)
CYPRESS RUN: [6057](https://dashboard.cypress.io/projects/xr7gft/runs/6057/specs)
TEST START: 2022-08-03T18:32:24.276Z
TOTAL: 365
SUCCESS: 330
FAIL: 34
SKIPPED: 1

2022-08-04 13:53 UTC, martinebucarey commented on src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-detalle/indicacion-detalle.component.ts
> +    `]
Estoy en desacuerdo con que se pongan los estilos acá y no se use una hoja de estilos y se agregue esta en los styleUrls. ( cara de empacado )

2022-08-05 15:16 UTC, AgosLizzi requested changes
Lauti, me paso al rari ...
No me da bola al guardar el motivo de suspensión, tampoco me figura sobre el listado. Te dejo video:
https://www.loom.com/share/d4f6d7c6e3684d2c89d118cee06ddabc

- Otra cosita que me llamo la atención
![2022-08-05 (7)](https://user-images.githubusercontent.com/72876985/183107774-39fa8772-bd0c-4bb1-b333-18127b08cd94.png)

2022-08-09 17:30 UTC, negro89 commented on src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-detalle/indicacion-detalle.component.ts
> +    `]
jajaja, lo suelo hacer cuando son muy pocas clases, para no llenar de archivos con poco contenido. Lo mismo pasa con los html eeeh. Pero creo que el request changes me obliga a hacer un archivito :smiling_face_with_tear:

2022-08-10 14:56 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7387](http://condorpiedra.andes.gob.ar:85/7387/mochawesome.html)
CYPRESS RUN: [6133](https://dashboard.cypress.io/projects/xr7gft/runs/6133/specs)
TEST START: 2022-08-10T14:56:45.532Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-08-10 16:50 UTC, martinebucarey commented
> 

Creo que estamos viendo dos cosas distintas, la tarea cuando lo hicimos fue por la suspension de una prescripción en capa medica, por lo que veo vos estas haciendo la suspension como interconsultor, que también debería tener un feedback el medico de porque no se acepto el medicamento

2022-08-10 16:50 UTC, martinebucarey commented
> Lauti, me paso al rari ... No me da bola al guardar el motivo de suspensión, tampoco me figura sobre el listado. Te dejo video: https://www.loom.com/share/d4f6d7c6e3684d2c89d118cee06ddabc
> 
>     * Otra cosita que me llamo la atención
>       ![2022-08-05 (7)](https://user-images.githubusercontent.com/72876985/183107774-39fa8772-bd0c-4bb1-b333-18127b08cd94.png)
Creo que estamos viendo dos cosas distintas, la tarea cuando lo hicimos fue por la suspension de una prescripción en capa medica, por lo que veo vos estas haciendo la suspension como interconsultor, que también debería tener un feedback el medico de porque no se acepto el medicamento

2022-08-10 16:51 UTC, martinebucarey approved these changes

2022-08-11 17:10 UTC, merged