IN: listado internación rango fechas
andes/app pull request #2728
Opened 2022-08-04 13:51 UTC by plammel

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/IN-477
### Funcionalidad desarrollada 

1. En los listados de interación, se modifica los filtros de manera que se pueda filtrar por opcionalmente por fecha de egreso o de ingreso, o  combinados, pero de manera que siempre es requerido algun rango de fechas completo. 
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2022-08-04 13:53 UTC, plammel commented on src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.service.ts
>      public refresh = new BehaviorSubject<any>(null);
@negro89 que función cumple el observable refresh? se puede borrar?

2022-08-05 11:30 UTC, martinebucarey reviewed
Para una próxima tarea no se puede pasar todo lo de filtros y listados a un service para no repetir tanto código por las distintas capas??

2022-08-09 13:57 UTC, plammel commented
> Si busco con rangos validos y no me trae resultado me muestra la tabla vaciá, esto y a ocurría creo, le pondría el label de no hay resultados para dar una respuesta al usuario.
> 
> ![imagen](https://user-images.githubusercontent.com/56874534/183067929-11de827c-b7d6-4b32-ac9c-556e160d34ba.png)
Hecho

2022-08-09 14:02 UTC, plammel commented on src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.service.ts
> +
Hecho

2022-08-09 14:08 UTC, plammel commented
> Para una próxima tarea no se puede pasar todo lo de filtros y listados a un service para no repetir tanto código por las distintas capas??

Cooincido. Existen tres listados y dos servicios para la misma funcionalidad. Mi intención en principio fue unificar el código, pero las implementaciones varian una de otra, y requiere análsis para poder refactorizar.
Se desprende requerimiento a https://proyectos.andes.gob.ar/browse/IN-481

2022-08-09 14:12 UTC, plammel commented
@martinebucarey otra observación respecto los listados, es que el cache a la subscripción al GET de internaciones produce que se muestren resultados erroneos al cambiar de listados. Se suguiere remover los cache.
Ver https://proyectos.andes.gob.ar/browse/IN-480
https://www.loom.com/share/d19ddfa9744a4fae85cdf674f59e8aeb

2022-08-18 11:08 UTC, martinebucarey submitted a review, later dismissed
Encuentro un problema, si no pongo rangos de ingresos, no me trae resultados solo con los egresos.
https://www.loom.com/share/59f2ca3d4d484ea8b8b6d6ced8be9acf

2022-08-18 11:28 UTC, silviroa requested changes
Es necesario modificar la API para que funcione la búsqueda sin la fecha de ingreso... en la API esta como un parámetro requerido. Por cada búsqueda se están ejecutando 2 request a la api seguidos

2022-08-19 13:56 UTC, plammel commented
> Es necesario modificar la API para que funcione la búsqueda sin la fecha de ingreso... en la API esta como un parámetro requerido. Por cada búsqueda se están ejecutando 2 request a la api seguidos
update: se cachea la suscripción para evitar llamados adicionales

2022-08-19 13:59 UTC, plammel commented on projects/shared/src/lib/server/resource-base.ts
> +
Esta parte hubo que modificarla porque excluía los resultados del día cuando la búsqueda era parcial (`>desde` o `<hasta`)

2022-08-26 18:40 UTC, silviroa approved these changes

2022-08-26 19:21 UTC, martinebucarey commented
USUARIO: plammel  
BUILD NUMBER: [7528](http://condorpiedra.andes.gob.ar:85/7528/mochawesome.html)
CYPRESS RUN: [6335](https://dashboard.cypress.io/projects/xr7gft/runs/6335/specs)
TEST START: 2022-08-26T19:19:59.853Z
TOTAL: 275
SUCCESS: 251
FAIL: 23
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-08-31 17:14 UTC, martinebucarey commented
USUARIO: silviroa  
BUILD NUMBER: [7550](http://condorpiedra.andes.gob.ar:85/7550/mochawesome.html)
CYPRESS RUN: [6358](https://dashboard.cypress.io/projects/xr7gft/runs/6358/specs)
TEST START: 2022-08-31T17:13:34.882Z
TOTAL: 368
SUCCESS: 359
FAIL: 8
SKIPPED: 1

2022-08-31 17:28 UTC, MCele approved these changes

2022-08-31 18:03 UTC, martinebucarey commented
USUARIO: silviroa  
BUILD NUMBER: [7552](http://condorpiedra.andes.gob.ar:85/7552/mochawesome.html)
CYPRESS RUN: [6361](https://dashboard.cypress.io/projects/xr7gft/runs/6361/specs)
TEST START: 2022-08-31T17:51:07.510Z
TOTAL: 406
SUCCESS: 384
FAIL: 21
SKIPPED: 1

2022-09-01 13:23 UTC, merged