UIUX - Tooltips recortados
andes/app pull request #2731
Opened 2022-08-05 17:05 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/UIUX-351

### Funcionalidad desarrollada 

1. Se cambio de posicion el boton de deshacer internacion dejandolo a la derecha. Tambien se modifico la posicion del tooltip de editar nota. Los cambios se encuentran en la linea 75 - 79 y 112 a 114

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-08-08 11:55 UTC, palita1991 requested changes
@MarianoCampetella se ven bien los cambios, capaz estaría bueno cambiar el tooltip este ya que estamos
![internacion](https://user-images.githubusercontent.com/30004190/183412411-5f1bf42f-66a1-4036-b3e0-c6da37437a84.png)

2022-08-08 18:02 UTC, MarianoCampetella commented
> @MarianoCampetella se ven bien los cambios, capaz estaría bueno cambiar el tooltip este ya que estamos ![internacion](https://user-images.githubusercontent.com/30004190/183412411-5f1bf42f-66a1-4036-b3e0-c6da37437a84.png)

Corregido!

2022-08-10 12:23 UTC, AgosLizzi approved these changes

2022-08-11 14:12 UTC, MarianoCampetella commented
> Campe, nos acaban de reportar esto. Fijate porque no puede quedar así:
> 
> ![image](https://user-images.githubusercontent.com/72876985/183978149-3998d06d-1996-44e3-a605-d9d2a68c8e80.png)

Corregido!

2022-08-16 12:44 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7422](http://condorpiedra.andes.gob.ar:85/7422/mochawesome.html)
CYPRESS RUN: [6185](https://dashboard.cypress.io/projects/xr7gft/runs/6185/specs)
TEST START: 2022-08-16T12:40:19.359Z
TOTAL: 369
SUCCESS: 363
FAIL: 5
SKIPPED: 1

2022-08-17 15:42 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7439](http://condorpiedra.andes.gob.ar:85/7439/mochawesome.html)
CYPRESS RUN: [6239](https://dashboard.cypress.io/projects/xr7gft/runs/6239/specs)
TEST START: 2022-08-17T15:41:46.965Z
TOTAL: 406
SUCCESS: 397
FAIL: 8
SKIPPED: 1

2022-08-17 16:09 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7440](http://condorpiedra.andes.gob.ar:85/7440/mochawesome.html)
CYPRESS RUN: [6240](https://dashboard.cypress.io/projects/xr7gft/runs/6240/specs)
TEST START: 2022-08-17T16:07:57.187Z
TOTAL: 258
SUCCESS: 233
FAIL: 24
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-08-18 11:36 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7447](http://condorpiedra.andes.gob.ar:85/7447/mochawesome.html)
CYPRESS RUN: [6252](https://dashboard.cypress.io/projects/xr7gft/runs/6252/specs)
TEST START: 2022-08-18T11:35:37.223Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-08-18 15:26 UTC, AgosLizzi approved these changes

2022-11-14 14:14 UTC, silviroa commented
USUARIO: silviroa  
BUILD NUMBER: [7913](http://condorpiedra.andes.gob.ar:85/7913/mochawesome.html)
CYPRESS RUN: [7108](https://dashboard.cypress.io/projects/xr7gft/runs/7108/specs)
TEST START: 2022-11-14T13:53:23.902Z
TOTAL: 324
SUCCESS: 295
FAIL: 28
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-11-14 15:07 UTC, silviroa approved these changes

2022-11-14 15:17 UTC, silviroa commented
USUARIO: silviroa  
BUILD NUMBER: [7917](http://condorpiedra.andes.gob.ar:85/7917/mochawesome.html)
CYPRESS RUN: [7112](https://dashboard.cypress.io/projects/xr7gft/runs/7112/specs)
TEST START: 2022-11-14T15:17:08.690Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

2022-11-14 15:36 UTC, merged