IN - Quitar unidad organizativa actual al prestar cama ocupada
andes/app pull request #2736
Opened 2022-08-12 16:17 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-466

### Funcionalidad desarrollada 

1. Filtra unidad organizativa actual al llenar el combo de unidad destino

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-08-12 17:04 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7415](http://condorpiedra.andes.gob.ar:85/7415/mochawesome.html)
CYPRESS RUN: [6168](https://dashboard.cypress.io/projects/xr7gft/runs/6168/specs)
TEST START: 2022-08-12T17:04:08.992Z
TOTAL: 406
SUCCESS: 398
FAIL: 7
SKIPPED: 1

2022-08-17 11:55 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7426](http://condorpiedra.andes.gob.ar:85/7426/mochawesome.html)
CYPRESS RUN: [6218](https://dashboard.cypress.io/projects/xr7gft/runs/6218/specs)
TEST START: 2022-08-17T11:55:22.777Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

2022-08-17 12:50 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7430](http://condorpiedra.andes.gob.ar:85/7430/mochawesome.html)
CYPRESS RUN: [6223](https://dashboard.cypress.io/projects/xr7gft/runs/6223/specs)
TEST START: 2022-08-17T12:50:25.886Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-08-17 13:33 UTC, martinebucarey requested changes

2022-08-17 13:33 UTC, martinebucarey commented on src/app/apps/rup/mapa-camas/sidebar/prestar-devolver-recurso/prestar-devolver-recurso.component.ts
> +        map(unidadesOrganizacivas => unidadesOrganizacivas.filter(uo => uo.id !== this.cama.unidadOrganizativa.id))
unidades organizaCivas ?? buen nombre

2022-10-20 16:23 UTC, MarianoCampetella approved these changes

2022-10-31 17:54 UTC, MCele requested changes
Algunas veces se visualiza la UO actual.
https://drive.google.com/file/d/1tbXGAWEWFxsADDU4XVgwGi97Y9jkSlXX/view

2022-11-01 16:51 UTC, negro89 commented
@MCele ahi quedo corregido. Habia algun temita de cache.

2022-11-16 19:51 UTC, MCele approved these changes

2022-11-18 15:48 UTC, merged