IN - Plan indicaciones: Separar acciones segun perfil
andes/app pull request #2740
Opened 2022-08-17 17:03 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-468

### Funcionalidad desarrollada 

1. Restringe acciones y visualización de indicaciones para perfil enfermeria.

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-08-17 17:22 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7441](http://condorpiedra.andes.gob.ar:85/7441/mochawesome.html)
CYPRESS RUN: [6241](https://dashboard.cypress.io/projects/xr7gft/runs/6241/specs)
TEST START: 2022-08-17T17:20:53.536Z
TOTAL: 365
SUCCESS: 342
FAIL: 22
SKIPPED: 1

2022-08-18 18:15 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7453](http://condorpiedra.andes.gob.ar:85/7453/mochawesome.html)
CYPRESS RUN: [6259](https://dashboard.cypress.io/projects/xr7gft/runs/6259/specs)
TEST START: 2022-08-18T18:15:23.476Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-08-19 12:39 UTC, martinebucarey requested changes

2022-08-19 12:39 UTC, martinebucarey commented on src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
> -
Sacando esto creo que no me muestra cuando no hay indicaciones en el perfil medico por ejemplo:
![imagen](https://user-images.githubusercontent.com/56874534/185620182-9d2fc5b0-2c7f-4212-bd4b-980e7897c8c5.png)

2022-08-19 18:42 UTC, negro89 commented on src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
> -
Corregidooo

2022-08-19 19:08 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7462](http://condorpiedra.andes.gob.ar:85/7462/mochawesome.html)
CYPRESS RUN: [6269](https://dashboard.cypress.io/projects/xr7gft/runs/6269/specs)
TEST START: 2022-08-19T18:58:27.733Z
TOTAL: 406
SUCCESS: 390
FAIL: 15
SKIPPED: 1

2022-08-19 19:30 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7464](http://condorpiedra.andes.gob.ar:85/7464/mochawesome.html)
CYPRESS RUN: [6271](https://dashboard.cypress.io/projects/xr7gft/runs/6271/specs)
TEST START: 2022-08-19T19:29:22.498Z
TOTAL: 377
SUCCESS: 368
FAIL: 8
SKIPPED: 1

2022-08-22 15:44 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7471](http://condorpiedra.andes.gob.ar:85/7471/mochawesome.html)
CYPRESS RUN: [6280](https://dashboard.cypress.io/projects/xr7gft/runs/6280/specs)
TEST START: 2022-08-22T15:43:53.783Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

2022-08-22 17:12 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7476](http://condorpiedra.andes.gob.ar:85/7476/mochawesome.html)
CYPRESS RUN: [6285](https://dashboard.cypress.io/projects/xr7gft/runs/6285/specs)
TEST START: 2022-08-22T17:02:25.844Z
TOTAL: 406
SUCCESS: 390
FAIL: 15
SKIPPED: 1

2022-08-22 19:50 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7484](http://condorpiedra.andes.gob.ar:85/7484/mochawesome.html)
CYPRESS RUN: [6292](https://dashboard.cypress.io/projects/xr7gft/runs/6292/specs)
TEST START: 2022-08-22T19:50:38.143Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-08-24 13:28 UTC, martinebucarey requested changes
Cuando el paciente no tiene indicaciones validadas, se muestra vació el calendario, yo creo que se debería mostrar como antes, la sección y que te diga que no hay indicaciones

![imagen](https://user-images.githubusercontent.com/56874534/186430764-c9ae2699-ce83-4c48-8d0b-9688818bdc4d.png)

2022-08-24 16:04 UTC, negro89 commented
@martinebucarey corregido, se mantuvo la modificacion original del pr mas la actual de master

2022-08-25 13:58 UTC, AgosLizzi approved these changes

2022-08-25 14:19 UTC, martinebucarey approved these changes

2022-08-25 14:25 UTC, merged