PER - cambios en seguimiento perinatal
andes/app pull request #2743
Opened 2022-08-22 15:11 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/PER-76

### Funcionalidad desarrollada 

1. Se agrego un filtro para que pueda traer solamente los pacientes que se encuentran en estado ausente.
2. En la descarga del csv se agregaron dos columnas: estado y efector del control.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-08-22 15:58 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7472](http://condorpiedra.andes.gob.ar:85/7472/mochawesome.html)
CYPRESS RUN: [6281](https://dashboard.cypress.io/projects/xr7gft/runs/6281/specs)
TEST START: 2022-08-22T15:58:04.583Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-08-22 17:49 UTC, martinebucarey submitted a review, later dismissed

2022-08-22 17:49 UTC, martinebucarey commented on src/app/modules/perinatal/services/carnet-perinatal.service.ts
> +    public estado = new BehaviorSubject<string>(null);
Por que el estado es un BehaviorSubjet??

2022-08-23 12:12 UTC, MarianoCampetella commented on src/app/modules/perinatal/services/carnet-perinatal.service.ts
> +                            return listado.map(l => {
Corregido, se cambio el nombre de la variable para que sea mas descriptiva y no confunda con el 1 incluso jaja

2022-08-23 12:16 UTC, MarianoCampetella commented on src/app/modules/perinatal/services/carnet-perinatal.service.ts
> +    public estado = new BehaviorSubject<string>(null);
El estado es un BehaviorSubjet ya que todos los filtros están implementado de esa forma en la clase filtrar() y dentro de carnet-perinatal.service los valores de los filtros estan dentro de un combinelatests.

2023-02-27 15:05 UTC, maring0019 approved these changes

2023-03-01 19:51 UTC, MCele commented on src/app/modules/perinatal/components/listado-perinatal.component.ts
> +    public estado;
Quizás en este caso el nombre puede ser más especifico para evitar ambigüedades. El nombre da a entender que se quiere almacenar un atributo estado, pero cuando se analiza el códido se observa que es un booleano para poder filtrar por estado "ausente", entonces me parece que se puede mejorar de dos formas:
1)  podría pensarse como una variable string que pueda almacenar el string "ausente", "todas", etc.
2) Cambiarse el nombre por "filtrarAusente", "verAusente", "estadoAusente" u otro similar.

2023-03-02 15:36 UTC, MarianoCampetella commented on src/app/modules/perinatal/components/listado-perinatal.component.ts
> +    public estado;
Corregido! se cambio el nombre de la variable estado a filtrarEstado

2023-03-02 19:47 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [8521](http://condorpiedra.andes.gob.ar:85/8521/mochawesome.html)
CYPRESS RUN: [7700](https://dashboard.cypress.io/projects/xr7gft/runs/7700/specs)
TEST START: 2023-03-02T19:47:07.032Z
TOTAL: 406
SUCCESS: 402
FAIL: 2
SKIPPED: 2

2023-03-02 20:51 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [8523](http://condorpiedra.andes.gob.ar:85/8523/mochawesome.html)
CYPRESS RUN: [7702](https://dashboard.cypress.io/projects/xr7gft/runs/7702/specs)
TEST START: 2023-03-02T20:50:58.555Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-03-03 19:56 UTC, MCele approved these changes

2023-04-03 14:53 UTC, MCele requested changes
Revisar query ya que no funciona de forma correcta.
Se le realizaron cambios en la query (queda en demo):
-  incorporando la fecha de control (que se quitó en esta versión).
- se cambia el orden de algunas columnas.
- para detalle de estado se corrige comparación con fecha del filtro por fecha actual.
Queda pendiente mostrar estado "ausente" respetando lo anterior, pero simpre que exista una fecha de control o el embarazo no haya finalizado

comparar fecha control con con la fecha actual, pero queda pendiente los casos en los que se finalizó el embarazo o no se registró fecha de control

2023-04-04 13:42 UTC, MCele approved these changes

2023-04-04 13:42 UTC, merged