RUP - Nueva molecula ACV
andes/app pull request #2752
Opened 2022-09-01 15:40 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/RUP-329

### Funcionalidad desarrollada 

1. Se crea nuevo elementoRup componente **MoleculaBaseComponent** y se edita **ValorFechaComponent**
 preexistente para incluir horario
2. Nuevo template para componente de moleculaBase que permite evolucionar este trastorno

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [X] Si
- [ ] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1755
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

**--------------------- MODIFICACIONES EN LA DB (EN DEMO ESTA ACTUALIZADO) -------------------**
{
    "_id" : ObjectId("6304f3625a17d31efdc7605b"),
    "activo" : true,
    "componente" : "MoleculaBaseComponent",
    "tipo" : "molecula",
    "esSolicitud" : false,
    "style" : {
        "columns" : 12.0,
        "cssClass" : null
    },
    "params" : {
        "required" : true,
        "title" : "ACV"
    },
    "conceptos" : [ 
        {
            "conceptId" : "230690007",
            "term" : "ACV",
            "fsn" : "accidente cerebrovascular (trastorno)",
            "semanticTag" : "trastorno"
        }
    ],
    "requeridos" : [ 
        {
            "elementoRUP" : ObjectId("5de107ba3463de2aac7e6618"),
            "concepto" : {
                "conceptId" : "298059007",
                "term" : "fecha de inicio",
                "fsn" : "fecha de inicio (entidad observable)",
                "semanticTag" : "entidad observable"
            },
            "params" : {
                "title" : "fecha de inicio de los síntomas",
                "type" : "date",
                "required" : true,
                "max" : "Date.now()"
            },
            "style" : {
                "columns" : 4.0,
                "cssClass" : null
            }
        }, 
        {
            "elementoRUP" : ObjectId("5de107ba3463de2aac7e6618"),
            "concepto" : {
                "conceptId" : "405795006",
                "term" : "hora de inicio",
                "fsn" : "hora de inicio de los síntomas(entidad observable)",
                "semanticTag" : "entidad observable"
            },
            "params" : {
                "title" : "hora de inicio de los síntomas",
                "type" : "time",
                "required" : true
            },
            "style" : {
                "columns" : 4.0,
                "cssClass" : null
            }
        }, 
        {
            "elementoRUP" : ObjectId("5a27dbce291f463c1b982d99"),
            "concepto" : {
                "fsn" : "informe (elemento de registro)",
                "semanticTag" : "elemento de registro",
                "term" : "informe",
                "conceptId" : "229059009"
            },
            "params" : {
                "titulo" : "evolución",
                "placeholder" : "Ingrese una evolución"
            },
            "style" : {
                "columns" : 12.0,
                "cssClass" : null
            }
        }
    ],
    "frecuentes" : []
}

-------------------------------------------------------------------------------------------------------------

{
    "_id" : ObjectId("5de107ba3463de2aac7e6618"),
    "activo" : true,
    "componente" : "ValorFechaComponent",
    "tipo" : "atomo",
    "esSolicitud" : false,
    "style" : {
        "columnas" : 6.0,
        "cssClass" : null
    },
    "conceptos" : [ 
        {
            "fsn" : "último período menstrual (entidad observable)",
            "semanticTag" : "entidad observable",
            "refsetIds" : [ 
                "900000000000497000"
            ],
            "conceptId" : "21840007",
            "term" : "último período menstrual"
        }, 
        {
            "conceptId" : "298059007",
            "term" : "fecha de inicio",
            "fsn" : "fecha de inicio (entidad observable)",
            "semanticTag" : "entidad observable"
        }, 
        {
            "conceptId" : "442864001",
            "term" : "fecha de alta",
            "fsn" : "fecha de alta (entidad observable)",
            "semanticTag" : "entidad observable"
        }, 
        {
            "conceptId" : "405795006",
            "term" : "hora de inicio",
            "fsn" : "hora de inicio de los síntomas(entidad observable)",
            "semanticTag" : "entidad observable"
        }
    ],
    "requeridos" : [],
    "frecuentes" : [],
    "params" : {
        "title" : "Fecha",
        "type" : "date",
        "required" : true,
        "max" : "Date.now()"
    }
}

2022-09-01 15:56 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7571](http://condorpiedra.andes.gob.ar:85/7571/mochawesome.html)
CYPRESS RUN: [6378](https://dashboard.cypress.io/projects/xr7gft/runs/6378/specs)
TEST START: 2022-09-01T15:56:31.320Z
TOTAL: 406
SUCCESS: 400
FAIL: 5
SKIPPED: 1

2022-09-01 17:23 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7572](http://condorpiedra.andes.gob.ar:85/7572/mochawesome.html)
CYPRESS RUN: [6379](https://dashboard.cypress.io/projects/xr7gft/runs/6379/specs)
TEST START: 2022-09-01T17:22:00.109Z
TOTAL: 353
SUCCESS: 338
FAIL: 14
SKIPPED: 1

2022-09-01 18:55 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7573](http://condorpiedra.andes.gob.ar:85/7573/mochawesome.html)
CYPRESS RUN: [6380](https://dashboard.cypress.io/projects/xr7gft/runs/6380/specs)
TEST START: 2022-09-01T18:54:59.888Z
TOTAL: 406
SUCCESS: 399
FAIL: 6
SKIPPED: 1

2022-09-02 13:33 UTC, silviroa commented
USUARIO: martinebucarey  
BUILD NUMBER: [7577](http://condorpiedra.andes.gob.ar:85/7577/mochawesome.html)
CYPRESS RUN: [6384](https://dashboard.cypress.io/projects/xr7gft/runs/6384/specs)
TEST START: 2022-09-02T13:33:25.651Z
TOTAL: 402
SUCCESS: 396
FAIL: 5
SKIPPED: 1

2022-09-07 12:16 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7587](http://condorpiedra.andes.gob.ar:85/7587/mochawesome.html)
CYPRESS RUN: [6396](https://dashboard.cypress.io/projects/xr7gft/runs/6396/specs)
TEST START: 2022-09-07T12:15:48.805Z
TOTAL: 406
SUCCESS: 392
FAIL: 13
SKIPPED: 1

2022-09-07 13:24 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7590](http://condorpiedra.andes.gob.ar:85/7590/mochawesome.html)
CYPRESS RUN: [6399](https://dashboard.cypress.io/projects/xr7gft/runs/6399/specs)
TEST START: 2022-09-07T13:03:19.143Z
TOTAL: 380
SUCCESS: 345
FAIL: 34
SKIPPED: 1

2022-09-07 16:24 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7593](http://condorpiedra.andes.gob.ar:85/7593/mochawesome.html)
CYPRESS RUN: [6402](https://dashboard.cypress.io/projects/xr7gft/runs/6402/specs)
TEST START: 2022-09-07T16:14:11.185Z
TOTAL: 406
SUCCESS: 386
FAIL: 19
SKIPPED: 1

2022-09-13 19:27 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7616](http://condorpiedra.andes.gob.ar:85/7616/mochawesome.html)
CYPRESS RUN: [6461](https://dashboard.cypress.io/projects/xr7gft/runs/6461/specs)
TEST START: 2022-09-13T19:25:52.314Z
TOTAL: 374
SUCCESS: 362
FAIL: 11
SKIPPED: 1

2022-09-14 13:36 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7624](http://condorpiedra.andes.gob.ar:85/7624/mochawesome.html)
CYPRESS RUN: [6469](https://dashboard.cypress.io/projects/xr7gft/runs/6469/specs)
TEST START: 2022-09-14T13:36:21.772Z
TOTAL: 406
SUCCESS: 401
FAIL: 4
SKIPPED: 1

2022-09-14 14:42 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7628](http://condorpiedra.andes.gob.ar:85/7628/mochawesome.html)
CYPRESS RUN: [6474](https://dashboard.cypress.io/projects/xr7gft/runs/6474/specs)
TEST START: 2022-09-14T14:30:52.437Z
TOTAL: 406
SUCCESS: 384
FAIL: 21
SKIPPED: 1

2022-09-14 16:59 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7632](http://condorpiedra.andes.gob.ar:85/7632/mochawesome.html)
CYPRESS RUN: [6478](https://dashboard.cypress.io/projects/xr7gft/runs/6478/specs)
TEST START: 2022-09-14T16:58:59.398Z
TOTAL: 406
SUCCESS: 401
FAIL: 4
SKIPPED: 1

2022-10-06 15:43 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7735](http://condorpiedra.andes.gob.ar:85/7735/mochawesome.html)
CYPRESS RUN: [6853](https://dashboard.cypress.io/projects/xr7gft/runs/6853/specs)
TEST START: 2022-10-06T15:43:28.536Z
TOTAL: 342
SUCCESS: 326
FAIL: 15
SKIPPED: 1

2022-10-14 18:44 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7757](http://condorpiedra.andes.gob.ar:85/7757/mochawesome.html)
CYPRESS RUN: [6895](https://dashboard.cypress.io/projects/xr7gft/runs/6895/specs)
TEST START: 2022-10-14T18:23:16.391Z
TOTAL: 363
SUCCESS: 343
FAIL: 19
SKIPPED: 1

2023-01-17 18:11 UTC, silviroa commented
USUARIO: silviroa  
BUILD NUMBER: [8260](http://condorpiedra.andes.gob.ar:85/8260/mochawesome.html)
CYPRESS RUN: [7441](https://dashboard.cypress.io/projects/xr7gft/runs/7441/specs)
TEST START: 2023-01-17T18:10:50.848Z
TOTAL: 406
SUCCESS: 390
FAIL: 14
SKIPPED: 2

2023-01-17 18:34 UTC, silviroa requested changes
En la visualización de los registros para evolucionar no se ve correctamente la hora que se registro como "hora de inicio de los síntomas"

2023-01-18 02:12 UTC, silviroa commented
> En la visualización de los registros para evolucionar no se ve correctamente la hora que se registro como "hora de inicio de los síntomas"

2023-01-18 02:14 UTC, silviroa approved these changes

2023-01-18 18:20 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8274](http://condorpiedra.andes.gob.ar:85/8274/mochawesome.html)
CYPRESS RUN: [7455](https://dashboard.cypress.io/projects/xr7gft/runs/7455/specs)
TEST START: 2023-01-18T18:20:36.831Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-01-18 18:41 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8276](http://condorpiedra.andes.gob.ar:85/8276/mochawesome.html)
CYPRESS RUN: [7457](https://dashboard.cypress.io/projects/xr7gft/runs/7457/specs)
TEST START: 2023-01-18T18:41:06.493Z
TOTAL: 406
SUCCESS: 401
FAIL: 3
SKIPPED: 2

2023-01-18 19:10 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8278](http://condorpiedra.andes.gob.ar:85/8278/mochawesome.html)
CYPRESS RUN: [7459](https://dashboard.cypress.io/projects/xr7gft/runs/7459/specs)
TEST START: 2023-01-18T19:09:52.860Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-01-26 16:02 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [8336](http://condorpiedra.andes.gob.ar:85/8336/mochawesome.html)
CYPRESS RUN: [7515](https://dashboard.cypress.io/projects/xr7gft/runs/7515/specs)
TEST START: 2023-01-26T16:01:51.071Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-01-27 15:10 UTC, MCele approved these changes

2023-01-27 15:16 UTC, merged