GDU - Perfiles ordenados
andes/app pull request #2756
Opened 2022-09-09 17:29 UTC by maring0019

### Requerimiento
 

### Funcionalidad desarrollada 

1. Se muestra el listado de perfiles en forma ordenada.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si
- [ ] No 

### Requiere actualizaciones en andes-test-integracion

- [X] Si
- [ ] No

2022-09-29 14:03 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [7705](http://condorpiedra.andes.gob.ar:85/7705/mochawesome.html)
CYPRESS RUN: [6696](https://dashboard.cypress.io/projects/xr7gft/runs/6696/specs)
TEST START: 2022-09-29T14:02:58.959Z
TOTAL: 401
SUCCESS: 398
FAIL: 2
SKIPPED: 1

2022-09-29 15:04 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [7706](http://condorpiedra.andes.gob.ar:85/7706/mochawesome.html)
CYPRESS RUN: [6698](https://dashboard.cypress.io/projects/xr7gft/runs/6698/specs)
TEST START: 2022-09-29T15:02:26.986Z
TOTAL: 376
SUCCESS: 364
FAIL: 11
SKIPPED: 1

2022-09-29 17:42 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [7710](http://condorpiedra.andes.gob.ar:85/7710/mochawesome.html)
CYPRESS RUN: [6701](https://dashboard.cypress.io/projects/xr7gft/runs/6701/specs)
TEST START: 2022-09-29T17:42:29.350Z
TOTAL: 401
SUCCESS: 391
FAIL: 9
SKIPPED: 1

2022-09-30 14:56 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [7718](http://condorpiedra.andes.gob.ar:85/7718/mochawesome.html)
CYPRESS RUN: [6713](https://dashboard.cypress.io/projects/xr7gft/runs/6713/specs)
TEST START: 2022-09-30T14:56:27.273Z
TOTAL: 401
SUCCESS: 397
FAIL: 3
SKIPPED: 1

2022-09-30 15:10 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [7719](http://condorpiedra.andes.gob.ar:85/7719/mochawesome.html)
CYPRESS RUN: [6719](https://dashboard.cypress.io/projects/xr7gft/runs/6719/specs)
TEST START: 2022-09-30T15:10:31.727Z
TOTAL: 401
SUCCESS: 398
FAIL: 2
SKIPPED: 1

2022-10-05 18:04 UTC, AgosLizzi reviewed
Mariela, veo bien los cambios sobre el módulo. Encontré solo un detalle que no se si corresponde a algo que trae por defecto o que se duplico dos veces. Te adjunto fotos:
![2022-10-05 (1)](https://user-images.githubusercontent.com/72876985/194129577-0a7ff363-4888-4ba2-a147-3eebe768ea35.jpg)
![2022-10-05 (4)](https://user-images.githubusercontent.com/72876985/194129768-90531e70-cbfa-469c-bf01-751f921dc8de.jpg)

Fijate que en ambos casos la fecha de actualización esta duplicada, mostrando en la primera opción solo la fecha y en la segunda fecha y hora. Los mismo sucede sobre la segunda imagen, que correponde al listado de perfiles, donde hay una columna de **actualización**

2022-10-21 12:35 UTC, maring0019 commented
Falta realizar test.

2022-11-14 16:34 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [7920](http://condorpiedra.andes.gob.ar:85/7920/mochawesome.html)
CYPRESS RUN: [7115](https://dashboard.cypress.io/projects/xr7gft/runs/7115/specs)
TEST START: 2022-11-14T16:34:05.833Z
TOTAL: 401
SUCCESS: 388
FAIL: 12
SKIPPED: 1

2022-11-14 18:13 UTC, maring0019 commented
> Mariela, veo bien los cambios sobre el módulo. Encontré solo un detalle que no se si corresponde a algo que trae por defecto o que se duplico dos veces. Te adjunto fotos: ![2022-10-05 (1)](https://user-images.githubusercontent.com/72876985/194129577-0a7ff363-4888-4ba2-a147-3eebe768ea35.jpg) ![2022-10-05 (4)](https://user-images.githubusercontent.com/72876985/194129768-90531e70-cbfa-469c-bf01-751f921dc8de.jpg)
> 
> Fijate que en ambos casos la fecha de actualización esta duplicada, mostrando en la primera opción solo la fecha y en la segunda fecha y hora. Los mismo sucede sobre la segunda imagen, que correponde al listado de perfiles, donde hay una columna de **actualización**

2022-11-15 15:54 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [7927](http://condorpiedra.andes.gob.ar:85/7927/mochawesome.html)
CYPRESS RUN: [7122](https://dashboard.cypress.io/projects/xr7gft/runs/7122/specs)
TEST START: 2022-11-15T15:54:18.283Z
TOTAL: 401
SUCCESS: 396
FAIL: 4
SKIPPED: 1

2022-11-16 15:28 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [7938](http://condorpiedra.andes.gob.ar:85/7938/mochawesome.html)
CYPRESS RUN: [7132](https://dashboard.cypress.io/projects/xr7gft/runs/7132/specs)
TEST START: 2022-11-16T15:28:16.968Z
TOTAL: 401
SUCCESS: 398
FAIL: 2
SKIPPED: 1

2022-11-28 16:45 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8024](http://condorpiedra.andes.gob.ar:85/8024/mochawesome.html)
CYPRESS RUN: [7217](https://dashboard.cypress.io/projects/xr7gft/runs/7217/specs)
TEST START: 2022-11-28T16:44:34.167Z
TOTAL: 387
SUCCESS: 378
FAIL: 7
SKIPPED: 2

2022-11-28 21:24 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8028](http://condorpiedra.andes.gob.ar:85/8028/mochawesome.html)
CYPRESS RUN: [7221](https://dashboard.cypress.io/projects/xr7gft/runs/7221/specs)
TEST START: 2022-11-28T21:13:45.664Z
TOTAL: 401
SUCCESS: 382
FAIL: 17
SKIPPED: 2

2022-11-29 17:21 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8038](http://condorpiedra.andes.gob.ar:85/8038/mochawesome.html)
CYPRESS RUN: [7231](https://dashboard.cypress.io/projects/xr7gft/runs/7231/specs)
TEST START: 2022-11-29T17:21:05.014Z
TOTAL: 401
SUCCESS: 389
FAIL: 10
SKIPPED: 2

2022-11-30 12:52 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8045](http://condorpiedra.andes.gob.ar:85/8045/mochawesome.html)
CYPRESS RUN: [7238](https://dashboard.cypress.io/projects/xr7gft/runs/7238/specs)
TEST START: 2022-11-30T12:52:32.287Z
TOTAL: 350
SUCCESS: 339
FAIL: 9
SKIPPED: 2

2022-12-05 17:10 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8088](http://condorpiedra.andes.gob.ar:85/8088/mochawesome.html)
CYPRESS RUN: [7280](https://dashboard.cypress.io/projects/xr7gft/runs/7280/specs)
TEST START: 2022-12-05T17:09:58.736Z
TOTAL: 401
SUCCESS: 389
FAIL: 10
SKIPPED: 2

2023-01-05 15:47 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8216](http://condorpiedra.andes.gob.ar:85/8216/mochawesome.html)
CYPRESS RUN: [7401](https://dashboard.cypress.io/projects/xr7gft/runs/7401/specs)
TEST START: 2023-01-05T15:37:30.229Z
TOTAL: 401
SUCCESS: 381
FAIL: 18
SKIPPED: 2

2023-01-05 16:00 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8217](http://condorpiedra.andes.gob.ar:85/8217/mochawesome.html)
CYPRESS RUN: [7402](https://dashboard.cypress.io/projects/xr7gft/runs/7402/specs)
TEST START: 2023-01-05T16:00:31.648Z
TOTAL: 401
SUCCESS: 397
FAIL: 2
SKIPPED: 2

2023-01-17 15:27 UTC, negro89 requested changes
Mari, un par de cositas ..
1. Editando los permisos de un usuario, en el panel de la izquierda titulado 'perfiles habilitados', los perfiles deberían mostrarse ordenados alfabeticamente.
2. En la pantalla 'perfiles', al inactivar alguno, desaparece del listado impidiendo la activación en un futuro. En esta pantalla deberían aparecer tanto los activos como los inactivos.
Los perfiles inactivos deberian ocultarse en la pantalla de **edición de permisos de un usuario**, en el panel izquierdo 'perfiles habilitados'.

2023-01-17 15:45 UTC, maring0019 commented
> 

1. No me pidieron ese orden en la tarea sino sobre el listado de perfiles donde aparecen los filtros.
2. Así fue como me pidieron. Que ya no aparezcan los inactivos.

2023-01-23 17:26 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8314](http://condorpiedra.andes.gob.ar:85/8314/mochawesome.html)
CYPRESS RUN: [7493](https://dashboard.cypress.io/projects/xr7gft/runs/7493/specs)
TEST START: 2023-01-23T17:26:19.245Z
TOTAL: 406
SUCCESS: 396
FAIL: 8
SKIPPED: 2

2023-01-23 17:52 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8315](http://condorpiedra.andes.gob.ar:85/8315/mochawesome.html)
CYPRESS RUN: [7494](https://dashboard.cypress.io/projects/xr7gft/runs/7494/specs)
TEST START: 2023-01-23T17:51:59.896Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-01-25 11:59 UTC, AgosLizzi requested changes
Mari, vi un par de cositas que estarían actualizarlas: 
1. Para orientarnos, la pantalla de la izquierda carece de un plex title, entonces los botones "vovler y nuevo" se encuentran sin contexto alguno. 
2. La pantalla de la derecha, contiene un plex title en gris, no se usa más en la aplicación, estaría bueno actualizarlo.
3. Y comparando ambas pantallas, no veo una simetria entre botones, campos de textos y tamaños. Eso debería acomodarse

![2023-01-25 (1)](https://user-images.githubusercontent.com/72876985/214556061-75263bb1-40ae-4e06-add6-08ff7f8b24ec.png)tamaños. 

![2023-01-25 (1)](https://user-images.githubusercontent.com/72876985/214556061-75263bb1-40ae-4e06-add6-08ff7f8b24ec.png)

2023-02-08 14:09 UTC, negro89 commented
@maring0019, en que estado quedó esta tarea?

2023-02-09 12:35 UTC, maring0019 commented
> @maring0019, en que estado quedó esta tarea?


Está en change done. Pero lo que veo es que Agostina me pidió unos cambios. Supongo que pasará a changes requested. Pero ella no actualizó la etiqueta. Quién debe cambiar la etiqueta? Te pregunto para evitar problemas.

2023-02-09 18:59 UTC, negro89 commented
> > @maring0019, en que estado quedó esta tarea?
> 
> Está en changes done porque si había hecho los cambios. Pero ahora lo que veo es que Agostina me pidió nuevos cambios. Supongo que pasará a changes requested. Pero ella no actualizó la etiqueta. Quién debe cambiar la etiqueta? Te pregunto para evitar problemas.

No importa quien actualice las etiquetas siempre y cuando tenga coherencia con lo que se tenga que hacer. Se le debe haber pasado por algo a agos cuando te los pidió. Ahora la agrego yo 👍🏼

2023-02-14 15:50 UTC, maring0019 commented
> Vi un par de cositas que estarían buenas actualizarlas:
> 
> 1. Para orientarnos, la pantalla de la izquierda carece de un plex title, entonces los botones "volver y nuevo" se encuentran sin contexto alguno.
> 2. La pantalla de la derecha, contiene un plex title en gris, no se usa más en la aplicación, estaría bueno actualizarlo.
> 3. Y comparando ambas pantallas, no veo una simetria entre botones, campos de textos y tamaños. Eso debería acomodarse
> 
> ![2023-01-25 (1)](https://user-images.githubusercontent.com/72876985/214556061-75263bb1-40ae-4e06-add6-08ff7f8b24ec.png)

Cambios realizados.

2023-02-15 12:05 UTC, negro89 approved these changes

2023-02-15 12:42 UTC, AgosLizzi approved these changes

2023-02-15 12:53 UTC, merged