TOP - Listado reglas
andes/app pull request #2757
Opened 2022-09-14 17:10 UTC by palita1991

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/TOP-134

### Funcionalidad desarrollada 

1. skip and limit en listado de reglas
2. Loader 
3. Mensaje de bienvenida

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [x] Si https://github.com/andes/api/pull/1756
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2022-09-14 17:46 UTC, silviroa commented
USUARIO: mpalavecino  
BUILD NUMBER: [7635](http://condorpiedra.andes.gob.ar:85/7635/mochawesome.html)
CYPRESS RUN: [6481](https://dashboard.cypress.io/projects/xr7gft/runs/6481/specs)
TEST START: 2022-09-14T17:36:20.464Z
TOTAL: 406
SUCCESS: 390
FAIL: 15
SKIPPED: 1

2022-09-15 12:02 UTC, silviroa commented
USUARIO: mpalavecino  
BUILD NUMBER: [7637](http://condorpiedra.andes.gob.ar:85/7637/mochawesome.html)
CYPRESS RUN: [6538](https://dashboard.cypress.io/projects/xr7gft/runs/6538/specs)
TEST START: 2022-09-15T11:50:28.900Z
TOTAL: 406
SUCCESS: 388
FAIL: 17
SKIPPED: 1

2022-09-16 17:21 UTC, silviroa commented
USUARIO: mpalavecino  
BUILD NUMBER: [7653](http://condorpiedra.andes.gob.ar:85/7653/mochawesome.html)
CYPRESS RUN: [6583](https://dashboard.cypress.io/projects/xr7gft/runs/6583/specs)
TEST START: 2022-09-16T17:20:15.953Z
TOTAL: 1
SUCCESS: 0
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-09-16 18:01 UTC, silviroa commented
USUARIO: mpalavecino  
BUILD NUMBER: [7654](http://condorpiedra.andes.gob.ar:85/7654/mochawesome.html)
CYPRESS RUN: [6584](https://dashboard.cypress.io/projects/xr7gft/runs/6584/specs)
TEST START: 2022-09-16T18:00:25.277Z
TOTAL: 51
SUCCESS: 51
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-09-22 19:19 UTC, negro89 reviewed
Palita, al parecer la api esta bien. Pero por algun motivo, si se setean primero los filtros de organizacion, el listado se completa con muchisimos resultados (Aunque la query trae correctamente 15). Después de esto los demas filtros quedan sin efecto, es decir, si el response viene con cero resultados, el listado continúa mostrando el resultado anterior (Dejo captura de esto ultimo)
No revisé el código pero este fue el comportamiento a primera prueba.

![image](https://user-images.githubusercontent.com/37875706/191832994-8b6f8085-bc92-4454-8f20-0d8f70f37d87.png)

2022-10-06 10:54 UTC, AgosLizzi requested changes
Actualizar
![image](https://user-images.githubusercontent.com/72876985/194295497-27737871-6c22-4ea1-9a49-01a931122ca6.png)

2022-10-18 21:11 UTC, negro89 commented
@AgosLizzi corregido.
Se actualiza la rama con master.

2022-10-18 21:31 UTC, negro89 approved these changes

2022-10-18 21:46 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7785](http://condorpiedra.andes.gob.ar:85/7785/mochawesome.html)
CYPRESS RUN: [6923](https://dashboard.cypress.io/projects/xr7gft/runs/6923/specs)
TEST START: 2022-10-18T21:46:46.473Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

2022-10-20 14:30 UTC, AgosLizzi requested changes
1) El mensaje de bienvenida necesita un ajuste, el texto esta redacatando casi como una orden. Utilizaría como ejemplos otros mensajes de bienvenidas más polite. Dejo ejemplo:
![image](https://user-images.githubusercontent.com/72876985/196977046-e9e993ee-71b1-4c5b-b115-159c259b3a42.png)
2) También aprovecharía y cambiaría de color el título asi le damos una jerarquía.
3) Estos dos "mensajes" no pueden existir juntos. 
![image](https://user-images.githubusercontent.com/72876985/196977408-dc814b28-acb4-443d-8825-3650a1e8b8f9.png)

2022-11-01 16:53 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7864](http://condorpiedra.andes.gob.ar:85/7864/mochawesome.html)
CYPRESS RUN: [6999](https://dashboard.cypress.io/projects/xr7gft/runs/6999/specs)
TEST START: 2022-11-01T16:53:01.867Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

2022-11-02 15:04 UTC, AgosLizzi approved these changes

2022-12-06 17:03 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8102](http://condorpiedra.andes.gob.ar:85/8102/mochawesome.html)
CYPRESS RUN: [7292](https://dashboard.cypress.io/projects/xr7gft/runs/7292/specs)
TEST START: 2022-12-06T17:02:50.586Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2022-12-06 18:25 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8106](http://condorpiedra.andes.gob.ar:85/8106/mochawesome.html)
CYPRESS RUN: [7295](https://dashboard.cypress.io/projects/xr7gft/runs/7295/specs)
TEST START: 2022-12-06T18:14:27.995Z
TOTAL: 406
SUCCESS: 389
FAIL: 15
SKIPPED: 2

2022-12-07 13:08 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8113](http://condorpiedra.andes.gob.ar:85/8113/mochawesome.html)
CYPRESS RUN: [7300](https://dashboard.cypress.io/projects/xr7gft/runs/7300/specs)
TEST START: 2022-12-07T12:58:14.896Z
TOTAL: 406
SUCCESS: 390
FAIL: 14
SKIPPED: 2

2022-12-07 14:41 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8114](http://condorpiedra.andes.gob.ar:85/8114/mochawesome.html)
CYPRESS RUN: [7301](https://dashboard.cypress.io/projects/xr7gft/runs/7301/specs)
TEST START: 2022-12-07T14:30:18.440Z
TOTAL: 406
SUCCESS: 389
FAIL: 15
SKIPPED: 2

2022-12-07 17:53 UTC, merged