fix(IN-492): control de fechas de registro
andes/app pull request #2761
Opened 2022-09-20 15:06 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-492

### Funcionalidad desarrollada 

1.  Se resto un minuto al valor minimo de la hora para que pueda generar un nuevo registro apenas se termina de internar a un paciente. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-09-20 15:31 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [7668](http://condorpiedra.andes.gob.ar:85/7668/mochawesome.html)
CYPRESS RUN: [6601](https://dashboard.cypress.io/projects/xr7gft/runs/6601/specs)
TEST START: 2022-09-20T15:31:01.846Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

2022-09-20 16:04 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [7670](http://condorpiedra.andes.gob.ar:85/7670/mochawesome.html)
CYPRESS RUN: [6604](https://dashboard.cypress.io/projects/xr7gft/runs/6604/specs)
TEST START: 2022-09-20T15:43:23.040Z
TOTAL: 363
SUCCESS: 351
FAIL: 11
SKIPPED: 1

2022-09-20 17:40 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [7671](http://condorpiedra.andes.gob.ar:85/7671/mochawesome.html)
CYPRESS RUN: [6608](https://dashboard.cypress.io/projects/xr7gft/runs/6608/specs)
TEST START: 2022-09-20T17:30:45.019Z
TOTAL: 406
SUCCESS: 390
FAIL: 15
SKIPPED: 1

2022-09-22 18:55 UTC, negro89 approved these changes

2022-10-19 15:46 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7793](http://condorpiedra.andes.gob.ar:85/7793/mochawesome.html)
CYPRESS RUN: [6931](https://dashboard.cypress.io/projects/xr7gft/runs/6931/specs)
TEST START: 2022-10-19T15:24:35.497Z
TOTAL: 335
SUCCESS: 320
FAIL: 14
SKIPPED: 1

2022-10-19 19:19 UTC, MCele requested changes
Revisar funcionamiento, porque sigue sin poder resolverse del todo bien, por ejemplo un caso de ingreso 16:14, se quiere cargar un registro médico 16:17, pero el botón no se habilita (a simple vista parece que utiliza la fecha actual del mapa para comparar),
![image](https://user-images.githubusercontent.com/19591224/196783814-f3438d37-50b5-4932-af83-1d5056d197c0.png)

2022-10-25 11:24 UTC, MarianoCampetella commented
> Revisar funcionamiento, porque sigue sin poder resolverse del todo bien, por ejemplo un caso de ingreso 16:14, se quiere cargar un registro médico 16:17, pero el botón no se habilita (a simple vista parece que utiliza la fecha actual del mapa para comparar), ![image](https://user-images.githubusercontent.com/19591224/196783814-f3438d37-50b5-4932-af83-1d5056d197c0.png)

Corregido!

2022-10-28 12:44 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [7850](http://condorpiedra.andes.gob.ar:85/7850/mochawesome.html)
CYPRESS RUN: [6985](https://dashboard.cypress.io/projects/xr7gft/runs/6985/specs)
TEST START: 2022-10-28T12:36:34.542Z
TOTAL: 343
SUCCESS: 337
FAIL: 5
SKIPPED: 1

2022-10-28 13:14 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [7852](http://condorpiedra.andes.gob.ar:85/7852/mochawesome.html)
CYPRESS RUN: [6987](https://dashboard.cypress.io/projects/xr7gft/runs/6987/specs)
TEST START: 2022-10-28T13:13:22.302Z
TOTAL: 379
SUCCESS: 371
FAIL: 7
SKIPPED: 1

2022-10-28 14:37 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [7855](http://condorpiedra.andes.gob.ar:85/7855/mochawesome.html)
CYPRESS RUN: [6990](https://dashboard.cypress.io/projects/xr7gft/runs/6990/specs)
TEST START: 2022-10-28T14:36:46.611Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-11-18 19:57 UTC, MCele commented on src/app/apps/rup/mapa-camas/sidebar/nuevo-registro-salud/nuevo-registro-salud.component.ts
> +            return moment(this.internacion.fechaIngreso).subtract(1, 'minutes').toDate();
por qué es necesario restar un minuto del tiempo? esto permite generar un registro médico un minuto antes de la internación. Por ejemplo internación creada  alas 16:43, puede cargarse un registro con fecha 16:42.
![image](https://user-images.githubusercontent.com/19591224/202791705-64855142-2494-4c6f-bb14-0c44d63a2f03.png)

![image](https://user-images.githubusercontent.com/19591224/202791571-2093e815-fabb-41ce-8680-0f49a6ef52de.png)

2023-01-13 18:40 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/sidebar/nuevo-registro-salud/nuevo-registro-salud.component.ts
> +            return moment(this.internacion.fechaIngreso).subtract(1, 'minutes').toDate();
Después de una revisión profunda, se observa que si la internación fue en un horario con 0 segundos ahí ocurre el problema que mencionas arriba el cual me permite generar un registro nuevo con un minuto antes de que el paciente fuera internado. Entonces se agrega una condición para verificar los segundos de dicha hora y saber si se tiene que restar o no un minuto.

2023-01-19 15:25 UTC, MCele approved these changes

2023-01-19 15:32 UTC, merged