IN - Validar internacion capa Estadistica
andes/app pull request #2762
Opened 2022-09-21 18:26 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-490

### Funcionalidad desarrollada 

1. FIltra la internación que se esta visualizando para que no aparezca en los registros de la huds
2. Agrega formulario para validación de fechas

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-09-21 19:59 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7676](http://condorpiedra.andes.gob.ar:85/7676/mochawesome.html)
CYPRESS RUN: [6659](https://dashboard.cypress.io/projects/xr7gft/runs/6659/specs)
TEST START: 2022-09-21T19:59:09.436Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-10-20 14:55 UTC, MarianoCampetella approved these changes

2022-10-20 18:33 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [7806](http://condorpiedra.andes.gob.ar:85/7806/mochawesome.html)
CYPRESS RUN: [6943](https://dashboard.cypress.io/projects/xr7gft/runs/6943/specs)
TEST START: 2022-10-20T18:31:39.260Z
TOTAL: 375
SUCCESS: 366
FAIL: 8
SKIPPED: 1

2022-10-21 18:42 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7830](http://condorpiedra.andes.gob.ar:85/7830/mochawesome.html)
CYPRESS RUN: [6965](https://dashboard.cypress.io/projects/xr7gft/runs/6965/specs)
TEST START: 2022-10-21T18:42:19.464Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-10-28 14:14 UTC, MCele requested changes

2022-10-28 14:14 UTC, MCele commented on src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
> +                estaPrestacion = prestacion;
cuidado porque prestacion a veces llega como un objeto {id:null}

2022-10-31 18:01 UTC, negro89 commented on src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
> +                estaPrestacion = prestacion;
@MCele desde el mapa de camas va a pasar siempre eso. Ahora se hicieron algunos cambios, habria que volver a checkear si filtra bien todo.

2022-11-10 18:31 UTC, MCele approved these changes

2022-11-10 19:24 UTC, merged