IN- Se visualiza edición de internación en un informe de egreso validada
andes/app pull request #2770
Opened 2022-10-27 17:24 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-506

### Funcionalidad desarrollada 

1. Se crea una nueva variable booleana puedeEditar para verificar en otro componente si puede editar o no una prestacion. En caso de que este validad la misma no se podrá editar. 
2. 
3. 

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2022-10-27 17:47 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [7847](http://condorpiedra.andes.gob.ar:85/7847/mochawesome.html)
CYPRESS RUN: [6982](https://dashboard.cypress.io/projects/xr7gft/runs/6982/specs)
TEST START: 2022-10-27T17:47:41.488Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-12-01 18:22 UTC, negro89 requested changes
Entiendo segun el requerimiento, que el problema no es el botón 'editar' en si, sino la visualización del formulario como si se estuviese editando. Teniendo en cuenta esto, el problema persiste.

De todas maneras la solución propuesta no resuelve el problema, ya que para permisos de edición está el observable _permisosMapaCamasService.egreso_ y para 'modo edición' (Visualizar el formularo) la variable _editar_.

Hay que buscarle la vuelta de otra manera.

2022-12-13 13:49 UTC, MarianoCampetella commented
> Entiendo segun el requerimiento, que el problema no es el botón 'editar' en si, sino la visualización del formulario como si se estuviese editando. Teniendo en cuenta esto, el problema persiste.
> 
> De todas maneras la solución propuesta no resuelve el problema, ya que para permisos de edición está la propiedad _permisosMapaCamasService.egreso_ y para 'modo edición' (Visualizar el formularo) la variable _editar_.
> 
> Hay que buscarle la vuelta de otra manera.

Corregido, ahora no se muestra ni el botón de editar egreso ni el formulario de egreso del cual se hablo anteriormente.

2022-12-26 15:23 UTC, AgosLizzi approved these changes

2022-12-26 16:33 UTC, negro89 requested changes

2022-12-26 16:33 UTC, negro89 commented on src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
> +    @Input('internacion')
Siguiendo el workflow del listado, al momento de seleccionar un item ya se carga la prestacion en el servicio de mapa de camas (Que puede ser accedida desde cualquier componente). Por lo tanto este input está generando redundancia de código al estar pasando información que el componente ya tiene.
Lo mismo para la variable 'informeEgreso': Ya existe un observable 'existeEgreso' para consultar por este informe.

2023-01-03 12:24 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
> +    @Input('internacion')
Corregido!

2023-01-11 18:13 UTC, negro89 requested changes
Realizar modificaciones según lo charlado 👍🏼

2023-01-24 15:20 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
> +        this.prestacion$.subscribe(prestacion => {
Corregido!! Gracias por las explicaciones!

2023-01-24 15:21 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
> +    set inProgress(value: any) {
Corregido!

2023-01-24 15:21 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
> +    public loading;
Corregido!!

2023-02-09 16:48 UTC, negro89 reviewed
Solo esa observación, lo demas de 10 👍🏼

2023-02-09 16:48 UTC, negro89 commented on src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
> +    puedeEgresar(permisos, estadoPrestacion, editar, existeIngreso) {
No haría falta enviar parámetros. Se puede obtener todo dentro de la función. Idem para 'puedeEgresar()'

2023-02-09 18:01 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
> +    puedeEgresar(permisos, estadoPrestacion, editar, existeIngreso) {
Corregido!!

2023-02-09 18:25 UTC, negro89 approved these changes

2023-02-09 19:22 UTC, MCele approved these changes

2023-02-10 13:07 UTC, merged