IN - No se modifica correctamente la fecha de ingreso
andes/app pull request #2771
Opened 2022-10-28 12:18 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-505

### Funcionalidad desarrollada 

1. Se agrega un BehaviorSubject en el servicio de mapa de camas para verificar si se esta yendo al historial o al listado de internación. De esta forma podremos saber si es necesario asigarle el valor nulo a la cama dentro de un nuevo combinateLatest que se implemento. 
2. Se modifica el mensaje de los modal.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-10-28 12:59 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [7851](http://condorpiedra.andes.gob.ar:85/7851/mochawesome.html)
CYPRESS RUN: [6986](https://dashboard.cypress.io/projects/xr7gft/runs/6986/specs)
TEST START: 2022-10-28T12:58:18.988Z
TOTAL: 358
SUCCESS: 350
FAIL: 7
SKIPPED: 1

2022-10-28 13:25 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [7853](http://condorpiedra.andes.gob.ar:85/7853/mochawesome.html)
CYPRESS RUN: [6988](https://dashboard.cypress.io/projects/xr7gft/runs/6988/specs)
TEST START: 2022-10-28T13:24:12.221Z
TOTAL: 392
SUCCESS: 387
FAIL: 5
SKIPPED: 0

2022-10-28 13:39 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [7854](http://condorpiedra.andes.gob.ar:85/7854/mochawesome.html)
CYPRESS RUN: [6989](https://dashboard.cypress.io/projects/xr7gft/runs/6989/specs)
TEST START: 2022-10-28T13:39:13.604Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-10-31 12:29 UTC, AgosLizzi approved these changes

2022-12-26 17:22 UTC, negro89 commented
Mejoró pero hay un temita: Todavia permite guardar el formulario con fecha inválida, aunque este no surte efecto en el informe ni en los movimientos. Creo que con un control sobre el boton de guardar quedaría bien.
https://watch.screencastify.com/v/2PBJMO0JXH4ZVME2CNxD

2023-01-12 18:17 UTC, negro89 requested changes

2023-01-12 18:17 UTC, negro89 commented on src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
> +        <app-ingresar-paciente *ngIf="editar" (onSave)="toggleEdit()" [editar]="editar">
No parece un uso apropiado para un input. Si editar es false el componente no se renderea, por lo tando este input siempre va a ser true.
Cual es la intención? Quizas funciona bien pero habría que buscar otra alternativa.

2023-02-09 15:43 UTC, negro89 reviewed
No está mal usado el behavior, pero si es solo para chequear donde estamos parados alcanzaría con la siguiente sugerencia...

2023-02-09 15:43 UTC, negro89 commented on src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
> +                if (esMovimiento) {
```suggestion
                const currentUrl = this.router.url;
                if (currentUrl.includes('listado-internacion-medico')) {
```

2023-02-09 17:49 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
> +                if (esMovimiento) {
Corregido!!

2023-02-09 18:37 UTC, negro89 approved these changes

2023-02-09 19:23 UTC, MCele approved these changes

2023-02-10 12:59 UTC, merged