TM - Configuracion de internacion por conceptos turnuables
andes/app pull request #2772
Opened 2022-11-01 14:50 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/TM-25

### Funcionalidad desarrollada 

1. Obtiene conceptos turneables solo de la DB
2. Agrega bool para 'nuevo registro' en capa interconsultores
3. Agrega botón 'reiniciar valores' para volver a los valores del efector de referencia la capa seleccionada

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [X] Si
- [ ] No

### Requiere actualizaciones en la API

- [X] Si  https://github.com/andes/api/pull/1770
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

Agregar los siguientes conceptos en la coleccion **conceptosTurneables**

{
    "conceptId" : "5491000013101",
    "term" : "evaluación médica inicial",
    "fsn" : "evaluación médica inicial (procedimiento)",
    "semanticTag" : "procedimiento",
    "ambito" : [ 
        "internacion"
    ]
},
{
    "conceptId" : "5971000013106",
    "term" : "evolución médica",
    "fsn" : "evolución médica (procedimiento)",
    "semanticTag" : "procedimiento",
    "ambito" : [ 
        "internacion"
    ]
},
{
    "conceptId" : "6881000013107",
    "term" : "evolución no médica",
    "fsn" : "evolución no médica (procedimiento)",
    "semanticTag" : "procedimiento",
    "ambito" : [ 
        "internacion"
    ]
},
{
    "conceptId" : "4981000013105",
    "term" : "plan de indicaciones médicas",
    "fsn" : "plan de indicaciones médicas (procedimiento)",
    "semanticTag" : "procedimiento",
    "ambito" : [ 
        "internacion"
    ]
},
{
    "conceptId" : "7141000013106",
    "term" : "procedimiento intraquirúrgico del médico",
    "fsn" : "procedimiento intraquirúrgico del médico (procedimiento)",
    "semanticTag" : "procedimiento",
    "ambito" : [ 
        "internacion"
    ]
},
{
    "conceptId" : "182771004",
    "term" : "Consentimiento informado",
    "fsn" : "Consentimiento informado (procedimiento)",
    "semanticTag" : "procedimiento",
    "ambito" : [ 
        "internacion"
    ]
},
{
    "conceptId" : "363679005",
    "term" : "procedimiento de diagnóstico por imágenes",
    "fsn" : "procedimiento de diagnóstico por imágenes (procedimiento)",
    "semanticTag" : "procedimiento",
    "ambito" : [ 
        "internacion"
    ]
}

---------------------------------------------------------------------------------------------

Modificar el concepto con conceptId **5891000013104** agregando el ambito **internacion**. Quedaria asi:
{
    "conceptId": "5891000013104",
    "term": "consulta de seguimiento de paciente asociado a infección por COVID-19",
    "fsn": "consulta de seguimiento de paciente asociado a infección por COVID-19 (procedimiento)",
    "semanticTag": "procedimiento",
    "ambito": [
        "ambulatorio",
        "internacion"
    ]
}

2022-11-01 15:56 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7861](http://condorpiedra.andes.gob.ar:85/7861/mochawesome.html)
CYPRESS RUN: [6996](https://dashboard.cypress.io/projects/xr7gft/runs/6996/specs)
TEST START: 2022-11-01T15:56:36.727Z
TOTAL: 406
SUCCESS: 394
FAIL: 11
SKIPPED: 1

2022-11-01 17:06 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7865](http://condorpiedra.andes.gob.ar:85/7865/mochawesome.html)
CYPRESS RUN: [7000](https://dashboard.cypress.io/projects/xr7gft/runs/7000/specs)
TEST START: 2022-11-01T16:55:38.099Z
TOTAL: 406
SUCCESS: 389
FAIL: 16
SKIPPED: 1

2022-11-11 19:43 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7903](http://condorpiedra.andes.gob.ar:85/7903/mochawesome.html)
CYPRESS RUN: [7098](https://dashboard.cypress.io/projects/xr7gft/runs/7098/specs)
TEST START: 2022-11-11T19:43:19.018Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

2022-11-17 12:48 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7955](http://condorpiedra.andes.gob.ar:85/7955/mochawesome.html)
CYPRESS RUN: [7148](https://dashboard.cypress.io/projects/xr7gft/runs/7148/specs)
TEST START: 2022-11-17T12:48:29.097Z
TOTAL: 406
SUCCESS: 398
FAIL: 7
SKIPPED: 1

2022-11-17 13:29 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7958](http://condorpiedra.andes.gob.ar:85/7958/mochawesome.html)
CYPRESS RUN: [7151](https://dashboard.cypress.io/projects/xr7gft/runs/7151/specs)
TEST START: 2022-11-17T13:29:27.197Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-11-18 12:51 UTC, MarianoCampetella approved these changes

2023-06-07 12:03 UTC, silviroa requested changes

2023-06-07 12:03 UTC, silviroa commented on src/app/components/organizacion/configuracion-internacion.component.ts
>              this.snomed.get({
Se siguen buscando los conceptos para los registros en snomed y no en la colección de conceptosTurneables con el filtro por ámbito internación

2023-06-28 11:48 UTC, negro89 commented on src/app/components/organizacion/configuracion-internacion.component.ts
>              this.snomed.get({
Corregido @silviroa 👍🏼

2023-07-06 16:53 UTC, silviroa commented on src/app/components/organizacion/configuracion-internacion.component.ts
>              this.snomed.get({
Chequeado!

2023-07-06 16:53 UTC, silviroa approved these changes

2023-07-12 12:19 UTC, merged