CITAS - Visualizar datos del paciente en gestor de agendas
andes/app pull request #2776
Opened 2022-11-10 19:26 UTC by maring0019

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-193

### Funcionalidad desarrollada 

1. Se agrega un plex-help con el detalle del paciente. Para turnos suspendidos.
2. Se muestra el número de celular o fijo en el listado de turnos suspendidos.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-11-11 12:08 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [7893](http://condorpiedra.andes.gob.ar:85/7893/mochawesome.html)
CYPRESS RUN: [7088](https://dashboard.cypress.io/projects/xr7gft/runs/7088/specs)
TEST START: 2022-11-11T12:08:16.204Z
TOTAL: 406
SUCCESS: 394
FAIL: 11
SKIPPED: 1

2022-11-11 12:33 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [7894](http://condorpiedra.andes.gob.ar:85/7894/mochawesome.html)
CYPRESS RUN: [7089](https://dashboard.cypress.io/projects/xr7gft/runs/7089/specs)
TEST START: 2022-11-11T12:23:26.266Z
TOTAL: 406
SUCCESS: 389
FAIL: 16
SKIPPED: 1

2022-11-11 15:30 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [7897](http://condorpiedra.andes.gob.ar:85/7897/mochawesome.html)
CYPRESS RUN: [7092](https://dashboard.cypress.io/projects/xr7gft/runs/7092/specs)
TEST START: 2022-11-11T15:17:47.133Z
TOTAL: 406
SUCCESS: 386
FAIL: 19
SKIPPED: 1

2022-11-11 15:59 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [7898](http://condorpiedra.andes.gob.ar:85/7898/mochawesome.html)
CYPRESS RUN: [7093](https://dashboard.cypress.io/projects/xr7gft/runs/7093/specs)
TEST START: 2022-11-11T15:59:12.446Z
TOTAL: 356
SUCCESS: 352
FAIL: 3
SKIPPED: 1

2022-11-11 16:06 UTC, AgosLizzi requested changes
Mari, vi varios errores sobre este pr. Para comentarte hice prueba en test en demo y en ambas estaban los errores. Voy primero con los de **test**

1-  Al abrir el módulo, la consola me tira error y sobre el sidebar no se muestra información
![2022-11-11 (1)](https://user-images.githubusercontent.com/72876985/201379814-5952cda6-7179-40bd-8108-ff12015a7a12.png)

2-  Cree una nueva agenda para probar sobre esa, y esto fue lo que paso. Te dejo video asi podes ver el comportamiento del plex help
![2022-11-11 (16)](https://user-images.githubusercontent.com/72876985/201380566-10c3d19c-a9dd-4e07-83c7-8b4699a3c160.png)
 ![2022-11-11 (3)](https://user-images.githubusercontent.com/72876985/201380561-d63bc47e-8e5a-4b34-8d96-34976350c365.png)
https://www.loom.com/share/c34329aad48c460990094e07d4250da0
https://www.loom.com/share/d44198ba15ff4efa80b00a55c6217941

Y luego en demo, lo mismo:
![2022-11-11 (21)](https://user-images.githubusercontent.com/72876985/201381278-82f2f207-5224-46cd-837d-463ec104200e.png)

Cuando se solucionen todos estos conflictos, modificaría el tooltip que no esta bien explicito. Actualmente dice solo "Detalle", si nos ponemos a pensar puede ser detalle de varias cosas... Pero en este caso estamos hablando de paciente, asi que lo cambiaría a **"Detalle del paciente"**
![2022-11-11 (6)](https://user-images.githubusercontent.com/72876985/201381491-aaff051c-228a-46be-aa30-0b3025b5a31d.png)

2022-11-11 16:13 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [7899](http://condorpiedra.andes.gob.ar:85/7899/mochawesome.html)
CYPRESS RUN: [7094](https://dashboard.cypress.io/projects/xr7gft/runs/7094/specs)
TEST START: 2022-11-11T16:12:52.433Z
TOTAL: 406
SUCCESS: 402
FAIL: 3
SKIPPED: 1

2022-11-11 17:31 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [7901](http://condorpiedra.andes.gob.ar:85/7901/mochawesome.html)
CYPRESS RUN: [7096](https://dashboard.cypress.io/projects/xr7gft/runs/7096/specs)
TEST START: 2022-11-11T17:31:07.851Z
TOTAL: 406
SUCCESS: 392
FAIL: 13
SKIPPED: 1

2022-11-11 19:29 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [7902](http://condorpiedra.andes.gob.ar:85/7902/mochawesome.html)
CYPRESS RUN: [7097](https://dashboard.cypress.io/projects/xr7gft/runs/7097/specs)
TEST START: 2022-11-11T19:19:36.197Z
TOTAL: 406
SUCCESS: 389
FAIL: 16
SKIPPED: 1

2022-11-14 12:49 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [7909](http://condorpiedra.andes.gob.ar:85/7909/mochawesome.html)
CYPRESS RUN: [7104](https://dashboard.cypress.io/projects/xr7gft/runs/7104/specs)
TEST START: 2022-11-14T12:27:58.610Z
TOTAL: 346
SUCCESS: 316
FAIL: 29
SKIPPED: 1

2022-11-14 13:30 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [7911](http://condorpiedra.andes.gob.ar:85/7911/mochawesome.html)
CYPRESS RUN: [7106](https://dashboard.cypress.io/projects/xr7gft/runs/7106/specs)
TEST START: 2022-11-14T13:30:02.576Z
TOTAL: 406
SUCCESS: 396
FAIL: 9
SKIPPED: 1

2022-11-14 14:24 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [7914](http://condorpiedra.andes.gob.ar:85/7914/mochawesome.html)
CYPRESS RUN: [7109](https://dashboard.cypress.io/projects/xr7gft/runs/7109/specs)
TEST START: 2022-11-14T14:24:31.266Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

2022-11-14 14:55 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [7916](http://condorpiedra.andes.gob.ar:85/7916/mochawesome.html)
CYPRESS RUN: [7111](https://dashboard.cypress.io/projects/xr7gft/runs/7111/specs)
TEST START: 2022-11-14T14:55:46.810Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

2022-11-14 15:30 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [7918](http://condorpiedra.andes.gob.ar:85/7918/mochawesome.html)
CYPRESS RUN: [7113](https://dashboard.cypress.io/projects/xr7gft/runs/7113/specs)
TEST START: 2022-11-14T15:29:03.317Z
TOTAL: 387
SUCCESS: 369
FAIL: 18
SKIPPED: 0

2022-11-15 12:57 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [7924](http://condorpiedra.andes.gob.ar:85/7924/mochawesome.html)
CYPRESS RUN: [7119](https://dashboard.cypress.io/projects/xr7gft/runs/7119/specs)
TEST START: 2022-11-15T12:56:58.443Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

2022-11-15 15:05 UTC, maring0019 commented
Ambos puntos fueron corregidos.

2022-11-15 15:25 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [7925](http://condorpiedra.andes.gob.ar:85/7925/mochawesome.html)
CYPRESS RUN: [7120](https://dashboard.cypress.io/projects/xr7gft/runs/7120/specs)
TEST START: 2022-11-15T15:25:22.772Z
TOTAL: 406
SUCCESS: 395
FAIL: 10
SKIPPED: 1

2022-11-16 14:06 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [7933](http://condorpiedra.andes.gob.ar:85/7933/mochawesome.html)
CYPRESS RUN: [7128](https://dashboard.cypress.io/projects/xr7gft/runs/7128/specs)
TEST START: 2022-11-16T14:06:28.485Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

2022-11-16 14:19 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [7934](http://condorpiedra.andes.gob.ar:85/7934/mochawesome.html)
CYPRESS RUN: [7129](https://dashboard.cypress.io/projects/xr7gft/runs/7129/specs)
TEST START: 2022-11-16T14:19:08.345Z
TOTAL: 356
SUCCESS: 353
FAIL: 2
SKIPPED: 1

2022-11-16 16:41 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [7942](http://condorpiedra.andes.gob.ar:85/7942/mochawesome.html)
CYPRESS RUN: [7135](https://dashboard.cypress.io/projects/xr7gft/runs/7135/specs)
TEST START: 2022-11-16T16:41:38.758Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-11-28 20:54 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8026](http://condorpiedra.andes.gob.ar:85/8026/mochawesome.html)
CYPRESS RUN: [7219](https://dashboard.cypress.io/projects/xr7gft/runs/7219/specs)
TEST START: 2022-11-28T20:54:27.402Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2022-11-29 11:52 UTC, MarianoCampetella requested changes

2022-11-30 14:05 UTC, maring0019 commented
> Tooltips cortados: ![2022-11-17 (1)](https://user-images.githubusercontent.com/72876985/202443560-cd26e284-48b9-4942-b077-2f7abef59380.png) ![2022-11-17](https://user-images.githubusercontent.com/72876985/202443656-0384a05c-749e-4b47-9ddb-677c87e7c636.png)
> 
> Otro detalle: Esto no sucedia. Observemos que el fondo al volverse azul queda sin verse el badge de sms, el botón de visualizar detalle queda sin volumen y el texto rojo queda ilegible ![image](https://user-images.githubusercontent.com/72876985/202443742-0fbbfa1b-aa25-4c3d-a83f-e1d677dc768e.png)

Cambios hechos.

2022-11-30 14:05 UTC, maring0019 commented on src/app/components/turnos/dar-turnos/dar-turnos.component.ts
> +        if (event.value !== undefined && event.value !== null) {
Cambios hechos.

2022-11-30 14:06 UTC, maring0019 commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.component.ts
> +            if (this.cambioTelefono && this.telefono !== undefined && this.telefono !== null) {
Cambios hechos.

2022-11-30 19:14 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8050](http://condorpiedra.andes.gob.ar:85/8050/mochawesome.html)
CYPRESS RUN: [7242](https://dashboard.cypress.io/projects/xr7gft/runs/7242/specs)
TEST START: 2022-11-30T19:14:22.635Z
TOTAL: 406
SUCCESS: 396
FAIL: 8
SKIPPED: 2

2022-12-01 12:59 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8052](http://condorpiedra.andes.gob.ar:85/8052/mochawesome.html)
CYPRESS RUN: [7244](https://dashboard.cypress.io/projects/xr7gft/runs/7244/specs)
TEST START: 2022-12-01T12:58:58.526Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2022-12-01 13:56 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8053](http://condorpiedra.andes.gob.ar:85/8053/mochawesome.html)
CYPRESS RUN: [7245](https://dashboard.cypress.io/projects/xr7gft/runs/7245/specs)
TEST START: 2022-12-01T13:44:21.416Z
TOTAL: 406
SUCCESS: 387
FAIL: 17
SKIPPED: 2

2022-12-01 14:11 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8054](http://condorpiedra.andes.gob.ar:85/8054/mochawesome.html)
CYPRESS RUN: [7246](https://dashboard.cypress.io/projects/xr7gft/runs/7246/specs)
TEST START: 2022-12-01T14:11:45.741Z
TOTAL: 406
SUCCESS: 402
FAIL: 2
SKIPPED: 2

2022-12-01 14:23 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8055](http://condorpiedra.andes.gob.ar:85/8055/mochawesome.html)
CYPRESS RUN: [7247](https://dashboard.cypress.io/projects/xr7gft/runs/7247/specs)
TEST START: 2022-12-01T14:23:38.257Z
TOTAL: 406
SUCCESS: 402
FAIL: 2
SKIPPED: 2

2022-12-01 14:43 UTC, AgosLizzi approved these changes

2022-12-01 16:55 UTC, negro89 approved these changes
Funciona de 10. 
Unicos detalles que agregaría, aunque no sean propios de la tarea, son:  
1. Modificar el type del botón _enviar mensaje_ a 'info' o 'primary' ya que es una acción propia del sistema y agregarle su respectivo tooltip. Lo mismo con el que esta a su izquierda de _detalles de la agenda_ ya que son iconográficos y deberían llevar tooltip.
2. El tooltip de _detalles del paciente_ debería ir a la izquierda: tooltipPosition="left" (Tener esto en cuenta para el punto 1 tambien)

2022-12-02 16:26 UTC, maring0019 commented
> Funciona de 10. Unicos detalles que agregaría, aunque no sean propios de la tarea, son:
> 
> 1. Modificar el type del botón _enviar mensaje_ a 'info' o 'primary' ya que es una acción propia del sistema y agregarle su respectivo tooltip. Lo mismo con el que esta a su izquierda de _detalles de la agenda_ ya que son iconográficos y deberían llevar tooltip.
>    ![image](https://user-images.githubusercontent.com/37875706/205112988-8122e728-045b-4d3f-af13-3dc759903485.png)
> 2. El tooltip de _detalles del paciente_ debería ir a la izquierda: tooltipPosition="left" (Tener esto en cuenta para el punto 1 tambien)

Cambios no realizados por pedido de otros reviewers.

2022-12-06 13:19 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8091](http://condorpiedra.andes.gob.ar:85/8091/mochawesome.html)
CYPRESS RUN: [7283](https://dashboard.cypress.io/projects/xr7gft/runs/7283/specs)
TEST START: 2022-12-06T13:18:48.295Z
TOTAL: 406
SUCCESS: 393
FAIL: 11
SKIPPED: 2

2022-12-06 13:54 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8093](http://condorpiedra.andes.gob.ar:85/8093/mochawesome.html)
CYPRESS RUN: [7285](https://dashboard.cypress.io/projects/xr7gft/runs/7285/specs)
TEST START: 2022-12-06T13:54:06.915Z
TOTAL: 397
SUCCESS: 394
FAIL: 1
SKIPPED: 2

2022-12-06 14:25 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8095](http://condorpiedra.andes.gob.ar:85/8095/mochawesome.html)
CYPRESS RUN: [7287](https://dashboard.cypress.io/projects/xr7gft/runs/7287/specs)
TEST START: 2022-12-06T14:22:45.987Z
TOTAL: 338
SUCCESS: 311
FAIL: 25
SKIPPED: 2

2022-12-06 16:01 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8099](http://condorpiedra.andes.gob.ar:85/8099/mochawesome.html)
CYPRESS RUN: [7290](https://dashboard.cypress.io/projects/xr7gft/runs/7290/specs)
TEST START: 2022-12-06T16:01:17.748Z
TOTAL: 406
SUCCESS: 395
FAIL: 9
SKIPPED: 2

2022-12-06 16:32 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8101](http://condorpiedra.andes.gob.ar:85/8101/mochawesome.html)
CYPRESS RUN: [7291](https://dashboard.cypress.io/projects/xr7gft/runs/7291/specs)
TEST START: 2022-12-06T16:22:30.035Z
TOTAL: 340
SUCCESS: 313
FAIL: 25
SKIPPED: 2

2023-01-03 17:17 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8199](http://condorpiedra.andes.gob.ar:85/8199/mochawesome.html)
CYPRESS RUN: [7384](https://dashboard.cypress.io/projects/xr7gft/runs/7384/specs)
TEST START: 2023-01-03T17:17:04.426Z
TOTAL: 406
SUCCESS: 396
FAIL: 8
SKIPPED: 2

2023-01-03 17:34 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8200](http://condorpiedra.andes.gob.ar:85/8200/mochawesome.html)
CYPRESS RUN: [7385](https://dashboard.cypress.io/projects/xr7gft/runs/7385/specs)
TEST START: 2023-01-03T17:33:31.781Z
TOTAL: 364
SUCCESS: 346
FAIL: 16
SKIPPED: 2

2023-01-04 14:48 UTC, MarianoCampetella approved these changes

2023-01-05 14:43 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8213](http://condorpiedra.andes.gob.ar:85/8213/mochawesome.html)
CYPRESS RUN: [7398](https://dashboard.cypress.io/projects/xr7gft/runs/7398/specs)
TEST START: 2023-01-05T14:42:23.613Z
TOTAL: 380
SUCCESS: 373
FAIL: 5
SKIPPED: 2

2023-01-05 15:30 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8215](http://condorpiedra.andes.gob.ar:85/8215/mochawesome.html)
CYPRESS RUN: [7400](https://dashboard.cypress.io/projects/xr7gft/runs/7400/specs)
TEST START: 2023-01-05T15:30:20.250Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-01-09 16:11 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8231](http://condorpiedra.andes.gob.ar:85/8231/mochawesome.html)
CYPRESS RUN: [7415](https://dashboard.cypress.io/projects/xr7gft/runs/7415/specs)
TEST START: 2023-01-09T16:11:00.250Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-01-18 17:31 UTC, merged