IN - Plan de indicaciones: Restricciones sobre la carga de indicación
andes/app pull request #2780
Opened 2022-11-22 13:39 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-509
https://proyectos.andes.gob.ar/browse/IN-507

### Funcionalidad desarrollada 

1. Actualiza pipe de detalles de la indicacion para poder ver la frecuencia en primera instancia
2. Se restringe la edición solo a indicaciones no validadas
3. Se restringe la ejecucion de eventos a la capa enfermeria exclusivamente

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-11-22 14:02 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7988](http://condorpiedra.andes.gob.ar:85/7988/mochawesome.html)
CYPRESS RUN: [7181](https://dashboard.cypress.io/projects/xr7gft/runs/7181/specs)
TEST START: 2022-11-22T13:58:56.851Z
TOTAL: 406
SUCCESS: 397
FAIL: 8
SKIPPED: 1

2022-11-22 16:46 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7990](http://condorpiedra.andes.gob.ar:85/7990/mochawesome.html)
CYPRESS RUN: [7183](https://dashboard.cypress.io/projects/xr7gft/runs/7183/specs)
TEST START: 2022-11-22T16:44:48.001Z
TOTAL: 361
SUCCESS: 351
FAIL: 9
SKIPPED: 1

2022-11-22 17:10 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7992](http://condorpiedra.andes.gob.ar:85/7992/mochawesome.html)
CYPRESS RUN: [7185](https://dashboard.cypress.io/projects/xr7gft/runs/7185/specs)
TEST START: 2022-11-22T16:59:40.323Z
TOTAL: 406
SUCCESS: 389
FAIL: 16
SKIPPED: 1

2022-11-22 18:38 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7996](http://condorpiedra.andes.gob.ar:85/7996/mochawesome.html)
CYPRESS RUN: [7189](https://dashboard.cypress.io/projects/xr7gft/runs/7189/specs)
TEST START: 2022-11-22T18:37:16.343Z
TOTAL: 382
SUCCESS: 372
FAIL: 9
SKIPPED: 1

2022-12-05 14:53 UTC, AgosLizzi requested changes
Lauti, los cambios los veo bien. Pero tengo una pequeña duda, el badge de ON HOLD, a que hace referencia? 
![2022-12-05 (4)](https://user-images.githubusercontent.com/72876985/205666239-b50a7f3c-d37f-4a89-b022-61250ba186fb.png)
 y luego al seleccionar un paciente me aparecieron ciertos errores en la consola, y para ver el sidebar también. te adjunto imagen. Probe con dos pacientes dif por las dudas
![2022-12-05 (5)](https://user-images.githubusercontent.com/72876985/205667433-87568acd-d3b8-427e-83db-5ccb89078f34.png)
![2022-12-05 (6)](https://user-images.githubusercontent.com/72876985/205667442-16004a39-d7ad-45cd-82dd-c05425252f23.png)
![2022-12-05 (7)](https://user-images.githubusercontent.com/72876985/205667445-81758ebe-092a-4661-bae2-d79360b373f5.png)

2022-12-13 14:23 UTC, negro89 commented
@AgosLizzi, el badge en la 1ra imagen describe el estado del evento seguido del horario de la ultima actualizacion. Como está en 'on-hold' (borrador), la hora corresponde a la aprobación por parte de interconsultores.
Intenté reproducir los errores pero no pude 😥, quizás algun fix que subió a producción y se corrigió cuando actualicé la rama. Sigo probando!

2022-12-13 14:38 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8127](http://condorpiedra.andes.gob.ar:85/8127/mochawesome.html)
CYPRESS RUN: [7314](https://dashboard.cypress.io/projects/xr7gft/runs/7314/specs)
TEST START: 2022-12-13T14:37:46.148Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2022-12-26 14:23 UTC, negro89 commented
REVISADO AL 26/12..
@MCele @silviroa 
- Se corrigió un error que figuraba en consola al clickear (capa medica) en una celula (horario) vacía. En demo se veía bien pero a agos le sigue figurando el error (Probablemente caché. REVISAR POR FAVOR).

2022-12-26 14:25 UTC, AgosLizzi approved these changes

2023-01-18 12:51 UTC, MarianoCampetella approved these changes

2023-01-18 17:48 UTC, merged