CIT - Visualizar badge No asistió en historial de turnos
andes/app pull request #2783
Opened 2022-11-24 14:14 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/CIT-200

### Funcionalidad desarrollada 

1. Se agregó un badge "NO ASISTIÓ" junto con las condiciones necesarias para que un paciente que no asistió a su turno no figure con el badge de ASIGNADO sino con el dicho al principio.  

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-11-24 15:20 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8003](http://condorpiedra.andes.gob.ar:85/8003/mochawesome.html)
CYPRESS RUN: [7196](https://dashboard.cypress.io/projects/xr7gft/runs/7196/specs)
TEST START: 2022-11-24T15:19:43.536Z
TOTAL: 99
SUCCESS: 0
FAIL: 99
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-11-24 17:05 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8008](http://condorpiedra.andes.gob.ar:85/8008/mochawesome.html)
CYPRESS RUN: [7201](https://dashboard.cypress.io/projects/xr7gft/runs/7201/specs)
TEST START: 2022-11-24T17:05:01.589Z
TOTAL: 356
SUCCESS: 352
FAIL: 3
SKIPPED: 1

2022-11-24 17:52 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8009](http://condorpiedra.andes.gob.ar:85/8009/mochawesome.html)
CYPRESS RUN: [7202](https://dashboard.cypress.io/projects/xr7gft/runs/7202/specs)
TEST START: 2022-11-24T17:41:27.849Z
TOTAL: 406
SUCCESS: 391
FAIL: 14
SKIPPED: 1

2022-11-24 18:04 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8010](http://condorpiedra.andes.gob.ar:85/8010/mochawesome.html)
CYPRESS RUN: [7203](https://dashboard.cypress.io/projects/xr7gft/runs/7203/specs)
TEST START: 2022-11-24T18:03:46.689Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-12-01 14:04 UTC, negro89 approved these changes

2022-12-05 14:28 UTC, AgosLizzi requested changes
Separar y poner tilde por fa

![image](https://user-images.githubusercontent.com/72876985/205661439-e3727c30-eabe-414e-9281-2196f94e4e05.png)

Tal cual como aparece acá:
![image](https://user-images.githubusercontent.com/72876985/205661521-fd86ca0d-046a-4036-bf1b-cab8f352e8de.png)

2022-12-13 11:33 UTC, AgosLizzi approved these changes

2022-12-13 18:05 UTC, MCele approved these changes

2022-12-14 13:38 UTC, merged