TOP - componentes superpuestos
andes/app pull request #2784
Opened 2022-11-25 14:47 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/TOP-147

### Funcionalidad desarrollada 

1. Se eliminó la palabra Tipo de prestación dentro de la columna "Datos destino"
2. Se agrego un dropdown que engloba todas las posibles acciones de cada solicitud.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-11-25 15:12 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8014](http://condorpiedra.andes.gob.ar:85/8014/mochawesome.html)
CYPRESS RUN: [7207](https://dashboard.cypress.io/projects/xr7gft/runs/7207/specs)
TEST START: 2022-11-25T15:11:18.790Z
TOTAL: 406
SUCCESS: 395
FAIL: 10
SKIPPED: 1

2022-11-25 15:33 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8016](http://condorpiedra.andes.gob.ar:85/8016/mochawesome.html)
CYPRESS RUN: [7209](https://dashboard.cypress.io/projects/xr7gft/runs/7209/specs)
TEST START: 2022-11-25T15:32:40.713Z
TOTAL: 366
SUCCESS: 346
FAIL: 19
SKIPPED: 1

2022-11-28 15:33 UTC, AgosLizzi requested changes
Campe, vi dos detalles mini :
- Fijate que al seleccionar los botones en el dropdown por una milésima de segundos desaparece la palabra al presionarlos, en todos ocurre lo mismo. Lo que siempre queda fijo es el signo. Si es posible dejaría a ambos visibles (palabra + signo)
https://www.loom.com/share/7b477934d36449fa83e503a88d6d6177
- Luego esto: Al borde de superponerse. Hay alguna manera de separarlos un poquito? 
![2022-11-28 (1)](https://user-images.githubusercontent.com/72876985/204317410-25b98671-b292-4570-8a3a-af4ff6a240f6.png)
![2022-11-28](https://user-images.githubusercontent.com/72876985/204317421-12f79bc5-966d-4f6d-a175-27bd04cb9ff9.png)

2022-12-01 14:08 UTC, MarianoCampetella commented
> Campe, vi dos detalles mini :
> 
> * Fijate que al seleccionar los botones en el dropdown por una milésima de segundos desaparece la palabra al presionarlos, en todos ocurre lo mismo. Lo que siempre queda fijo es el signo. Si es posible dejaría a ambos visibles (palabra + signo)
>   https://www.loom.com/share/7b477934d36449fa83e503a88d6d6177
> * Luego esto: Al borde de superponerse. Hay alguna manera de separarlos un poquito?
>   ![2022-11-28 (1)](https://user-images.githubusercontent.com/72876985/204317410-25b98671-b292-4570-8a3a-af4ff6a240f6.png)
>   ![2022-11-28](https://user-images.githubusercontent.com/72876985/204317421-12f79bc5-966d-4f6d-a175-27bd04cb9ff9.png)

Corregido, al seleccionar los items del dropdown cambian al color celeste. 
Por otro lado como se cambio el listado por una tabla, los componentes se acomodan en base al ancho de cada columna, pero se encuentran alineados en su mayoria.

2022-12-01 21:14 UTC, negro89 reviewed
La leyenda 'Tipo de prestación' sigue apareciendo en la columna 'Datos destino'. Habría que sacarla.
![image](https://user-images.githubusercontent.com/37875706/205160159-35ea0529-46f2-48ff-8ca5-90ac94e7431b.png)

2022-12-02 14:20 UTC, MarianoCampetella commented
> La leyenda 'Tipo de prestación' sigue apareciendo en la columna 'Datos destino'. Habría que sacarla. ![image](https://user-images.githubusercontent.com/37875706/205160159-35ea0529-46f2-48ff-8ca5-90ac94e7431b.png)

No logro ver la leyenda "Tipo de prestación" tanto en las solicitudes de entrada como de salida. Lo revise varias veces pero en el código no figura ya que fue removido con anterioridad.

2022-12-02 14:21 UTC, MarianoCampetella commented on src/app/components/top/solicitudes/solicitudes.component.ts
> +                params['ordenFechaDescAct'] = true;
Según lo charlado se removieron esas variables! de todas formas filtra por orden descendente si filtra por fecha de registro o fecha de actualización.

2022-12-02 14:49 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8062](http://condorpiedra.andes.gob.ar:85/8062/mochawesome.html)
CYPRESS RUN: [7254](https://dashboard.cypress.io/projects/xr7gft/runs/7254/specs)
TEST START: 2022-12-02T14:48:13.749Z
TOTAL: 406
SUCCESS: 384
FAIL: 20
SKIPPED: 2

2022-12-02 18:53 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8069](http://condorpiedra.andes.gob.ar:85/8069/mochawesome.html)
CYPRESS RUN: [7261](https://dashboard.cypress.io/projects/xr7gft/runs/7261/specs)
TEST START: 2022-12-02T18:42:51.138Z
TOTAL: 406
SUCCESS: 390
FAIL: 14
SKIPPED: 2

2022-12-05 11:31 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8074](http://condorpiedra.andes.gob.ar:85/8074/mochawesome.html)
CYPRESS RUN: [7266](https://dashboard.cypress.io/projects/xr7gft/runs/7266/specs)
TEST START: 2022-12-05T11:31:40.121Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2022-12-13 11:04 UTC, AgosLizzi approved these changes

2022-12-14 19:36 UTC, negro89 approved these changes

2023-01-13 19:41 UTC, MCele requested changes
Las opcines de acciones a realizar no siempre coinciden con los botones originales. Caso detectado para "ver Huds". Se ven 3 acciones posibles:
![image](https://user-images.githubusercontent.com/19591224/212404476-e11414bd-8e5e-4f31-8578-843d8affa40d.png)
deberían verse 2:
![image](https://user-images.githubusercontent.com/19591224/212405241-4bc7b4bd-176b-40a4-966b-8ec3a391006e.png)

2023-01-16 17:25 UTC, MarianoCampetella commented
> 
He tratado de reproducir el caso para encontrarle la solución pero no logre llegar al problema de la imagen. Incluso compare varios botones de demo con mi local de la rama y no encontré ningún botón o estado fuera de su lugar. 

DEMO
![image](https://user-images.githubusercontent.com/65697028/212735644-35f823bd-5b3d-4625-ac58-0621ee955d93.png)
LOCAL con la rama en TOP-147
![image](https://user-images.githubusercontent.com/65697028/212735756-ba5e85e3-2a36-4a34-a118-e28634b9803d.png)

2023-01-26 13:48 UTC, MarianoCampetella commented
> Las opcines de acciones a realizar no siempre coinciden con los botones originales. Caso detectado para "ver Huds". Se ven 3 acciones posibles: ![image](https://user-images.githubusercontent.com/19591224/212404476-e11414bd-8e5e-4f31-8578-843d8affa40d.png) deberían verse 2: ![image](https://user-images.githubusercontent.com/19591224/212405241-4bc7b4bd-176b-40a4-966b-8ec3a391006e.png)

Corregido!! Ahora se va a mostrar el boton "ver HUDS" cuando corresponde!

2023-02-07 15:28 UTC, MCele approved these changes

2023-02-07 15:45 UTC, merged