RUP - No se visualiza botón iniciar prestación
andes/app pull request #2787
Opened 2022-12-14 13:18 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/RUP-334

### Funcionalidad desarrollada 

1. Se corrige chequeo de permisos. En lugar de consultar a auth por id de prestacion, se consulta a un array previamente cargado con permisos por conceptId.

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-12-14 13:53 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8132](http://condorpiedra.andes.gob.ar:85/8132/mochawesome.html)
CYPRESS RUN: [7319](https://dashboard.cypress.io/projects/xr7gft/runs/7319/specs)
TEST START: 2022-12-14T13:52:23.456Z
TOTAL: 323
SUCCESS: 292
FAIL: 29
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-12-14 19:33 UTC, MCele commented
En el punto de inicio de RUP cuando observo una agenda, además de poder visualizar el botón de iniciar prestación, independientemente de la prestación asociada al turno (ej "consulta de oftalmología" o "consulta con médico oculista"), como lo indica la tarea, el usuario debería seguir viendo todas las agendas de acuerdo al conceptId del permiso que tenga, es decir si tengo permiso para "consulta con médico oculista", debería poder ver las agendas para las prestaciones de "consulta de oftalmología" o vicersa, pero esto último con estos cambios no se está cumpliendo.

2022-12-19 18:52 UTC, MCele requested changes
me parece que se debería revisar el comportamiento de las agendas que no se visualizan, cuando se tiene uno de los permisos.

2022-12-27 13:33 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [8162](http://condorpiedra.andes.gob.ar:85/8162/mochawesome.html)
CYPRESS RUN: [7349](https://dashboard.cypress.io/projects/xr7gft/runs/7349/specs)
TEST START: 2022-12-27T13:33:33.763Z
TOTAL: 406
SUCCESS: 397
FAIL: 7
SKIPPED: 2

2022-12-27 14:48 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [8164](http://condorpiedra.andes.gob.ar:85/8164/mochawesome.html)
CYPRESS RUN: [7351](https://dashboard.cypress.io/projects/xr7gft/runs/7351/specs)
TEST START: 2022-12-27T14:48:14.447Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2022-12-27 15:15 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [8165](http://condorpiedra.andes.gob.ar:85/8165/mochawesome.html)
CYPRESS RUN: [7352](https://dashboard.cypress.io/projects/xr7gft/runs/7352/specs)
TEST START: 2022-12-27T15:00:21.877Z
TOTAL: 402
SUCCESS: 379
FAIL: 21
SKIPPED: 2

2022-12-27 15:29 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [8166](http://condorpiedra.andes.gob.ar:85/8166/mochawesome.html)
CYPRESS RUN: [7353](https://dashboard.cypress.io/projects/xr7gft/runs/7353/specs)
TEST START: 2022-12-27T15:29:03.392Z
TOTAL: 406
SUCCESS: 397
FAIL: 7
SKIPPED: 2

2022-12-27 16:07 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [8167](http://condorpiedra.andes.gob.ar:85/8167/mochawesome.html)
CYPRESS RUN: [7354](https://dashboard.cypress.io/projects/xr7gft/runs/7354/specs)
TEST START: 2022-12-27T16:06:02.331Z
TOTAL: 394
SUCCESS: 370
FAIL: 22
SKIPPED: 2

2022-12-27 16:26 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [8168](http://condorpiedra.andes.gob.ar:85/8168/mochawesome.html)
CYPRESS RUN: [7355](https://dashboard.cypress.io/projects/xr7gft/runs/7355/specs)
TEST START: 2022-12-27T16:26:15.423Z
TOTAL: 371
SUCCESS: 362
FAIL: 7
SKIPPED: 2

2022-12-27 16:41 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [8169](http://condorpiedra.andes.gob.ar:85/8169/mochawesome.html)
CYPRESS RUN: [7356](https://dashboard.cypress.io/projects/xr7gft/runs/7356/specs)
TEST START: 2022-12-27T16:41:25.219Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2022-12-27 16:53 UTC, MCele approved these changes

2022-12-27 16:59 UTC, MarianoCampetella approved these changes

2022-12-27 17:01 UTC, merged