CITAS - Refactor al crear una nota en el gestor de agendas
andes/app pull request #2793
Opened 2022-12-21 15:42 UTC by maring0019

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-194
### Funcionalidad desarrollada 

1. 
2. 
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2022-12-21 16:05 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8146](http://condorpiedra.andes.gob.ar:85/8146/mochawesome.html)
CYPRESS RUN: [7333](https://dashboard.cypress.io/projects/xr7gft/runs/7333/specs)
TEST START: 2022-12-21T16:04:19.631Z
TOTAL: 378
SUCCESS: 371
FAIL: 5
SKIPPED: 2

2022-12-21 17:06 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8147](http://condorpiedra.andes.gob.ar:85/8147/mochawesome.html)
CYPRESS RUN: [7334](https://dashboard.cypress.io/projects/xr7gft/runs/7334/specs)
TEST START: 2022-12-21T17:06:00.197Z
TOTAL: 406
SUCCESS: 397
FAIL: 7
SKIPPED: 2

2022-12-21 17:21 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8148](http://condorpiedra.andes.gob.ar:85/8148/mochawesome.html)
CYPRESS RUN: [7335](https://dashboard.cypress.io/projects/xr7gft/runs/7335/specs)
TEST START: 2022-12-21T17:21:28.167Z
TOTAL: 406
SUCCESS: 397
FAIL: 7
SKIPPED: 2

2022-12-21 17:39 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8149](http://condorpiedra.andes.gob.ar:85/8149/mochawesome.html)
CYPRESS RUN: [7336](https://dashboard.cypress.io/projects/xr7gft/runs/7336/specs)
TEST START: 2022-12-21T17:29:49.724Z
TOTAL: 406
SUCCESS: 390
FAIL: 14
SKIPPED: 2

2022-12-21 17:55 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8150](http://condorpiedra.andes.gob.ar:85/8150/mochawesome.html)
CYPRESS RUN: [7337](https://dashboard.cypress.io/projects/xr7gft/runs/7337/specs)
TEST START: 2022-12-21T17:55:19.675Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-01-02 12:07 UTC, MarianoCampetella commented
Mari, hay problemas de linteo en algunas clases. Para solucionarlos hace npm run lint -- --fix

2023-01-04 15:48 UTC, MarianoCampetella approved these changes

2023-01-04 16:53 UTC, AgosLizzi requested changes
Cuando selecciono más de una nota, el detalle sobre el sidebar queda ordenado de tal manera que no se puede diferenciar que fecha, ni prestación ni espacio fisico corresponde a casa. 
![01](https://user-images.githubusercontent.com/72876985/210607249-9b946fbf-3f59-4591-9088-58791147236b.png)
![02](https://user-images.githubusercontent.com/72876985/210607256-4a3120da-352d-4521-9508-02bd7b870ee7.png)
 
Me parece que en estos casos se podría reever otra visualización más legible para la persona usuaria.

Y como un detalle mínimo, el icono del check esta un poco más grande que el de cerrar 
![image](https://user-images.githubusercontent.com/72876985/210607713-74150555-07cd-4283-9dd7-5a6c401bdabb.png)
Te dejo como ejemplo dos iconos que están con el mismo tamaño 
![image](https://user-images.githubusercontent.com/72876985/210610565-fc5101dc-6dde-4da9-a5c0-b70c21570752.png)

2023-01-05 18:23 UTC, MCele commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/nota-agenda.html
> +            <ng-container *ngFor="let agenda of agendasSeleccionadas; let i = index">
Cada iteración del ngFor debería contener un plex-item para que cuando se selecciones más de una agenda se pueda diferenciar el dato de cada una. Entonces, se puede mover el plex-item de la línea 11 dentro de la repetitiva.

2023-01-06 12:11 UTC, maring0019 commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/nota-agenda.html
> +            <ng-container *ngFor="let agenda of agendasSeleccionadas; let i = index">
Se soluciona. Pero modifica el mockup pedido para esta tarea.

2023-01-06 12:20 UTC, maring0019 commented
> Cuando selecciono más de una nota, el detalle sobre el sidebar queda ordenado de tal manera que no se puede diferenciar que fecha, ni prestación ni espacio fisico corresponde a cada. ![01](https://user-images.githubusercontent.com/72876985/210607249-9b946fbf-3f59-4591-9088-58791147236b.png) ![02](https://user-images.githubusercontent.com/72876985/210607256-4a3120da-352d-4521-9508-02bd7b870ee7.png)
> 
> Me parece que en estos casos se podría reever otra visualización más legible para la persona usuaria.
> 
> Y como un detalle mínimo, el icono del check esta un poco más grande que el de cerrar ![image](https://user-images.githubusercontent.com/72876985/210607713-74150555-07cd-4283-9dd7-5a6c401bdabb.png) Te dejo como ejemplo dos iconos que están con el mismo tamaño ![image](https://user-images.githubusercontent.com/72876985/210610565-fc5101dc-6dde-4da9-a5c0-b70c21570752.png)

Hay una solución pero modifica el mockup pedido para esta tarea. Reveer si se hace o no ese cambio.

2023-01-06 15:44 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8220](http://condorpiedra.andes.gob.ar:85/8220/mochawesome.html)
CYPRESS RUN: [7405](https://dashboard.cypress.io/projects/xr7gft/runs/7405/specs)
TEST START: 2023-01-06T15:43:47.150Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-01-06 16:52 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8221](http://condorpiedra.andes.gob.ar:85/8221/mochawesome.html)
CYPRESS RUN: [7406](https://dashboard.cypress.io/projects/xr7gft/runs/7406/specs)
TEST START: 2023-01-06T16:42:31.727Z
TOTAL: 406
SUCCESS: 390
FAIL: 14
SKIPPED: 2

2023-01-06 17:41 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8222](http://condorpiedra.andes.gob.ar:85/8222/mochawesome.html)
CYPRESS RUN: [7407](https://dashboard.cypress.io/projects/xr7gft/runs/7407/specs)
TEST START: 2023-01-06T17:41:00.400Z
TOTAL: 406
SUCCESS: 392
FAIL: 12
SKIPPED: 2

2023-01-06 18:05 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8223](http://condorpiedra.andes.gob.ar:85/8223/mochawesome.html)
CYPRESS RUN: [7408](https://dashboard.cypress.io/projects/xr7gft/runs/7408/specs)
TEST START: 2023-01-06T18:05:03.892Z
TOTAL: 388
SUCCESS: 384
FAIL: 2
SKIPPED: 2

2023-01-06 18:21 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8224](http://condorpiedra.andes.gob.ar:85/8224/mochawesome.html)
CYPRESS RUN: [7409](https://dashboard.cypress.io/projects/xr7gft/runs/7409/specs)
TEST START: 2023-01-06T18:20:29.046Z
TOTAL: 394
SUCCESS: 387
FAIL: 5
SKIPPED: 2

2023-01-09 15:38 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8229](http://condorpiedra.andes.gob.ar:85/8229/mochawesome.html)
CYPRESS RUN: [7413](https://dashboard.cypress.io/projects/xr7gft/runs/7413/specs)
TEST START: 2023-01-09T15:37:52.178Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-01-12 12:36 UTC, negro89 commented
@maring0019 quizas, para no trabar el pr, se podria realizar los cambios aunque se salga un poquito del mockup. Después para lo que haya que corregir podemos ir tirando propuestas 👍🏼 ..Te parece?

2023-01-17 15:34 UTC, maring0019 commented
> 

A qué cambios te refieres?

2023-01-17 16:11 UTC, negro89 commented
@maring0019 al comentario que te dejó cele, que respondiste _Se soluciona. Pero modifica el mockup pedido para esta tarea._ .. Si ya los resolviste respondelo comentando que fué asi, para que el resto de los revisores puedan estar al tanto.

2023-01-18 14:35 UTC, AgosLizzi requested changes
Mari, vi en el pr la etiqueta de **"changes done"**, pero al revisar nuevamente no me aparecen los cambios. Puede ser que no se hayan realizado?
![image](https://user-images.githubusercontent.com/72876985/213199104-1a011aba-6af8-429b-af4e-c5338affc474.png)

2023-01-20 18:50 UTC, negro89 commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/nota-agenda.html
> +        <plex-item>
Mari, te recomiendo iterar acá para que, como dice cele, cada elemento del listado sea una agenda (Entiendo que el mockup no muestra el caso de agregar una nota teniendo varias agendas seleccionadas).

Te dejo un videito de como se comporta segun el tamaño de pantalla que se esté usando.
Video: https://watch.screencastify.com/v/bzWm1Zh8minaJMJYl1BP

2023-01-25 15:55 UTC, maring0019 commented
> @maring0019 al comentario que te dejó cele, que respondiste _Se soluciona. Pero modifica el mockup pedido para esta tarea._ .. Si ya los resolviste respondelo comentando que fué asi, para que el resto de los revisores puedan estar al tanto.

Ah, si. Al principio lo había hecho así. Pero no era lo que pedía y lo borré. Pero  ahora ya están realizados esos cambios. No había respondido pero si había puesto la etiqueta change done.

2023-01-25 15:56 UTC, maring0019 commented
> Mari, vi en el pr la etiqueta de **"changes done"**, pero al revisar nuevamente no me aparecen los cambios. Puede ser que no se hayan realizado? ![image](https://user-images.githubusercontent.com/72876985/213199104-1a011aba-6af8-429b-af4e-c5338affc474.png)

Si están subido esos cambios. Por eso había puesto la etiqueta change done.

2023-01-25 15:57 UTC, maring0019 commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/nota-agenda.html
> +        <plex-item>
Si, ya fueron realizados esos cambios. Gracias!

2023-01-26 12:36 UTC, maring0019 commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/nota-agenda.html
> +            <ng-container *ngFor="let agenda of agendasSeleccionadas; let i = index">
Cambios subidos.

2023-01-26 12:37 UTC, maring0019 commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/nota-agenda.html
> +        <plex-item>
Cambios subidos.

2023-01-26 12:37 UTC, maring0019 commented
> > @maring0019 al comentario que te dejó cele, que respondiste _Se soluciona. Pero modifica el mockup pedido para esta tarea._ .. Si ya los resolviste respondelo comentando que fué asi, para que el resto de los revisores puedan estar al tanto.
> 
> Creí que los cambios se habían subido pero no. Cambio la etiqueta a changes requested.

Cambios subidos.

2023-01-26 15:35 UTC, AgosLizzi requested changes
Ahi pude ver los cambios... quedaron bien! solo un detalle, la primera vez que te había comentado el pr, te hice una observación sobre el tamaño del icono del botón check, ahi no veo los cambios. Te transcribo lo que te habia comentado ...
![image](https://user-images.githubusercontent.com/72876985/214878623-6b3cb034-2672-4633-8012-4f9db93b722a.png)
![image (2)](https://user-images.githubusercontent.com/72876985/214878733-a0747773-1fc1-47fb-a79f-d452f12f3bce.png)

"Y como un detalle mínimo, el icono del check esta un poco más grande que el de cerrar
Te dejo como ejemplo dos iconos que están con el mismo tamaño
![image](https://user-images.githubusercontent.com/72876985/214879027-df12e91d-7276-4c80-bd80-f198db777d64.png)

2023-02-01 16:17 UTC, maring0019 commented
> Ahi pude ver los cambios... quedaron bien! solo un detalle, la primera vez que te había comentado el pr, te hice una observación sobre el tamaño del icono del botón check, ahi no veo los cambios. Te transcribo lo que te habia comentado ... ![image](https://user-images.githubusercontent.com/72876985/214878623-6b3cb034-2672-4633-8012-4f9db93b722a.png) ![image (2)](https://user-images.githubusercontent.com/72876985/214878733-a0747773-1fc1-47fb-a79f-d452f12f3bce.png)
> 
> "Y como un detalle mínimo, el icono del check esta un poco más grande que el de cerrar Te dejo como ejemplo dos iconos que están con el mismo tamaño ![image](https://user-images.githubusercontent.com/72876985/214879027-df12e91d-7276-4c80-bd80-f198db777d64.png)

Supuestamente si había hecho esos cambios. Pero lo voy a revisar de nuevo.

2023-02-01 18:13 UTC, maring0019 commented
> 



> > Ahi pude ver los cambios... quedaron bien! solo un detalle, la primera vez que te había comentado el pr, te hice una observación sobre el tamaño del icono del botón check, ahi no veo los cambios. Te transcribo lo que te habia comentado ... ![image](https://user-images.githubusercontent.com/72876985/214878623-6b3cb034-2672-4633-8012-4f9db93b722a.png) ![image (2)](https://user-images.githubusercontent.com/72876985/214878733-a0747773-1fc1-47fb-a79f-d452f12f3bce.png)
> > "Y como un detalle mínimo, el icono del check esta un poco más grande que el de cerrar Te dejo como ejemplo dos iconos que están con el mismo tamaño ![image](https://user-images.githubusercontent.com/72876985/214879027-df12e91d-7276-4c80-bd80-f198db777d64.png)
> 
> Supuestamente si había hecho esos cambios. Pero lo voy a revisar de nuevo.

Ya revisé y si están los cambios. En el código ambos ícono aparecen como size="sm". O no sé si será que te da la sensación de que son diferentes.

2023-02-07 13:49 UTC, maring0019 commented
> > 
> 
> > > Ahi pude ver los cambios... quedaron bien! solo un detalle, la primera vez que te había comentado el pr, te hice una observación sobre el tamaño del icono del botón check, ahi no veo los cambios. Te transcribo lo que te habia comentado ... ![image](https://user-images.githubusercontent.com/72876985/214878623-6b3cb034-2672-4633-8012-4f9db93b722a.png) ![image (2)](https://user-images.githubusercontent.com/72876985/214878733-a0747773-1fc1-47fb-a79f-d452f12f3bce.png)
> > > "Y como un detalle mínimo, el icono del check esta un poco más grande que el de cerrar Te dejo como ejemplo dos iconos que están con el mismo tamaño ![image](https://user-images.githubusercontent.com/72876985/214879027-df12e91d-7276-4c80-bd80-f198db777d64.png)
> > 
> > 
> > Supuestamente si había hecho esos cambios. Pero lo voy a revisar de nuevo.
> 
> Ya revisé y si están los cambios. En el código ambos ícono aparecen como size="sm". O no sé si será que te da la sensación de que son diferentes.

Problema solucionado. Cambios subidos.

2023-02-07 17:46 UTC, AgosLizzi approved these changes

2023-02-08 13:55 UTC, negro89 approved these changes
Excelente.
Algo de codigo en desuso, agregué un commit donde se borra.

2023-02-08 14:00 UTC, merged