MISC - Aplicar mockups en Novedades
andes/app pull request #2796
Opened 2022-12-29 15:45 UTC by ma7payne

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/MISC-262

### Funcionalidad desarrollada 

1. Implementación de nuevas vistas para el módulo de Novedades, basado en mockups de diseño.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2023-01-04 17:53 UTC, MarianoCampetella commented
Apenas entro al modulo de novedades me sale el siguiente error en la consola. Este mismo error esta relacionado con el select que no me devuelve ningún módulo para seleccionar. 

![Error1](https://user-images.githubusercontent.com/65697028/210618700-1852eb08-0e23-4e80-88e8-3bb0bc8f0968.png)

2023-01-04 18:04 UTC, MarianoCampetella commented
También veo muchas variables publicas que fueron declaradas como undefined o null. Esto no es necesario ya que dichas variables por defecto se crean undefined hasta que en algún momento se le cargue algún valor.

2023-01-05 11:03 UTC, AgosLizzi requested changes
Mati, noto lo mismo que campe. Apenas abro el módulo me saltan varios errores. 
Cuando voy a seleccionar algún módulo, no me hace la busqueda, es como si no tuviera accción el campo... Por otro lado el label del calendario "No hay resultados.." lo veo bien, solo agregaría el tilde al **más**.
Te dejo captura de lo que nombre anteriormente:
![2023-01-05](https://user-images.githubusercontent.com/72876985/210765481-896cd89f-be52-4cb8-bbdc-059e7fb96677.png)
![image](https://user-images.githubusercontent.com/72876985/210765500-9fed429f-fe59-47dc-b7dc-b21a795cf611.png)

2023-01-19 18:42 UTC, ma7payne commented
Buenas, ha sido reemplazado el calendar del sidebar de novedades por un selector datetime. Esta tarea se detalla en  https://proyectos.andes.gob.ar/browse/MISC-265 del nuevo sprint y fue sumada en la descripción del PR.
Con respecto a los errores que ven en consola, se trata de un tema con cache de los módulos. Par evitar esto deben borrar "modulos-v1" en Session Storage del navegador.

Quedo atento por más revisiones.

2023-01-26 15:55 UTC, MarianoCampetella commented
Dejo algunas observaciones que se pueden corregir o implementar en una tarea a futuro para que no se extienda mas:
1- Apenas entro al modulo veo que no esta cargada ninguna fecha lo cual me trae todas las solicitudes que existen y sin ningún orden (chequear si eso esta bien)
![image](https://user-images.githubusercontent.com/65697028/214881396-45e8231c-bea4-4401-9c76-93c09be2733c.png)

2- Cuando ingreso una fecha donde existen varias novedades el scroll desaparece
![image](https://user-images.githubusercontent.com/65697028/214881785-56c4178f-aac7-4529-9c7b-b8e7b0e5f07d.png)

3- Cuando selecciono toda la fecha y la borro queda la leyenda "Invalidate Date" lo cual si quiero ingresar una fecha ocurre lo siguiente:
![image](https://user-images.githubusercontent.com/65697028/214882049-5852d962-c457-4586-a6ee-fed58a263749.png)

4- Al dirigirme a una fecha antigua donde existen múltiples novedades y selecciono una para ver el detalle, cuando selecciono el botón volver me dirige a la vista principal del modulo de novedades donde se visualizan todas, en ves de dirigirme a la fecha donde antes estaba. 

Chequear cuales de las correcciones anteriores se pueden aplicar a este PR, o de caso contrario, armar una nueva tarea solicitando los nuevos cambios!

2023-01-27 11:50 UTC, AgosLizzi requested changes
Veo lo mismo que campe con respecto a las fechas. Y por otro lado, me parece un poco raro que en la pantalla de inicio los cards estén en un tamaño, pero cuando me voy a un módulo en particular, cambian de tamaño a más chico. Te dejo video e imagen
https://www.loom.com/share/c2c2ed8032204fb881ac10e337599b8d
![2023-01-27](https://user-images.githubusercontent.com/72876985/215079696-b76cc0bc-df2e-4bbb-a9be-5a7ff4a6ead7.png)
![2023-01-27 (1)](https://user-images.githubusercontent.com/72876985/215079716-497a6dd9-8fac-440c-b406-331f4ac8e61d.png)
![2023-01-27 (2)](https://user-images.githubusercontent.com/72876985/215079719-10846915-af26-4ba4-9156-4242f0b17e3a.png)

2023-02-08 14:36 UTC, negro89 commented
@ma7payne En que estado esta este pr?
@MarianoCampetella que faltaria consensuar? 
Asi vamos destrabando ...

2023-02-13 14:54 UTC, ma7payne commented
@AgosLizzi lo que comentabas del cambio de tamaño en los cards tiene que ver con el uso de slides y por otro lado el encolumnado de plex, todo hace variar los tamaños por lo tanto es difícil de mejorar. Luego el tema de las fechas, podría solucionarse en una próxima tarea aprovechando que hay que agregar también la palabra significativa que se incorporó recientemente.

2023-02-15 17:47 UTC, ma7payne commented
@AgosLizzi Dejo unos cambios relacionados al tamaño de los cards y lo charlado respecto del comportamiento de plex-datetime.
Por otro lado, @MarianoCampetella  fixeo el error de "invalid date" en plex-datetime.

Quedo atento a los comentarios

2023-02-15 17:58 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [8417](http://condorpiedra.andes.gob.ar:85/8417/mochawesome.html)
CYPRESS RUN: [7594](https://dashboard.cypress.io/projects/xr7gft/runs/7594/specs)
TEST START: 2023-02-15T17:58:22.111Z
TOTAL: 406
SUCCESS: 399
FAIL: 5
SKIPPED: 2

2023-03-06 13:43 UTC, AgosLizzi approved these changes

2023-03-06 16:28 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8538](http://condorpiedra.andes.gob.ar:85/8538/mochawesome.html)
CYPRESS RUN: [7717](https://dashboard.cypress.io/projects/xr7gft/runs/7717/specs)
TEST START: 2023-03-06T16:28:10.780Z
TOTAL: 406
SUCCESS: 402
FAIL: 2
SKIPPED: 2

2023-04-26 17:17 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8771](http://condorpiedra.andes.gob.ar:85/8771/mochawesome.html)
CYPRESS RUN: [7942](https://dashboard.cypress.io/projects/xr7gft/runs/7942/specs)
TEST START: 2023-04-26T17:16:52.027Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-04-26 18:15 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8773](http://condorpiedra.andes.gob.ar:85/8773/mochawesome.html)
CYPRESS RUN: [7944](https://dashboard.cypress.io/projects/xr7gft/runs/7944/specs)
TEST START: 2023-04-26T17:54:15.447Z
TOTAL: 310
SUCCESS: 294
FAIL: 14
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-04-27 12:02 UTC, merged