Huds - Filtrar trastornos activos en paciente
andes/app pull request #2799
Opened 2023-01-04 13:53 UTC by ma7payne

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/HUDS-64

### Funcionalidad desarrollada 

1. Al ingresar ala HUDS de un paciente, es posible filtrar los trastornos por aquellos que se encuentran activos (por defecto) o todos los restantes.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2023-01-12 12:21 UTC, negro89 requested changes
No pude filtrar los conceptos, dejo videito mas abajo.
Por otro lado me parece que el slide debería mantener el mismo label ('Activos' en este caso) para no generar confusion. Ya que lo que le comunica al usuario es qué opción estamos (des)activando.
chrome-extension://mmeijimgabbpbgpdklnllpncmdofkcpn/app.html#/files/d77391f9-60b1-4669-yf9e-35587c277adc

2023-01-16 16:41 UTC, ma7payne commented
@negro89 Lauti no veo el error replicado en el filtro, podes ver por consola si tira alguno?

2023-01-17 14:20 UTC, negro89 approved these changes

2023-01-17 14:48 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8259](http://condorpiedra.andes.gob.ar:85/8259/mochawesome.html)
CYPRESS RUN: [7440](https://dashboard.cypress.io/projects/xr7gft/runs/7440/specs)
TEST START: 2023-01-17T14:47:49.307Z
TOTAL: 406
SUCCESS: 396
FAIL: 8
SKIPPED: 2

2023-01-17 18:21 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8261](http://condorpiedra.andes.gob.ar:85/8261/mochawesome.html)
CYPRESS RUN: [7442](https://dashboard.cypress.io/projects/xr7gft/runs/7442/specs)
TEST START: 2023-01-17T18:21:32.313Z
TOTAL: 406
SUCCESS: 394
FAIL: 10
SKIPPED: 2

2023-01-17 19:23 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8264](http://condorpiedra.andes.gob.ar:85/8264/mochawesome.html)
CYPRESS RUN: [7445](https://dashboard.cypress.io/projects/xr7gft/runs/7445/specs)
TEST START: 2023-01-17T19:21:56.498Z
TOTAL: 364
SUCCESS: 347
FAIL: 15
SKIPPED: 2

2023-01-18 13:22 UTC, AgosLizzi approved these changes
Mati, super la implementación. Solo como un comentario y para tener en cuenta. Me dio la sensación que el componente esta agregado sin ningún contexto, es decir, algún plex title que acompañe la acción o guié a la persona usuaria. Y tal vez de esta manera hubiera quedado posicionado sobre la derecha del listado.

2023-01-18 16:09 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8271](http://condorpiedra.andes.gob.ar:85/8271/mochawesome.html)
CYPRESS RUN: [7452](https://dashboard.cypress.io/projects/xr7gft/runs/7452/specs)
TEST START: 2023-01-18T15:59:04.147Z
TOTAL: 359
SUCCESS: 333
FAIL: 24
SKIPPED: 2

2023-01-18 18:06 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8273](http://condorpiedra.andes.gob.ar:85/8273/mochawesome.html)
CYPRESS RUN: [7454](https://dashboard.cypress.io/projects/xr7gft/runs/7454/specs)
TEST START: 2023-01-18T18:06:01.183Z
TOTAL: 406
SUCCESS: 394
FAIL: 10
SKIPPED: 2

2023-01-18 18:31 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8275](http://condorpiedra.andes.gob.ar:85/8275/mochawesome.html)
CYPRESS RUN: [7456](https://dashboard.cypress.io/projects/xr7gft/runs/7456/specs)
TEST START: 2023-01-18T18:31:16.055Z
TOTAL: 406
SUCCESS: 395
FAIL: 9
SKIPPED: 2

2023-01-18 18:54 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8277](http://condorpiedra.andes.gob.ar:85/8277/mochawesome.html)
CYPRESS RUN: [7458](https://dashboard.cypress.io/projects/xr7gft/runs/7458/specs)
TEST START: 2023-01-18T18:53:10.434Z
TOTAL: 389
SUCCESS: 370
FAIL: 18
SKIPPED: 1

2023-02-06 17:15 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8361](http://condorpiedra.andes.gob.ar:85/8361/mochawesome.html)
CYPRESS RUN: [7539](https://dashboard.cypress.io/projects/xr7gft/runs/7539/specs)
TEST START: 2023-02-06T17:05:25.322Z
TOTAL: 406
SUCCESS: 390
FAIL: 14
SKIPPED: 2

2023-02-06 17:59 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8362](http://condorpiedra.andes.gob.ar:85/8362/mochawesome.html)
CYPRESS RUN: [7540](https://dashboard.cypress.io/projects/xr7gft/runs/7540/specs)
TEST START: 2023-02-06T17:59:32.478Z
TOTAL: 356
SUCCESS: 353
FAIL: 1
SKIPPED: 2

2023-02-06 18:31 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8364](http://condorpiedra.andes.gob.ar:85/8364/mochawesome.html)
CYPRESS RUN: [7542](https://dashboard.cypress.io/projects/xr7gft/runs/7542/specs)
TEST START: 2023-02-06T18:21:31.839Z
TOTAL: 406
SUCCESS: 390
FAIL: 14
SKIPPED: 2

2023-02-06 18:58 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8365](http://condorpiedra.andes.gob.ar:85/8365/mochawesome.html)
CYPRESS RUN: [7543](https://dashboard.cypress.io/projects/xr7gft/runs/7543/specs)
TEST START: 2023-02-06T18:58:42.867Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-02-08 13:14 UTC, merged