CITAS - Error en agenda dinámica
andes/app pull request #2802
Opened 2023-01-09 14:51 UTC by maring0019

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-196

### Funcionalidad desarrollada 

1. Corrección de mensaje de error.
2. Corrección de error de función inexistente. Se agregó esa función.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2023-01-18 12:45 UTC, maring0019 commented on src/app/components/turnos/gestor-agendas/operaciones-turnos/liberar-turno.component.ts
> +                    this.plex.info('warning', 'El turno ya tiene una prestación asociada.', 'Prestación existente');
El mensaje fue cambiado después que publicaron la tarea. Lo dejé comentado en los comentarios de la misma tarea en Jira.

2023-01-18 15:15 UTC, negro89 commented on src/app/components/turnos/gestor-agendas/operaciones-turnos/liberar-turno.component.ts
> +                    this.plex.info('warning', 'El turno ya tiene una prestación asociada.', 'Prestación existente');
Buenisimo, no lo había leido. Mala mia ✋🏼

2023-01-18 15:22 UTC, AgosLizzi requested changes
Mari, un par de cositas que vi.

1.  La primera, el tooltip suspender turno esta cortado. Si podes de yapa realizar ese cambio, genial. 
![2023-01-18 (10)](https://user-images.githubusercontent.com/72876985/213209343-e099334f-46bf-48ec-ac58-f256fd831fd9.png)
2. Cuando doy a liberar un turno, me aparece un error en la consola, lo podras revisar? te lo muestro por las dudas. 
![2023-01-18 (11)](https://user-images.githubusercontent.com/72876985/213210015-4e380c6f-0138-46b8-ac7c-b5b9b30cc316.png)
3. El writing del modal, vi lo que cele te había sugerido, asi que lo dejo como otra sugerencia. Desde el writing se repiten palabras, "prestación" y "prestación existente/asociada" se entiende como que tanto desde el título como en el cuerpo de texto se dice lo mismo. Yo tal vez de títilo pondría algo más neutro y desde el cuerpo explico el problema para no ser repetitivos.

2023-02-07 14:22 UTC, maring0019 commented
> Mari, un par de cositas que vi.
> 
> 1. La primera, el tooltip suspender turno esta cortado. Si podes de yapa realizar ese cambio, genial.
>    ![2023-01-18 (10)](https://user-images.githubusercontent.com/72876985/213209343-e099334f-46bf-48ec-ac58-f256fd831fd9.png)
> 2. Cuando doy a liberar un turno, me aparece un error en la consola, lo podras revisar? te lo muestro por las dudas.
>    ![2023-01-18 (11)](https://user-images.githubusercontent.com/72876985/213210015-4e380c6f-0138-46b8-ac7c-b5b9b30cc316.png)
> 3. El writing del modal, vi lo que cele te había sugerido, asi que lo dejo como otra sugerencia. Desde el writing se repiten palabras, "prestación" y "prestación existente/asociada" se entiende como que tanto desde el título como en el cuerpo de texto se dice lo mismo. Yo tal vez de título pondría algo más neutro y desde el cuerpo explico el problema para no ser repetitivos.

Cambios realizados.

2023-02-07 18:37 UTC, AgosLizzi approved these changes

2023-02-09 18:53 UTC, negro89 approved these changes

2023-02-10 13:18 UTC, merged