MPI - Visualización de formulario para pacientes con DNI argentino
andes/app pull request #2803
Opened 2023-01-09 16:27 UTC by ma7payne

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/MPI-392
### Funcionalidad desarrollada 

1. Al ingresar un paciente en la búsqueda de MPI, si el mismo es extranjero pero posee DNI argentino (validado o sin validar), se visualiza el formulario correspondiente para pacientes argentinos.
2. Se mantiene la visualización del formulario exclusivo para pacientes extranjeros solo si tienen numero de identificación pero no tienen DNI.
3. Se mantiene la visualización del formulario correspondiente para el resto de los casos.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [x] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2023-01-10 15:29 UTC, MCele requested changes
Actualmente si tengo un paciente con DNI Artigentino e identificacion extranjera deberpia redireccionarme al formulario de ".../mpi/paciente", pero me sigue redireccionando al de paciente extranjero.
![image](https://user-images.githubusercontent.com/19591224/211591976-c84b637f-2934-45dd-80e3-3237da2f1e1a.png)
La variable tipoPaciente que fue renombrada ya viene con información desde la invocacion de componentes anteriores, creo que es mejor revisar esa interacción.
Ver el momento en el que se selecciona la ruta del formulario a cargar, ya que para paciente extranjero es otra y solo debería utilizarse cuando no se tiene numero de documento argentino.

2023-01-17 12:49 UTC, ma7payne commented
Se cambia la condición de la vista para mostrar form y se asigna tipoFormulario en paciente-buscar.component para que afecte tambien en las urls. Quedo atento a la revisión.

2023-01-17 18:51 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8262](http://condorpiedra.andes.gob.ar:85/8262/mochawesome.html)
CYPRESS RUN: [7443](https://dashboard.cypress.io/projects/xr7gft/runs/7443/specs)
TEST START: 2023-01-17T18:40:55.808Z
TOTAL: 406
SUCCESS: 389
FAIL: 15
SKIPPED: 2

2023-01-17 19:11 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8263](http://condorpiedra.andes.gob.ar:85/8263/mochawesome.html)
CYPRESS RUN: [7444](https://dashboard.cypress.io/projects/xr7gft/runs/7444/specs)
TEST START: 2023-01-17T19:02:02.570Z
TOTAL: 406
SUCCESS: 389
FAIL: 15
SKIPPED: 2

2023-01-18 18:11 UTC, MCele requested changes

2023-01-18 18:11 UTC, MCele commented on src/app/core/mpi/components/busqueda-mpi.component.ts
> +        return paciente.numeroIdentificacion && !paciente.documento;
el cambio me parece perfecto que sea acá, pero revisar condicion que se quiere modificar para no quitar aquellos casos registrados desde la pantalla de paciente extranjero (sin documento) pero que sí tenga registrado un tipo de identificación extranjera (DNI o pasaporte)

2023-01-18 18:12 UTC, MCele commented
queda pendiente la revisión del linteo utilizado

2023-01-19 18:06 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [8285](http://condorpiedra.andes.gob.ar:85/8285/mochawesome.html)
CYPRESS RUN: [7466](https://dashboard.cypress.io/projects/xr7gft/runs/7466/specs)
TEST START: 2023-01-19T18:06:42.668Z
TOTAL: 406
SUCCESS: 396
FAIL: 8
SKIPPED: 2

2023-01-19 18:44 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [8286](http://condorpiedra.andes.gob.ar:85/8286/mochawesome.html)
CYPRESS RUN: [7467](https://dashboard.cypress.io/projects/xr7gft/runs/7467/specs)
TEST START: 2023-01-19T18:44:22.975Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-01-19 19:20 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [8288](http://condorpiedra.andes.gob.ar:85/8288/mochawesome.html)
CYPRESS RUN: [7469](https://dashboard.cypress.io/projects/xr7gft/runs/7469/specs)
TEST START: 2023-01-19T19:20:27.923Z
TOTAL: 406
SUCCESS: 402
FAIL: 2
SKIPPED: 2

2023-01-20 14:33 UTC, merged