Botón iniciar prestación
andes/app pull request #2808
Opened 2023-01-18 14:48 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-514

### Funcionalidad desarrollada 

1. Se agregaron restricciones para que los botones continuar y anular prestación solamente lo puedan hacer los usuarios con rol de profesional. Cambien se corrigieron algunos títulos de los labels.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2023-01-18 15:10 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8269](http://condorpiedra.andes.gob.ar:85/8269/mochawesome.html)
CYPRESS RUN: [7450](https://dashboard.cypress.io/projects/xr7gft/runs/7450/specs)
TEST START: 2023-01-18T15:10:02.806Z
TOTAL: 401
SUCCESS: 396
FAIL: 3
SKIPPED: 2

2023-01-18 15:51 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8270](http://condorpiedra.andes.gob.ar:85/8270/mochawesome.html)
CYPRESS RUN: [7451](https://dashboard.cypress.io/projects/xr7gft/runs/7451/specs)
TEST START: 2023-01-18T15:49:50.212Z
TOTAL: 338
SUCCESS: 310
FAIL: 26
SKIPPED: 2

2023-01-19 12:32 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8282](http://condorpiedra.andes.gob.ar:85/8282/mochawesome.html)
CYPRESS RUN: [7463](https://dashboard.cypress.io/projects/xr7gft/runs/7463/specs)
TEST START: 2023-01-19T12:32:32.542Z
TOTAL: 406
SUCCESS: 401
FAIL: 3
SKIPPED: 2

2023-01-24 13:52 UTC, ma7payne commented
Campe, parece estar todo ok con la condiciones para "Continuar", "Anular" y "Romper validación". 
Sin embargo, al crear un usuario no profesional puedo iniciar la prestación de todos modos. Allí no veo condición para evitar que se visualice o se pueda dar clic en el botón "Iniciar Prestación".

Dejo un video con el ejemplo: https://www.loom.com/share/2e7cc77ac26748d7b6d14057a520432d

Notar que en el video el usuario no puede entrar a RUP por no ser profesional. 
Considerar que si un usuario no es profesional directamente no debería poder dar clic en "Nuevo Registro".

Saludos!

2023-01-24 18:20 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8324](http://condorpiedra.andes.gob.ar:85/8324/mochawesome.html)
CYPRESS RUN: [7503](https://dashboard.cypress.io/projects/xr7gft/runs/7503/specs)
TEST START: 2023-01-24T18:09:39.485Z
TOTAL: 406
SUCCESS: 388
FAIL: 16
SKIPPED: 2

2023-01-24 19:14 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8328](http://condorpiedra.andes.gob.ar:85/8328/mochawesome.html)
CYPRESS RUN: [7507](https://dashboard.cypress.io/projects/xr7gft/runs/7507/specs)
TEST START: 2023-01-24T19:13:48.818Z
TOTAL: 338
SUCCESS: 331
FAIL: 5
SKIPPED: 2

2023-01-26 11:50 UTC, ma7payne approved these changes
Funciona muy bien! Encuentro un pequeño detalle sintáctico en el nombre "onNuevoRegistrio".

2023-01-26 13:18 UTC, MarianoCampetella commented
> Funciona muy bien! Encuentro un pequeño detalle sintáctico en el nombre "onNuevoRegistrio".

Si se considera necesario se puede modificar!! 
Se esperan respuestas!

2023-01-26 13:35 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8334](http://condorpiedra.andes.gob.ar:85/8334/mochawesome.html)
CYPRESS RUN: [7513](https://dashboard.cypress.io/projects/xr7gft/runs/7513/specs)
TEST START: 2023-01-26T13:33:45.187Z
TOTAL: 359
SUCCESS: 347
FAIL: 10
SKIPPED: 2

2023-01-26 14:18 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8335](http://condorpiedra.andes.gob.ar:85/8335/mochawesome.html)
CYPRESS RUN: [7514](https://dashboard.cypress.io/projects/xr7gft/runs/7514/specs)
TEST START: 2023-01-26T14:05:18.604Z
TOTAL: 406
SUCCESS: 385
FAIL: 19
SKIPPED: 2

2023-02-27 15:31 UTC, negro89 requested changes

2023-02-27 15:31 UTC, negro89 commented on src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
> +    generarRegistro(acciones, permisos) {
Campe, reconsideraría dos cosas en esta funcion:
1. Se implementa en mas de un componente. Por lo tanto en lugar de repetir codigo la pondría en el servicio correspondiente.
2. Ya que no se encarga de generar registros sino que realiza un control para decidir si un usuario debería hacerlo, reemplazaría el nombre por uno mas apropiado.

2023-02-28 14:50 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
> +    generarRegistro(acciones, permisos) {
Corregido!! la verificacion del boton NUEVO REGISTRO se hace desde el servicio de mapaCamaService y se agrego un nombre mas significativo.

2023-03-07 15:22 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8549](http://condorpiedra.andes.gob.ar:85/8549/mochawesome.html)
CYPRESS RUN: [7728](https://dashboard.cypress.io/projects/xr7gft/runs/7728/specs)
TEST START: 2023-03-07T15:22:26.843Z
TOTAL: 406
SUCCESS: 394
FAIL: 10
SKIPPED: 2

2023-03-07 15:45 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8550](http://condorpiedra.andes.gob.ar:85/8550/mochawesome.html)
CYPRESS RUN: [7729](https://dashboard.cypress.io/projects/xr7gft/runs/7729/specs)
TEST START: 2023-03-07T15:45:06.456Z
TOTAL: 406
SUCCESS: 402
FAIL: 2
SKIPPED: 2

2023-03-07 16:17 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8552](http://condorpiedra.andes.gob.ar:85/8552/mochawesome.html)
CYPRESS RUN: [7731](https://dashboard.cypress.io/projects/xr7gft/runs/7731/specs)
TEST START: 2023-03-07T16:16:58.945Z
TOTAL: 388
SUCCESS: 383
FAIL: 3
SKIPPED: 2

2023-05-16 18:42 UTC, negro89 approved these changes
excelente ese rxjs

2023-05-16 19:05 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8905](http://condorpiedra.andes.gob.ar:85/8905/mochawesome.html)
CYPRESS RUN: [8070](https://dashboard.cypress.io/projects/xr7gft/runs/8070/specs)
TEST START: 2023-05-16T19:05:06.388Z
TOTAL: 406
SUCCESS: 402
FAIL: 2
SKIPPED: 2

2023-05-16 19:17 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8906](http://condorpiedra.andes.gob.ar:85/8906/mochawesome.html)
CYPRESS RUN: [8071](https://dashboard.cypress.io/projects/xr7gft/runs/8071/specs)
TEST START: 2023-05-16T19:15:52.875Z
TOTAL: 370
SUCCESS: 358
FAIL: 10
SKIPPED: 2

2023-05-17 12:04 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8909](http://condorpiedra.andes.gob.ar:85/8909/mochawesome.html)
CYPRESS RUN: [8074](https://dashboard.cypress.io/projects/xr7gft/runs/8074/specs)
TEST START: 2023-05-17T12:00:22.478Z
TOTAL: 358
SUCCESS: 348
FAIL: 8
SKIPPED: 2

2023-05-18 16:51 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8920](http://condorpiedra.andes.gob.ar:85/8920/mochawesome.html)
CYPRESS RUN: [8084](https://dashboard.cypress.io/projects/xr7gft/runs/8084/specs)
TEST START: 2023-05-18T16:51:08.784Z
TOTAL: 406
SUCCESS: 402
FAIL: 2
SKIPPED: 2

2023-05-18 17:08 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8921](http://condorpiedra.andes.gob.ar:85/8921/mochawesome.html)
CYPRESS RUN: [8085](https://dashboard.cypress.io/projects/xr7gft/runs/8085/specs)
TEST START: 2023-05-18T17:08:04.383Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-05-19 13:18 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8924](http://condorpiedra.andes.gob.ar:85/8924/mochawesome.html)
CYPRESS RUN: [8088](https://dashboard.cypress.io/projects/xr7gft/runs/8088/specs)
TEST START: 2023-05-19T13:17:52.051Z
TOTAL: 406
SUCCESS: 400
FAIL: 4
SKIPPED: 2

2023-05-19 16:10 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8925](http://condorpiedra.andes.gob.ar:85/8925/mochawesome.html)
CYPRESS RUN: [8089](https://dashboard.cypress.io/projects/xr7gft/runs/8089/specs)
TEST START: 2023-05-19T16:10:18.783Z
TOTAL: 406
SUCCESS: 402
FAIL: 2
SKIPPED: 2

2023-05-19 16:14 UTC, negro89 commented
@MarianoCampetella revisar test de registros. Es el unico que viene fallando en todas las corridas.
![image](https://github.com/andes/app/assets/37875706/b619e110-9e81-4190-8f63-0fd512ad3fde)

2023-05-19 16:21 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8926](http://condorpiedra.andes.gob.ar:85/8926/mochawesome.html)
CYPRESS RUN: [8090](https://dashboard.cypress.io/projects/xr7gft/runs/8090/specs)
TEST START: 2023-05-19T16:21:45.546Z
TOTAL: 406
SUCCESS: 402
FAIL: 2
SKIPPED: 2

2023-06-01 19:37 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8980](http://condorpiedra.andes.gob.ar:85/8980/mochawesome.html)
CYPRESS RUN: [8143](https://dashboard.cypress.io/projects/xr7gft/runs/8143/specs)
TEST START: 2023-06-01T19:36:11.840Z
TOTAL: 95
SUCCESS: 0
FAIL: 95
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-06-06 15:38 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [9008](http://condorpiedra.andes.gob.ar:85/9008/mochawesome.html)
CYPRESS RUN: [8168](https://dashboard.cypress.io/projects/xr7gft/runs/8168/specs)
TEST START: 2023-06-06T15:38:26.191Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-06-08 13:04 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [9033](http://condorpiedra.andes.gob.ar:85/9033/mochawesome.html)
CYPRESS RUN: [8191](https://dashboard.cypress.io/projects/xr7gft/runs/8191/specs)
TEST START: 2023-06-08T13:04:32.071Z
TOTAL: 403
SUCCESS: 397
FAIL: 4
SKIPPED: 2

2023-06-08 13:30 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [9034](http://condorpiedra.andes.gob.ar:85/9034/mochawesome.html)
CYPRESS RUN: [8192](https://dashboard.cypress.io/projects/xr7gft/runs/8192/specs)
TEST START: 2023-06-08T13:30:21.601Z
TOTAL: 403
SUCCESS: 397
FAIL: 4
SKIPPED: 2

2023-06-08 14:41 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [9037](http://condorpiedra.andes.gob.ar:85/9037/mochawesome.html)
CYPRESS RUN: [8195](https://dashboard.cypress.io/projects/xr7gft/runs/8195/specs)
TEST START: 2023-06-08T14:41:07.440Z
TOTAL: 403
SUCCESS: 397
FAIL: 4
SKIPPED: 2

2023-06-12 12:00 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [9061](http://condorpiedra.andes.gob.ar:85/9061/mochawesome.html)
CYPRESS RUN: [8219](https://dashboard.cypress.io/projects/xr7gft/runs/8219/specs)
TEST START: 2023-06-12T12:00:25.369Z
TOTAL: 403
SUCCESS: 398
FAIL: 3
SKIPPED: 2

2023-06-12 12:29 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [9063](http://condorpiedra.andes.gob.ar:85/9063/mochawesome.html)
CYPRESS RUN: [8221](https://dashboard.cypress.io/projects/xr7gft/runs/8221/specs)
TEST START: 2023-06-12T12:25:13.458Z
TOTAL: 362
SUCCESS: 354
FAIL: 6
SKIPPED: 2

2023-06-12 14:06 UTC, merged