CITAS - Error al suspender turnos de una agenda
andes/app pull request #2811
Opened 2023-01-19 17:09 UTC by maring0019

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-206
### Funcionalidad desarrollada 

1.  Se corrige la función de suspender turnos cuando de selecciona más de un turno.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2023-01-19 17:51 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8284](http://condorpiedra.andes.gob.ar:85/8284/mochawesome.html)
CYPRESS RUN: [7465](https://dashboard.cypress.io/projects/xr7gft/runs/7465/specs)
TEST START: 2023-01-19T17:43:06.481Z
TOTAL: 99
SUCCESS: 0
FAIL: 99
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-01-20 12:13 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8291](http://condorpiedra.andes.gob.ar:85/8291/mochawesome.html)
CYPRESS RUN: [7472](https://dashboard.cypress.io/projects/xr7gft/runs/7472/specs)
TEST START: 2023-01-20T12:13:32.425Z
TOTAL: 406
SUCCESS: 402
FAIL: 2
SKIPPED: 2

2023-01-20 13:05 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8294](http://condorpiedra.andes.gob.ar:85/8294/mochawesome.html)
CYPRESS RUN: [7473](https://dashboard.cypress.io/projects/xr7gft/runs/7473/specs)
TEST START: 2023-01-20T12:54:52.485Z
TOTAL: 406
SUCCESS: 388
FAIL: 16
SKIPPED: 2

2023-01-20 17:33 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8301](http://condorpiedra.andes.gob.ar:85/8301/mochawesome.html)
CYPRESS RUN: [7480](https://dashboard.cypress.io/projects/xr7gft/runs/7480/specs)
TEST START: 2023-01-20T17:32:25.528Z
TOTAL: 365
SUCCESS: 355
FAIL: 8
SKIPPED: 2

2023-01-20 18:06 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8302](http://condorpiedra.andes.gob.ar:85/8302/mochawesome.html)
CYPRESS RUN: [7481](https://dashboard.cypress.io/projects/xr7gft/runs/7481/specs)
TEST START: 2023-01-20T18:05:49.125Z
TOTAL: 369
SUCCESS: 360
FAIL: 7
SKIPPED: 2

2023-01-20 18:36 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8303](http://condorpiedra.andes.gob.ar:85/8303/mochawesome.html)
CYPRESS RUN: [7482](https://dashboard.cypress.io/projects/xr7gft/runs/7482/specs)
TEST START: 2023-01-20T18:36:26.530Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-01-25 17:05 UTC, AgosLizzi approved these changes

2023-01-25 19:20 UTC, MCele commented on src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.component.ts
> +
este cambio no es necesario, además en este caso quitamos la restricción de tipos que nos da el uso de Interfaces.

2023-01-25 19:28 UTC, MCele requested changes

2023-01-25 19:28 UTC, MCele commented on src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.component.ts
> +        this.turnosSeleccionados.forEach(() => {
Este forEach no es necesario, ya que el patch que se hace a la api resuelve la acción (suspenderTurno en este caso) sobre un array de turnos, la clave está en poder establecer el array de "turnos" que se envían por parámetro,

2023-01-25 19:28 UTC, MCele commented on src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.component.ts
> +                err => {
ya que estamos tocando esta parte del código, se puede aprovechar para hacer un poco de limpieza (quitar estas lineas que no realizan ninguna acción).

2023-02-01 16:14 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8347](http://condorpiedra.andes.gob.ar:85/8347/mochawesome.html)
CYPRESS RUN: [7525](https://dashboard.cypress.io/projects/xr7gft/runs/7525/specs)
TEST START: 2023-02-01T16:13:52.072Z
TOTAL: 406
SUCCESS: 395
FAIL: 9
SKIPPED: 2

2023-02-01 16:33 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8348](http://condorpiedra.andes.gob.ar:85/8348/mochawesome.html)
CYPRESS RUN: [7526](https://dashboard.cypress.io/projects/xr7gft/runs/7526/specs)
TEST START: 2023-02-01T16:33:25.232Z
TOTAL: 406
SUCCESS: 401
FAIL: 3
SKIPPED: 2

2023-02-01 17:47 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8350](http://condorpiedra.andes.gob.ar:85/8350/mochawesome.html)
CYPRESS RUN: [7528](https://dashboard.cypress.io/projects/xr7gft/runs/7528/specs)
TEST START: 2023-02-01T17:46:20.218Z
TOTAL: 376
SUCCESS: 357
FAIL: 17
SKIPPED: 2

2023-02-06 13:19 UTC, maring0019 commented on src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.component.ts
> +
> este cambio no es necesario, además en este caso quitamos la restricción de tipos que nos da el uso de Interfaces.

Cambio quitado.

2023-02-06 13:20 UTC, maring0019 commented on src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.component.ts
> +        this.turnosSeleccionados.forEach(() => {
Cambio realizado.

2023-02-06 13:20 UTC, maring0019 commented on src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.component.ts
> +                err => {
Cambio realizado.

2023-02-06 14:05 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8356](http://condorpiedra.andes.gob.ar:85/8356/mochawesome.html)
CYPRESS RUN: [7534](https://dashboard.cypress.io/projects/xr7gft/runs/7534/specs)
TEST START: 2023-02-06T13:43:28.126Z
TOTAL: 381
SUCCESS: 352
FAIL: 27
SKIPPED: 2

2023-02-06 14:18 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8357](http://condorpiedra.andes.gob.ar:85/8357/mochawesome.html)
CYPRESS RUN: [7535](https://dashboard.cypress.io/projects/xr7gft/runs/7535/specs)
TEST START: 2023-02-06T14:18:05.303Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-02-06 16:02 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8360](http://condorpiedra.andes.gob.ar:85/8360/mochawesome.html)
CYPRESS RUN: [7538](https://dashboard.cypress.io/projects/xr7gft/runs/7538/specs)
TEST START: 2023-02-06T16:02:33.132Z
TOTAL: 406
SUCCESS: 395
FAIL: 9
SKIPPED: 2

2023-02-06 18:57 UTC, negro89 commented
Mari, probe la funcionalidad y te grabé un video https://watch.screencastify.com/v/Xkr4niJeawZkG2Eu0pn0
El error en la consola se corrige haciendo que el motivo sea un campo requerido.

2023-02-07 16:35 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8372](http://condorpiedra.andes.gob.ar:85/8372/mochawesome.html)
CYPRESS RUN: [7550](https://dashboard.cypress.io/projects/xr7gft/runs/7550/specs)
TEST START: 2023-02-07T16:35:23.289Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-02-07 16:52 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8374](http://condorpiedra.andes.gob.ar:85/8374/mochawesome.html)
CYPRESS RUN: [7551](https://dashboard.cypress.io/projects/xr7gft/runs/7551/specs)
TEST START: 2023-02-07T16:52:20.471Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-02-07 17:13 UTC, maring0019 commented
Nota: a pesar que el test en Jenkis no resulta positivo. Cuando se lo corre a nivel local, resulta sin errores. Adjunto fotos de los test.

![GESTOR_AGENDA_TEST-2023-02-07 13-50-23](https://user-images.githubusercontent.com/57371507/217315710-f66dc00f-542b-4720-b720-99377ae8eda2.png)
![GESTOR_AGENDAS_LISTADO_TEST -2023-02-07 13-52-09](https://user-images.githubusercontent.com/57371507/217315751-82c6b58d-beba-40d8-9846-cc5b99214b2f.png)
![PLANIFICACION-AGENDAS-TEST -2023-02-07 13-56-57](https://user-images.githubusercontent.com/57371507/217315823-5b18f1ce-4bf7-4c7d-a190-27934953527c.png)

2023-02-13 16:58 UTC, maring0019 commented
> Mari, probe la funcionalidad y te grabé un video https://watch.screencastify.com/v/Xkr4niJeawZkG2Eu0pn0 El error en la consola se corrige haciendo que el motivo sea un campo requerido.

No había visto este comentario. Lo que corregí en esta tarea era suspender turnos pero para _turnos donde no había pacientes_.  No ví lo de turnos del día. Lo corrijo igual?

2023-02-14 16:12 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [8401](http://condorpiedra.andes.gob.ar:85/8401/mochawesome.html)
CYPRESS RUN: [7578](https://dashboard.cypress.io/projects/xr7gft/runs/7578/specs)
TEST START: 2023-02-14T16:12:24.460Z
TOTAL: 406
SUCCESS: 401
FAIL: 3
SKIPPED: 2

2023-02-14 18:06 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8402](http://condorpiedra.andes.gob.ar:85/8402/mochawesome.html)
CYPRESS RUN: [7579](https://dashboard.cypress.io/projects/xr7gft/runs/7579/specs)
TEST START: 2023-02-14T18:05:48.173Z
TOTAL: 406
SUCCESS: 392
FAIL: 12
SKIPPED: 2

2023-02-14 18:19 UTC, negro89 approved these changes

2023-02-15 14:02 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8412](http://condorpiedra.andes.gob.ar:85/8412/mochawesome.html)
CYPRESS RUN: [7589](https://dashboard.cypress.io/projects/xr7gft/runs/7589/specs)
TEST START: 2023-02-15T13:51:52.109Z
TOTAL: 406
SUCCESS: 384
FAIL: 20
SKIPPED: 2

2023-02-15 14:33 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8414](http://condorpiedra.andes.gob.ar:85/8414/mochawesome.html)
CYPRESS RUN: [7591](https://dashboard.cypress.io/projects/xr7gft/runs/7591/specs)
TEST START: 2023-02-15T14:33:36.838Z
TOTAL: 406
SUCCESS: 400
FAIL: 4
SKIPPED: 2

2023-02-15 15:35 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8415](http://condorpiedra.andes.gob.ar:85/8415/mochawesome.html)
CYPRESS RUN: [7592](https://dashboard.cypress.io/projects/xr7gft/runs/7592/specs)
TEST START: 2023-02-15T15:34:52.984Z
TOTAL: 356
SUCCESS: 348
FAIL: 6
SKIPPED: 2

2023-02-22 19:57 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8435](http://condorpiedra.andes.gob.ar:85/8435/mochawesome.html)
CYPRESS RUN: [7610](https://dashboard.cypress.io/projects/xr7gft/runs/7610/specs)
TEST START: 2023-02-22T19:36:13.716Z
TOTAL: 320
SUCCESS: 299
FAIL: 19
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-02-27 14:26 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8454](http://condorpiedra.andes.gob.ar:85/8454/mochawesome.html)
CYPRESS RUN: [7629](https://dashboard.cypress.io/projects/xr7gft/runs/7629/specs)
TEST START: 2023-02-27T14:26:31.488Z
TOTAL: 406
SUCCESS: 393
FAIL: 11
SKIPPED: 2

2023-02-27 15:21 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8457](http://condorpiedra.andes.gob.ar:85/8457/mochawesome.html)
CYPRESS RUN: [7632](https://dashboard.cypress.io/projects/xr7gft/runs/7632/specs)
TEST START: 2023-02-27T15:20:38.701Z
TOTAL: 406
SUCCESS: 399
FAIL: 5
SKIPPED: 2

2023-03-02 15:10 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8501](http://condorpiedra.andes.gob.ar:85/8501/mochawesome.html)
CYPRESS RUN: [7680](https://dashboard.cypress.io/projects/xr7gft/runs/7680/specs)
TEST START: 2023-03-02T15:07:48.700Z
TOTAL: 387
SUCCESS: 376
FAIL: 9
SKIPPED: 2

2023-03-02 15:25 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8502](http://condorpiedra.andes.gob.ar:85/8502/mochawesome.html)
CYPRESS RUN: [7681](https://dashboard.cypress.io/projects/xr7gft/runs/7681/specs)
TEST START: 2023-03-02T15:25:19.757Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-03-02 16:26 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8507](http://condorpiedra.andes.gob.ar:85/8507/mochawesome.html)
CYPRESS RUN: [7686](https://dashboard.cypress.io/projects/xr7gft/runs/7686/specs)
TEST START: 2023-03-02T16:25:34.226Z
TOTAL: 314
SUCCESS: 287
FAIL: 25
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-03-02 16:39 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8508](http://condorpiedra.andes.gob.ar:85/8508/mochawesome.html)
CYPRESS RUN: [7687](https://dashboard.cypress.io/projects/xr7gft/runs/7687/specs)
TEST START: 2023-03-02T16:39:34.464Z
TOTAL: 397
SUCCESS: 393
FAIL: 2
SKIPPED: 2

2023-03-02 17:03 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8509](http://condorpiedra.andes.gob.ar:85/8509/mochawesome.html)
CYPRESS RUN: [7688](https://dashboard.cypress.io/projects/xr7gft/runs/7688/specs)
TEST START: 2023-03-02T17:02:38.485Z
TOTAL: 377
SUCCESS: 366
FAIL: 9
SKIPPED: 2

2023-03-02 17:26 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8510](http://condorpiedra.andes.gob.ar:85/8510/mochawesome.html)
CYPRESS RUN: [7689](https://dashboard.cypress.io/projects/xr7gft/runs/7689/specs)
TEST START: 2023-03-02T17:25:57.976Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-03-02 17:51 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8512](http://condorpiedra.andes.gob.ar:85/8512/mochawesome.html)
CYPRESS RUN: [7691](https://dashboard.cypress.io/projects/xr7gft/runs/7691/specs)
TEST START: 2023-03-02T17:51:16.094Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-03-02 18:29 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8515](http://condorpiedra.andes.gob.ar:85/8515/mochawesome.html)
CYPRESS RUN: [7694](https://dashboard.cypress.io/projects/xr7gft/runs/7694/specs)
TEST START: 2023-03-02T18:28:48.751Z
TOTAL: 406
SUCCESS: 401
FAIL: 3
SKIPPED: 2

2023-03-02 18:54 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8517](http://condorpiedra.andes.gob.ar:85/8517/mochawesome.html)
CYPRESS RUN: [7696](https://dashboard.cypress.io/projects/xr7gft/runs/7696/specs)
TEST START: 2023-03-02T18:54:32.670Z
TOTAL: 337
SUCCESS: 329
FAIL: 6
SKIPPED: 2

2023-03-02 19:19 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8519](http://condorpiedra.andes.gob.ar:85/8519/mochawesome.html)
CYPRESS RUN: [7698](https://dashboard.cypress.io/projects/xr7gft/runs/7698/specs)
TEST START: 2023-03-02T19:19:06.176Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-03-03 13:01 UTC, merged