TOP - Agrega información en vista de prestación y solicitud
andes/app pull request #2813
Opened 2023-01-26 12:52 UTC by ma7payne

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/TOP-149
https://proyectos.andes.gob.ar/browse/TOP-145
### Funcionalidad desarrollada 

1. En la HUDS de un paciente se renombran y agregan datos relacionados a la solicitud según corresponda.
2. Se consideran los mockups creados para la tarea TOP-145 para la nomenclatura y organización de los datos.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2023-01-31 13:25 UTC, AgosLizzi reviewed
Mati, según lo charlado con @MCele se decidio implementar un dropdown para que la persona usuaria tenga la posibilidad de poder ver o no ver la información... Confirmame si esta implementación decidis realizarla sobre este pr o abrir una tarea nueva.

![image (3)](https://user-images.githubusercontent.com/72876985/215772751-1d66691b-0762-49f5-8ee6-c7bdad2b6bda.png)

2023-02-08 15:44 UTC, ma7payne commented
@AgosLizzi si lo dejamos para una tarea nueva!

2023-02-09 14:53 UTC, MarianoCampetella approved these changes

2023-02-09 14:56 UTC, MarianoCampetella commented
Dejo la tarea de implementar un dropdown para que no quede en el olvido!
https://proyectos.andes.gob.ar/browse/TOP-151

2023-02-09 16:58 UTC, AgosLizzi approved these changes

2023-03-20 16:15 UTC, maring0019 requested changes
Hola Matias! 
Lo que veo es que el orden en que aparecen los _datos no es el mismo que el mockup_. Por ejemplo primero aparece Fecha Inicio Prestación y después Fecha Creación Solicitud. Y en el mockup va primero Fecha Creación Solicitud y después Fecha Inicio Prestación. Lo mismo pasa con los datos del Profesional y de la Organización. 

En conclusión, sería cambiar el orden de la información para que sea como el del mockup.

2023-03-22 11:18 UTC, ma7payne commented
@maring0019  Listo el cambio del ordenamiento de los datos!

2023-03-22 11:38 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [8615](http://condorpiedra.andes.gob.ar:85/8615/mochawesome.html)
CYPRESS RUN: [7793](https://dashboard.cypress.io/projects/xr7gft/runs/7793/specs)
TEST START: 2023-03-22T11:38:18.398Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-03-30 18:04 UTC, maring0019 commented
- El orden de los títulos está bien.
-  Solo un detalle. El tamaño de los íconos creo que se ve mejor con size="md" que sm, como estaba antes.

2023-03-31 12:26 UTC, maring0019 approved these changes

2023-04-11 12:48 UTC, merged