CIT - En accion de turnos agregar datos del usuario y ordenar busquedas en el sidebar
andes/app pull request #2816
Opened 2023-02-03 13:48 UTC by Fabio-Ramirez

### Requerimiento
 

### Funcionalidad desarrollada 

1.  En el sidebar del html, se agrego un contenedor con la info del usuario.
2.  Usando el componente paciente-detalle se obtuvo la info basica del usuario.
3.  Se modifico el array "busquedas" para visualizarlo en el sidebar, comprimiendolo a 5 prestaciones y ordenando en el caso de  prestaciones ya existentes en el campo "BUSQUEDAS RECIENTES".

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2023-02-06 18:15 UTC, AgosLizzi requested changes
Fabio, la tarea especificaba que el plex detail era necesario agregarlo en la pantalla del calendario, no replicarlo cuando ya tengo prestación y fecha seleccionada. De esta manera se superponen los componentes. Te dejo video:
https://www.loom.com/share/c9f1f890eb6c4d11acae9de4922114d5
Te dejo también una imagen de como se ve el otro sidebar, así deberia quedar. solo un plex detail sobre la pantalla.
![image](https://user-images.githubusercontent.com/72876985/217050652-3dd90e94-6f3c-4f30-a3bb-b57e405cd522.png)

Por otro lado, sobre las busquedas recientes, si hago click 5 veces sobre "consulta de medicina general", me las replica. Creo que desde la usabilidad no estaría bueno que eso suceda, si ya tengo guardado una prestación en una busqueda y decido usar esa esa, y por algún motivo hago click varias veces sobre la misma, no deberia realizarse dicha acción.
![image](https://user-images.githubusercontent.com/72876985/217051272-57d4ccc3-0c53-43af-b8a4-2caf3b793bf0.png)

Por último, al primer plex detail, el del calendario, Le agregaría un plex title, para que quede algo así
![plex-detail-03](https://user-images.githubusercontent.com/72876985/217052147-3073953d-ee5b-46fb-a527-f37a940ece22.png)

2023-02-08 18:53 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [8382](http://condorpiedra.andes.gob.ar:85/8382/mochawesome.html)
CYPRESS RUN: [7559](https://dashboard.cypress.io/projects/xr7gft/runs/7559/specs)
TEST START: 2023-02-08T18:52:20.017Z
TOTAL: 388
SUCCESS: 381
FAIL: 5
SKIPPED: 2

2023-03-21 13:27 UTC, Fabio-Ramirez commented
Se realizaron los cambios de logica para corregir unos puntos en el componente dar-turnos.ts (lineas  370-381, 738-739).
En el html se modifico las lineas 70 y 71, el resto es de linteo.

2023-03-21 13:56 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [8606](http://condorpiedra.andes.gob.ar:85/8606/mochawesome.html)
CYPRESS RUN: [7784](https://dashboard.cypress.io/projects/xr7gft/runs/7784/specs)
TEST START: 2023-03-21T13:56:17.014Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-03-22 12:43 UTC, AgosLizzi requested changes
Fabio, parecier que la prestación consulta de genética anula las otras prestraciones, te dejo un video para mostrarte. Con la prestación "consulta de cirugía general" me sucede lo mismo. 

https://www.loom.com/share/21750b748ef94944a711db2cd7609de8

2023-05-17 14:47 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [8911](http://condorpiedra.andes.gob.ar:85/8911/mochawesome.html)
CYPRESS RUN: [8076](https://dashboard.cypress.io/projects/xr7gft/runs/8076/specs)
TEST START: 2023-05-17T14:46:51.274Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-05-17 14:57 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [8912](http://condorpiedra.andes.gob.ar:85/8912/mochawesome.html)
CYPRESS RUN: [8077](https://dashboard.cypress.io/projects/xr7gft/runs/8077/specs)
TEST START: 2023-05-17T14:57:18.747Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-05-17 16:35 UTC, negro89 commented
Fabio, lo nuevo lo vi ok. Pero la seleccionar el turno, el siguiente sidebar aparece roto (Dejo captura). Revisate las nuevas funciones que agregaste para simplificar los if del html que parece que no le estas mandando el turno y lo comas como si la variable de clase lo tuviera seleccionado.
![image](https://github.com/andes/app/assets/37875706/ee14478d-adfd-4643-9cca-563facf5c104)

2023-05-17 16:54 UTC, AgosLizzi approved these changes

2023-05-17 18:10 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [8915](http://condorpiedra.andes.gob.ar:85/8915/mochawesome.html)
CYPRESS RUN: [8079](https://dashboard.cypress.io/projects/xr7gft/runs/8079/specs)
TEST START: 2023-05-17T18:10:03.539Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-05-17 18:59 UTC, negro89 approved these changes

2023-05-17 19:01 UTC, merged