fix(IN-511): balance hidrico en el plan de indicaciones
andes/app pull request #2819
Opened 2023-02-07 14:46 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-511

### Funcionalidad desarrollada 
1. se corrigió el error de no poder guardar una indicación de hidratación (el error provenía de un forEach)
2. Se agregaron toast al momento de guardar y editar una indicación de hidratación y también se agregaron tooltips a los botones de guardar y cancelar.
3. Se hizo un pequeño refactor en los detalles del sidebar al momento de mostrar una indicación de hidratacion.

NOTA: La tarea solamente consiste en poder guardar y editar una indicación de hidratacion solamente. Existen algunos bugs dentro del plan de indicacion pero ya existen las tareas correspondientes para ir resolviendolo! 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si   https://github.com/andes/api/pull/1783
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2023-02-07 15:04 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8367](http://condorpiedra.andes.gob.ar:85/8367/mochawesome.html)
CYPRESS RUN: [7545](https://dashboard.cypress.io/projects/xr7gft/runs/7545/specs)
TEST START: 2023-02-07T15:04:10.052Z
TOTAL: 406
SUCCESS: 397
FAIL: 7
SKIPPED: 2

2023-02-17 12:48 UTC, AgosLizzi requested changes
Campe, algunos detallitos.:  

1.  Cuando no agrego texto en el campo **"Indicaciones"** sobre el sidebar me aparece como **"[object Object]"** , entiendo que es algo que sale por defecto. Yo agregaría un texto minímo que avise que en ese item no se agrego nada.
2. Cuando si agrego texto en el campo **"Indicaciones"**, sobre el sidebar lo visualizo en gris, mientras que los demas se visualizan en blanco. Modificar para que haya una consistencia. 
3. Cuando valido la indicación hidrica me salta error en la consola (en el video lo vas a poder visualiazar bien)
4. Al editar el detalle de la indicación para agregar texto sobre el campo **"indicaciones"**, parece que en una primera instacia me lo carga, y luego ese texto desaparece. Va video para que puedas observar bien el comportamiento. https://www.loom.com/share/a5a44c36c262492fb610484d3947a700

2023-04-13 19:23 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8708](http://condorpiedra.andes.gob.ar:85/8708/mochawesome.html)
CYPRESS RUN: [7883](https://dashboard.cypress.io/projects/xr7gft/runs/7883/specs)
TEST START: 2023-04-13T19:23:05.711Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-05-03 14:42 UTC, MarianoCampetella commented
> 1. agregaría un texto minímo que avise que en ese item no se agrego nada.

Corregido!

2023-05-03 15:01 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8822](http://condorpiedra.andes.gob.ar:85/8822/mochawesome.html)
CYPRESS RUN: [7991](https://dashboard.cypress.io/projects/xr7gft/runs/7991/specs)
TEST START: 2023-05-03T15:00:52.365Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-05-04 14:34 UTC, silviroa approved these changes

2023-05-04 18:03 UTC, negro89 approved these changes

2023-05-04 18:04 UTC, merged