TOP - Seguimiento de llamados telefonicos a pacientes
andes/app pull request #2821
Opened 2023-02-14 18:57 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/TOP-131

### Funcionalidad desarrollada 

1. Se agrego una nueva funcionalidad de tal forma que el usuario puede notificar las veces que sea necesario, completando los campo obligatorios de fecha y descripcion.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si   https://github.com/andes/api/pull/1785
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

NOTA: Se debería agregar un nuevo test para controlar esta nueva funcionalidad.

2023-02-23 13:44 UTC, ma7payne commented
![image](https://user-images.githubusercontent.com/7356452/220923619-5857b800-5ba6-49a2-8f78-78a9407abbd4.png)

![image](https://user-images.githubusercontent.com/7356452/220924290-a9feec28-0283-4b82-b955-c2699eeb5200.png)

@MarianoCampetella adjunto imagen de una solicitud vieja que no tiene historial. Para estos casos no es posible realizar la operación de notificar al paciente. Considerar aplicar un chequeo para evitar notificar en estos casos.

2023-02-24 17:11 UTC, MarianoCampetella commented
> ![image](https://user-images.githubusercontent.com/7356452/220923619-5857b800-5ba6-49a2-8f78-78a9407abbd4.png)
> 
> ![image](https://user-images.githubusercontent.com/7356452/220924290-a9feec28-0283-4b82-b955-c2699eeb5200.png)
> 
> @MarianoCampetella adjunto imagen de una solicitud vieja que no tiene historial. Para estos casos no es posible realizar la operación de notificar al paciente. Considerar aplicar un chequeo para evitar notificar en estos casos.

Corregido, en caso de que la solicitud no tenga ningun historial no se presentara dicho error y se mostrará una leyenda en el sidebar de que la solicitud no tiene un historial

2023-03-03 17:58 UTC, AgosLizzi requested changes
Revisar cuando el estado de la solicitud es "turno dado" me aparece para notificar paciente
![2023-03-03 (6)](https://user-images.githubusercontent.com/72876985/222793445-06148154-8162-40e8-bd32-ae2a3f02c8a7.png)

2023-03-07 13:58 UTC, MarianoCampetella commented
> Revisar cuando el estado de la solicitud es "turno dado" me aparece para notificar paciente ![2023-03-03 (6)](https://user-images.githubusercontent.com/72876985/222793445-06148154-8162-40e8-bd32-ae2a3f02c8a7.png)

Tanto para las solicitudes de entrada como de salida no se observa el dropdown que permite visualizar la opcion de notificar paciente. Revise en múltiples fechas incluyendo la imagen que me mandaste pero no logre encontrar ese error. 
![image](https://user-images.githubusercontent.com/65697028/223443049-3e75253e-c160-4834-bfd6-180434d4f175.png)

Aprovecho para dejar un comentario de que se agrego una condición mas a la función de verificarBotones ya que desde las solicitudes de salida no se podían notificar a las que se encontraban con estado AUDITORIA

2023-03-07 14:17 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8546](http://condorpiedra.andes.gob.ar:85/8546/mochawesome.html)
CYPRESS RUN: [7725](https://dashboard.cypress.io/projects/xr7gft/runs/7725/specs)
TEST START: 2023-03-07T14:16:52.707Z
TOTAL: 406
SUCCESS: 401
FAIL: 3
SKIPPED: 2

2023-03-07 14:30 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8547](http://condorpiedra.andes.gob.ar:85/8547/mochawesome.html)
CYPRESS RUN: [7726](https://dashboard.cypress.io/projects/xr7gft/runs/7726/specs)
TEST START: 2023-03-07T14:29:49.516Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-03-13 14:25 UTC, MarianoCampetella commented
> Revisar cuando el estado de la solicitud es "turno dado" me aparece para notificar paciente ![2023-03-03 (6)](https://user-images.githubusercontent.com/72876985/222793445-06148154-8162-40e8-bd32-ae2a3f02c8a7.png)

Corregido, la opción de "notificar paciente" solamente saldrá en los estados AUDITORIA y PENDIENTE.

2023-03-20 12:17 UTC, AgosLizzi requested changes
Campe, cuando doy aceptar me aparece este error. 
![2023-03-20 (3)](https://user-images.githubusercontent.com/72876985/226335656-532a1349-2e56-46a9-ab42-221f04f33e3f.png)
![2023-03-20 (4)](https://user-images.githubusercontent.com/72876985/226335671-06cab0f5-ef4d-404e-b888-2e0da042f69f.png)

2023-03-22 12:20 UTC, AgosLizzi approved these changes

2023-03-31 17:55 UTC, maring0019 commented
Sigue apareciendo el siguiente error. Al querer guardar la notificación no lo permite. Y en la consola aparece ese error. 
![error](https://user-images.githubusercontent.com/57371507/229194275-c8e7dfb6-9bda-4690-a10c-eed2410477e2.png)

2023-03-31 17:59 UTC, maring0019 requested changes
Sigue apareciendo el siguiente error. Al querer guardar la notificación no lo permite. Y en la consola aparece ese error.

![error](https://user-images.githubusercontent.com/57371507/229195260-6aac6958-4d4b-4a1c-83e8-bcc27c86efc4.png)

2023-04-13 17:48 UTC, MarianoCampetella commented
> Sigue apareciendo el siguiente error. Al querer guardar la notificación no lo permite. Y en la consola aparece ese error.
> 
> ![error](https://user-images.githubusercontent.com/57371507/229195260-6aac6958-4d4b-4a1c-83e8-bcc27c86efc4.png)

Corregido!
Al momento de crear una solicitud en el historial figura que fue creada en una determinada fecha y por el usuario. Las prestaciones que no tenían ningún historial es porque fueron creadas hace mucho lo cual esto no sucede actualmente. De todas formas se agrego una condición  de que si no existe ningún historial no se pueda notificar al paciente.
También, según lo charlado con Silvina Garcia y Roa se cambio "notificar paciente" por "comunicación con el paciente"

2023-05-15 18:14 UTC, negro89 commented
Funciona de 10, pero me parece que no queda bien la columna en el medio (historial). Ademas redunda. Se lo sacamos? 
![image](https://github.com/andes/app/assets/37875706/bae27733-d344-4230-86de-4c75ee38150e)

2023-05-16 12:21 UTC, MarianoCampetella commented
> Funciona de 10, pero me parece que no queda bien la columna en el medio (historial). Ademas redunda. Se lo sacamos? Aprovecharía para ponerle al formulario como fecha maxima el dia actual. ![image](https://user-images.githubusercontent.com/37875706/238435422-bae27733-d344-4230-86de-4c75ee38150e.png)

Corregido! Se agrego el [max] y se quito la columna de notificado para respetar como estaba antes, es decir, dos columnas nomas.

2023-05-16 13:31 UTC, negro89 approved these changes

2023-05-19 18:10 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8928](http://condorpiedra.andes.gob.ar:85/8928/mochawesome.html)
CYPRESS RUN: [8092](https://dashboard.cypress.io/projects/xr7gft/runs/8092/specs)
TEST START: 2023-05-19T18:10:26.571Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-05-23 12:02 UTC, merged