MPI: Implementa registro para extranjeros con DNI argentino
andes/app pull request #2822
Opened 2023-02-27 16:20 UTC by ma7payne

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/MPI-393

### Funcionalidad desarrollada 

1. Se crea un nuevo formulario (paralelo) para registrar a un paciente extranjero con DNI argentino
2. Se crea una opción (boton slide) para habilitar el con DNI a un paciente extranjero
3. Se validan los campos actuales del formulario para el paciente extranjero al momento de habilitar la opción para registrar con DNI argentino
4. Se validan los campos del paciente con DNI argentino
5. Al momento de validar con RENAPER, se reemplazan los datos obtenidos en el formulario de paciente con DNI argentino
6. Al momento de guardar los datos del paciente, se chequean las suregencias con pacientes similares
7. Al seleccionar un paciente sugerido, el formulario se redirige al formulario tradicional de registro de paciente argentino
8. Al momento de redirigir, se muestra una alerta informando acerca de la vinculación del paciente extranjero con el nuevo paciente con DNI argentino
9. Al guardar los datos (con o sin paciente sugerido) se actualizan en DB los datos del paciente extranjero y se crea el nuevo paciente con DNI argentino
9. Se vincula al paciente extranjero actual con el nuevo paciente con DNI argentino

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2023-03-03 17:16 UTC, AgosLizzi requested changes
Mati, detallitos:

1. Primera vez que veo un botón "seleccionar" en ANDES. No me parece muy usable para lo que estamos acostumbrados en el sistema. La acción puede salir directamente del **click** sobre el listado, como se suelen comportar el resto de las acciones en la interfaz. 
![2023-03-03 (4)](https://user-images.githubusercontent.com/72876985/222784503-4d9160f6-4343-4d75-aea3-ee77b17ed459.png)

2. Ampliaria un poco el tamaño del sidebar para que el listado se vea asi: 
![2023-03-03 (5)](https://user-images.githubusercontent.com/72876985/222784786-f5099612-cf4e-4a7d-b847-5f389f2caac0.png)

2023-03-13 17:45 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [8575](http://condorpiedra.andes.gob.ar:85/8575/mochawesome.html)
CYPRESS RUN: [7753](https://dashboard.cypress.io/projects/xr7gft/runs/7753/specs)
TEST START: 2023-03-13T17:41:39.259Z
TOTAL: 406
SUCCESS: 394
FAIL: 10
SKIPPED: 2

2023-03-28 14:10 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [8641](http://condorpiedra.andes.gob.ar:85/8641/mochawesome.html)
CYPRESS RUN: [7817](https://dashboard.cypress.io/projects/xr7gft/runs/7817/specs)
TEST START: 2023-03-28T14:09:12.150Z
TOTAL: 406
SUCCESS: 400
FAIL: 4
SKIPPED: 2

2023-04-20 15:42 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [8739](http://condorpiedra.andes.gob.ar:85/8739/mochawesome.html)
CYPRESS RUN: [7914](https://dashboard.cypress.io/projects/xr7gft/runs/7914/specs)
TEST START: 2023-04-20T15:42:03.495Z
TOTAL: 356
SUCCESS: 350
FAIL: 4
SKIPPED: 2

2023-04-21 13:55 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [8746](http://condorpiedra.andes.gob.ar:85/8746/mochawesome.html)
CYPRESS RUN: [7921](https://dashboard.cypress.io/projects/xr7gft/runs/7921/specs)
TEST START: 2023-04-21T13:55:21.576Z
TOTAL: 356
SUCCESS: 350
FAIL: 4
SKIPPED: 2

2023-05-08 17:58 UTC, MarianoCampetella commented
Es necesario modificar los siguientes test
![image](https://user-images.githubusercontent.com/65697028/236896490-31b1345b-5ac1-48a6-9ed4-b61ba33a1439.png)

2023-05-18 14:50 UTC, ma7payne commented
@AgosLizzi esta realizado el cambio del botón "Seleccionar" por click directo sobre el item del paciente sugerido. 

@MarianoCampetella los casos de test estan listos y corresponden al siguiente PR: https://github.com/andes/andes-test-integracion/pull/472

Quedo atento! Saludos

2023-05-30 15:29 UTC, AgosLizzi requested changes
Mati, vi varias cositas: 

1. Consulta, esta sugerencia que te parecio? "Ampliaria un poco el tamaño del sidebar para que el listado se vea asi:"? 
2. Si es un mensaje de warning, con un "atención", por que se utiliza color info? 
![Captura de pantalla (7)](https://github.com/andes/app/assets/72876985/7af8e528-4105-4d64-b89b-b7ac99ffe6ec)
3. Cuando tengo los datos obligatorios completos, me salta este modal, te dejo video.
 https://www.loom.com/share/6344e952ac29465c8030c67c51d7bafc

2023-06-08 13:12 UTC, AgosLizzi approved these changes

2023-06-08 18:19 UTC, MarianoCampetella requested changes

2023-06-08 18:19 UTC, MarianoCampetella commented on src/app/core/mpi/components/paciente.component.ts
> +        if (data.registroDNI !== undefined) {
Solamente puede llegar a venir el valor undefined? que ocurre si viene el valor null?
Si se debe controlar que sea distinto de null y undefined entonces se deberia remplazar la condicion por !data.registroDNI

2023-06-26 18:36 UTC, ma7payne commented on src/app/core/mpi/components/paciente.component.ts
> +        if (data.registroDNI !== undefined) {
@MarianoCampetella como el muestreo de los formularios es dinámico, en algunos casos la variable registroDNI puede no estar definida, por eso la necesidad de chequearla como tal.

2023-06-26 18:43 UTC, ma7payne commented on src/app/core/mpi/components/datos-basicos.html
> +                             (change)="completarGenero();">
Listo el cambio!

2023-06-29 14:14 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [9132](http://condorpiedra.andes.gob.ar:85/9132/mochawesome.html)
CYPRESS RUN: [8279](https://dashboard.cypress.io/projects/xr7gft/runs/8279/specs)
TEST START: 2023-06-29T14:13:53.197Z
TOTAL: 407
SUCCESS: 379
FAIL: 26
SKIPPED: 2

2023-07-03 18:47 UTC, MarianoCampetella approved these changes

2023-08-14 23:16 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [9417](http://condorpiedra.andes.gob.ar:85/9417/mochawesome.html)
CYPRESS RUN: [8554](https://dashboard.cypress.io/projects/xr7gft/runs/8554/specs)
TEST START: 2023-08-14T23:16:31.198Z
TOTAL: 407
SUCCESS: 378
FAIL: 27
SKIPPED: 2

2023-08-15 14:46 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9424](http://condorpiedra.andes.gob.ar:85/9424/mochawesome.html)
CYPRESS RUN: [8561](https://dashboard.cypress.io/projects/xr7gft/runs/8561/specs)
TEST START: 2023-08-15T14:43:59.676Z
TOTAL: 352
SUCCESS: 318
FAIL: 32
SKIPPED: 2

2023-08-15 14:59 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9425](http://condorpiedra.andes.gob.ar:85/9425/mochawesome.html)
CYPRESS RUN: [8562](https://dashboard.cypress.io/projects/xr7gft/runs/8562/specs)
TEST START: 2023-08-15T14:56:47.224Z
TOTAL: 352
SUCCESS: 329
FAIL: 21
SKIPPED: 2

2023-08-15 15:26 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9426](http://condorpiedra.andes.gob.ar:85/9426/mochawesome.html)
CYPRESS RUN: [8563](https://dashboard.cypress.io/projects/xr7gft/runs/8563/specs)
TEST START: 2023-08-15T15:25:56.285Z
TOTAL: 407
SUCCESS: 377
FAIL: 28
SKIPPED: 2

2023-08-15 19:31 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [9429](http://condorpiedra.andes.gob.ar:85/9429/mochawesome.html)
CYPRESS RUN: [8566](https://dashboard.cypress.io/projects/xr7gft/runs/8566/specs)
TEST START: 2023-08-15T19:30:41.134Z
TOTAL: 357
SUCCESS: 343
FAIL: 12
SKIPPED: 2

2023-08-15 19:43 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [9430](http://condorpiedra.andes.gob.ar:85/9430/mochawesome.html)
CYPRESS RUN: [8567](https://dashboard.cypress.io/projects/xr7gft/runs/8567/specs)
TEST START: 2023-08-15T19:43:40.137Z
TOTAL: 407
SUCCESS: 377
FAIL: 28
SKIPPED: 2

2023-08-16 13:08 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9434](http://condorpiedra.andes.gob.ar:85/9434/mochawesome.html)
CYPRESS RUN: [8571](https://dashboard.cypress.io/projects/xr7gft/runs/8571/specs)
TEST START: 2023-08-16T13:07:59.130Z
TOTAL: 407
SUCCESS: 379
FAIL: 26
SKIPPED: 2

2023-09-05 12:55 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9551](http://condorpiedra.andes.gob.ar:85/9551/mochawesome.html)
CYPRESS RUN: [8677](https://dashboard.cypress.io/projects/xr7gft/runs/8677/specs)
TEST START: 2023-09-05T12:53:23.118Z
TOTAL: 379
SUCCESS: 342
FAIL: 35
SKIPPED: 2

2023-09-05 13:15 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9552](http://condorpiedra.andes.gob.ar:85/9552/mochawesome.html)
CYPRESS RUN: [8678](https://dashboard.cypress.io/projects/xr7gft/runs/8678/specs)
TEST START: 2023-09-05T13:11:10.085Z
TOTAL: 384
SUCCESS: 352
FAIL: 30
SKIPPED: 2

2023-09-05 16:50 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [9560](http://condorpiedra.andes.gob.ar:85/9560/mochawesome.html)
CYPRESS RUN: [8683](https://dashboard.cypress.io/projects/xr7gft/runs/8683/specs)
TEST START: 2023-09-05T16:50:06.276Z
TOTAL: 407
SUCCESS: 378
FAIL: 27
SKIPPED: 2

2023-09-05 17:10 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [9561](http://condorpiedra.andes.gob.ar:85/9561/mochawesome.html)
CYPRESS RUN: [8684](https://dashboard.cypress.io/projects/xr7gft/runs/8684/specs)
TEST START: 2023-09-05T17:09:48.906Z
TOTAL: 407
SUCCESS: 378
FAIL: 27
SKIPPED: 2

2023-09-05 17:13 UTC, negro89 approved these changes
Laburaso 👍🏼

2023-09-05 17:25 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [9562](http://condorpiedra.andes.gob.ar:85/9562/mochawesome.html)
CYPRESS RUN: [8685](https://dashboard.cypress.io/projects/xr7gft/runs/8685/specs)
TEST START: 2023-09-05T17:24:11.327Z
TOTAL: 407
SUCCESS: 375
FAIL: 30
SKIPPED: 2

2023-09-05 20:56 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [9565](http://condorpiedra.andes.gob.ar:85/9565/mochawesome.html)
CYPRESS RUN: [8688](https://dashboard.cypress.io/projects/xr7gft/runs/8688/specs)
TEST START: 2023-09-05T20:55:16.278Z
TOTAL: 353
SUCCESS: 327
FAIL: 24
SKIPPED: 2

2023-09-06 12:06 UTC, MCele requested changes
Revisar que:
Al validar un paciente si lo trae de la bd debería mostrar el botón "validar" y no "deshacer validación", ya que el paciente aún no fue validado.
Revisar error en consola al intentar guardar un paciente existente, además en este caso no debería tomarlo como referencia de paciente similar al 100%.

2023-09-06 14:13 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [9567](http://condorpiedra.andes.gob.ar:85/9567/mochawesome.html)
CYPRESS RUN: [8690](https://dashboard.cypress.io/projects/xr7gft/runs/8690/specs)
TEST START: 2023-09-06T14:13:31.853Z
TOTAL: 407
SUCCESS: 378
FAIL: 27
SKIPPED: 2

2023-10-26 15:15 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9826](http://condorpiedra.andes.gob.ar:85/9826/mochawesome.html)
CYPRESS RUN: [8936](https://dashboard.cypress.io/projects/xr7gft/runs/8936/specs)
TEST START: 2023-10-26T15:15:09.965Z
TOTAL: 407
SUCCESS: 377
FAIL: 28
SKIPPED: 2

2023-10-30 14:22 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9842](http://condorpiedra.andes.gob.ar:85/9842/mochawesome.html)
CYPRESS RUN: [8950](https://dashboard.cypress.io/projects/xr7gft/runs/8950/specs)
TEST START: 2023-10-30T14:22:12.570Z
TOTAL: 407
SUCCESS: 378
FAIL: 27
SKIPPED: 2

2023-10-30 16:17 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9843](http://condorpiedra.andes.gob.ar:85/9843/mochawesome.html)
CYPRESS RUN: [8951](https://dashboard.cypress.io/projects/xr7gft/runs/8951/specs)
TEST START: 2023-10-30T16:16:48.586Z
TOTAL: 406
SUCCESS: 378
FAIL: 26
SKIPPED: 2

2023-10-30 17:30 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9845](http://condorpiedra.andes.gob.ar:85/9845/mochawesome.html)
CYPRESS RUN: [8953](https://dashboard.cypress.io/projects/xr7gft/runs/8953/specs)
TEST START: 2023-10-30T17:29:11.252Z
TOTAL: 308
SUCCESS: 274
FAIL: 33
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-10-31 15:53 UTC, MCele requested changes
La vinculación entre paciente activo/inactivo se hace perfecto, pero aún noto algunos detalles a corregir al momento de validar un paciente, ya que se guarda como temporal y se duplica. Paso a detallar los casos que observé:
1. Una vez que se carga/edita un paciente y se lo valida (ya sea por primera vez desde el formulario con dni o como edición de un paciente extranjero), pueden ocurrir dos situaciones:
- el paciente no existe en la bd y se lo valida sin problemas con fuentes auténticas => debería quedar como estado "validado" en la base, pero queda como "temporal".
- el paciente si existe en la bd de mpi (DNI y sexo) y se trae el paciente original, pero el paciente no fue validado, sin embargo el botón "validar" queda inactivo y no se lo puede validar. Por otro lado, cuando se guarda el paciente que se acaba de validar, se duplica, es decir queda el paciente de la base que estaba validado, pero tambien se crea un nuevo similar, pero con estado temporal.

2. Luego de validar y guardar un paciente, el paciente que queda inactivo (paciente con identificación extranjera) no debería aparecer en el listado de búsquedas recientes de mpi.

2023-11-09 17:23 UTC, ma7payne commented
> La vinculación entre paciente activo/inactivo se hace perfecto, pero aún noto algunos detalles a corregir al momento de validar un paciente, ya que se guarda como temporal y se duplica. Paso a detallar los casos que observé:
> 
> 1. Una vez que se carga/edita un paciente y se lo valida (ya sea por primera vez desde el formulario con dni o como edición de un paciente extranjero), pueden ocurrir dos situaciones:
> 
> * el paciente no existe en la bd y se lo valida sin problemas con fuentes auténticas => debería quedar como estado "validado" en la base, pero queda como "temporal".
> * el paciente si existe en la bd de mpi (DNI y sexo) y se trae el paciente original, pero el paciente no fue validado, sin embargo el botón "validar" queda inactivo y no se lo puede validar. Por otro lado, cuando se guarda el paciente que se acaba de validar, se duplica, es decir queda el paciente de la base que estaba validado, pero también se crea un nuevo similar, pero con estado temporal.
> 
> 2. Luego de validar y guardar un paciente, el paciente que queda inactivo (paciente con identificación extranjera) no debería aparecer en el listado de búsquedas recientes de mpi.
> 
> Dejo un video que lo muestra https://drive.google.com/file/d/1gAUxo0UrWetRMMNPzT2MWr0XM6LEKKWy/view

Listos los cambios!

2023-11-14 22:02 UTC, MCele commented
Mati estuve revisando y noté lo siguiente:

- Cuando se vincula el paciente extranjero, con un paciente ya existente en la BD de datos anda perfecta la vinculación. Pero cuando se intenta vincular un paciente extranjero (temporal) con uno nuevo validado, no se está creando el nuevo paciente.

2023-11-17 14:38 UTC, ma7payne commented
> Mati estuve revisando y noté lo siguiente:
> 
> * Cuando se vincula el paciente extranjero, con un paciente ya existente en la BD de datos anda perfecta la vinculación. Pero cuando se intenta vincular un paciente extranjero (temporal) con uno nuevo validado, no se está creando el nuevo paciente.

@MCele listos estos cambios tambien.

2023-11-28 15:56 UTC, MCele approved these changes

2023-11-28 16:33 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [9989](http://condorpiedra.andes.gob.ar:85/9989/mochawesome.html)
CYPRESS RUN: [9098](https://dashboard.cypress.io/projects/xr7gft/runs/9098/specs)
TEST START: 2023-11-28T16:31:08.556Z
TOTAL: 325
SUCCESS: 313
FAIL: 10
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-11-28 19:09 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9991](http://condorpiedra.andes.gob.ar:85/9991/mochawesome.html)
CYPRESS RUN: [9100](https://dashboard.cypress.io/projects/xr7gft/runs/9100/specs)
TEST START: 2023-11-28T19:08:32.936Z
TOTAL: 363
SUCCESS: 328
FAIL: 33
SKIPPED: 2

2023-11-29 13:16 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [9999](http://condorpiedra.andes.gob.ar:85/9999/mochawesome.html)
CYPRESS RUN: [9108](https://dashboard.cypress.io/projects/xr7gft/runs/9108/specs)
TEST START: 2023-11-29T13:15:39.784Z
TOTAL: 380
SUCCESS: 369
FAIL: 9
SKIPPED: 2

2023-12-05 15:29 UTC, MCele commented
Revisar test

2023-12-15 14:49 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10061](http://condorpiedra.andes.gob.ar:85/10061/mochawesome.html)
CYPRESS RUN: [9169](https://dashboard.cypress.io/projects/xr7gft/runs/9169/specs)
TEST START: 2023-12-15T14:49:08.994Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-12-15 16:06 UTC, merged