Feat(IN-531) Inmovilizar Titulo c/Botones en Ingreso de Pacientes capa Estadística
andes/app pull request #2830
Opened 2023-03-20 15:10 UTC by JuanIRamirez

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/IN-531

### Funcionalidad desarrollada 

1. Componente: ingresar-paciente.component
2. Se creó un archivo 'ingresar-paciente.component.css' con la clase '.title-fixed' para inmovilizar el Título y los botones del encabezado en el Ingreso de Pacientes de Internación, capa Estadística.
3. Se agregó la ref. a ese archivo en el 'styleUrls' del componente.
4. Se llama a la clase .title-fixed desde el .html 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X ] No

2023-03-20 16:12 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [8601](http://condorpiedra.andes.gob.ar:85/8601/mochawesome.html)
CYPRESS RUN: [7779](https://dashboard.cypress.io/projects/xr7gft/runs/7779/specs)
TEST START: 2023-03-20T16:10:55.501Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-03-21 12:24 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [8605](http://condorpiedra.andes.gob.ar:85/8605/mochawesome.html)
CYPRESS RUN: [7783](https://dashboard.cypress.io/projects/xr7gft/runs/7783/specs)
TEST START: 2023-03-21T12:23:47.077Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-03-22 12:02 UTC, AgosLizzi requested changes
Juan, me surgen un par de errores cuando abro el módulo, y siempre van en aumento. Lo podrás revisar?

![2023-03-22 (2)](https://user-images.githubusercontent.com/72876985/226899926-7dd31f79-d265-4eaf-ab33-64f631197f82.png)

![2023-03-22 (1)](https://user-images.githubusercontent.com/72876985/226899328-8cd7f73c-676b-4682-b6cd-265c108fafa4.png)

2023-03-23 13:32 UTC, AgosLizzi approved these changes

2023-04-11 13:58 UTC, merged