CIT - Mostrar Obra Social en Historial de Turnos
andes/app pull request #2832
Opened 2023-03-22 12:21 UTC by JuanIRamirez

### Requerimiento
 []
https://proyectos.andes.gob.ar/browse/CIT-215

### Funcionalidad desarrollada 

1.  Se muestra en Historial de Turnos la Obra Social con la que se dio el turno.
2. Archivo modificado: \app\src\app\components\turnos\dashboard\estadisticas-pacientes.html

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2023-03-22 12:42 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [8616](http://condorpiedra.andes.gob.ar:85/8616/mochawesome.html)
CYPRESS RUN: [7794](https://dashboard.cypress.io/projects/xr7gft/runs/7794/specs)
TEST START: 2023-03-22T12:42:18.963Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-03-23 12:14 UTC, MarianoCampetella requested changes

2023-03-23 12:14 UTC, MarianoCampetella commented on src/app/components/turnos/dashboard/estadisticas-pacientes.html
> +                            Obra Social: {{turno.paciente.obraSocial.nombre}}
Estaría bueno agregar una condición que pregunte si el paciente tiene una obra social que lo muestre como en este caso. Pero si no tiene agregaría lo siguiente: Sin obra social. 
Esto mismo solucionaría el problema que actualmente ocurre de que si dicho paciente no posee una obra social arroja múltiples errores en consola y en el sidebar no se muestra correctamente la información!

2023-03-23 12:21 UTC, MarianoCampetella commented
Al parecer también se subieron los cambios de la tarea de internación: https://github.com/andes/app/pull/2830#pullrequestreview-1352400145. Habría que sacarlos para evitar conflictos futuros!

2023-03-23 12:49 UTC, JuanIRamirez commented on src/app/components/turnos/dashboard/estadisticas-pacientes.html
> +                            Obra Social: {{turno.paciente.obraSocial.nombre}}
Hecho. si no tiene OS, muestra: "Sin obra social".

2023-03-23 13:54 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [8624](http://condorpiedra.andes.gob.ar:85/8624/mochawesome.html)
CYPRESS RUN: [7801](https://dashboard.cypress.io/projects/xr7gft/runs/7801/specs)
TEST START: 2023-03-23T13:54:03.420Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-03-29 12:39 UTC, AgosLizzi approved these changes

2023-04-11 13:27 UTC, merged