MPI: Cambiar icono 'plus' por 'check' en Notas Paciente
andes/app pull request #2834
Opened 2023-03-23 15:36 UTC by JuanIRamirez

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/MPI-397

### Funcionalidad desarrollada 

1. Se cambió el ícono de guardar nota de Paciente.
2. Archivo: \app\src\app\core\mpi\components\notas-paciente.html
3. Se modificó la propiedad "icon" de "plus" a "check" del "plex-button"

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2023-03-23 15:53 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [8626](http://condorpiedra.andes.gob.ar:85/8626/mochawesome.html)
CYPRESS RUN: [7803](https://dashboard.cypress.io/projects/xr7gft/runs/7803/specs)
TEST START: 2023-03-23T15:53:19.850Z
TOTAL: 406
SUCCESS: 401
FAIL: 3
SKIPPED: 2

2023-03-23 17:19 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [8628](http://condorpiedra.andes.gob.ar:85/8628/mochawesome.html)
CYPRESS RUN: [7805](https://dashboard.cypress.io/projects/xr7gft/runs/7805/specs)
TEST START: 2023-03-23T17:19:10.043Z
TOTAL: 406
SUCCESS: 401
FAIL: 3
SKIPPED: 2

2023-03-24 23:57 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [8630](http://condorpiedra.andes.gob.ar:85/8630/mochawesome.html)
CYPRESS RUN: [7807](https://dashboard.cypress.io/projects/xr7gft/runs/7807/specs)
TEST START: 2023-03-24T23:56:35.522Z
TOTAL: 318
SUCCESS: 296
FAIL: 20
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-03-27 13:29 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [8634](http://condorpiedra.andes.gob.ar:85/8634/mochawesome.html)
CYPRESS RUN: [7811](https://dashboard.cypress.io/projects/xr7gft/runs/7811/specs)
TEST START: 2023-03-27T13:29:14.236Z
TOTAL: 406
SUCCESS: 402
FAIL: 2
SKIPPED: 2

2023-03-28 14:13 UTC, MarianoCampetella commented
Juan te dejo un par de cositas que estaría bueno que se agregaran para que quede de 10:
- Ya que modificaste el icono del botón, no estaría demás agregar un tooltip que diga "guardar" para darle mas información al usuario. 
- Cuando seleccionamos el tab de NOTAS observamos la leyenda "No se encontraron notas registradas en el paciente" pero cuando selecciono el botón "AGREGAR NOTA" sigue estando dicha leyenda. Lo ideal seria que cuando se selecciona el botón, esa leyenda no debería estar. 
![image](https://user-images.githubusercontent.com/65697028/228265874-1a997e34-ee66-4228-8105-75e99a592588.png)

- Corregir los test detallados abajo ya que al cambiar los iconos de los botones no están logrando pasar.
![image](https://user-images.githubusercontent.com/65697028/228266408-f1159927-b1c9-424b-897e-d1de2d77fbc4.png)

2023-03-29 13:31 UTC, AgosLizzi requested changes
Juan, con respecto al comentario que te sugirió @MarianoCampetella. Yo no agregaría el tooltip, me parece que el botón es sumamente intuitivo como para generar otra "guía". También tengamos en cuenta que antes para confirmar una nota se encontraba un "+" y la persona usuaria lo entendia de igual manera. No confundamos agregar información clave y funcional, que aporte significativamente a la interfaz, con agregar acciones ambiguas y repetitivas. 

Por otro lado, si me sumo al comentario para agregar toast, y eliminar la leyenda "No se encontraron notas registradas en el paciente"  un vez que damos click al botón

Avisame y cualquier cosa lo vemos,

2023-07-06 13:14 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9174](http://condorpiedra.andes.gob.ar:85/9174/mochawesome.html)
CYPRESS RUN: [8321](https://dashboard.cypress.io/projects/xr7gft/runs/8321/specs)
TEST START: 2023-07-06T13:13:52.008Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

2023-07-06 13:30 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9175](http://condorpiedra.andes.gob.ar:85/9175/mochawesome.html)
CYPRESS RUN: [8322](https://dashboard.cypress.io/projects/xr7gft/runs/8322/specs)
TEST START: 2023-07-06T13:30:10.590Z
TOTAL: 403
SUCCESS: 398
FAIL: 3
SKIPPED: 2

2023-07-06 13:50 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9176](http://condorpiedra.andes.gob.ar:85/9176/mochawesome.html)
CYPRESS RUN: [8323](https://dashboard.cypress.io/projects/xr7gft/runs/8323/specs)
TEST START: 2023-07-06T13:50:19.313Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

2023-07-06 18:32 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9178](http://condorpiedra.andes.gob.ar:85/9178/mochawesome.html)
CYPRESS RUN: [8325](https://dashboard.cypress.io/projects/xr7gft/runs/8325/specs)
TEST START: 2023-07-06T18:32:05.773Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

2023-07-25 12:33 UTC, JuanIRamirez commented on src/app/core/mpi/components/notas-paciente.html
>          </plex-text>
Hecho

2023-07-25 13:08 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9260](http://condorpiedra.andes.gob.ar:85/9260/mochawesome.html)
CYPRESS RUN: [8406](https://dashboard.cypress.io/projects/xr7gft/runs/8406/specs)
TEST START: 2023-07-25T13:07:47.956Z
TOTAL: 403
SUCCESS: 398
FAIL: 3
SKIPPED: 2

2023-07-25 15:16 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9262](http://condorpiedra.andes.gob.ar:85/9262/mochawesome.html)
CYPRESS RUN: [8408](https://dashboard.cypress.io/projects/xr7gft/runs/8408/specs)
TEST START: 2023-07-25T15:16:17.287Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

2023-07-25 18:28 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9267](http://condorpiedra.andes.gob.ar:85/9267/mochawesome.html)
CYPRESS RUN: [8413](https://dashboard.cypress.io/projects/xr7gft/runs/8413/specs)
TEST START: 2023-07-25T18:28:19.789Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-07-26 12:07 UTC, JuanIRamirez commented on src/app/core/mpi/components/notas-paciente.html
>          </plex-text>
La propiedad 'required' solo para el cuerpo de la nota, el tìtulo es opcional

2023-07-26 12:37 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9273](http://condorpiedra.andes.gob.ar:85/9273/mochawesome.html)
CYPRESS RUN: [8419](https://dashboard.cypress.io/projects/xr7gft/runs/8419/specs)
TEST START: 2023-07-26T12:37:27.995Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-07-27 11:37 UTC, MarianoCampetella approved these changes

2023-08-14 14:35 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9406](http://condorpiedra.andes.gob.ar:85/9406/mochawesome.html)
CYPRESS RUN: [8543](https://dashboard.cypress.io/projects/xr7gft/runs/8543/specs)
TEST START: 2023-08-14T14:35:24.880Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

2023-08-14 15:11 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9409](http://condorpiedra.andes.gob.ar:85/9409/mochawesome.html)
CYPRESS RUN: [8546](https://dashboard.cypress.io/projects/xr7gft/runs/8546/specs)
TEST START: 2023-08-14T15:10:47.250Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-08-14 15:38 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9411](http://condorpiedra.andes.gob.ar:85/9411/mochawesome.html)
CYPRESS RUN: [8548](https://dashboard.cypress.io/projects/xr7gft/runs/8548/specs)
TEST START: 2023-08-14T15:38:22.636Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-08-29 15:03 UTC, merged