In - Plan indicaciones - No se debería poder registrar indicaciones en el pasado
andes/app pull request #2845
Opened 2023-04-03 15:29 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-528

### Funcionalidad desarrollada 

1. Agrega controles para restringit las acciones sobre una indiacion al dia actual.

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2023-04-03 16:05 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8673](http://condorpiedra.andes.gob.ar:85/8673/mochawesome.html)
CYPRESS RUN: [7848](https://dashboard.cypress.io/projects/xr7gft/runs/7848/specs)
TEST START: 2023-04-03T16:05:07.521Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-04-18 12:22 UTC, MarianoCampetella requested changes

2023-04-18 12:22 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
> +        return a;
Creo que esto te habrá quedado cuando hicistes algún debugger!

2023-05-02 17:36 UTC, negro89 commented on src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
> +        return a;
jaja! que colgado, era para el debuguer que no me lo tomaba. Corregido!

2023-05-04 17:36 UTC, MarianoCampetella approved these changes

2023-05-05 12:22 UTC, silviroa approved these changes

2023-05-05 12:42 UTC, merged