IN - Control en registro de una internacion
andes/app pull request #2849
Opened 2023-04-13 17:32 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-533

### Funcionalidad desarrollada 

1. Verifica si existe una internación futura en la cama que se esta ingresando un paciente. De ser asi, se da aviso de la fecha y hora de la misma.

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2023-04-13 18:00 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8702](http://condorpiedra.andes.gob.ar:85/8702/mochawesome.html)
CYPRESS RUN: [7877](https://dashboard.cypress.io/projects/xr7gft/runs/7877/specs)
TEST START: 2023-04-13T17:58:56.220Z
TOTAL: 366
SUCCESS: 357
FAIL: 8
SKIPPED: 1

2023-04-13 18:26 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8704](http://condorpiedra.andes.gob.ar:85/8704/mochawesome.html)
CYPRESS RUN: [7879](https://dashboard.cypress.io/projects/xr7gft/runs/7879/specs)
TEST START: 2023-04-13T18:25:59.253Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-04-13 19:09 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8707](http://condorpiedra.andes.gob.ar:85/8707/mochawesome.html)
CYPRESS RUN: [7882](https://dashboard.cypress.io/projects/xr7gft/runs/7882/specs)
TEST START: 2023-04-13T19:08:59.696Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-04-19 14:20 UTC, MarianoCampetella approved these changes

2023-05-19 16:53 UTC, MCele requested changes

2023-05-19 16:53 UTC, MCele commented on src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
> +                if (historial.length && historial[0].idInternacion && historial[0].idInternacion !== this.cama.idInternacion) {
Cuando se intenta registrar una internación, si el próximo movimiento que sigue es un ingreso o cambio de cama funciona bien. El problema está cuando el movimiento es un bloqueo o préstamo de cama, en esos casos no se guarda un idInternacion, por lo que no se visualiza el mensaje.

2023-06-02 18:19 UTC, MCele approved these changes

2023-06-02 18:45 UTC, merged