IN - Fijar botones al cargar una indicación
andes/app pull request #2850
Opened 2023-04-18 13:56 UTC by aldoEMatamala

### Requerimiento 
https://proyectos.andes.gob.ar/browse/IN-526
 

### Funcionalidad desarrollada 

1.  Se creó la clase '.title-fixed' para inmovilizar el Título y los botones del encabezado cuando se agrega una nueva indicación.
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [x] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2023-04-19 12:24 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8723](http://condorpiedra.andes.gob.ar:85/8723/mochawesome.html)
CYPRESS RUN: [7898](https://dashboard.cypress.io/projects/xr7gft/runs/7898/specs)
TEST START: 2023-04-19T12:22:06.267Z
TOTAL: 263
SUCCESS: 244
FAIL: 17
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-04-19 13:46 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8727](http://condorpiedra.andes.gob.ar:85/8727/mochawesome.html)
CYPRESS RUN: [7902](https://dashboard.cypress.io/projects/xr7gft/runs/7902/specs)
TEST START: 2023-04-19T13:46:29.941Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-04-19 18:07 UTC, MarianoCampetella requested changes

2023-04-19 18:07 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.html
> +<plex-title [titulo]="selectedConcept ? selectedConcept.term : nombreSeccion" size="md" class="title-fixed">
Si al plex-title le agregas un "justify" queda de 10. 
Esto va a ser que el fondo del titulo no quede transparente y se transponga con los contenidos del sidebar.

2023-04-20 14:06 UTC, aldoEMatamala commented on src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.html
> +<plex-title [titulo]="selectedConcept ? selectedConcept.term : nombreSeccion" size="md" class="title-fixed">
gracias! modificadoo

2023-04-25 11:17 UTC, MarianoCampetella approved these changes

2023-05-02 15:48 UTC, negro89 approved these changes

2023-05-02 16:59 UTC, merged