IN- Control anular internación
andes/app pull request #2853
Opened 2023-04-24 09:22 UTC by aldoEMatamala

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-532
 

### Funcionalidad desarrollada 

1. Se cambia la leyenda al querer eliminar una internación de forma completa.

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [x] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2023-05-05 13:08 UTC, MarianoCampetella requested changes

2023-05-05 13:08 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
> +        }
Estas sentencias se pueden simplificar mediante un operador condicional ternario:
const msjDeshacer = (completo) ? 'Si el paciente tiene...' : 'Esta acción deshace...';

2023-05-05 13:08 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
> +        }
Lo mismo que el mensaje anterior.

2023-05-05 13:10 UTC, MarianoCampetella commented
También se subieron cambios que forman parte de otro pr, o que al menos en esta tarea no fueron especificados.
- nueva-indicacion.component.html
- plan-indicaciones.scss

Y ya que estamos resolver los conflictos!

2023-05-11 13:35 UTC, AgosLizzi approved these changes
Aldo, solo como una sugerencia a futuro. Entiendo que en la tarea este explicito el mensaje a agregar, pero es sumamente largo para un modal. Además que presenta inconsistencias como doble pregunta "¿Quiere deshacer esta internación?" " ¿Desea continuar con la anulación?"
Me parece que el armado del texto no es el correcto sumado a que se debería modificar la formulación de la pregunta.

2023-05-29 17:16 UTC, ma7payne approved these changes

2023-06-07 14:23 UTC, MarianoCampetella commented
Al deshacer una internación entera o el ultimo movimiento, el mensaje del modal es siempre el mismo. Trataría de cambiar el contenido del mismo para distinguir la acción que voy a realizar. 
![image](https://github.com/andes/app/assets/65697028/61091aa0-b4b7-4d35-bf55-e956291fe920)

Podria quedar algo asi: 
- Esta acción deshace la internación, es decir...
- Esta acción deshace el ultimo movimiento, es decir...

2023-07-14 18:32 UTC, aldoEMatamala commented
> Al deshacer una internación entera o el ultimo movimiento, el mensaje del modal es siempre el mismo. Trataría de cambiar el contenido del mismo para distinguir la acción que voy a realizar. ![image](https://user-images.githubusercontent.com/65697028/244097185-61091aa0-b4b7-4d35-bf55-e956291fe920.png)
> 
> Podria quedar algo asi:
> 
> * Esta acción deshace la internación, es decir...
> * Esta acción deshace el ultimo movimiento, es decir...

Buenas campe! gracias por las observaciones, luego de un consenso con cele y valen la leyenda quedó en :
![image](https://github.com/andes/app/assets/123381977/a5cee504-275c-447e-b54f-25c314f89567)
![image](https://github.com/andes/app/assets/123381977/c3888b78-1c1b-4c29-9fef-1337b81ab35b)

2023-07-14 18:33 UTC, aldoEMatamala commented
> Aldo, solo como una sugerencia a futuro. Entiendo que en la tarea este explicito el mensaje a agregar, pero es sumamente largo para un modal. Además que presenta inconsistencias como doble pregunta "¿Quiere deshacer esta internación?" " ¿Desea continuar con la anulación?" Me parece que el armado del texto no es el correcto sumado a que se debería modificar la formulación de la pregunta.

Buenas agos! gracias por la sugerencia, luego de un consenso con cele y valen los mensajes quedaron en : 
![image](https://github.com/andes/app/assets/123381977/a5cee504-275c-447e-b54f-25c314f89567)
![image](https://github.com/andes/app/assets/123381977/c3888b78-1c1b-4c29-9fef-1337b81ab35b)

2023-07-14 18:54 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9210](http://condorpiedra.andes.gob.ar:85/9210/mochawesome.html)
CYPRESS RUN: [8356](https://dashboard.cypress.io/projects/xr7gft/runs/8356/specs)
TEST START: 2023-07-14T18:53:18.835Z
TOTAL: 381
SUCCESS: 363
FAIL: 17
SKIPPED: 1

2023-07-14 19:35 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9211](http://condorpiedra.andes.gob.ar:85/9211/mochawesome.html)
CYPRESS RUN: [8357](https://dashboard.cypress.io/projects/xr7gft/runs/8357/specs)
TEST START: 2023-07-14T19:34:41.603Z
TOTAL: 403
SUCCESS: 392
FAIL: 9
SKIPPED: 2

2023-07-14 19:54 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9212](http://condorpiedra.andes.gob.ar:85/9212/mochawesome.html)
CYPRESS RUN: [8358](https://dashboard.cypress.io/projects/xr7gft/runs/8358/specs)
TEST START: 2023-07-14T19:53:25.067Z
TOTAL: 353
SUCCESS: 334
FAIL: 17
SKIPPED: 2

2023-07-14 20:23 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9213](http://condorpiedra.andes.gob.ar:85/9213/mochawesome.html)
CYPRESS RUN: [8359](https://dashboard.cypress.io/projects/xr7gft/runs/8359/specs)
TEST START: 2023-07-14T20:22:13.799Z
TOTAL: 320
SUCCESS: 296
FAIL: 22
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-07-14 20:36 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9214](http://condorpiedra.andes.gob.ar:85/9214/mochawesome.html)
CYPRESS RUN: [8360](https://dashboard.cypress.io/projects/xr7gft/runs/8360/specs)
TEST START: 2023-07-14T20:36:32.966Z
TOTAL: 403
SUCCESS: 392
FAIL: 9
SKIPPED: 2

2023-07-14 21:31 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9215](http://condorpiedra.andes.gob.ar:85/9215/mochawesome.html)
CYPRESS RUN: [8361](https://dashboard.cypress.io/projects/xr7gft/runs/8361/specs)
TEST START: 2023-07-14T21:29:51.555Z
TOTAL: 398
SUCCESS: 383
FAIL: 13
SKIPPED: 2

2023-07-16 19:56 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9218](http://condorpiedra.andes.gob.ar:85/9218/mochawesome.html)
CYPRESS RUN: [8364](https://dashboard.cypress.io/projects/xr7gft/runs/8364/specs)
TEST START: 2023-07-16T19:55:50.836Z
TOTAL: 403
SUCCESS: 392
FAIL: 9
SKIPPED: 2

2023-07-17 15:55 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [9221](http://condorpiedra.andes.gob.ar:85/9221/mochawesome.html)
CYPRESS RUN: [8367](https://dashboard.cypress.io/projects/xr7gft/runs/8367/specs)
TEST START: 2023-07-17T15:55:38.966Z
TOTAL: 403
SUCCESS: 391
FAIL: 10
SKIPPED: 2

2023-07-18 12:09 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9226](http://condorpiedra.andes.gob.ar:85/9226/mochawesome.html)
CYPRESS RUN: [8372](https://dashboard.cypress.io/projects/xr7gft/runs/8372/specs)
TEST START: 2023-07-18T12:09:20.405Z
TOTAL: 380
SUCCESS: 367
FAIL: 11
SKIPPED: 2

2023-07-19 12:12 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9230](http://condorpiedra.andes.gob.ar:85/9230/mochawesome.html)
CYPRESS RUN: [8376](https://dashboard.cypress.io/projects/xr7gft/runs/8376/specs)
TEST START: 2023-07-19T12:12:31.997Z
TOTAL: 403
SUCCESS: 392
FAIL: 9
SKIPPED: 2

2023-07-20 14:17 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9234](http://condorpiedra.andes.gob.ar:85/9234/mochawesome.html)
CYPRESS RUN: [8380](https://dashboard.cypress.io/projects/xr7gft/runs/8380/specs)
TEST START: 2023-07-20T14:16:43.007Z
TOTAL: 403
SUCCESS: 390
FAIL: 11
SKIPPED: 2

2023-07-21 16:00 UTC, negro89 approved these changes

2023-07-21 16:03 UTC, negro89 commented
@aldoEMatamala  buena mejora! solo recordar que hay casos de test que modificar para que quede todo ok.

2023-07-24 13:34 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9247](http://condorpiedra.andes.gob.ar:85/9247/mochawesome.html)
CYPRESS RUN: [8393](https://dashboard.cypress.io/projects/xr7gft/runs/8393/specs)
TEST START: 2023-07-24T13:34:34.182Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-07-24 15:02 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9248](http://condorpiedra.andes.gob.ar:85/9248/mochawesome.html)
CYPRESS RUN: [8394](https://dashboard.cypress.io/projects/xr7gft/runs/8394/specs)
TEST START: 2023-07-24T15:02:31.227Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-07-24 17:36 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9252](http://condorpiedra.andes.gob.ar:85/9252/mochawesome.html)
CYPRESS RUN: [8398](https://dashboard.cypress.io/projects/xr7gft/runs/8398/specs)
TEST START: 2023-07-24T17:35:19.965Z
TOTAL: 325
SUCCESS: 313
FAIL: 10
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-07-25 14:52 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9261](http://condorpiedra.andes.gob.ar:85/9261/mochawesome.html)
CYPRESS RUN: [8407](https://dashboard.cypress.io/projects/xr7gft/runs/8407/specs)
TEST START: 2023-07-25T14:52:28.047Z
TOTAL: 404
SUCCESS: 400
FAIL: 2
SKIPPED: 2

2023-07-25 15:30 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9263](http://condorpiedra.andes.gob.ar:85/9263/mochawesome.html)
CYPRESS RUN: [8409](https://dashboard.cypress.io/projects/xr7gft/runs/8409/specs)
TEST START: 2023-07-25T15:29:57.387Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-07-25 15:58 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9264](http://condorpiedra.andes.gob.ar:85/9264/mochawesome.html)
CYPRESS RUN: [8410](https://dashboard.cypress.io/projects/xr7gft/runs/8410/specs)
TEST START: 2023-07-25T15:58:18.833Z
TOTAL: 404
SUCCESS: 400
FAIL: 2
SKIPPED: 2

2023-07-25 18:18 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9266](http://condorpiedra.andes.gob.ar:85/9266/mochawesome.html)
CYPRESS RUN: [8412](https://dashboard.cypress.io/projects/xr7gft/runs/8412/specs)
TEST START: 2023-07-25T18:18:01.308Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-07-25 18:19 UTC, aldoEMatamala commented
> @aldoEMatamala buena mejora! solo recordar que hay casos de test que modificar para que quede todo ok.

ok! subido pr de test

2023-07-25 18:19 UTC, aldoEMatamala commented
> > @aldoEMatamala buena mejora! solo recordar que hay casos de test que modificar para que quede todo ok.
> 
> ok! gracias, queda subido pr de test

2023-08-16 13:46 UTC, ma7payne approved these changes

2023-08-16 13:56 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9436](http://condorpiedra.andes.gob.ar:85/9436/mochawesome.html)
CYPRESS RUN: [8573](https://dashboard.cypress.io/projects/xr7gft/runs/8573/specs)
TEST START: 2023-08-16T13:56:29.425Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-08-16 14:10 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9437](http://condorpiedra.andes.gob.ar:85/9437/mochawesome.html)
CYPRESS RUN: [8574](https://dashboard.cypress.io/projects/xr7gft/runs/8574/specs)
TEST START: 2023-08-16T14:09:17.101Z
TOTAL: 361
SUCCESS: 350
FAIL: 9
SKIPPED: 2

2023-08-16 14:37 UTC, JuanIRamirez approved these changes
Revisado OK

2023-08-16 16:29 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9448](http://condorpiedra.andes.gob.ar:85/9448/mochawesome.html)
CYPRESS RUN: [8579](https://dashboard.cypress.io/projects/xr7gft/runs/8579/specs)
TEST START: 2023-08-16T16:29:46.832Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

2023-08-16 18:10 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9453](http://condorpiedra.andes.gob.ar:85/9453/mochawesome.html)
CYPRESS RUN: [8583](https://dashboard.cypress.io/projects/xr7gft/runs/8583/specs)
TEST START: 2023-08-16T18:10:34.258Z
TOTAL: 353
SUCCESS: 349
FAIL: 2
SKIPPED: 2

2023-08-17 11:31 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9458](http://condorpiedra.andes.gob.ar:85/9458/mochawesome.html)
CYPRESS RUN: [8588](https://dashboard.cypress.io/projects/xr7gft/runs/8588/specs)
TEST START: 2023-08-17T11:31:01.380Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-08-18 14:42 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9474](http://condorpiedra.andes.gob.ar:85/9474/mochawesome.html)
CYPRESS RUN: [8601](https://dashboard.cypress.io/projects/xr7gft/runs/8601/specs)
TEST START: 2023-08-18T14:40:27.813Z
TOTAL: 365
SUCCESS: 356
FAIL: 7
SKIPPED: 2

2023-08-18 14:54 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9475](http://condorpiedra.andes.gob.ar:85/9475/mochawesome.html)
CYPRESS RUN: [8602](https://dashboard.cypress.io/projects/xr7gft/runs/8602/specs)
TEST START: 2023-08-18T14:52:50.991Z
TOTAL: 358
SUCCESS: 345
FAIL: 11
SKIPPED: 2

2023-08-18 15:39 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9476](http://condorpiedra.andes.gob.ar:85/9476/mochawesome.html)
CYPRESS RUN: [8603](https://dashboard.cypress.io/projects/xr7gft/runs/8603/specs)
TEST START: 2023-08-18T15:38:58.999Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-08-18 16:24 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9477](http://condorpiedra.andes.gob.ar:85/9477/mochawesome.html)
CYPRESS RUN: [8604](https://dashboard.cypress.io/projects/xr7gft/runs/8604/specs)
TEST START: 2023-08-18T16:23:55.183Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-08-18 16:52 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9478](http://condorpiedra.andes.gob.ar:85/9478/mochawesome.html)
CYPRESS RUN: [8605](https://dashboard.cypress.io/projects/xr7gft/runs/8605/specs)
TEST START: 2023-08-18T16:51:52.463Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-08-22 12:20 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9485](http://condorpiedra.andes.gob.ar:85/9485/mochawesome.html)
CYPRESS RUN: [8612](https://dashboard.cypress.io/projects/xr7gft/runs/8612/specs)
TEST START: 2023-08-22T12:19:58.339Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-08-22 12:47 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9487](http://condorpiedra.andes.gob.ar:85/9487/mochawesome.html)
CYPRESS RUN: [8614](https://dashboard.cypress.io/projects/xr7gft/runs/8614/specs)
TEST START: 2023-08-22T12:46:44.882Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-08-22 13:16 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9489](http://condorpiedra.andes.gob.ar:85/9489/mochawesome.html)
CYPRESS RUN: [8616](https://dashboard.cypress.io/projects/xr7gft/runs/8616/specs)
TEST START: 2023-08-22T13:16:35.935Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-08-22 23:08 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9491](http://condorpiedra.andes.gob.ar:85/9491/mochawesome.html)
CYPRESS RUN: [8618](https://dashboard.cypress.io/projects/xr7gft/runs/8618/specs)
TEST START: 2023-08-22T23:07:15.238Z
TOTAL: 371
SUCCESS: 363
FAIL: 6
SKIPPED: 2

2023-08-23 11:46 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [9493](http://condorpiedra.andes.gob.ar:85/9493/mochawesome.html)
CYPRESS RUN: [8620](https://dashboard.cypress.io/projects/xr7gft/runs/8620/specs)
TEST START: 2023-08-23T11:46:09.848Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-08-24 11:14 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9498](http://condorpiedra.andes.gob.ar:85/9498/mochawesome.html)
CYPRESS RUN: [8625](https://dashboard.cypress.io/projects/xr7gft/runs/8625/specs)
TEST START: 2023-08-24T11:14:11.315Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-08-29 13:50 UTC, merged