CIT - Implementa selector de financiadores
andes/app pull request #2854
Opened 2023-04-24 15:45 UTC by ma7payne

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-214

### Funcionalidad desarrollada 

1. Implementación de un componente reutilizable para las obras sociales o prepagas del paciente
2. El selector manual para "otras" ahora incluye no solo las Obras Sociales (OS) sino también todas las prepagas disponibles. Se excluyen las OS que el paciente ya posee.
3. Se agrega el componente en la pantalla -Dar Turno- en ventanilla de citas.
4. Se reemplaza el componente en la solapa -Turnos- en ventanilla de citas.
5. Se reemplaza el componente al seleccionar turno, para prestaciones iniciadas, en -Buscador de Turnos-.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

https://proyectos.andes.gob.ar/browse/MPI-403
- [x] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2023-05-05 15:03 UTC, MarianoCampetella commented
Cuando agrego un sobreturno me sigue saliendo igual a como estaba antes. 
![image](https://user-images.githubusercontent.com/65697028/236484600-a8d7bd8a-adad-4ebd-a498-38c68a0ab01d.png)

Otra cosa a corregir es en el buscador de turnos y prestaciones. Cuando selecciono un turno cuyo paciente tiene obra social me sale el select como se pide en la tarea. Pero cuando selecciono un item del listado con obra social SUMAR y luego selecciono otro donde tiene cualquier obra social distinta a SUMAR ocurre lo que se ve en la imagen. 
![image](https://user-images.githubusercontent.com/65697028/236495377-9d5cd4e7-bbc7-4ded-a8b8-c966f39152c5.png)

2023-05-16 12:02 UTC, ma7payne commented
@MarianoCampetella Están listos los cambios para volver a chequear el selector, de no poder verlo, revisar la cache del navegador. El PR esta al día y sin conflictos, quedo atento.

2023-05-16 12:13 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [8899](http://condorpiedra.andes.gob.ar:85/8899/mochawesome.html)
CYPRESS RUN: [8064](https://dashboard.cypress.io/projects/xr7gft/runs/8064/specs)
TEST START: 2023-05-16T12:11:51.976Z
TOTAL: 375
SUCCESS: 363
FAIL: 10
SKIPPED: 2

2023-05-16 12:31 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [8900](http://condorpiedra.andes.gob.ar:85/8900/mochawesome.html)
CYPRESS RUN: [8065](https://dashboard.cypress.io/projects/xr7gft/runs/8065/specs)
TEST START: 2023-05-16T12:31:04.079Z
TOTAL: 406
SUCCESS: 401
FAIL: 3
SKIPPED: 2

2023-05-16 12:59 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [8902](http://condorpiedra.andes.gob.ar:85/8902/mochawesome.html)
CYPRESS RUN: [8067](https://dashboard.cypress.io/projects/xr7gft/runs/8067/specs)
TEST START: 2023-05-16T12:59:01.589Z
TOTAL: 406
SUCCESS: 401
FAIL: 3
SKIPPED: 2

2023-05-17 12:15 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [8910](http://condorpiedra.andes.gob.ar:85/8910/mochawesome.html)
CYPRESS RUN: [8075](https://dashboard.cypress.io/projects/xr7gft/runs/8075/specs)
TEST START: 2023-05-17T12:14:55.589Z
TOTAL: 406
SUCCESS: 401
FAIL: 3
SKIPPED: 2

2023-06-01 15:57 UTC, AgosLizzi requested changes
Mati, en muchos paciente observé esto. Parece que hubiera un problema en la interlinea.
![Screenshot_1](https://github.com/andes/app/assets/72876985/1745872c-8180-4803-9b6e-b5b4a39fd71e)
![Screenshot_2](https://github.com/andes/app/assets/72876985/74099a5e-4a3c-4392-9d5c-1beca85dd0d5)

 
Se podra resolver?
_*Revisar por fa en todas las pantallas que esta implementado_

También observe esto + un error en la consola.
![Screenshot_3](https://github.com/andes/app/assets/72876985/1e666051-9105-4f21-81e5-dccb2b5a59ea)
![Screenshot_4](https://github.com/andes/app/assets/72876985/ef31a1a0-9e57-4f8e-99e6-5fd65a285cea)

2023-07-04 14:46 UTC, ma7payne commented
> Cuando agrego un sobreturno me sigue saliendo igual a como estaba antes. ![image](https://user-images.githubusercontent.com/65697028/236484600-a8d7bd8a-adad-4ebd-a498-38c68a0ab01d.png)
> 
> Otra cosa a corregir es en el buscador de turnos y prestaciones. Cuando selecciono un turno cuyo paciente tiene obra social me sale el select como se pide en la tarea. Pero cuando selecciono un item del listado con obra social SUMAR y luego selecciono otro donde tiene cualquier obra social distinta a SUMAR ocurre lo que se ve en la imagen, es decir, no sale el select como corresponde y queda la leyenda de SUMAR solamente ![image](https://user-images.githubusercontent.com/65697028/236495377-9d5cd4e7-bbc7-4ded-a8b8-c966f39152c5.png)
> 
> Ya que estamos aprovechar a resolver los conflictos y correr los test!

@MarianoCampetella listo el cambio en la opción se SUMAR, deberías ver las otras obras sociales y prepagas disponibles. Para dar sobreturno tenes que poder ver la opción en el sidebar, la pantalla antigua ya no esta en uso. En caso de no verla probablemente sea algún tema de cache de datos.

2023-07-04 14:48 UTC, ma7payne commented
> Mati, en muchos paciente observé esto. Parece que hubiera un problema en la interlinea. ![Screenshot_1](https://user-images.githubusercontent.com/72876985/242657105-1745872c-8180-4803-9b6e-b5b4a39fd71e.png) ![Screenshot_2](https://user-images.githubusercontent.com/72876985/242657790-74099a5e-4a3c-4392-9d5c-1beca85dd0d5.png)
> 
> Se podra resolver? _*Revisar por fa en todas las pantallas que esta implementado_
> 
> También observe esto + un error en la consola. ![Screenshot_3](https://user-images.githubusercontent.com/72876985/242866355-1e666051-9105-4f21-81e5-dccb2b5a59ea.png) ![Screenshot_4](https://user-images.githubusercontent.com/72876985/242866496-ef31a1a0-9e57-4f8e-99e6-5fd65a285cea.png)

@AgosLizzi el error en consola fue identificado, ya no deberías poder verlo. En cuanto al interlineado, esta contemplado en la próxima actualización de Plex.

Quedo atento!

2023-07-04 15:13 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9163](http://condorpiedra.andes.gob.ar:85/9163/mochawesome.html)
CYPRESS RUN: [8310](https://dashboard.cypress.io/projects/xr7gft/runs/8310/specs)
TEST START: 2023-07-04T15:13:14.735Z
TOTAL: 395
SUCCESS: 388
FAIL: 5
SKIPPED: 2

2023-07-04 18:37 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9167](http://condorpiedra.andes.gob.ar:85/9167/mochawesome.html)
CYPRESS RUN: [8314](https://dashboard.cypress.io/projects/xr7gft/runs/8314/specs)
TEST START: 2023-07-04T18:36:52.814Z
TOTAL: 403
SUCCESS: 398
FAIL: 3
SKIPPED: 2

2023-07-04 19:48 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9169](http://condorpiedra.andes.gob.ar:85/9169/mochawesome.html)
CYPRESS RUN: [8316](https://dashboard.cypress.io/projects/xr7gft/runs/8316/specs)
TEST START: 2023-07-04T19:48:40.397Z
TOTAL: 395
SUCCESS: 390
FAIL: 3
SKIPPED: 2

2023-07-13 12:29 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9206](http://condorpiedra.andes.gob.ar:85/9206/mochawesome.html)
CYPRESS RUN: [8352](https://dashboard.cypress.io/projects/xr7gft/runs/8352/specs)
TEST START: 2023-07-13T12:27:53.598Z
TOTAL: 95
SUCCESS: 0
FAIL: 95
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-07-13 15:48 UTC, MarianoCampetella requested changes

2023-07-13 15:48 UTC, MarianoCampetella commented on src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
> +                            </div> -->
Eliminar código comentado!

2023-07-13 15:48 UTC, MarianoCampetella commented on src/app/components/turnos/dar-turnos/seleccionar-financiador.component.ts
> +    public selectorFinanciadores: any[] = [];
Usar las interfaces necesarias como en el caso de obrasSociales con IObraSocial

2023-07-13 15:48 UTC, MarianoCampetella commented on src/app/components/turnos/dar-turnos/seleccionar-financiador.component.ts
> +            this.selectorObrasSociales = this.obrasSociales.map((os: any) => ({ id: os.nombre || os.financiador, label: os.nombre || os.financiador }));
remplazar por .map((os: IObraSocial)

2023-07-26 17:49 UTC, AgosLizzi requested changes
Mati, cuando me voy al caso que seleccione en la anterior corrección (adjunto imagen), en una primera instancia aparece para seleccionar una obra social y al instante desaparece, para que aparezca el select de selecionar opción. Por ahora es con el unico paciente que me sucedio. Te dejo video.
- ![242866355-1e666051-9105-4f21-81e5-dccb2b5a59ea](https://github.com/andes/app/assets/72876985/e78fd685-def5-462f-8951-a1add2ecff11)

https://www.loom.com/share/fd66aa04754d4cb6b202ab08092cddba

2023-08-16 13:23 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9435](http://condorpiedra.andes.gob.ar:85/9435/mochawesome.html)
CYPRESS RUN: [8572](https://dashboard.cypress.io/projects/xr7gft/runs/8572/specs)
TEST START: 2023-08-16T13:22:58.296Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

2023-08-24 11:37 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9499](http://condorpiedra.andes.gob.ar:85/9499/mochawesome.html)
CYPRESS RUN: [8626](https://dashboard.cypress.io/projects/xr7gft/runs/8626/specs)
TEST START: 2023-08-24T11:36:17.846Z
TOTAL: 263
SUCCESS: 245
FAIL: 16
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-09-01 14:40 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9528](http://condorpiedra.andes.gob.ar:85/9528/mochawesome.html)
CYPRESS RUN: [8655](https://dashboard.cypress.io/projects/xr7gft/runs/8655/specs)
TEST START: 2023-09-01T14:40:17.032Z
TOTAL: 403
SUCCESS: 398
FAIL: 3
SKIPPED: 2

2023-09-01 15:41 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9530](http://condorpiedra.andes.gob.ar:85/9530/mochawesome.html)
CYPRESS RUN: [8657](https://dashboard.cypress.io/projects/xr7gft/runs/8657/specs)
TEST START: 2023-09-01T15:40:19.718Z
TOTAL: 337
SUCCESS: 317
FAIL: 19
SKIPPED: 1

2023-09-04 11:36 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9537](http://condorpiedra.andes.gob.ar:85/9537/mochawesome.html)
CYPRESS RUN: [8664](https://dashboard.cypress.io/projects/xr7gft/runs/8664/specs)
TEST START: 2023-09-04T11:35:25.662Z
TOTAL: 371
SUCCESS: 363
FAIL: 6
SKIPPED: 2

2023-09-04 12:13 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9539](http://condorpiedra.andes.gob.ar:85/9539/mochawesome.html)
CYPRESS RUN: [8666](https://dashboard.cypress.io/projects/xr7gft/runs/8666/specs)
TEST START: 2023-09-04T12:13:45.328Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

2023-09-05 14:29 UTC, AgosLizzi requested changes
Mati, te dejo comentado lo que hablamos por slack. 

El select de prepaga no carga datos, me sucede con varios pacientes. te dejo con los que probé 
- NAAB, Juan pablo 
- O CONNOR, Nelson Alejandro
- Obadilla, Ercira

https://www.loom.com/share/bd8dfd5d111f4e459aabda5e68a40f73

Se suma este error 
![image](https://github.com/andes/app/assets/72876985/8521d5c8-e45f-4ec9-9e3a-ebe80e04e579)

2023-09-05 15:22 UTC, ma7payne commented
> 

Agos, no logro replicar el error.. posiblemente ha quedado alguna cache de datos al deployar porque el label "Prepaga" ya no existe en la tarea. De no ver eso quiere decir que no estas viendo los últimos cambios. Quedo atento!

2023-09-05 15:27 UTC, AgosLizzi approved these changes

2023-09-05 16:19 UTC, Fabio-Ramirez requested changes

2023-09-05 16:19 UTC, Fabio-Ramirez commented on src/app/components/turnos/punto-inicio/turnos-paciente.html
> +                                     *ngIf="financiador?.nombre !== 'SUMAR' && turno && turno.profesionales?.length && turno.estado !== 'suspendido' && turno.paciente.documento">
Se sugiere utilizar un metodo en el componente.ts para evaluar las múltiples condiciones y asi evitar cargar el html. Además utilizar el signo ? en la variable turno para reducir código.

2023-09-05 16:19 UTC, Fabio-Ramirez commented on src/app/components/turnos/punto-inicio/turnos-paciente.html
> +                                <plex-button *ngIf="financiador?.nombre !== 'SUMAR' && turno && turno.profesionales?.length > 0 && turno.paciente.documento"
Casi similar a la sugerencia anterior.

2023-09-28 17:02 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9701](http://condorpiedra.andes.gob.ar:85/9701/mochawesome.html)
CYPRESS RUN: [8813](https://dashboard.cypress.io/projects/xr7gft/runs/8813/specs)
TEST START: 2023-09-28T17:01:52.783Z
TOTAL: 403
SUCCESS: 398
FAIL: 3
SKIPPED: 2

2023-09-28 17:24 UTC, ma7payne commented
> CIT-214

Listo los cambios para solucionar el error y la sugerencia del titulo en el selector cuando no hay SUMAR o prepagas.

2023-09-29 13:19 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9703](http://condorpiedra.andes.gob.ar:85/9703/mochawesome.html)
CYPRESS RUN: [8815](https://dashboard.cypress.io/projects/xr7gft/runs/8815/specs)
TEST START: 2023-09-29T13:19:11.758Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-09-29 13:39 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9704](http://condorpiedra.andes.gob.ar:85/9704/mochawesome.html)
CYPRESS RUN: [8816](https://dashboard.cypress.io/projects/xr7gft/runs/8816/specs)
TEST START: 2023-09-29T13:39:29.629Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-12-05 19:29 UTC, MCele commented
Actualizar PR

2023-12-19 16:31 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10072](http://condorpiedra.andes.gob.ar:85/10072/mochawesome.html)
CYPRESS RUN: [9180](https://dashboard.cypress.io/projects/xr7gft/runs/9180/specs)
TEST START: 2023-12-19T16:30:33.335Z
TOTAL: 96
SUCCESS: 0
FAIL: 96
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-12-19 18:02 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10077](http://condorpiedra.andes.gob.ar:85/10077/mochawesome.html)
CYPRESS RUN: [9185](https://dashboard.cypress.io/projects/xr7gft/runs/9185/specs)
TEST START: 2023-12-19T18:02:02.920Z
TOTAL: 405
SUCCESS: 402
FAIL: 1
SKIPPED: 2

2023-12-19 18:22 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10079](http://condorpiedra.andes.gob.ar:85/10079/mochawesome.html)
CYPRESS RUN: [9187](https://dashboard.cypress.io/projects/xr7gft/runs/9187/specs)
TEST START: 2023-12-19T18:22:21.137Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-12-20 15:10 UTC, Fabio-Ramirez approved these changes

2023-12-21 18:13 UTC, MCele commented
Cambios pedido en api

2023-12-22 15:20 UTC, MCele approved these changes

2023-12-22 15:25 UTC, MarianoCampetella approved these changes

2023-12-22 15:26 UTC, merged