BI - Permisos por zona
andes/app pull request #2855
Opened 2023-04-26 14:44 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/BI-135

### Funcionalidad desarrollada 

1. Filtra select de zonas y organizaciones según permisos de usuario.

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2023-04-26 15:01 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8764](http://condorpiedra.andes.gob.ar:85/8764/mochawesome.html)
CYPRESS RUN: [7937](https://dashboard.cypress.io/projects/xr7gft/runs/7937/specs)
TEST START: 2023-04-26T15:00:38.374Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-04-26 15:46 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8767](http://condorpiedra.andes.gob.ar:85/8767/mochawesome.html)
CYPRESS RUN: [7939](https://dashboard.cypress.io/projects/xr7gft/runs/7939/specs)
TEST START: 2023-04-26T15:46:35.892Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-05-05 18:27 UTC, MarianoCampetella commented
Solamente va a ser necesario tener que arreglar el test!
![image](https://user-images.githubusercontent.com/65697028/236538810-0de6b05b-6d5a-4302-a374-a01acb24bffc.png)

2023-05-29 18:24 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8960](http://condorpiedra.andes.gob.ar:85/8960/mochawesome.html)
CYPRESS RUN: [8123](https://dashboard.cypress.io/projects/xr7gft/runs/8123/specs)
TEST START: 2023-05-29T18:03:03.802Z
TOTAL: 262
SUCCESS: 234
FAIL: 26
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-05-29 20:03 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8962](http://condorpiedra.andes.gob.ar:85/8962/mochawesome.html)
CYPRESS RUN: [8125](https://dashboard.cypress.io/projects/xr7gft/runs/8125/specs)
TEST START: 2023-05-29T20:02:54.955Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-06-06 17:07 UTC, silviroa requested changes
Revisar el caso de tener permisos para algunas zonas en particular. Se pisa el argumento y no se muestra el select

2023-06-14 12:43 UTC, negro89 commented
@silviroa corregidooo

2023-08-16 15:40 UTC, merged