PERINATAL - Revisar filtros y scroll listado perinatal
andes/app pull request #2857
Opened 2023-04-28 16:09 UTC by maring0019

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/PER-82
### Funcionalidad desarrollada 

1. Se corrigen parámetros fecha 
2. Modificar query listado-perinatal de la colección queries.
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [X] Si
- [ ] No

Modificar query _listado-perinatal_ de la colección _queries_.
El primer match quedaría de esta forma. Se cambia  "controles.fechaControl" por “fecha”.

            "!match" : {
                "fecha" : {
                    "!gte" : ISODate('2021-04-01 00:00:00.000-03:00'),
                    "!lte" : ISODate('2021-05-30 00:00:00.000-03:00'),
                }
            }
       
### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2023-04-28 17:24 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8801](http://condorpiedra.andes.gob.ar:85/8801/mochawesome.html)
CYPRESS RUN: [7971](https://dashboard.cypress.io/projects/xr7gft/runs/7971/specs)
TEST START: 2023-04-28T17:23:08.023Z
TOTAL: 358
SUCCESS: 348
FAIL: 8
SKIPPED: 2

2023-04-28 18:29 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8802](http://condorpiedra.andes.gob.ar:85/8802/mochawesome.html)
CYPRESS RUN: [7972](https://dashboard.cypress.io/projects/xr7gft/runs/7972/specs)
TEST START: 2023-04-28T18:29:20.896Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-05-12 12:18 UTC, MarianoCampetella commented
Si bien los filtros funcionan bien, cuando hago la descarga del csv tanto en el módulo de perinatal como en bi-queries y agrego la fecha desde: 01/02/23 y la fecha hasta: 14/02/23 me descarga la siguiente cantidad de datos, los cuales no coinciden con los que se encuentran en la BD. 
![image](https://github.com/andes/app/assets/65697028/2ce8e7e4-81eb-4b64-b708-16c5b73d5786)

2023-05-15 16:22 UTC, MCele requested changes

2023-05-15 16:22 UTC, MCele commented on src/app/modules/perinatal/services/carnet-perinatal.service.ts
> +                params.fecha = this.queryDateParams(fechaDesde as Date, fechaHasta as Date);
Cuidado con esto:
 la _fecha_ es la fecha inicial en la que se iniciaron los controles de embarazo y "fechaControl" es la fecha de un control. 
 El objetivo del listado es poder filtrar por fechas de controles, no necesariamente tiene que ser la fecha de la columna "Fecha inicio" del listado. La tarea no pide que se modifique el objetivo de la query, si no que coincidan.
 Mismo comentario al intentar modificar: _"controles.fechaControl" por “fecha”._

2023-06-30 15:03 UTC, maring0019 commented on src/app/modules/perinatal/services/carnet-perinatal.service.ts
> +                params.fecha = this.queryDateParams(fechaDesde as Date, fechaHasta as Date);
Se han realizado cambios.

2023-06-30 15:05 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9140](http://condorpiedra.andes.gob.ar:85/9140/mochawesome.html)
CYPRESS RUN: [8287](https://dashboard.cypress.io/projects/xr7gft/runs/8287/specs)
TEST START: 2023-06-30T15:04:51.564Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

2023-06-30 15:27 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9142](http://condorpiedra.andes.gob.ar:85/9142/mochawesome.html)
CYPRESS RUN: [8289](https://dashboard.cypress.io/projects/xr7gft/runs/8289/specs)
TEST START: 2023-06-30T15:25:56.402Z
TOTAL: 378
SUCCESS: 367
FAIL: 9
SKIPPED: 2

2023-07-03 14:24 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9155](http://condorpiedra.andes.gob.ar:85/9155/mochawesome.html)
CYPRESS RUN: [8302](https://dashboard.cypress.io/projects/xr7gft/runs/8302/specs)
TEST START: 2023-07-03T14:23:41.196Z
TOTAL: 375
SUCCESS: 367
FAIL: 6
SKIPPED: 2

2023-07-03 15:26 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9157](http://condorpiedra.andes.gob.ar:85/9157/mochawesome.html)
CYPRESS RUN: [8304](https://dashboard.cypress.io/projects/xr7gft/runs/8304/specs)
TEST START: 2023-07-03T15:26:11.482Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-07-06 16:32 UTC, MCele requested changes
Dejo por escrito las correcciones planteadas:
1) Falta resolver problema de scroll infinito, porque sigue ocurriendo.
2) Filtros por fecha no siempre coinciden con la descarga csv.

2023-07-27 13:34 UTC, maring0019 commented
Se realizaron cambios. Para la descarga del CSV probar en local porque en demo no funciona.

2023-07-27 13:44 UTC, maring0019 commented
> Dejo por escrito las correcciones planteadas:
> 
> 1. Falta resolver problema de scroll infinito, porque sigue ocurriendo.
> 2. Filtros por fecha no siempre coinciden con la descarga csv.

Se realizaron cambios. Para la descarga del CSV probar en local porque en demo no funciona.

2023-07-27 13:53 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9291](http://condorpiedra.andes.gob.ar:85/9291/mochawesome.html)
CYPRESS RUN: [8436](https://dashboard.cypress.io/projects/xr7gft/runs/8436/specs)
TEST START: 2023-07-27T13:52:46.356Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-07-27 14:18 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9292](http://condorpiedra.andes.gob.ar:85/9292/mochawesome.html)
CYPRESS RUN: [8437](https://dashboard.cypress.io/projects/xr7gft/runs/8437/specs)
TEST START: 2023-07-27T14:18:25.640Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-08-16 15:56 UTC, JuanIRamirez requested changes
Sugiero aumentar el tiempo de rebote [debounce] en "fechaHasta" ej: "2000", porque cambia rapidamente la fecha ingresada por tener la propiedad [min]="fechaDesdeEntrada".

2023-09-05 14:53 UTC, Fabio-Ramirez requested changes

2023-09-05 14:53 UTC, Fabio-Ramirez commented on src/app/modules/perinatal/components/listado-perinatal.component.ts
> +    public fechaHastaEntrada2: any;
Seria optimo para las buenas practicas de programacion en TS, evitaria utilizar en any y le asignaria un tipo de dato a estas variables, por ejemplo, como en este caso se trata de fecha, utilizaria Date como tipo.  En el componente: fuera-agenda.component.ts hay un ejemplo.

2023-09-06 17:39 UTC, maring0019 commented on src/app/modules/perinatal/components/listado-perinatal.component.ts
> +    public fechaHastaEntrada2: any;
> Seria optimo para las buenas practicas de programacion en TS, evitaria utilizar en any y le asignaria un tipo de dato a estas variables, por ejemplo, como en este caso se trata de fecha, utilizaria Date como tipo. En el componente: fuera-agenda.component.ts hay un ejemplo.

Cambios hechos.

2023-10-03 13:54 UTC, Fabio-Ramirez reviewed
Mari estaria correcta las correciones de las observaciones que te realice.

2024-01-10 15:10 UTC, MarianoCampetella requested changes

2024-01-10 15:10 UTC, MarianoCampetella commented on src/app/modules/perinatal/components/listado-perinatal.component.ts
> +            this.fechaHastaEntrada2 = moment(this.fechaHastaEntrada).endOf('day');
Corregir esta linea ya que fechaHastaEntrada2 se encuentra declarada como Date y se le esta asignando un moment()

2024-08-20 15:51 UTC, closed without merging

2024-08-20 18:52 UTC, negro89 commented
Se reemplaza por https://github.com/andes/app/pull/3057