feat(HUDS): modifica muestra en info de prestación
andes/app pull request #2859
Opened 2023-05-02 14:48 UTC by ma7payne

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/HUDS-68
https://proyectos.andes.gob.ar/browse/HUDS-67

### Funcionalidad desarrollada 

1. Se complementa la información con "Unidad Organizativa".
2. Se prioriza la visualización de la información relevante para ámbitos de Internación y Ambulatorio sin despliegue. 
3. Se crea un botón para desplegar la información restante y evitar acumulación masiva en pantalla.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2023-05-02 14:49 UTC, ma7payne commented
@AgosLizzi te priorizo en la revisión para acomodar el botón con la información desplegable. Quedo atento!

2023-05-02 15:55 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [8814](http://condorpiedra.andes.gob.ar:85/8814/mochawesome.html)
CYPRESS RUN: [7984](https://dashboard.cypress.io/projects/xr7gft/runs/7984/specs)
TEST START: 2023-05-02T15:55:05.554Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-05-09 17:34 UTC, MarianoCampetella commented
A modo de pregunta, ¿Existirá alguna forma de poder alinear los elementos que se muestran en la segunda columna?
![image](https://github.com/andes/app/assets/65697028/f409151e-3006-4749-9f58-200d55d7f80b)

2023-05-09 17:44 UTC, ma7payne commented
> A modo de pregunta, ¿Existirá alguna forma de poder alinear los elementos que se muestran en la segunda columna? ![image](https://user-images.githubusercontent.com/65697028/237175034-f409151e-3006-4749-9f58-200d55d7f80b.png)
> 
> El resto esta todo bien!

Hola, hay un tema con esos elementos de PLEX que no dejan ordenar como uno quisiera los ítems. Chequeo para ver si puedo hacer un fix.

2023-05-10 13:13 UTC, AgosLizzi requested changes
Mati, no me parece el mejor lugar para colocar el botón de "mostrar más/ ocultar"
![2023-05-10 (2)](https://github.com/andes/app/assets/72876985/10e090d6-9657-46ec-88d6-d3f09b49799b)
![2023-05-10 (3)](https://github.com/andes/app/assets/72876985/7b69f9ee-ac39-4eaf-9f8a-53a156b3b943)

Si funciona como dropdown, lo agregaria sobre el plex title, y a lo sumo le daría tooltip de "mostrar más"

2023-05-16 13:16 UTC, negro89 approved these changes

2023-05-17 12:20 UTC, merged