CIT - Implementación mockup sobreturnos
andes/app pull request #2864
Opened 2023-05-09 19:02 UTC by aldoEMatamala

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-212
### Funcionalidad desarrollada 

1. Al presionar "agregar sobreturno" en "Gestor de agenda" se permite la búsqueda del paciente,carga, validación y guardado del sobreturno sin cambiar de instancia.

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [x] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2023-05-10 12:33 UTC, AgosLizzi requested changes
Aldito, vi un par de detalles:

1. Cuando estoy cargando un sobreturno y doy _cancelar_ al botón me lleva nuevamente al listado para elegir un paciente. Creo que si cancelamos la acción, la deberia cancelar por completo, no dar un paso hacia atras. Eso igualmente se podría evaluar.
2. Si realizo la misma acción que describo en el punto 1, y luego me voy a otra agenda del listado, me mantiene los datos del sobeturno de la agenda anterior.
3. Siguiendo con la misma acción del punto 1 , si cierro el sidebar y voy al botón sobreturno de una agenda, me vuelve a abrir las acciones a partir del listado.

Te dejo video donde se ve todo esto:
https://www.loom.com/share/fefb5b4ff5fe4a3ca65cfc3a6f3c9f2e

2023-06-06 13:29 UTC, aldoEMatamala commented
> Aldito, vi un par de detalles:
> 
>     1. Cuando estoy cargando un sobreturno y doy _cancelar_ al botón me lleva nuevamente al listado para elegir un paciente. Creo que si cancelamos la acción, la deberia cancelar por completo, no dar un paso hacia atras. Eso igualmente se podría evaluar.
> 
>     2. Si realizo la misma acción que describo en el punto 1, y luego me voy a otra agenda del listado, me mantiene los datos del sobeturno de la agenda anterior.
> 
>     3. Siguiendo con la misma acción del punto 1 , si cierro el sidebar y voy al botón sobreturno de una agenda, me vuelve a abrir las acciones a partir del listado.
> 
> 
> Te dejo video donde se ve todo esto: https://www.loom.com/share/fefb5b4ff5fe4a3ca65cfc3a6f3c9f2e

Agos:
1- Corregido cancelar ahora cancela todo y cierra sidebar.
2- y 3- Corregido

2023-06-06 13:49 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9003](http://condorpiedra.andes.gob.ar:85/9003/mochawesome.html)
CYPRESS RUN: [8163](https://dashboard.cypress.io/projects/xr7gft/runs/8163/specs)
TEST START: 2023-06-06T13:48:53.360Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-06-08 12:04 UTC, AgosLizzi approved these changes

2023-06-08 12:16 UTC, AgosLizzi requested changes
Aldo, sabes que observe algo un poco raro. 
Cuando doy confirmar el sobreturno, el módulo me queda cargando, y luego de unos minutos me saltan algunos errores. Será propio de la task? 
https://www.loom.com/share/de1cf10d81744a11977752605531164d

*Yo probé cargar otras cosas en otros módulos y me los hacia perfecto. Solo sobre el gestor me ocurre esto

2023-06-08 16:03 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9039](http://condorpiedra.andes.gob.ar:85/9039/mochawesome.html)
CYPRESS RUN: [8197](https://dashboard.cypress.io/projects/xr7gft/runs/8197/specs)
TEST START: 2023-06-08T16:03:43.777Z
TOTAL: 403
SUCCESS: 398
FAIL: 3
SKIPPED: 2

2023-06-14 12:14 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9077](http://condorpiedra.andes.gob.ar:85/9077/mochawesome.html)
CYPRESS RUN: [8235](https://dashboard.cypress.io/projects/xr7gft/runs/8235/specs)
TEST START: 2023-06-14T12:13:45.359Z
TOTAL: 403
SUCCESS: 398
FAIL: 3
SKIPPED: 2

2023-06-14 13:20 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9081](http://condorpiedra.andes.gob.ar:85/9081/mochawesome.html)
CYPRESS RUN: [8239](https://dashboard.cypress.io/projects/xr7gft/runs/8239/specs)
TEST START: 2023-06-14T13:20:15.872Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-06-14 13:36 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9082](http://condorpiedra.andes.gob.ar:85/9082/mochawesome.html)
CYPRESS RUN: [8240](https://dashboard.cypress.io/projects/xr7gft/runs/8240/specs)
TEST START: 2023-06-14T13:35:47.751Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-06-14 13:51 UTC, AgosLizzi approved these changes

2023-06-14 13:55 UTC, ma7payne approved these changes

2023-06-30 16:25 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9143](http://condorpiedra.andes.gob.ar:85/9143/mochawesome.html)
CYPRESS RUN: [8290](https://dashboard.cypress.io/projects/xr7gft/runs/8290/specs)
TEST START: 2023-06-30T16:25:17.203Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-06-30 18:06 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9147](http://condorpiedra.andes.gob.ar:85/9147/mochawesome.html)
CYPRESS RUN: [8294](https://dashboard.cypress.io/projects/xr7gft/runs/8294/specs)
TEST START: 2023-06-30T18:06:42.957Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

2023-07-03 10:07 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9152](http://condorpiedra.andes.gob.ar:85/9152/mochawesome.html)
CYPRESS RUN: [8299](https://dashboard.cypress.io/projects/xr7gft/runs/8299/specs)
TEST START: 2023-07-03T10:07:08.160Z
TOTAL: 403
SUCCESS: 398
FAIL: 3
SKIPPED: 2

2023-07-03 11:54 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9153](http://condorpiedra.andes.gob.ar:85/9153/mochawesome.html)
CYPRESS RUN: [8300](https://dashboard.cypress.io/projects/xr7gft/runs/8300/specs)
TEST START: 2023-07-03T11:53:26.020Z
TOTAL: 375
SUCCESS: 367
FAIL: 6
SKIPPED: 2

2023-07-03 13:49 UTC, MarianoCampetella commented
En reiteradas veces el siguiente test falla! Revisarlo y en caso de ser necesario corregirlo para poder mergear dicha tarea.
![image](https://github.com/andes/app/assets/65697028/8946ef83-0ec8-4da7-aba1-936d824e0882)

2023-07-03 14:06 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9154](http://condorpiedra.andes.gob.ar:85/9154/mochawesome.html)
CYPRESS RUN: [8301](https://dashboard.cypress.io/projects/xr7gft/runs/8301/specs)
TEST START: 2023-07-03T14:06:19.961Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-07-03 14:20 UTC, aldoEMatamala commented
> USUARIO: amatamala BUILD NUMBER: [9154](http://condorpiedra.andes.gob.ar:85/9154/mochawesome.html) CYPRESS RUN: [8301](https://dashboard.cypress.io/projects/xr7gft/runs/8301/specs) TEST START: 2023-07-03T14:06:19.961Z TOTAL: 403 SUCCESS: 401 FAIL: 0 SKIPPED: 2

Hola campe! ahi paso el test, tiraba el timeout q tiene a veces el clonar agenda

2023-07-03 14:22 UTC, aldoEMatamala commented
> > USUARIO: amatamala BUILD NUMBER: [9154](http://condorpiedra.andes.gob.ar:85/9154/mochawesome.html) CYPRESS RUN: [8301](https://dashboard.cypress.io/projects/xr7gft/runs/8301/specs) TEST START: 2023-07-03T14:06:19.961Z TOTAL: 403 SUCCESS: 401 FAIL: 0 SKIPPED: 2
> 
> Hola @MarianoCampetella alias campe! ahi paso el test, tiraba el timeout q tiene a veces el clonar agenda

2023-07-03 15:23 UTC, MarianoCampetella commented
> > > USUARIO: amatamala BUILD NUMBER: [9154](http://condorpiedra.andes.gob.ar:85/9154/mochawesome.html) CYPRESS RUN: [8301](https://dashboard.cypress.io/projects/xr7gft/runs/8301/specs) TEST START: 2023-07-03T14:06:19.961Z TOTAL: 403 SUCCESS: 401 FAIL: 0 SKIPPED: 2
> > 
> > 
> > Hola @MarianoCampetella alias campe! ahi paso el test, tiraba el timeout q tiene a veces el clonar agenda

Excelente!! Vengo a hacer publica mis disculpas pensando que era problema de los test cuando en realidad no lo era. 
Que tenga buenos días!

2023-07-04 18:37 UTC, negro89 approved these changes
Excelente. Agregué un pequeño commit con unas miniedades.

2023-07-05 12:40 UTC, AgosLizzi approved these changes
Un placer visual. Gracias por tanto, perdon por tan poco!
![image](https://github.com/andes/app/assets/72876985/44ef2dde-9ede-4c49-a1da-8107df9e67b0)

2023-07-12 13:31 UTC, merged