Filtro para derivaciones
andes/app pull request #2874
Opened 2023-06-05 14:33 UTC by Fabio-Ramirez

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/RUP-348

### Funcionalidad desarrollada 

1.  Agregar filtro busqueda en componente prestacionEjecucion (lineas 13-20)
2.  Filtrar dinamicamente  la prestaciones destinos que coincidan parcial o total con en el campo anterior.  

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2023-06-06 18:37 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9018](http://condorpiedra.andes.gob.ar:85/9018/mochawesome.html)
CYPRESS RUN: [8178](https://dashboard.cypress.io/projects/xr7gft/runs/8178/specs)
TEST START: 2023-06-06T18:36:13.445Z
TOTAL: 364
SUCCESS: 354
FAIL: 8
SKIPPED: 2

2023-06-06 18:51 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9019](http://condorpiedra.andes.gob.ar:85/9019/mochawesome.html)
CYPRESS RUN: [8179](https://dashboard.cypress.io/projects/xr7gft/runs/8179/specs)
TEST START: 2023-06-06T18:50:42.291Z
TOTAL: 377
SUCCESS: 365
FAIL: 10
SKIPPED: 2

2023-06-08 14:43 UTC, MarianoCampetella commented
![image](https://github.com/andes/app/assets/65697028/32022d11-a414-4097-a452-933139ce8dd7)
Dos cosas se observan en la siguiente imagen:
- No se carga la cantidad de items como corresponde, y algunos que ya estaban cargados desaparecen.
- En caso de que la busqueda no me traiga ningun resultado, deberia aparecer una leyenda de que no hay resultados.

2023-06-08 14:47 UTC, MarianoCampetella requested changes

2023-06-08 14:47 UTC, MarianoCampetella commented on src/app/components/top/reglas/visualizacionReglas.html
>          </div>
La leyenda de: "Comience completando los filtros" estaria demas ya que el listado se encuentra cargado, lo cual dicho item nunca se mostraria. No es como el modulo de matriculaciones donde apenas entras no se visualiza ningun profesional debido a que es necesario tener que cargar al menos un filtro para verlos.

2023-06-08 14:47 UTC, MarianoCampetella commented on src/app/components/top/reglas/visualizacionReglas.html
> +        <div *ngIf="!loader && filas$ && filas$?.length" justify="center" class="mt-5">
No se puede preguntar a un Observable la longitud como si se tratase de un arreglo. Implementaria en un ng-container un *ngIf="filas$ | async as filas" y trabajaria con la variable filas para preguntrar si vienen elementos o no y de esta forma poder mostrar la leyenda que corresponde o los elementos.

2023-06-14 11:23 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9076](http://condorpiedra.andes.gob.ar:85/9076/mochawesome.html)
CYPRESS RUN: [8234](https://dashboard.cypress.io/projects/xr7gft/runs/8234/specs)
TEST START: 2023-06-14T11:23:08.783Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-07-11 12:30 UTC, Fabio-Ramirez commented on src/app/components/top/reglas/visualizacionReglas.component.ts
> +import { filter, map, toArray } from 'rxjs/operators';
Corregido!

2023-07-11 12:30 UTC, Fabio-Ramirez commented on src/app/components/top/reglas/visualizacionReglas.html
> +        <div *ngIf="!loader && filas$ && filas$?.length" justify="center" class="mt-5">
Corregido mr campe

2023-07-11 12:54 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9191](http://condorpiedra.andes.gob.ar:85/9191/mochawesome.html)
CYPRESS RUN: [8337](https://dashboard.cypress.io/projects/xr7gft/runs/8337/specs)
TEST START: 2023-07-11T12:54:28.277Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

2023-07-11 13:44 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9195](http://condorpiedra.andes.gob.ar:85/9195/mochawesome.html)
CYPRESS RUN: [8341](https://dashboard.cypress.io/projects/xr7gft/runs/8341/specs)
TEST START: 2023-07-11T13:43:14.194Z
TOTAL: 377
SUCCESS: 367
FAIL: 8
SKIPPED: 2

2023-07-11 13:46 UTC, MarianoCampetella commented
![image](https://github.com/andes/app/assets/65697028/7df1596a-08e4-463c-849d-5b5175e139c0)
Excelente la forma en que busca y me trae los resultado, pero cuando ingreso mal un nombre (o busco una prestación que no existe) me figura de la siguiente manera.

2023-07-14 13:21 UTC, AgosLizzi requested changes
Fabio, veo lo mismo que campe
![ejemplo](https://github.com/andes/app/assets/72876985/a9eeb002-1e64-4858-bfcf-6ef61adb7ca2)

y sumo otro detalle... tengo dudas sobre el doble scroll, no se si es TAN necesario, particularmente solo dejaría 1
![scroll](https://github.com/andes/app/assets/72876985/dfd103e4-5904-43e0-b4c0-426d5b93f980)

Corregido ambas casos.

2023-07-17 19:06 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9223](http://condorpiedra.andes.gob.ar:85/9223/mochawesome.html)
CYPRESS RUN: [8369](https://dashboard.cypress.io/projects/xr7gft/runs/8369/specs)
TEST START: 2023-07-17T19:05:44.357Z
TOTAL: 403
SUCCESS: 392
FAIL: 9
SKIPPED: 2

2023-07-18 11:33 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9225](http://condorpiedra.andes.gob.ar:85/9225/mochawesome.html)
CYPRESS RUN: [8371](https://dashboard.cypress.io/projects/xr7gft/runs/8371/specs)
TEST START: 2023-07-18T11:33:24.777Z
TOTAL: 403
SUCCESS: 392
FAIL: 9
SKIPPED: 2

2023-07-18 11:49 UTC, MarianoCampetella commented
![image](https://github.com/andes/app/assets/65697028/7be83a96-b4fa-4659-aa20-0cbb9e53ccc5)
![image](https://github.com/andes/app/assets/65697028/8a21ba44-8ab9-41d0-b1c2-f4f03a42c811)

Fabi un par de cositas, apenas entro al modulo de RUP y selecciono el botón reglas solicitudes se puede observar que se ve el título "REGLAS SOLICITUDES" repetido. Segundo, se sigue observado el doble scroll como menciono Agos en el comentario anterior. Y por ultimo cuando no se obtiene ningún resultado de la búsqueda, cambiaría el subtitulo "Edite algún filtro para realizar una nueva" por "Edite el filtro para realizar una nueva búsqueda" ya que solamente tenemos un filtro y no varios como para decir "algun".

2023-07-24 18:51 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9257](http://condorpiedra.andes.gob.ar:85/9257/mochawesome.html)
CYPRESS RUN: [8403](https://dashboard.cypress.io/projects/xr7gft/runs/8403/specs)
TEST START: 2023-07-24T18:51:07.343Z
TOTAL: 385
SUCCESS: 382
FAIL: 1
SKIPPED: 2

2023-07-25 12:24 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9259](http://condorpiedra.andes.gob.ar:85/9259/mochawesome.html)
CYPRESS RUN: [8405](https://dashboard.cypress.io/projects/xr7gft/runs/8405/specs)
TEST START: 2023-07-25T12:23:25.799Z
TOTAL: 366
SUCCESS: 356
FAIL: 8
SKIPPED: 2

2023-07-26 17:15 UTC, AgosLizzi requested changes
Fabi, te dejo comentado lo que charlamos:

- El plex help esta muy grande, y cuando termina el listado se genera un espacio en gris molesto e innecesario. 
![image (4)](https://github.com/andes/app/assets/72876985/78c02da1-bbd6-44f4-a213-47f4be95da8a)
![image (3)](https://github.com/andes/app/assets/72876985/731d1371-a27a-4659-b592-5ca90301114f)

- Por el resto de las correcciones (scroll, etc) lo veo bien!

Queda corregido Agos.

2023-08-01 18:03 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9322](http://condorpiedra.andes.gob.ar:85/9322/mochawesome.html)
CYPRESS RUN: [8464](https://dashboard.cypress.io/projects/xr7gft/runs/8464/specs)
TEST START: 2023-08-01T18:02:40.837Z
TOTAL: 351
SUCCESS: 340
FAIL: 10
SKIPPED: 1

2023-08-02 19:15 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9333](http://condorpiedra.andes.gob.ar:85/9333/mochawesome.html)
CYPRESS RUN: [8473](https://dashboard.cypress.io/projects/xr7gft/runs/8473/specs)
TEST START: 2023-08-02T19:15:19.244Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-09-05 13:11 UTC, AgosLizzi requested changes
Fabio, sigo viendo las cositas que te comente y ahora se agrega un comportamiento extraño (te adjunto video) 

- https://www.loom.com/share/266d6a7fd6cc45399fe5fdd36074a623

2023-12-21 17:48 UTC, negro89 requested changes
Fabiolo, hay un par de cositas ..
1. Se genera un doble scroll en el help. El scroll infinito funciona bien (es el interno, el del listado) pero el scroll del help no debería verse.
2. El ultimo elemento del listado siempre está vacio.
3. Dentro de la consulta de rup no se puede agregar una solicitud a la consulta ya que el boton ('+') siempre queda desactivado.

Adjunto captura donde se pueden ver los tres puntos anteriores

![image](https://github.com/andes/app/assets/37875706/1c3ebec1-0185-4270-b2b8-abbdc5021b11)

2024-01-16 20:25 UTC, MCele requested changes
Habría que revisar las busquedas que se realizan ya, dependiendo de cómo se hagan las búsquedas, se visualizan datos duplicados en el listado, esto no ocurre siempre, pero sí de forma recurrente. Por ejemplo si se realiza un tipeo rápido a veces se duplican los datos (como si alguna variable no se estuviera "limpiando") y además esto genera request innecesarios a la api, creo que conviene controlar las búsquedas por un determinado tiempo y una cantidad mínima de caracteres antes de generarse.


Ejemplo:
Regla existente: 
![image](https://github.com/andes/app/assets/19591224/fc7c8a98-a283-4677-aa55-d524427b375f)

Visualización en el listado:
![image](https://github.com/andes/app/assets/19591224/ce9e183e-cb52-4eb2-883d-89ed788cd70f)

2024-01-17 19:09 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [10302](http://condorpiedra.andes.gob.ar:85/10302/mochawesome.html)
CYPRESS RUN: [9409](https://dashboard.cypress.io/projects/xr7gft/runs/9409/specs)
TEST START: 2024-01-17T19:09:17.485Z
TOTAL: 401
SUCCESS: 399
FAIL: -1
SKIPPED: 3

2024-01-26 13:46 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [10348](http://condorpiedra.andes.gob.ar:85/10348/mochawesome.html)
CYPRESS RUN: [9455](https://dashboard.cypress.io/projects/xr7gft/runs/9455/specs)
TEST START: 2024-01-26T13:45:39.373Z
TOTAL: 349
SUCCESS: 340
FAIL: 6
SKIPPED: 3

2024-01-26 14:39 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [10352](http://condorpiedra.andes.gob.ar:85/10352/mochawesome.html)
CYPRESS RUN: [9459](https://dashboard.cypress.io/projects/xr7gft/runs/9459/specs)
TEST START: 2024-01-26T14:39:38.852Z
TOTAL: 401
SUCCESS: 399
FAIL: -1
SKIPPED: 3

2024-02-05 14:03 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [10440](http://condorpiedra.andes.gob.ar:85/10440/mochawesome.html)
CYPRESS RUN: [9545](https://dashboard.cypress.io/projects/xr7gft/runs/9545/specs)
TEST START: 2024-02-05T14:02:44.213Z
TOTAL: 402
SUCCESS: 400
FAIL: -1
SKIPPED: 3

2024-02-15 12:07 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [10484](http://condorpiedra.andes.gob.ar:85/10484/mochawesome.html)
CYPRESS RUN: [9585](https://dashboard.cypress.io/projects/xr7gft/runs/9585/specs)
TEST START: 2024-02-15T12:07:28.549Z
TOTAL: 399
SUCCESS: 396
FAIL: 1
SKIPPED: 2

2024-02-15 12:44 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [10486](http://condorpiedra.andes.gob.ar:85/10486/mochawesome.html)
CYPRESS RUN: [9587](https://dashboard.cypress.io/projects/xr7gft/runs/9587/specs)
TEST START: 2024-02-15T12:44:44.017Z
TOTAL: 399
SUCCESS: 397
FAIL: 0
SKIPPED: 2

2024-02-26 11:45 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [10546](http://condorpiedra.andes.gob.ar:85/10546/mochawesome.html)
CYPRESS RUN: [9645](https://dashboard.cypress.io/projects/xr7gft/runs/9645/specs)
TEST START: 2024-02-26T11:45:20.787Z
TOTAL: 399
SUCCESS: 396
FAIL: 1
SKIPPED: 2

2024-02-29 17:16 UTC, negro89 commented
@Fabio-Ramirez en que estado está este pr?

2024-03-07 14:05 UTC, MarianoCampetella commented
![image](https://github.com/andes/app/assets/65697028/353ff1c4-9c1c-4832-8c09-1a07462b8717)
![image](https://github.com/andes/app/assets/65697028/64751de2-a1fc-4501-a984-97ca1cc26ef4)

Con cualquier prestación me sigue pasando que el ultimo ítem de la lista sigue siendo un ítem vacío sin ningún dato!
También observe un detalle de que al momento de mostrar una leyenda cuando no existe ningún ítem en el listado, aparece un scroll el cual no debería estar. Si es posible removerlo.

2024-03-07 14:17 UTC, MarianoCampetella requested changes

2024-03-07 14:17 UTC, MarianoCampetella commented on src/app/components/top/reglas/visualizacionReglas.component.ts
> +import { UnidadEdad } from 'src/app/utils/enumerados';
Esta variable que se importo no se esta utilizando actualmente en ningún lado.

2024-03-07 14:17 UTC, MarianoCampetella commented on src/app/components/top/reglas/visualizacionReglas.html
> +        <ng-container *ngIf="filas$ | async as filas">
Es necesario tener que volver a consultar lo mismo que se encuentra en la linea 25?

2024-03-08 18:53 UTC, Fabio-Ramirez commented on src/app/components/top/reglas/visualizacionReglas.component.ts
> +import { UnidadEdad } from 'src/app/utils/enumerados';
corregido compa!

2024-03-08 18:53 UTC, Fabio-Ramirez commented on src/app/components/top/reglas/visualizacionReglas.html
> +        <ng-container *ngIf="filas$ | async as filas">
Corregido.

2024-04-04 14:40 UTC, Fabio-Ramirez reviewed
En el test existe un caso de mapa de camas (deshacer internación), donde es una cuestión que  se desestima por el momento y no influye en esta tarea. Adjunto imagen del test en cuestión.
![image (5)](https://github.com/andes/app/assets/45831788/e4e96f94-3918-4c91-84c1-3d026188714d)

2024-05-08 17:42 UTC, negro89 approved these changes
Agregué algunos cambios visuales en un nuevo commit

2024-05-08 18:22 UTC, negro89 commented
Tests al 08/05/24
![image](https://github.com/andes/app/assets/37875706/dd983b46-f36d-4381-b697-145d341ae9f1)

2024-05-08 18:24 UTC, merged