MISC-278 - Repara filtros de vistas para las novedades
andes/app pull request #2877
Opened 2023-06-12 13:59 UTC by ma7payne

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/MISC-278

### Funcionalidad desarrollada 

1. Se implementa la apertura de una novedad al hacer click sobre la campanita en el nav-bar principal
2. Se corrige el uso del botón volver al navegar por novedades y filtros
3. Se corrige el muestreo y borrado del campo de fecha al navegar
4. Se corrige scroll-bar en el muestreo de novedades con filtro por módulos

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2023-06-12 14:15 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9068](http://condorpiedra.andes.gob.ar:85/9068/mochawesome.html)
CYPRESS RUN: [8226](https://dashboard.cypress.io/projects/xr7gft/runs/8226/specs)
TEST START: 2023-06-12T14:15:39.173Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-07-03 18:32 UTC, MarianoCampetella requested changes

2023-07-03 18:32 UTC, MarianoCampetella commented on src/app/components/novedades/novedades.component.ts
> +            this.novedad = novedades.find((novedad: INovedad) => novedad._id === id);
Ya que tenes la interfaz de novedades se podria remplazar el novedades: any[] por novedades: Inovedades[]

2023-07-04 13:56 UTC, ma7payne commented on src/app/components/novedades/novedades.component.ts
> +            this.novedad = novedades.find((novedad: INovedad) => novedad._id === id);
Listo los cambios!

2023-07-04 13:57 UTC, ma7payne commented
> Mati, observe dos detalles.
> 
> 1. Te dejo video del comportamiento del campo de texto. Parece que no me dejará tipiar una fecha manual ... https://www.loom.com/share/2ca5d28042574512beaf1a45f7e1ae61
> 2. Hay icono para este módulo?
>    ![image](https://user-images.githubusercontent.com/72876985/248816970-24ffa262-dfdf-4205-a751-376906d9f0f0.png)
> 3. Estaría bueno agregar la línea caracteristica de apoyo tanto para texto como para botones
>    ![image](https://user-images.githubusercontent.com/72876985/248856837-7f97330b-994e-44e5-a9c2-29eee92c2dfe.png)

Listos los cambios @AgosLizzi

2023-07-04 15:28 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9164](http://condorpiedra.andes.gob.ar:85/9164/mochawesome.html)
CYPRESS RUN: [8311](https://dashboard.cypress.io/projects/xr7gft/runs/8311/specs)
TEST START: 2023-07-04T15:28:21.255Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-07-05 12:08 UTC, MarianoCampetella approved these changes

2023-07-05 12:14 UTC, AgosLizzi approved these changes

2023-07-05 12:31 UTC, negro89 approved these changes

2023-07-05 15:17 UTC, merged