IN - quitar indicaciones de registro
andes/app pull request #2881
Opened 2023-06-22 13:44 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-546

### Funcionalidad desarrollada 

1. Se agrego una condición IF para que filtre por las prestaciones que no sean pertenecientes al plan de indicación (Sección de medicación, hidratación, etc)
2. Se agrego un filter al observable prestacionesList$ para que el select de prestación dentro del tab de registros no aparezca el de "plan de indicacion" 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2023-06-22 14:01 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [9109](http://condorpiedra.andes.gob.ar:85/9109/mochawesome.html)
CYPRESS RUN: [8258](https://dashboard.cypress.io/projects/xr7gft/runs/8258/specs)
TEST START: 2023-06-22T14:00:20.746Z
TOTAL: 322
SUCCESS: 311
FAIL: 9
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-06-26 15:29 UTC, AgosLizzi requested changes
Campe, solo un detallito:

1. Parece reflejarse como una doble carga del modal cuando ingresamos a los registros de internación, te dejo video para que lo veas bien.
https://www.loom.com/share/456c2e1195c343a3b0cc8aa304873b33

2023-07-06 12:51 UTC, MarianoCampetella commented
> Campe, solo un detallito:
> 
> 1. Parece reflejarse como una doble carga del modal cuando ingresamos a los registros de internación, te dejo video para que lo veas bien.
>    https://www.loom.com/share/456c2e1195c343a3b0cc8aa304873b33

El bug no forma parte de la tarea pero se resolvió de todas formas! 
Aguardo respuestas! 

Saludos!

2023-07-11 13:34 UTC, MarianoCampetella commented
> Campe, gracias por corregirlo. Un detalle, cuando estaba revisando el bug, me salto dos veces este error ![error01](https://user-images.githubusercontent.com/72876985/252358749-c1e08b6f-ac98-4131-a158-f1e382edd30e.png)

Corregido el bug de consola (Ya venia desde master el error)

2023-07-14 13:00 UTC, AgosLizzi approved these changes
Campe, dejo comentado por aqui para que se tenga en cuenta tal vez para una nueva task @MCele @negro89 @silviroa 

- Dentro de registros y cambiando de paciente, no se me refresca el select y queda la prestación que elegí para el anterior paciente. Estaría bueno contemplar que cuando se cambie de persona, el select se limpie. Dejo video:
- https://www.loom.com/share/29bac07b9b8749dca1f127a32d33afa7

2023-07-17 13:05 UTC, MarianoCampetella commented
> Campe, dejo comentado por aqui para que se tenga en cuenta tal vez para una nueva task @MCele @negro89 @silviroa
> 
> * Dentro de registros y cambiando de paciente, no se me refresca el select y queda la prestación que elegí para el anterior paciente. Estaría bueno contemplar que cuando se cambie de persona, el select se limpie. Dejo video:
> * https://www.loom.com/share/29bac07b9b8749dca1f127a32d33afa7

Gracias por la observación! Dependiendo de lo que diga Cele, Laucha o Silvi agregamos las nuevas correcciones acá o creamos una nueva tarea para resolverlo! 
Aguardo respuestas.

2023-07-24 14:40 UTC, negro89 commented
Buenisimas las observaciones chicos! 💯
Esto ultimo lo cargamos como tarea nueva ya que hace poco subieron varios cambios, asi no se solapan tanto.

2023-07-24 15:05 UTC, negro89 approved these changes

2023-07-24 15:46 UTC, merged