CIT - Nuevo submódulo Auditoría de Agendas
andes/app pull request #2882
Opened 2023-06-22 14:05 UTC by JuanIRamirez

### Requerimiento
https://proyectos.andes.gob.ar/browse/CIT-227

### Funcionalidad desarrollada 

1. Nuevo submódulo de Auditoría de Agendas.
2. Nuevo componente: auditoria-agendas.component.ts
3. Modificados: gestor-agendas, fuera-agenda, sobreturno, revision-agenda, agregar-paciente.
4. Se separa la Auditoría del Gestor de Agendas. para separar acceso según permisos.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [x] Si
- [ ] No

### Requiere actualizaciones en la API

- [X] Si,  https://github.com/andes/api/pull/1813
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [X] Si https://github.com/andes/andes-test-integracion/pull/482
- [ ] No

Agregar este objeto al arreglo 'submodulos' del documento 'Citas' en colección 'modulos'
{ nombre:'CITAS'}
```
        {
            "activo" : true,
            "orden" : 0,
            "icono" : "table-search",
            "nombre" : "Auditoría de Agendas",
            "descripcion" : "Auditoría de turnos y Prestaciones",
            "class" : "citas audit",
            "color" : "#00a8e0",
            "linkAcceso" : "citas/auditoria_agendas",
            "permisos" : [ 
                "turnos:auditoriaAgenda:?"
            ]
        }
```

2023-06-26 14:17 UTC, AgosLizzi requested changes
Juan, me da la impresión que muchas cosas que están implementadas en el mockup no se tuvieron en cuenta y en consecuencia se usaron los recursos de los módulos viejos. Te voy detallando algunas cosas. Pero mi recomendación en general, es que revises nuevamente los mockups: 

1. Te dejo la comparación de imagenes de implementación/ imagenes: Estaría faltando icono, corregir ordenamiento y el tamaño de icono para cerrar es demasido grande, lo achicaria.![image](https://github.com/andes/app/assets/72876985/88c0e91f-c3cf-47d9-8c9c-2f5b6ea83305) 
![image](https://github.com/andes/app/assets/72876985/8cfd4b61-80f3-4e73-aebc-dca4d1d30428)

2. Los iconos están demasiado separados
![image](https://github.com/andes/app/assets/72876985/f2660184-a27b-41fa-9812-dd9d128e98b2)

3. Esta tabla, es la que esta usada sobre las funciones viejas. Además muchos badge no estan contemplados, como el de **"turno libre"**. Como referencia, la que esta reflajada en el mockup es la misma que se ve en el gestor de agendas.
![image](https://github.com/andes/app/assets/72876985/d47a54e2-c8e1-425c-86f6-8eca8dcdca08)

4. Los iconos sobre la asistencia no están contemplados en el mockup, y faltan las tildes sobre las palabras
![image](https://github.com/andes/app/assets/72876985/ff37c64a-2569-45b1-ae9d-4460c42b75e7) / 
![image](https://github.com/andes/app/assets/72876985/001c9e71-6b3d-4793-8ed7-9669a9206677)

5. Como sumatoria del punto anterior, una vez que doy asistencia en el mockup se utiliza un badge para dar esa indicación a la persona usuaria. En esta implementación no veo dicha acción y por lo contrario, tengo nuevamente un botón para generar asistencia. Ejemplo:
![image](https://github.com/andes/app/assets/72876985/c03ae39c-4456-4e2b-b6ed-60ebaf8bcf6b)

6. Aca también. Revisar como están los botones en el mockup
![image](https://github.com/andes/app/assets/72876985/b0e14bb4-d21a-4779-a42b-a9eaa916fcd8)

7. La codificación esta planteada como estaba en el módulo anterior, diferente al mockup. También se ve reflejado un botón "volver" que no se de donde sale.
![image](https://github.com/andes/app/assets/72876985/404c8ece-c1cd-41ab-b43d-8d0e83c2101b) 
Nuevamente, no se reflejan los componentes del mockup. ![image](https://github.com/andes/app/assets/72876985/4eca6d77-522b-4965-975f-c14522fa7cb9)

8. Por qué ese contexto del checkbox? 
![image](https://github.com/andes/app/assets/72876985/58933ed9-336f-4525-8980-48a642c3920e)

9. El color del módulo, no es el que esta contemplado en el mockup. No debería ser el mismo que el gestor de agendas, por eso se uso un color diferenciador.
![image](https://github.com/andes/app/assets/72876985/468956cf-a720-499b-8b01-8ae0a82d8333)
![citas](https://github.com/andes/app/assets/72876985/87725c69-2f59-4984-b1c2-f55d1cd7ad50)

10. Botones en diferente lugar que en el mockup
![image](https://github.com/andes/app/assets/72876985/a4715931-1293-4d83-83b8-84326b02122d)

11. Qué sucedió aca? ... a la palabra revisión le agregaría la tilde que le falta
![image](https://github.com/andes/app/assets/72876985/eafa1ea6-1091-4a00-a0e1-6adb98bced2b)

2023-06-26 19:01 UTC, MCele requested changes
Juan en general el funcionamiento está bastante bien, te dejo algunas observaciones de lo que noté para revisar.
Detalles visuales: 
- Cuando en el tab de fuera de agenda no se encuentren datos a mostrar no debería visualizarse el listado vacío, si no un mensaje notificando que no se encontraron prestaciones para los filtros seleccionados.
- El filtro de Espacios físicos ya no es necesario en esta pantalla.
- Cuando se cambia algún filtro desde fuera de agendas, si se elige el tab de agendas no se actualiza el listado con los nuevos filtros.
 - El filtro (check) "ver prestaciones ya auditadas" puede considerarse el filtro de estado para las fuera de agendas.

2023-06-28 18:59 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9127](http://condorpiedra.andes.gob.ar:85/9127/mochawesome.html)
CYPRESS RUN: [8274](https://dashboard.cypress.io/projects/xr7gft/runs/8274/specs)
TEST START: 2023-06-28T18:59:33.067Z
TOTAL: 403
SUCCESS: 393
FAIL: 8
SKIPPED: 2

2023-06-28 19:20 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [9129](http://condorpiedra.andes.gob.ar:85/9129/mochawesome.html)
CYPRESS RUN: [8276](https://dashboard.cypress.io/projects/xr7gft/runs/8276/specs)
TEST START: 2023-06-28T19:20:08.992Z
TOTAL: 403
SUCCESS: 393
FAIL: 8
SKIPPED: 2

2023-06-29 20:04 UTC, MCele commented on src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
> +import { ProfesionalService } from '../../../services/profesional.service';
me parece que no son necesarios los cambios en las rutas

2023-06-29 20:18 UTC, MCele commented
Revisar el commit de este pr, parece haberse quedado con el de otro PR

2023-06-30 17:56 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9146](http://condorpiedra.andes.gob.ar:85/9146/mochawesome.html)
CYPRESS RUN: [8293](https://dashboard.cypress.io/projects/xr7gft/runs/8293/specs)
TEST START: 2023-06-30T17:53:02.435Z
TOTAL: 403
SUCCESS: 392
FAIL: 9
SKIPPED: 2

2023-06-30 18:33 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9148](http://condorpiedra.andes.gob.ar:85/9148/mochawesome.html)
CYPRESS RUN: [8295](https://dashboard.cypress.io/projects/xr7gft/runs/8295/specs)
TEST START: 2023-06-30T18:33:16.757Z
TOTAL: 403
SUCCESS: 393
FAIL: 8
SKIPPED: 2

2023-07-06 12:55 UTC, JuanIRamirez commented on src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
> +import { ProfesionalService } from '../../../services/profesional.service';
Me daba error de no encontrado. por eso las cambié.

2023-07-10 12:50 UTC, AgosLizzi requested changes
Juan, van correcciones:

1. Siguen faltando tildes: 
![acentos](https://github.com/andes/app/assets/72876985/3c0bf2c2-647f-4ad2-b92b-8cb39d46dd86)

2.  Se puede corregir el largo del campo de texto? innecesariamente esta más corto y hay algunos que respetan el largo.
![ancho campo de texto](https://github.com/andes/app/assets/72876985/397d136f-7c09-45ba-a51c-6dabcb774af9)

3. Acá la asistencia esta como en la versión vieja, mediante campo de texto. 
![asistencia](https://github.com/andes/app/assets/72876985/660614c8-968d-496c-a49a-6b35bff5cdca)

4. Hay alguna forma de cambiar los tamaños, para que queden mas similares?
![badge+boton](https://github.com/andes/app/assets/72876985/c292c8a4-3985-4124-905d-0fd8d4f9ef82)

5. Este botón esta mal ubicado 
![boton](https://github.com/andes/app/assets/72876985/de0fa80a-c2d8-4f37-8872-4004026c8b5e)

6. No me cierra la situación de que haya dos botones que pueden llegar a prestar confusión por acción parecida. Acá ocurre como en muchos casos que todas las subacciones dentro del sidebar, tienen un "cerrar" para volver atras, eso deberiamos plantearlo bien, porque no queda del todo claro.
![confusión](https://github.com/andes/app/assets/72876985/e47c8d4f-78ed-404b-b160-4af66f1ecee5)

7. El listado no esta implementado como se propuso, nuevamente dejo el ejemplo del sidebar en el gestor de agenda, que presenta la misma implementación. Se pueden distinguir bien las diferencias. 
![listado](https://github.com/andes/app/assets/72876985/fae23558-9ae0-4c35-b7a0-c56769ace0b5)

8. Acá sucedio algo con el plex help. Nuevamente revisar el tema de doble "XX"
![plex help](https://github.com/andes/app/assets/72876985/c1bee962-8060-49cc-a168-33b991de8392)

9. Acá no hay cambios 
![same](https://github.com/andes/app/assets/72876985/c1877f1a-7901-4149-a057-6c0fbee7fb0c)
![same01](https://github.com/andes/app/assets/72876985/ec8c6fc9-07ad-485e-81ef-10fe49e32a1f)
 
10. Cuando selecciono estado, el sidebar se cierra sin motivo alguno
https://www.loom.com/share/8ad39c37f6684a51a8897d6494373538

11. En algunos casos los botones aparecen pegados. Si vamos a hacer una leve separación que se contemple en todos los casos, que no sea arbitrario.
![botones juntos](https://github.com/andes/app/assets/72876985/1a7c78c7-4bc6-47ee-bbab-ff07128ef8a1)

2023-09-18 12:36 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9637](http://condorpiedra.andes.gob.ar:85/9637/mochawesome.html)
CYPRESS RUN: [8751](https://dashboard.cypress.io/projects/xr7gft/runs/8751/specs)
TEST START: undefined
TOTAL: 0
SUCCESS: 0
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-09-18 18:26 UTC, AgosLizzi requested changes
Juan, solo unos detalles:

1. Este campo de texto sigue estando corto, fijate que para "sobreturnos" lo tenes bien aplicado
![Captura de pantalla 2023-09-18 145422](https://github.com/andes/app/assets/72876985/d997e2dd-2610-45a9-861c-cc1435ec9ce3)

2. En el tab "fuera de agenda" teniendo el sidebar abierto, y cambiando de estado, me sigue cerrando el sidebar automáticamente. No pasa con el tab "agendas"
3. Cuando quiero seleccionar opción de prepagas, no me carga listado
4. Este plex help quedo muy separado de su botón 
![Captura de pantalla 2023-09-18 145649](https://github.com/andes/app/assets/72876985/202595ae-7416-49f0-b89b-31bb9d3b30cd)
5. Cuando cambio de un tab a otro, no me actualiza el estado
![image](https://github.com/andes/app/assets/72876985/ce47128c-0283-4e15-b765-a1d5a1debd29)

2023-10-11 14:19 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9763](http://condorpiedra.andes.gob.ar:85/9763/mochawesome.html)
CYPRESS RUN: [8873](https://dashboard.cypress.io/projects/xr7gft/runs/8873/specs)
TEST START: 2023-10-11T14:18:12.792Z
TOTAL: 95
SUCCESS: 0
FAIL: 95
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-10-11 18:54 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9766](http://condorpiedra.andes.gob.ar:85/9766/mochawesome.html)
CYPRESS RUN: [8876](https://dashboard.cypress.io/projects/xr7gft/runs/8876/specs)
TEST START: 2023-10-11T18:51:35.932Z
TOTAL: 367
SUCCESS: 348
FAIL: 17
SKIPPED: 2

2023-10-18 12:15 UTC, AgosLizzi requested changes
Juan, no veo los 3 primeros cambios que te nombré en la corrección anterior.
También tener en cuenta estos detalles sobre el listado. El salto de linea que deja abajo "registro por profesional" no deberia existir
![listado](https://github.com/andes/app/assets/72876985/18d33986-344f-40d9-bb68-45c46a2880dd)
![Listado01](https://github.com/andes/app/assets/72876985/93b92506-385b-4b9c-929c-9e1788866fef)
te adjunto un ejemplo del caso ideal: 
![EjCambio-01](https://github.com/andes/app/assets/72876985/e8cc7392-bd39-44f2-898b-17faf32337f7)

Por último, sobre el icono de la pantalla de inicio, se podría bajar el "de", para que la diagramación sea igual que el resto de los iconos que se encuentran en CITAS.
Te dejo el ejemplo del mockup
![citas](https://github.com/andes/app/assets/72876985/0bfde6c6-c2a1-481b-96b5-f2deb74cd55d)

2023-10-30 13:34 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9839](http://condorpiedra.andes.gob.ar:85/9839/mochawesome.html)
CYPRESS RUN: [8947](https://dashboard.cypress.io/projects/xr7gft/runs/8947/specs)
TEST START: 2023-10-30T13:34:00.408Z
TOTAL: 405
SUCCESS: 402
FAIL: 1
SKIPPED: 2

2023-10-30 14:05 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9841](http://condorpiedra.andes.gob.ar:85/9841/mochawesome.html)
CYPRESS RUN: [8949](https://dashboard.cypress.io/projects/xr7gft/runs/8949/specs)
TEST START: 2023-10-30T14:05:30.949Z
TOTAL: 405
SUCCESS: 403
FAIL: 0
SKIPPED: 2

2023-11-01 14:10 UTC, JuanIRamirez commented
Hechos los cambios solicitados.

2023-11-13 11:15 UTC, AgosLizzi requested changes
Juan!

- Me sigue pasando esta situación "En el tab "fuera de agenda" teniendo el sidebar abierto, y cambiando de estado, me sigue cerrando el sidebar automáticamente. "7
- Corregir este tooltip que quedo demasiado alejado 
![01tooltip](https://github.com/andes/app/assets/72876985/cb7bea24-c752-4daf-bc44-3dc8734fa0d8)
- Y si estos dos badge pueden quedar del mismo tamaño, mejor. En estos casos siempre deberían tener mismo tamaño, cuando la diferencia es minima, no tiene sentido
![badge](https://github.com/andes/app/assets/72876985/0dd6a890-8b3e-443f-bd2c-e2ca136ee506)

2023-11-27 14:02 UTC, MarianoCampetella requested changes

2023-11-27 14:02 UTC, MarianoCampetella commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/auditoria-agendas.scss
Ya que todo el código se encuentra comentado dentro de la clase, eliminarla la misma.

2023-11-27 14:43 UTC, JuanIRamirez commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/auditoria-agendas.scss
Hecho

2023-11-28 14:15 UTC, silviroa requested changes
Habría que filtrar las agendas con tipos de prestación NO NOMINALIZADA ya que estas agendas no se auditan

2023-12-07 15:09 UTC, JuanIRamirez commented on src/app/components/turnos/gestor-agendas/revision/fuera-agenda.component.ts
> +        { 'key': 'sleccionar', 'label': '' },
Hecho

2023-12-12 18:41 UTC, MarianoCampetella commented
Cualquiera de las acciones que se haga con ambos botones (aceptar, reparar o reestablecer que aparece una vez seleccionado cualquiera de los dos) se podría agregar un toast para informarle al usuario que la acción se realizo con éxito. Agregar el mensaje correspondiente de acuerdo a la acción realizada. 
![image](https://github.com/andes/app/assets/65697028/cd9e5425-e4f7-4a1a-9490-6dfaea3bdf98)

2023-12-21 19:02 UTC, negro89 approved these changes

2023-12-22 11:58 UTC, MarianoCampetella approved these changes

2023-12-22 12:07 UTC, AgosLizzi approved these changes

2024-01-17 14:03 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10294](http://condorpiedra.andes.gob.ar:85/10294/mochawesome.html)
CYPRESS RUN: [9401](https://dashboard.cypress.io/projects/xr7gft/runs/9401/specs)
TEST START: 2024-01-17T14:02:38.904Z
TOTAL: 91
SUCCESS: 0
FAIL: 91
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-25 13:13 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10330](http://condorpiedra.andes.gob.ar:85/10330/mochawesome.html)
CYPRESS RUN: [9437](https://dashboard.cypress.io/projects/xr7gft/runs/9437/specs)
TEST START: 2024-01-25T13:08:53.584Z
TOTAL: 91
SUCCESS: 0
FAIL: 91
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-25 13:25 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10331](http://condorpiedra.andes.gob.ar:85/10331/mochawesome.html)
CYPRESS RUN: [9438](https://dashboard.cypress.io/projects/xr7gft/runs/9438/specs)
TEST START: 2024-01-25T13:24:07.420Z
TOTAL: 336
SUCCESS: 327
FAIL: 6
SKIPPED: 3

2024-01-25 14:05 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10333](http://condorpiedra.andes.gob.ar:85/10333/mochawesome.html)
CYPRESS RUN: [9440](https://dashboard.cypress.io/projects/xr7gft/runs/9440/specs)
TEST START: 2024-01-25T14:04:43.358Z
TOTAL: 365
SUCCESS: 357
FAIL: 5
SKIPPED: 3

2024-01-25 18:16 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10340](http://condorpiedra.andes.gob.ar:85/10340/mochawesome.html)
CYPRESS RUN: [9447](https://dashboard.cypress.io/projects/xr7gft/runs/9447/specs)
TEST START: 2024-01-25T18:15:43.298Z
TOTAL: 403
SUCCESS: 401
FAIL: -1
SKIPPED: 3

2024-02-29 17:07 UTC, negro89 commented
Se publica en produccion el 10 de marzo.

2026-04-07 13:29 UTC, closed without merging