MPI - Auditoria de pacientes- creado por
andes/app pull request #2887
Opened 2023-07-04 12:52 UTC by aldoEMatamala

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/MPI-406
### Funcionalidad desarrollada 

1.  Se agrega columna con dato "Creado por" que muestra el usuario que creó ese paciente. Cuando no existe el usuario se autocompleta con "S/D" (sin dato).

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [x] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2023-07-04 13:52 UTC, MarianoCampetella requested changes

2023-07-04 13:52 UTC, MarianoCampetella commented on src/app/modules/auditoria/component/auditoria-listado.html
> +            </plex-label>
La vista se ve excelente solo dos cosas:
- Sacaría el type="sm" ya que queda muy pequeño para la vista del usuario.
- En la interfaz del paciente habría que definir el objeto createdBy y en el HTML habría que llamarlo de la siguiente manera utilizando el pipe de nombre: paciente.createdBy | nombre

2023-07-04 14:03 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [9162](http://condorpiedra.andes.gob.ar:85/9162/mochawesome.html)
CYPRESS RUN: [8309](https://dashboard.cypress.io/projects/xr7gft/runs/8309/specs)
TEST START: 2023-07-04T13:55:07.950Z
TOTAL: 390
SUCCESS: 385
FAIL: 3
SKIPPED: 2

2023-07-04 15:56 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [9165](http://condorpiedra.andes.gob.ar:85/9165/mochawesome.html)
CYPRESS RUN: [8312](https://dashboard.cypress.io/projects/xr7gft/runs/8312/specs)
TEST START: 2023-07-04T15:55:52.807Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

2023-07-04 16:13 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [9166](http://condorpiedra.andes.gob.ar:85/9166/mochawesome.html)
CYPRESS RUN: [8313](https://dashboard.cypress.io/projects/xr7gft/runs/8313/specs)
TEST START: 2023-07-04T16:12:03.955Z
TOTAL: 382
SUCCESS: 373
FAIL: 7
SKIPPED: 2

2023-07-05 12:23 UTC, AgosLizzi requested changes
Aldito, cuando el sidebar esta abierto, suceden estas cosas con los badge, textos. Se comienzan a encimar ... (adjunto fotos)
![Mpi](https://github.com/andes/app/assets/72876985/1b3da0f0-3b23-429a-b8c9-007fc1e99b4b)
![mpi01](https://github.com/andes/app/assets/72876985/f12b95e1-08e9-4927-b259-92f085f7f49f)

2023-07-06 17:26 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9177](http://condorpiedra.andes.gob.ar:85/9177/mochawesome.html)
CYPRESS RUN: [8324](https://dashboard.cypress.io/projects/xr7gft/runs/8324/specs)
TEST START: 2023-07-06T17:25:50.509Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-07-06 18:35 UTC, aldoEMatamala commented
> Aldito, cuando el sidebar esta abierto, suceden estas cosas con los badge, textos. Se comienzan a encimar ... (adjunto fotos) ![Mpi](https://user-images.githubusercontent.com/72876985/251148230-1b3da0f0-3b23-429a-b8c9-007fc1e99b4b.png) ![mpi01](https://user-images.githubusercontent.com/72876985/251148236-f12b95e1-08e9-4927-b259-92f085f7f49f.png)

Hola Agos! gracias por la observación, corregido cuando se abre sidebar en resolución 720p

2023-07-06 18:37 UTC, aldoEMatamala commented on src/app/modules/auditoria/component/auditoria-listado.html
> +            </plex-label>
hola campe! gracias por la observación! corregido y creado el campo "createdBy" en IPaciente por lo que agrego la modificación en API. Saludos!

2023-07-10 12:47 UTC, MarianoCampetella approved these changes

2023-07-10 12:47 UTC, MarianoCampetella commented on src/app/core/mpi/interfaces/IPaciente.ts
> +    createdBy: ICreatedBy[];
Por qué el createdBy lo dejaste como un array? En la BD esta como un objeto y a demás esto mismo genera problemas en el HTML.

2023-07-11 12:52 UTC, aldoEMatamala commented on src/app/core/mpi/interfaces/IPaciente.ts
> +    createdBy: ICreatedBy[];
Buenas campe! gracias por la corrección, ya saqué el "[ ]", saludos!

2023-07-13 12:13 UTC, MarianoCampetella approved these changes

2023-07-13 15:37 UTC, AgosLizzi approved these changes

2023-07-21 17:37 UTC, negro89 approved these changes

2023-07-24 13:27 UTC, merged