IN - Deshacer internación
andes/app pull request #2889
Opened 2023-07-10 20:02 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-547

### Funcionalidad desarrollada 

1. Corrige fecha 'desde' para obtención del historial de movimientos.
2. Corrige función de deshacer internación tanto desde el mapa como listado de internacion, en capas asistencial y estadistica-v2 para efectores con capas unificadas. 
3. Actualiza listado luego de deshacer.

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2023-07-12 12:46 UTC, MarianoCampetella requested changes

2023-07-12 12:46 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.service.ts
> +            switchMap(([fechaIngresoDesde, fechaIngresoHasta, fechaEgresoDesde, fechaEgresoHasta, refresh]) => {
Me queda la duda por qué se agrega el refresh si en ningún momento se lo utiliza adentro del switchMap. Ya que estamos se podría eliminar el comentario de la linea 24. Lo mismo para la clase "listado-internacion.service.ts" en la linea 35.

2023-07-14 12:11 UTC, negro89 commented on src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.service.ts
> +            switchMap(([fechaIngresoDesde, fechaIngresoHasta, fechaEgresoDesde, fechaEgresoHasta, refresh]) => {
Como es un behavior se lo puede utilizar desde cualquier otro componente. En este caso se lo llama desde el listado médico.
Ahí se agregaron un par de modificaciones:
- Se excluyó a las salas de esta funcionalidad
- Se borró código comentado de un compañero xD
![Captura de pantalla -2023-07-14 01-04-12](https://github.com/andes/app/assets/37875706/f25ad930-e2b0-4557-b2b6-5027c2bd6cb0)

2023-07-14 12:57 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [9208](http://condorpiedra.andes.gob.ar:85/9208/mochawesome.html)
CYPRESS RUN: [8354](https://dashboard.cypress.io/projects/xr7gft/runs/8354/specs)
TEST START: 2023-07-14T12:57:18.332Z
TOTAL: 403
SUCCESS: 391
FAIL: 10
SKIPPED: 2

2023-07-14 13:27 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [9209](http://condorpiedra.andes.gob.ar:85/9209/mochawesome.html)
CYPRESS RUN: [8355](https://dashboard.cypress.io/projects/xr7gft/runs/8355/specs)
TEST START: 2023-07-14T13:26:51.849Z
TOTAL: 403
SUCCESS: 390
FAIL: 11
SKIPPED: 2

2023-07-14 15:39 UTC, MarianoCampetella commented
Excelente el comportamiento y el funcionamiento. Dejo a continuación un detalle que note y que en todo caso se puede resolver en una tarea nueva. 
 
[screen-capture.webm](https://github.com/andes/app/assets/65697028/180a39d0-c2fe-4797-add1-4199087a9c9d)

2023-07-14 15:40 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.service.ts
> +            switchMap(([fechaIngresoDesde, fechaIngresoHasta, fechaEgresoDesde, fechaEgresoHasta, refresh]) => {
Jaja no era necesario mostrar quien era :B

2023-07-14 15:41 UTC, MarianoCampetella approved these changes

2023-07-20 12:55 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [9232](http://condorpiedra.andes.gob.ar:85/9232/mochawesome.html)
CYPRESS RUN: [8378](https://dashboard.cypress.io/projects/xr7gft/runs/8378/specs)
TEST START: 2023-07-20T12:54:01.768Z
TOTAL: 331
SUCCESS: 315
FAIL: 14
SKIPPED: 2

2023-07-20 13:06 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [9233](http://condorpiedra.andes.gob.ar:85/9233/mochawesome.html)
CYPRESS RUN: [8379](https://dashboard.cypress.io/projects/xr7gft/runs/8379/specs)
TEST START: 2023-07-20T13:06:02.514Z
TOTAL: 403
SUCCESS: 395
FAIL: 6
SKIPPED: 2

2023-07-20 14:28 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [9235](http://condorpiedra.andes.gob.ar:85/9235/mochawesome.html)
CYPRESS RUN: [8381](https://dashboard.cypress.io/projects/xr7gft/runs/8381/specs)
TEST START: 2023-07-20T14:28:17.163Z
TOTAL: 403
SUCCESS: 389
FAIL: 12
SKIPPED: 2

2023-07-21 14:16 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [9238](http://condorpiedra.andes.gob.ar:85/9238/mochawesome.html)
CYPRESS RUN: [8384](https://dashboard.cypress.io/projects/xr7gft/runs/8384/specs)
TEST START: 2023-07-21T14:12:12.773Z
TOTAL: 355
SUCCESS: 347
FAIL: 6
SKIPPED: 2

2023-07-21 14:27 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [9239](http://condorpiedra.andes.gob.ar:85/9239/mochawesome.html)
CYPRESS RUN: [8385](https://dashboard.cypress.io/projects/xr7gft/runs/8385/specs)
TEST START: 2023-07-21T14:27:26.216Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-07-21 19:02 UTC, MCele approved these changes

2023-07-24 12:02 UTC, merged