RUP - Sobreturnos solo con agenda completa
andes/app pull request #2891
Opened 2023-07-12 13:42 UTC by aldoEMatamala

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/RUP-354
### Funcionalidad desarrollada 

1. Se agrega restricción de no tener turnos disponibles para poder agregar un sobreturno desde RUP.
2.  Se agrega restricción de la agenda tenga al menos un paciente para poder agregar un sobreturno desde RUP.

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [x] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2023-07-12 14:01 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9200](http://condorpiedra.andes.gob.ar:85/9200/mochawesome.html)
CYPRESS RUN: [8346](https://dashboard.cypress.io/projects/xr7gft/runs/8346/specs)
TEST START: 2023-07-12T14:01:40.447Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-07-12 16:06 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9204](http://condorpiedra.andes.gob.ar:85/9204/mochawesome.html)
CYPRESS RUN: [8350](https://dashboard.cypress.io/projects/xr7gft/runs/8350/specs)
TEST START: 2023-07-12T16:06:20.550Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-07-13 14:56 UTC, MarianoCampetella requested changes

2023-07-13 14:56 UTC, MarianoCampetella commented on src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
> +    }
Una forma de poder resumir un while con un filter es a través del metodo some(). Va un ejemplo:

agendaTienePaciente(agenda) {
  return agenda.bloques.some((bloque) => {
    return bloque.turnos.some((turno) => {
      return turno.paciente && turno.paciente.id;
    });
  });
}

En caso de utilizarlo como guía dejar un comentario en dicha función para una mejor interpretación!

2023-07-14 19:24 UTC, aldoEMatamala commented on src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
> +    }
Buenas campe! gracias por la sugerencia, queda mas corto es verdad, quedo aplicado con un pequeño comentario. Saludos !

2023-07-18 12:21 UTC, MarianoCampetella approved these changes

2023-07-24 13:29 UTC, negro89 commented
Esperar hasta mediados de agosto para incorporar a prod.

2023-10-02 15:46 UTC, maring0019 requested changes
-

2023-10-02 18:10 UTC, maring0019 commented
-

2023-10-31 03:32 UTC, negro89 approved these changes

2023-12-11 16:08 UTC, negro89 commented
Tarea momentáneamente bloqueada por otro requerimiento.

2026-04-08 12:57 UTC, closed without merging