MPI: Identidad autopercibida
andes/app pull request #2893
Opened 2023-07-17 13:11 UTC by Fabio-Ramirez

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/MPI-407

### Funcionalidad desarrollada 

1. Agregar filtraciones de identidad autopercibida (alias) o datos de identificación extranjera, para visualizarls en busquedas. 
2. Ademas se agrega el detalle del alias en las descargas de pdf (CITAS y RUP).

GLPI asociado: https://glpi.andes.gob.ar/front/ticket.form.php?id=3998

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [x] Si: https://github.com/andes/api/pull/1821
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [x] Si: https://github.com/andes/andes-test-integracion/pull/481
- [ ] No

2023-07-17 15:55 UTC, MarianoCampetella requested changes

2023-07-18 13:05 UTC, Fabio-Ramirez commented on src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
> +                       placeholder="Ingrese un documento, apellido, nombre, alias o numero de identificación">
corregido!

2023-07-18 13:06 UTC, Fabio-Ramirez commented on src/app/modules/perinatal/components/listado-perinatal.component.html
> +                    <td *plTableCol="'paciente'">{{ carnet.paciente.alias ? (carnet.paciente.apellido + ', ' + carnet.paciente.alias) : (carnet.paciente.apellido + ', ' + carnet.paciente.nombre) }}</
corregido Mr!

2023-07-21 11:41 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9237](http://condorpiedra.andes.gob.ar:85/9237/mochawesome.html)
CYPRESS RUN: [8383](https://dashboard.cypress.io/projects/xr7gft/runs/8383/specs)
TEST START: 2023-07-21T11:41:16.498Z
TOTAL: 403
SUCCESS: 391
FAIL: 10
SKIPPED: 2

2023-07-21 18:53 UTC, MarianoCampetella approved these changes

2023-07-24 18:25 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9255](http://condorpiedra.andes.gob.ar:85/9255/mochawesome.html)
CYPRESS RUN: [8401](https://dashboard.cypress.io/projects/xr7gft/runs/8401/specs)
TEST START: 2023-07-24T18:25:26.569Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

2023-07-24 18:37 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9256](http://condorpiedra.andes.gob.ar:85/9256/mochawesome.html)
CYPRESS RUN: [8402](https://dashboard.cypress.io/projects/xr7gft/runs/8402/specs)
TEST START: 2023-07-24T18:37:05.467Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

2023-07-26 18:39 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9285](http://condorpiedra.andes.gob.ar:85/9285/mochawesome.html)
CYPRESS RUN: [8430](https://dashboard.cypress.io/projects/xr7gft/runs/8430/specs)
TEST START: 2023-07-26T18:38:58.532Z
TOTAL: 341
SUCCESS: 334
FAIL: 5
SKIPPED: 2

2023-07-26 19:08 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9287](http://condorpiedra.andes.gob.ar:85/9287/mochawesome.html)
CYPRESS RUN: [8432](https://dashboard.cypress.io/projects/xr7gft/runs/8432/specs)
TEST START: 2023-07-26T19:07:57.248Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

2023-07-26 19:34 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9288](http://condorpiedra.andes.gob.ar:85/9288/mochawesome.html)
CYPRESS RUN: [8433](https://dashboard.cypress.io/projects/xr7gft/runs/8433/specs)
TEST START: 2023-07-26T19:33:11.951Z
TOTAL: 342
SUCCESS: 329
FAIL: 11
SKIPPED: 2

2023-07-27 18:38 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9299](http://condorpiedra.andes.gob.ar:85/9299/mochawesome.html)
CYPRESS RUN: [8444](https://dashboard.cypress.io/projects/xr7gft/runs/8444/specs)
TEST START: 2023-07-27T18:38:05.685Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-08-02 11:43 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9328](http://condorpiedra.andes.gob.ar:85/9328/mochawesome.html)
CYPRESS RUN: [8469](https://dashboard.cypress.io/projects/xr7gft/runs/8469/specs)
TEST START: 2023-08-02T11:43:21.208Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

2023-08-02 16:10 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9329](http://condorpiedra.andes.gob.ar:85/9329/mochawesome.html)
CYPRESS RUN: [8470](https://dashboard.cypress.io/projects/xr7gft/runs/8470/specs)
TEST START: 2023-08-02T16:09:35.416Z
TOTAL: 312
SUCCESS: 294
FAIL: 16
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-08-02 16:35 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9330](http://condorpiedra.andes.gob.ar:85/9330/mochawesome.html)
CYPRESS RUN: [8471](https://dashboard.cypress.io/projects/xr7gft/runs/8471/specs)
TEST START: 2023-08-02T16:35:19.896Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

2023-08-02 18:48 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9331](http://condorpiedra.andes.gob.ar:85/9331/mochawesome.html)
CYPRESS RUN: [8472](https://dashboard.cypress.io/projects/xr7gft/runs/8472/specs)
TEST START: 2023-08-02T18:48:38.522Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-09-01 18:38 UTC, negro89 commented
Al descargar el informe de una prestación de rup realizada a un paciente con nombre "autopercibido", en el apartado _datos del paciente_ figura el nombre en lugar del alias. (Adjunto captura).
Creo que lo demás esta de 10.

![image](https://github.com/andes/app/assets/37875706/6938ca7d-3ce4-48f6-87b7-91c99b276064)

2023-09-05 13:16 UTC, negro89 approved these changes

2023-09-05 13:59 UTC, JuanIRamirez commented
![image](https://github.com/andes/app/assets/83436047/31c7eb9b-fde5-4243-9851-4e06c6eaa4d8)
No aparece el nombre atopercibido en la descarga de .pdf en RUP,

2023-10-04 13:18 UTC, merged