TOP - información sidebar - historial
andes/app pull request #2896
Opened 2023-07-25 15:28 UTC by maring0019

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/TOP-154
### Funcionalidad desarrollada 

1. Se agrega el nombre del efector en el historial de la solicitud tanto para las solicitudes de entrada como de salida.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2023-08-03 13:54 UTC, MarianoCampetella commented
Cuando busco una solicitud del 26/01/2023 y me fijo en el historial, se puede observar que uno de los items, al tener gran cantidad de información, ocurre que se pierde la información del efector. Trataría de buscar alguna alternativa para no se pierda ninguna información y que tampoco se solapen. 
![image](https://github.com/andes/app/assets/65697028/a39b2e53-bfb1-4082-9a85-ebf5b066af52)

2023-08-04 16:11 UTC, AgosLizzi requested changes
Mar:

- Me sumo al pedido de @MarianoCampetella (buena observación). Supongo que esto también depende del tamaño de la pantalla ... igualmente resolvería para que sea adaptable a dif formatos.
- Cuando lo veo desde un monitor más chico, la info se muestra así:
![image](https://github.com/andes/app/assets/72876985/d4c73a9c-0313-49a2-9328-68067c98780b)
![image](https://github.com/andes/app/assets/72876985/a999986b-17d5-420f-8c2a-5be9955a2e17)

Lo cual observo que el plex item se vuelve muy enorme, y podría generar más scroll.

2023-08-07 12:28 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [9360](http://condorpiedra.andes.gob.ar:85/9360/mochawesome.html)
CYPRESS RUN: [8499](https://dashboard.cypress.io/projects/xr7gft/runs/8499/specs)
TEST START: 2023-08-07T12:25:07.800Z
TOTAL: 403
SUCCESS: 392
FAIL: 9
SKIPPED: 2

2023-08-08 14:43 UTC, maring0019 commented
> Cuando busco una solicitud del 26/01/2023 y me fijo en el historial, se puede observar que uno de los items, al tener gran cantidad de información, ocurre que se pierde la información del efector. Trataría de buscar alguna alternativa para no se pierda ninguna información y que tampoco se solapen. ![image](https://user-images.githubusercontent.com/65697028/258133229-a39b2e53-bfb1-4082-9a85-ebf5b066af52.png)

Se realizaron cambios.

2023-08-08 14:45 UTC, maring0019 commented
> Mar:
> 
> * Me sumo al pedido de @MarianoCampetella (buena observación). Supongo que esto también depende del tamaño de la pantalla ... igualmente resolvería para que sea adaptable a dif formatos.
> * Cuando lo veo desde un monitor más chico, la info se muestra así:
>   ![image](https://user-images.githubusercontent.com/72876985/258472670-d4c73a9c-0313-49a2-9328-68067c98780b.png)
>   ![image](https://user-images.githubusercontent.com/72876985/258472947-a999986b-17d5-420f-8c2a-5be9955a2e17.png)
> 
> Lo cual observo que el plex item se vuelve muy enorme, y genera más scroll.

Se realizaron cambios,


> Mar:
> 
> * Me sumo al pedido de @MarianoCampetella (buena observación). Supongo que esto también depende del tamaño de la pantalla ... igualmente resolvería para que sea adaptable a dif formatos.
> * Cuando lo veo desde un monitor más chico, la info se muestra así:
>   ![image](https://user-images.githubusercontent.com/72876985/258472670-d4c73a9c-0313-49a2-9328-68067c98780b.png)
>   ![image](https://user-images.githubusercontent.com/72876985/258472947-a999986b-17d5-420f-8c2a-5be9955a2e17.png)
> 
> Lo cual observo que el plex item se vuelve muy enorme, y genera más scroll.

Se realizaron cambios.

2023-08-08 15:06 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9374](http://condorpiedra.andes.gob.ar:85/9374/mochawesome.html)
CYPRESS RUN: [8511](https://dashboard.cypress.io/projects/xr7gft/runs/8511/specs)
TEST START: 2023-08-08T15:04:57.739Z
TOTAL: 371
SUCCESS: 361
FAIL: 8
SKIPPED: 2

2023-08-11 14:51 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9392](http://condorpiedra.andes.gob.ar:85/9392/mochawesome.html)
CYPRESS RUN: [8529](https://dashboard.cypress.io/projects/xr7gft/runs/8529/specs)
TEST START: 2023-08-11T14:51:15.565Z
TOTAL: 344
SUCCESS: 340
FAIL: 2
SKIPPED: 2

2023-08-14 14:04 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9404](http://condorpiedra.andes.gob.ar:85/9404/mochawesome.html)
CYPRESS RUN: [8541](https://dashboard.cypress.io/projects/xr7gft/runs/8541/specs)
TEST START: 2023-08-14T14:04:18.054Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-08-14 16:21 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9413](http://condorpiedra.andes.gob.ar:85/9413/mochawesome.html)
CYPRESS RUN: [8550](https://dashboard.cypress.io/projects/xr7gft/runs/8550/specs)
TEST START: 2023-08-14T16:21:32.278Z
TOTAL: 403
SUCCESS: 394
FAIL: 7
SKIPPED: 2

2023-08-14 16:38 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9414](http://condorpiedra.andes.gob.ar:85/9414/mochawesome.html)
CYPRESS RUN: [8551](https://dashboard.cypress.io/projects/xr7gft/runs/8551/specs)
TEST START: 2023-08-14T16:37:04.187Z
TOTAL: 359
SUCCESS: 347
FAIL: 10
SKIPPED: 2

2023-08-15 12:42 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9421](http://condorpiedra.andes.gob.ar:85/9421/mochawesome.html)
CYPRESS RUN: [8558](https://dashboard.cypress.io/projects/xr7gft/runs/8558/specs)
TEST START: 2023-08-15T12:41:23.688Z
TOTAL: 340
SUCCESS: 330
FAIL: 8
SKIPPED: 2

2023-08-16 11:55 UTC, MarianoCampetella commented
![image](https://github.com/andes/app/assets/65697028/3038b082-2723-4423-a217-4f742565f9ac)
Al probarlo en una pantalla chica me ocurre lo que se muestra en la imagen. Para sumar no siempre es recomendable expandir tanto el sidebar ya que cierta información se pierde. 
Una posible solución, sin antes consultarla previamente, podría ser que si en un item vienen cuatro elementos ordenarlo con un grid mediante dos filas y dos columnas.

2023-08-16 18:02 UTC, maring0019 commented
> ![image](https://user-images.githubusercontent.com/65697028/260993256-3038b082-2723-4423-a217-4f742565f9ac.png) Al probarlo en una pantalla chica me ocurre lo que se muestra en la imagen. Para sumar no siempre es recomendable expandir tanto el sidebar ya que cierta información se pierde. Una posible solución, sin antes consultarla previamente, podría ser que si en un item vienen cuatro elementos ordenarlo con un grid mediante dos filas y dos columnas.

Que mal, a modificar de nuevo.

2023-08-18 17:48 UTC, maring0019 commented
> > ![image](https://user-images.githubusercontent.com/65697028/260993256-3038b082-2723-4423-a217-4f742565f9ac.png) Al probarlo en una pantalla chica me ocurre lo que se muestra en la imagen. Para sumar no siempre es recomendable expandir tanto el sidebar ya que cierta información se pierde. Una posible solución, sin antes consultarla previamente, podría ser que si en un item vienen cuatro elementos ordenarlo con un grid mediante dos filas y dos columnas.
> 
> Que mal, a modificar de nuevo.

Se realizaron nuevos cambios.

2023-08-18 18:00 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9479](http://condorpiedra.andes.gob.ar:85/9479/mochawesome.html)
CYPRESS RUN: [8606](https://dashboard.cypress.io/projects/xr7gft/runs/8606/specs)
TEST START: 2023-08-18T17:59:59.525Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-08-18 18:24 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9480](http://condorpiedra.andes.gob.ar:85/9480/mochawesome.html)
CYPRESS RUN: [8607](https://dashboard.cypress.io/projects/xr7gft/runs/8607/specs)
TEST START: 2023-08-18T18:23:54.153Z
TOTAL: 385
SUCCESS: 382
FAIL: 1
SKIPPED: 2

2023-08-22 11:41 UTC, MarianoCampetella approved these changes

2023-08-22 12:57 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9488](http://condorpiedra.andes.gob.ar:85/9488/mochawesome.html)
CYPRESS RUN: [8615](https://dashboard.cypress.io/projects/xr7gft/runs/8615/specs)
TEST START: 2023-08-22T12:56:49.224Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-08-22 13:38 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9490](http://condorpiedra.andes.gob.ar:85/9490/mochawesome.html)
CYPRESS RUN: [8617](https://dashboard.cypress.io/projects/xr7gft/runs/8617/specs)
TEST START: 2023-08-22T13:38:17.226Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-09-01 17:54 UTC, negro89 approved these changes

2023-09-01 18:13 UTC, merged