TOP - Revisar y analizar comportamiento del botón continuar
andes/app pull request #2903
Opened 2023-08-11 14:04 UTC by aldoEMatamala

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/TOP-142
### Funcionalidad desarrollada 

1.  Corregidos badges de solicitudes de "Turno dado" a "Ejecución"
2.  Correjidos filtros de "Turno dado" que tambíen mostraba solicitudes en "Ejecución"
3.  Botón "Continuar registro" reestrigido sólo a solicitudes con una prestación iniciada

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2023-08-14 14:19 UTC, MarianoCampetella commented
![image](https://github.com/andes/app/assets/65697028/26049307-f667-429e-bf91-04ade7b5e1f1)
En las solicitudes de salida encontré el siguiente problema (muy raro): 
Al seleccionar el dropdown se abre pero al parecer no existe ninguna acción para poder seleccionar. Solamente me ocurrió con esa solicitud, con el resto que tiene el mismo estado no ocurre. En demo se puede visualizar la opción de "Continuar Registro".

2023-09-28 16:10 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9700](http://condorpiedra.andes.gob.ar:85/9700/mochawesome.html)
CYPRESS RUN: [8812](https://dashboard.cypress.io/projects/xr7gft/runs/8812/specs)
TEST START: 2023-09-28T16:09:49.722Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-12-20 13:21 UTC, MarianoCampetella commented
![image](https://github.com/andes/app/assets/65697028/5cf5b5e4-0cc2-491f-a7a4-2665314c3fa1)
![image](https://github.com/andes/app/assets/65697028/af5afc18-38c7-4c48-9f30-6409c6fee95a)

También se observa que desde la bandeja de salida, a partir de diciembre del 2022 existen varias solicitudes con distintos estados los cuales en el dropdown sigue figurando "continuar registro".

2024-01-02 12:40 UTC, aldoEMatamala commented on src/app/components/top/solicitudes/solicitudes.html
> +                                        *ngIf="prestacion.estadoActual.tipo !== 'rechazada' && prestacion.estadoActual.tipo !== 'auditoria' && prestacion.estadoActual.tipo !== 'validada' && prestacio
corregido gracias!

2024-01-02 14:56 UTC, aldoEMatamala commented
> ![image](https://private-user-images.githubusercontent.com/65697028/288774070-2e221c13-f1d9-4677-852a-a2cd43a3e5d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxOTcyOTQsIm5iZiI6MTcwNDE5Njk5NCwicGF0aCI6Ii82NTY5NzAyOC8yODg3NzQwNzAtMmUyMjFjMTMtZjFkOS00Njc3LTg1MmEtYTJjZDQzYTNlNWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDEyMDMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0OGQzM2VjN2U1YWQwMTYzMGZlYzY1MTIwMmYxNWU0Yjk1OTdkOWMyZjg3YTY5OWUyMzA4ODMwODFjNjJmMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tNUNT50FFqMBzXW1t_KNbG1oQItmAMJcCZrek7VZbts)
> 
> Me queda la duda con el botón "continuar registros" ya que en la descripcion de la tarea dice: El botón "continuar registro" para una solicitud ... en la de salida nunca debería verse. Las puedo ver para las solicitudes con "turno dado" o "ejecución"
> 
> Ya que estamos corregir los conflictos

corregido cuando aparecia "continuar registro" en solicitudes de salida y tambien ese dropdown sin elementos, saludos!

2024-01-04 18:11 UTC, aldoEMatamala commented
> ![image](https://private-user-images.githubusercontent.com/65697028/291900001-5cf5b5e4-0cc2-491f-a7a4-2665314c3fa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxOTcyOTQsIm5iZiI6MTcwNDE5Njk5NCwicGF0aCI6Ii82NTY5NzAyOC8yOTE5MDAwMDEtNWNmNWI1ZTQtMGNjMi00OTFmLWE3YTQtMjY2NTMxNGMzZmExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDEyMDMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiODE0ZDY1YTE5ZWM1MmYzOWU1ODRmOWQ5MzNlYTdlMWRmYzhkMDMxOWM5ZDM3ZmJiMTRmMDViN2E4ZmViZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fhSukF2jz-0d6OyM310TCitHSbRaNh-0iqOrGvCK6NA)
> 
> También se observa que desde la bandeja de salida, a partir de diciembre del 2022 existen varias solicitudes con distintos estados los cuales en el dropdown sigue figurando "continuar registro". A demás, en la bandeja de salida cuando filtro por Turno dado se observa que los badges no tienen el mismo color

Gracias por la corrección, ahora las solicitudes que tengan un turno y estén en ejecución se mostraran con el badge "ejecución". Saludos!

2024-01-04 18:36 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [10177](http://condorpiedra.andes.gob.ar:85/10177/mochawesome.html)
CYPRESS RUN: [9285](https://dashboard.cypress.io/projects/xr7gft/runs/9285/specs)
TEST START: 2024-01-04T18:36:28.660Z
TOTAL: 406
SUCCESS: 400
FAIL: 4
SKIPPED: 2

2024-01-05 13:07 UTC, MarianoCampetella approved these changes

2024-01-05 13:12 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [10183](http://condorpiedra.andes.gob.ar:85/10183/mochawesome.html)
CYPRESS RUN: [9291](https://dashboard.cypress.io/projects/xr7gft/runs/9291/specs)
TEST START: 2024-01-05T13:11:02.207Z
TOTAL: 311
SUCCESS: 290
FAIL: 19
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-05 15:03 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [10185](http://condorpiedra.andes.gob.ar:85/10185/mochawesome.html)
CYPRESS RUN: [9293](https://dashboard.cypress.io/projects/xr7gft/runs/9293/specs)
TEST START: 2024-01-05T15:03:09.810Z
TOTAL: 397
SUCCESS: 393
FAIL: 2
SKIPPED: 2

2024-01-05 16:20 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [10189](http://condorpiedra.andes.gob.ar:85/10189/mochawesome.html)
CYPRESS RUN: [9297](https://dashboard.cypress.io/projects/xr7gft/runs/9297/specs)
TEST START: 2024-01-05T16:20:07.632Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2024-01-05 17:30 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [10190](http://condorpiedra.andes.gob.ar:85/10190/mochawesome.html)
CYPRESS RUN: [9298](https://dashboard.cypress.io/projects/xr7gft/runs/9298/specs)
TEST START: 2024-01-05T17:30:17.528Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2024-01-09 14:56 UTC, ma7payne approved these changes

2024-01-09 16:03 UTC, AgosLizzi requested changes
Corregir:
![image](https://github.com/andes/app/assets/72876985/ec205e93-63c7-44ed-b063-95746c138b5a)
![image (2)](https://github.com/andes/app/assets/72876985/fc74b79e-13ac-4418-8d72-e1737385aaf4)
**### Aldo:
Corregido gracias !**

2024-02-06 15:50 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [10449](http://condorpiedra.andes.gob.ar:85/10449/mochawesome.html)
CYPRESS RUN: [9554](https://dashboard.cypress.io/projects/xr7gft/runs/9554/specs)
TEST START: 2024-02-06T15:50:35.161Z
TOTAL: 402
SUCCESS: 396
FAIL: 3
SKIPPED: 3

2024-02-06 16:29 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [10451](http://condorpiedra.andes.gob.ar:85/10451/mochawesome.html)
CYPRESS RUN: [9556](https://dashboard.cypress.io/projects/xr7gft/runs/9556/specs)
TEST START: 2024-02-06T16:29:29.188Z
TOTAL: 394
SUCCESS: 391
FAIL: 0
SKIPPED: 3

2024-02-07 13:31 UTC, AgosLizzi approved these changes

2024-02-14 15:54 UTC, merged