(REFACTOR) IN - Cambios porpuestos en mockups
andes/app pull request #2906
Opened 2023-08-29 11:33 UTC by Fabio-Ramirez

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/IN-554

### Funcionalidad desarrollada 

1.  Para evitar redundancias, se quita el dropdown.
2.  Se agrega cartelito inidicando la accion cuando no hay indicaciones cargadas.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2023-08-29 12:01 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9507](http://condorpiedra.andes.gob.ar:85/9507/mochawesome.html)
CYPRESS RUN: [8634](https://dashboard.cypress.io/projects/xr7gft/runs/8634/specs)
TEST START: 2023-08-29T12:00:37.796Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-08-29 12:51 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9509](http://condorpiedra.andes.gob.ar:85/9509/mochawesome.html)
CYPRESS RUN: [8636](https://dashboard.cypress.io/projects/xr7gft/runs/8636/specs)
TEST START: 2023-08-29T12:51:22.019Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-08-31 13:14 UTC, MarianoCampetella requested changes

2023-08-31 13:14 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
> +                                                        titulo="No hay solicitudes de entrada en el rango de fechas"
Según lo charlado en la demo, cambiaría el mensaje del título y del subtitulo por los mensajes que figuran en el mockup: https://proyectos.andes.gob.ar/browse/UIUX-346

2023-09-04 14:30 UTC, AgosLizzi requested changes
Fabio. Un par de cositas, las voy detallando:

1. El mensaje de guia debería aparecer aca: 
![plan01](https://github.com/andes/app/assets/72876985/f9be6550-b340-4a3d-b10a-e12aa358870e)
 y no sobre cada dropdown de la sección, ya que de este modo se ve a primera instancia, y como esta implementado, la persona usuaria deberia adivinar el paso para descubrir el mensaje.

2. Coincido con campe con lo que dice el mensaje @MarianoCampetella 
3.  SI tengo un mensaje de acción, dejo uno, el otro sobra "No hay indicaciones a la fecha"
![plan02](https://github.com/andes/app/assets/72876985/c97f8ed3-bb23-489f-ad39-207e462db908)
4. No veo el plex title sobre la botonera, que se explica en la task "acciones reiterativas", te dejo captura 
![plan03](https://github.com/andes/app/assets/72876985/3a3d9864-3407-4c53-8751-59dd08857ea2)
![plan04](https://github.com/andes/app/assets/72876985/efe9d20d-76e9-4069-b83b-765fcc2438bc)

Agos, quedan los cambios solicitados. Quedo atento.

2023-09-08 14:26 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9584](http://condorpiedra.andes.gob.ar:85/9584/mochawesome.html)
CYPRESS RUN: [8705](https://dashboard.cypress.io/projects/xr7gft/runs/8705/specs)
TEST START: 2023-09-08T14:25:50.329Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-09-08 15:50 UTC, Fabio-Ramirez commented on src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
> +                                                        titulo="No hay solicitudes de entrada en el rango de fechas"
Corregido.

2023-09-12 12:11 UTC, MarianoCampetella commented
![image](https://github.com/andes/app/assets/65697028/decd221e-7401-4307-aca8-0fe33d23f251)
Solo me queda una duda: el title de "LISTADO DE INDICACIONES" debe aparecer solamente cuando se selecciona una indicación?  
Falta agregar el acento a la palabra botón.

2023-09-14 12:49 UTC, AgosLizzi requested changes
Fabii

- Cuando se apreta el botón, que desaparezca el mensaje, si no ocurre lo siguiente:
https://www.loom.com/share/729302a79bd647e29fbd646b920a0911

- Tene en cuenta el tema de los acentos, que te lo marco campe
- Cuando fui a rechazar una indicación me salta este error, confirmame si pertenece a este pr o es para arreglarlo en nueva task. 
![image](https://github.com/andes/app/assets/72876985/27d2d6e9-01f7-4db8-8844-979a0cf70991)

Agos quedarían ok los cambio. Con respecto a la última observación, y de acuerdo a lo charlado, sería un error que lo arreglaría el pr: https://github.com/andes/api/pull/1817#pullrequestreview-1648760189. Cualquier cosita quedo atento.

2023-09-28 13:24 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9695](http://condorpiedra.andes.gob.ar:85/9695/mochawesome.html)
CYPRESS RUN: [8807](https://dashboard.cypress.io/projects/xr7gft/runs/8807/specs)
TEST START: 2023-09-28T13:22:51.711Z
TOTAL: 286
SUCCESS: 268
FAIL: 16
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-09-28 13:53 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9698](http://condorpiedra.andes.gob.ar:85/9698/mochawesome.html)
CYPRESS RUN: [8810](https://dashboard.cypress.io/projects/xr7gft/runs/8810/specs)
TEST START: 2023-09-28T13:53:27.951Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-10-03 13:53 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9726](http://condorpiedra.andes.gob.ar:85/9726/mochawesome.html)
CYPRESS RUN: [8834](https://dashboard.cypress.io/projects/xr7gft/runs/8834/specs)
TEST START: 2023-10-03T13:52:59.617Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-10-03 16:46 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9728](http://condorpiedra.andes.gob.ar:85/9728/mochawesome.html)
CYPRESS RUN: [8836](https://dashboard.cypress.io/projects/xr7gft/runs/8836/specs)
TEST START: 2023-10-03T16:45:56.555Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-10-30 12:40 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9836](http://condorpiedra.andes.gob.ar:85/9836/mochawesome.html)
CYPRESS RUN: [8944](https://dashboard.cypress.io/projects/xr7gft/runs/8944/specs)
TEST START: 2023-10-30T12:40:29.864Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-10-31 03:03 UTC, negro89 requested changes
El resto de 10 !

2023-10-31 03:03 UTC, negro89 commented on src/app/modules/rup/components/core/rup.component.ts
> +        if (!this.registro?.privacy) {
Ojo con este tipo de condiciones con negación. En este caso no es lo mismo que "exista el registro pero no contenga el atriburo 'privacy'" a que directamente "no exista el registro".

2023-11-01 16:08 UTC, Fabio-Ramirez commented on src/app/modules/rup/components/core/rup.component.ts
> +        if (!this.registro?.privacy) {
Corregido!

2023-11-01 16:30 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9859](http://condorpiedra.andes.gob.ar:85/9859/mochawesome.html)
CYPRESS RUN: [8966](https://dashboard.cypress.io/projects/xr7gft/runs/8966/specs)
TEST START: 2023-11-01T16:30:06.450Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-11-01 16:54 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9861](http://condorpiedra.andes.gob.ar:85/9861/mochawesome.html)
CYPRESS RUN: [8968](https://dashboard.cypress.io/projects/xr7gft/runs/8968/specs)
TEST START: 2023-11-01T16:54:38.954Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-11-02 13:03 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9867](http://condorpiedra.andes.gob.ar:85/9867/mochawesome.html)
CYPRESS RUN: [8974](https://dashboard.cypress.io/projects/xr7gft/runs/8974/specs)
TEST START: 2023-11-02T13:03:17.415Z
TOTAL: 353
SUCCESS: 350
FAIL: 1
SKIPPED: 2

2023-11-02 13:30 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9869](http://condorpiedra.andes.gob.ar:85/9869/mochawesome.html)
CYPRESS RUN: [8976](https://dashboard.cypress.io/projects/xr7gft/runs/8976/specs)
TEST START: 2023-11-02T13:30:00.159Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-11-09 19:11 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9883](http://condorpiedra.andes.gob.ar:85/9883/mochawesome.html)
CYPRESS RUN: [8990](https://dashboard.cypress.io/projects/xr7gft/runs/8990/specs)
TEST START: 2023-11-09T19:11:09.922Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-11-10 11:46 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9885](http://condorpiedra.andes.gob.ar:85/9885/mochawesome.html)
CYPRESS RUN: [8992](https://dashboard.cypress.io/projects/xr7gft/runs/8992/specs)
TEST START: 2023-11-10T11:44:59.303Z
TOTAL: 214
SUCCESS: 166
FAIL: 46
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-11-10 12:38 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9887](http://condorpiedra.andes.gob.ar:85/9887/mochawesome.html)
CYPRESS RUN: [8994](https://dashboard.cypress.io/projects/xr7gft/runs/8994/specs)
TEST START: 2023-11-10T12:35:50.126Z
TOTAL: 273
SUCCESS: 243
FAIL: 28
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-11-10 13:03 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9889](http://condorpiedra.andes.gob.ar:85/9889/mochawesome.html)
CYPRESS RUN: [8996](https://dashboard.cypress.io/projects/xr7gft/runs/8996/specs)
TEST START: 2023-11-10T13:03:06.474Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

2023-11-10 14:01 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9892](http://condorpiedra.andes.gob.ar:85/9892/mochawesome.html)
CYPRESS RUN: [8999](https://dashboard.cypress.io/projects/xr7gft/runs/8999/specs)
TEST START: 2023-11-10T14:01:28.213Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-11-10 14:35 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9895](http://condorpiedra.andes.gob.ar:85/9895/mochawesome.html)
CYPRESS RUN: [9002](https://dashboard.cypress.io/projects/xr7gft/runs/9002/specs)
TEST START: 2023-11-10T14:34:48.204Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-11-22 15:48 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9943](http://condorpiedra.andes.gob.ar:85/9943/mochawesome.html)
CYPRESS RUN: [9050](https://dashboard.cypress.io/projects/xr7gft/runs/9050/specs)
TEST START: 2023-11-22T15:48:27.705Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-12-07 18:17 UTC, AgosLizzi approved these changes

2023-12-11 13:39 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [10041](http://condorpiedra.andes.gob.ar:85/10041/mochawesome.html)
CYPRESS RUN: [9150](https://dashboard.cypress.io/projects/xr7gft/runs/9150/specs)
TEST START: 2023-12-11T13:38:50.602Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

2023-12-21 13:15 UTC, negro89 approved these changes

2023-12-22 18:30 UTC, merged