IN - Internación sin movimiento de ingreso
andes/app pull request #2908
Opened 2023-08-30 18:24 UTC by JuanIRamirez

### Requerimiento
[ ](https://proyectos.andes.gob.ar/browse/IN-552)

### Funcionalidad desarrollada 

1. No mostrar posibilidad de egresar el paciente (tab) cuando no tiene movimientos.
2. Eliminar internación (mostrar botón para deshacer internación) => sólo se borraría prestación/ resumen (estadística/médica).
3. Asociar la internación a una cama disponible: cargar movimiento de ingreso faltante.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2023-09-19 11:43 UTC, MarianoCampetella approved these changes

2023-09-19 11:43 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
> +                    *ngIf="((hayMovimientosSinEgresoAt$ | async) || (intSinMovimientos$ | async)) && (view$ | async) === 'listado-internacion' && !(mapaCamasService.loading | async)">
Cuando los *ngIf son lo bastante grande para encuadrar varias comparaciones lo ideal seria dejarlo dentro de una función para no extender el HTML y sea mas legible. Hacerlo para todos los casos donde se observen múltiples condiciones.

2023-09-19 11:43 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.html
> +                    [readonly]="capa !== 'estadistica' && capa !== 'estadistica-v2' && resumen?.id && !(intSinMovimientos$ | async)"
Mismo comentario que el anterior. Armar una función para minimizar la condición.

2023-09-19 11:43 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/sidebar/ingreso/ingreso-paciente-workflow/ingreso-paciente-workflow.component.ts
> +// import { MapaCamasService } from '../../../services/mapa-camas.service';
SI el import ya no se utiliza, borrar el comentario!

2023-09-19 11:49 UTC, MarianoCampetella requested changes

2023-09-19 11:49 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
> +                    *ngIf="((hayMovimientosSinEgresoAt$ | async) || (intSinMovimientos$ | async)) && (view$ | async) === 'listado-internacion' && !(mapaCamasService.loading | async)">
Cuando los *ngIf son lo bastante grande para encuadrar varias comparaciones lo ideal seria dejarlo dentro de una función para no extender el HTML y sea mas legible. Hacerlo para todos los casos donde se observen múltiples condiciones.

2023-10-04 15:34 UTC, JuanIRamirez commented on src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.html
> +                    [readonly]="capa !== 'estadistica' && capa !== 'estadistica-v2' && resumen?.id && !(intSinMovimientos$ | async)"
hecho

2023-10-04 15:36 UTC, JuanIRamirez commented on src/app/apps/rup/mapa-camas/sidebar/ingreso/ingreso-paciente-workflow/ingreso-paciente-workflow.component.ts
> +// import { MapaCamasService } from '../../../services/mapa-camas.service';
Hecho

2023-10-04 15:47 UTC, JuanIRamirez commented on src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
> +                    *ngIf="((hayMovimientosSinEgresoAt$ | async) || (intSinMovimientos$ | async)) && (view$ | async) === 'listado-internacion' && !(mapaCamasService.loading | async)">
Hecho

2023-10-05 18:24 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9747](http://condorpiedra.andes.gob.ar:85/9747/mochawesome.html)
CYPRESS RUN: [8857](https://dashboard.cypress.io/projects/xr7gft/runs/8857/specs)
TEST START: 2023-10-05T18:24:06.853Z
TOTAL: 403
SUCCESS: 397
FAIL: 4
SKIPPED: 2

2023-10-30 12:52 UTC, AgosLizzi approved these changes

2023-11-29 13:56 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [10002](http://condorpiedra.andes.gob.ar:85/10002/mochawesome.html)
CYPRESS RUN: [9111](https://dashboard.cypress.io/projects/xr7gft/runs/9111/specs)
TEST START: 2023-11-29T13:55:36.612Z
TOTAL: 359
SUCCESS: 345
FAIL: 12
SKIPPED: 2

2023-12-05 19:27 UTC, MCele commented
Actualizar PR y revisar los test

2023-12-14 16:10 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [10058](http://condorpiedra.andes.gob.ar:85/10058/mochawesome.html)
CYPRESS RUN: [9166](https://dashboard.cypress.io/projects/xr7gft/runs/9166/specs)
TEST START: 2023-12-14T16:10:21.377Z
TOTAL: 403
SUCCESS: 397
FAIL: 4
SKIPPED: 2

2023-12-20 15:02 UTC, MarianoCampetella requested changes

2023-12-20 15:02 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.ts
> +import { Component, OnDestroy, OnInit, Optional } from '@angular/core';
Remover esta variable ya que la misma no se esta utilizando.

2023-12-22 12:11 UTC, JuanIRamirez commented on src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.ts
> +import { Component, OnDestroy, OnInit, Optional } from '@angular/core';
Hecho

2023-12-22 12:35 UTC, MarianoCampetella approved these changes

2023-12-22 12:38 UTC, MarianoCampetella commented
Es necesario tener que corregir los siguientes test de internación para ser mergeado:
- Capa Estadística - Ingresos -> Editar ingreso
- Acciones sobre paciente ingresado desde capa asistencial -> Carga del informe de ingreso desde estadística-v2
- Acciones sobre paciente ingresado desde capa asistencial...capa asistencial y verificar sincronización en estadística-v2
- Mapa Camas - Detalle de Cama -> Deshacer internación

2023-12-22 12:55 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [10111](http://condorpiedra.andes.gob.ar:85/10111/mochawesome.html)
CYPRESS RUN: [9219](https://dashboard.cypress.io/projects/xr7gft/runs/9219/specs)
TEST START: 2023-12-22T12:55:08.823Z
TOTAL: 406
SUCCESS: 402
FAIL: 2
SKIPPED: 2

2023-12-22 14:45 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [10116](http://condorpiedra.andes.gob.ar:85/10116/mochawesome.html)
CYPRESS RUN: [9224](https://dashboard.cypress.io/projects/xr7gft/runs/9224/specs)
TEST START: 2023-12-22T14:45:37.755Z
TOTAL: 406
SUCCESS: 400
FAIL: 4
SKIPPED: 2

2024-01-12 17:12 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10255](http://condorpiedra.andes.gob.ar:85/10255/mochawesome.html)
CYPRESS RUN: [9362](https://dashboard.cypress.io/projects/xr7gft/runs/9362/specs)
TEST START: 2024-01-12T17:10:54.917Z
TOTAL: 238
SUCCESS: 184
FAIL: 53
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-16 17:51 UTC, silviroa commented
USUARIO: silviroa  
BUILD NUMBER: [10285](http://condorpiedra.andes.gob.ar:85/10285/mochawesome.html)
CYPRESS RUN: [9392](https://dashboard.cypress.io/projects/xr7gft/runs/9392/specs)
TEST START: 2024-01-16T17:51:34.701Z
TOTAL: 401
SUCCESS: 397
FAIL: 1
SKIPPED: 3

2024-01-16 18:23 UTC, silviroa commented
USUARIO: silviroa  
BUILD NUMBER: [10287](http://condorpiedra.andes.gob.ar:85/10287/mochawesome.html)
CYPRESS RUN: [9394](https://dashboard.cypress.io/projects/xr7gft/runs/9394/specs)
TEST START: 2024-01-16T18:22:38.137Z
TOTAL: 378
SUCCESS: 369
FAIL: 6
SKIPPED: 3

2024-02-29 18:14 UTC, merged