HUDS - mplementa mockups de prestaciones
andes/app pull request #2909
Opened 2023-08-31 17:11 UTC by ma7payne

### Requerimiento
https://proyectos.andes.gob.ar/browse/HUDS-74

### Funcionalidad desarrollada 

1. Se implementan los mockups para el panel de búsqueda, prestaciones en ámbito de internación, detalles de la prestación, detalle de la internación y detalle de otros conceptos.
2. Se crea nuevo selector con slider para filtro de conceptos.
3. Se añaden filtros para agrupar las internaciones y sus prestaciones en panel de búsqueda.
4. Se añaden filtros para agrupar las prestaciones que no pertenecen a una internación y sus prestaciones en panel de búsqueda.
5. Se añaden filtros para agrupar los registros del plan de indicaciones de una internación.
6. Se añaden filtros para agrupar los registros de las prestaciones que no pertenecen una internación.
8. Se crea nueva pantalla para detalle de registros del plan de indicaciones pertenecientes a una internación.
9. Se crea nueva pantalla para detalle de prestaciones fuera de una internación.
10. Se crea nueva pantalla para detalle de evoluciones y otros registros de prestaciones pertenecientes a una internación.
11. Se crea nueva pantalla para detalle de evoluciones y otros registros de prestaciones fuera de una internación.

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [x] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2023-09-05 12:00 UTC, AgosLizzi requested changes
Mati, un par de detallitos

1. Sobre el panel de busqueda, cuando deslizo hacia la derecha y no hay más iconos visibles, se genera este espacio (adj imagen). No se si es adrede para en un futuro agregar iconos ... si no es así me parece innecesario su visualización
![H01](https://github.com/andes/app/assets/72876985/a1e4e0df-f9fb-46ee-b679-005e88e57a10)

2. Mirando el panel de busqueda completo, cuando selecciono uno de los filtros y me van apareciendo lo que esta cargado, estaría bueno que aparezca un plex title con lo que se selecciona, asi le damos más contexto.
![H02](https://github.com/andes/app/assets/72876985/65cd1860-62c2-4e6e-ba97-cea80ba0cd03)

3. El botón volver sigue apareciendo en el footer, y se repite dos veces. 
![H03](https://github.com/andes/app/assets/72876985/2b42fd48-5d97-48d8-ac2c-5b4fc64c55b8)

4. Algunos items, como por ejemplo el de vacuna sigue apareciendo con el modelo viejo. También las solicitudes vencidas.
![H06](https://github.com/andes/app/assets/72876985/6b590505-26a9-4aef-ab80-87fcd0a6bff3) 
![HVencida](https://github.com/andes/app/assets/72876985/eccc5b02-4de9-4797-8381-a4ba78587156)

5. Agregar línea gris divisora 
![H08](https://github.com/andes/app/assets/72876985/98686873-0dfc-4711-9d16-206a4446f0e7)

6. A esto lo veo raro visualmente, como si le faltara un plex title.
![H05](https://github.com/andes/app/assets/72876985/4b260bf9-19d5-4ae3-9024-7cfd6d96c498)

2023-09-05 12:32 UTC, MarianoCampetella commented
![image](https://github.com/andes/app/assets/65697028/f4eaec77-3bdf-4b5e-885d-19723367b897)
Para sumar otro detalle estaría bueno que si no tiene ninguna vacuna, producto, etc estaría bueno que salga una leyenda informandole al usuario de que no hay vacunas, medicamentos, etc cargados/registrados. Nose que opina @AgosLizzi

2023-09-05 14:06 UTC, MarianoCampetella requested changes

2023-09-05 14:06 UTC, MarianoCampetella commented on src/app/modules/rup/components/huds/internacion/detalleRegistroInternación.component.ts
> +    public diasSuministro;
Esta variable parece estar demás ya que en la linea 80 se declara una constante con el mismo nombre.

2023-09-05 14:06 UTC, MarianoCampetella commented on src/app/modules/rup/components/huds/vistaContextoPrestacion.html
> +<div class="columna prestacion-offset"> -->
Eliminar la flecha -->

2023-09-05 14:06 UTC, MarianoCampetella commented on src/app/modules/rup/components/huds/vistaRegistro.html
> +                        <h5 class="ml-1 text-primary evoluciones">Evoluciones hola</h5>
Quedo un hola de alguna prueba realizada!

2023-09-05 15:35 UTC, AgosLizzi commented
> ![image](https://user-images.githubusercontent.com/65697028/265697719-f4eaec77-3bdf-4b5e-885d-19723367b897.png) Para sumar otro detalle estaría bueno que si no tiene ninguna vacuna, producto, etc estaría bueno que salga una leyenda informandole al usuario de que no hay vacunas, medicamentos, etc cargados/registrados. Nose que opina @AgosLizzi

Estoy de acuerdo, me parece bien!

2023-09-14 16:28 UTC, ma7payne commented
Quedaron revisados y corregidos los cambios! Además del agregado de algunas otras cositas a nivel UI. Quedo atento.

2023-10-03 12:59 UTC, ma7payne commented
> * ![image](https://user-images.githubusercontent.com/72876985/268946766-94c0eac0-e414-4691-bcaa-c15f1edc1852.png)
> * ![image](https://user-images.githubusercontent.com/72876985/268949395-3f1e4c7c-0834-4ec3-9efa-130681ccaa7a.png)

@AgosLizzi Listos los cambios para evitar el error!

2023-10-03 13:26 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9724](http://condorpiedra.andes.gob.ar:85/9724/mochawesome.html)
CYPRESS RUN: [8832](https://dashboard.cypress.io/projects/xr7gft/runs/8832/specs)
TEST START: 2023-10-03T13:24:45.994Z
TOTAL: 394
SUCCESS: 383
FAIL: 10
SKIPPED: 1

2023-10-05 12:00 UTC, AgosLizzi approved these changes
que bien quedo la implementación 💯

2023-10-06 13:04 UTC, MarianoCampetella commented
Maty hay uno de los comentarios de arriba, el que si se puede los ngIf dejarlos en una función, lo sigo viendo tal cual. 
Aprovecho a mostrarte que hay un botón de descargar PDF que estaría bueno poder agregarle un tooltip. 
![image](https://github.com/andes/app/assets/65697028/5c54b346-610d-4eb7-aa82-f2b535fe192d)

2023-10-30 11:40 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9834](http://condorpiedra.andes.gob.ar:85/9834/mochawesome.html)
CYPRESS RUN: [8942](https://dashboard.cypress.io/projects/xr7gft/runs/8942/specs)
TEST START: 2023-10-30T11:40:22.352Z
TOTAL: 403
SUCCESS: 394
FAIL: 7
SKIPPED: 2

2023-10-30 12:56 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9837](http://condorpiedra.andes.gob.ar:85/9837/mochawesome.html)
CYPRESS RUN: [8945](https://dashboard.cypress.io/projects/xr7gft/runs/8945/specs)
TEST START: 2023-10-30T12:55:37.481Z
TOTAL: 403
SUCCESS: 395
FAIL: 6
SKIPPED: 2

2023-10-30 13:56 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9840](http://condorpiedra.andes.gob.ar:85/9840/mochawesome.html)
CYPRESS RUN: [8948](https://dashboard.cypress.io/projects/xr7gft/runs/8948/specs)
TEST START: 2023-10-30T13:54:44.286Z
TOTAL: 317
SUCCESS: 301
FAIL: 14
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-10-30 18:12 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9847](http://condorpiedra.andes.gob.ar:85/9847/mochawesome.html)
CYPRESS RUN: [8955](https://dashboard.cypress.io/projects/xr7gft/runs/8955/specs)
TEST START: 2023-10-30T18:12:04.000Z
TOTAL: 403
SUCCESS: 395
FAIL: 6
SKIPPED: 2

2023-11-10 13:51 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9891](http://condorpiedra.andes.gob.ar:85/9891/mochawesome.html)
CYPRESS RUN: [8998](https://dashboard.cypress.io/projects/xr7gft/runs/8998/specs)
TEST START: 2023-11-10T13:51:13.285Z
TOTAL: 402
SUCCESS: 400
FAIL: 0
SKIPPED: 2

2023-11-27 12:18 UTC, AgosLizzi requested changes
Mati, un pequeño cambio:

El color del badge "asignada" 
![image](https://github.com/andes/app/assets/72876985/9b40db61-883f-4ffa-b1f7-eac608457ecd)
![image](https://github.com/andes/app/assets/72876985/9a278cef-72ba-44c0-b150-59773cc9f75e)

2023-12-07 14:56 UTC, ma7payne commented
@AgosLizzi Listos los cambios en los badges.

2023-12-13 12:32 UTC, AgosLizzi requested changes
Mati, solo quedaron unos badge que se me pasaron por alto.
![vencida](https://github.com/andes/app/assets/72876985/135140e8-baab-4777-b34e-493fd05809de)
![rechazada](https://github.com/andes/app/assets/72876985/ec8185ec-cbc6-4cee-9a0d-a0c7db287dcf)

- Vencida iria en rojo y rechazada tmb.

2024-01-18 15:37 UTC, ma7payne commented
Listos los cambios en badges @AgosLizzi

2024-01-23 17:36 UTC, AgosLizzi approved these changes

2024-03-07 12:12 UTC, AgosLizzi commented
Mati, se podrán corregir estos detallitos?

Este aviso debería aparecer?
![huds](https://github.com/andes/app/assets/72876985/e88c2015-a1d2-48da-bd31-55121c0d7e36)
![Captura de pantalla 2024-03-07 082346](https://github.com/andes/app/assets/72876985/08249a10-9203-43d9-bf89-0ea0e018dbe3)


El active, se podrá cambiar a color success. Gracias
![huds01](https://github.com/andes/app/assets/72876985/a95212da-594a-4e7d-adb7-3b30e35dfedf)

2024-03-11 17:34 UTC, ma7payne commented
Listos los cambios pedidos por @AgosLizzi! Quedo atento

2024-03-18 17:17 UTC, AgosLizzi reviewed
Mati, queda solo un detalle en los badge de estado. Veo un estado "borrador" realmente existe o quedo por default?
![image](https://github.com/andes/app/assets/72876985/b63f4503-a7e1-4f72-8c51-20179e6b1120)

2024-05-22 18:12 UTC, MarianoCampetella commented
Me queda la duda si esta bien que a pesar de que no exista ningún elemento siga apareciendo el buscador, esto se en vario de los items dentro del panel de búsqueda. Si ya se charlo que el estado borrador de las mediaciones sea "DRAFT" entonces ignorar el mensaje. Si no deberia decir borrador como ocurre en el plan de indicaciones 
![image](https://github.com/andes/app/assets/65697028/f75bbd84-aadd-432c-8840-6626e68648a1)
![image](https://github.com/andes/app/assets/65697028/1f44ad2a-ba7c-4601-8566-3f3c014d0ccd)

2024-05-22 18:24 UTC, negro89 commented
Segun se charló, solo resta filtrar las indicaciones en borrador.

2024-05-28 15:29 UTC, ma7payne commented
> Segun se charló, solo resta filtrar las indicaciones en borrador.

@negro89  Listo el cambio para filtrar indicaciones con estado "Borrador" (Draft)

2024-05-29 18:34 UTC, negro89 approved these changes

2024-05-30 14:49 UTC, AgosLizzi approved these changes

2024-07-12 12:51 UTC, MarianoCampetella commented
En hallazgos, trastornos, procedimientos y productos cuando no se encuentra ningún elemento para mostrar en el listado, si bien sale la leyenda como corresponde sigue figurando el input para buscar los elementos cuando en realidad eso solo debería salir cuando al menos existiera un elemento.
![image](https://github.com/user-attachments/assets/da35b976-06a8-4fa3-b594-f997a9c59649)

2024-07-15 18:36 UTC, ma7payne commented
> En hallazgos, trastornos, procedimientos y productos cuando no se encuentra ningún elemento para mostrar en el listado, si bien sale la leyenda como corresponde sigue figurando el input para buscar los elementos cuando en realidad eso solo debería salir cuando al menos existiera un elemento. ![image](https://private-user-images.githubusercontent.com/65697028/348264604-da35b976-06a8-4fa3-b594-f997a9c59649.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNTk1OTUsIm5iZiI6MTcyMTA1OTI5NSwicGF0aCI6Ii82NTY5NzAyOC8zNDgyNjQ2MDQtZGEzNWI5NzYtMDZhOC00ZmEzLWI1OTQtZjk5N2E5YzU5NjQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE2MDEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNDllNjhiNWJlNDA4NDhiMjkzYzgwOTlhNjIxYzA2ZmI4MTlhNGE2NTRkZmFjNjMyYWY1ZmY0ODVjN2QwZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rWm5qkzrAqJZiZEwZm6ZrURTRTzuUzUpgWvuqjiGGak)

@Listo el fix sobre muestreo de campo de filtros!

2024-07-16 12:38 UTC, ma7payne commented
> En hallazgos, trastornos, procedimientos y productos cuando no se encuentra ningún elemento para mostrar en el listado, si bien sale la leyenda como corresponde sigue figurando el input para buscar los elementos cuando en realidad eso solo debería salir cuando al menos existiera un elemento. ![image](https://private-user-images.githubusercontent.com/65697028/348264604-da35b976-06a8-4fa3-b594-f997a9c59649.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNTk1OTUsIm5iZiI6MTcyMTA1OTI5NSwicGF0aCI6Ii82NTY5NzAyOC8zNDgyNjQ2MDQtZGEzNWI5NzYtMDZhOC00ZmEzLWI1OTQtZjk5N2E5YzU5NjQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE2MDEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNDllNjhiNWJlNDA4NDhiMjkzYzgwOTlhNjIxYzA2ZmI4MTlhNGE2NTRkZmFjNjMyYWY1ZmY0ODVjN2QwZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rWm5qkzrAqJZiZEwZm6ZrURTRTzuUzUpgWvuqjiGGak)

@MarianoCampetella listos los cambios para la busqueda de registros.

2024-07-16 13:36 UTC, merged