IN - Sumar laboratorios en vista de registros
andes/app pull request #2913
Opened 2023-09-06 12:25 UTC by ma7payne

### Requerimiento
 

### Funcionalidad desarrollada 

1. Se incorporan los registros traídos de CDA con laboratorios a los registros actuales.
2. Se modifican las opciones de filtrado de registros para incluir laboratorios.
3. Se implementa la descarga para cada resultado de laboratorio.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2023-09-07 12:27 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9576](http://condorpiedra.andes.gob.ar:85/9576/mochawesome.html)
CYPRESS RUN: [8697](https://dashboard.cypress.io/projects/xr7gft/runs/8697/specs)
TEST START: 2023-09-07T12:27:34.157Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

2023-09-14 12:21 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9622](http://condorpiedra.andes.gob.ar:85/9622/mochawesome.html)
CYPRESS RUN: [8738](https://dashboard.cypress.io/projects/xr7gft/runs/8738/specs)
TEST START: 2023-09-14T12:20:48.013Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

2023-11-24 13:02 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9957](http://condorpiedra.andes.gob.ar:85/9957/mochawesome.html)
CYPRESS RUN: [9064](https://dashboard.cypress.io/projects/xr7gft/runs/9064/specs)
TEST START: 2023-11-24T13:02:28.957Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

2023-11-24 14:18 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9958](http://condorpiedra.andes.gob.ar:85/9958/mochawesome.html)
CYPRESS RUN: [9065](https://dashboard.cypress.io/projects/xr7gft/runs/9065/specs)
TEST START: 2023-11-24T14:18:40.899Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-11-27 16:22 UTC, MarianoCampetella commented
Agregaría un botón de cerrar para poder ver el mapa de camas nuevamente.
![Uploading image.png…]()

2023-11-27 17:13 UTC, Fabio-Ramirez approved these changes

2023-12-19 15:42 UTC, ma7payne commented
Listo el agregado del botón para cerrar pedido por @MarianoCampetella

2023-12-19 19:16 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10082](http://condorpiedra.andes.gob.ar:85/10082/mochawesome.html)
CYPRESS RUN: [9190](https://dashboard.cypress.io/projects/xr7gft/runs/9190/specs)
TEST START: 2023-12-19T19:16:25.130Z
TOTAL: 406
SUCCESS: 402
FAIL: 2
SKIPPED: 2

2023-12-19 19:45 UTC, AgosLizzi requested changes
Mati:
Cuando ingreso a internación, selecciono paciente y ya en el tabs de "registros" desde el campo de texto "prestación" filtro por _informe de laboratorio_, me salta este error:
![image](https://github.com/andes/app/assets/72876985/afa9292f-84a8-488b-9438-a527e65e799d)

- Una duda tmb: Los filtros deberían realizar la acción, no?

2023-12-20 14:09 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10089](http://condorpiedra.andes.gob.ar:85/10089/mochawesome.html)
CYPRESS RUN: [9197](https://dashboard.cypress.io/projects/xr7gft/runs/9197/specs)
TEST START: 2023-12-20T14:08:30.123Z
TOTAL: 277
SUCCESS: 249
FAIL: 27
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-12-20 14:32 UTC, AgosLizzi approved these changes

2023-12-20 17:21 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10098](http://condorpiedra.andes.gob.ar:85/10098/mochawesome.html)
CYPRESS RUN: [9206](https://dashboard.cypress.io/projects/xr7gft/runs/9206/specs)
TEST START: 2023-12-20T17:21:43.967Z
TOTAL: 406
SUCCESS: 400
FAIL: 4
SKIPPED: 2

2023-12-20 17:38 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10099](http://condorpiedra.andes.gob.ar:85/10099/mochawesome.html)
CYPRESS RUN: [9207](https://dashboard.cypress.io/projects/xr7gft/runs/9207/specs)
TEST START: 2023-12-20T17:37:08.917Z
TOTAL: 380
SUCCESS: 369
FAIL: 9
SKIPPED: 2

2023-12-20 18:08 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10100](http://condorpiedra.andes.gob.ar:85/10100/mochawesome.html)
CYPRESS RUN: [9208](https://dashboard.cypress.io/projects/xr7gft/runs/9208/specs)
TEST START: 2023-12-20T18:07:55.773Z
TOTAL: 406
SUCCESS: 402
FAIL: 2
SKIPPED: 2

2023-12-20 19:10 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10103](http://condorpiedra.andes.gob.ar:85/10103/mochawesome.html)
CYPRESS RUN: [9211](https://dashboard.cypress.io/projects/xr7gft/runs/9211/specs)
TEST START: 2023-12-20T19:10:18.537Z
TOTAL: 406
SUCCESS: 402
FAIL: 2
SKIPPED: 2

2023-12-21 16:55 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10107](http://condorpiedra.andes.gob.ar:85/10107/mochawesome.html)
CYPRESS RUN: [9215](https://dashboard.cypress.io/projects/xr7gft/runs/9215/specs)
TEST START: 2023-12-21T16:55:19.692Z
TOTAL: 344
SUCCESS: 339
FAIL: 3
SKIPPED: 2

2023-12-21 17:54 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10108](http://condorpiedra.andes.gob.ar:85/10108/mochawesome.html)
CYPRESS RUN: [9216](https://dashboard.cypress.io/projects/xr7gft/runs/9216/specs)
TEST START: 2023-12-21T17:54:44.404Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-12-21 18:11 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10109](http://condorpiedra.andes.gob.ar:85/10109/mochawesome.html)
CYPRESS RUN: [9217](https://dashboard.cypress.io/projects/xr7gft/runs/9217/specs)
TEST START: 2023-12-21T18:10:51.082Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-12-22 18:44 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10122](http://condorpiedra.andes.gob.ar:85/10122/mochawesome.html)
CYPRESS RUN: [9230](https://dashboard.cypress.io/projects/xr7gft/runs/9230/specs)
TEST START: 2023-12-22T18:44:06.166Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-12-22 19:03 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10123](http://condorpiedra.andes.gob.ar:85/10123/mochawesome.html)
CYPRESS RUN: [9231](https://dashboard.cypress.io/projects/xr7gft/runs/9231/specs)
TEST START: 2023-12-22T19:02:36.239Z
TOTAL: 345
SUCCESS: 335
FAIL: 8
SKIPPED: 2

2024-01-02 15:07 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10135](http://condorpiedra.andes.gob.ar:85/10135/mochawesome.html)
CYPRESS RUN: [9243](https://dashboard.cypress.io/projects/xr7gft/runs/9243/specs)
TEST START: 2024-01-02T15:06:18.352Z
TOTAL: 96
SUCCESS: 0
FAIL: 96
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-02 15:42 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10136](http://condorpiedra.andes.gob.ar:85/10136/mochawesome.html)
CYPRESS RUN: [9244](https://dashboard.cypress.io/projects/xr7gft/runs/9244/specs)
TEST START: 2024-01-02T15:41:25.907Z
TOTAL: 96
SUCCESS: 0
FAIL: 96
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-02 16:47 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10137](http://condorpiedra.andes.gob.ar:85/10137/mochawesome.html)
CYPRESS RUN: [9245](https://dashboard.cypress.io/projects/xr7gft/runs/9245/specs)
TEST START: 2024-01-02T16:46:33.770Z
TOTAL: 96
SUCCESS: 0
FAIL: 96
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-03 11:43 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10140](http://condorpiedra.andes.gob.ar:85/10140/mochawesome.html)
CYPRESS RUN: [9248](https://dashboard.cypress.io/projects/xr7gft/runs/9248/specs)
TEST START: 2024-01-03T11:34:08.084Z
TOTAL: 406
SUCCESS: 393
FAIL: 11
SKIPPED: 2

2024-01-03 12:00 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10141](http://condorpiedra.andes.gob.ar:85/10141/mochawesome.html)
CYPRESS RUN: [9249](https://dashboard.cypress.io/projects/xr7gft/runs/9249/specs)
TEST START: 2024-01-03T11:59:25.728Z
TOTAL: 393
SUCCESS: 385
FAIL: 7
SKIPPED: 1

2024-01-03 12:18 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10142](http://condorpiedra.andes.gob.ar:85/10142/mochawesome.html)
CYPRESS RUN: [9250](https://dashboard.cypress.io/projects/xr7gft/runs/9250/specs)
TEST START: 2024-01-03T12:16:57.566Z
TOTAL: 299
SUCCESS: 281
FAIL: 18
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-03 13:28 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10144](http://condorpiedra.andes.gob.ar:85/10144/mochawesome.html)
CYPRESS RUN: [9252](https://dashboard.cypress.io/projects/xr7gft/runs/9252/specs)
TEST START: 2024-01-03T13:28:19.832Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2024-01-09 18:26 UTC, merged