Ep 217
andes/app pull request #2914
Opened 2023-09-07 15:56 UTC by maring0019

### Requerimiento
 

### Funcionalidad desarrollada 

1. 
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2023-09-07 18:37 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9580](http://condorpiedra.andes.gob.ar:85/9580/mochawesome.html)
CYPRESS RUN: [8701](https://dashboard.cypress.io/projects/xr7gft/runs/8701/specs)
TEST START: 2023-09-07T18:36:25.659Z
TOTAL: 372
SUCCESS: 357
FAIL: 13
SKIPPED: 2

2023-09-11 14:33 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9594](http://condorpiedra.andes.gob.ar:85/9594/mochawesome.html)
CYPRESS RUN: [8712](https://dashboard.cypress.io/projects/xr7gft/runs/8712/specs)
TEST START: 2023-09-11T14:33:21.577Z
TOTAL: 353
SUCCESS: 341
FAIL: 10
SKIPPED: 2

2023-09-11 17:01 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9597](http://condorpiedra.andes.gob.ar:85/9597/mochawesome.html)
CYPRESS RUN: [8715](https://dashboard.cypress.io/projects/xr7gft/runs/8715/specs)
TEST START: 2023-09-11T17:00:52.715Z
TOTAL: 403
SUCCESS: 396
FAIL: 5
SKIPPED: 2

2023-09-12 15:14 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9601](http://condorpiedra.andes.gob.ar:85/9601/mochawesome.html)
CYPRESS RUN: [8717](https://dashboard.cypress.io/projects/xr7gft/runs/8717/specs)
TEST START: 2023-09-12T15:13:30.135Z
TOTAL: 403
SUCCESS: 398
FAIL: 3
SKIPPED: 2

2023-09-12 16:13 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9602](http://condorpiedra.andes.gob.ar:85/9602/mochawesome.html)
CYPRESS RUN: [8718](https://dashboard.cypress.io/projects/xr7gft/runs/8718/specs)
TEST START: 2023-09-12T16:12:38.824Z
TOTAL: 400
SUCCESS: 395
FAIL: 3
SKIPPED: 2

2023-09-12 16:27 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9603](http://condorpiedra.andes.gob.ar:85/9603/mochawesome.html)
CYPRESS RUN: [8719](https://dashboard.cypress.io/projects/xr7gft/runs/8719/specs)
TEST START: 2023-09-12T16:26:44.960Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-09-14 15:28 UTC, Fabio-Ramirez commented on src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
> +                                              && seccion.fields['segundaclasificacion']?.id!=='lamp' && seccion.fields['segundaclasificacion']?.id!=='pcr' && seccion.fields['segundaclasificacion']?.i
Sería óptimo reducir el html, utilizando un metodo en el componente que evalúe las mutliples condiciones.

2023-09-14 15:29 UTC, Fabio-Ramirez commented on src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
> +                                <plex-select *ngIf="field.key==='ifi' && checkConfirmados(seccion.fields['segundaclasificacion'])!=='confirmado'
Idem a lo anterior.

2023-09-14 15:29 UTC, Fabio-Ramirez commented on src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
> +                                && seccion.fields['antigeno']?.id!=='confirmado' && seccion.fields['ifi']?.id!=='confirmado' && seccion.fields['segundaclasificacion']?.id!=='pcr'"
Aca lo mismo.

2023-09-14 15:31 UTC, Fabio-Ramirez requested changes
Se agregan unas pequeñas observaciones al código.

2023-09-22 16:00 UTC, maring0019 commented on src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
> +                                              && seccion.fields['segundaclasificacion']?.id!=='lamp' && seccion.fields['segundaclasificacion']?.id!=='pcr' && seccion.fields['segundaclasificacion']?.i
Cambios hechos.

2023-09-22 16:00 UTC, maring0019 commented on src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
> +                                <plex-select *ngIf="field.key==='ifi' && checkConfirmados(seccion.fields['segundaclasificacion'])!=='confirmado'
Cambios hechos.

2023-09-22 16:00 UTC, maring0019 commented on src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
> +                                && seccion.fields['antigeno']?.id!=='confirmado' && seccion.fields['ifi']?.id!=='confirmado' && seccion.fields['segundaclasificacion']?.id!=='pcr'"
Cambios hechos.

2023-09-22 16:00 UTC, maring0019 commented
> Se agregan unas pequeñas observaciones al código.

Cambios hechos.

2023-09-22 16:36 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9650](http://condorpiedra.andes.gob.ar:85/9650/mochawesome.html)
CYPRESS RUN: [8764](https://dashboard.cypress.io/projects/xr7gft/runs/8764/specs)
TEST START: 2023-09-22T16:35:23.609Z
TOTAL: 95
SUCCESS: 0
FAIL: 95
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-09-22 18:16 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9652](http://condorpiedra.andes.gob.ar:85/9652/mochawesome.html)
CYPRESS RUN: [8766](https://dashboard.cypress.io/projects/xr7gft/runs/8766/specs)
TEST START: 2023-09-22T18:15:36.305Z
TOTAL: 379
SUCCESS: 366
FAIL: 11
SKIPPED: 2

2023-09-27 16:31 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9674](http://condorpiedra.andes.gob.ar:85/9674/mochawesome.html)
CYPRESS RUN: [8788](https://dashboard.cypress.io/projects/xr7gft/runs/8788/specs)
TEST START: 2023-09-27T16:30:40.274Z
TOTAL: 361
SUCCESS: 350
FAIL: 9
SKIPPED: 2

2023-09-27 17:36 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9678](http://condorpiedra.andes.gob.ar:85/9678/mochawesome.html)
CYPRESS RUN: [8792](https://dashboard.cypress.io/projects/xr7gft/runs/8792/specs)
TEST START: 2023-09-27T17:35:01.839Z
TOTAL: 332
SUCCESS: 316
FAIL: 15
SKIPPED: 1

2023-09-27 19:27 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9685](http://condorpiedra.andes.gob.ar:85/9685/mochawesome.html)
CYPRESS RUN: [8798](https://dashboard.cypress.io/projects/xr7gft/runs/8798/specs)
TEST START: 2023-09-27T19:26:30.984Z
TOTAL: 363
SUCCESS: 354
FAIL: 7
SKIPPED: 2

2023-09-28 12:24 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [9691](http://condorpiedra.andes.gob.ar:85/9691/mochawesome.html)
CYPRESS RUN: [8803](https://dashboard.cypress.io/projects/xr7gft/runs/8803/specs)
TEST START: 2023-09-28T12:24:22.163Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-10-03 13:20 UTC, Fabio-Ramirez approved these changes
Correcciones de codigo Ok!

2023-10-10 18:53 UTC, silviroa approved these changes

2023-10-18 16:48 UTC, merged