RUP - Filtro por actualizacion de solicitudes
andes/app pull request #2915
Opened 2023-09-08 18:18 UTC by JuanIRamirez

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/RUP-363

### Funcionalidad desarrollada 

1.  Se modificó '**../solicitudes-component.ts**' y '**solicitudes.html**' para que envíe fechaActualizacion al get de la api.
2.  Y así obtener las solicitudes p/fecha de actualización.
3.  Mismo campo fechas desde/hasta para entradas/salidas, p/fecha de solicitud o fecha actualización.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2023-09-14 13:39 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [9627](http://condorpiedra.andes.gob.ar:85/9627/mochawesome.html)
CYPRESS RUN: [8743](https://dashboard.cypress.io/projects/xr7gft/runs/8743/specs)
TEST START: 2023-09-14T13:39:06.795Z
TOTAL: 394
SUCCESS: 391
FAIL: 1
SKIPPED: 2

2023-09-14 13:55 UTC, MarianoCampetella approved these changes

2023-09-14 13:55 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [9628](http://condorpiedra.andes.gob.ar:85/9628/mochawesome.html)
CYPRESS RUN: [8744](https://dashboard.cypress.io/projects/xr7gft/runs/8744/specs)
TEST START: 2023-09-14T13:54:32.350Z
TOTAL: 383
SUCCESS: 378
FAIL: 4
SKIPPED: 1

2023-09-14 15:58 UTC, Fabio-Ramirez commented on src/app/components/top/solicitudes/solicitudes.html
> +                        <plex-datetime *ngIf="asignadas && tipoSolicitud === 'entrada' && !actualizacion"
A modo de no sobrecargar el html con condiciones, se sugiere utilizar un método en el componente, de modo tal que realice la lógica. Se recomienda como mucho usar dos condiciones dentro de un if de la vista.

2023-09-14 16:00 UTC, Fabio-Ramirez commented on src/app/components/top/solicitudes/solicitudes.html
> +                        <plex-datetime *ngIf="asignadas && tipoSolicitud === 'entrada' && !actualizacion"
Idem a lo anterior.

2023-09-14 16:01 UTC, Fabio-Ramirez requested changes
Dejo unos detalles sobre el codigo compa.

2024-01-12 15:54 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [10252](http://condorpiedra.andes.gob.ar:85/10252/mochawesome.html)
CYPRESS RUN: [9359](https://dashboard.cypress.io/projects/xr7gft/runs/9359/specs)
TEST START: 2024-01-12T15:54:37.996Z
TOTAL: 401
SUCCESS: 397
FAIL: 1
SKIPPED: 3

2024-01-12 16:17 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [10253](http://condorpiedra.andes.gob.ar:85/10253/mochawesome.html)
CYPRESS RUN: [9360](https://dashboard.cypress.io/projects/xr7gft/runs/9360/specs)
TEST START: 2024-01-12T16:17:22.130Z
TOTAL: 401
SUCCESS: 397
FAIL: 1
SKIPPED: 3

2024-01-12 19:13 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [10257](http://condorpiedra.andes.gob.ar:85/10257/mochawesome.html)
CYPRESS RUN: [9364](https://dashboard.cypress.io/projects/xr7gft/runs/9364/specs)
TEST START: 2024-01-12T19:13:30.435Z
TOTAL: 401
SUCCESS: 397
FAIL: 1
SKIPPED: 3

2024-01-15 11:46 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [10261](http://condorpiedra.andes.gob.ar:85/10261/mochawesome.html)
CYPRESS RUN: [9368](https://dashboard.cypress.io/projects/xr7gft/runs/9368/specs)
TEST START: 2024-01-15T11:45:16.437Z
TOTAL: 367
SUCCESS: 357
FAIL: 7
SKIPPED: 3

2024-01-15 13:32 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [10265](http://condorpiedra.andes.gob.ar:85/10265/mochawesome.html)
CYPRESS RUN: [9372](https://dashboard.cypress.io/projects/xr7gft/runs/9372/specs)
TEST START: 2024-01-15T13:31:04.367Z
TOTAL: 318
SUCCESS: 301
FAIL: 15
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-15 13:36 UTC, Fabio-Ramirez commented on src/app/components/top/solicitudes/solicitudes.html
> +                        <plex-datetime *ngIf="asignadas && tipoSolicitud === 'entrada' && !actualizacion"
corregido!

2024-01-15 13:56 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [10267](http://condorpiedra.andes.gob.ar:85/10267/mochawesome.html)
CYPRESS RUN: [9374](https://dashboard.cypress.io/projects/xr7gft/runs/9374/specs)
TEST START: 2024-01-15T13:56:39.551Z
TOTAL: 398
SUCCESS: 396
FAIL: -1
SKIPPED: 3

2024-01-15 14:17 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [10268](http://condorpiedra.andes.gob.ar:85/10268/mochawesome.html)
CYPRESS RUN: [9375](https://dashboard.cypress.io/projects/xr7gft/runs/9375/specs)
TEST START: 2024-01-15T14:16:14.686Z
TOTAL: 398
SUCCESS: 393
FAIL: 2
SKIPPED: 3

2024-01-15 14:31 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [10269](http://condorpiedra.andes.gob.ar:85/10269/mochawesome.html)
CYPRESS RUN: [9376](https://dashboard.cypress.io/projects/xr7gft/runs/9376/specs)
TEST START: 2024-01-15T14:30:38.645Z
TOTAL: 398
SUCCESS: 390
FAIL: 5
SKIPPED: 3

2024-01-15 15:03 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [10270](http://condorpiedra.andes.gob.ar:85/10270/mochawesome.html)
CYPRESS RUN: [9377](https://dashboard.cypress.io/projects/xr7gft/runs/9377/specs)
TEST START: 2024-01-15T15:03:36.181Z
TOTAL: 400
SUCCESS: 397
FAIL: 0
SKIPPED: 3

2024-01-16 16:01 UTC, MarianoCampetella approved these changes

2024-03-07 18:41 UTC, Fabio-Ramirez reviewed
Por el lado de funcionalidad estaría correcto, faltaría resolver el conflicto unicamente.

2024-03-20 13:56 UTC, MCele requested changes
No resuelve el punto 2 pedido en la tarea, ya que al cambiar entre tipos de filtro de fecha sigue sin mostrar datos en el listado, y recién se actualiza cuando se modifica la fecha.
El punto 1 está correcto, pero está resuelto en api, por lo que app sigue pendiente de corrección

2024-05-08 18:39 UTC, negro89 approved these changes

2024-05-08 19:03 UTC, negro89 commented
Tests al 08/05/24
![image](https://github.com/andes/app/assets/37875706/1c319385-8abc-45cc-b506-aa8b8f9a68b1)

2024-05-08 19:04 UTC, merged