CIT - Implementar mockups de reasignación de turnos
andes/app pull request #2916
Opened 2023-09-08 18:45 UTC by JuanIRamirez

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-210

### Funcionalidad desarrollada 

1.  Se implementó nuevo mockup para las agendas suspendidas c/turnos dados.
2. 
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [X] Si
- [ ] No

2023-09-13 12:12 UTC, AgosLizzi requested changes
Juan, te dejo un par de comentarios:

- No usaría este tipo de recursos para implementar, comunmente no se usan más dentro de andes. Sumado a que no esta reflejado en el mockup
![Captura de pantalla 2023-09-13 083620](https://github.com/andes/app/assets/72876985/93bb7762-3104-4039-80f6-6be5d64dff45)

- Hay que ver de arreglar esto:
![Captura de pantalla 2023-09-13 083853](https://github.com/andes/app/assets/72876985/94b03797-f2f1-42e8-a977-6d5b888f4e8e)

- La visualización de turnos, no esta aplicada como se muestra en el mockup. Esto no quiere decir que tiene que ser exacto... Pero el componente utilizado no es el adecuado. 
![Captura de pantalla 2023-09-13 084117](https://github.com/andes/app/assets/72876985/76d8308b-0fb1-43e7-8a44-fb23782a72b3)

- Esta aplicación viene de la versión vieja de la interfaz. Si no hay mockup para esto, consultar y lo vemos.
![Captura de pantalla 2023-09-13 083805](https://github.com/andes/app/assets/72876985/f1b1a8fc-6a93-43ab-b6d5-a4f987bc4008)

- Por último, este modal es excesivamente enorme. 
![Captura de pantalla 2023-09-13 084154](https://github.com/andes/app/assets/72876985/715ef850-03c2-41a2-a85c-7c7610ce480a)

2023-09-13 13:07 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9609](http://condorpiedra.andes.gob.ar:85/9609/mochawesome.html)
CYPRESS RUN: [8725](https://dashboard.cypress.io/projects/xr7gft/runs/8725/specs)
TEST START: 2023-09-13T13:07:36.592Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-09-13 13:30 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9610](http://condorpiedra.andes.gob.ar:85/9610/mochawesome.html)
CYPRESS RUN: [8726](https://dashboard.cypress.io/projects/xr7gft/runs/8726/specs)
TEST START: 2023-09-13T13:29:24.895Z
TOTAL: 378
SUCCESS: 370
FAIL: 6
SKIPPED: 2

2023-09-13 13:44 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9611](http://condorpiedra.andes.gob.ar:85/9611/mochawesome.html)
CYPRESS RUN: [8727](https://dashboard.cypress.io/projects/xr7gft/runs/8727/specs)
TEST START: 2023-09-13T13:43:46.713Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-09-14 14:23 UTC, MarianoCampetella requested changes

2023-09-14 14:23 UTC, MarianoCampetella commented on src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.component.ts
> +        return false;
Esto se puede simplificar con una ternaria:
return (indiceTurno === this.indiceTurno && ...) ? true : false

2023-09-14 14:23 UTC, MarianoCampetella commented on src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.html
> +                    subtitulo="{{ turnoSeleccionado.paciente | nombre }} | DNI: {{turnoSeleccionado.paciente.documento}}">
Ya que se esta utilizando el pipe de nombre, tambien utilizarlo para documento. Seria '| documento'

2023-09-14 14:23 UTC, MarianoCampetella commented on src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.html
> +                        subtitulo="DNI: {{turnoSeleccionado.paciente.documento}}">
Utilizar el pipe de documento

2023-09-14 14:23 UTC, MarianoCampetella commented on src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.html
> +    <!-- <div class="row" *ngIf="turnoSeleccionado?.reasignado?.siguiente"> -->
Eliminar comentario

2023-09-14 14:23 UTC, MarianoCampetella commented on src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.html
> +            *ngIf="turnoSeleccionado && !turnoSeleccionado?.reasignado?.siguiente && agendasSimilares?.length > 0">
Cuando los *ngIf son largos y con varias condiciones, lo mejor seria armar una función dentro del ts con todo lo que se tena que verificar para que sea mucho mas legible el HTML. A dicha condición no agregarle el > 0 ya que el .length se ecarga de verificarlo.

2023-09-14 14:23 UTC, MarianoCampetella commented on src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.html
> +                                            getHora(turno.horaInicio) > getHora(hoy)) || (getFecha(hoy) !== getFecha(agenda.horaInicio))">
Similar a lo anterior, armar una función e incluir todo lo que se vaya comprar.

2023-09-14 14:23 UTC, MarianoCampetella commented on src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno.html
> +                    <plex-label *ngIf="agendaAReasignar.profesionales?.length > 0" titulo="Profesionales"
sacar el > 0 al igual que en todos los .length > 0

2023-09-14 14:23 UTC, MarianoCampetella commented on src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno.html
> +                    </plex-wrapper> -->
Eliminar todos los codigos comentados que existan dentro del html

2023-09-18 18:39 UTC, JuanIRamirez commented on src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.html
> +    <!-- <div class="row" *ngIf="turnoSeleccionado?.reasignado?.siguiente"> -->
Hecho

2023-09-19 12:14 UTC, JuanIRamirez commented on src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.html
> +    <!-- <div class="row" *ngIf="turnoSeleccionado?.reasignado?.siguiente"> -->
Hecho

2023-09-19 12:14 UTC, JuanIRamirez commented on src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.html
> +                    subtitulo="{{ turnoSeleccionado.paciente | nombre }} | DNI: {{turnoSeleccionado.paciente.documento}}">
Hecho

2023-09-19 12:15 UTC, JuanIRamirez commented on src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.html
> +                        subtitulo="DNI: {{turnoSeleccionado.paciente.documento}}">
Hecho

2023-09-19 12:19 UTC, JuanIRamirez commented on src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.html
> +            *ngIf="turnoSeleccionado && !turnoSeleccionado?.reasignado?.siguiente && agendasSimilares?.length > 0">
Hecho

2023-09-19 12:31 UTC, JuanIRamirez commented on src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.html
> +                                            getHora(turno.horaInicio) > getHora(hoy)) || (getFecha(hoy) !== getFecha(agenda.horaInicio))">
Hecho

2023-09-26 14:40 UTC, JuanIRamirez commented on src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno.html
> +                    <plex-label *ngIf="agendaAReasignar.profesionales?.length > 0" titulo="Profesionales"
Hecho

2023-09-28 13:43 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9697](http://condorpiedra.andes.gob.ar:85/9697/mochawesome.html)
CYPRESS RUN: [8809](https://dashboard.cypress.io/projects/xr7gft/runs/8809/specs)
TEST START: 2023-09-28T13:43:43.470Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-09-29 13:51 UTC, AgosLizzi requested changes
1. El writing no es el correcto. En una misma oración se repiten 2 veces las palabras y por debajo en una especia de "bajada" nuevamente se repite. Demasiado redundante
![Captura de pantalla 2023-09-28 152312](https://github.com/andes/app/assets/72876985/c3ad58eb-2dfa-4bb4-b642-301eea318d8e)

2. Hay tooltip cortado 
![Captura de pantalla 2023-09-28 154252](https://github.com/andes/app/assets/72876985/7b641256-c7bb-4553-8ae8-1b76d5fad0b5)

3. La grilla de horario deberia mostrarse con un espacio entre card y card. Tal cual como se define en la libreria de plex. Adjunto ejemplos: 
![Captura de pantalla 2023-09-28 153514](https://github.com/andes/app/assets/72876985/99979d90-05e6-430c-93d2-2f9d7775f7e0)
![Captura de pantalla 2023-09-28 153550](https://github.com/andes/app/assets/72876985/dbe73748-4da0-4b3a-99aa-bcd5f402acfd)
 Se ve la diferencia? 
![image](https://github.com/andes/app/assets/72876985/1f657b03-22bb-4f22-8b5c-6db6bc76c87a)

4.  Mensaje que aparece por unos segundos ... es adrede? https://www.loom.com/share/d83594b62fef42cf9faacc305001a69a
5.  No se cual fue la decisión de cambiar los iconos 
![image](https://github.com/andes/app/assets/72876985/8cfa2225-f00a-4e3d-a941-89ccfec38d71)
![image](https://github.com/andes/app/assets/72876985/8a2ec7cc-64ff-4fe2-888c-72e1e3a3e886)

6. En general veo muchas cositas de tamaños y alineaciones. Te adjunto un par de ejemplos:
![image](https://github.com/andes/app/assets/72876985/cc84a73b-e900-4ed7-a6e4-817da73b0a80)
y a su vez ,esta la tipografía como demasiado grande, no se si es porque esta en bold, pero da la sensación que esta gigante. Me pasa lo mismo con el item de arriba (tanto en el sidebar como en el main). Otra cosa a observar es el centrado en los card de horarios.
7. Este mouseover del listado estaria bueno que se muestre así 
![image](https://github.com/andes/app/assets/72876985/f821b1a0-4d4d-449f-b14e-38cbf9b1a962)

![image](https://github.com/andes/app/assets/72876985/9c9faf06-19a2-4f1c-a953-f949ad7b76d9)

8. El modal sigue enorme
![image](https://github.com/andes/app/assets/72876985/1501f525-d02e-47cf-8ef9-2ad16a31c991)
9. SI el equipo de salud lo muestro sobre el listado, por que repetirlo nuevamente?
![image](https://github.com/andes/app/assets/72876985/a21ed85e-1be0-4768-9cd5-121801716d8e)

10. Hay un pequeño delay para cargar el modal. Apenas damos a confirmar debería aparecer y si le damos aceptar ahi visualizamos el resultado final de la pantalla
https://www.loom.com/share/b36a7f23d4a84e8986287967eaedf787
11. Esto debería visualizarse de manera correcta 
![image](https://github.com/andes/app/assets/72876985/60ba53b1-3f3a-4ea1-94f3-79b082b70f33)
12. La acción del hipervinculo que te lleva a crear una nueva agenda, es práctica, pero cuando creo la agenda, me vuelve a dejar en la pantalla de auditoria que sigo sin ver la agenda (porque no esta publicada) el caminito debería ser distinto.
13. Se ven las diferencias? 
![h](https://github.com/andes/app/assets/72876985/61f929c8-9348-498d-9727-8ce7ee87319a)
![image](https://github.com/andes/app/assets/72876985/64a62bc8-8445-4405-a4ab-f57083e612b4)
El heading debería mostrarse con ese background que te di de ejemplo, sumado a que el que esta implementado en reasignación esta muy separado del title

2023-10-12 12:17 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9769](http://condorpiedra.andes.gob.ar:85/9769/mochawesome.html)
CYPRESS RUN: [8879](https://dashboard.cypress.io/projects/xr7gft/runs/8879/specs)
TEST START: 2023-10-12T12:16:54.855Z
TOTAL: 403
SUCCESS: 398
FAIL: 3
SKIPPED: 2

2023-10-12 14:13 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9770](http://condorpiedra.andes.gob.ar:85/9770/mochawesome.html)
CYPRESS RUN: [8880](https://dashboard.cypress.io/projects/xr7gft/runs/8880/specs)
TEST START: 2023-10-12T14:12:56.218Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

2023-10-12 18:27 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9771](http://condorpiedra.andes.gob.ar:85/9771/mochawesome.html)
CYPRESS RUN: [8881](https://dashboard.cypress.io/projects/xr7gft/runs/8881/specs)
TEST START: 2023-10-12T18:27:01.774Z
TOTAL: 403
SUCCESS: 398
FAIL: 3
SKIPPED: 2

2023-10-13 13:02 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9773](http://condorpiedra.andes.gob.ar:85/9773/mochawesome.html)
CYPRESS RUN: [8883](https://dashboard.cypress.io/projects/xr7gft/runs/8883/specs)
TEST START: 2023-10-13T13:02:32.248Z
TOTAL: 403
SUCCESS: 398
FAIL: 3
SKIPPED: 2

2023-10-18 12:53 UTC, AgosLizzi requested changes
Juan, no estoy viendo los cambios solicitados. Cualquier cosa avisame y lo vemos. Acordate de siempre tener como referencia el mockup

2023-12-13 11:48 UTC, AgosLizzi commented
Juan, sigo sin ver los cambios solicitados en el comentario de septiembre. Cualquier cosa avisame

2024-02-14 14:00 UTC, JuanIRamirez commented
> 1. El writing no es el correcto. En una misma oración se repiten 2 veces las palabras y por debajo en una especia de "bajada" nuevamente se repite. Demasiado redundante
>    ![Captura de pantalla 2023-09-28 152312](https://private-user-images.githubusercontent.com/72876985/271601180-c3ad58eb-2dfa-4bb4-b642-301eea318d8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MTk0OTMsIm5iZiI6MTcwNzkxOTE5MywicGF0aCI6Ii83Mjg3Njk4NS8yNzE2MDExODAtYzNhZDU4ZWItMmRmYS00YmI0LWI2NDItMzAxZWVhMzE4ZDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDEzNTk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhOTNmODAwZWE3N2Y0ZmNiMWU2OTdiYzZjZTZkZWY0OTI4NTVlNGQyM2YwYmU1YjNhNDkyZjhkMGNhNmQyOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cm8rLlIpa5XwqKraGvAOj38mKLqoi4iFznj0YnUWG7I)
> 2. Hay tooltip cortado
>    ![Captura de pantalla 2023-09-28 154252](https://private-user-images.githubusercontent.com/72876985/271601575-7b641256-c7bb-4553-8ae8-1b76d5fad0b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MTk0OTMsIm5iZiI6MTcwNzkxOTE5MywicGF0aCI6Ii83Mjg3Njk4NS8yNzE2MDE1NzUtN2I2NDEyNTYtYzdiYi00NTUzLThhZTgtMWI3NmQ1ZmFkMGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDEzNTk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2ZTBlZmY1ZjY3ZDk5NDRiMmVjMjYyMWE4ODk4YTNiZTc4MDZkNmRiZGUxODU2MGFhNTQyZTEzNmY1ZTQxNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7vsDNMEm_JfwcwW3LbO4bchGB6oafxjffGwW0zuGjEg)
> 3. La grilla de horario deberia mostrarse con un espacio entre card y card. Tal cual como se define en la libreria de plex. Adjunto ejemplos:
>    ![Captura de pantalla 2023-09-28 153514](https://private-user-images.githubusercontent.com/72876985/271602114-99979d90-05e6-430c-93d2-2f9d7775f7e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MTk0OTMsIm5iZiI6MTcwNzkxOTE5MywicGF0aCI6Ii83Mjg3Njk4NS8yNzE2MDIxMTQtOTk5NzlkOTAtMDVlNi00MzBjLTkzZDItMmY5ZDc3NzVmN2UwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDEzNTk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxZTM0NmJmMDFmNjg1NDNiZWJiMWIyMWY4MThhMDEwZGNjOGE0MWU3NmRhYmM1ZjZkZmU2YTA1MzljYmE2ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BEeWFEXp0e_zkPh8xQ0hbjV3oKhmt-BjKk66bXFK4-c)
>    ![Captura de pantalla 2023-09-28 153550](https://private-user-images.githubusercontent.com/72876985/271602128-dbe73748-4da0-4b3a-99aa-bcd5f402acfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MTk0OTMsIm5iZiI6MTcwNzkxOTE5MywicGF0aCI6Ii83Mjg3Njk4NS8yNzE2MDIxMjgtZGJlNzM3NDgtNGRhMC00YjNhLTk5YWEtYmNkNWY0MDJhY2ZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDEzNTk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1YWE4NWFhNTg1MjIyNjk5MjAyMTlhYzQyMWYzMjNlODJjOGFjMzZmMjkwOWU0YjE0NTE0ZDFkMDI0MmVlOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.89MEJEA4M3PJV73CHWYSs4ffmF0hcvM6QQNaOgaGT9w)
>    Se ve la diferencia?
>    ![image](https://private-user-images.githubusercontent.com/72876985/271602438-1f657b03-22bb-4f22-8b5c-6db6bc76c87a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MTk0OTMsIm5iZiI6MTcwNzkxOTE5MywicGF0aCI6Ii83Mjg3Njk4NS8yNzE2MDI0MzgtMWY2NTdiMDMtMjJiYi00ZjIyLThiNWMtNmRiNmJjNzZjODdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDEzNTk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZDkyMjU3OTQwNTEzMGNhNDczNzM0ZDMyMTFhYmM3ZDc1MTgyMDEwMDU4ZjMyYTc0NWI3MmE0MzYwMTY3OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NI0jI18JmMTM3mKB7qbYGfy55AtzSSciGLGamxGyJl0)
> 4. Mensaje que aparece por unos segundos ... es adrede? https://www.loom.com/share/d83594b62fef42cf9faacc305001a69a
> 5. No se cual fue la decisión de cambiar los iconos
>    ![image](https://private-user-images.githubusercontent.com/72876985/271604629-8cfa2225-f00a-4e3d-a941-89ccfec38d71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MTk0OTMsIm5iZiI6MTcwNzkxOTE5MywicGF0aCI6Ii83Mjg3Njk4NS8yNzE2MDQ2MjktOGNmYTIyMjUtZjAwYS00ZTNkLWE5NDEtODljY2ZlYzM4ZDcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDEzNTk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViYTdiZGQwM2Y3OWZjZjUwNzY0OWMyNjU0OGU0MTdhM2Q3MDkyZDBmZmIxZGIxMzViNTMxNDZiODk1N2U5YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ohratDf7-YMMKRCIc3YNaUkbZhlCWVLRAMSlJU-uEio)
>    ![image](https://private-user-images.githubusercontent.com/72876985/271604732-8a2ec7cc-64ff-4fe2-888c-72e1e3a3e886.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MTk0OTMsIm5iZiI6MTcwNzkxOTE5MywicGF0aCI6Ii83Mjg3Njk4NS8yNzE2MDQ3MzItOGEyZWM3Y2MtNjRmZi00ZmUyLTg4OGMtNzJlMWUzYTNlODg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDEzNTk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjZTUxMmEzNjQ0ZmRjYWE2OWQxMjcxOTMwNjgwMTgyNzk3Mzg3Mzc2ZmJjYjYwZWRkMjhhZjkxYTYyNWJlMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wWSdarRtoL6el8doZ_qhTcqh8hsVfkZCCwmM1Dmnqmg)
> 6. En general veo muchas cositas de tamaños y alineaciones. Te adjunto un par de ejemplos:
>    ![image](https://private-user-images.githubusercontent.com/72876985/271605895-cc84a73b-e900-4ed7-a6e4-817da73b0a80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MTk0OTMsIm5iZiI6MTcwNzkxOTE5MywicGF0aCI6Ii83Mjg3Njk4NS8yNzE2MDU4OTUtY2M4NGE3M2ItZTkwMC00ZWQ3LWE2ZTQtODE3ZGE3M2IwYTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDEzNTk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiYzJhZjIwZTllMWQ1NGZkODk5YjRmYTBlYzM2M2U4YzMxZjQ5Yjk2ZmI5ZGNkMmJhMTM1ZDdjOWUyY2IxY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2cKlCd5VJTOsgfivf-J4qp5hGfm8GUw9TLJXfSIi_bw)
>    y a su vez ,esta la tipografía como demasiado grande, no se si es porque esta en bold, pero da la sensación que esta gigante. Me pasa lo mismo con el item de arriba (tanto en el sidebar como en el main). Otra cosa a observar es el centrado en los card de horarios.
> 7. Este mouseover del listado estaria bueno que se muestre así
>    ![image](https://private-user-images.githubusercontent.com/72876985/271606980-f821b1a0-4d4d-449f-b14e-38cbf9b1a962.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvb [...]

2024-02-14 14:17 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [10480](http://condorpiedra.andes.gob.ar:85/10480/mochawesome.html)
CYPRESS RUN: [9581](https://dashboard.cypress.io/projects/xr7gft/runs/9581/specs)
TEST START: 2024-02-14T14:17:16.283Z
TOTAL: 402
SUCCESS: 396
FAIL: 3
SKIPPED: 3

2024-02-14 14:54 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [10481](http://condorpiedra.andes.gob.ar:85/10481/mochawesome.html)
CYPRESS RUN: [9582](https://dashboard.cypress.io/projects/xr7gft/runs/9582/specs)
TEST START: 2024-02-14T14:53:33.660Z
TOTAL: 91
SUCCESS: 0
FAIL: 91
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-02-14 15:38 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [10482](http://condorpiedra.andes.gob.ar:85/10482/mochawesome.html)
CYPRESS RUN: [9583](https://dashboard.cypress.io/projects/xr7gft/runs/9583/specs)
TEST START: 2024-02-14T15:37:38.900Z
TOTAL: 398
SUCCESS: 387
FAIL: 9
SKIPPED: 2

2024-02-16 13:29 UTC, negro89 commented
@JuanIRamirez en que estado esta este pr? (Consulto porque no logro ver todos los cambios)

2024-03-08 14:23 UTC, JuanIRamirez commented
> @JuanIRamirez en que estado esta este pr? (Consulto porque no logro ver todos los cambios)

Están todos los cambio hechos. Hay que ver el botón CREAR NUEVA AGENDA , vuelve a la pantalla de reasignación, se sigue sin ver la agenda (porque no esta publicada) el c

2024-04-11 14:40 UTC, AgosLizzi requested changes
Lauti, se podrá invertir la posición de los botones, por fa?
![image](https://github.com/andes/app/assets/72876985/f0f20f6f-ec82-4719-95c6-e588eb29cb6e)

Un par de observaciones más. Te dejo video al final de los cometarios:
1. SI sobre el detalle no tengo datos de contactos que aparezca "sin datos", porque queda un poco raro que en alguno los muestre y en otro no (parece un error)
2. El modal sigue un poco grande, sobre todo en su ancho. Y observá que hay un pequeño delay en aparecer al dar confirmar... Lo mismo para el icono de solicitud, tiene sentido mostrarlo si no hay datos?
3.  El error de la consola

_Video:_ https://www.loom.com/share/a1a2e49bafe440ba80a3bd19fd5263e5

2024-05-10 19:21 UTC, negro89 commented
@AgosLizzi ya estan hechas las correcciones. Agregué el caso para extranjeros con nro de identificacion que no se habia tenido en cuenta. Dejo videito.
https://www.loom.com/share/1be563b64e574858acb2aabeb04e1b67?sid=7c5e9a8d-bca8-4afb-aedb-f2ba0fbab3e7

2024-05-13 15:08 UTC, AgosLizzi approved these changes

2024-05-15 15:12 UTC, negro89 approved these changes

2024-05-15 16:32 UTC, negro89 commented
Test al 15/05/24
![image](https://github.com/andes/app/assets/37875706/526b51c4-e21a-441f-87ea-cc5c56b569dd)

2024-05-22 18:05 UTC, merged