TOP - Deshacer una solicitud auditada
andes/app pull request #2925
Opened 2023-09-27 14:33 UTC by aldoEMatamala

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/TOP-163
### Funcionalidad desarrollada 

1. Se agrega opción "volver a auditoria" en dropdown de una solicitud en estado pendiente sin turno en bandeja de entrada.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2023-09-27 14:50 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9669](http://condorpiedra.andes.gob.ar:85/9669/mochawesome.html)
CYPRESS RUN: [8783](https://dashboard.cypress.io/projects/xr7gft/runs/8783/specs)
TEST START: 2023-09-27T14:50:02.835Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-09-29 14:18 UTC, AgosLizzi approved these changes

2023-10-02 13:05 UTC, MarianoCampetella requested changes

2023-10-02 13:05 UTC, MarianoCampetella commented on src/app/components/top/solicitudes/solicitudes.component.ts
> +        this.plex.confirm('¿Realmente quiere volver al estado Auditoría?', 'Atención').then(confirmar => {
En la mayoría de los mensajes se suele colocar "Desea ...." antes que un "Realmente..."

2023-10-02 13:05 UTC, MarianoCampetella commented on src/app/components/top/solicitudes/solicitudes.component.ts
> +                    estado: { tipo: 'auditoria', observaciones: 'Cambio de estado a Auditoria' }
Tal ves seria idea un mensaje como: "La solicitud pasó a estado Auditoria"

2023-10-02 13:05 UTC, MarianoCampetella commented on src/app/components/top/solicitudes/solicitudes.component.ts
> +            if (botones.auditar || botones.darTurno || (botones.iniciarPrestacion && this.isPresentationEnabled(prestacion)) || botones.citarPaciente//
Ya que estamos aprovechar a eliminar las barras de comentario //

2023-10-19 17:59 UTC, aldoEMatamala commented on src/app/components/top/solicitudes/solicitudes.component.ts
> +            if (botones.auditar || botones.darTurno || (botones.iniciarPrestacion && this.isPresentationEnabled(prestacion)) || botones.citarPaciente//
Borrado

2023-10-25 18:12 UTC, AgosLizzi approved these changes

2023-10-31 02:32 UTC, negro89 approved these changes

2023-10-31 11:15 UTC, MarianoCampetella approved these changes

2023-11-16 15:55 UTC, merged