CIT - Reasigna turnos en agenda suspendida desde TOP
andes/app pull request #2927
Opened 2023-09-27 16:19 UTC by ma7payne

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-242

### Funcionalidad desarrollada 

1. Se implementa el método "reasignarTurno" que, basado en un id de turno suspendido, realiza la reasignación del mismo en la nueva agenda.
2. La agenda suspendida actualiza el estado del turno reasignado.
3. Se utiliza el método "hayTurnoSuspendido" para chequear la existencia de un ultimo turno suspendido.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2023-09-27 17:11 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9677](http://condorpiedra.andes.gob.ar:85/9677/mochawesome.html)
CYPRESS RUN: [8791](https://dashboard.cypress.io/projects/xr7gft/runs/8791/specs)
TEST START: 2023-09-27T17:02:26.024Z
TOTAL: 403
SUCCESS: 391
FAIL: 10
SKIPPED: 2

2023-09-29 17:45 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9707](http://condorpiedra.andes.gob.ar:85/9707/mochawesome.html)
CYPRESS RUN: [8819](https://dashboard.cypress.io/projects/xr7gft/runs/8819/specs)
TEST START: 2023-09-29T17:44:07.052Z
TOTAL: 355
SUCCESS: 345
FAIL: 8
SKIPPED: 2

2023-10-30 15:43 UTC, MarianoCampetella requested changes

2023-10-30 15:43 UTC, MarianoCampetella commented on src/app/components/turnos/dar-turnos/dar-turnos.component.ts
> +    reasignarTurno(turno_id, agenda_actual) {
Como buenas practicas se debe evitar que los subscribes se vayan anidando. 
https://www.yaircarreno.com/2020/08/utilizar-operadores-y-evitar-anidar.html?m=0

2023-11-10 19:41 UTC, ma7payne commented on src/app/components/turnos/dar-turnos/dar-turnos.component.ts
> +    reasignarTurno(turno_id, agenda_actual) {
Listo la resolución sin subscribe anidado, cambio por un switchMap para completar la operacion. Quedo atento!

2023-12-07 13:18 UTC, Fabio-Ramirez approved these changes
Ok!... Se realizó prueba con la prestación mencionada en la sugerencia y la prestación "consulta de medicina general". Quedaría actualizar la rama.

2023-12-15 15:18 UTC, negro89 approved these changes

2023-12-15 15:53 UTC, merged