(MAT) Pantalla creacion usuario
andes/app pull request #2930
Opened 2023-10-03 15:51 UTC by JuanIRamirez

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/MAT-151

### Funcionalidad desarrollada 

1. El timeout que da al intentar enviar email, (guarda el usuario), solo me dió en la subse, en mi casa anduvo OK.
2. El error de validación en un caso estudiado (Ape, nom, 32247536) se dá porque ese documento está duplicado, le cambié a 32247540 y validó OK.
3. Debajo del <form> agregué la leyenda: **Los datos deben ser ingresados tal cual figuran en el DNI.**
4. Se cambiaron plex.info('danger'...) por plex.info('warning', ...)
5. Se cambió <plex-text> por <plex-int ... max="100000000"> p/N° documento.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [X] Si
- [ ] No

2023-10-03 18:44 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9729](http://condorpiedra.andes.gob.ar:85/9729/mochawesome.html)
CYPRESS RUN: [8837](https://dashboard.cypress.io/projects/xr7gft/runs/8837/specs)
TEST START: 2023-10-03T18:43:44.946Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-10-05 12:42 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9739](http://condorpiedra.andes.gob.ar:85/9739/mochawesome.html)
CYPRESS RUN: [8850](https://dashboard.cypress.io/projects/xr7gft/runs/8850/specs)
TEST START: 2023-10-05T12:42:16.049Z
TOTAL: 368
SUCCESS: 358
FAIL: 8
SKIPPED: 2

2023-10-05 13:34 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9740](http://condorpiedra.andes.gob.ar:85/9740/mochawesome.html)
CYPRESS RUN: [8851](https://dashboard.cypress.io/projects/xr7gft/runs/8851/specs)
TEST START: 2023-10-05T13:34:22.351Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-10-10 13:38 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9760](http://condorpiedra.andes.gob.ar:85/9760/mochawesome.html)
CYPRESS RUN: [8870](https://dashboard.cypress.io/projects/xr7gft/runs/8870/specs)
TEST START: 2023-10-10T13:38:25.822Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-10-30 15:56 UTC, AgosLizzi requested changes
Juan, porque al momento de cargar usuario la leyenda aparece sobre el "pie de página" y luego al completar los datos y validar, cambia de orientación? Te dejo video
https://www.loom.com/share/a732e13969884207995afbddf727774d?sid=29dda556-c968-4e58-937b-5b7fd87e4237

2024-01-03 17:31 UTC, MarianoCampetella commented
> Juan, porque al momento de cargar usuario la leyenda aparece sobre el "pie de página" y luego al completar los datos y validar, cambia de orientación? Te dejo video https://www.loom.com/share/a732e13969884207995afbddf727774d?sid=29dda556-c968-4e58-937b-5b7fd87e4237

Cuando valido los datos de varios usuarios no me ocurre el comportamiento mostrado en el video.

2024-01-03 18:00 UTC, MarianoCampetella approved these changes

2024-01-03 18:21 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10155](http://condorpiedra.andes.gob.ar:85/10155/mochawesome.html)
CYPRESS RUN: [9263](https://dashboard.cypress.io/projects/xr7gft/runs/9263/specs)
TEST START: 2024-01-03T18:21:23.868Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2024-01-04 12:50 UTC, Fabio-Ramirez approved these changes

2024-01-04 13:05 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10162](http://condorpiedra.andes.gob.ar:85/10162/mochawesome.html)
CYPRESS RUN: [9270](https://dashboard.cypress.io/projects/xr7gft/runs/9270/specs)
TEST START: 2024-01-04T13:05:18.461Z
TOTAL: 388
SUCCESS: 385
FAIL: 1
SKIPPED: 2

2024-01-04 13:52 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10165](http://condorpiedra.andes.gob.ar:85/10165/mochawesome.html)
CYPRESS RUN: [9273](https://dashboard.cypress.io/projects/xr7gft/runs/9273/specs)
TEST START: 2024-01-04T13:51:02.547Z
TOTAL: 371
SUCCESS: 354
FAIL: 15
SKIPPED: 2

2024-01-04 14:53 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10168](http://condorpiedra.andes.gob.ar:85/10168/mochawesome.html)
CYPRESS RUN: [9276](https://dashboard.cypress.io/projects/xr7gft/runs/9276/specs)
TEST START: 2024-01-04T14:52:52.666Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2024-01-09 15:36 UTC, AgosLizzi approved these changes

2024-01-09 18:34 UTC, merged