CIT - Crear agenda con profesional habilitado
andes/app pull request #2942
Opened 2023-10-30 12:04 UTC by JuanIRamirez

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-247

### Funcionalidad desarrollada 

1. En profesionalService se cambió atributo '**activo**'(string) por boolean.
2. En componente 'tmProfesionales' se filtra solo habilitados.
3. En 'planificar-agenda' se agregó 'habilitado: true' en el query del request.
4. En 'profesional-component' se modificó profesionalService.activo.next(this.filtros.estado ? !this.filtros.estado : null).

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2023-10-30 13:41 UTC, aldoEMatamala commented
buenas juan! te subo dos cosas q vi, una en el filtro q no hace el cambio y la otra en que me permite usar un profesional deshabilitado al crear una agenda, cualquier cosa lo vemos !


https://github.com/andes/app/assets/123381977/69985141-3d61-4c5d-b8a1-ba34bf40ebeb

2023-10-30 18:17 UTC, JuanIRamirez commented
Aldo, cambiaste la rama en API ? porque hay cambios en la API también.

2023-10-31 12:04 UTC, MarianoCampetella requested changes

2023-10-31 12:17 UTC, aldoEMatamala commented
> Aldo, cambiaste la rama en API ? porque hay cambios en la API también.

Juan, ahi estuve probando con la rama de api correspondiente y lo que te señalaba está funcionando bien, retiro la corrección anterior. Saludos

2023-10-31 12:17 UTC, aldoEMatamala approved these changes

2023-10-31 12:33 UTC, MarianoCampetella commented
![image](https://github.com/andes/app/assets/65697028/4a30d61d-8d27-4590-8026-87cf514b23c7)
Hay un caso particular que si creo una agenda para dentro de unos días con un profesional X habilitado, y si luego lo deshabilito, si quiero editar la agenda puedo seguir agregando el profesional aunque el mismo se encuentre deshabilitado.

2023-11-10 12:09 UTC, JuanIRamirez commented on src/app/services/profesional.service.ts
> +                if (activo !== null) {
Tiene que ser así, si dejo if(activo) en caso se ser 'false' no entraría al if, y la idea es que el parámetro 'habilitado' sea true o false, si  activo es null no filtra.

2023-11-21 15:17 UTC, JuanIRamirez commented
> ![image](https://user-images.githubusercontent.com/65697028/279372038-4a30d61d-8d27-4590-8026-87cf514b23c7.png) Hay un caso particular que si creo una agenda para dentro de unos días con un profesional X habilitado, y si luego lo deshabilito, si quiero editar la agenda puedo seguir agregando el profesional aunque el mismo se encuentre deshabilitado.

Corregido, en una agenda c/profesional/es cargado/s, si se deshabilita el profesional, al editar la Agenda lo quita de la lista.

2023-12-22 13:14 UTC, MarianoCampetella commented on src/app/services/profesional.service.ts
> +                if (activo !== null) {
Excelente, a demás también se chequeo que no viene undefined, solamente puede venir true/false/null

2023-12-22 13:35 UTC, MarianoCampetella approved these changes

2023-12-22 13:54 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10112](http://condorpiedra.andes.gob.ar:85/10112/mochawesome.html)
CYPRESS RUN: [9220](https://dashboard.cypress.io/projects/xr7gft/runs/9220/specs)
TEST START: 2023-12-22T13:54:34.399Z
TOTAL: 406
SUCCESS: 398
FAIL: 6
SKIPPED: 2

2023-12-22 14:24 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10114](http://condorpiedra.andes.gob.ar:85/10114/mochawesome.html)
CYPRESS RUN: [9222](https://dashboard.cypress.io/projects/xr7gft/runs/9222/specs)
TEST START: 2023-12-22T14:23:24.480Z
TOTAL: 370
SUCCESS: 358
FAIL: 11
SKIPPED: 1

2024-01-09 15:35 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10211](http://condorpiedra.andes.gob.ar:85/10211/mochawesome.html)
CYPRESS RUN: [9319](https://dashboard.cypress.io/projects/xr7gft/runs/9319/specs)
TEST START: 2024-01-09T15:33:48.809Z
TOTAL: 368
SUCCESS: 353
FAIL: 13
SKIPPED: 2

2024-01-10 13:16 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10221](http://condorpiedra.andes.gob.ar:85/10221/mochawesome.html)
CYPRESS RUN: [9329](https://dashboard.cypress.io/projects/xr7gft/runs/9329/specs)
TEST START: 2024-01-10T13:15:43.975Z
TOTAL: 401
SUCCESS: 391
FAIL: 7
SKIPPED: 3

2024-01-10 14:33 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10225](http://condorpiedra.andes.gob.ar:85/10225/mochawesome.html)
CYPRESS RUN: [9333](https://dashboard.cypress.io/projects/xr7gft/runs/9333/specs)
TEST START: 2024-01-10T14:32:25.493Z
TOTAL: 356
SUCCESS: 343
FAIL: 11
SKIPPED: 2

2024-01-10 16:15 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10229](http://condorpiedra.andes.gob.ar:85/10229/mochawesome.html)
CYPRESS RUN: [9337](https://dashboard.cypress.io/projects/xr7gft/runs/9337/specs)
TEST START: 2024-01-10T16:14:07.968Z
TOTAL: 376
SUCCESS: 365
FAIL: 8
SKIPPED: 3

2024-01-10 18:23 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10234](http://condorpiedra.andes.gob.ar:85/10234/mochawesome.html)
CYPRESS RUN: [9342](https://dashboard.cypress.io/projects/xr7gft/runs/9342/specs)
TEST START: 2024-01-10T18:23:06.417Z
TOTAL: 401
SUCCESS: 393
FAIL: 5
SKIPPED: 3

2024-01-11 15:13 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10240](http://condorpiedra.andes.gob.ar:85/10240/mochawesome.html)
CYPRESS RUN: [9348](https://dashboard.cypress.io/projects/xr7gft/runs/9348/specs)
TEST START: 2024-01-11T15:13:31.647Z
TOTAL: 401
SUCCESS: 393
FAIL: 5
SKIPPED: 3

2024-01-17 14:50 UTC, MCele commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts
> +        // let iniAgenda, finAgenda;
evitemos dejar código comentado, si no se usa es mejor eliminarlo

2024-01-25 13:54 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10332](http://condorpiedra.andes.gob.ar:85/10332/mochawesome.html)
CYPRESS RUN: [9439](https://dashboard.cypress.io/projects/xr7gft/runs/9439/specs)
TEST START: 2024-01-25T13:53:45.735Z
TOTAL: 91
SUCCESS: 0
FAIL: 91
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-26 12:08 UTC, negro89 commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts
> +        // let iniAgenda, finAgenda;
corregido

2024-01-26 12:27 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10344](http://condorpiedra.andes.gob.ar:85/10344/mochawesome.html)
CYPRESS RUN: [9451](https://dashboard.cypress.io/projects/xr7gft/runs/9451/specs)
TEST START: 2024-01-26T12:25:45.850Z
TOTAL: 349
SUCCESS: 334
FAIL: 12
SKIPPED: 3

2024-01-26 13:04 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10345](http://condorpiedra.andes.gob.ar:85/10345/mochawesome.html)
CYPRESS RUN: [9452](https://dashboard.cypress.io/projects/xr7gft/runs/9452/specs)
TEST START: 2024-01-26T13:04:24.753Z
TOTAL: 381
SUCCESS: 368
FAIL: 10
SKIPPED: 3

2024-01-26 13:17 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10346](http://condorpiedra.andes.gob.ar:85/10346/mochawesome.html)
CYPRESS RUN: [9453](https://dashboard.cypress.io/projects/xr7gft/runs/9453/specs)
TEST START: 2024-01-26T13:17:06.907Z
TOTAL: 401
SUCCESS: 393
FAIL: 5
SKIPPED: 3

2024-01-26 13:32 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10347](http://condorpiedra.andes.gob.ar:85/10347/mochawesome.html)
CYPRESS RUN: [9454](https://dashboard.cypress.io/projects/xr7gft/runs/9454/specs)
TEST START: 2024-01-26T13:32:42.954Z
TOTAL: 401
SUCCESS: 393
FAIL: 5
SKIPPED: 3

2024-01-26 13:56 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10349](http://condorpiedra.andes.gob.ar:85/10349/mochawesome.html)
CYPRESS RUN: [9456](https://dashboard.cypress.io/projects/xr7gft/runs/9456/specs)
TEST START: 2024-01-26T13:56:44.967Z
TOTAL: 388
SUCCESS: 380
FAIL: 5
SKIPPED: 3

2024-01-26 14:20 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10351](http://condorpiedra.andes.gob.ar:85/10351/mochawesome.html)
CYPRESS RUN: [9458](https://dashboard.cypress.io/projects/xr7gft/runs/9458/specs)
TEST START: 2024-01-26T14:20:36.112Z
TOTAL: 401
SUCCESS: 392
FAIL: 6
SKIPPED: 3

2024-01-26 14:48 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10353](http://condorpiedra.andes.gob.ar:85/10353/mochawesome.html)
CYPRESS RUN: [9460](https://dashboard.cypress.io/projects/xr7gft/runs/9460/specs)
TEST START: 2024-01-26T14:48:38.540Z
TOTAL: 367
SUCCESS: 358
FAIL: 6
SKIPPED: 3

2024-01-26 15:36 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10356](http://condorpiedra.andes.gob.ar:85/10356/mochawesome.html)
CYPRESS RUN: [9463](https://dashboard.cypress.io/projects/xr7gft/runs/9463/specs)
TEST START: 2024-01-26T15:35:38.667Z
TOTAL: 401
SUCCESS: 392
FAIL: 6
SKIPPED: 3

2024-01-26 16:55 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10359](http://condorpiedra.andes.gob.ar:85/10359/mochawesome.html)
CYPRESS RUN: [9466](https://dashboard.cypress.io/projects/xr7gft/runs/9466/specs)
TEST START: 2024-01-26T16:54:23.916Z
TOTAL: 91
SUCCESS: 0
FAIL: 91
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-29 13:15 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10369](http://condorpiedra.andes.gob.ar:85/10369/mochawesome.html)
CYPRESS RUN: [9476](https://dashboard.cypress.io/projects/xr7gft/runs/9476/specs)
TEST START: 2024-01-29T13:14:52.736Z
TOTAL: 401
SUCCESS: 394
FAIL: 4
SKIPPED: 3

2024-01-29 16:14 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10379](http://condorpiedra.andes.gob.ar:85/10379/mochawesome.html)
CYPRESS RUN: [9486](https://dashboard.cypress.io/projects/xr7gft/runs/9486/specs)
TEST START: 2024-01-29T16:12:51.093Z
TOTAL: 347
SUCCESS: 335
FAIL: 9
SKIPPED: 3

2024-01-29 16:34 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10381](http://condorpiedra.andes.gob.ar:85/10381/mochawesome.html)
CYPRESS RUN: [9488](https://dashboard.cypress.io/projects/xr7gft/runs/9488/specs)
TEST START: 2024-01-29T16:34:15.094Z
TOTAL: 401
SUCCESS: 394
FAIL: 4
SKIPPED: 3

2024-01-29 19:06 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10386](http://condorpiedra.andes.gob.ar:85/10386/mochawesome.html)
CYPRESS RUN: [9493](https://dashboard.cypress.io/projects/xr7gft/runs/9493/specs)
TEST START: 2024-01-29T19:05:47.794Z
TOTAL: 343
SUCCESS: 339
FAIL: 1
SKIPPED: 3

2024-01-30 11:54 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10391](http://condorpiedra.andes.gob.ar:85/10391/mochawesome.html)
CYPRESS RUN: [9498](https://dashboard.cypress.io/projects/xr7gft/runs/9498/specs)
TEST START: 2024-01-30T11:53:43.384Z
TOTAL: 91
SUCCESS: 0
FAIL: 91
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-30 12:48 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10394](http://condorpiedra.andes.gob.ar:85/10394/mochawesome.html)
CYPRESS RUN: [9501](https://dashboard.cypress.io/projects/xr7gft/runs/9501/specs)
TEST START: 2024-01-30T12:47:11.334Z
TOTAL: 326
SUCCESS: 308
FAIL: 16
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-30 13:20 UTC, silviroa commented
USUARIO: silviroa  
BUILD NUMBER: [10395](http://condorpiedra.andes.gob.ar:85/10395/mochawesome.html)
CYPRESS RUN: [9502](https://dashboard.cypress.io/projects/xr7gft/runs/9502/specs)
TEST START: 2024-01-30T13:20:33.771Z
TOTAL: 401
SUCCESS: 397
FAIL: 1
SKIPPED: 3

2024-01-30 13:59 UTC, silviroa commented
USUARIO: silviroa  
BUILD NUMBER: [10397](http://condorpiedra.andes.gob.ar:85/10397/mochawesome.html)
CYPRESS RUN: [9504](https://dashboard.cypress.io/projects/xr7gft/runs/9504/specs)
TEST START: 2024-01-30T13:58:29.488Z
TOTAL: 295
SUCCESS: 277
FAIL: 15
SKIPPED: 3
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-30 15:48 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10399](http://condorpiedra.andes.gob.ar:85/10399/mochawesome.html)
CYPRESS RUN: [9506](https://dashboard.cypress.io/projects/xr7gft/runs/9506/specs)
TEST START: 2024-01-30T15:48:02.820Z
TOTAL: 401
SUCCESS: 399
FAIL: -1
SKIPPED: 3

2024-01-31 14:49 UTC, negro89 approved these changes

2024-01-31 14:56 UTC, merged