RUP - Implementa mockups en punto de inicio
andes/app pull request #2945
Opened 2023-11-03 16:12 UTC by ma7payne

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/RUP-370

### Funcionalidad desarrollada 

1. Implementa rediseño basado en mockup para punto de inicio
2. Implementa rediseño basado en mockup para selección de pacientes en agenda dinámica

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2023-11-07 17:09 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9878](http://condorpiedra.andes.gob.ar:85/9878/mochawesome.html)
CYPRESS RUN: [8985](https://dashboard.cypress.io/projects/xr7gft/runs/8985/specs)
TEST START: 2023-11-07T16:39:25.899Z
TOTAL: 352
SUCCESS: 275
FAIL: 76
SKIPPED: 1

2023-11-08 18:08 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9881](http://condorpiedra.andes.gob.ar:85/9881/mochawesome.html)
CYPRESS RUN: [8988](https://dashboard.cypress.io/projects/xr7gft/runs/8988/specs)
TEST START: 2023-11-08T18:06:55.587Z
TOTAL: 326
SUCCESS: 301
FAIL: 23
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-11-10 12:23 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9886](http://condorpiedra.andes.gob.ar:85/9886/mochawesome.html)
CYPRESS RUN: [8993](https://dashboard.cypress.io/projects/xr7gft/runs/8993/specs)
TEST START: 2023-11-10T11:52:06.069Z
TOTAL: 403
SUCCESS: 335
FAIL: 66
SKIPPED: 2

2023-11-14 14:50 UTC, AgosLizzi requested changes
Mati, te dejo un par de cositas que vi: 

1. Los botones cambian de visual cuando cambio de pantalla. Fijate también que en el mismo video cuando quiero abrir un listado "fuera de agenda" no me deja, recien cuando lo abrí desde otro dif, me deja pasar al que quiero. te dejo video: https://www.loom.com/share/1e8b2faa976a4e858552ca29969a52ec + 
![image](https://github.com/andes/app/assets/72876985/b122e2d4-d513-4e0d-acf1-d59cb2fb2515)

2. Por fa agregar la línea gris divisora 
![image](https://github.com/andes/app/assets/72876985/bb9584e8-5c26-4086-8283-863c74ca2ec6)

3.  Re ordenar tooltip hacia la izquierda, no importa que se superponga con los botones.
![image](https://github.com/andes/app/assets/72876985/8033e741-4414-41e2-9ded-48a1d069a5d3)

4. No carga bien las agendas, por alguna razón cuando cambio de pantalla, me refresca y ahi carga las que corresponde. Te dejo video: https://www.loom.com/share/683ed0805b064cae81c68194be23c2f0

2023-11-16 13:05 UTC, ma7payne commented
> Mati, te dejo un par de cositas que vi:
> 
> 1. Los botones cambian de visual cuando cambio de pantalla. Fijate también que en el mismo video cuando quiero abrir un listado "fuera de agenda" no me deja, recien cuando lo abrí desde otro dif, me deja pasar al que quiero. te dejo video: https://www.loom.com/share/1e8b2faa976a4e858552ca29969a52ec +
>    ![image](https://user-images.githubusercontent.com/72876985/282810642-b122e2d4-d513-4e0d-acf1-d59cb2fb2515.png)
> 2. Por fa agregar la línea gris divisora
>    ![image](https://user-images.githubusercontent.com/72876985/282810939-bb9584e8-5c26-4086-8283-863c74ca2ec6.png)
> 3. Re ordenar tooltip hacia la izquierda, no importa que se superponga con los botones.
>    ![image](https://user-images.githubusercontent.com/72876985/282811387-8033e741-4414-41e2-9ded-48a1d069a5d3.png)
> 4. No carga bien las agendas, por alguna razón cuando cambio de pantalla, me refresca y ahi carga las que corresponde. Te dejo video: https://www.loom.com/share/683ed0805b064cae81c68194be23c2f0

Listos los cambios!

2023-11-17 11:57 UTC, AgosLizzi requested changes
Mati, van correcciones:

1. Hay varios badge que estan mal acomodados o quedaron fuera de contextos. Ye adjunto capturas: 
- ![badgeRUP](https://github.com/andes/app/assets/72876985/4857d5f3-0fd3-4d58-9d49-32e5e2eb40e2)

- ![0badge rup](https://github.com/andes/app/assets/72876985/cdfdba48-9fa8-4350-ac0f-8e8e522ab506)
- ![image](https://github.com/andes/app/assets/72876985/d556e025-8df5-4c97-a924-0abc20e69255)



Si vas al mockup los badge estan en otra posición, no se si fue adrede cambiarlos o simplemente quedaron así

2. Te adjunto un video donde sucede algo parecido a la primera observación, pero con el botón, cuando voy a "registrar inasistencia", el botón de "revertir cambios" quedá en un lugar donde no debería. https://www.loom.com/share/c31658f8f48e4b05bbf07f4601be6603
3. Este tooltip, que paso? Observar también el botón, me parece que no es correcto.
![rup tooltip](https://github.com/andes/app/assets/72876985/f049b5f0-db0c-4edb-aa4f-8bd724c1067b)
4. Cuando doy un sobreturno, queda así. Acomodar situación con botones y agregar plex title de sobreturnos, por favor.
![Rup sobreturnos](https://github.com/andes/app/assets/72876985/531e0611-866d-42d9-9ffe-aa72bf0f94ce)
5. La acción de autocitado esta mal. Fijate que en demo esta bien la implementación... Como primera instancia en este caso el botón de "iniciar prestación" esta de más.
![Rup autocitado](https://github.com/andes/app/assets/72876985/de36ff37-8514-4299-ab32-6a921afb5839)

2023-12-06 17:04 UTC, ma7payne commented
> Mati, van correcciones:
> 
> 1. Hay varios badge que estan mal acomodados o quedaron fuera de contextos. Ye adjunto capturas:
> 
> * ![badgeRUP](https://private-user-images.githubusercontent.com/72876985/283776090-4857d5f3-0fd3-4d58-9d49-32e5e2eb40e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NzAxMDMsIm5iZiI6MTcwMTg2OTgwMywicGF0aCI6Ii83Mjg3Njk4NS8yODM3NzYwOTAtNDg1N2Q1ZjMtMGZkMy00ZDU4LTlkNDktMzJlNWUyZWI0MGUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDEzMzY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYTQ1NTFkODM0N2MxMmFlMzgyMjM1ZTMwNzkzNTY0Y2I4MjMxYmY1MjQyM2JiMGQwMjVmNGY2ZjBlMmMwNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QDoR59M_hLtbn5aBWBDcXbwcDKHenoriIMeAfTopP1I)
> * ![0badge rup](https://private-user-images.githubusercontent.com/72876985/283776204-cdfdba48-9fa8-4350-ac0f-8e8e522ab506.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NzAxMDMsIm5iZiI6MTcwMTg2OTgwMywicGF0aCI6Ii83Mjg3Njk4NS8yODM3NzYyMDQtY2RmZGJhNDgtOWZhOC00MzUwLWFjMGYtOGU4ZTUyMmFiNTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDEzMzY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlOGUzZGM3ODEwZjE0OTMyNmVjOWUxMDVmMGQwZDliZmEwNTcwM2JmMWVhOTA5YzllMWQwODRlY2UyM2Y3Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VkSybEX1dBl54aDi8AjEhBogcNX-eWIitrEcp2n4Aq8)
> * ![image](https://private-user-images.githubusercontent.com/72876985/283793966-d556e025-8df5-4c97-a924-0abc20e69255.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NzAxMDMsIm5iZiI6MTcwMTg2OTgwMywicGF0aCI6Ii83Mjg3Njk4NS8yODM3OTM5NjYtZDU1NmUwMjUtOGRmNS00Yzk3LWE5MjQtMGFiYzIwZTY5MjU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDEzMzY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNDE2NDE3MzhjZjQ4OGFhMGIxZmJjMGVkNjA5MWJjNjQ4ZGYxNDllNzVkYWEzNWE4MDhlZDljMTBmNmRiZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qm6xjwl6w4p8xSjnx76tOQHJvir_RS1zzWcwX-0KeZ8)
> 
> Si vas al mockup los badge estan en otra posición, no se si fue adrede cambiarlos o simplemente quedaron así
> 
> 2. Te adjunto un video donde sucede algo parecido a la primera observación, pero con el botón, cuando voy a "registrar inasistencia", el botón de "revertir cambios" quedá en un lugar donde no debería. https://www.loom.com/share/c31658f8f48e4b05bbf07f4601be6603
> 3. Este tooltip, que paso? Observar también el botón, me parece que no es correcto.
>    ![rup tooltip](https://private-user-images.githubusercontent.com/72876985/283777739-f049b5f0-db0c-4edb-aa4f-8bd724c1067b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NzAxMDMsIm5iZiI6MTcwMTg2OTgwMywicGF0aCI6Ii83Mjg3Njk4NS8yODM3Nzc3MzktZjA0OWI1ZjAtZGIwYy00ZWRiLWFhNGYtOGJkNzI0YzEwNjdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDEzMzY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNWJhNTIzNDQ2MTEwZjlmMzFlMDE0ZDRkM2VlN2U1ZjFlN2E1NGIyM2YxMjM2YTg2NmY5MGExNmRhM2IwNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NG3Zi1hduHRN-6zHuuatN7NtFUJ7PkwOWYJebn15dX4)
> 4. Cuando doy un sobreturno, queda así. Acomodar situación con botones y agregar plex title de sobreturnos, por favor.
>    ![Rup sobreturnos](https://private-user-images.githubusercontent.com/72876985/283778018-531e0611-866d-42d9-9ffe-aa72bf0f94ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NzAxMDMsIm5iZiI6MTcwMTg2OTgwMywicGF0aCI6Ii83Mjg3Njk4NS8yODM3NzgwMTgtNTMxZTA2MTEtODY2ZC00MmQ5LTlmZmUtYWE3MmJmMGY5NGNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDEzMzY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkOTNlZjNlZDJhMmMzYTE5NzUxMjkzNTM3MDk2YzkxYWUyZDAxODgyYzBmMzFhNDBhZDIzYzM0NjAyYzY0NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ioJ73fz_KhjK5Qaw8sMW31q8lo4cR9461TitBMgazuM)
> 5. La acción de autocitado esta mal. Fijate que en demo esta bien la implementación... Como primera instancia en este caso el botón de "iniciar prestación" esta de más.
>    ![Rup autocitado](https://private-user-images.githubusercontent.com/72876985/283793326-de36ff37-8514-4299-ab32-6a921afb5839.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NzAxMDMsIm5iZiI6MTcwMTg2OTgwMywicGF0aCI6Ii83Mjg3Njk4NS8yODM3OTMzMjYtZGUzNmZmMzctODUxNC00Mjk5LWFiMzItNmE5MjFhZmI1ODM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDEzMzY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzNDk1YWU5MTc0MmUzYWFhOGE5ZjU4OTBmZmIwODMwOGFjZTE1YzlkNzJmOTAzOWM0NGQ5Mzk3NjY3MWU4MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cnOO9yfN4QnORDzDwHLg8IHbBvK9_HPe62NcQNhxAfY)

@AgosLizzi Estan listos los nuevos cambios!

2023-12-07 15:40 UTC, AgosLizzi requested changes
Mati, van nuevos cambios:

1.  Hay un problema con el scroll y el label. Desde mi opinión, no se si es necesario el doble scroll, el que va sobre el listado ocasiona muchos problemas. Y luego el label queda como estático. Va video adjunto https://www.loom.com/share/0daf14ccbcb84e098dc11c606a265120
2. En sobreturno los badge se repiten y el botón queda mal ubicado 
![sobreturno](https://github.com/andes/app/assets/72876985/90a22dec-e3cf-4968-9389-d848895ff2b3)
3. Consulta, hay posibilidad que los badge queden uno al lado del otro y no uno sobre el otro? 
![badge00](https://github.com/andes/app/assets/72876985/03fa5767-1851-4ca5-b0a0-a09299b2b402)
4. Y por último, muy parecido al ejemplo 1, desde autocitado sucede lo siguiente:
https://www.loom.com/share/2d0c44a14e3f47c9a25e55dd84014e55
*El principio del video, yo me confundí y empecé a grabar en demo, desestimalo por fa.

2024-01-10 14:15 UTC, MarianoCampetella commented
Ya que estamos agregarle un espacio entre ambos botones para una mejor visualización!
![image](https://github.com/andes/app/assets/65697028/8a83b35e-049f-4530-84b7-22f5e3cde36d)

2024-01-10 15:31 UTC, MarianoCampetella requested changes

2024-01-10 15:31 UTC, MarianoCampetella commented on src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts
> +            this.max = new Date();
Ver si es posible cambiar a moment() para no utilizar new Date()

2024-01-10 15:31 UTC, MarianoCampetella commented on src/app/modules/rup/components/ejecucion/puntoInicio.html
> +                                                 type="danger btn-sm" (click)="invalidarPrestacion(prestacion)">
Esta función dentro del ts tiene dos argumentos cuando en el HTML tiene una sola. 
Eliminar el parámetro que no sea necesario por parte del ts.

2024-01-15 16:29 UTC, ma7payne commented
Listos los cambios pedidos por @AgosLizzi y @MarianoCampetella !

2024-01-15 17:06 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10272](http://condorpiedra.andes.gob.ar:85/10272/mochawesome.html)
CYPRESS RUN: [9379](https://dashboard.cypress.io/projects/xr7gft/runs/9379/specs)
TEST START: 2024-01-15T16:33:48.370Z
TOTAL: 401
SUCCESS: 333
FAIL: 65
SKIPPED: 3

2024-01-15 18:07 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10273](http://condorpiedra.andes.gob.ar:85/10273/mochawesome.html)
CYPRESS RUN: [9380](https://dashboard.cypress.io/projects/xr7gft/runs/9380/specs)
TEST START: 2024-01-15T17:35:05.652Z
TOTAL: 360
SUCCESS: 274
FAIL: 83
SKIPPED: 3

2024-01-16 15:28 UTC, AgosLizzi requested changes
Mati, deberiamos analizar la posibilidad de sacar el scroll cuando se genera el listado, y solo dejar el del sidebar. Resulta un tanto molesto 
![00](https://github.com/andes/app/assets/72876985/aad7ea42-bb8e-47a9-a4d2-3d4ebd589abd)
https://www.loom.com/share/72b7e02e197e4328872c02c83617f7ee

- Cuando damos click al botón "ver huds" me salta este error 
![0verhuds](https://github.com/andes/app/assets/72876985/af840b89-ff47-4e88-8f36-df1ad9a70287)

-  Este botón, hay que cambiarlo para que aparezca con su color deshabilitado + tooltip. Te dejo captura ![IP](https://github.com/andes/app/assets/72876985/1ae14be4-4809-499b-8eec-48557f35f896) 
![Punto de inicio-22](https://github.com/andes/app/assets/72876985/62c79a39-6e8c-472a-8369-9155cb228dc8)

2024-01-18 11:25 UTC, AgosLizzi commented
Mati, vi este detalle de color en los badge. Cuando doy la asistencia de un turnos sobre una agenda y un sobreturno, los badge se muestran diferentes. 
![pb](https://github.com/andes/app/assets/72876985/063a0107-fa79-4bf9-ae44-1eb70c19b40c)
![baddge2](https://github.com/andes/app/assets/72876985/30bdbefa-e2ef-4496-8283-4f3aa0f4308d)
![badge](https://github.com/andes/app/assets/72876985/2e162741-6ea2-425b-8feb-66e5100c6b75)

- Ambos deberían quedar en verde!

2024-01-18 13:29 UTC, ma7payne commented
Listos los cambios en bdges pedidos por @AgosLizzi !

2024-01-18 14:19 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10306](http://condorpiedra.andes.gob.ar:85/10306/mochawesome.html)
CYPRESS RUN: [9413](https://dashboard.cypress.io/projects/xr7gft/runs/9413/specs)
TEST START: 2024-01-18T13:47:15.624Z
TOTAL: 401
SUCCESS: 332
FAIL: 66
SKIPPED: 3

2024-01-18 15:52 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10308](http://condorpiedra.andes.gob.ar:85/10308/mochawesome.html)
CYPRESS RUN: [9415](https://dashboard.cypress.io/projects/xr7gft/runs/9415/specs)
TEST START: 2024-01-18T15:22:17.701Z
TOTAL: 401
SUCCESS: 333
FAIL: 65
SKIPPED: 3

2024-01-18 16:28 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10309](http://condorpiedra.andes.gob.ar:85/10309/mochawesome.html)
CYPRESS RUN: [9416](https://dashboard.cypress.io/projects/xr7gft/runs/9416/specs)
TEST START: 2024-01-18T15:58:22.403Z
TOTAL: 401
SUCCESS: 333
FAIL: 65
SKIPPED: 3

2024-01-22 17:55 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10321](http://condorpiedra.andes.gob.ar:85/10321/mochawesome.html)
CYPRESS RUN: [9428](https://dashboard.cypress.io/projects/xr7gft/runs/9428/specs)
TEST START: 2024-01-22T17:54:19.827Z
TOTAL: 91
SUCCESS: 0
FAIL: 91
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-22 18:10 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10322](http://condorpiedra.andes.gob.ar:85/10322/mochawesome.html)
CYPRESS RUN: [9429](https://dashboard.cypress.io/projects/xr7gft/runs/9429/specs)
TEST START: 2024-01-22T18:09:22.877Z
TOTAL: 330
SUCCESS: 305
FAIL: 22
SKIPPED: 3

2024-01-22 18:28 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10323](http://condorpiedra.andes.gob.ar:85/10323/mochawesome.html)
CYPRESS RUN: [9430](https://dashboard.cypress.io/projects/xr7gft/runs/9430/specs)
TEST START: 2024-01-22T18:27:20.001Z
TOTAL: 371
SUCCESS: 349
FAIL: 20
SKIPPED: 2

2024-01-23 12:17 UTC, AgosLizzi approved these changes

2024-01-23 12:53 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10327](http://condorpiedra.andes.gob.ar:85/10327/mochawesome.html)
CYPRESS RUN: [9434](https://dashboard.cypress.io/projects/xr7gft/runs/9434/specs)
TEST START: 2024-01-23T12:53:22.493Z
TOTAL: 389
SUCCESS: 375
FAIL: 11
SKIPPED: 3

2024-01-25 14:31 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10335](http://condorpiedra.andes.gob.ar:85/10335/mochawesome.html)
CYPRESS RUN: [9442](https://dashboard.cypress.io/projects/xr7gft/runs/9442/specs)
TEST START: 2024-01-25T14:31:16.721Z
TOTAL: 421
SUCCESS: 406
FAIL: 12
SKIPPED: 3

2024-01-26 14:24 UTC, Fabio-Ramirez requested changes

2024-01-26 14:24 UTC, Fabio-Ramirez commented on src/app/modules/rup/components/ejecucion/prestacionCrear.html
> +    <div *ngIf="!loading && resultadoBusqueda && !resultadoBusqueda.length" class="alert alert-danger">
Se podría simplificar el resultadoBusqueda && !resultadoBusqueda.length, por el signo de encadenamiento no nulo !resultadoBusqueda?.length

2024-01-26 14:24 UTC, Fabio-Ramirez commented on src/app/modules/rup/components/ejecucion/prestacionCrear.html
> +<ng-container *ngIf="paciente && paciente.id">
Idem a la observacion anterior, se puede simplificar esta línea

2024-01-31 15:29 UTC, ma7payne commented on src/app/modules/rup/components/ejecucion/prestacionCrear.html
> +<ng-container *ngIf="paciente && paciente.id">
Este caso esta corregido!

2024-01-31 15:30 UTC, ma7payne commented on src/app/modules/rup/components/ejecucion/prestacionCrear.html
> +    <div *ngIf="!loading && resultadoBusqueda && !resultadoBusqueda.length" class="alert alert-danger">
Para este caso no es posible aplicar la sugerencia porque se debe chequear que resultadoBusqueda no sea null y además sea vacio.

2024-01-31 15:31 UTC, ma7payne commented
Listos los últimos cambios pedidos por @Fabio-Ramirez

2024-03-05 13:14 UTC, Fabio-Ramirez reviewed
Mati por el video que te envié por slack, te dejo estas observaciones... 

- El logo "iniciar prestación" no sería el mismo que el mockup.
- Cuando cierro el sidebar al momento de estar cargando una prestación, algo se rompe.
- En el autocitado no se ve la opción de iniciar la prestación.

2024-03-07 18:34 UTC, MarianoCampetella commented
Concuerdo con el comentario de Fabi de que "En el autocitado no se ve la opción de iniciar la prestación"

2024-04-09 13:33 UTC, AgosLizzi requested changes
@Fabio-Ramirez @MarianoCampetella. El botón "iniciar prestación" desde autocitado, no se muestra porque el que da acción es otro componente. Les dejo un video desde demo (esta actualización quedó de antes que se inicie el mockup de punto de inicio). https://www.loom.com/share/25391417e6cf4a2f980d85b98c1c9836

- Lo que habría que corregir es el final del camino. Cuando doy confirmar al turno, no me debería seguir mostrando el paciente. Te dejo video:
https://www.loom.com/share/5ddfba5600ef4902bb1b6fbd3ac3261b

- el badge "no asistió" podría corregirse, por favor?
![image](https://github.com/andes/app/assets/72876985/11a1f624-dbf4-406f-b710-9c769c575e10)

2024-05-20 17:53 UTC, ma7payne commented
> @Fabio-Ramirez @MarianoCampetella. El botón "iniciar prestación" desde autocitado, no se muestra porque el que da acción es otro componente. Les dejo un video desde demo (esta actualización quedó de antes que se inicie el mockup de punto de inicio). https://www.loom.com/share/25391417e6cf4a2f980d85b98c1c9836
> 
> * Lo que habría que corregir es el final del camino. Cuando doy confirmar al turno, no me debería seguir mostrando el paciente. Te dejo video:
>   https://www.loom.com/share/5ddfba5600ef4902bb1b6fbd3ac3261b
> * el badge "no asistió" podría corregirse, por favor?
>   ![image](https://private-user-images.githubusercontent.com/72876985/320862537-11a1f624-dbf4-406f-b710-9c769c575e10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMjY5NTUsIm5iZiI6MTcxNjIyNjY1NSwicGF0aCI6Ii83Mjg3Njk4NS8zMjA4NjI1MzctMTFhMWY2MjQtZGJmNC00MDZmLWI3MTAtOWM3NjljNTc1ZTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE3MzczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxODY2MTY4MTg4ZGE1NTQ1NTA1ZTBiZmFhNGNkMjEwMGZmYTQ0ODcyNTg5OGVjM2M3MWFiNDY5MzYzZGE3ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.URORjHFraowkPbNIy7GMSRmhtqvwfc6a-FZoH28SWDk)

@AgosLizzi Listo los cambios pedidos!

2024-05-21 14:52 UTC, ma7payne commented
TEST ok [(#10916)](http://condorpiedra.andes.gob.ar/job/andes-test-integracion/10916/)

2024-05-23 11:27 UTC, Fabio-Ramirez requested changes
Mati sigo viendo lo siguiente:

- El logo "iniciar prestación" no sería el mismo que el mockup.
- Cuando cierro el sidebar al momento de estar cargando una prestación, algo se rompe.

2024-05-23 18:58 UTC, ma7payne commented
> Mati sigo viendo lo siguiente:
> 
> * El logo "iniciar prestación" no sería el mismo que el mockup.
> * Cuando cierro el sidebar al momento de estar cargando una prestación, algo se rompe.

@Fabio-Ramirez Listo los cambios. Agrego cartel ante la no selección de agenda y corrijo comportamiento de sidebar. El botón de "Iniciar Prestacion" queda como está.

2024-05-24 12:57 UTC, Fabio-Ramirez approved these changes

2024-05-30 11:57 UTC, AgosLizzi requested changes
Mati, te dejo el comportamiento al aceptar un turno autocitado
https://www.loom.com/share/6449424c0cf84905b46bfb8695259b68

Fijate que al aceptar el modal, el sidebar queda abierto y podes realizar nuevamente la acción de seleccionar un horario. Estaría bueno un toast de confirmación y que cierre el sidebar

2024-06-04 14:12 UTC, ma7payne commented
> Mati, te dejo el comportamiento al aceptar un turno autocitado https://www.loom.com/share/6449424c0cf84905b46bfb8695259b68
> 
> Fijate que al aceptar el modal, el sidebar queda abierto y podes realizar nuevamente la acción de seleccionar un horario. Estaría bueno un toast de confirmación y que cierre el sidebar

@AgosLizzi quedo listo el cambio con el comportamiento del sidebar al finalizar el turno autocitado.

2024-06-04 15:20 UTC, AgosLizzi approved these changes

2024-06-05 13:37 UTC, ma7payne commented
✅ TEST OK [(#11041)](http://condorpiedra.andes.gob.ar/job/andes-test-integracion/11041/)

2024-06-05 16:00 UTC, negro89 commented
Agregar tooltip faltante para cerrar el sidebar

2024-06-07 17:49 UTC, MCele requested changes
Mati se ve hermosa la nueva pantalla :D
Te comento por aca lo que estuvimos charlando que falta revisar:

No se visualizan los fuera de agenda algunos dias (parece ser que es cuando no hay ninguna agenda para visualizar).
Cuando se visualizan los fuera de agenda debería ser un sólo item para todos los fuera de agenda cargados en el día, en cambio ahora se visualiza uno por cada prestacion cargada.
![Uploading image.png…]()

Dato de color aprovecharía a sacar el campo requerido en el selec de prestacion, ya que nunca se aplica como tal

2024-06-13 16:34 UTC, ma7payne commented
@MCele Listos los últimos cambios en la visualización del listado de agendas.

2024-06-14 13:32 UTC, ma7payne commented
Test OK [#11094](http://condorpiedra.andes.gob.ar/job/andes-test-integracion/11094/)

2024-06-14 18:51 UTC, negro89 commented
Mati, quedó joya excepto por un par de detallitos visuales que se encontraron. Estas serían las ultimas tres cositas a solucionar antes de subirlo. Va con imagenes:

1. Cuando seleccionamos una agenda con prestacion no nominalizada desde el gestor, el sidebar nos muestra información repetida.
![nominalizada x 2](https://github.com/andes/app/assets/37875706/1e2aa050-3537-4023-ad35-c4a8f6e05068)

2. La botonera de sobreturnos esta ordenada inversamente con respecto a la de turnos. Además se sugirió que el ícono para registrar la inasistencia sea _adi-account-cruz_ para no confundir con las notas. 
![botones al verrez](https://github.com/andes/app/assets/37875706/11ab4310-323c-4735-ae69-37f8aced2aeb)

3. Por ultimo, un inconveniente más que se encontró relacionado al punto 2 es que al registrar inasistencia de la tercer agenda (por ejemplo) se recarga el sidebar y queda mostrando los detalles de la primera agenda del listado; para lo cual se propone, además de mantener en el sidebar la información de la agenda seleccionada, resaltar esta agenda en el listado al igual que en el gestor.
Imagen de la información que se muestra seguido a registrar inasistencia en la 3er agenda del listado: 
![foco agenda](https://github.com/andes/app/assets/37875706/0b2c8414-2cd0-4ed0-ba06-f4203627001f)

2024-06-24 13:41 UTC, ma7payne commented
![image](https://github.com/andes/app/assets/7356452/9577e733-e5b3-47cb-9cf4-41921faed0f0)



> Mati, quedó joya excepto por un par de detallitos visuales que se encontraron. Estas serían las ultimas tres cositas a solucionar antes de subirlo. Va con imagenes:
> 
> 1. Cuando seleccionamos una agenda con prestacion no nominalizada desde el gestor, el sidebar nos muestra información repetida.
>    ![nominalizada x 2](https://private-user-images.githubusercontent.com/37875706/339867065-1e2aa050-3537-4023-ad35-c4a8f6e05068.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMzY2NDMsIm5iZiI6MTcxOTIzNjM0MywicGF0aCI6Ii8zNzg3NTcwNi8zMzk4NjcwNjUtMWUyYWEwNTAtMzUzNy00MDIzLWFkMzUtYzRhOGY2ZTA1MDY4LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQxMzM5MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2VkZWQwN2U5MTgyZTU3M2ZmNzFmZjllMzVhODRkMTllNjI2ZTkxNWUxYWJmYWM0Y2FlNmM4N2EyZjhjY2IxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vFlJlSb_ZYBfSLjuK7fnASZWQQ5Hp0S3ai0GqtyrFok)
> 2. La botonera de sobreturnos esta ordenada inversamente con respecto a la de turnos. Además se sugirió que el ícono para registrar la inasistencia sea _adi-account-cruz_ para no confundir con las notas.
>    ![botones al verrez](https://private-user-images.githubusercontent.com/37875706/339869033-11ab4310-323c-4735-ae69-37f8aced2aeb.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMzY2NDMsIm5iZiI6MTcxOTIzNjM0MywicGF0aCI6Ii8zNzg3NTcwNi8zMzk4NjkwMzMtMTFhYjQzMTAtMzIzYy00NzM1LWFlNjktMzdmOGFjZWQyYWViLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQxMzM5MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDZiNDI0Y2ZmNGI2NmY5MzgxODM2NTA2YTczNWY2MTkzMmViN2QwMWViMmVjYTA2MGEyZDU0MGUyNjZmN2I2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._cBsalk9ZSRujg2qYf2xV1iO8ZwirgqX9mXNb6d79vY)
> 3. Por ultimo, un inconveniente más que se encontró relacionado al punto 2 es que al registrar inasistencia de la tercer agenda (por ejemplo) se recarga el sidebar y queda mostrando los detalles de la primera agenda del listado; para lo cual se propone, además de mantener en el sidebar la información de la agenda seleccionada, resaltar esta agenda en el listado al igual que en el gestor.
>    Imagen de la información que se muestra seguido a registrar inasistencia en la 3er agenda del listado:
>    ![foco agenda](https://private-user-images.githubusercontent.com/37875706/339873771-0b2c8414-2cd0-4ed0-ba06-f4203627001f.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMzY2NDMsIm5iZiI6MTcxOTIzNjM0MywicGF0aCI6Ii8zNzg3NTcwNi8zMzk4NzM3NzEtMGIyYzg0MTQtMmNkMC00ZWQwLWJhMDYtZjQyMDM2MjcwMDFmLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQxMzM5MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGUxMmRjZmYzYWQ1MmY1NGUxZmY3ZDFkMDk0NDE0NmZhMTNiMGI3ZGJkNTFiNWNjN2U5YzZiYWQwOTk2ZDNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YysLZa5r7y8C6ImQGEjbqS-PlFw9FCdJGJjC45vsseM)

@negro89 Listos los cambios en los botones y en la actualización de la vista para evitar el cambio de agenda (puntos 2 y 3). El punto numero 1 corresponde a una vista del gestor de agendas. Quedo atento!

2024-06-25 14:27 UTC, merged