CIT - Ventanilla: No dar turno en agenda dinamica
andes/app pull request #2946
Opened 2023-11-09 12:49 UTC by JuanIRamirez

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-249

### Funcionalidad desarrollada 

1. Se modificó <**dar-turnos**> para que inabilite botón [**DAR TURNO**] si la agenda Dinámica no es del día de la fecha.
2. Se corrigió <**calendario**> para que muestre correctamente **label e iconos** de cant.agendas y turnos disp.
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2023-12-22 14:49 UTC, MarianoCampetella requested changes

2023-12-22 14:49 UTC, MarianoCampetella commented on src/app/components/turnos/dar-turnos/calendario.component.ts
> +        return (dia.dinamicasIndefinidas > 0 && moment(dia.fecha).format('DD/MM/YYYY') > moment().format('DD/MM/YYYY'));
ya que utilizamos moment, las comparaciones de las fechas no son a través de los símbolos <, > o = sino con isBefore, isAfter, etc. En la siguiente documentación hay varios ejemplos para trabajar sobre las comparaciones: https://momentjs.com/docs/

2023-12-22 14:49 UTC, MarianoCampetella commented on src/app/components/turnos/dar-turnos/dar-turnos.component.ts
> +        return (moment(this.agenda.horaInicio).format('DD/MM/YYYY') === moment().format('DD/MM/YYYY'));
Similar al comentario anterior!

2023-12-22 14:51 UTC, MarianoCampetella commented
Se subo alguna librería nueva o alguna actualización al package-lock.json?
En caso contrario deshacer dichos cambios.

2024-01-09 16:03 UTC, ma7payne commented
Espero a la realización de los cambios propuestos por campe para finalizar review.

2024-01-09 16:35 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10214](http://condorpiedra.andes.gob.ar:85/10214/mochawesome.html)
CYPRESS RUN: [9322](https://dashboard.cypress.io/projects/xr7gft/runs/9322/specs)
TEST START: 2024-01-09T16:34:58.463Z
TOTAL: 406
SUCCESS: 400
FAIL: 4
SKIPPED: 2

2024-01-10 12:55 UTC, AgosLizzi approved these changes
Se creo tarea para analizar las mejoras visuales [UIUX-374](https://proyectos.andes.gob.ar/browse/UIUX-374)

2024-01-12 12:00 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10246](http://condorpiedra.andes.gob.ar:85/10246/mochawesome.html)
CYPRESS RUN: [9353](https://dashboard.cypress.io/projects/xr7gft/runs/9353/specs)
TEST START: 2024-01-12T11:59:20.217Z
TOTAL: 91
SUCCESS: 0
FAIL: 91
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-12 12:16 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10247](http://condorpiedra.andes.gob.ar:85/10247/mochawesome.html)
CYPRESS RUN: [9354](https://dashboard.cypress.io/projects/xr7gft/runs/9354/specs)
TEST START: 2024-01-12T12:16:29.469Z
TOTAL: 383
SUCCESS: 377
FAIL: 3
SKIPPED: 3

2024-01-12 13:14 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10249](http://condorpiedra.andes.gob.ar:85/10249/mochawesome.html)
CYPRESS RUN: [9356](https://dashboard.cypress.io/projects/xr7gft/runs/9356/specs)
TEST START: 2024-01-12T13:13:10.588Z
TOTAL: 363
SUCCESS: 352
FAIL: 8
SKIPPED: 3

2024-05-02 17:57 UTC, JuanIRamirez commented on src/app/components/turnos/dar-turnos/calendario.component.ts
> +        return (dia.dinamicasIndefinidas > 0 && moment(dia.fecha).format('DD/MM/YYYY') > moment().format('DD/MM/YYYY'));
Hecho

2024-05-02 17:57 UTC, JuanIRamirez commented on src/app/components/turnos/dar-turnos/dar-turnos.component.ts
> +        return (moment(this.agenda.horaInicio).format('DD/MM/YYYY') === moment().format('DD/MM/YYYY'));
Hecho

2024-05-30 12:54 UTC, Fabio-Ramirez approved these changes
Juan este pr cumple con las especificaciones iniciales. Lo que menciona  @AgosLizzi sobre una nueva sugerencia: https://proyectos.andes.gob.ar/browse/UIUX-374, será parte de otra tarea. Tener presente la actualización y testeo posterior.

2024-06-11 14:52 UTC, MarianoCampetella approved these changes

2024-06-12 15:33 UTC, merged