MPI - Modifica condición para botón de "ignorar y guardar"
andes/app pull request #2950
Opened 2023-11-14 15:11 UTC by ma7payne

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/MPI-417

### Funcionalidad desarrollada 

1. Se habilita el botón de "ignorar y guardar" tras encontrar coincidencias con otro paciente ya agregado.
2. Se implementa detector de cambios para los campos de formulario que deshabilitan botón de "ignorar y guardar".

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2023-11-14 15:30 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9919](http://condorpiedra.andes.gob.ar:85/9919/mochawesome.html)
CYPRESS RUN: [9026](https://dashboard.cypress.io/projects/xr7gft/runs/9026/specs)
TEST START: 2023-11-14T15:29:58.868Z
TOTAL: 403
SUCCESS: 397
FAIL: 4
SKIPPED: 2

2023-11-14 20:15 UTC, MCele requested changes

2023-11-14 20:15 UTC, MCele commented on src/app/core/mpi/components/paciente.component.ts
> +                        this.visualizarIgnorarGuardar = true;
cuidado con esto! porque se está quitando un control importante que evita crear pacientes duplicados.
Si el paciente seleccionado supera la cota, no debería mostrase como una solicitud de sugerencia a ignora. Ejemplo:
![image](https://github.com/andes/app/assets/19591224/99abaa44-6d8c-4bf0-a432-044e4bd1eca5)

Me parece que el error para la tarea planteada en el caso 1, trata de un paciente que ya existe como temporal y supera la cota al compararlo con un paciente nuevo ya validado (por eso el mensaje del modal da a entender eso, como si el paciente ya existiera y no como sugerencia de "paciente similar"). Si el paciente a crear es validado y ya existe en la base uno igual (supera la cota) pero que es temporal, entonces no se debería traer como sugerencia, y por ende no se guarda, pero al guardarlo la api se encarga de realizar la vinculación.
Revisar si es correcto el cambio sobre el botón, o  quizás el control va sobre la respuesta que da la api al intentar guardar un paciente.

2023-11-16 14:18 UTC, ma7payne commented on src/app/core/mpi/components/paciente.component.ts
> +                        this.visualizarIgnorarGuardar = true;
Listos los cambios! Quedo atento.

2023-11-23 15:06 UTC, Fabio-Ramirez approved these changes

2023-11-23 15:10 UTC, Fabio-Ramirez commented
Quedaria ver los tests.

2023-11-27 13:39 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9971](http://condorpiedra.andes.gob.ar:85/9971/mochawesome.html)
CYPRESS RUN: [9082](https://dashboard.cypress.io/projects/xr7gft/runs/9082/specs)
TEST START: 2023-11-27T13:36:58.601Z
TOTAL: 379
SUCCESS: 369
FAIL: 8
SKIPPED: 2

2023-11-27 13:51 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9972](http://condorpiedra.andes.gob.ar:85/9972/mochawesome.html)
CYPRESS RUN: [9083](https://dashboard.cypress.io/projects/xr7gft/runs/9083/specs)
TEST START: 2023-11-27T13:49:57.530Z
TOTAL: 369
SUCCESS: 356
FAIL: 11
SKIPPED: 2

2023-11-27 14:07 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9973](http://condorpiedra.andes.gob.ar:85/9973/mochawesome.html)
CYPRESS RUN: [9084](https://dashboard.cypress.io/projects/xr7gft/runs/9084/specs)
TEST START: 2023-11-27T14:06:37.561Z
TOTAL: 403
SUCCESS: 398
FAIL: 3
SKIPPED: 2

2023-11-27 14:31 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9975](http://condorpiedra.andes.gob.ar:85/9975/mochawesome.html)
CYPRESS RUN: [9086](https://dashboard.cypress.io/projects/xr7gft/runs/9086/specs)
TEST START: 2023-11-27T14:30:58.724Z
TOTAL: 403
SUCCESS: 398
FAIL: 3
SKIPPED: 2

2023-11-27 15:41 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9978](http://condorpiedra.andes.gob.ar:85/9978/mochawesome.html)
CYPRESS RUN: [9089](https://dashboard.cypress.io/projects/xr7gft/runs/9089/specs)
TEST START: 2023-11-27T15:41:40.258Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-11-27 16:10 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9979](http://condorpiedra.andes.gob.ar:85/9979/mochawesome.html)
CYPRESS RUN: [9090](https://dashboard.cypress.io/projects/xr7gft/runs/9090/specs)
TEST START: 2023-11-27T16:08:51.903Z
TOTAL: 326
SUCCESS: 317
FAIL: 7
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-11-27 16:23 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9980](http://condorpiedra.andes.gob.ar:85/9980/mochawesome.html)
CYPRESS RUN: [9091](https://dashboard.cypress.io/projects/xr7gft/runs/9091/specs)
TEST START: 2023-11-27T16:21:53.247Z
TOTAL: 383
SUCCESS: 375
FAIL: 6
SKIPPED: 2

2023-11-27 18:26 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9982](http://condorpiedra.andes.gob.ar:85/9982/mochawesome.html)
CYPRESS RUN: [9093](https://dashboard.cypress.io/projects/xr7gft/runs/9093/specs)
TEST START: 2023-11-27T18:26:34.168Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-11-27 19:05 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9983](http://condorpiedra.andes.gob.ar:85/9983/mochawesome.html)
CYPRESS RUN: [9094](https://dashboard.cypress.io/projects/xr7gft/runs/9094/specs)
TEST START: 2023-11-27T19:04:27.087Z
TOTAL: 372
SUCCESS: 365
FAIL: 5
SKIPPED: 2

2023-11-28 19:36 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9993](http://condorpiedra.andes.gob.ar:85/9993/mochawesome.html)
CYPRESS RUN: [9102](https://dashboard.cypress.io/projects/xr7gft/runs/9102/specs)
TEST START: 2023-11-28T19:35:28.431Z
TOTAL: 343
SUCCESS: 334
FAIL: 7
SKIPPED: 2

2023-11-29 11:36 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [9995](http://condorpiedra.andes.gob.ar:85/9995/mochawesome.html)
CYPRESS RUN: [9104](https://dashboard.cypress.io/projects/xr7gft/runs/9104/specs)
TEST START: 2023-11-29T11:35:45.979Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-12-07 19:57 UTC, MCele commented on src/app/core/mpi/components/paciente.component.ts
> +                        this.visualizarIgnorarGuardar = true;
Mati los casos planteado quedaron resueltos pero encontré uno que no se funciona como se espera.
el caso es el siguiente: si al querer guardar un paciente temporal debería verificar y visualizar similitudes con pacientes temporales y validados, pero si ya existe uno o más pacientes temporales similares (independientemente de si la cota supere o no lo el 95%) no los muestra (ver imagen). 
![image](https://github.com/andes/app/assets/19591224/40e42a9b-7eb5-4b52-9989-2611cd1c25a5)

2023-12-07 20:17 UTC, MCele commented on src/app/core/mpi/components/paciente.component.ts
> +                        this.visualizarIgnorarGuardar = true;
por las dudas comento lo que te dije personalmente para no olvidarnos, este cambio que te sugerí:
`similares[0]._score < 0.94;`
no es aplicable así textual porque el array de similares no contiene el atributo _score, se puede pensar en hacer una comparacion similar

2024-01-03 16:00 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10150](http://condorpiedra.andes.gob.ar:85/10150/mochawesome.html)
CYPRESS RUN: [9258](https://dashboard.cypress.io/projects/xr7gft/runs/9258/specs)
TEST START: 2024-01-03T15:59:17.758Z
TOTAL: 96
SUCCESS: 0
FAIL: 96
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-03 16:11 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10151](http://condorpiedra.andes.gob.ar:85/10151/mochawesome.html)
CYPRESS RUN: [9259](https://dashboard.cypress.io/projects/xr7gft/runs/9259/specs)
TEST START: 2024-01-03T16:10:56.212Z
TOTAL: 406
SUCCESS: 400
FAIL: 4
SKIPPED: 2

2024-01-03 17:34 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10152](http://condorpiedra.andes.gob.ar:85/10152/mochawesome.html)
CYPRESS RUN: [9260](https://dashboard.cypress.io/projects/xr7gft/runs/9260/specs)
TEST START: 2024-01-03T17:33:14.637Z
TOTAL: 96
SUCCESS: 0
FAIL: 96
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-03 17:47 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10153](http://condorpiedra.andes.gob.ar:85/10153/mochawesome.html)
CYPRESS RUN: [9261](https://dashboard.cypress.io/projects/xr7gft/runs/9261/specs)
TEST START: 2024-01-03T17:45:47.905Z
TOTAL: 331
SUCCESS: 313
FAIL: 16
SKIPPED: 2

2024-01-03 18:06 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10154](http://condorpiedra.andes.gob.ar:85/10154/mochawesome.html)
CYPRESS RUN: [9262](https://dashboard.cypress.io/projects/xr7gft/runs/9262/specs)
TEST START: 2024-01-03T18:05:52.658Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2024-02-05 14:57 UTC, ma7payne commented
> Al validar un paciente, el resultado de los pacientes sugeridos deben ser pacientes validados. En caso de querer guardar un temporal, las sugerencias deben incluir todos los pacientes activos (temporales y validados). Revisar la condición del matcheo y no del botón "ignorar y guardar".

Listos los cambios, quedo atento.

2024-03-07 12:08 UTC, merged