IN - Eliminar indicación en estado borrador
andes/app pull request #2954
Opened 2023-11-22 16:28 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-583

### Funcionalidad desarrollada 

1.  Se agrega un boton para eliminar las indicaciones que se encuentran en estado "borrador"
2. NOTA: en el html de plan-indicaciones.component.html solamente se modifica las lineas 125 a 128 donde se agrega dicho botón. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si   https://github.com/andes/api/pull/1853
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2023-11-22 16:41 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [9946](http://condorpiedra.andes.gob.ar:85/9946/mochawesome.html)
CYPRESS RUN: [9053](https://dashboard.cypress.io/projects/xr7gft/runs/9053/specs)
TEST START: 2023-11-22T16:40:49.299Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-11-30 13:34 UTC, AgosLizzi approved these changes

2024-01-03 14:47 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10149](http://condorpiedra.andes.gob.ar:85/10149/mochawesome.html)
CYPRESS RUN: [9257](https://dashboard.cypress.io/projects/xr7gft/runs/9257/specs)
TEST START: 2024-01-03T14:47:15.628Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2024-02-29 12:16 UTC, negro89 requested changes
Anda bien. El unico problema es que si al eliminar la indicación el sidebar con los detalles se encuentra abierto, se puede seguir visualizando los detalles e incluso editarla y guardar, obteniendo un toast de confirmación. Esto no debería suceder. Dejo videito.

https://app.screencastify.com/v3/watch/IxvXPlP7yaWfVTcKcpcK

2024-03-07 17:50 UTC, Fabio-Ramirez commented on src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
> +                                                    <div *ngIf="isToday() && permisosMapaCamasService.indicacionesEjecutar && permisosMapaCamasService.indicacionesEjecutar && !indicacionEventoSelecte
Se podría comprimir esta condición, por:  isToday() &&  permisosMapaCamasService.indicacionesEjecutar && !indicacionEventoSelected  && !indicacion?.readonly

2024-03-14 12:38 UTC, negro89 commented
Campe, el problema persiste cuando se elimina un borrador que se estaba editando. 
![image](https://github.com/andes/app/assets/37875706/381eea82-cc30-4cf6-9d23-d42a1a0590e7)
![image](https://github.com/andes/app/assets/37875706/86f97b8d-4588-426d-a2ee-5af1d4ed6064)

2024-03-15 17:46 UTC, negro89 approved these changes

2024-03-22 18:07 UTC, merged