Typ - Buscador de turnos y prestaciones - privacidad
andes/app pull request #2956
Opened 2023-11-23 12:47 UTC by JuanIRamirez

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/TYP-1

### Funcionalidad desarrollada 

1. Se agregó **@Input() verContenido** default: true en **vistaPrestación**.
2. En turnos-prestaciones.html, componente vista-prestacion [verContenido]="false"

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2023-12-12 16:00 UTC, MarianoCampetella commented
Tanto la funcionalidad como el código se encuentran bien, la única duda que me queda es porque se sumaron cambios al package-lock.json? Es necesario tener que subirlo??

2024-01-11 13:46 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10237](http://condorpiedra.andes.gob.ar:85/10237/mochawesome.html)
CYPRESS RUN: [9345](https://dashboard.cypress.io/projects/xr7gft/runs/9345/specs)
TEST START: 2024-01-11T13:46:35.725Z
TOTAL: 401
SUCCESS: 395
FAIL: 3
SKIPPED: 3

2024-01-11 13:58 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10238](http://condorpiedra.andes.gob.ar:85/10238/mochawesome.html)
CYPRESS RUN: [9346](https://dashboard.cypress.io/projects/xr7gft/runs/9346/specs)
TEST START: 2024-01-11T13:58:25.326Z
TOTAL: 401
SUCCESS: 397
FAIL: 1
SKIPPED: 3

2024-01-11 14:12 UTC, ma7payne commented on src/app/modules/rup/components/huds/vistaPrestacion.html
> +                                {{ (elemento.esSolicitud) ? 'solicitud' : elemento.concepto.semanticTag}}:&nbsp;
En caso de no mostrar solicitud el valor debería se null en lugar del caracter ASCII "&nbsp"

2024-01-11 14:15 UTC, AgosLizzi requested changes
La funcionalidad la veo bien. Hay unos minímos detalles visuales:

- En lo posible posicionar el icono para que quede centrado al relleno de color 
![Captura de pantalla 2024-01-11 110124](https://github.com/andes/app/assets/72876985/f44e3f1e-469a-491e-be95-9fd491a8e999)
![Captura de pantalla 2024-01-11 110219](https://github.com/andes/app/assets/72876985/8d992f06-975e-4686-b188-1737d562c1a5)
![Captura de pantalla 2024-01-11 110302](https://github.com/andes/app/assets/72876985/17312bf1-c14a-4ba7-97a5-f5085009d3bd)

- Lo mismo para el badge que esta dentro del componente 
![Captura de pantalla 2024-01-11 110611](https://github.com/andes/app/assets/72876985/a36790d1-b7e2-4d6c-8287-e84371659d5d)

Corregido, quedo atento.

2024-01-11 14:30 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10239](http://condorpiedra.andes.gob.ar:85/10239/mochawesome.html)
CYPRESS RUN: [9347](https://dashboard.cypress.io/projects/xr7gft/runs/9347/specs)
TEST START: 2024-01-11T14:29:42.599Z
TOTAL: 366
SUCCESS: 355
FAIL: 8
SKIPPED: 3

2024-01-11 15:01 UTC, MarianoCampetella commented
![image](https://github.com/andes/app/assets/65697028/6c05a35b-b07b-422d-af26-80f3128a5f3b)

Revisar este error en consola que ocurre cuando entro al modulo de Turnos y Prestaciones y selecciono cualquier paciente. Toda la vista con su información correspondiente se muestra normal, incluso al seleccionar otro paciente ya no ocurre dicho error.

2024-01-15 18:40 UTC, Fabio-Ramirez commented on src/app/modules/rup/components/huds/vistaPrestacion.html
> +                                {{ (elemento.esSolicitud) ? 'solicitud' : elemento.concepto.semanticTag}}:&nbsp;
Corregido!

2024-01-15 19:03 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [10274](http://condorpiedra.andes.gob.ar:85/10274/mochawesome.html)
CYPRESS RUN: [9381](https://dashboard.cypress.io/projects/xr7gft/runs/9381/specs)
TEST START: 2024-01-15T19:01:54.468Z
TOTAL: 368
SUCCESS: 358
FAIL: 7
SKIPPED: 3

2024-01-16 12:04 UTC, MarianoCampetella approved these changes

2024-01-16 12:22 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10276](http://condorpiedra.andes.gob.ar:85/10276/mochawesome.html)
CYPRESS RUN: [9383](https://dashboard.cypress.io/projects/xr7gft/runs/9383/specs)
TEST START: 2024-01-16T12:21:21.700Z
TOTAL: 91
SUCCESS: 0
FAIL: 91
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-16 12:38 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10277](http://condorpiedra.andes.gob.ar:85/10277/mochawesome.html)
CYPRESS RUN: [9384](https://dashboard.cypress.io/projects/xr7gft/runs/9384/specs)
TEST START: 2024-01-16T12:38:16.838Z
TOTAL: 392
SUCCESS: 389
FAIL: 0
SKIPPED: 3

2024-01-16 14:50 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10279](http://condorpiedra.andes.gob.ar:85/10279/mochawesome.html)
CYPRESS RUN: [9386](https://dashboard.cypress.io/projects/xr7gft/runs/9386/specs)
TEST START: 2024-01-16T14:48:42.670Z
TOTAL: 380
SUCCESS: 373
FAIL: 4
SKIPPED: 3

2024-01-16 15:57 UTC, AgosLizzi approved these changes
Gracias @Fabio-Ramirez por corregirlo

2024-01-16 18:33 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10288](http://condorpiedra.andes.gob.ar:85/10288/mochawesome.html)
CYPRESS RUN: [9395](https://dashboard.cypress.io/projects/xr7gft/runs/9395/specs)
TEST START: 2024-01-16T18:33:20.695Z
TOTAL: 401
SUCCESS: 399
FAIL: -1
SKIPPED: 3

2024-01-22 16:06 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [10319](http://condorpiedra.andes.gob.ar:85/10319/mochawesome.html)
CYPRESS RUN: [9426](https://dashboard.cypress.io/projects/xr7gft/runs/9426/specs)
TEST START: 2024-01-22T16:05:10.107Z
TOTAL: 91
SUCCESS: 0
FAIL: 91
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-23 11:32 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [10326](http://condorpiedra.andes.gob.ar:85/10326/mochawesome.html)
CYPRESS RUN: [9433](https://dashboard.cypress.io/projects/xr7gft/runs/9433/specs)
TEST START: 2024-01-23T11:31:51.411Z
TOTAL: 401
SUCCESS: 398
FAIL: 0
SKIPPED: 3

2026-04-08 20:23 UTC, closed without merging