PRIV - Visualizar motivos de acceso a la HUDS
andes/app pull request #2958
Opened 2023-11-28 17:25 UTC by aldoEMatamala

* **IN-532:** Control anular internacion ([#2853](https://github.com/andes/app/issues/2853)) ([c9cae13](https://github.com/andes/app/commit/c9cae134d3c17458cfbb5fca4862e66965fede40))

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/PRIV-65
### Funcionalidad desarrollada 

Se reemplazan los motivos de acceso a la HUDS estáticos por accesos a BD.
1. Acceso explícito a la HUDS (modal).
2. Buscador de Turnos y prestaciones.
3. Al iniciar una prestación.
4. Desde la internación (modal) de acceso a los registros y plan de indicaciones.
5. Solicitudes: bandeja de entrada/salida al iniciar una prestación.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [x] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2023-12-20 13:43 UTC, MarianoCampetella requested changes

2023-12-20 13:43 UTC, MarianoCampetella commented on src/app/modules/rup/components/huds/modal-motivo-acceso-huds.component.ts
> +import { Observable } from 'rxjs';
Remover estos dos import que no se están utilizando!

2023-12-20 15:22 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10092](http://condorpiedra.andes.gob.ar:85/10092/mochawesome.html)
CYPRESS RUN: [9200](https://dashboard.cypress.io/projects/xr7gft/runs/9200/specs)
TEST START: 2023-12-20T14:47:03.531Z
TOTAL: 360
SUCCESS: 289
FAIL: 69
SKIPPED: 2

2023-12-20 19:00 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10102](http://condorpiedra.andes.gob.ar:85/10102/mochawesome.html)
CYPRESS RUN: [9210](https://dashboard.cypress.io/projects/xr7gft/runs/9210/specs)
TEST START: 2023-12-20T18:23:57.909Z
TOTAL: 406
SUCCESS: 346
FAIL: 58
SKIPPED: 2

2023-12-22 11:49 UTC, JuanIRamirez commented
Al continuar una prestación no toma el motivo de acceso a la HUDS de la DB.

2023-12-22 11:57 UTC, JuanIRamirez commented
En el modal la opción 'Intervención en el proceso de cuidado del paciente' se solapa en 2 lineas, esto se corrige en 'modal-motivo-acceso-huds.html' (linea 7) <div class="w-60">

2024-01-04 18:38 UTC, aldoEMatamala commented on src/app/modules/rup/components/huds/modal-motivo-acceso-huds.component.ts
> +import { Observable } from 'rxjs';
corregido!

2024-01-05 18:10 UTC, aldoEMatamala commented
> En el modal la opción 'Intervención en el proceso de cuidado del paciente' se solapa en 2 lineas, esto se corrige en 'modal-motivo-acceso-huds.html' (linea 7) -div class="w-60"-

corregido! gracias !

2024-01-25 16:06 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [10337](http://condorpiedra.andes.gob.ar:85/10337/mochawesome.html)
CYPRESS RUN: [9444](https://dashboard.cypress.io/projects/xr7gft/runs/9444/specs)
TEST START: 2024-01-25T15:31:40.870Z
TOTAL: 401
SUCCESS: 341
FAIL: 57
SKIPPED: 3

2024-01-31 19:26 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [10413](http://condorpiedra.andes.gob.ar:85/10413/mochawesome.html)
CYPRESS RUN: [9518](https://dashboard.cypress.io/projects/xr7gft/runs/9518/specs)
TEST START: 2024-01-31T19:25:13.071Z
TOTAL: 333
SUCCESS: 317
FAIL: 14
SKIPPED: 2

2024-02-01 11:38 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [10415](http://condorpiedra.andes.gob.ar:85/10415/mochawesome.html)
CYPRESS RUN: [9520](https://dashboard.cypress.io/projects/xr7gft/runs/9520/specs)
TEST START: 2024-02-01T11:37:48.359Z
TOTAL: 402
SUCCESS: 399
FAIL: 0
SKIPPED: 3

2024-03-07 13:25 UTC, aldoEMatamala commented
> En el modal la opción 'Intervención en el proceso de cuidado del paciente' se solapa en 2 lineas, esto se corrige en 'modal-motivo-acceso-huds.html' (linea 7) -div class="w-60"-

resuelto gracias!

2024-03-07 18:23 UTC, aldoEMatamala commented
![imagen](https://github.com/andes/app/assets/123381977/81cb8ccc-f5fb-4503-880f-ff8e90f68ca6)

2024-04-25 19:08 UTC, MCele commented
Revisar lo siguiente:

- Al momento de cargar una nueva prestación se guarda el motivo "inicio de prestación", y eso es correcto, pero si luego se seleccionan otros motivos en el sidebar o si se continua una prestación iniciada, sigue guardando el mismo motivo y no corresponde, para esto último debería ser "Continuidad de ..." o similar.
- Tener en cuenta que el dato de "moduloDefault" debería considerarse como una clave, ya que es por la que se hacen las búsquedas, por esto debería ser indistinto que el dato esté en mayúscula o minúscula, evitar que tengan espacios en blanco, etc.

2024-05-16 15:31 UTC, aldoEMatamala commented
> Revisar lo siguiente:
> 
> * Al momento de cargar una nueva prestación se guarda el motivo "inicio de prestación", y eso es correcto, pero si luego se seleccionan otros motivos en el sidebar o si se continua una prestación iniciada, sigue guardando el mismo motivo y no corresponde, para esto último debería ser "Continuidad de ..." o similar.
> * Tener en cuenta que el dato de "moduloDefault" debería considerarse como una clave, ya que es por la que se hacen las búsquedas, por esto debería ser indistinto que el dato esté en mayúscula o minúscula, evitar que tengan espacios en blanco, etc.

Hola cele, gracias por los comentarios,
- Corregido el motivo a guardar al continuar una prestacion desde RUP.
- Se modificó en BD todos los motivos los cuales quedaron en minúscula y sin espacios en blanco

2024-05-31 18:24 UTC, negro89 requested changes
Aldinho, habría que hacer unos pequeños cambios en el esquema de este nuevo recurso:
1. Agregar una columna "key" para cada motivo
2. Renombrar el atributo "motivo" a nombre/label que es mas representativo para como venimos usando internamente los componentes que sugieren opciones
3. El atributo "descripcion" contendría texto a modo informativo para orientar al usuario (Después vemos qué, por ahora no lo utilizariamos)
4. El atributo "moduloDefault" debería ser un array, para no repetir registros en caso de compartir motivo por defecto entre varios modulos

Cualquier cosita quedo a disposición

2024-07-04 11:50 UTC, aldoEMatamala commented
![imagen](https://github.com/andes/app/assets/123381977/9165dee8-5c18-42b5-9897-607ca048030f)

2024-07-04 11:53 UTC, aldoEMatamala commented
> Aldinho, habría que hacer unos pequeños cambios en el esquema de este nuevo recurso:
> 
>     1. Agregar una columna "key" para cada motivo
> 
>     2. Renombrar el atributo "motivo" a nombre/label que es mas representativo para como venimos usando internamente los componentes que sugieren opciones
> 
>     3. El atributo "descripcion" contendría texto a modo informativo para orientar al usuario (Después vemos qué, por ahora no lo utilizariamos)
> 
>     4. El atributo "moduloDefault" debería ser un array, para no repetir registros en caso de compartir motivo por defecto entre varios modulos
> 
> 
> Por otro lado, almacenar del lado de la app el motivo y el detalle en un array puede ser un poco confuso en cuanto a recordar en qué posición se encuentra cada elemento o para el caso de los undefined. Sugeriría utilizar un objeto similar a `motivo: { key: string, detalle: string }`
> 
> Cualquier cosita quedo a disposición
buendi lautaro!
Quedan subidas las modificaciones de esquema como se charlo por slack. Así quedan los registros en demo. Saludos!
![imagen](https://github.com/andes/app/assets/123381977/8daae364-ff53-4022-8b4b-ed44b8904528)

2024-07-17 16:25 UTC, negro89 reviewed
Holi, funciona de 10 pero dejé algunas observaciones. Trato de resumirlas en ... 
1. En relación al pasaje del motivo entre el modal y los otros componentes, noté que a veces se lo trata como un objeto (uso correcto) y otras veces como valores separados. 
2. En todos los casos la búsqueda del motivo por defecto (moduloDefault) está perfecto. 
No me quería extender mucho, cualquier cosa despejamos charlando 👌🏼

2024-07-17 16:25 UTC, negro89 commented on src/app/modules/rup/components/huds/modal-motivo-acceso-huds.component.ts
> +            this.motivo = {
Acá si no se pasa el objeto completo, al menor debería respetarse las keys de la interfaz _key_ y _label_ (nuevamente para estandarizar su uso y que no varía de componente a componente).

Si el problema es identificar los valores por separado en el html, se puede acceder haciendo  _[(ngModel)]="motivo.label"_

2024-07-18 15:38 UTC, aldoEMatamala commented on src/app/components/top/solicitudes/solicitudes.component.ts
> +        const motivo = (typeof motivoAccesoHuds !== 'string') ? motivoAccesoHuds.motivo : motivoAccesoHuds;
Agregado el control!

2024-07-18 18:40 UTC, aldoEMatamala commented on src/app/modules/rup/components/huds/modal-motivo-acceso-huds.component.ts
> +            this.motivo = {
Se mantienen las dos interfaces como se charlo. Saludos!

2024-07-18 18:40 UTC, aldoEMatamala commented on src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
> +                    detalleMotivo: (typeof motivoAccesoHuds !== 'string') ? motivoAccesoHuds.descripcionAcceso : null
Se mantienen las dos interfaces como se charlo. Saludos!

2024-07-22 18:24 UTC, aldoEMatamala commented
![imagen](https://github.com/user-attachments/assets/a0b71b84-c972-4634-8236-08be50a1e029)

2024-07-30 14:24 UTC, negro89 approved these changes

2024-07-30 14:42 UTC, MarianoCampetella approved these changes

2024-07-30 16:06 UTC, merged