IN - nuevo rol de internacion: farmacia
andes/app pull request #2961
Opened 2023-12-06 16:03 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-573
https://proyectos.andes.gob.ar/browse/IN-584

### Funcionalidad desarrollada 

1.  Se agrega un nuevo rol dentro del modulo de internacion llamada FARMACEUTICO donde se puede ver la huds del paciente y trabajar sobre el plan de indicaciones.
2.  Dentro del plan de indicaciones, como farmacéutico puedo aceptar/rechazar una indicación que se encuentra en estado validada o bypasseada por el profesional.
3. Se agregaron nuevos badges (VALIDADA, SUSPENDIDA, ESPERANDO CONTROL DE FARMACIA) para indicar los estados de las indicaciones.
4. Se agregaron nuevos colores a las indicaciones para mostrar los estados en los que se encuentra. VERDE: indicación aceptada por farmacéutico, NARANJA: indicación bypasseada por el profesional.
5. Se modificó el label de suspender/rechazar una indicación ya que al hacer las dos acciones anteriores, dicho label era el mismo. Ahora se diferencia entre una accion y la otra.
6. Se agrego una nueva opcion dentro del dropdown que solamente ve el medico (profesional a cargo) con el nombre de "bypass" para poder bypassear las indicaciones y que el enfermero pueda ejecutarlas.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [X] Si   ya fue aclarado en el PR de la api
- [ ] No

### Requiere actualizaciones en la API

- [X] Si   https://github.com/andes/api/pull/1856
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2023-12-06 17:42 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10032](http://condorpiedra.andes.gob.ar:85/10032/mochawesome.html)
CYPRESS RUN: [9141](https://dashboard.cypress.io/projects/xr7gft/runs/9141/specs)
TEST START: 2023-12-06T17:42:36.323Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2024-01-03 14:37 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10148](http://condorpiedra.andes.gob.ar:85/10148/mochawesome.html)
CYPRESS RUN: [9256](https://dashboard.cypress.io/projects/xr7gft/runs/9256/specs)
TEST START: 2024-01-03T14:37:18.520Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2024-01-12 13:48 UTC, MarianoCampetella commented
> * Desde el perfil médico, agrego una indicación y la valido. Luego realizo bypass. Me voy al perfil enfermero y ejecuto la indicación. Desde el perfil farmacéutico la rechazo y vuelvo al perfil enfermero dandome cuenta que me sigue habilitando para ejecutar. **Esta acción no debería suceder.**
> * Desde el perfil médico, tengo dos botones suspender. Uno localizado en dropdown y el otro sobre la botonera. El que debería permanecer es el de la botonera, el otro se elimina.
>   ![image](https://private-user-images.githubusercontent.com/72876985/295201740-610d3954-632d-42fc-b74b-099f5d294c94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNjI5MjQsIm5iZiI6MTcwNTA2MjYyNCwicGF0aCI6Ii83Mjg3Njk4NS8yOTUyMDE3NDAtNjEwZDM5NTQtNjMyZC00MmZjLWI3NGItMDk5ZjVkMjk0Yzk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDEyMzAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNmM0MjJmYTRjODc4NjgwY2RhOGRjYTQ5YTMwMDc3MGU4NTgwZWM2OTA4MjkyNjk1NmI2NGEyZTJjZTQ5NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PPoOEiPan6ZWN_AGkZfucFECY0fKCU262_Ww_uqwGgs)
> * Ver si es posible que los contornos no se superpongan
>   ![image](https://private-user-images.githubusercontent.com/72876985/295202093-201b0b85-b867-4226-b73e-4448b1079dd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNjI5MjQsIm5iZiI6MTcwNTA2MjYyNCwicGF0aCI6Ii83Mjg3Njk4NS8yOTUyMDIwOTMtMjAxYjBiODUtYjg2Ny00MjI2LWI3M2UtNDQ0OGIxMDc5ZGQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDEyMzAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjMDk3MGUxNjQzZjA0ZTc0YzQ3NTcxY2IzNjk3NzBhMjEzZGIwMDE3Y2VmNDFhODZjNWNkOTY0NjdlOGEyYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EgP6G-Q6OJwmrn5VBjzQ4zj4Qudfobt2c5B9m7fmmJc)
> * Errores: Al suspender indicación desde capa medica
>   Al darle click a una indicación, desde capa médica. Este es el más polémico
>   Al crear una indicación, desde capa médica

Se corrigieron los dos primeros items. 
El tercero se arma una tarea para los contornos no se superpongan.
Por ultimo los errores que se observan en la consola al momento de crear, seleccionar y suspender una indicación se encuentran fixeados en la tarea: https://github.com/andes/app/pull/2954

2024-01-15 11:37 UTC, AgosLizzi approved these changes

2024-02-28 14:25 UTC, negro89 commented
Campe, cargando el mapa de camas despues de seleccionar la nueva capa se rompe todo. Quizas quedó algo mal en la resolución de conflictos. Dejo captura.

![image](https://github.com/andes/app/assets/37875706/4a6acfa5-8506-4a71-9c8a-4030a37e69e9)

2024-02-29 15:33 UTC, negro89 requested changes
Funciona hermoso, un par de detallitos nada mas:
1. En la imagenes adjuntas se pueden ver tres indicaciones; las primeras 2 estan correctas, pero la tercera (ibuprofeno) fue creada hace unos dias atrás y en su momento aceptada por farmacia. El problema es que cuando al dia de hoy se la _continúa_ sigue resaltada en verde como si estuviera aprobada (Las indicaciones que se continúan deben ser nuevamente bypasseadas/aprobadas para que enfermería pueda verlas).
2. En el video adjunto se ve que cada vez que se clickea en el menú _opciones_ de una indicación validada, se ven tantas ocurrencias de "bypass" como clicks se hayan realizado.

### Enfermería
![image](https://github.com/andes/app/assets/37875706/03ca4b10-da78-4383-85b0-26ffb2930e66)

### Farmacia
![image](https://github.com/andes/app/assets/37875706/2c6025e2-c095-4a6f-8dbe-9ea61a674318)

### Bypass repetidos:
https://app.screencastify.com/v3/watch/UpXG7CoBKctDQuNnQtUn

2024-03-07 11:34 UTC, MarianoCampetella commented
> Funciona hermoso, un par de detallitos nada mas:
> 
> 1. En la imagenes adjuntas se pueden ver tres indicaciones; las primeras 2 estan correctas, pero la tercera (ibuprofeno) fue creada hace unos dias atrás y en su momento aceptada por farmacia. El problema es que cuando al dia de hoy se la _continúa_ sigue resaltada en verde como si estuviera aprobada (Las indicaciones que se continúan deben ser nuevamente bypasseadas/aprobadas para que enfermería pueda verlas).
> 2. En el video adjunto se ve que cada vez que se clickea en el menú _opciones_ de una indicación validada, se ven tantas ocurrencias de "bypass" como clicks se hayan realizado.
> 
> ### Enfermería
> ![image](https://private-user-images.githubusercontent.com/37875706/308978715-03ca4b10-da78-4383-85b0-26ffb2930e66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTEwOTgsIm5iZiI6MTcwOTgxMDc5OCwicGF0aCI6Ii8zNzg3NTcwNi8zMDg5Nzg3MTUtMDNjYTRiMTAtZGE3OC00MzgzLTg1YjAtMjZmZmIyOTMwZTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDExMjYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3NDMxYjY5ODM4ODdjYWZkNmM1YTRkY2U1ZWU4ZjE2MDQxZmQ0ZDNjN2MwMWNjZGY1YzU4ZWMyYTgwYTZjZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g_b-1YL28-X_H6cxTvKxurCua4n3LPyXC1xzKkVGi1E)
> 
> ### Farmacia
> ![image](https://private-user-images.githubusercontent.com/37875706/308979042-2c6025e2-c095-4a6f-8dbe-9ea61a674318.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTEwOTgsIm5iZiI6MTcwOTgxMDc5OCwicGF0aCI6Ii8zNzg3NTcwNi8zMDg5NzkwNDItMmM2MDI1ZTItYzA5NS00YTZmLThkYmUtOWVhNjFhNjc0MzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDExMjYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkYWE5ZDdlMTYxYTQ4NDA0ZDJmMmU0N2IzZTUwYjliNGNlNDRiYjllNTAyMmZhZjk3NzkxYjg2M2RjOTM0OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qhc37RnnkzuvI2Yfv5rednwnNNxgc-X3BMgJ9je33pE)
> 
> ### Bypass repetidos:
> https://app.screencastify.com/v3/watch/UpXG7CoBKctDQuNnQtUn

Correcciones relalizadas:
- Cada vez que se selecciona el dropdown la opción de Bypass no se duplican los botones
- Si la medicación se encuentra en estado pendiente no se visualiza ningún botón
- Cuando se continua la medicación esta misma tiene que volver a ser bypaseada por el medico o ser aceptada/rechazada por el farmacéutico.

2024-03-11 15:45 UTC, silviroa reviewed
- Creo que estaría bueno que el cartelito que dice "indicación no aceptada" se vea en la capa de enfermería tbm 

<img width="535" alt="image" src="https://github.com/andes/app/assets/11513044/89c3c240-e5c8-459e-b586-c1c67a87f65c">

- Revisar si es necesario cargar la configuración de las secciones del plan en todas las capas
- Ver el permiso del aceptar o rechazar una indicación, si hay que chequear el permiso para el bypass

2024-03-12 12:55 UTC, silviroa approved these changes

2024-03-21 18:40 UTC, negro89 approved these changes

2024-03-22 15:23 UTC, merged