TYP - Listado de prestaciones no nominalizadas
andes/app pull request #2962
Opened 2023-12-11 17:23 UTC by ma7payne

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/TYP-5
https://proyectos.andes.gob.ar/browse/TYP-11

### Funcionalidad desarrollada 

1. Crea nuevo componente para la visualización de prestaciones "no nominalizadas".
2. Modifica el componente de búsqueda actual para excluir las prestaciones "no nominalizadas" del campo "Prestaciones".
3. Segun lo especificado en la tarea [TYP-11](https://proyectos.andes.gob.ar/browse/TYP-11), se modifica la directiva "prestaciones-select" para poder filtrar por tipo de prestacion en los listados de selección.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [x] Si
- [ ] No

Se deben actualizar el módulo de "Turnos y Prestaciones" en la colección "modulos" con los siguientes datos:

{
  "nombre": "Turnos y Prestaciones",
  "descripcion": "Buscador de turnos y prestaciones",
  "subtitulo": "Buscador",
  "linkAcceso": "/apps/mpi/busqueda",
  "color": "#7c87a5",
  "icono": "table-search",
  "activo": true,
  "submodulos": [
    {
      "activo": true,
      "permisos": [
        "mpi:?"
      ],
      "nombre": "Nominali-<br>zadas",
      "linkAcceso": "/buscador",
      "color": "#7c87a5",
      "icono": "compu-listado",
      "orden": 0
    },
    {
      "activo": true,
      "permisos": [
        "auditoriaPacientes:?"
      ],
      "nombre": "No<br>nominali-<br>zadas",
      "linkAcceso": "/buscador/no_nominalizadas",
      "color": "#005f63",
      "icono": "tilde",
      "orden": 1
    }
}

### Requiere actualizaciones en la API

- [x] Si https://github.com/andes/api/pull/1857
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2023-12-11 17:59 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10043](http://condorpiedra.andes.gob.ar:85/10043/mochawesome.html)
CYPRESS RUN: [9152](https://dashboard.cypress.io/projects/xr7gft/runs/9152/specs)
TEST START: 2023-12-11T17:58:50.215Z
TOTAL: 365
SUCCESS: 347
FAIL: 16
SKIPPED: 2

2023-12-15 18:04 UTC, AgosLizzi reviewed
Nuevo versión (1.1.22) con los iconos a utilizar 
https://www.npmjs.com/package/@andes/icons

- agenda-paciente

- calendar-cruz

Colores: #7C87A5 / #5C7BBF

2024-01-05 12:56 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10182](http://condorpiedra.andes.gob.ar:85/10182/mochawesome.html)
CYPRESS RUN: [9290](https://dashboard.cypress.io/projects/xr7gft/runs/9290/specs)
TEST START: 2024-01-05T12:47:40.875Z
TOTAL: 352
SUCCESS: 333
FAIL: 17
SKIPPED: 2

2024-01-05 13:27 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10184](http://condorpiedra.andes.gob.ar:85/10184/mochawesome.html)
CYPRESS RUN: [9292](https://dashboard.cypress.io/projects/xr7gft/runs/9292/specs)
TEST START: 2024-01-05T13:26:36.909Z
TOTAL: 385
SUCCESS: 373
FAIL: 11
SKIPPED: 1

2024-01-08 12:44 UTC, ma7payne commented
> Nuevo versión (1.1.22) con los iconos a utilizar https://www.npmjs.com/package/@andes/icons
> 
> * agenda-paciente
> * calendar-cruz
> 
> Colores: #7C87A5 / #5C7BBF

Testeados los nuevos iconos. Tener en cuenta que se aplican en bases como se menciona previamente.

2024-01-08 12:59 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10197](http://condorpiedra.andes.gob.ar:85/10197/mochawesome.html)
CYPRESS RUN: [9305](https://dashboard.cypress.io/projects/xr7gft/runs/9305/specs)
TEST START: 2024-01-08T12:57:59.287Z
TOTAL: 406
SUCCESS: 399
FAIL: 5
SKIPPED: 2

2024-01-08 13:24 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10199](http://condorpiedra.andes.gob.ar:85/10199/mochawesome.html)
CYPRESS RUN: [9307](https://dashboard.cypress.io/projects/xr7gft/runs/9307/specs)
TEST START: 2024-01-08T13:24:17.294Z
TOTAL: 406
SUCCESS: 399
FAIL: 5
SKIPPED: 2

2024-01-08 15:42 UTC, Fabio-Ramirez commented on src/app/components/buscadorTurnosPrestaciones/no-nominalizadas/no-nominalizadas.component.ts
> +        if (fechaDesde && fechaDesde.isValid() && fechaHasta && fechaHasta.isValid()) {
Utilizar el encademiento opcional "?" para simplificar codigo.

2024-01-08 15:42 UTC, Fabio-Ramirez commented on src/app/components/buscadorTurnosPrestaciones/no-nominalizadas/no-nominalizadas.html
> +                                    {{busqueda.organizacion.nombre}}
Se sugiere chequear que exista organizacion.

2024-01-08 15:42 UTC, Fabio-Ramirez commented on src/app/components/buscadorTurnosPrestaciones/no-nominalizadas/no-nominalizadas.html
> +                            {{prestacion?.estadoActual.createdAt.fecha | hora }}
Haria falta chequear que exita prestacion, cuando anteriromente se observó en el *ngIf.

2024-01-08 15:42 UTC, Fabio-Ramirez commented on src/app/components/buscadorTurnosPrestaciones/no-nominalizadas/no-nominalizadas.html
> +                    <tr *ngFor="let documento of prestacion?.documentos">
Aca igual tengo la misma consulta con prestacion, anteriormente en el div quedo chequeado.

2024-01-08 16:07 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10201](http://condorpiedra.andes.gob.ar:85/10201/mochawesome.html)
CYPRESS RUN: [9309](https://dashboard.cypress.io/projects/xr7gft/runs/9309/specs)
TEST START: 2024-01-08T16:06:07.983Z
TOTAL: 96
SUCCESS: 0
FAIL: 96
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-08 16:29 UTC, AgosLizzi requested changes
Corregir ubicación del tootip
![image](https://github.com/andes/app/assets/72876985/5c479f5f-e4d3-41d8-a658-6d7dc48424c7)

2024-01-09 14:40 UTC, Fabio-Ramirez requested changes
Mati, se observa dos cositas: 

1. El label "fuera de agenda" no estaria visible en el panel del "sidebar".
2. El filtro paciente en el buscador no deberia estar. Adjunto imagen. 
![Captura de pantalla 2024-01-09 113928](https://github.com/andes/app/assets/45831788/661aa706-c5ea-4bcc-a06f-70ce34e01132)

2024-01-15 12:20 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10262](http://condorpiedra.andes.gob.ar:85/10262/mochawesome.html)
CYPRESS RUN: [9369](https://dashboard.cypress.io/projects/xr7gft/runs/9369/specs)
TEST START: 2024-01-15T12:19:36.003Z
TOTAL: 401
SUCCESS: 396
FAIL: 2
SKIPPED: 3

2024-01-15 12:44 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10263](http://condorpiedra.andes.gob.ar:85/10263/mochawesome.html)
CYPRESS RUN: [9370](https://dashboard.cypress.io/projects/xr7gft/runs/9370/specs)
TEST START: 2024-01-15T12:43:31.468Z
TOTAL: 271
SUCCESS: 251
FAIL: 18
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-15 13:42 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10266](http://condorpiedra.andes.gob.ar:85/10266/mochawesome.html)
CYPRESS RUN: [9373](https://dashboard.cypress.io/projects/xr7gft/runs/9373/specs)
TEST START: 2024-01-15T13:41:56.489Z
TOTAL: 401
SUCCESS: 398
FAIL: 0
SKIPPED: 3

2024-01-15 14:38 UTC, AgosLizzi requested changes
Mati, al seleccionar un rango de fechas y dar click en "buscar" me saltan un par de errores. Te dejo video
https://www.loom.com/share/e96f9c0b9e0448b0a486e7f6f440a6bd

2024-01-16 15:15 UTC, ma7payne commented
> Mati, al seleccionar un rango de fechas y dar click en "buscar" me saltan un par de errores. Te dejo video https://www.loom.com/share/e96f9c0b9e0448b0a486e7f6f440a6bd

Lista la corrección de errores mostrados en consola!

2024-01-16 17:52 UTC, AgosLizzi approved these changes

2024-01-16 17:58 UTC, Fabio-Ramirez reviewed
Mati tal como lo observamos, en slack queda el videito, en el cual cuando fltras una busqueda en "X" organización y despues cambias de efector, el filtro no se limpia y por ende se visualizan los datos de la ultima búsqueda. Igual adjunto imagenes. Queda atento.
![Observación 1](https://github.com/andes/app/assets/45831788/ac770b31-8196-4ae6-ae58-72207ae48ebb)
![Observación 2](https://github.com/andes/app/assets/45831788/9d0eff1a-2399-41f6-9976-653ac5ad6faa)

2024-01-17 18:12 UTC, Fabio-Ramirez approved these changes

2024-01-18 13:42 UTC, ma7payne commented
Listos los cambios en cache pedidos por @Fabio-Ramirez

2024-02-14 14:37 UTC, merged