TYP - Corregir Acceso al buscador
andes/app pull request #2964
Opened 2023-12-13 18:49 UTC by aldoEMatamala

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/TYP-10
### Funcionalidad desarrollada 

1. Un usuario profesional que no tenga permisos para el módulo TYP podrá acceder al buscador a travéz de la dirección (...gob.ar/buscador)
2. Se visualizan las prestaciones en las que el profesional sea parte del equipo de salud.
3. Se deshabilita el campo "Equipo de salud" .

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2023-12-13 19:12 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [10053](http://condorpiedra.andes.gob.ar:85/10053/mochawesome.html)
CYPRESS RUN: [9162](https://dashboard.cypress.io/projects/xr7gft/runs/9162/specs)
TEST START: 2023-12-13T19:12:01.173Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

2023-12-14 13:06 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [10055](http://condorpiedra.andes.gob.ar:85/10055/mochawesome.html)
CYPRESS RUN: [9163](https://dashboard.cypress.io/projects/xr7gft/runs/9163/specs)
TEST START: 2023-12-14T13:05:15.541Z
TOTAL: 348
SUCCESS: 339
FAIL: 7
SKIPPED: 2

2023-12-14 13:27 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [10056](http://condorpiedra.andes.gob.ar:85/10056/mochawesome.html)
CYPRESS RUN: [9164](https://dashboard.cypress.io/projects/xr7gft/runs/9164/specs)
TEST START: 2023-12-14T13:27:35.070Z
TOTAL: 385
SUCCESS: 382
FAIL: 1
SKIPPED: 2

2023-12-14 13:47 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [10057](http://condorpiedra.andes.gob.ar:85/10057/mochawesome.html)
CYPRESS RUN: [9165](https://dashboard.cypress.io/projects/xr7gft/runs/9165/specs)
TEST START: 2023-12-14T13:47:20.970Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-12-20 18:12 UTC, MarianoCampetella requested changes

2023-12-20 18:15 UTC, MarianoCampetella commented
Según lo charlado la funcionalidad y el resto del código se encuentra de forma correcta. 
Si a futuro surgen nuevos cambios, dejarlos explícitos en el PR y charlarlo con los revisores.
Saludos Cordiales!

2023-12-21 13:58 UTC, aldoEMatamala commented on src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
> +import Integer from '@zxing/library/esm/core/util/Integer';
corregido, gracias!

2023-12-21 14:13 UTC, MarianoCampetella approved these changes

2023-12-21 16:08 UTC, JuanIRamirez approved these changes

2023-12-22 16:35 UTC, merged