PERINATAL: fix en filtros del listado
andes/app pull request #2972
Opened 2024-01-29 19:06 UTC by MCele

### Requerimiento
 

### Funcionalidad desarrollada 

1. 
2. 
3. 

### UserStory llegó a completarse

- [X
- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2024-01-29 19:43 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [10389](http://condorpiedra.andes.gob.ar:85/10389/mochawesome.html)
CYPRESS RUN: [9496](https://dashboard.cypress.io/projects/xr7gft/runs/9496/specs)
TEST START: 2024-01-29T19:41:38.906Z
TOTAL: 371
SUCCESS: 361
FAIL: 7
SKIPPED: 3

2024-01-30 12:00 UTC, MarianoCampetella requested changes

2024-01-30 12:00 UTC, MarianoCampetella commented on src/app/modules/perinatal/components/listado-perinatal.component.ts
> +            paciente: this.paciente
Esto se puede resumir mediante la propiedad "shorthand property names"  quedando solamente el atributo paciente.

2024-01-30 12:35 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10393](http://condorpiedra.andes.gob.ar:85/10393/mochawesome.html)
CYPRESS RUN: [9500](https://dashboard.cypress.io/projects/xr7gft/runs/9500/specs)
TEST START: 2024-01-30T12:34:31.619Z
TOTAL: 91
SUCCESS: 0
FAIL: 91
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-30 13:32 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10396](http://condorpiedra.andes.gob.ar:85/10396/mochawesome.html)
CYPRESS RUN: [9503](https://dashboard.cypress.io/projects/xr7gft/runs/9503/specs)
TEST START: 2024-01-30T13:32:33.849Z
TOTAL: 401
SUCCESS: 399
FAIL: -1
SKIPPED: 3

2024-01-30 14:13 UTC, MCele commented on src/app/modules/perinatal/components/listado-perinatal.component.ts
> +            paciente: this.paciente
no entiendo la sugerencia, cómo se aplicaría a este caso puntual?

2024-01-30 14:51 UTC, MarianoCampetella approved these changes

2024-01-30 17:45 UTC, silviroa approved these changes

2024-01-31 15:05 UTC, merged