GDU - Modificar email en paciente temporal
andes/app pull request #2974
Opened 2024-02-08 15:13 UTC by ma7payne

User
### Requerimiento
 
https://proyectos.andes.gob.ar/browse/GDU-62

### Funcionalidad desarrollada 

1. Agrega ventana de modificación de email con plex-help
2. Verifica que el usuario a modificar sea profesional temporal
3. Verifica permisos de usuario para poder editar email en profesional
4. Agrega slider con opción de reactivación de contraseña al guardar

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [x] Si https://github.com/andes/api/pull/1866
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2024-02-08 15:30 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [10471](http://condorpiedra.andes.gob.ar:85/10471/mochawesome.html)
CYPRESS RUN: [9572](https://dashboard.cypress.io/projects/xr7gft/runs/9572/specs)
TEST START: 2024-02-08T15:29:52.894Z
TOTAL: 402
SUCCESS: 400
FAIL: -1
SKIPPED: 3

2024-02-15 15:00 UTC, AgosLizzi requested changes
Mati, cuando edito un email y doy confirmar, el plex help queda abierto. Seria mejor si al dar confirmar se cierra. Luego, el email queda "guardado" y te lo muestra cuando queres editar otros usuarios. Adjunto video:
https://www.loom.com/share/2f97fe54f20a4237bcf9f35670017e23

2024-04-18 19:00 UTC, ma7payne commented
> Mati, cuando edito un email y doy confirmar, el plex help queda abierto. Seria mejor si al dar confirmar se cierra. Luego, el email queda "guardado" y te lo muestra cuando queres editar otros usuarios. Adjunto video: https://www.loom.com/share/2f97fe54f20a4237bcf9f35670017e23

@AgosLizzi para poder lograr lo que muestra el video deberia agregar la opcion de cierre programado al plex help, de esa forma puedo cerrarlo desde APP al guardar info. Creo tarea en PLEX y luego trasladamos este cambio.

2024-04-19 12:42 UTC, ma7payne commented
> Mati, cuando edito un email y doy confirmar, el plex help queda abierto. Seria mejor si al dar confirmar se cierra. Luego, el email queda "guardado" y te lo muestra cuando queres editar otros usuarios. Adjunto video: https://www.loom.com/share/2f97fe54f20a4237bcf9f35670017e23

@AgosLizzi listo el cambio de email guardado.

2024-04-22 17:59 UTC, AgosLizzi approved these changes

2024-05-06 19:12 UTC, negro89 commented
Mati, me descargué la rama actualizada y rebasee (sin pushear) y tengo el inconveniente de que la modificacion no impacta en la DB. A vos te pasa? Dejo video
https://www.loom.com/share/413c747f93bf4cb59f343f82e8b1cec9?sid=d92b25c7-4e17-42d3-becb-39cd44cdcd56

2024-05-20 12:38 UTC, ma7payne commented
> Mati, me descargué la rama actualizada y rebasee (sin pushear) y tengo el inconveniente de que la modificacion no impacta en la DB. A vos te pasa? Dejo video https://www.loom.com/share/413c747f93bf4cb59f343f82e8b1cec9?sid=d92b25c7-4e17-42d3-becb-39cd44cdcd56

@negro89 Por lo visto funciona todo ok, no noto el mismo error.

2024-05-20 13:00 UTC, Fabio-Ramirez approved these changes
Con respecto a las observaciones y la funcionalidad, estaría correcto esta tarea.

2024-05-21 17:33 UTC, merged