fix(IN-593): Duplicacion de egresos
andes/app pull request #2980
Opened 2024-02-22 11:48 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-593

### Funcionalidad desarrollada 

1. Se corrige bug de que al momento de editar un egreso en capa estadística, se duplicaban los mismos!
2. Se corrige bug de que al momento de egresar un paciente en el pasando cuando en el presente se hace lo mismo, no se generen egresos duplicados con diferentes fechas. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2024-02-22 13:11 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10528](http://condorpiedra.andes.gob.ar:85/10528/mochawesome.html)
CYPRESS RUN: [9629](https://dashboard.cypress.io/projects/xr7gft/runs/9629/specs)
TEST START: 2024-02-22T13:10:48.074Z
TOTAL: 399
SUCCESS: 389
FAIL: 8
SKIPPED: 2

2024-02-22 13:27 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10529](http://condorpiedra.andes.gob.ar:85/10529/mochawesome.html)
CYPRESS RUN: [9630](https://dashboard.cypress.io/projects/xr7gft/runs/9630/specs)
TEST START: 2024-02-22T13:25:46.154Z
TOTAL: 371
SUCCESS: 359
FAIL: 10
SKIPPED: 2

2024-02-26 17:20 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10559](http://condorpiedra.andes.gob.ar:85/10559/mochawesome.html)
CYPRESS RUN: [9653](https://dashboard.cypress.io/projects/xr7gft/runs/9653/specs)
TEST START: 2024-02-26T17:19:54.647Z
TOTAL: 399
SUCCESS: 397
FAIL: 0
SKIPPED: 2

2024-04-22 18:10 UTC, Fabio-Ramirez requested changes
Campe, el código lo veo bien. Lo único que recalco es lo que estuvimos viendo que la opcion "desocupar" se sigue visualizando. Adjunto imagenes. Este seria el caso del paciente egresado el 18/03/2024 
![image](https://github.com/andes/app/assets/45831788/0d153b61-7830-457a-bd5f-ca0cb04e8cbd) y cuando lo "busco" aparece la opción "descocupar" 
![image](https://github.com/andes/app/assets/45831788/c106d34d-00f0-496e-be69-560a1f8f3fee)

2024-10-18 12:28 UTC, negro89 commented
Se resuelve en https://github.com/andes/app/pull/3004

2024-10-18 12:28 UTC, closed without merging