TOP - Implementa mockups para reglas de entrada
andes/app pull request #2982
Opened 2024-03-05 18:52 UTC by ma7payne

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/TOP-158

### Funcionalidad desarrollada 

1.  Aplica mockuos en pantallas de creación de reglas de entrada.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [X] Si
- [ ] No

2024-03-07 14:05 UTC, AgosLizzi requested changes
Mati, solo un par de observaciones:

1. Cuando quiero eliminar la organización de origen, me genera la selección para la visualización del sidebar. Eso no deberí funcionar asi, si decido eliminar, se elimina sin mostrar nada. Tal cual funciona actualmente. También fijate que salta un error en consola... Capaz a ese botón le falta un tooltip y/o mensaje que avise al usuario https://www.loom.com/share/fb70907a51474a09957084d1b158b959
2.  En la misma linea que el ejemplo anterior, sucede esto. Un poco confuso
https://www.loom.com/share/6d1245883a934d5f941ccf0b078afa98

2024-04-18 15:05 UTC, ma7payne commented
@AgosLizzi esta listo el cambio para revisar si cumple con los dos puntos que mencionabas. Quedo atento.

2024-04-22 15:16 UTC, AgosLizzi approved these changes

2024-04-23 12:55 UTC, MarianoCampetella requested changes

2024-04-23 12:55 UTC, MarianoCampetella commented on src/app/components/top/reglas/reglas.component.ts
> +    tipoPrestacion;
Esta variable no se esta utilizando en ningún lado, lo cual seria ideal eliminarla.

2024-04-23 13:05 UTC, MarianoCampetella commented
![Captura desde 2024-04-23 09-58-23](https://github.com/andes/app/assets/65697028/47335394-7721-43bb-a853-2c8100f6d1dc)
Según lo charlado con Agos, estaría bueno que existiera un botón "volver" al costado del título 'Datos del destino' ya que si el usuario deseara volver a la pantalla anterior debe hacerlo a través de los botones de navegación <- ->. A demás si selecciona el que tiene la flecha izquierda (volver atrás) me direcciona al inicio o pantalla anterior.

2024-05-20 13:52 UTC, ma7payne commented
> ![Captura desde 2024-04-23 09-58-23](https://private-user-images.githubusercontent.com/65697028/324843552-47335394-7721-43bb-a853-2c8100f6d1dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMTMyMzIsIm5iZiI6MTcxNjIxMjkzMiwicGF0aCI6Ii82NTY5NzAyOC8zMjQ4NDM1NTItNDczMzUzOTQtNzcyMS00M2JiLWE4NTMtMmM4MTAwZjZkMWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDEzNDg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzOWI2NzMzYjVjYzI3N2NkNjg3OWZlMTliZWE0YjQxMDYyYmRhYjA0ZjgwOGUxYzUwZjZjNTQ1Y2UwOGNjMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LtI_UZui0WuSjYcStRixnfWhBnqUNsBI4fzqjzAFZcc) Según lo charlado con Agos, estaría bueno que existiera un botón "volver" al costado del título 'Datos del destino' ya que si el usuario deseara volver a la pantalla anterior debe hacerlo a través de los botones de navegación <- ->. A demás si selecciona el que tiene la flecha izquierda (volver atrás) me direcciona al inicio o pantalla anterior.

@MarianoCampetella Listos los cambios con el botón volver!

2024-05-22 17:50 UTC, negro89 commented
Tests al 22/05/24
![image](https://github.com/andes/app/assets/37875706/e150d39f-3d60-436a-adbe-279a47789499)

2024-05-22 17:53 UTC, merged