RUP - Visualizar edad en turnos asignados en una agenda.
andes/app pull request #2983
Opened 2024-03-06 18:10 UTC by JuanIRamirez

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/RUP-362

### Funcionalidad desarrollada 

1.  Se muestra la edad del paciente en Agenda c/turnos y Fuera de Agenda.
2. Si el paciente del turno tiene fechaNacimiento, se muestra la edad con el pipe edad.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2024-03-07 18:11 UTC, MarianoCampetella commented
Cuando agrego un paciente fuera de agenda no se visualiza la edad de dicho paciente!
![image](https://github.com/andes/app/assets/65697028/7fb00651-a877-46b1-84b2-396728c21193)

2024-04-09 14:25 UTC, AgosLizzi requested changes
Dejo la misma observación que @MarianoCampetella. El resto lo veo bien

2024-04-10 15:03 UTC, JuanIRamirez commented
> Dejo la misma observación que @MarianoCampetella. El resto lo veo bien

Hecho

2024-04-22 15:47 UTC, AgosLizzi approved these changes

2024-04-23 11:57 UTC, MarianoCampetella approved these changes

2024-05-08 13:34 UTC, merged