IN - Reporte pedido de medicamentos
andes/app pull request #2997
Opened 2024-04-08 12:25 UTC by aldoEMatamala

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/IN-574
### Funcionalidad desarrollada 

  1.  Reporte de los pedidos de medicamentos de un sector para realizar el control de entrega de medicación 
  2.  Extraccion de una planilla con la siguiente información: DNI paciente / sector / unidad org./ cama actual/ los datos del medicamento, filtros por sector, unidad organizativa y por nombre de medicamento para un efector.
  3. Descarga en csv

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si https://github.com/andes/api/pull/1883
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2024-04-11 15:09 UTC, negro89 reviewed
chicos, dos cositas por ahora, ademas de lo charlado en la demo:
1. Se está pudiendo acceder por url por fuera de la capa farmaceutica
2. El mensaje del listado vacío si no se está filtrando no debería decir que no hay resultados, sino sugerir como empezar a interactuar

El resto de 10 👍🏼

2024-04-16 13:57 UTC, aldoEMatamala commented
> 2\. está filtrando no debería decir que no hay resultados, sino sugerir como empezar a interactuar



> chicos, dos cositas por ahora, ademas de lo charlado en la demo:
> 
>     1. Se está pudiendo acceder por url por fuera de la capa farmaceutica
> 
>     2. El mensaje del listado vacío si no se está filtrando no debería decir que no hay resultados, sino sugerir como empezar a interactuar
> 
> 
> El resto de 10 👍🏼
gracias por la revisión!
1- Queda la redireccion cuando no se encuentra en capa distinta a 'farmaceutica' y se quiere acceder al listado.
2- Se modificó la leyenda de listado vacío a 
![imagen](https://github.com/andes/app/assets/123381977/8c1f7678-853c-48f7-b3b5-0bb5c7ae2dbd)
Saludos!

2024-04-19 12:21 UTC, MarianoCampetella commented
![image](https://github.com/andes/app/assets/65697028/64704ad8-47ab-42d1-b903-8397e92fb22a)
![image](https://github.com/andes/app/assets/65697028/8d263409-4ec2-4a6e-9d71-14c20dea8e58)

En la primera foto se observa que el filtro de paciente no esta funcionando como corresponde ya que al ingresar un apellido que no se encuentra en el listado sigue devolviendo todos los medicamentos registrados en el día.
En la segunda foto me queda la duda si no será mejor cambiar la leyenda cuando no obtenemos ningún resultado a partir de la búsqueda de cualquiera de los filtros. En caso de que se pueda implementar dos leyendas serian de la siguiente forma:
- Si no existen medicamentos registrados en el día de la fecha podría decir la leyenda que se encuentra ahora.
- Si no existen medicamentos en base a los filtros utilizados entonces mostrar una leyenda que diga: No hay resultados para esta búsqueda - Edite algún filtro para realizar una nueva.

2024-05-21 19:07 UTC, aldoEMatamala commented
> ![image](https://private-user-images.githubusercontent.com/65697028/323944483-64704ad8-47ab-42d1-b903-8397e92fb22a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMTg0NDAsIm5iZiI6MTcxNjMxODE0MCwicGF0aCI6Ii82NTY5NzAyOC8zMjM5NDQ0ODMtNjQ3MDRhZDgtNDdhYi00MmQxLWI5MDMtODM5N2U5MmZiMjJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDE5MDIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4Y2I2NzE2ZjUzZWU3ZDQyZGMzYWU4MjRhMzIwNmUzODEzZDZlMmI5YTZkNTQ5NTc0ZmI2MDgyZDFjMmUyOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IYyuNEDMWxBdAoBzmagncQdIp5rYVELax3EuzBPSI4s) ![image](https://private-user-images.githubusercontent.com/65697028/323944612-8d263409-4ec2-4a6e-9d71-14c20dea8e58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMTg0NDAsIm5iZiI6MTcxNjMxODE0MCwicGF0aCI6Ii82NTY5NzAyOC8zMjM5NDQ2MTItOGQyNjM0MDktNGVjMi00YTZlLTlkNzEtMTRjMjBkZWE4ZTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDE5MDIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5NTk2N2Y5M2Y1N2JlNTVmODU4MmIwNGY3YmMzY2Y2ZmRlODNlMDNlZmExYzkxMjgzMWY5MDVkOWY3NWYxODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SYUwil7dnkc2Z3w5n-2qS4BJFDGX_7mvTgZwgVedV2U)
> 
> En la primera foto se observa que el filtro de paciente no esta funcionando como corresponde ya que al ingresar un apellido que no se encuentra en el listado sigue devolviendo todos los medicamentos registrados en el día. En la segunda foto me queda la duda si no será mejor cambiar la leyenda cuando no obtenemos ningún resultado a partir de la búsqueda de cualquiera de los filtros. En caso de que se pueda implementar dos leyendas serian de la siguiente forma:
> 
>     * Si no existen medicamentos registrados en el día de la fecha podría decir la leyenda que se encuentra ahora.
> 
>     * Si no existen medicamentos en base a los filtros utilizados entonces mostrar una leyenda que diga: No hay resultados para esta búsqueda - Edite algún filtro para realizar una nueva.

Gracias por la corrección! 
- Queda corregido cuando se modificaba el filtro de paciente y filtraba mal.
- Modificada la leyenda a "No hay resultados para esta búsqueda"

2024-05-28 16:08 UTC, aldoEMatamala commented
![imagen](https://github.com/andes/app/assets/123381977/dc100487-4e85-4fee-94d7-a7cc8781c170)

2024-06-11 15:09 UTC, negro89 commented
Aldinho, fijate que debes haber pisado los cambios de este commit _9658734d6100666f5413a832162b61dfc6165f62_ porque en la rama actual no se ven reflejados. 
Agrego como observación que en la pantalla del listado de medicamentos, si se actualiza el navegador vuelve al mapa de camas pero en la capa medica.
El resto ok 👌🏼

2024-06-12 17:41 UTC, aldoEMatamala commented
> Aldinho, fijate que debes haber pisado los cambios de este commit _[9658734](https://github.com/andes/app/commit/9658734d6100666f5413a832162b61dfc6165f62)_ porque en la rama actual no se ven reflejados. Agrego como observación que en la pantalla del listado de medicamentos, si se actualiza el navegador vuelve al mapa de camas pero en la capa medica. El resto ok 👌🏼

gracias por la corrección!
- queda correjido lo de al refrescar la vista que se iba a otra pantalla, también se agrego la necesidad de tener el permiso de capa farmaceutica para acceder al listado.

2024-06-13 12:56 UTC, negro89 commented on src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-medicamentos-capas.component.html
> +                        titulo="No hay resultados para esta búsqueda"
> * queda correjido lo de al refrescar la vista que se iba a otra pantalla, también se agrego la necesidad de tener el permiso de capa farmaceutica para acceder al listado.

Excelente 👍🏼  con respecto al cartel que se muestra inicialmente en el listado, debés tener algo cacheado porque en el codigo sigue figurando "No hay resultados para esta búsqueda"

2024-06-13 18:43 UTC, aldoEMatamala commented
![imagen](https://github.com/andes/app/assets/123381977/d4681a2f-bf39-48d5-ae92-4144ac551dc5)

2024-06-14 15:04 UTC, aldoEMatamala commented on src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-medicamentos-capas.component.html
> +                        titulo="No hay resultados para esta búsqueda"
> Aldinho, fijate que debes haber pisado los cambios de este commit _[9658734](https://github.com/andes/app/commit/9658734d6100666f5413a832162b61dfc6165f62)_ porque en la rama actual no se ven reflejados. Agrego como observación que en la pantalla del listado de medicamentos, si se actualiza el navegador vuelve al mapa de camas pero en la capa medica. El resto ok 👌🏼




Buenas ! gracias por la revisión.
-Se modifican leyendas cuando arroja listado vacio en función de la existencia de pedidos de medicamentos en el día de la fecha:
=> si no hay ningún pedido en el día.
![imagen](https://github.com/andes/app/assets/123381977/c1f93b33-f96d-452e-b288-d2d33738c195)
=> si hay pedidos pero no ninguno conhincide con los filtros aplicados

2024-06-14 18:13 UTC, aldoEMatamala commented
![imagen](https://github.com/andes/app/assets/123381977/02a7213a-0be0-4f85-8974-66b0dfa5baa3)
https://cloud.cypress.io/projects/xr7gft/runs/10165/overview?roarHideRunsWithDiffGroupsAndTags=1

2024-06-19 16:53 UTC, negro89 approved these changes

2024-07-12 14:03 UTC, MarianoCampetella requested changes

2024-07-12 14:03 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-medicamentos-capas.component.ts
> +    public hayHoy = true;
Múltiples variables como fechaDesdeEntrada, fechaHastaEntrada, hayHoy,selectedPrestacion$ y fechaControl no estan siendo utilizadas, al igual que Iprestaciones de la linea 7.

2024-07-12 14:04 UTC, MarianoCampetella commented
También falta corregir uno de los comentarios de arriba, el de la variable params.

2024-07-16 13:56 UTC, aldoEMatamala commented on src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-medicamentos-capas.component.ts
> +    public hayHoy = true;
hecho!

2024-07-16 14:03 UTC, aldoEMatamala commented on src/app/apps/rup/mapa-camas/services/mapa-camas.http.ts
> +            };
quedó como lo conversado. Gracias!

2024-07-17 13:41 UTC, negro89 approved these changes

2024-07-18 15:59 UTC, MarianoCampetella approved these changes

2024-07-18 16:07 UTC, merged