MPI - Pacientes sin domicilio real
andes/app pull request #2999
Opened 2024-04-12 12:19 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MPI-424

### Funcionalidad desarrollada 

1. Se agrega un nuevo check que permite habilitar la opción de que el paciente vive en situación de calle, entonces no solo se inhabilita el poder georeferenciar una dirección sino que dicho atributo no se cargará en la base de dato. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si   https://github.com/andes/api/pull/1886
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2024-05-07 14:48 UTC, negro89 commented
Campe, funciona ok. El unico tema es que el checkbox "se esconde" cuando lo clickeas. Quizas tenga que ver con el contenedor. Dejo videito.

https://www.loom.com/share/df76ac4da7d34333b4c500a379a95448?sid=adf6bd4a-e0a4-455c-83b8-49c647d4bd1f

2024-05-13 18:54 UTC, MarianoCampetella commented
> Campe, funciona ok. El unico tema es que el checkbox "se esconde" cuando lo clickeas. Quizas tenga que ver con el contenedor. Dejo videito.
> 
> https://www.loom.com/share/df76ac4da7d34333b4c500a379a95448?sid=adf6bd4a-e0a4-455c-83b8-49c647d4bd1f

Esto ya es un problema es propio de plex, el cual Matias estuvo trabajando en el mismo. Cuando se suban esos cambios volver a probar si ocurre o no lo mismo! Saludos.

2024-05-20 14:37 UTC, negro89 requested changes

2024-05-20 14:37 UTC, negro89 commented on src/app/core/mpi/components/paciente.component.ts
> +                if (this.situacionEnCalle !== undefined) {
Desde la primera vez que el check se pone en true, este control daría siempre false. Se podría omitir tranquilamente ya que mientras el check nunca se haya activado siempre va a ser undefined.
Por otro lado la variable situacionEnCalle también podría omitirse (y por tanto el output) al no existir ningun control de por medio y tener siempre el mismo valor que el dato paciente[0].direccion.situacionCalle

2024-05-29 14:46 UTC, MarianoCampetella commented on src/app/core/mpi/components/paciente.component.ts
> +                if (this.situacionEnCalle !== undefined) {
Corregido, se saco la variable situacionEnCalle, se borraron las verificaciones innecesarias y se actualizo un subscribe que se encontraba deprecado.

2024-05-29 17:47 UTC, negro89 approved these changes

2024-06-03 13:57 UTC, negro89 commented
Tests al 03/06/2024
![image](https://github.com/andes/app/assets/37875706/2fd5d126-5459-4e76-a03e-abb3d8f8340f)

2024-06-03 14:11 UTC, merged