(FEAT) Demanda Insatisfecha: pasar funcionalidad a API
andes/app pull request #3002
Opened 2024-04-24 14:30 UTC by JuanIRamirez

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-268

### Funcionalidad desarrollada 

1. El método post de ../routes/listaEspera.ts decide si agregar un nuevo doc a la colección o una nueva demanda a un doc existente.
2. Desde app se invoca desde ../turnos/listaEspera.Service.ts método save(...)
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1893
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2024-05-06 17:39 UTC, negro89 requested changes

2024-05-06 17:39 UTC, negro89 commented on src/app/components/turnos/dashboard/demandaInsatisfecha.ts
> +            if (this.listaEsperaService.save(this.paciente, this.tipoPrestacion, this.estado, this.profesional, this.organizacion, this.motivo.nombre, this.origen)) {
El problema de hacer esto es que la respuesta del save es asincrona, es decir, lo que retorna es una promesa y recien a la vuelta de la api se obtiene el valor. Por lo tanto el if en primera instancia siempre va a dar true.
Lo correcto sería eliminar el if y dejar solo el llamado y, a la vuelta del subscribe, segun sea exito o error se muestra el toast correspondiente:
```suggestion
            this.listaEsperaService.save(this.paciente, this.tipoPrestacion, this.estado, this.profesional, this.organizacion, this.motivo.nombre, this.origen).subscribe(respuesta => {
            complete: () => {
                *** exito ***
            },
            error: () => {
                *** error ***
            }
    })
```

2024-05-23 13:56 UTC, JuanIRamirez commented on src/app/components/turnos/dashboard/demandaInsatisfecha.ts
> +            if (this.listaEsperaService.save(this.paciente, this.tipoPrestacion, this.estado, this.profesional, this.organizacion, this.motivo.nombre, this.origen)) {
Hecho

2024-06-13 15:11 UTC, negro89 approved these changes

2024-06-14 19:03 UTC, MCele approved these changes

2024-06-18 17:21 UTC, merged