IN - Implementa periodos censables en internacion
andes/app pull request #3003
Opened 2024-04-24 18:01 UTC by ma7payne

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/IN-594

### Funcionalidad desarrollada 

1. En el detalle de la internación (Ingreso) puedo verse una opción para agregar periodos censables, solo en capa estadística.
2. El selector de periodos permite agregar uno o mas periodos a partir del ingreso por fechas.
3. Los periodos se agregan al campo periodosCensables de la internación.
4. Si se borra el listado de periodos el estado esCensable en la internación pasa a "false".
5. Si la internación tiene estado esCensable "false" y  se agregan periodos, pasa a ser "true".

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [x] Si
- [ ] No

### Requiere actualizaciones en la API

- [x] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [x] Si
- [ ] No

2024-05-16 13:48 UTC, ma7payne commented
@AgosLizzi los cambios charlados fueron realizados.

2024-05-31 15:40 UTC, negro89 commented
Mati, completando el circuito veo que lo datos se guardan correctamente y todo queda bien entendible desde el detalle en el sidebar. Pero noto algunas dificultades en el circuito de registro de los periodos que hacen a la funcionalidad un poco confusa:
1. Si completo las fechas de un nuevo periodo que deseo agregar y en lugar de clickear en el boton "check" presiono "guardar" se lanza un cartel de confirmación pero el periodo no queda guardado.
2. Similar al anterior. Si completo las fechas de un nuevo periodo y clickeo el "chheck" pero en lugar de guardar presiono la "X" no aparece el cartel pero tampoco se registra el periodo (Habiendo presionado previamente el boton "check").
3. Cada vez que agrego un periodo, este se almacena debajo del todo y se resetean los campos de fecha quedando listos para registrar otro periodo. Esta ok, pero en mi pantalla no se percibe a primera vista que se haya registrado el nuevo periodo, por lo que sugeriría agregar un scrollToEnd cada vez que se registra un periodo.

Como propuesta (Revisar con agos en todo caso) suprimiría el botón "guardar" asi por un lado no mezclamos texto e iconos en los botones, y por el otro eliminamos la ambigüedad de la acción de guardar. Y dejaría el botón check con un tooltip "guardar periodo" encargado de almacenar cada uno. Quizas con la propuesta deja medio descolocado al botón "editar", para lo que se me ocurren dos cosas; que se muestre solo si hay al menos un periodo censable o que cada periodo tenga un boton editar (De esta forma hasta se podría controlar que no se pisen los periodos)

Dejo videito con las observaciones hechas: https://www.loom.com/share/ae2c4734eea14ac385af1a922a3e457b?sid=b2eb58e5-e244-428f-96c3-f806e0e56bd4

2024-06-13 16:26 UTC, ma7payne commented
TEST OK [11090](http://condorpiedra.andes.gob.ar/job/andes-test-integracion/11090/)

2024-06-13 16:32 UTC, ma7payne commented
> Mati, completando el circuito veo que lo datos se guardan correctamente y todo queda bien entendible desde el detalle en el sidebar. Pero noto algunas dificultades en el circuito de registro de los periodos que hacen a la funcionalidad un poco confusa:
> 
> 1. Si completo las fechas de un nuevo periodo que deseo agregar y en lugar de clickear en el boton "check" presiono "guardar" se lanza un cartel de confirmación pero el periodo no queda guardado.
> 2. Similar al anterior. Si completo las fechas de un nuevo periodo y clickeo el "chheck" pero en lugar de guardar presiono la "X" no aparece el cartel pero tampoco se registra el periodo (Habiendo presionado previamente el boton "check").
> 3. Cada vez que agrego un periodo, este se almacena debajo del todo y se resetean los campos de fecha quedando listos para registrar otro periodo. Esta ok, pero en mi pantalla no se percibe a primera vista que se haya registrado el nuevo periodo, por lo que sugeriría agregar un scrollToEnd cada vez que se registra un periodo.
> 
> Como propuesta (Revisar con agos en todo caso) suprimiría el botón "guardar" asi por un lado no mezclamos texto e iconos en los botones, y por el otro eliminamos la ambigüedad de la acción de guardar. Y dejaría el botón check con un tooltip "guardar periodo" encargado de almacenar cada uno. Quizas con la propuesta deja medio descolocado al botón "editar", para lo que se me ocurren dos cosas; que se muestre solo si hay al menos un periodo censable o que cada periodo tenga un boton editar (De esta forma hasta se podría controlar que no se pisen los periodos)
> 
> Dejo videito con las observaciones hechas: https://www.loom.com/share/ae2c4734eea14ac385af1a922a3e457b?sid=b2eb58e5-e244-428f-96c3-f806e0e56bd4
> 
> P/D: Tres casos recurrentes al dia de hoy de fallo de test (Dos corridas distintas)
> 
> 1. https://cloud.cypress.io/projects/xr7gft/runs/10068/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D
> 2. https://cloud.cypress.io/projects/xr7gft/runs/10067/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D
> 
> ![image](https://private-user-images.githubusercontent.com/37875706/335697445-bcc5252c-e5a5-4c15-8267-8cbe734350e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyOTQwMDIsIm5iZiI6MTcxODI5MzcwMiwicGF0aCI6Ii8zNzg3NTcwNi8zMzU2OTc0NDUtYmNjNTI1MmMtZTVhNS00YzE1LTgyNjctOGNiZTczNDM1MGUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDE1NDgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmMjQxZjgyZWVhNDdjMTlmNGQ4MTZlM2U5MzRkYmYwYmFhNmEyNDVhZGIwMDgyMmRhN2RkMzQyZWE4OTQ4YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XkKbQlmipvcCa2xK7xSzRCvnFhXjZ2WL40saJLvjsKo)

@negro89 Listo los nuevos cambios para revisar. Se quita el botón de Guardar para aplicar cambios solo con el botón de check. No se aplica el tooltip en el check porque rompe la vista, se podría evaluar con @AgosLizzi una alternativa para este caso.

2024-06-14 12:57 UTC, negro89 approved these changes

2024-06-18 14:28 UTC, MarianoCampetella requested changes

2024-06-18 14:28 UTC, MarianoCampetella commented on src/app/apps/rup/mapa-camas/sidebar/periodos-censables/periodos-censables.component.ts
> +    camaEsCensable = false;
Esta variable no se utiliza en ningún lado. Si se dejó por un posible uso en el futuro, entonces se puede dejar!

2024-06-19 12:14 UTC, ma7payne commented on src/app/apps/rup/mapa-camas/sidebar/periodos-censables/periodos-censables.component.ts
> +    camaEsCensable = false;
@MarianoCampetella  Listo el cambio y las sugerencias sobre los subscribe deprecados!

2024-06-19 12:37 UTC, MarianoCampetella approved these changes

2024-06-26 15:02 UTC, merged