CIT - Implementa mockups de demanda insatisfecha
andes/app pull request #3006
Opened 2024-05-13 13:28 UTC by ma7payne

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-277

### Funcionalidad desarrollada 

1.  Implementa mockups para nuevo módulo de demanda insatisfecha
2. Se recupera lista de espera de pacientes sin turnos, con opciones de filtros
3. Se visualiza detalle de paciente en sidebar

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2024-05-13 14:36 UTC, ma7payne commented
Test OK: [#10875](http://172.16.1.116:8080/job/andes-test-integracion/10875/)

2024-05-24 14:39 UTC, ma7payne commented
Test OK: [#10942](http://condorpiedra.andes.gob.ar/job/andes-test-integracion/10942/)

2024-05-30 18:23 UTC, AgosLizzi requested changes
Mati, te dejo unas observaciones:

- **Como cambio importante:** El filtro por prestación, por motivo y por paciente parecen no tener funcionalidad, es decir, sobre el listado no me aparece exclusivamente lo que seleccioné para filtrar. Dejo ejemplo
![filtro](https://github.com/andes/app/assets/72876985/3e746d2c-4bde-49af-b8cb-61c880b424d1)

- Sobre el listado se muestra el estado "resuelto", no debería aparecer.
![resuelto](https://github.com/andes/app/assets/72876985/c4837b01-4442-416d-a72a-1fb2ee647a2a)

- Parece que los llamados no se guardan. Una vez ingresado uno, doy volver y vuelvo a elegir mismo paciente, y no me muestra nada. Dejo video
https://www.loom.com/share/26461ca215c3466283c86d6c207c436a

**Como cambos secundarios:** 
- Sobre el plex item se podría subir el tamaño de la tipo? Siento que el size:S va a quedar muy chico. Que te parece?
![tituosidebar](https://github.com/andes/app/assets/72876985/983ff891-924a-4736-8549-ef1490c300f7)
- Al listado de pacientes, se le puede aplicar el mouse over?

2024-07-02 16:01 UTC, AgosLizzi approved these changes

2024-07-02 19:17 UTC, MCele commented
Mati dejo algunas cositas que fui viendo en uan primer revisión:

- Listado: filtro de paciente no funciona la búsqueda por número de documento
- Quizás sea mejor cargar el nuevo componente desde citas.module y no desde app.module (raíz).
- Cuidado con los archivos que se eliminan, ya que se está quitando la posibilidad de cargar demandas, botón nuevo que se visualiza desde citas (punto de inicio). Este botón permite registrar una nueva demanda al usuario => pensamos que lo mejor sería crear un nuevo módulo desde el inicio para visualizar esta nueva pantalla de demandas, ícono a analizar por @AgosLizzi

2024-07-02 19:52 UTC, MCele requested changes
en comentarios dejé correcciones que me parecen importantes a considerar

2024-07-12 12:24 UTC, ma7payne commented
TEST OK [#11205](http://condorpiedra.andes.gob.ar/job/andes-test-integracion/11205/)

2024-07-29 19:24 UTC, MCele commented
> * Filtro "desde" si es obligatorio debería precargarse con un dato siempre y no hacer las búsquedas si no lo tiene.



> Mati en general la visualziación me parece que esta hermosa, dejo algunas cositas que fui viendo en una primer revisión:
> 
> * Filtro "desde" si es obligatorio debería precargarse con un dato siempre y no hacer las búsquedas si no lo tiene.
> * Las demandas "resueltas" se ven con estado "pendiente" en el listado, considerar que no deberían verse.
> * Listado: filtro de paciente no funciona la búsqueda por número de documento.
> * Un detalle visual, me parece que los motivos a mostrar en el listado deberían agruparse y sólo mostrar los que son distintos, no repetir los que coinciden por cada ocurrencia
>   ![image](https://private-user-images.githubusercontent.com/19591224/345480073-93d24d5d-1bb2-4908-86db-368f4a21b4bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyODA2NDIsIm5iZiI6MTcyMjI4MDM0MiwicGF0aCI6Ii8xOTU5MTIyNC8zNDU0ODAwNzMtOTNkMjRkNWQtMWJiMi00OTA4LTg2ZGItMzY4ZjRhMjFiNGJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDE5MTIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjMWQ0N2ZlODhhODU1ZGE5YWM5MTdlYzdmYzI4OTNkM2NlMTNjYTIxMGUwYTE0MGFiMDdiMzU4NDhhZDNhNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gjjyCIsJBDPOQYmjJ8NlyDdOXHvrKRYcFzaAazzNulQ)
> * Respecto al código, quizás sea mejor cargar el nuevo componente desde citas.module y no desde app.module (raíz).
> * Cuidado con los archivos que se eliminan, ya que se está quitando la posibilidad de cargar demandas, botón nuevo que se visualiza desde citas (punto de inicio). Este botón permite registrar una nueva demanda al usuario => pensamos que lo mejor sería crear un nuevo módulo desde el inicio para visualizar esta nueva pantalla de demandas, ícono a analizar por @AgosLizzi.
> * El historial de turnos está incompleto, no se visualizan todos los turnos, a veces se ven menos y otras veces se ven anteriores a la fecha de la primer demanda mostrada.
>   Creo que debería incluir los fuera de agenda, tal como se ve en el historial de turnos de citas, peor siempre respetando la fecha posterior al primer registro de demanda.
> * Listado de llamadas, funciona bien, sólo hay un detalle en la actualización de un registro de llamada recién cargado, ya que cuando se lo vuelve a visualizar en el sidebar el mismo item no se ve el llamado registrado, pero si se refresca el listado se visualiza. Quizás cada vez que se haga la visualización de un item del listado se debería volver a obtener dicho recurso para mostrarlo actualizado y de esta forma se mostraría actualizado la información en general.
> 
> Mati ya que se van a hacer cambios agrego un detalle que notamos que nos faltó contemplar en el mockup, pero que nos pareció importante que se haga, que es en el listado de demandas registradas a un paciente y prestación (sidebar) agregar la fecha de cada demanda, actualmente solo se ve prestación y efector.



> Mati en general la visualziación me parece que esta hermosa, dejo algunas cositas que fui viendo en una primer revisión:
> 
> * Filtro "desde" si es obligatorio debería precargarse con un dato siempre y no hacer las búsquedas si no lo tiene.
> * Las demandas "resueltas" se ven con estado "pendiente" en el listado, considerar que no deberían verse.
> * Listado: filtro de paciente no funciona la búsqueda por número de documento.
> * Un detalle visual, me parece que los motivos a mostrar en el listado deberían agruparse y sólo mostrar los que son distintos, no repetir los que coinciden por cada ocurrencia
>   ![image](https://private-user-images.githubusercontent.com/19591224/345480073-93d24d5d-1bb2-4908-86db-368f4a21b4bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyODA5MjMsIm5iZiI6MTcyMjI4MDYyMywicGF0aCI6Ii8xOTU5MTIyNC8zNDU0ODAwNzMtOTNkMjRkNWQtMWJiMi00OTA4LTg2ZGItMzY4ZjRhMjFiNGJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDE5MTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjYzgyZjgyNTAxMWIxMGIzZDE4YzMxMmE4ODIxMDRlNDYxOTAwZWU0OTc1MDVhNzYzYjUyY2MwZGExYjY3MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q5TTlDh41kSOQd5iRTzW0TlPgAGKp_bnIir5kxq1C4M)
> * Respecto al código, quizás sea mejor cargar el nuevo componente desde citas.module y no desde app.module (raíz).
> * Cuidado con los archivos que se eliminan, ya que se está quitando la posibilidad de cargar demandas, botón nuevo que se visualiza desde citas (punto de inicio). Este botón permite registrar una nueva demanda al usuario => pensamos que lo mejor sería crear un nuevo módulo desde el inicio para visualizar esta nueva pantalla de demandas, ícono a analizar por @AgosLizzi.
> * El historial de turnos está incompleto, no se visualizan todos los turnos, a veces se ven menos y otras veces se ven anteriores a la fecha de la primer demanda mostrada.
>   Creo que debería incluir los fuera de agenda, tal como se ve en el historial de turnos de citas, peor siempre respetando la fecha posterior al primer registro de demanda.
> * Listado de llamadas, funciona bien, sólo hay un detalle en la actualización de un registro de llamada recién cargado, ya que cuando se lo vuelve a visualizar en el sidebar el mismo item no se ve el llamado registrado, pero si se refresca el listado se visualiza. Quizás cada vez que se haga la visualización de un item del listado se debería volver a obtener dicho recurso para mostrarlo actualizado y de esta forma se mostraría actualizado la información en general.
> 
> Mati ya que se van a hacer cambios agrego un detalle que notamos que nos faltó contemplar en el mockup, pero que nos pareció importante que se haga, que es en el listado de demandas registradas a un paciente y prestación (sidebar) agregar la fecha de cada demanda, actualmente solo se ve prestación y efector.


Mati veo la gran mayoría de los cambios, faltaron algunos a considerar, pero ya que aún no se resolvió vamos a replantear uno de los pedidos. Los que veo que faltan resolver son:

- El historial de turnos está incompleto, sigo sin ver todos los turnos posteriores a **la fecha posterior al primer registro de demanda.**, si no que veo todos los turnos. Pero además faltan las atenciones fuera de agenda.

- Falta agrupar motivos en el listado y sólo mostrar los que son distintos (no repetir los que coinciden por cada ocurrencia).
 
El filtro **desde** habíamos pensado en que sea obligatorio, porque el listado que existe hoy en día es muy grande, pero vamos a cambiar ese pedido por la incorporación de un **scroll infinito** para poder paginar los datos-

2024-07-30 00:27 UTC, MCele commented on src/app/app.routing.ts
> +    { path: 'citas/demanda-insatisfecha', component: DemandaInsatisfechaComponent, canActivate: [RoutingNavBar] },
agregar RoutingGuard
`{ path: 'citas/demanda-insatisfecha', component: DemandaInsatisfechaComponent, canActivate: [RoutingNavBar, RoutingGuard] },`

2024-07-31 15:48 UTC, ma7payne commented
> > Mati en general la visualziación me parece que esta hermosa, dejo algunas cositas que fui viendo en una primer revisión:
> > 
> > * Filtro "desde" si es obligatorio debería precargarse con un dato siempre y no hacer las búsquedas si no lo tiene.
> > * Las demandas "resueltas" se ven con estado "pendiente" en el listado, considerar que no deberían verse.
> > * Listado: filtro de paciente no funciona la búsqueda por número de documento.
> > * Un detalle visual, me parece que los motivos a mostrar en el listado deberían agruparse y sólo mostrar los que son distintos, no repetir los que coinciden por cada ocurrencia
> >   .....
> 
> Mati veo la gran mayoría de los cambios, faltaron algunos a considerar, pero ya que aún no se resolvió vamos a replantear uno de los pedidos. Los que veo que faltan resolver son:
> 
> * El historial de turnos está incompleto, sigo sin ver todos los turnos posteriores a **la fecha posterior al primer registro de demanda.**, si no que veo todos los turnos. Pero además faltan las atenciones fuera de agenda.
> * Falta agrupar motivos en el listado y sólo mostrar los que son distintos (no repetir los que coinciden por cada ocurrencia).
> 
> Por otro lado, el filtro **desde** habíamos pensado en que sea obligatorio, porque el listado que existe hoy en día es muy grande, pero vamos a cambiar ese pedido por la incorporación de un **scroll infinito** para poder paginar los datos-

@MCele listos los cambios. La fecha de comparación de los filtros se unificó a "horaInicio" en el campo de historial, de esta forma filtra bien los resultados. Veo los "fuera de agenda" correctamente, avisame si seguis sin ver alguno. El campo de filtro "fecha desde" es obligatorio, posee un valor unicial a una semana atrás y no busca si esta vacio.

2024-07-31 19:13 UTC, silviroa requested changes

2024-07-31 19:13 UTC, silviroa commented on src/app/components/demandaInsatisfecha/demanda-insatisfecha.html
> +                </plex-select>
Agregar atributo "name" o no va a funcionar el form del filtro

2024-07-31 19:14 UTC, silviroa commented on src/app/components/demandaInsatisfecha/demanda-insatisfecha.html
> +                </plex-select>
Mati, el resto lo veo bien.... solo este detalle

2024-08-01 11:32 UTC, MarianoCampetella requested changes

2024-08-01 11:32 UTC, MarianoCampetella commented on src/app/components/demandaInsatisfecha/demanda-insatisfecha.component.ts
> +    public selectedPaciente;
Eliminar esta variable ya que no se utiliza en ningún lado!

2024-08-01 13:36 UTC, ma7payne commented
@silviroa @MarianoCampetella  Los cambios fueron realizados!

2024-08-02 15:15 UTC, merged