PRIV - Agregar campo observación en motivos
andes/app pull request #3010
Opened 2024-05-20 13:37 UTC by aldoEMatamala

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/PRIV-70
### Funcionalidad desarrollada 

1. Se agrega campo observación al modal de selección de motivo
2. Se agrega plex-help de la observación en listado de accesos HUDS 

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [x] Si https://github.com/andes/api/pull/1901
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [X] Si https://github.com/andes/andes-test-integracion/pull/523
- [ ] No

2024-05-20 17:50 UTC, negro89 commented
Desde la pantalla de busqueda de huds, al seleccionar un motivo y, ya sea escribiendo o no en el nuevo campo, luego de confirmar la api arroja el error adjunto en la imagen. Además, en el tab "accesos a la huds" no me muestra este ultimo ingreso.
Parecería que el error esta en la api.

![image](https://github.com/andes/app/assets/37875706/f19dd902-94c4-49f7-9cac-75aa82ba29e1)

2024-05-23 19:13 UTC, negro89 requested changes

2024-05-23 19:13 UTC, negro89 commented on src/app/modules/rup/components/huds/modal-motivo-acceso-huds.component.ts
> +            this.motivoAccesoHuds.emit([item.label, this.detalleMotivo]);
Esto está trayendo problemas del lado de la api ya que se esperan dos strings _motivo_ y _detalleMotivo_ pero desde app se está enviando el array. Sugeriría dejar la api como está pero en cada componente que arme los params para llamar a _generateHudsToken(params)_ se separe el array en los dos atributos esperados.

2024-05-28 16:08 UTC, aldoEMatamala commented
![imagen](https://github.com/andes/app/assets/123381977/6fa3934e-6c7e-4598-bedb-64b2c0cb4313)

2024-05-29 12:13 UTC, negro89 commented
Charlado con agos y aldo, se agrega nuevo commit para modificar la visualización del motivo reemplazando el help por un hint.

2024-05-29 12:13 UTC, negro89 approved these changes

2024-05-30 12:48 UTC, AgosLizzi approved these changes

2024-05-30 13:27 UTC, MarianoCampetella approved these changes

2024-05-31 11:34 UTC, negro89 commented
Tests al 30/05/24
![image](https://github.com/andes/app/assets/37875706/2ed56523-8ad2-4536-8bc0-9490d472e709)

2024-06-03 15:07 UTC, merged