CIT - Edición de profesional en agenda
andes/app pull request #3011
Opened 2024-05-23 15:04 UTC by Fabio-Ramirez

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-274

### Funcionalidad desarrollada 

1.  En la creación de la agenda se verifica que el/los profesionales no estén en agendas de otros efectores en el mismo dia y hora.
2.  En la modificación de agenda, se controla que el/los profesionales, estén habilitados para la prestación seleccionada, ademas que no esten en agendas de otros efectores.

### UserStory llegó a completarse

- [ x ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [x] Si: https://github.com/andes/api/pull/1903
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2024-05-30 15:15 UTC, MarianoCampetella requested changes

2024-05-30 15:15 UTC, MarianoCampetella commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts
>                  }, err => {
Ya que se estuvo trabajando sobre esta sección de código, actualizar dicho subcribe con la siguiente información:
https://rxjs.dev/deprecations/subscribe-arguments

2024-06-10 11:10 UTC, Fabio-Ramirez commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts
>                  }, err => {
Corregido compa.

2024-06-13 11:41 UTC, negro89 approved these changes

2024-06-18 12:50 UTC, MarianoCampetella approved these changes

2024-06-18 17:28 UTC, merged