RUP - Implementa habilitación de prestaciones a profesional
andes/app pull request #3014
Opened 2024-05-29 14:57 UTC by ma7payne

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/RUP-399

### Funcionalidad desarrollada 

1.  Crea módulo de habilitación para prestaciones de un profesional
2. Implementa mockups con formulario de carga de nuevo acceso.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2024-05-30 14:22 UTC, AgosLizzi approved these changes

2024-05-30 15:40 UTC, MarianoCampetella requested changes

2024-05-30 15:40 UTC, MarianoCampetella commented on src/app/app.routing.ts
>  // import { ExtranjeroNNCruComponent } from './core/mpi/components/extranjero-nn-cru.component';
Se podría quitar este import comentado.

2024-05-30 15:40 UTC, MarianoCampetella commented on src/app/components/turnos/gestor-agendas/prestaciones-habilitadas/prestaciones-habilitadas.component.ts
> +        { id: 'miercoles', label: 'Miercoles' },
Falta el acento a Miércoles

2024-05-30 15:42 UTC, MarianoCampetella commented
A modo de comentario, cuando se tenga que continuar con el PR la variable nuevoAcceso habría que cargarle los elementos necesarios para evitar los errores en el HTML de Property ' ... ' does not exist on type '{}'. el resto se encuentra en perfecta condiciones para continuarlo.

2024-06-04 14:57 UTC, ma7payne commented
> A modo de comentario, cuando se tenga que continuar con el PR la variable nuevoAcceso habría que cargarle los elementos necesarios para evitar los errores en el HTML de Property ' ... ' does not exist on type '{}'. el resto se encuentra en perfecta condiciones para continuarlo.

@MarianoCampetella listos los cambios! En relacional ultimo comentario, ya se charló en persona.

2024-06-04 14:58 UTC, ma7payne commented on src/app/components/turnos/gestor-agendas/prestaciones-habilitadas/prestaciones-habilitadas.component.ts
> +        { id: 'miercoles', label: 'Miercoles' },
✅

2024-06-04 14:58 UTC, ma7payne commented on src/app/app.routing.ts
>  // import { ExtranjeroNNCruComponent } from './core/mpi/components/extranjero-nn-cru.component';
✅

2024-06-05 12:39 UTC, MarianoCampetella approved these changes

2024-06-05 15:51 UTC, negro89 reviewed
Se ve de 10! solo dos observaciones sobre la pantalla inicial:
1. El botón "volver" lo venimos ubicando siempre a la izquierda (excepto en los sidebar, que lo mostramos con el icono "X") tal cual la pantalla "crear nuevo acceso" 
2. La leyenda "no hay permisos disponibles" quizás quede mejor dandole un margen en la parte superior para distribuir un poquito mas que nada (solo es una apreciación personal)

![image](https://github.com/andes/app/assets/37875706/d92f168a-f4ed-4748-91fe-c76bb08ffee7)

2024-06-24 15:02 UTC, ma7payne commented
> Se ve de 10! solo dos observaciones sobre la pantalla inicial:
> 
> 1. El botón "volver" lo venimos ubicando siempre a la izquierda (excepto en los sidebar, que lo mostramos con el icono "X") tal cual la pantalla "crear nuevo acceso"
> 2. La leyenda "no hay permisos disponibles" quizás quede mejor dandole un margen en la parte superior para distribuir un poquito mas que nada (solo es una apreciación personal)
> 
> ![image](https://private-user-images.githubusercontent.com/37875706/336913551-d92f168a-f4ed-4748-91fe-c76bb08ffee7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDEzNDgsIm5iZiI6MTcxOTI0MTA0OCwicGF0aCI6Ii8zNzg3NTcwNi8zMzY5MTM1NTEtZDkyZjE2OGEtZjRlZC00NzQ4LTkxZmUtYzc2YmIwOGZmZWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDE0NTcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmYWU1MThlYWFiMjEyMmE5NDI2MDkzOGNhYzY3MWM0NWJlOTU5ZGZjMTBhMGE0Mzc5ZTZjMDI2YjdmNGY0ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rj-i_qTswRmXq6Og9LrNTsDcioMTXOJCDhK14-rpjXg)



> Se ve de 10! solo dos observaciones sobre la pantalla inicial:
> 
> 1. El botón "volver" lo venimos ubicando siempre a la izquierda (excepto en los sidebar, que lo mostramos con el icono "X") tal cual la pantalla "crear nuevo acceso"
> 2. La leyenda "no hay permisos disponibles" quizás quede mejor dandole un margen en la parte superior para distribuir un poquito mas que nada (solo es una apreciación personal)
> 
> ![image](https://private-user-images.githubusercontent.com/37875706/336913551-d92f168a-f4ed-4748-91fe-c76bb08ffee7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDEzNDgsIm5iZiI6MTcxOTI0MTA0OCwicGF0aCI6Ii8zNzg3NTcwNi8zMzY5MTM1NTEtZDkyZjE2OGEtZjRlZC00NzQ4LTkxZmUtYzc2YmIwOGZmZWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDE0NTcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmYWU1MThlYWFiMjEyMmE5NDI2MDkzOGNhYzY3MWM0NWJlOTU5ZGZjMTBhMGE0Mzc5ZTZjMDI2YjdmNGY0ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rj-i_qTswRmXq6Og9LrNTsDcioMTXOJCDhK14-rpjXg)

@negro89 Cambios listos!

2024-06-28 14:03 UTC, negro89 approved these changes

2024-07-18 15:38 UTC, merged