GDU - Controlar datos del profesional asociado al usuario
andes/app pull request #3018
Opened 2024-06-03 12:53 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/GDU-64

### Funcionalidad desarrollada 

1. Se verifica si el usuario es un profesional habilitado o no. Si se encuentra duplicado mostrará los datos del habilitado y en caso de que se encuentre deshabilitado mostrará un badge rojo DESHABILITADO. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si   https://github.com/andes/api/pull/1915
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [X] Si   https://github.com/andes/andes-test-integracion/pull/528
- [ ] No

2024-06-04 15:48 UTC, aldoEMatamala commented
campe como lo hablamos te dejo por escrito las observaciones:
1- Si es correcta la interpretacion de cuando un profesional se encuentre deshabilitado se puedan dar permisos desde el gestor.
2- En la visualización de "MIS DATOS" se ven las profesiones de grado de otro profesional
![imagen](https://github.com/andes/app/assets/123381977/2dae4dc8-6ae0-45bd-8a96-90bacb8d6ae9)

2024-06-05 15:25 UTC, MarianoCampetella commented
> campe como lo hablamos te dejo por escrito las observaciones: 1- Si es correcta la interpretacion de cuando un profesional se encuentre deshabilitado se puedan dar permisos desde el gestor. 2- En la visualización de "MIS DATOS" se ven las profesiones de grado de otro profesional ![imagen](https://private-user-images.githubusercontent.com/123381977/336520652-2dae4dc8-6ae0-45bd-8a96-90bacb8d6ae9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MDEyNzEsIm5iZiI6MTcxNzYwMDk3MSwicGF0aCI6Ii8xMjMzODE5NzcvMzM2NTIwNjUyLTJkYWU0ZGM4LTZhZTAtNDViZC04YTk2LTkwYmFjYjhkNmFlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQxNTIyNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjE3ZmZiNGQ0NTQ1ODI0YTFlYzZhZjU5YWRmMTg2YzYyYjBmOGFlYWUwYTBjYmI5M2EyY2ZkZWFlNTllMmQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kSIqXKBJcrehLri6quAdhgY774pKoBR_s2ZRi_jR4pw)

Corregido, ahora cada vez que se vaya a loguear un usuario el cual este duplicado por BD, va a seleccionar el que se encuentre habilitado. En caso de que se encuentren ambos o deshabilitados selecciona uno de ellos.

2024-06-05 16:12 UTC, aldoEMatamala commented
> > campe como lo hablamos te dejo por escrito las observaciones: 1- Si es correcta la interpretacion de cuando un profesional se encuentre deshabilitado se puedan dar permisos desde el gestor. 2- En la visualización de "MIS DATOS" se ven las profesiones de grado de otro profesional ![imagen](https://private-user-images.githubusercontent.com/123381977/336520652-2dae4dc8-6ae0-45bd-8a96-90bacb8d6ae9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MDEyNzEsIm5iZiI6MTcxNzYwMDk3MSwicGF0aCI6Ii8xMjMzODE5NzcvMzM2NTIwNjUyLTJkYWU0ZGM4LTZhZTAtNDViZC04YTk2LTkwYmFjYjhkNmFlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQxNTIyNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjE3ZmZiNGQ0NTQ1ODI0YTFlYzZhZjU5YWRmMTg2YzYyYjBmOGFlYWUwYTBjYmI5M2EyY2ZkZWFlNTllMmQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kSIqXKBJcrehLri6quAdhgY774pKoBR_s2ZRi_jR4pw)
> 
> Corregido, ahora cada vez que se vaya a loguear un usuario siendo el mismo un profesional, el cual este duplicado por BD, va a seleccionar el que se encuentre habilitado. En caso de que se encuentren ambos deshabilitados selecciona uno de ellos.

genial campe ahi lo probe y anda joya

2024-06-05 16:12 UTC, aldoEMatamala approved these changes

2024-06-11 17:37 UTC, negro89 requested changes

2024-06-11 17:37 UTC, negro89 commented on src/app/app.component.ts
> +                this.profesionalService.get({ documento: this.auth.usuario.documento }).subscribe(profesional => {
Campe hay un problema con esta funcion; como está hecha para una búsqueda tipo filtro, si el dni que se está buscando es subcadena de otro dni entonces también lo va a traer. Habría que ..
1. modificar la búsqueda para que ofrezca la opcion de matching exacto
2. controlar en el response que efectivamente se trate de la misma persona

(En ambos casos aclararía la situación en el codigo con algun comentario)

2024-06-11 17:37 UTC, negro89 commented on src/app/app.component.ts
> +                        this.profesional = profHabilitado || profesional[0];
```suggestion
                        this.profesional = profesional.filter(prof => prof.habilitado);
```

2024-06-11 17:37 UTC, negro89 commented on src/app/apps/gestor-usuarios/components/usuario-detalle/usuario-detalle.component.ts
> +            this.profesional = this.profesionalHabilitado || profesional[0];
idem a la sugerencia anterior

2024-06-26 14:24 UTC, MarianoCampetella commented on src/app/app.component.ts
> +                this.profesionalService.get({ documento: this.auth.usuario.documento }).subscribe(profesional => {
Corregido, se agregó un parametro mas llamado busquedaExacta que se utiliza desde la API para hacer un matcheo exacto con el profesional.

2024-06-28 14:25 UTC, MarianoCampetella commented on src/app/app.component.ts
> +                        this.profesional = profHabilitado || profesional[0];
Este comentario se ignora ya que se aplica la primera sugerencia de cambio.

2024-06-28 14:25 UTC, MarianoCampetella commented on src/app/apps/gestor-usuarios/components/usuario-detalle/usuario-detalle.component.ts
> +            this.profesional = this.profesionalHabilitado || profesional[0];
Idem al comentario anterior!

2024-06-28 14:45 UTC, Fabio-Ramirez approved these changes

2024-07-02 14:31 UTC, ma7payne approved these changes

2024-07-23 16:22 UTC, MarianoCampetella commented
TEST OK: https://cloud.cypress.io/projects/xr7gft/runs/10322/overview?roarHideRunsWithDiffGroupsAndTags=1
![image](https://github.com/user-attachments/assets/8d61513b-88a7-4d09-ad23-3ab96ce14a9a)

2024-07-30 16:18 UTC, merged