feat(CIT-272): Ventanilla-Solicitudes: visualizar estado asignada
andes/app pull request #3026
Opened 2024-06-25 14:39 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/CIT-272

### Funcionalidad desarrollada 

1. Se agregaron a los parametros de busqueda de las prestaciones aquellas que tienen los estados "asignada" y "anulada"
2. Se cambió el color del badge de ANULADA por rojo.

NOTA: Ver si es necesario tener que cambiar el color del badge ASIGNADA ya que la misma se encuentra de color azul como los otros estados PENDIENTE y AUDITADA

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2024-06-26 17:37 UTC, MarianoCampetella commented
Los test se encuentran ok
![image](https://github.com/andes/app/assets/65697028/a76d736b-4d96-4caf-ac44-4527308604f6)

2024-07-05 17:43 UTC, AgosLizzi requested changes
Campe, te dejo una imagen de los estados y colores de los badge para solicitudes. Estaría bueno que queden de la misma manera asi logramos que todo siga dentro de un sistema ya definido. El asignada en verde y no en azul.
![Badge](https://github.com/andes/app/assets/72876985/73afe86f-d00d-4ce5-ae80-56f2a29d2254)
![image](https://github.com/andes/app/assets/72876985/2e156ea3-2283-4a44-8206-5f5eb6c8e203)

2024-07-08 18:18 UTC, MarianoCampetella commented
> Campe, te dejo una imagen de los estados y colores de los badge para solicitudes. Estaría bueno que queden de la misma manera asi logramos que todo siga dentro de un sistema ya definido. El asignada en verde y no en azul. ![Badge](https://private-user-images.githubusercontent.com/72876985/346194466-73afe86f-d00d-4ce5-ae80-56f2a29d2254.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NjE2NzUsIm5iZiI6MTcyMDQ2MTM3NSwicGF0aCI6Ii83Mjg3Njk4NS8zNDYxOTQ0NjYtNzNhZmU4NmYtZDAwZC00Y2U1LWFlODAtNTZmMmEyOWQyMjU0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDE3NTYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5OGQwNGM2ZGQ3YTFjNjI5MWFhMWUxZWRjNjg1M2MyZmE3MWZlN2IzNjRlZGI3M2JlM2Y1Y2Q1YzEwOWI0YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9EWqRACyfy_3ie6XOvNoXbH7T3nuZiqZmN5sY3PUIHQ) ![image](https://private-user-images.githubusercontent.com/72876985/346194560-2e156ea3-2283-4a44-8206-5f5eb6c8e203.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NjE2NzUsIm5iZiI6MTcyMDQ2MTM3NSwicGF0aCI6Ii83Mjg3Njk4NS8zNDYxOTQ1NjAtMmUxNTZlYTMtMjI4My00YTQ0LTgyMDYtNWY1ZWI2YzhlMjAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDE3NTYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkZTgyZTQzMTM3ZWRmYTNjOTUzMjY4M2QxMDkwMjhlNzdiMTFkODU4NjJjYjIxNjNiOGVjNmUyYzRkNmFkNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2sj9GVnxPE9Y4CMewonpf3VYqcwr-YVoz58sKqD9HeE)

Gracias por la imagen anterior, se corrigió con el color que le corresponde!
Saludos!

2024-07-10 17:43 UTC, AgosLizzi approved these changes

2024-07-18 16:18 UTC, merged