RUP - Foco en registros de consulta
andes/app pull request #3042
Opened 2024-07-24 17:33 UTC by Fabio-Ramirez

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/RUP-407

### Funcionalidad desarrollada 

1. Se agrega variable para que exista el foco en pestaña "Registros de la consulta" cuando se selecciona un concepto
2. En el html prestacionEjecucion se reduce condición.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2024-07-26 14:25 UTC, AgosLizzi requested changes
Fabi, te dejo comentario de lo charlado...
No se visualizan los cambios detallados en el pr!

Gracias Agos, corrección aplicada.

2024-07-26 16:27 UTC, AgosLizzi approved these changes

2024-07-26 17:06 UTC, Fabio-Ramirez reviewed
Test Ok!
https://cloud.cypress.io/projects/xr7gft/runs/10347/overview?roarHideRunsWithDiffGroupsAndTags=1

2024-07-31 14:44 UTC, negro89 approved these changes

2024-08-08 15:04 UTC, merged