HUDS - Fix al eliminar reemplazo de privacy en elemento rup
andes/app pull request #3044
Opened 2024-07-25 12:41 UTC by ma7payne

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/HUDS-116

### Funcionalidad desarrollada 

1. Se elimina condición con timeout que pisa el estado del campo privacy en los registros de las prestaciones

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2024-07-25 13:34 UTC, silviroa requested changes
con el cambio, los registros asociados a un elemento rup que tiene configurado por params el scope no quedan guardados con dicha configuracion

2024-07-25 14:19 UTC, ma7payne commented
> con el cambio, los registros asociados a un elemento rup que tiene configurado por params el scope no quedan guardados con dicha configuracion

Listo el cambio para chequear @silviroa !

2024-07-25 14:58 UTC, silviroa approved these changes

2024-07-26 11:59 UTC, MCele approved these changes

2024-07-26 12:39 UTC, ma7payne commented
TEST OK [#11283](http://condorpiedra.andes.gob.ar/job/andes-test-integracion/11283/)

2024-07-26 13:40 UTC, merged