HUDS - Implementa vista exclusiva para procedimientos
andes/app pull request #3045
Opened 2024-07-25 17:02 UTC by ma7payne

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/HUDS-118
### Funcionalidad desarrollada 

1. Se implementa la vista para las prestaciones de tipo "procedimiento"
2. Se incorpora la nueva vista en punto de inicio de HUDS y en la ejecución de RUP

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2024-07-30 13:36 UTC, MarianoCampetella requested changes

2024-07-30 13:36 UTC, MarianoCampetella commented on src/app/modules/rup/components/huds/detalleProcedimiento.ts
> +    elementoRUP: IElementoRUP;
Esta variable parece no estar utilizándose en ninguna parte. De ser así eliminarla.

2024-08-05 18:27 UTC, ma7payne commented
TEST OK [#11327](http://condorpiedra.andes.gob.ar/job/andes-test-integracion/11327/)

2024-08-27 14:48 UTC, Fabio-Ramirez approved these changes

2024-09-06 14:41 UTC, MarianoCampetella approved these changes

2024-09-06 14:41 UTC, MarianoCampetella commented on src/app/modules/rup/components/huds/detalleProcedimiento.ts
> +            this.prestacionRelacionada = prestacion.find(x => x.id === this.registro.idPrestacion);
A modo recordatorio (no es necesario realizar cambios) en caso de tener una función dentro de otra utilizar variables mas explicitas para saber sobre que estoy operando.

2024-09-11 12:40 UTC, silviroa requested changes
Al intentar visualizar un procedimiento, abre sobre una nueva pestaña una prestacion completa.
<img width="1433" alt="image" src="https://github.com/user-attachments/assets/77af3ccf-1119-462d-a9b5-95a1fbbdbebf">

2024-11-13 13:49 UTC, ma7payne commented
Listos los cambios pedidos por @silviroa !

2024-11-19 19:03 UTC, silviroa approved these changes

2024-11-21 14:32 UTC, merged