HUDS (Fix) - Agrega boton de descarga y UO en prestaciones de internación
andes/app pull request #3047
Opened 2024-07-29 14:56 UTC by negro89

### Requerimiento
Luego de la ultima actualización de HUDS no se visualiza el boton de descarga para las prestaciones de internación. Tampoco la unidad organizativa.

GLPI asociado: https://glpi.andes.gob.ar/front/ticket.form.php?id=4886

### Funcionalidad desarrollada 

1. Agrega botón de descarga y UO en las prestaciónes de internación.

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2024-07-29 17:10 UTC, negro89 commented
[Build #11295](http://condorpiedra.andes.gob.ar/job/andes-test-integracion/11295/) ✅

2024-07-30 12:35 UTC, MarianoCampetella requested changes

2024-07-30 12:35 UTC, MarianoCampetella commented on src/app/modules/rup/components/huds/internacion/detalleRegistroInternación.component.ts
> +    public colapsable = [];
Esta variable parece no estar utilizandose en ningún lado. De ser así eliminarla!

2024-07-30 12:35 UTC, MarianoCampetella commented on src/app/modules/rup/components/huds/internacion/detalleRegistroInternación.component.ts
> +        );
Me queda la duda de por qué dentro de esta suscripción hay dos asignaciones a una misma variable con el mismo valor? Será por algo en particular? Si se puede actualizarla ya que la misma se encuentra deprecada.

2024-07-30 14:59 UTC, MCele approved these changes

2024-07-30 15:35 UTC, merged