MPI -  Actualización select género
andes/app pull request #3050
Opened 2024-08-02 17:58 UTC by aldoEMatamala

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/MPI-434
### Funcionalidad desarrollada 

1. Se agregan registros de género a colección "constantes" en demo
2. En MPI se obliga a seleccionar un genero al seleccionar sexo='otro'

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2024-08-05 15:10 UTC, aldoEMatamala commented
![imagen](https://github.com/user-attachments/assets/2ff96011-9237-4312-919f-325f21f02097)

2024-08-09 12:38 UTC, Fabio-Ramirez requested changes
Compa, sabes que noto cuando seleccion "femenino" en el campo sexo, se autocompleta el campo género con "mujer", pero cuando selecciono "masculino", en el campo género no se autocompleta ningún dato. Dejo las capturas: 
![image](https://github.com/user-attachments/assets/384a203c-2121-4a36-b105-380c048b942f)

![image](https://github.com/user-attachments/assets/65493d58-2499-4421-9679-1ccb9bf19fd6)

2024-08-13 14:20 UTC, aldoEMatamala commented
> Compa, sabes que noto cuando seleccion "femenino" en el campo sexo, se autocompleta el campo género con "mujer", pero cuando selecciono "masculino", en el campo género no se autocompleta ningún dato. Dejo las capturas: ![image](https://private-user-images.githubusercontent.com/45831788/356593714-384a203c-2121-4a36-b105-380c048b942f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTY3MTYsIm5iZiI6MTcyMzU1NjQxNiwicGF0aCI6Ii80NTgzMTc4OC8zNTY1OTM3MTQtMzg0YTIwM2MtMjEyMS00YTM2LWIxMDUtMzgwYzA0OGI5NDJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEzNDAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MTUwYTFjN2ExMjJmMGI3NWY5MjU0YjY3MzQ1NTk4YmY4MTZlNDA0NzkzM2VkZjhiMjBmNGY3ZTlhNDU2YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2C7_vDPx9M4-Z79CrjbQSADLwt8C8lD8QVkd0SDa1uM)
> 
> ![image](https://private-user-images.githubusercontent.com/45831788/356593572-65493d58-2499-4421-9679-1ccb9bf19fd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTY3MTYsIm5iZiI6MTcyMzU1NjQxNiwicGF0aCI6Ii80NTgzMTc4OC8zNTY1OTM1NzItNjU0OTNkNTgtMjQ5OS00NDIxLTk2NzktMWNjYjliZjE5ZmQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEzNDAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhNmJkNzhjNjQwZjljOTYwM2FiNWYxODI5ODY4NTVmOGMxMDdjNTU5ZjQxNjY5OWM1MDAwMTY3NjkwMDE5MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9LxRYHbI7z8su4s9zdcVKLhpci6Wkpys2r1e2bWB1hE)

fabio! gracias por la revisión! me faltaba un tilde en "varon" que despues se modifico en bd. solucionado gracias por la observación

2024-08-27 13:03 UTC, Fabio-Ramirez approved these changes

2024-08-27 13:34 UTC, ma7payne commented
@aldoEMatamala Noto que cuando quiero guardar datos por primera vez y selecciono sex: "otro", el campo de género cambia y aparece el hint de obligatorio, pero no el error. Dejo video: https://www.loom.com/share/c2c74d915cec45b09b500a9383319697?sid=bb5fbf79-038c-4e83-93ed-efc8c905ca12

2024-09-25 13:26 UTC, negro89 commented
> @aldoEMatamala Noto que cuando quiero guardar datos por primera vez y selecciono sex: "otro", el campo de género cambia y aparece el hint de obligatorio, pero no el error. Dejo video: 


Corregido mati 👍🏼

2024-09-25 13:27 UTC, negro89 approved these changes

2024-09-25 15:39 UTC, aldoEMatamala commented
> > @aldoEMatamala Noto que cuando quiero guardar datos por primera vez y selecciono sex: "otro", el campo de género cambia y aparece el hint de obligatorio, pero no el error. Dejo video:
> 
> Corregido mati 👍🏼

gracias lauta por las correcciones! ahi quedo actualizada la rama, lo unico q modifique fue un tilde en "varon" para que lo pueda recuperar, es lo q habia observado fabio.

2024-09-25 17:02 UTC, merged