feat(CIT-293): cerrar demanda insatisfecha
andes/app pull request #3052
Opened 2024-08-06 18:39 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/CIT-293
https://proyectos.andes.gob.ar/browse/CIT-276

### Funcionalidad desarrollada 

1. Se implementa la funcionalidad de cerrar una demanda dandole un turno o seleccionando la opcion de finalizada con el motivo correspondiente.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si   https://github.com/andes/api/pull/1937
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2024-08-12 17:53 UTC, JuanIRamirez commented on src/app/components/turnos/dar-turnos/dar-turnos.component.ts
> +                this.tipoTurno === 'gestion';
Cambiar '===' por '='

2024-08-12 19:09 UTC, JuanIRamirez approved these changes

2024-08-13 12:08 UTC, Fabio-Ramirez requested changes
Compa, tal como lo vimos recién, al momento de "dar turno", las agendas disponibles a visualizar serían las mismas que aparecen en ventanilla, no las de TOP por ejemplo. Dejo imagen tomada con datos de demo.
![image](https://github.com/user-attachments/assets/9fd04a7c-54c2-4568-a5c4-44ef18941356)

2024-08-14 11:11 UTC, MarianoCampetella commented on src/app/components/turnos/dar-turnos/dar-turnos.component.ts
> +                this.tipoTurno === 'gestion';
Listo

2024-08-15 12:46 UTC, MarianoCampetella commented
> Compa, tal como lo vimos recién, al momento de "dar turno", las agendas disponibles a visualizar serían las mismas que aparecen en ventanilla, no las de TOP por ejemplo. Dejo imagen tomada con datos de demo. ![image](https://private-user-images.githubusercontent.com/45831788/357402973-9fd04a7c-54c2-4568-a5c4-44ef18941356.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MjYyNzAsIm5iZiI6MTcyMzcyNTk3MCwicGF0aCI6Ii80NTgzMTc4OC8zNTc0MDI5NzMtOWZkMDRhN2MtNTRjMi00NTY4LWE1YzQtNDRlZjE4OTQxMzU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDEyNDYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3YzMzOTI4OTVmMWQ1MWFkOTEzMWY3NmI2M2E1NDViNDgwYzAxNGFmZDBjN2Q2YjJkNzcxNDBiOWU1YjQ1MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nAssiIyXPoUt3PVj6RIdCgYZokE1QyLcg5M3HxM7vqE)

Corregido!

2024-08-22 13:34 UTC, JuanIRamirez approved these changes
Funciona OK

2024-08-26 15:15 UTC, negro89 approved these changes

2024-08-27 16:03 UTC, merged