HUDS - Implementa mejoras en buscador y cambios en UI
andes/app pull request #3054
Opened 2024-08-09 16:58 UTC by ma7payne

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/HUDS-113
https://proyectos.andes.gob.ar/browse/HUDS-120

### Funcionalidad desarrollada 

1. Implementa paginación de prestaciones en internación para visualizar sin tanto tiempo de carga
2. Se modifican vistas de registros para cargar selectivamente acorde al botón de despliegue
3. Se aplican diseño de mockup para la visualización en el listado de prestaciones de la internación
4. Se repara error de visualización de datos en prestaciones fuera de una internación

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2024-08-14 12:41 UTC, AgosLizzi approved these changes
Mati, un mini detalle. Se podrá corregir esta superposición que se genera?
![image](https://github.com/user-attachments/assets/2371d3af-e132-447e-9377-699ef7f7a169)

2024-08-16 17:07 UTC, ma7payne commented
> Mati, un mini detalle. Se podrá corregir esta superposición que se genera? ![image](https://private-user-images.githubusercontent.com/72876985/357815081-2371d3af-e132-447e-9377-699ef7f7a169.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MjgzNDksIm5iZiI6MTcyMzgyODA0OSwicGF0aCI6Ii83Mjg3Njk4NS8zNTc4MTUwODEtMjM3MWQzYWYtZTEzMi00NDdlLTkzNzctNjk5ZWY3ZjdhMTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDE3MDcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ODA1MjI2Mjk4NTRjMzFlOTQ5YmEwMmY1NjQ4MzkzMzQ0Y2M0NmI5NTFjMzUzOGQ5ZGNlYjQ3YWUxMjZkMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r1178FhXsySqLS6y2HDzX4X3MaR0mAw70sS3w59gxtY)

Listo ese cambio!

2024-08-23 14:26 UTC, negro89 approved these changes
exceleenteeeee

2024-08-23 17:37 UTC, MCele requested changes
Mati la paginación en internación se ve muy bien! Sólo veo que se está separando por conceptos (o elementos RUP) la visualización de las prestaciones que no quedan asociadas a una internación. Ej: en la imagen se ven todos registros separados y no se disntigue a qué prestación corresponden cada uno, en ese caso la navegación me parece que debería ser por prestaciones, similar a la de una internación
![image](https://github.com/user-attachments/assets/13c479b4-0db8-4320-a3a4-e8e44d5bce92)

2024-08-30 15:28 UTC, negro89 commented
Mati, acabo de darme cuenta que manualmente se puede intruducir un valor de pagina que exceda la cantidad total. Un controlcito por acá y listo. Dejo video: https://www.loom.com/share/47ffb54c99894af19ba5701cd552efbe?sid=1dd74ec9-c6ed-450c-8472-6bdfbde4dfcd

2024-09-06 15:14 UTC, ma7payne commented
Quedaron listos los cambios pedidos por @MCele y @negro89.  Quedo atento!

2024-09-11 15:56 UTC, negro89 commented
> Quedaron listos los cambios pedidos por @MCele y @negro89. Quedo atento!

Joya, por mi lo de la paginación quedó de 10

2024-09-11 16:00 UTC, MCele approved these changes

2024-09-11 17:03 UTC, merged