Tm 34
andes/app pull request #3061
Opened 2024-08-23 18:04 UTC by MarianoCampetella

### Requerimiento
 

### Funcionalidad desarrollada 

1. Se desarrolla el nuevo modulo de farmacias que permite cargar una nueva farmacia, editar una cargada y eliminar la que se desee (esta última por el momento solo la inhabilita desde la base de datos)

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [X] Si
- [ ] No

Remplazar o agregar el siguiente JSON en la coleccion "módulos" para poder ver el nuevo modulo de farmacias. 
En caso contrario acceder por ruta http://localhost:4200/tm/farmacia con los permisos correspondientes.

### Requiere actualizaciones en la API

- [X] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No -> No requiere ya que es un nuevo módulo aunque a futuro se pueden agregar nuevos test

2024-09-06 13:56 UTC, Fabio-Ramirez requested changes
Compa te dejo algunas sugerencias, si se pueden corregir: 

1. El dato CUIT, se podría tomar expressiones regulares algo como en matricualciones por ejemplo.

2. Los campos de Matrícula D.T y Número caja, entiendo que estan asociados a valores numéricos unicamente, pero puedo colocar cualquier cadena de caracteres.

3. El campo Horarios, permite cualquier ingreso.

Dejo imagenes señalando los anteriores puntos. 
![TM-34](https://github.com/user-attachments/assets/6414d522-3c93-4e83-a806-83534c60c25e)
![TM-34- PARTE2](https://github.com/user-attachments/assets/d418ea60-a507-4147-80f2-30dcdceb710e)

2024-09-09 14:15 UTC, MarianoCampetella commented
> 1. El dato CUIT, acepta cualquier valor, en todo caso se podría tomar expressiones regulares algo como en matricualciones por ejemplo.

2024-09-09 14:23 UTC, MarianoCampetella commented
> Compa te dejo algunas sugerencias, si se pueden corregir:
> 
> 1. El dato CUIT, acepta cualquier valor, en todo caso se podría tomar expressiones regulares algo como en matricualciones por ejemplo.
> 2. Los campos de Matrícula D.T y Número caja, entiendo que estan asociados a valores numéricos unicamente, pero puedo colocar cualquier cadena de caracteres.
> 3. El campo Horarios, permite cualquier ingreso.
> 
> Dejo imagenes señalando los anteriores puntos. ![TM-34](https://private-user-images.githubusercontent.com/45831788/365190805-6414d522-3c93-4e83-a806-83534c60c25e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4ODQxNzAsIm5iZiI6MTcyNTg4Mzg3MCwicGF0aCI6Ii80NTgzMTc4OC8zNjUxOTA4MDUtNjQxNGQ1MjItM2M5My00ZTgzLWE4MDYtODM1MzRjNjBjMjVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDEyMTExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MmM5ODliNzczNTBjMmQwM2IzYTQxZTk3YzhjZmNiMmZlMDQxZWRhMDlkNTEwOTM1MzQ2Y2ZiZDFmMjcxODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-7faf1i29TL6ihgwfBkMD6mIPYnKV4PBcf8DEySj4OM) ![TM-34- PARTE2](https://private-user-images.githubusercontent.com/45831788/365190886-d418ea60-a507-4147-80f2-30dcdceb710e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4ODQxNzAsIm5iZiI6MTcyNTg4Mzg3MCwicGF0aCI6Ii80NTgzMTc4OC8zNjUxOTA4ODYtZDQxOGVhNjAtYTUwNy00MTQ3LTgwZjItMzBkY2RjZWI3MTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDEyMTExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1OTg0NmY5ODI1MjkyY2U1YmQ3NmUwYzk0NzRkMTJkOTM5ZmNkNDUwYzM5Y2YxYWU0OTE1YjE1NDNjYmNmMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z0xOUg739H2qIvqp5mw62HdQQmfOz7O8P2wRmDQgnp8)

1- Se agrego una expresión regular para que solamente pueda tomar valores numéricos al momento de ingresar el numero de una matrícula. 
2- También se agrego una expresión regular sobre matrícula DT y matrícula de farmacéutico auxiliar para que solamente acepte números pero numero de caja suelen escribirlo de la siguiente manera: CAJA N° XX lo cual se decide que se permita ingresar caracteres. 
3- El campo horario por el momento se permite que ingrese cualquier carácter debido a que existen múltiples formas de ingresar un horario, es decir, no es el mismo para las múltiples farmacias que existen.  

Estoy atento a nuevos comentarios y/o sugerencias de cambios! Saludos.

2024-09-10 16:03 UTC, AgosLizzi requested changes
Campe, en general lo veo bien. Solo dos detalles:

1. en el label de inicio, cuando no hay listado yo cambiaría el writing por _"Edite algún filtro o cargue una nueva farmacia"_
2. Veo un poco confuso al momento de cargar estas acciones, esto va para todas las secciones que tienen el botón "+". Cómo hago para confirmar los datos que estoy agregando?
![image](https://github.com/user-attachments/assets/7773c454-b27f-42a4-9e7f-4bf0c4cdd5f5)

2024-09-17 14:51 UTC, MarianoCampetella commented
> Campe, en general lo veo bien. Solo dos detalles:
> 
> 1. en el label de inicio, cuando no hay listado yo cambiaría el writing por _"Edite algún filtro o cargue una nueva farmacia"_
> 2. Veo un poco confuso al momento de cargar estas acciones, esto va para todas las secciones que tienen el botón "+". Cómo hago para confirmar los datos que estoy agregando?
>    ![image](https://private-user-images.githubusercontent.com/72876985/366119458-7773c454-b27f-42a4-9e7f-4bf0c4cdd5f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1ODMzNTYsIm5iZiI6MTcyNjU4MzA1NiwicGF0aCI6Ii83Mjg3Njk4NS8zNjYxMTk0NTgtNzc3M2M0NTQtYjI3Zi00MmE0LTllN2YtNGJmMGM0Y2RkNWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDE0MjQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MWIwZDFiNWY4ZTVlMWE4ZmY2OTZmMmVhNzM2YjcxOGIxNDkwNDAxMmRiMjA2ZmNlYjUzOTBmZDU1MDhmOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KVZ3PZe2kCYtlO0eqUfOzK7i5yi4onXVAJ5V6YIZbMs)

1- Se modificó el writin a "Edite algún filtro o cargue una nueva farmacia"
2- Cuando se agrega un nuevo farmacéutico auxiliar, un nuevo horario o nuevo contacto, se comporta de la misma forma que ocurre en múltiples módulos como por ejemplo matriculaciones. Cuando ingresamos algunos de estos datos adicionales, si no se completan los campos requeridos no me dejará guardar. Es por eso que lo mejor es completar todos los datos de forma secuencial y llenando los campos requeridos de tal forma que se pueda habilitar dicho botón.

Estoy atento a nuevas correcciones o sugerencias!

2024-09-18 14:58 UTC, MarianoCampetella commented
Se agregan nuevas correcciones solicitadas en la tarea https://proyectos.andes.gob.ar/browse/TM-38

Estoy a la espera de correcciones o resultados. Saludos!

2024-09-20 13:15 UTC, AgosLizzi requested changes
Campe, van un par de cambios para los writings, si la palabra ya esta en el título, en el subtitulo no es necesario repetirla, teniendo "una o uno" se reemplaza y se entiende.

![image](https://github.com/user-attachments/assets/a619f20f-84c4-4ff8-b8b9-17fba0a8497d)

No hay contactos cargados
Para agregar uno diríjase a la edición de la farmacia.

No hay ninguna disposición aún
Para agregar una presioná el botón AGREGAR DISPOSICIÓN

No hay ninguna sanción aún
Para agregar una, presioná el botón AGREGAR SANCIÓN

2024-10-01 11:48 UTC, MarianoCampetella commented
> No hay ninguna sanción aún

Corregido, se cambiaron todas las leyendas eliminando las palabras redundantes. 
Estoy atento a nuevas correcciones.
Saludos!

2024-10-01 14:21 UTC, AgosLizzi approved these changes

2024-10-22 19:08 UTC, merged