feat(MPI-438): MPI - reporte de errores de renaper
andes/app pull request #3080
Opened 2024-10-08 17:14 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MPI-438

### Funcionalidad desarrollada 

1.  Se cambio el label del bool de reportar errores de renaper
2.  Se quito el input de escribir un texto del reporte de error y se agregaron dos nuevos input para agregar el nombre y apellido correcto del paciente.
3. Se agrega un nuevo modal en caso de que el nombre y apellido sea igual al que se registro en MPI.
4. Se agregan nuevas leyendas sobre el reporte de error de Renaper.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si   https://github.com/andes/api/pull/1972
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2024-10-18 15:47 UTC, AgosLizzi requested changes
Campe, según lo charlado ... 
el icono de  "documento-cruz" apenas se ve, y no se logra a distinguir el circulo que va en conjunto con el icono. Probaría con otro icono, capaz alguna que sea  cruz. Puedo buscar alguno si queres

![image](https://github.com/user-attachments/assets/3cf4a140-4c2b-4121-84e7-2bc68ca9d406)


Se cambiaron los dos iconos por los que se muestran en la imagen. 
![image](https://github.com/user-attachments/assets/1bf605ed-ed24-4947-b7d8-38e5ccac2d78)

2024-10-22 18:49 UTC, MarianoCampetella commented
> Campe, según lo charlado ... el icono de "documento-cruz" apenas se ve, y no se logra a distinguir el circulo que va en conjunto con el icono. Probaría con otro icono, capaz alguna que sea cruz. Puedo buscar alguno si queres
> 
> ![image](https://private-user-images.githubusercontent.com/72876985/377930504-3cf4a140-4c2b-4121-84e7-2bc68ca9d406.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MjMyNDIsIm5iZiI6MTcyOTYyMjk0MiwicGF0aCI6Ii83Mjg3Njk4NS8zNzc5MzA1MDQtM2NmNGExNDAtNGMyYi00MTIxLTg0ZTctMmJjNjhjYTlkNDA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDE4NDkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3YzJjMzk1YjdmMTFiZmYyODcyYjlmMjVkYzRmOTI0YzZkZGUwNGY4Mjk3YzM2NmIxMjI5ZDJlNzY4MDJhZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xmr_BDi96-KNpiRMpVXjl5XiLQu14tt_UR8TMJyY71Y)

Se cambiaron los dos iconos por los que se muestran en la imagen. Estoy atento para nuevas correcciones!
![image](https://github.com/user-attachments/assets/78d13ff7-583d-4031-a884-a75fff4dfd5e)

2024-10-23 13:56 UTC, AgosLizzi approved these changes

2024-11-19 13:10 UTC, negro89 commented
Funciona de 10, el unico de talle que encontré (no era parte de esta tarea) es que el listado de errores reportados se ordena por fecha de creación, sin embargo la fecha que se muestra en un badge azul a la derecha de cada item es la de actualización. Esto en algunos casos parecería un error de ordenamiento del listado. Dejo ejemplo en imagen adjunta..

Consulta: en la leyenda "si hay un error en RENAPER, ..." no está un poco grande el tamaño de la fuente??

![image](https://github.com/user-attachments/assets/2d90c5f7-f18a-43a0-afdb-50c583cd858f)

2024-11-19 15:24 UTC, negro89 approved these changes

2024-11-21 15:44 UTC, merged