feat(PLEX): actualiza a version 8.0.5
andes/app pull request #3088
Opened 2024-10-18 17:07 UTC by ma7payne

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/PLEX-355

### Funcionalidad desarrollada 

Novedades de la versión 8.0.5:

PLEX-TEXT - Implementa validación personalizada
PLEX-TEXT - Repara error de vista html en plex-text
PLEX-HELP - Implementa mejoras funcionales
PLEX-HINT - Implementa mejoras en plex-hint
PLEX-HELP - Scroll y maxHeight opcionales en plex-help
PLEX-BOOL - Corregir overflow en checkbox

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2024-10-23 12:33 UTC, negro89 commented
Mati, como lo charlamos hay algunos temitas con el texto enriquecido. Dejo video https://www.loom.com/share/60f9caa873dd46ec9917d19744b3ed4f?sid=56626cdf-5f57-44c8-a5cf-0640215fcd1e

2024-12-13 18:24 UTC, negro89 approved these changes

2024-12-17 12:33 UTC, AgosLizzi requested changes
Mati, van dos observaciones pequeñas:
- Sobre el componente Plex text, esta bien este comportamiento? te dejo video para que lo veas. 
https://www.loom.com/share/c13df81a1f5b4e3fb854c8ec6b435892

- Cuando agrego por primera vez, me aparece la leyenda "undefined". Se podría cambiar?Tal vez por algún texto que se relacione a lo que la persona usuaria esta por realizar.
![image](https://github.com/user-attachments/assets/884aa1cf-9c9e-4097-9995-17419bf8b3a3)

2025-01-17 14:39 UTC, AgosLizzi requested changes
Sigo viendo el Undefined 
![localhost_4200_rup_ejecucion_678a63d832a2fe038e441a36](https://github.com/user-attachments/assets/57c32a1b-6ee8-4ef3-976c-12118438ba9b)

2025-02-20 18:55 UTC, ma7payne commented
> Sigo viendo el Undefined ![localhost_4200_rup_ejecucion_678a63d832a2fe038e441a36](https://private-user-images.githubusercontent.com/72876985/404338027-57c32a1b-6ee8-4ef3-976c-12118438ba9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDAwNzc3NDgsIm5iZiI6MTc0MDA3NzQ0OCwicGF0aCI6Ii83Mjg3Njk4NS80MDQzMzgwMjctNTdjMzJhMWItNmVlOC00ZWYzLTk3NmMtMTIxMTg0MzhiYTliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjIwVDE4NTA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1YWQyY2RhZWVmOTk1YTUxOGQ5NTA1YmU5NmRiY2MwYzBlNWU4ZWMxNGNmODgwNDM5MTk5MjQ2YTZkNWNiODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xXEMkKCZ3lKtCUqo5x_UcbSwRNrNVkARZbWl3hGnuKg)

@AgosLizzi esta listo el cambio para chequear!

2025-02-21 13:39 UTC, AgosLizzi approved these changes

2025-03-06 13:55 UTC, negro89 commented
checkeado, quedó de 10 👍🏼

2025-03-10 14:00 UTC, merged