CIT - clonar agendas si los conceptos turneables tienen ámbito ambulatorio
andes/app pull request #3090
Opened 2024-10-23 18:40 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/CIT-303

### Funcionalidad desarrollada 

1.  Se agregaron condiciones a la hora de clonar agendas para que esta misma acción no se pueda realizar en caso de que las prestaciones no presenten ámbito ambulatorio. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

NOTA: Se podría agregar un test donde se intente clonar una agenda que tenga una prestación con ambito distinto al de "ambulatorio" mostrando el mensaje correspondiente.

2024-11-21 16:08 UTC, MCele requested changes

2024-11-21 16:08 UTC, MCele commented on src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
> +        agenda.tipoPrestaciones.forEach(prestacion => {
Campe esto está perfecto si la agenda ya tiene actualizado el ámbito de la prestación, pero esos casos son los menos, ya que entiendo que hoy agendas con prestaciones sin ámbito ambulatorio no se pueden crear. Entonces, me parece que con este control no alcanza, porque debería hacerse con los datos de la colección conceptosTurneables. Más que nada considerando que esa colección es en la que mantenemos actualizado los ámbitos por prestaciones. Si se modifica el ámbito para una prestación particular desde ahí, y ya existen agendas creadas para esa prestación, el ámbito que contienen no se actualiza, sigue conteniendo el que se originó al momento de la creación de la agenda

2024-11-21 16:08 UTC, MCele commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
> +        let incluyeAmbulatorio = true;
mismo comentario anterior. Por otro lado, me hace ruido que se repita tanto código, pero quizás escapa a los fines de esta tarea

2024-12-12 14:49 UTC, MarianoCampetella commented on src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
> +        agenda.tipoPrestaciones.forEach(prestacion => {
Corregido, ahora en vez de consultar la prestación desde la agenda, lo hace desde el concepto turneable.

2024-12-12 14:50 UTC, MarianoCampetella commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
> +        let incluyeAmbulatorio = true;
Corregido! Si bien comparten las mismas condiciones con el código de arriba, las implementaciones no son tan parecidas. Incluso escapa a los fines de la tarea.

2024-12-13 19:20 UTC, negro89 requested changes

2024-12-13 19:20 UTC, negro89 commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
> +        this.modelo.tipoPrestaciones.forEach(prestacion => {
Campe, se entiende la idea pero el resultado de este codigo es impredecible ya que se está aplicando asincronismo (search) a una repetitiva foreach. Lo correcto sería usar un forkjoin para traer los conceptos correspondientes a cada prestación y trabajar el control del ambito dentro del subscribe de este forkjoin. Lo mismo para el resto de los casos. Consultame cualquier cosa 👍🏼

2024-12-19 15:07 UTC, MarianoCampetella commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
> +        this.modelo.tipoPrestaciones.forEach(prestacion => {
Corregido en ambos casos!

2025-01-03 18:20 UTC, MarianoCampetella commented
Se realizaron nuevas correcciones! Estoy atento por si hay nuevas devoluciones. Saludos!

2025-01-10 14:48 UTC, Fabio-Ramirez reviewed
Compa tal como lo charlamos por slack, el tema es cuando clono una agenda que esta "EN PLANIFICACION" y con un tipo de prestación que no es ambulatoria, sucede que lo realiza igual. Por si te sirve el dato, probe desde el efector de Plottier con la prestacion ANAMNESIS.

2025-01-14 18:36 UTC, MCele approved these changes

2025-01-15 13:06 UTC, Fabio-Ramirez approved these changes

2025-01-21 18:26 UTC, negro89 reviewed
Campe te dejo un par de observaciones. Si son ciertas, sugeriría que para no perder tiempo  agregues un chequeo en la respuesta (despues del flat) de que efectivamente tenes tantos elementos como request enviaste.
Con eso creo que estaria todo ok

2025-01-21 18:26 UTC, negro89 commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
> +                catchError(() => of([]))
En esa linea, si hay un error en alguno de los request de _observables$_, a la respuesta en el array resultante le faltaria un elemento segun entiendo, y si es asi, el proceso seguiría como si nada y los controles posteriores no revisarían esa prestacion (avisame si estoy errado)

2025-01-21 18:26 UTC, negro89 commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
> +                incluyeAmbulatorio: prestaciones.every(p => p.ambito.includes('ambulatorio')),
En esta linea se está evaluando si todas las prestaciones tienen ambito ambulatorio (quizas me confunde el nombre de la constante, que me da a entender que se quiere saber si alguna prestacion tiene ambito ambulatorio). En cualquier caso, la observacion del punto 1 influye en este resultado ya que si es correcta faltaría evaluar la prestación que no pudo resolver el request

2025-02-10 16:11 UTC, negro89 commented
@MarianoCampetella buenass, paso a recordar el pedido de cambios. Saluditoss

2025-02-11 18:28 UTC, MarianoCampetella commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
> +                catchError(() => of([]))
Corregido! Se saco el catch para agregarlo dentro del forkJoin y de esta manera poder trabajar el error de forma mas global.

2025-02-11 18:29 UTC, MarianoCampetella commented on src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
> +                incluyeAmbulatorio: prestaciones.every(p => p.ambito.includes('ambulatorio')),
Se agrega dentro del forkJoin el catch para que una vez hecha las peticiones necesarias dentro del search, si alguna de ellas fallas no continué con la ejecución del código.

2025-02-13 16:47 UTC, negro89 approved these changes

2025-02-13 16:48 UTC, merged