EP - No mostrar fichas deshabilitadas
andes/app pull request #3095
Opened 2024-10-29 18:52 UTC by agustin1996ra

### Requerimiento
 
[EP-237](https://proyectos.andes.gob.ar/browse/EP-237)

### Funcionalidad desarrollada 

1. No se muestran las fichas deshabilitadas

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2024-11-05 14:35 UTC, Fabio-Ramirez approved these changes

2024-11-06 15:42 UTC, AgosLizzi approved these changes

2024-11-08 14:14 UTC, negro89 reviewed
Agus, funciona de 10 👌🏼. Solo te hice una observación sobre el llamado a los servicios. Habría que replicar la corrección a los otros casos 👍🏼

2024-11-08 14:14 UTC, negro89 commented on src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
> +                this.formEpidemiologiaService.update(this.fichaPaciente._id, fichaFinal).subscribe((fichaFinal) => {
Estas subscripciones tienen implementada una manera de capturar los errores y manejar el resultado del request que nos ahorra el uso de try-catch (por eso vas a ver que no los usamos del lado de la app). Te dejo la sugerencia para este caso..
```suggestion
this.formEpidemiologiaService.update(this.fichaPaciente._id, fichaFinal).subscribe({
            next: (fichaFinal) => {
                    this.plex.toast('success', 'Su ficha fue actualizada correctamente');
                    this.postSave(fichaFinal);
            },
            error: () => this.plex.toast('danger', 'ERROR: La ficha no pudo ser actualizada')
        });
                
```

2024-11-12 11:58 UTC, agustin1996ra commented on src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
> +                this.formEpidemiologiaService.update(this.fichaPaciente._id, fichaFinal).subscribe((fichaFinal) => {
Muchas gracias, quise salvar el error del subscribe deprecado pero lo había entendido mal claramente

2024-11-13 12:46 UTC, silviroa requested changes
Cuando se guarda la ficha, no se esta volviendo al punto de inicio. Esto podría generar que guarden la misma ficha varias veces

2024-11-19 18:36 UTC, merged