feat(CIT-348): Guardado incorrecto de sobreturnos
andes/app pull request #3098
Opened 2024-10-30 17:54 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/CIT-348

### Funcionalidad desarrollada 

1. Se saca modal al momento de guardar un subre turno desde el gestor de agendas, agregando un toast con el mensaje correspondiente y cerrando el sidebar.
2. Se inhabilita el botón guardar una vez seleccionado para evitar duplicar turnos con el mismo horario.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2024-11-01 12:23 UTC, AgosLizzi requested changes
Campe, la tarea se ve bien. Tengo dos dudas:

1. La primera, Sería conveniente que se muestren los datos del sobreturno? 
2. Desde citas, había que cambiar el toast? 
![image](https://github.com/user-attachments/assets/1a85cdae-1118-495f-ac3c-f8a8616e4b15)

2024-11-12 18:35 UTC, MarianoCampetella commented
> Campe, la tarea se ve bien. Tengo dos dudas:
> 
> 1. La primera, Sería conveniente que se muestren los datos del sobreturno?
> 2. Desde citas, había que cambiar el toast?
>    ![image](https://private-user-images.githubusercontent.com/72876985/382277903-1a85cdae-1118-495f-ac3c-f8a8616e4b15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MzY1OTEsIm5iZiI6MTczMTQzNjI5MSwicGF0aCI6Ii83Mjg3Njk4NS8zODIyNzc5MDMtMWE4NWNkYWUtMTExOC00OTVmLWFjM2MtZjhhODYxNmU0YjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE4MzEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzOTQ3OTQ1NTQwODA5OTk3Mzk1MGY1OGU3MTg3NTJlOWVlZmYxNmRhNzY2OTg5ZjU1NDJjODU0ZjM2ZGRlNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-NG2Z0hT6pnoC4nvDvnQkV3pgRgf425FWW4zPRfnOI8)

1. En base al primer comentario no se logra entender a que te referís con mostrar los datos del sobreturno. Si genera algún tipo de confusión o si es necesario poder distinguir un turno de un sobreturno. 
2. El toast se cambio a color verde. 

Estoy atento a nuevos cambios y/o sugerencias.

2024-11-19 11:16 UTC, AgosLizzi approved these changes
@MarianoCampetella Me refería a la posibilidad de poder visualizar la información del sobreturno guardado, en caso de tener muchas agendas se podría prestar a confusión de a cual corresponde... De todas maneras dejémoslo para analizar en otra tarea

2024-11-20 17:22 UTC, negro89 approved these changes

2024-11-21 15:17 UTC, merged