IN - Modificar carga de OS en alta de internación capa estadística
andes/app pull request #3107
Opened 2024-11-12 17:21 UTC by MarianoCampetella

### Requerimiento
https://github.com/andes/api/pull/1994

### Funcionalidad desarrollada 

1. https://proyectos.andes.gob.ar/browse/IN-619

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si     https://github.com/andes/api/pull/1994
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2024-12-13 17:46 UTC, aldoEMatamala commented
Buenas campe ! estuve consultando y queda pendiente el registro de la OS en la prestación 
![image](https://github.com/user-attachments/assets/a01ae637-af35-4232-abc3-7ced5d0f2e8f)
![image](https://github.com/user-attachments/assets/b6a22112-bb8c-49b0-ab47-7801dffdbc20)

2024-12-13 17:50 UTC, aldoEMatamala requested changes
Buenas campe ! estuve consultando y si bien se registra la nueva OS en paciente, queda pendiente el registro de la misma en la prestación 
![image](https://github.com/user-attachments/assets/a01ae637-af35-4232-abc3-7ced5d0f2e8f)
![image](https://github.com/user-attachments/assets/b6a22112-bb8c-49b0-ab47-7801dffdbc20)

2025-01-02 16:08 UTC, MarianoCampetella commented
> Buenas campe ! estuve consultando y si bien se registra la nueva OS en paciente, queda pendiente el registro de la misma en la prestación ![image](https://private-user-images.githubusercontent.com/123381977/395649989-a01ae637-af35-4232-abc3-7ced5d0f2e8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4MzQzMjQsIm5iZiI6MTczNTgzNDAyNCwicGF0aCI6Ii8xMjMzODE5NzcvMzk1NjQ5OTg5LWEwMWFlNjM3LWFmMzUtNDIzMi1hYmMzLTdjZWQ1ZDBmMmU4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMlQxNjA3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjgyYmRjODY5YmNlODI2YTk2N2NkYWEwNzRkYTA3Yzc0ZGQ4NGE1ZDNmNGE0YzBjYTdiNDU4NzhmZDg5YWVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3kDmwdkR9Un-oxqZjdDRHAy_MpNVl5wAPBKGnDtDRYo) ![image](https://private-user-images.githubusercontent.com/123381977/395650428-b6a22112-bb8c-49b0-ab47-7801dffdbc20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4MzQzMjQsIm5iZiI6MTczNTgzNDAyNCwicGF0aCI6Ii8xMjMzODE5NzcvMzk1NjUwNDI4LWI2YTIyMTEyLWJiOGMtNDliMC1hYjQ3LTc4MDFkZmZkYmMyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMlQxNjA3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTc0ZTA4ZmNlNTBmMGQ2NzA3NGE0ZWU2ZmU0NGE4ZGQ0ZjBiM2NlMTI3Yjg0ZmVjNGZjNzgwNGZiY2YwMDc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7vBJnV0oaP3U3_TRguY_yC4CCS28_1iUNnVWBopCT8Y)

Muy buena observación!! Ya quedo corregido, ahora tambien se modifica la obra social del paciente dentro de la prestación cuando se la crea.

2025-01-21 15:07 UTC, negro89 requested changes
Campe, algunas cosas no me estarían funcionando. Decime si tambien te pasa..
- Opcion 1: se selecciona bien pero al visualizar en el sidebar no muestra la obra social
![image](https://github.com/user-attachments/assets/738c7efe-32c8-43b6-b011-485e174bc763)
esto es porque en la base guarda null
![image](https://github.com/user-attachments/assets/d8f4e435-22b4-4531-a228-ad72ef5094fc)


- Opcion 2: seleccionando no muestra el select para elegir obra social pero por defecto guarda la declarada previamente en algun momento en andes. Se guarda bien en base y se ve bien en sidebar pero debería dejar elegir al momento de la seleccion
![image](https://github.com/user-attachments/assets/363b7392-3f28-4efe-be9a-d2e3137f4dbf)


- Opciones 3 y 4 (ninguna - sin datos): no muestra ningun valor en el titulo "obra social" (No deberia mostrarse esta columna ya que no hay cobertura)

**OBSERVACION:** Fijate que en la api parece que hay unos tests que no pasaron

2025-02-20 15:27 UTC, MarianoCampetella commented
> > Gracias por las observaciones laucha, a continuacion voy detallando cada una de lo que se fue haciendo: Opción 1: Se corrigió un problema en el que la obra social no se mostraba en el sidebar al seleccionar una obra social pública (si corresponde) o una obra social privada al editar un ingreso.
> > Opción 2: Según lo acordado previamente, al seleccionar una obra social pública, no debe aparecer un selector de obra social. Esta acción solo ocurre cuando se elige una obra social privada.
> > Opción 3: La columna "Obra Social" no se muestra cuando se seleccionan las opciones "Sin Datos" o "Ninguno".
> > PD: Ahora pasaron los test de la api!
> > Estoy a la espera de nuevas correcciones!
> 
> Campe, va un ultimo feedback:
> 
> Opcion 2: Esta bien que no te muestre el selector de obra social en este caso, pero a lo que me refería es que en modo lectura (cuando no se esta editando) APARECE UNA OBRA SOCIAL si el paciente la tuvo asignada en algun momento, lo cual no debería. Dejo imagen a continuacion.
> 
> ![image](https://private-user-images.githubusercontent.com/37875706/412940518-a85a3bdc-7bc9-4dd2-92a4-e6b022797127.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDAwNjU1MTEsIm5iZiI6MTc0MDA2NTIxMSwicGF0aCI6Ii8zNzg3NTcwNi80MTI5NDA1MTgtYTg1YTNiZGMtN2JjOS00ZGQyLTkyYTQtZTZiMDIyNzk3MTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjIwVDE1MjY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhNjliMWM3YWJlNTE5YjAzZTA0MWIwNmYzODIwYWExNjFkNDk0NzIxMDgzYmUxNWJlMjZiMzQzMmQ4N2E0YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f9V_S4BdKpnRvplLFHhJn5FNTsE56N5LzQbD6CT_Aks)
> 
> Otras observaciones: 1- Si se selecciona una obra social privada con lo cual aparece el select de obras sociales, deshabilitar el botón guardar hasta que se agregue una! 2- Si se selecciona una obra social publica, el campo "obraSocial" debe guardarse como null.
> 
> El resto todo ok 👍🏼

Corregido lo solicitado!

2025-03-07 14:39 UTC, negro89 approved these changes

2025-03-07 19:03 UTC, merged