TOP - Anular solicitudes en AUDITORIA
andes/app pull request #3110
Opened 2024-11-20 14:07 UTC by Fabio-Ramirez

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/TOP-189

### Funcionalidad desarrollada 

1. Se habilita el botón "anular" en la bandeja de entrada y el botón "cancelar" en la bandeja de salida.
2. Además se limpia el campo "motivo" en el anular cuando se confirma, ya que antes quedaba el texto.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2024-12-17 13:40 UTC, AgosLizzi requested changes
Fabi, van algunas observaciones:
1. Cambiar el icono del botón para cancelar en la bandeja de salida. Es el mismo para Anular solicitud desde la bandeja de entrada y podría resultar confuso. 
2. Siguiendo con el comentario anterior, aplicaría el mismo orden para las botoneras 
3. Tener en cuenta confirmación sobre la solicitud que fue anulada mediante toast de tipo info.
4.  Solo si se puede, acomodar un poquito el modal. Centrar el título "Atención" y cambiar icono gris. Se adjunta imagen por sustituto a modo de ejemplo
![image](https://github.com/user-attachments/assets/f2b62de9-ed9a-4c9e-98be-e70be060d621)

![image](https://github.com/user-attachments/assets/06c14eea-287e-4b3f-9d13-6d129875755d)

2025-01-03 12:11 UTC, AgosLizzi approved these changes

2025-01-13 18:55 UTC, negro89 commented on src/app/components/top/solicitudes/solicitudes.component.ts
> +                    this.plex.toast('info', 'Prestación cancelada');
Este toast debería ser type="success" ya que es una operación exitosa. Además la acción que se lleva a cabo es "anular solicitud", por tanto me parece que el toast debería decir algo similar a "Solicitud anulada exitosamente".

2025-01-14 17:59 UTC, Fabio-Ramirez commented on src/app/components/top/solicitudes/solicitudes.component.ts
> +                    this.plex.toast('info', 'Prestación cancelada');
Corregido compa!

2025-01-17 13:12 UTC, negro89 approved these changes

2025-01-23 18:54 UTC, merged