IN -  Cambiar periodos de registros de internación
andes/app pull request #3115
Opened 2024-11-26 18:20 UTC by aldoEMatamala

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/IN-612
### Funcionalidad desarrollada 

1. Se reduce el rango inicial de registros de internación a 3 dias desde el día de la fecha
2. Se modifica el pedido de motivo de acceso a la HUDS a sólo una vez.

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [ ] No

2024-12-17 13:36 UTC, Fabio-Ramirez commented on src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
> +            // acceso$
Compa, estaria perfecto. Solamente si esta variable "acceso" no tiene utilidad, habria que eliminarlo, o bien se deja para una utilidad futura.

2025-01-09 18:52 UTC, aldoEMatamala commented on src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
> +            // acceso$
corregido! gracias por la observación

2025-01-22 18:47 UTC, negro89 requested changes
Compa, el filtro de fechas para los registros de la internacion quedó de 10 pero hay un temita con el modal de motivo de acceso: Por un lado, despues de varias pruebas me sigue pidiendo el motivo por cada vez que quiero ver los registros (acepto el modal, me muevo al tab "cama" y despues de nuevo a "internacion -> registros" y vuelve a pedir el motivo (yo supongo que debe estar molestando el behaviorSubject que agregaste). Por otro lado, si selecciono motivo y acepto y despues selecciono una cama sin paciente me vuelve a pedir el motivo (en demo actualmente no pasa). Dejo videito: https://www.loom.com/share/1902ad83dbb440f2860a81a32ccf0067?sid=d8847647-4144-42e6-9998-25eae1c7800e

La solución ideal seria almacenar un array con los ultimos motivos de acceso (hoy en dia solo se guarda el ultimo, es decir, cada vez que aceptamos el modal el motivo anterior se pisa) y cada vez que se solicite acceso a la huds revisar si en este array existe un token aún vigente que contenga al usuario logeado, paciente y organizacion. En caso de que exista se lo utiliza en lugar de generar un token nuevo.

Para esto deberían suceder las siguientes cosas:
1. los tokens deberían generarse con una validez de 1 hora
2. el array de tokens deberá tener un maximo de 15 elementos
3. los tokens vencidos deben borrarse del array

2025-02-13 18:56 UTC, aldoEMatamala commented
> Compa, el filtro de fechas para los registros de la internacion quedó de 10 pero hay un temita con el modal de motivo de acceso: Por un lado, despues de varias pruebas me sigue pidiendo el motivo por cada vez que quiero ver los registros (acepto el modal, me muevo al tab "cama" y despues de nuevo a "internacion -> registros" y vuelve a pedir el motivo (yo supongo que debe estar molestando el behaviorSubject que agregaste). Por otro lado, si selecciono motivo y acepto y despues selecciono una cama sin paciente me vuelve a pedir el motivo (en demo actualmente no pasa). Dejo videito: https://www.loom.com/share/1902ad83dbb440f2860a81a32ccf0067?sid=d8847647-4144-42e6-9998-25eae1c7800e
> 
> La solución ideal seria almacenar un array con los ultimos motivos de acceso (hoy en dia solo se guarda el ultimo, es decir, cada vez que aceptamos el modal el motivo anterior se pisa) y cada vez que se solicite acceso a la huds revisar si en este array existe un token aún vigente que contenga al usuario logeado, paciente y organizacion. En caso de que exista se lo utiliza en lugar de generar un token nuevo.
> 
> Para esto deberían suceder las siguientes cosas:
> 
> 1. los tokens deberían generarse con una validez de 1 hora
> 2. el array de tokens deberá tener un maximo de 15 elementos
> 3. los tokens vencidos deben borrarse del array

Hola lauta! gracias por los comentarios, quedan los tokenHuds en arreglo para que no vuelva a pedir, y queda la vigencia de 1hora
![image](https://github.com/user-attachments/assets/2dc4d69d-b8e6-4680-a1d7-59a4316f3295)

2025-03-26 14:41 UTC, negro89 approved these changes

2025-03-26 14:42 UTC, merged