CIT - Notificaciones: limpiar código innecesario
andes/app pull request #3117
Opened 2024-11-27 14:59 UTC by JuanIRamirez

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-355

### Funcionalidad desarrollada 

1. Se elimina código obsoleto 'enviarSms' y sus llamadas. 
2. Se quita if (environment.production === true)
3. Se modifica también suspender-turno.component para marcar el turno.avisoSuspension = 'enviado' o 'fallido' idem 
suspender-agenda.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2024-12-05 19:35 UTC, negro89 approved these changes
codigo ok

2024-12-17 14:14 UTC, Fabio-Ramirez approved these changes

2024-12-19 15:56 UTC, ma7payne requested changes

2024-12-19 15:56 UTC, ma7payne commented on src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.component.ts
> +            this.turnosService.patch(this.agenda.id, idBloque, turno.id, data).subscribe(resultado => {
@JuanIRamirez Veo en esta linea dos subscribe anidados, lo que resulta mala practica porque permite la fuga de memoria y dificultad para el manejo de errores. En su lugar se puede optar por pipe + switchMap o similar

2025-02-11 18:58 UTC, negro89 commented
@ma7payne ya estan subidas las correcciones 👌🏼 avisa cualquier cosita

2025-02-13 11:20 UTC, ma7payne approved these changes

2025-02-13 16:29 UTC, merged