CIT - cambiar tipo de visualización para notificar
andes/app pull request #3123
Opened 2024-12-11 14:29 UTC by MarianoCampetella

### Requerimiento
 

### Funcionalidad desarrollada 

1.  Se agranda el tamaño del checkbox y se cambia el color del mismo al momento de querer notificar al paciente cuando se suspende el turno o los turnos correspondientes.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [X] No

2024-12-17 14:04 UTC, AgosLizzi requested changes
Campe, el checkbox lo veo bien pero cuando cierro el modal sin realizar alguna acción y hago scroll me salta el siguiente error sobre la consola
![image](https://github.com/user-attachments/assets/2964e059-2260-4363-986c-3b3014d1182c)

2024-12-19 15:40 UTC, MarianoCampetella commented
> Campe, el checkbox lo veo bien pero cuando cierro el modal sin realizar alguna acción y hago scroll me salta el siguiente error sobre la consola ![image](https://private-user-images.githubusercontent.com/72876985/396527420-2964e059-2260-4363-986c-3b3014d1182c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MjEyNDYsIm5iZiI6MTczNDYyMDk0NiwicGF0aCI6Ii83Mjg3Njk4NS8zOTY1Mjc0MjAtMjk2NGUwNTktMjI2MC00MzYzLTk4NmMtM2IzMDE0ZDExODJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDE1MDkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNGUxZDRjNDRkOWM5MTkxNGM3MDVlMTgzNzljMWYxNGViZjg2YTBkMzA2ZGE3NzZjNjJhODY3ZDMzZTJkNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Mfi-scvnXGTRyPCfF0zHAY0BZD00AvJuEj5U3zPsZ88)

Agos, lo estuve probando de miles de manera y no logro poder reproducir el error, seleccione los turnos e hice un scroll, no selecciono nada y hago un scroll, suspendo los turnos y hago un scroll y ninguna de las opciones me genera un error. 
Si a alguien le sucede lo mismo entonces que me deje detallado en el PR como fue la manera de reproducirlo. 
Saludos!!

2024-12-27 14:07 UTC, AgosLizzi commented
> > Campe, el checkbox lo veo bien pero cuando cierro el modal sin realizar alguna acción y hago scroll me salta el siguiente error sobre la consola ![image](https://private-user-images.githubusercontent.com/72876985/396527420-2964e059-2260-4363-986c-3b3014d1182c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MjEyNDYsIm5iZiI6MTczNDYyMDk0NiwicGF0aCI6Ii83Mjg3Njk4NS8zOTY1Mjc0MjAtMjk2NGUwNTktMjI2MC00MzYzLTk4NmMtM2IzMDE0ZDExODJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDE1MDkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNGUxZDRjNDRkOWM5MTkxNGM3MDVlMTgzNzljMWYxNGViZjg2YTBkMzA2ZGE3NzZjNjJhODY3ZDMzZTJkNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Mfi-scvnXGTRyPCfF0zHAY0BZD00AvJuEj5U3zPsZ88)
> 
> Agos, lo estuve probando de miles de manera y no logro poder reproducir el error, seleccione los turnos e hice un scroll, no selecciono nada y hago un scroll, suspendo los turnos y hago un scroll y ninguna de las opciones me genera un error. Si a alguien le sucede lo mismo entonces que me deje detallado en el PR como fue la manera de reproducirlo. Saludos!!

Campe, okey. Lo revise denuevo y me lo sigue mostrando, será algo de demo? 
Apruebo el pr y tengamos en cuenta el error por las dudas

2024-12-27 14:07 UTC, AgosLizzi approved these changes

2025-01-02 15:15 UTC, MarianoCampetella commented
> > > Campe, el checkbox lo veo bien pero cuando cierro el modal sin realizar alguna acción y hago scroll me salta el siguiente error sobre la consola ![image](https://private-user-images.githubusercontent.com/72876985/396527420-2964e059-2260-4363-986c-3b3014d1182c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MjEyNDYsIm5iZiI6MTczNDYyMDk0NiwicGF0aCI6Ii83Mjg3Njk4NS8zOTY1Mjc0MjAtMjk2NGUwNTktMjI2MC00MzYzLTk4NmMtM2IzMDE0ZDExODJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDE1MDkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNGUxZDRjNDRkOWM5MTkxNGM3MDVlMTgzNzljMWYxNGViZjg2YTBkMzA2ZGE3NzZjNjJhODY3ZDMzZTJkNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Mfi-scvnXGTRyPCfF0zHAY0BZD00AvJuEj5U3zPsZ88)
> > 
> > 
> > Agos, lo estuve probando de miles de manera y no logro poder reproducir el error, seleccione los turnos e hice un scroll, no selecciono nada y hago un scroll, suspendo los turnos y hago un scroll y ninguna de las opciones me genera un error. Si a alguien le sucede lo mismo entonces que me deje detallado en el PR como fue la manera de reproducirlo. Saludos!!
> 
> Campe, okey. Lo revise denuevo y me lo sigue mostrando, será algo de demo? Apruebo el pr y tengamos en cuenta el error por las dudas

Veamos si a alguien le sucede lo mismo de forma local y en demo para hacer la corrección necesaria. Gracias Agos!

2025-01-22 19:09 UTC, negro89 approved these changes
Recordar antes de mergear:
1. reemplazar el style="..." por class="ml-5" (buena practica)
2. borrar de la linea 24 _{{turno.estado}}_ que está hace tiempo seguramente por error

2025-01-23 18:17 UTC, merged