MPI - Implementa seleccion editable de obras sociales
andes/app pull request #3125
Opened 2024-12-11 17:07 UTC by ma7payne

### Requerimiento
 
https://proyectos.andes.gob.ar/browse/MPI-399

### Funcionalidad desarrollada 

1. Visualización de Obras Sociales (PUCO): se muestra el listado actual de OS provenientes de PUCO como datos de solo lectura. 
2. Tab para Gestión de Obras Sociales: se agregó un tab en el módulo MPI para la gestión de OS del paciente.
3. Se crea un input para indicar que el selector esta en modo EDITABLE.
4. Selector de Obras Sociales: se implementó un selector que obtiene OS desde la colección obraSocial, excluyendo las registradas en PUCO. 
5. Gestión Manual de OS Declaradas: se permite agregar, modificar y eliminar OS manualmente.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [x] Si
- [ ] No

### Requiere actualizaciones en andes-test-integracion

- [ ] Si
- [x] No

2024-12-17 14:25 UTC, AgosLizzi requested changes
Si nos vamos al tab de "datos de contacto" tenemos al botón agregar de esta manera:
![image](https://github.com/user-attachments/assets/3a6e8f0a-caa5-4f2f-b8cb-2f96bb513ec7)
Tal vez estaría bueno replicar.

- Si **obras sociales del paciente**  y  **financiadores** van a funcionar como listado, se podría agregar un list?

2024-12-17 18:33 UTC, ma7payne commented
> Si nos vamos al tab de "datos de contacto" tenemos al botón agregar de esta manera: ![image](https://private-user-images.githubusercontent.com/72876985/396531160-3a6e8f0a-caa5-4f2f-b8cb-2f96bb513ec7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NTU2ODUsIm5iZiI6MTczNDQ1NTM4NSwicGF0aCI6Ii83Mjg3Njk4NS8zOTY1MzExNjAtM2E2ZThmMGEtY2FhNS00ZjJmLWI4Y2ItMmY5NmJiNTEzZWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDE3MDk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0ZGE2ZjY1MDg5YWU0ZTYzMGMzODhhYmYxOWI0MzM5ODMwOTk2MDM1NjcwZGZlNjc3MzI1ODNmY2ZjNDg2NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2TSJNrIPF9raOUma3IOWkLx6Jobz82Jma0P7nQJy48A) Tal vez estaría bueno replicar.
> 
> * Si **obras sociales del paciente**  y  **financiadores** van a funcionar como listado, se podría agregar un list?

Listo el cambio a plex-list y del botón solo con ícono. También agrego una opción para deshabilitar el campo de selección si es que no se recuperaron las obras sociales.
![image](https://github.com/user-attachments/assets/cdccb371-91df-400f-b9c3-793d228addef)

2024-12-26 15:39 UTC, AgosLizzi reviewed
Loa cambios los veo bien. Consulta, se puede agregar más de un financiador? probando nuevamente el pr me di cuenta que al agregar otro financiador directamente me cambia el que ya tengo en el listado. Tal vez esta acción es correcto, por eso consulto
Te dejo video:
https://www.loom.com/share/54e97546ee054749ba908b6dd1055e56

2025-01-10 15:15 UTC, MarianoCampetella requested changes

2025-02-07 14:07 UTC, AgosLizzi approved these changes

2025-02-12 17:56 UTC, JuanIRamirez commented
Error paisActual y paisActual[0].nombre -> nulo
![image](https://github.com/user-attachments/assets/0aeb68ce-76e6-458c-969e-35d5f51849c5)
![image](https://github.com/user-attachments/assets/59625282-b76d-45c3-8bf2-a995431df0f8)

2025-02-20 15:26 UTC, negro89 commented
Segun charlamos hoy 20/02 la idea sería ..
1. que el paciente pueda declarar mas de un financiador
2. probar desde los distintos lugares de andes en donde el usuario puede seleccionar un financiador (dacion de turnos, internacion, etc) si queda funcionando todo ok sin replantear funcionalidad en estos puntos
3. si el punto 2 queda ok entonces pensar una nueva tarea para extender selección de financiador de manera que el select muestre solo las declaradas por el paciente (en lugar de todas como está actualmente) y en caso de ser necesario poder editar

registrese, comuniquese y archivese 🤭

2025-02-24 18:29 UTC, JuanIRamirez approved these changes
OK

2025-03-06 17:51 UTC, ma7payne commented
> Segun charlamos hoy 20/02 la idea sería ..
> 
> 1. que el paciente pueda declarar mas de un financiador
> 2. probar desde los distintos lugares de andes en donde el usuario puede seleccionar un financiador (dacion de turnos, internacion, etc) si queda funcionando todo ok sin replantear funcionalidad en estos puntos
> 3. si el punto 2 queda ok entonces pensar una nueva tarea para extender selección de financiador de manera que el select muestre solo las declaradas por el paciente (en lugar de todas como está actualmente) y en caso de ser necesario poder editar
> 
> registrese, comuniquese y archivese 🤭

Se subieron los cambios que corresponden a estos 3 puntos, teniendo en cuenta los comentarios de @MarianoCampetella  y @AgosLizzi

2025-03-07 13:09 UTC, MarianoCampetella approved these changes

2025-03-07 19:10 UTC, merged